- targets/TARGET_Silicon_Labs/TARGET_EFM32/TARGET_EFM32GG_STK3700/device/TOOLCHAIN_GCC_ARM/efm32gg.ld
- targets/TARGET_Silicon_Labs/TARGET_EFM32/TARGET_EFM32GG_STK3700/device/TOOLCHAIN_GCC_ARM/startup_efm32gg.S
- targets/TARGET_Silicon_Labs/TARGET_EFM32/TARGET_EFM32GG_STK3700/device/cmsis_nvic.c
- targets/TARGET_Silicon_Labs/TARGET_EFM32/TARGET_EFM32GG_STK3700/device/cmsis_nvic.h
- targets/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_system.c
This PR adds support for uVisor to the EFM32GG target.
Changes:
* Linker script and startup file, as documented by [the uVisor porting guide](https://github.com/ARMmbed/uvisor/blob/master/docs/core/PORTING.md).
* Apply NVIC virtualization (backwards-compatible when uVisor is not present).
* Use `SECURE_ACCESS()` APIs to read/write from the device ROM table at startup time. Those APIs map to a regular memory access when uVisor is not present.
@sg- @0xc0170 @meriac @Patater
> EFM32GG: Add support for uVisor

- targets/TARGET_STM/TARGET_STM32F4/TARGET_UBLOX_EVK_ODIN_W2/device/TOOLCHAIN_ARM_STD/startup_stm32f439xx.S
- targets/TARGET_STM/TARGET_STM32F4/TARGET_UBLOX_EVK_ODIN_W2/objects.h
- targets/targets.json
Enabled TRNG functionality for UBLOX_EVK_ODIN_W2 target the same way as:
https://github.com/ARMmbed/mbed-os/pull/2611
Tested the same way as done for https://github.com/ARMmbed/mbed-os/pull/2611 for ARM and GCC_ARM.
@screamerbg
@0xc0170
> Enabled TRNG functionality for UBLOX_EVK_ODIN_W2 target.

- targets/TARGET_STM/TARGET_STM32F4/i2c_api.c
- Remove waiting for `BTF` flag in `i2c_stop()`
- Delay clock enabling until pins are configured
- Move initialization of `handle->Instance` to function `i2c_reset()`
**READY**
> Make (synchronous) I2C work again

- tools/options.py
- tools/utils.py
--profile can be used with just a profile name eg. default, debug as
long as <name>.json file is in default profile directory.
**READY**
NO
CC: @0xc0170 @theotherjimmy @bridadan
> Accept profile name as well as file path for tools/make.py --profile

- tools/memap.py
This reverts commit 8f9f4eefed50a60eac2f4b7004381a843f334cc2 since it broke memory map info for IAR, ARMCC and on windows, GCC_ARM.
> Revert "Allow max-depth specification in memap"

- features/netsocket/nsapi_dns.cpp
Fix DNS query behavior: don't query more servers if we got reply, make sure the return value is correct.
**READY**
NO
https://github.com/ARMmbed/mbed-os/pull/2963
@kjbracey-arm @0xc0170
> DNS: Revork DNS query

- tools/export/iar/iar_definitions.json
Adds support for nrf52_dk in IAR. Solves https://github.com/ARMmbed/oob-mbed-os-example-blinky/issues/4#issuecomment-252595498
@0xc0170
> NRF52_DK support for IAR exporter

- tools/toolchains/gcc.py
Use newlib nano for targets which have the key "default_lib" set to "small". Also support the legacy key of "default_build".
> Properly set flags for default_lib = small

- features/FEATURE_LWIP/lwip-interface/emac_lwip.c
- features/FEATURE_LWIP/lwip-interface/emac_stack_lwip.cpp
- features/netsocket/emac_stack_mem.h
- hal/hal/emac_api.h
Fix for the issue #2993, do not use ``platform.h`` in the C files.
**READY**
Tested defining EMAC for one platform and  see if DEVICE_ it's properly defined and the code is compiled.
@pan-
> lwip-interface: fix issue #2993

- targets/TARGET_STM/TARGET_STM32F3/TARGET_NUCLEO_F303ZE/PeripheralPins.c
READY
OS2 and OS5 tests are still all OK
> NUCLEO_F303ZE: Enable all I2C instances

- targets/TARGET_STM/TARGET_STM32L1/TARGET_XDOT_L151CC/objects.h
PR #2888 broke the build for the XDOT_L151CC. It looks like it was missed in the PR. This should fix the build and allow CI to complete for other PRs
Since you submitted #2888, would you be able to review this please @LMESTM?
**READY**
NO
> Remove shared spi_s struct from XDOT_L151CC

- targets/TARGET_STM/TARGET_STM32F4/TARGET_UBLOX_EVK_ODIN_W2/sdk/wifi_emac/wifi_emac_api.cpp
Fixed the emac_interface_t struct so that the struct constructor is not used.
We can not rely on the struct constructor to be run since wifi_emac_get_interface can be run from the OdinWiFiInterface constructor before that.
Only one basic test have been done for this i.e. verified that the application run as expected for GCC_ARM:
https://github.com/ARMmbed/oob-mbed-os-example-wifi
NO
https://github.com/ARMmbed/oob-mbed-os-example-wifi/issues/10
> Fixed the emac_interface_t struct for wifi_emac_api.cpp

- tools/export/iar/ewp.tmpl
Remove K64F macros from IAR template.  This was an oversight missed after copying progen's template file https://github.com/project-generator/project_generator/blob/master/project_generator/templates/iar.ewp#L173. 
Fixes https://github.com/ARMmbed/mbed-os/issues/3026
**READY**
> Remove k64f defines from IAR templates

- tools/build_api.py
- tools/memap.py
- tools/test_api.py
- tools/toolchains/__init__.py
**tl;dr:** the linking step of building tests now respects the `-j` flag, so it can be parallelized to make building tests faster.
This uses similar code that is used withing the toolchains when compiling to parallelize the linking process of all the tests across the available CPUs.
To prevent interleaving of build output, I had to modify how the toolchains handle the `silent` parameter. @screamerbg or @theotherjimmy if this will cause issues, please let me know and I will add a different parameter to stop the printing from occurring.
Some brief numbers, cuz who doesn't like numbers :)
Before parallelization, building all tests for the K64F with GCC_ARM on our "Build beast" CI machine took **~45 seconds**, with almost 40 seconds of that taken up by the linking stage.
After …
> [tools] Parallel building of tests

- tools/tests.py
In my previous pull request (https://github.com/ARMmbed/mbed-os/pull/2727),
I forgot to remove all the duration time with a value inferior than the default value...
READY
> Increase serial init timeout value

- TESTS/mbed_drivers/lp_timeout/main.cpp
- TESTS/mbed_hal/lp_ticker/main.cpp
Since deepsleep() may shut down the UART peripheral, I added a wait for 10ms to allow for hardware serial buffers to completely flush.
This should be replaced with a better function that checks if the hardware buffers are empty. However, such an API does not exist now, so I'm using the wait_ms() function for now.
Should resolve some of the issues discussed here: https://github.com/ARMmbed/mbed-os/pull/2966
**READY**
NO
FYI @sg- and @mmahadevan108
> [tests] Waiting before call to deepsleep to allow buffers to flush

- features/unsupported/tests/mbed/digitalin_digitalout/main.cpp
- features/unsupported/tests/mbed/digitalinout/main.cpp
- features/unsupported/tests/mbed/interruptin/main.cpp
- tools/tests.py
Make digital_loop OS2 tests available for all STM32 targets
READY
Tests OK
> digital_loop tests update for STM32

- targets/TARGET_ONSEMI/TARGET_NCS36510/swversion.c
- targets/targets.json
- tools/export/iar/iar_definitions.json
This fixes issue:
https://github.com/ARMmbed/mbed-os/issues/3025
add ncs36510 exporter support for IAR
it exports successfully and builds in IAR.
NO
n/a
branch | PR
n/a
n/a
NCS36510 requires extra settings in IAR to add a few macros and the post build script stuff.  I am working with ON Semi to get the steps added to their platform page.  contact me for details.
mbed export -m NCS36510 -i IAR
> add ncs36510 exporter support for IAR

- targets/TARGET_NORDIC/TARGET_NRF5/serial_api.c
- targets/targets.json
Introduce serial flow control API implementation for Nordic's nRF5 targets (NRF51_DK & NRF52_DK).
Provided implementation for method SerialBase:set_flow_control().
> [nRF5] - added implementation of API of serial port flow control configuration.

- features/FEATURE_LWIP/lwip-interface/lwip_stack.c
Corrected lwip TCP socket accept to correctly convert remote ipv6 address to nsapi ipv6 address.
READY
NO
None
None
None
> Corrected lwip TCP socket accept ipv6 address conversion

- tools/export/cdt/__init__.py
Give a name to the Eclipse exporters that differs from the Make exporters.
Further, remove an pair extraneous relpath computations.
**READY**
**REQUIRED FOR ONLINE COMPILER**
None
> Exporters - Name the eclipse exporters and remove relpath computations

- targets/TARGET_RENESAS/TARGET_RZ_A1H/device/cmsis_nvic.h
- targets/TARGET_RENESAS/TARGET_VK_RZ_A1H/device/cmsis_nvic.h
Add cmsis.h inclusion in cmsis_nvic header file for Cortex-A9 device which was missing.
This was found in OoB test RC3.
https://github.com/ARMmbed/oob-mbed-os-example-client/issues/1
> [TARGET_RENESAS] Add cmsis.h inclusion

- targets/TARGET_STM/TARGET_STM32F0/gpio_irq_api.c
- targets/TARGET_STM/TARGET_STM32F0/pinmap.c
- targets/TARGET_STM/TARGET_STM32F1/gpio_irq_api.c
- targets/TARGET_STM/TARGET_STM32F1/pinmap.c
- targets/TARGET_STM/TARGET_STM32F2/gpio_irq_api.c
- targets/TARGET_STM/TARGET_STM32F2/pinmap.c
- targets/TARGET_STM/TARGET_STM32F3/gpio_irq_api.c
- targets/TARGET_STM/TARGET_STM32F3/pinmap.c
- targets/TARGET_STM/TARGET_STM32F7/gpio_irq_api.c
- targets/TARGET_STM/TARGET_STM32F7/pinmap.c
- targets/TARGET_STM/TARGET_STM32L0/gpio_irq_api.c
- targets/TARGET_STM/TARGET_STM32L0/pinmap.c
- targets/TARGET_STM/TARGET_STM32L1/gpio_irq_api.c
- targets/TARGET_STM/TARGET_STM32L1/pinmap.c
- targets/TARGET_STM/TARGET_STM32L4/gpio_irq_api.c
- targets/TARGET_STM/TARGET_STM32L4/pinmap.c
This is a fix for all STM32 families for reported issue #2638.
The pull-up / pull-down was over-writtent in case irq API was called after pinmap one.
READY
Tests ok - no regression seen - all families tested
[Nonreg_FixPullOverwrite.xlsx](https://github.com/ARMmbed/mbed-os/files/535526/Nonreg_FixPullOverwrite.xlsx)
Also the test reported in the issue runs fine on all tested boards when the fix is applied
> Fix stm32 pull overwrite

- tools/export/makefile/Makefile.tmpl
It just tells the user that they need srec_cat to build when they need it.
**READY**
> [Exporters] Add quick print to the makefile when srec_cat is required

- targets/TARGET_STM/TARGET_STM32F4/TARGET_F429_F439/device/TOOLCHAIN_IAR/stm32f429xx_flash.icf
Increase the IAR heap size from 48KiB to 64KiB. This give enough heap space to run the TLS encryption examples.
> NUCLEO_F429 - Increase IAR heap size

- tools/export/sw4stm32.py
SW4STM32 exporter used to traceback. Now it does not.
**READY**
> [exporters] Fix traceback in SW4STM32 from incorrect use of core

- tools/export/iar/ewd.tmpl
it seems that using the old version of the ewd (debug project file) would cause IAR to replace the debug info with a standard template. I have replaced the ewd template with one generated from 7.70.1 and now all of the IAR targets (that build) are debugging with the right adapter set
**READY**
https://github.com/ARMmbed/oob-mbed-os-example-tls/issues/21
> Exporters - Update the IAR debug template to version 7.70.1

- tools/export/makefile/Makefile.tmpl
- tools/export/makefile/__init__.py
In an unlikely corner-case, the make exporter would generate a bad name for a library. This should fix that incorrect naming.
**READY**
Resolves https://github.com/ARMmbed/oob-mbed-os-example-blinky/issues/20
> [Exporters] Use correct names for library files in makefile exporter

- features/mbedtls/importer/adjust-config.sh
- features/mbedtls/inc/mbedtls/config.h
Add preprocessor checks to mbed TLS through the importer scripts to ensure that compilation fails for targets that attempt to use SSL or entropy, but these are not supported by the target.
READY
NO
This causes build errors while trying to build applications that require SSL or entropy sources but the target does not support it.
> Add checks for NULL_ENTROPY and SSL_TLS in mbed OS

- tools/export/iar/__init__.py
For uVision and IAR, the `Exporter` class contains a `build` method that allows you to use the IDE's build system. Currently, uVision uses a parallel build that uses all available CPUs but IAR only uses one CPU. 
This PR adds a `jobs` a parameter to the `build` method. It defaults to using all available CPUs with the option limit the number of CPUs used.
Since IAR doesn't accept an "auto detect" value for CPUs (for uVision the value is `0`), I used the Python `multiprocessing` library to detect the number CPUs available, which is then passed to the IAR build system.
This will help speed up the exporter tests in CI, thus making it easier for us to make sure exporters aren't broken by changes :smile: 
**READY**
If this PR changes any APIs or behaviors, give a short description of what *API …
> [tools + tests] Adding parallelized build option for iar and uvision exporters

- targets/TARGET_NORDIC/TARGET_NRF5/gpio_api.c
A gpioe pin might have been uninitialized badly for a new settings - should been uninitialized for an old     settings.
> [nrf5] fix in Digital I/O : a gpioe pin was uninitialized badly

- targets/TARGET_ONSEMI/TARGET_NCS36510/clock.h
- targets/TARGET_ONSEMI/TARGET_NCS36510/gpio_api.c
- targets/TARGET_ONSEMI/TARGET_NCS36510/gpio_irq_api.c
- targets/TARGET_ONSEMI/TARGET_NCS36510/ncs36510Init.c
- targets/TARGET_ONSEMI/TARGET_NCS36510/pinmap.c
- targets/TARGET_ONSEMI/TARGET_NCS36510/serial_api.c
- targets/TARGET_ONSEMI/TARGET_NCS36510/trim_map.h
> InterruptIn changes in NCS36510 HAL.

- events/Event.h
Remove unused variable warning in ndebug builds.
The id variable in `Event::call` is only used to assert that the posting of the event succeeded. In non-debug builds, there is no assert, causing a warning on unused variable.
> events - Remove unused variable warning in ndebug builds

- TESTS/netsocket/ip_parsing/main.cpp
- features/netsocket/SocketAddress.cpp
Thanks to @EduardPon for hunting this down:
> In the function ipv6_from_address(), address values of IPv6 address after a :: is found are moved to the end of the short[] array. But the source memory of the moved part should also be cleared with zeros before the address values in front of the :: are copied. In the current implementation this may lead to an invalid address conversion. 
fixes #2931
> nsapi - Fix leftover bytes from suffix during ipv6 parsing

- targets/TARGET_STM/TARGET_STM32F1/TARGET_BLUEPILL_F103C8/device/hal_tick.c
- targets/TARGET_STM/TARGET_STM32F1/TARGET_NUCLEO_F103RB/device/hal_tick.c
- targets/TARGET_STM/TARGET_STM32F1/us_ticker.c
The reading of the Timer master value was not done correctly. Apply same method as done in STM32F0. This should fix the issue #2910
READY
No
None
> STM32F1: Correct timer master value reading

- targets/targets.json
Add LOWPOWERTIMER capability for NUCLEO_F303ZE
READY
Tests are OK:
| NUCLEO_F303ZE-GCC_ARM | NUCLEO_F303ZE | tests-mbed_hal-lp_ticker | 1ms lp_ticker          | 1      | 0      | OK     | 0.04               |
| NUCLEO_F303ZE-GCC_ARM | NUCLEO_F303ZE | tests-mbed_hal-lp_ticker | 1s lp_ticker           | 1      | 0      | OK     | 1.04               |
| NUCLEO_F303ZE-GCC_ARM | NUCLEO_F303ZE | tests-mbed_hal-lp_ticker | 1s lp_ticker deepsleep | 1      | 0      | OK     | 1.07               |
| NUCLEO_F303ZE-GCC_ARM | NUCLEO_F303ZE | tests-mbed_hal-lp_ticker | 1s lp_ticker sleep     | 1      | 0      | OK     | 1.05               |
| NUCLEO_F303ZE-GCC_ARM | NUCLEO_F303ZE | tests-mbed_hal-lp_ticker | 500us lp_ticker        | 1      | 0      | OK     | 0.04               |
| …
> Add LOWPOWERTIMER capability for NUCLEO_F303ZE

- features/unsupported/fs/sd/SDFileSystem.cpp
- features/unsupported/fs/sd/SDFileSystem.h
+ Added ``void debug(bool dbg)`` method to allow enabling/disabling
serial debug at runtime.
+ Replaced calls to ``debug`` with ``debug_if`` to prevent messges
from being thrown via serial when debug is disabled.
**READY**
NO
1. Create a SDFileSystem instance ``sd``, do not inset card.
2. Try to create a file at the root directory. Error messages **should not** be thrown over serial interface.
3. Issue ``sd.debug(true)`` command.
4. Try to create a file at the root directory. Error messages **should** be thrown over serial interface..
Signed-off-by: Bruno Monteiro Pires <brunomonteiropires@gmail.com>
> [SDFileSystem] Enable / Disable serial debug.

- requirements.txt
- tools/arm_pack_manager/__init__.py
PyCURL was causing issues, see #3095 
Turns out this was a < 15min fix.
**READY**
@ohagendorf
> Arm-Pack-Manager Remove pycurl dependency

- targets/TARGET_ONSEMI/TARGET_NCS36510/device/TOOLCHAIN_ARM/NCS36510.sct
- targets/TARGET_ONSEMI/TARGET_NCS36510/device/TOOLCHAIN_ARM/startup_NCS36510.s
Notes:
Recovers 4K of precious RAM. Valid only for ARMCC. Similar fixes should be done to GCC and IAR too.
YES | NO
branch | PR
Outline the steps to test or …
> OnSemi RAM usage fix

- targets/TARGET_STM/TARGET_STM32F3/serial_api.c
When DEVICE_SERIAL_ASYNCH is defined during compile of an STM32F3 target, SerialBase::write() for UART4 and UART5 can't be used because UART4 and UART5 were referenced in serial_api.c as USART4 and USART5 but the real defines were created using UART4 and UART5 names.
READY
NO
None
None
None
Create a build for an STM32F3 based target device and define DEVICE_SERIAL_ASYNCH.
Create a Serial object using pins associated with UART4 or UART5.
Attempt to use the write() member function to transmit data using an IRQ.
Nothing gets transmitted and transmit complete event is never generated because the IRQ to use was not determined due to the bug.
> STM32F3: Correct UART4 and UART5 defines when using DEVICE_SERIAL_ASYNCH

- features/FEATURE_LWIP/lwip-interface/lwip_stack.c
- features/netsocket/NetworkInterface.cpp
- features/netsocket/NetworkInterface.h
- features/netsocket/NetworkStack.cpp
- features/netsocket/NetworkStack.h
- features/netsocket/SocketAddress.cpp
- features/netsocket/SocketAddress.h
- features/netsocket/nsapi_dns.cpp
- features/netsocket/nsapi_types.h
Standardize support of NSAPI_UNSPEC (renamed to NSAPI_IP_NONE)
Introduced in https://github.com/ARMmbed/mbed-os/pull/2767
- Renamed to NSAPI_IP_NONE for consistency with other enums
- Reordered nsapi_version_t to make defaule nsapi_addr_t NSAPI_IP_NONE
- Added support to NSAPI_IP_NONE in SocketAddress
cc @sg-, @c1728p9, @kjbracey-arm, @mikaleppanen
> nsapi - Standardize support of NSAPI_UNSPEC

- features/unsupported/tests/mbed/analog/main.cpp
- tools/tests.py
Make analog_loop OS2 tests available for all STM32 targets
READY
Tests OK
> analog_loop tests update for STM32

- targets/targets.json
This platform currently fails to build for mbed 2 due to the mbedtls dependency. We remove it until it's fixed. I'll create a tracking issue soon.
Error:
```
\targets\TARGET_NUVOTON\TARGET_NUC472\crypto\aes\aes_alt.c:25:28: fatal error: mbedtls/config.h: No such file or directory
#include "mbedtls/config.h"
```
@cyliangtw @adbridge
> Targets- NUMAKER_PFM_NUC47216 remove mbed 2

- tools/make.py
That let us to ignore build failures for examples on not supported
platforms.
**READY**
CC: @bridadan @adbridge
> Handle [NOT_SUPPORTED] exception in make.py

- features/frameworks/greentea-client/source/test_env.cpp
This change prevents the standard library from allocating a large buffer on the heap. On GCC_ARM, this is a saving of 1K in the most basic example (modified blinky). On ARM, this is a saving of 64 bytes.
**READY**
NO
You can turn on runtime heap stat tracking by running the following commands:
```
mbed test --compile -m <TARGET>-t <TOOLCHAIN> -DMBED_HEAP_STATS_ENABLED=1 -DMBED_STACK_STATS_ENABLED=1
mbed test --run -m <TARGET>-t <TOOLCHAIN> -v
```
> [tests] Replacing getchar with RawSerial getc in greentea-client

- targets/TARGET_STM/TARGET_STM32F0/can_api.c
Fix issue #2987 
Bug fix is completely implemented for STM32F0 and has been tested on STM32F072 Nucleo board.
No APIs are changed, but the behavior of the STM32F0 CAN filter API behaves now as it would be expected.
- Check Reference Manuals of other MCUs from STM32 family if register layout is the same as F0 MCU. If yes, same issue will exist for other STM32 targets supporting CAN.
No changes in build environment.
Try to set a CAN message filter with the previous version and wonder why it filters random message IDs, just not the ones you want to be filtered.
> Update of can_api.c fixing #2987

- tools/export/iar/iar_definitions.json
The IAR definition for the NCS36510 is not up to date for IAR Embedded Workbench v7.8. This patches the definition.
@maclobdell This will probably affect you, will you please test these changes/check with ONSemiconductor?
**READY**
NO
> Updating IAR definition for the NCS36510 for IAR EW v7.8

- TESTS/mbedmicro-mbed/cpp/main.cpp
The `tests-mbedmicro-mbed-cpp` test was causing issues on some platforms because the serial output would get garbled and cause exceptions to occur in the testing tools when using the reporting functionality. This corrects the behavior to follow the other tests. It will now defer all printing until after the `__sync` event occurs.
I've also made a PR against Greentea to scrub these 'unprintable' characters from the log to prevent the traceback: https://github.com/ARMmbed/greentea/pull/200
**READY**
NO
Using commit 8a9a2463563af3ffb8d289905d3f7073a46ecc80 of mbed-os, run the following commands:
```
mbed test --compile -m NCS36510 -t GCC_ARM -n tests-mbedmicro-mbed-cpp …
```
> [tests] Preventing test from printing before Greentea __sync

- features/storage/FEATURE_STORAGE/cfstore/source/cfstore_svm.cpp
Removed static declaration for the StorageVolumeManager in the CFStore. The StorageVolumeManager must be accessible to all users of the region covered by the manager.
Also added define guards to the CFStore size and location so that these can be changed in the configuration file and not hard coded.
> CFStore fix needed for the Cloud Client

- features/FEATURE_LWIP/lwip-interface/lwip-eth/arch/TARGET_Freescale/k64f_emac.c
This is hopefully a fix for #3118, where @infinnovation put in a lot of work in tracking down the exact problem.
This was actually several bugs colluding together.
1. Confusion on the buffer-semaphore paradigm used led to misuse of the tx semaphore and potential for odd behaviour.
2. Equality tests on `tx_consume_index` and `tx_produce_index` did not handle overflow correctly. This would allow `tx_consume_index` to catch up to `tx_produce_index` and trick the `k64f_rx_reclaim` function into forgetting about a whole buffer of pbufs.
3. On top of all of that, the `ENET_BUFFDESCRIPTOR_TX_READ_MASK` was not correctly read immediately after being set due to either a compiler optimization or hardware delays. This caused `k64f_low_level_output` to eagerly overrun existing buff-descriptors before …
> lwip - Fix memory leak in k64f cyclic-buffer overflow

- tools/test/examples/examples.json
- tools/test/examples/examples.py
- tools/test/examples/examples_lib.py
- tools/test/examples/update.py
> Make update.py test compile examples prior to updating mbed-os version.

- features/FEATURE_LWIP/lwip-interface/lwip-sys/arch/cc.h
- features/FEATURE_LWIP/lwip-interface/lwip/src/core/lwip_pbuf.c
- features/netsocket/SocketAddress.cpp
Clean up warnings in network code
```
- cc.h@57,1: "BYTE_ORDER" redefined
- lwip_inet_chksum.c@560,44: passing argument 1 of 'thumb2_checksum'
discards 'const' qualifier from pointer target type
- lwip_pbuf.c@1172,9: variable 'err' set but not used
- SocketAddress.cpp@293,1: control reaches end of non-void function
```
cc @c1728p9, @kjbracey-arm
> lwip/nsapi - Clean up warnings in network code

- features/netsocket/NetworkStack.cpp
Add better heuristic for the default record of DNS queries.
Takes advantage of the get_ip_address function to predict the IP address version wanted by the underlying interface. The should avoid the need for most IPv6 interfaces to overload gethostbyname.
suggested by @kjbracey-arm
previous discussion https://github.com/ARMmbed/mbed-os/issues/3145
should resolve https://github.com/ARMmbed/mbed-os/issues/3145
> nsapi - Add better heuristic for the default record of DNS queries

- targets/targets.json
Add a device name field for the microbit so that its target information may be picked up from CMSIS description files, and it can be used in export.
**READY**
`mbed export -m nrf51_microbit -i uvision5`
@0xc0170 @screamerbg @jaustin
> [Exporters] Add a device_name to microbit entry in targets.json

- features/unsupported/tests/mbed/i2c_master_slave/main.cpp
- features/unsupported/tests/mbed/i2c_master_slave_asynch/main.cpp
- tools/tests.py
Make i2c_loop OS2 tests available for all STM32 targets
Note that I could remove mcu list in the tests.py file as other boards than STM32 one were not defined in the test main.cpp file...
READY
Our test bench is already connected with that configuration
Tests have been done with all STM32 families
> i2c_loop tests update for STM32

- docs/testing_mbed_OS_5.md
- tools/test.py
Before, `mbed_app.json` files were explicitly ignored when building tests.
This was mostly because you could have multiple `mbed_app.json` files in the
tree (for instance, in test case folders) and the behavior would be
undefined. Now the tools explicitly ensure that there aren't multiple
`mbed_app.json` files in your source files. So auto discovery of
`mbed_app.json` for testing is being reintroduced.
**ON HOLD (pending review)**
If this PR changes any APIs or behaviors, give a short description of what _API users_ should do when this PR is merged.
YES
If you relied on the behavior of `mbed_app.json` being ignored when building tests, this is a breaking change.
FYI @BlackstoneEngineering and @screamerbg
> Allowing mbed_app.json files to be discovered for tests.

- features/FEATURE_LWIP/lwip-interface/lwipopts.h
- features/FEATURE_LWIP/lwip-interface/mbed_lib.json
The file lwipopts.h defines various values configuring the lwIP library. These were chosen with quite small values, presumably to allow basic functionality but with a modest RAM footprint suitable for an embedded platform.
Depending on the application or target platform, a user may wish to modify the values, for example to allow more than 4 sockets open at once.  The principal values are made available to the configuration system, with information on the RAM penalty from increasing them.
**READY**
NO
Reworking of #2550, rebased.
> lwip: Allow several configuration macros to be set externally (bis)

- features/nanostack/FEATURE_NANOSTACK/nanostack-interface/NanostackInterface.cpp
To resolve #3146, add checks to APIs that the address passed in is IPv6.
Other improvements while touching this area:
* Allow binding to a specific address (previously address was ignored).
* Remove no-longer-needed address binary<->string conversions.
> Add address type checks to NanostackInterface

- features/netsocket/nsapi_dns.cpp
Replace Comodo and OpenDNS IPv4 servers with Google and DNS.WATCH IPv6
servers, so IPv6-only devices (eg 6LoWPAN) have a default.
3 IPv4 resolvers should be plenty - existing code doesn't remember which
one last worked, so if early list entries were unreachable performance
would be consistently bad anyway. Replacing two entries avoids
increasing image size and RAM consumption.
For this to fully work with Nanostack, #3146 needs to be fixed - Nanostack is currently attempting to send to the IPv4 resolvers. (Other socket providers like the Wifi module may need equivalent checks to not interpret an IPv6 address as IPv4.)
@SeppoTakalo, @geky, @c1728p9, @mikaleppanen
> nsapi_dns: Provide 2 IPv6-hosted default servers

- .travis.yml
- tools/project.py
- tools/utils.py
Printing too large of a string can fail in Windows, as detailed here: https://bugs.python.org/issue11395. This works around the problem by adding a print_large_string function that breaks up the string into smaller pieces before printing it.
**READY**
NO
Before this change, `mbed export -S` would fail with the following traceback:
```
File "C:\Users\bridan01\Documents\dev\m_mbed\mbed\tools\project.py", line 244, in <module>
main()
File "C:\Users\bridan01\Documents\dev\m_mbed\mbed\tools\project.py", line 192, in main
print mcu_ide_matrix()
IOError: [Errno 12] Not enough space
[mbed] ERROR: "python" returned error code 1.
[mbed] ERROR: …
```
> [tools] Fixing project.py -S printing problem

- tools/export/__init__.py
- tools/export/cmsis/__init__.py
- tools/export/exporters.py
- tools/export/iar/__init__.py
- tools/export/makefile/__init__.py
- tools/export/uvision/__init__.py
- tools/project.py
- tools/project_api.py
- tools/test/examples/examples.json
- tools/test/examples/examples.py
- tools/test/examples/examples_lib.py
- tools/test/export/build_test.py
Adds additional export-build tests that use subprocess commands `mbed import` and `mbed export`. Additionally, I have revised how exporters store supported targets, and, as a result, how project.py handles unsupported targets. I did this to make supported targets more visible for the new tests.
**READY**
Build tests of any kind require the IDEs executable to be in the path.
In a clean subdirectory of `mbed-os\.build`
`python ..\..\tools\test\examples\examples.py import`
`python ..\..\tools\test\examples\examples.py export iar uvision make_armc5 make_iar make_gcc_arm`
> [Exporters] New export-build tests

- targets/TARGET_Freescale/TARGET_KSDK2_MCUS/TARGET_MCU_K64F/trng_api.c
Notes:
* I agree to [contributer agreement](https://github.com/ARMmbed/mbed-os/blob/master/CONTRIBUTING.md).
Remove one compiler warning in trng_api.c with K64F due to unused variable "ret".
**READY**
NO
None. 
None
Just compile it  -  
```
mbed compile -m K64F -t GCC_ARM  -c
Compile [ 94.6%]: trng_api.c
[Warning] trng_api.c@67,9: unused variable 'ret' [-Wunused-variable]
```
Github issue #3183
> #3183 Compiler warning in trng_api.c with K64F 

- docs/exporters.md
- docs/mbed_targets.md
- tools/export/cmsis/__init__.py
- tools/export/exporters.py
Introduces a new `exporters.md` in the docs folder. Additionally, updates `device_name` documentation in `mbed_targets.json` and adds more docstrings. 
**Ready**
@0xc0170 @sg- @bridadan @theotherjimmy
> Exporter documentation

- tools/export/makefile/__init__.py
**READY**
Before:
```
$ mbed export -i make_gcc_arm -m <any>
[mbed] Auto-installing missing Python modules...
Scan: .
Scan: FEATURE_LWIP
Scan: FEATURE_LOWPAN_ROUTER
Scan: FEATURE_NANOSTACK
Scan: FEATURE_THREAD_END_DEVICE
Scan: FEATURE_THREAD_ROUTER
Scan: FEATURE_THREAD_BORDER_ROUTER
Scan: FEATURE_LOWPAN_BORDER_ROUTER
Scan: FEATURE_NANOSTACK_FULL
Scan: FEATURE_LOWPAN_HOST
File "/home/jimbri01/src/arm-mbed/oob-mbed-os-example-wifi/mbed-os/tools/project.py", line 244, in <module>
main()
File "/home/jimbri01/src/arm-mbed/oob-mbed-os-example-wifi/mbed-os/tools/project.py", line 240, in main
zip_proj=zip_proj, build_profile=profile)
File …
```
> [Export-Make] Use internal class variable for resolving templates in makefiles

- tools/export/iar/__init__.py
- tools/export/makefile/__init__.py
- tools/export/uvision/__init__.py
This transitions all build steps for the exporters to use a combination of the Python `Popen` and `communicate` functions to unify the calling of sub-processes.
It also helps standardize the logging functionality across all the build steps and makes the functions more consistent with each other.
**READY**
NO
> Using Popen for uVision and unifying the structure of the build function

- features/FEATURE_LWIP/lwip-interface/EthernetInterface.cpp
- features/FEATURE_LWIP/lwip-interface/EthernetInterface.h
- features/FEATURE_LWIP/lwip-interface/lwip_stack.c
- features/FEATURE_LWIP/lwip-interface/lwip_stack.h
- features/nanostack/FEATURE_NANOSTACK/nanostack-interface/NanostackInterface.cpp
- features/nanostack/FEATURE_NANOSTACK/nanostack-interface/NanostackInterface.h
- features/netsocket/CellularInterface.h
- features/netsocket/NetworkInterface.cpp
- features/netsocket/NetworkInterface.h
- features/netsocket/NetworkStack.cpp
- features/netsocket/NetworkStack.h
- features/netsocket/Socket.cpp
- features/netsocket/Socket.h
- features/netsocket/TCPServer.cpp
- features/netsocket/TCPServer.h
- features/netsocket/TCPSocket.cpp
- features/netsocket/TCPSocket.h
- features/netsocket/UDPSocket.cpp
- features/netsocket/UDPSocket.h
- features/netsocket/WiFiInterface.h
- features/netsocket/nsapi_dns.cpp
- features/netsocket/nsapi_dns.h
- features/netsocket/nsapi_types.h
- targets/TARGET_STM/TARGET_STM32F4/TARGET_UBLOX_EVK_ODIN_W2/sdk/ublox-odin-w2-drivers/OdinWiFiInterface.h
**Note:** Backwards compatible user API
**Note:** Backwards compatible implementation API
Add standardized return types for size and errors:
```
nsapi_error_t         - enum of errors or 0 for NSAPI_ERROR_OK
nsapi_size_t          - unsigned size of data that could be sent
nsapi_size_or_error_t - either a non-negative size or negative error
```
Unfortunately, compatibility concerns limit this types to signed/unsigned ints. It may be worthwhile in the future to switch these types to stricter variants.
As pointed out by @bulislaw, we should also adopt these types in the interfaces that exist in mbed-os:
from this discusson https://github.com/ARMmbed/mbed-os/pull/2627#r78072433
cc @bulislaw, @kjbracey-arm, @sg-
> nsapi - Add standardized return types for size and errors

- targets/TARGET_RENESAS/TARGET_RZ_A1H/device/vfp_neon_push_pop.h
- targets/TARGET_RENESAS/TARGET_RZ_A1H/us_ticker.c
When the floating-point calculation is executed into the processing which is called from IRQ handlers, VFP register is overwritten.
Therefore, we fixed the issue. we added the process to execute the saving (Push) and the returning (Pop) of VFP register in before and after the appropriate processing.
> Fixed the issue about push/pop of VFP register.

- platform/mbed_wait_api_rtos.cpp
Fix arithmetic error in rtos-based wait
The value of `start` is taken from before that wait call, so the value of `us` shouldn't be changed. This was a simple mistake/fix.
cc @infinnovation, @bogdanm
> Fix arithmetic error in rtos-based wait

- tools/test/examples/examples_lib.py
Exporter build tests  for exporters that have no build function (simplicity, kds, etc) will be tested for their ability to export with no tracebacks.
(Additionally added prettier printing organization for results).
**READY**
> [Exporter tests] Export only 

- mbed.h
Allow compile-time tests on the version of mbed-os to cope with
e.g. API changes across versions.
To distinguish between mbed OS 2 and mbed OS 5, we use the
MBED_CONF_RTOS_PRESENT macro.
Note: mbed OS 2 versioning is 2.0.MBED_LIBRARY_VERSION
This is #3096 rebased against master
> Add mbed OS version macros

- tools/test/examples/examples.py
- tools/test/examples/examples_lib.py
This adds an example clone and deploy step that allows you to modify
each top level repository before pulling in the rest of the example's
dependencies. This allows us to not pull in a copy of mbed-os for each
example in CI and instead symbolic link the already cloned copy, saving
valuable time and disk space
**READY**
NO
These changes are intended mostly for use in CI. Currently importing the examples and their dependencies (including mbed-os for every example) takes upwards of 10 minutes and multiple GBs of disk space. This will both reduce the time and disk space for testing with one common mbed-os revision by allowing you to symbolic link to one specific repository. …
> [example tests] Adding a clone and a deploy step to allow optimizations in CI.

- tools/test/examples/examples.py
- tools/test/examples/examples_lib.py
Allow command line filtering of targets and examples for both compile and export tests.
**READY**
> [Exporter/compile tests] Examples test filters

- tools/export/uvision/__init__.py
Doing an export fails if .hpp files are included, this patch add it to the list of recognized extensions.
```
mbed export -i UVISION5 -m NRF52_DK
File "c:\mbed-project\mbed-os\tools\project.py", line 234, in <module>
main()
File "c:\mbed-project\mbed-os\tools\project.py", line 230, in main
zip_proj=zip_proj, build_profile=profile)
File "c:\mbed-project\mbed-os\tools\project.py", line 93, in export
build_profile=build_profile, silent=silent)
File "c:\mbed-project\mbed-os\tools\project_api.py", line 229, in export_project
macros=macros)
File "c:\mbed-project\mbed-os\tools\project_api.py", line 90, in generate_project_files
exporter.generate()
File "c:\mbed-project\mbed-os\tools\export\uvision\__init__.py", line 189, in generate
'project_files': …
```
> Add .hpp to list of Uvision Exporter extensions

- targets/TARGET_NXP/TARGET_LPC43XX/ethernet_api.c
NUM_TX_FRAG should be used instead of NUM_RX_FRAG, otherwise the tx_end_ring will never be set.
**READY**
NO
> Fix wrong index at LPC43xx tx end ring assignment

- features/netsocket/WiFiInterface.h
Fix WiFi issues pointed in #3236 
**READY**
@0xc0170 @lauri-piikivi 
Closes #3236
> WiFi: Minor fixes to docs and includes

- features/FEATURE_LWIP/TESTS/mbedmicro-net/gethostbyname/main.cpp
- features/netsocket/NetworkStack.cpp
There is a missing check for NSAPI_UNSPEC in gethostbyname, this causes all ip literals to be rejected by default, which is definitely not the correct behaviour. May have been missed since the unspec and ip literal check prs were introduced in parallel.
cc @c1728p9, @kjbracey-arm
> nsapi - Fix missing NSAPI_UNSPEC check in gethostbyname for ip literals

- tools/export/makefile/Makefile.tmpl
Resolves #2962 part B in a way that should be noticable
It looks like this (k64f, no hex file merging):
```
$ make -j 
[SNIP]
Compile: port_api.c
Compile: sleep.c
Compile: i2c_api.c
Compile: rtc_api.c
../mbed-os/targets/TARGET_Freescale/TARGET_KSDK2_MCUS/TARGET_MCU_K64F/drivers/fsl_enet.c: In function 'ENET_SetTxBufferDescriptors':
../mbed-os/targets/TARGET_Freescale/TARGET_KSDK2_MCUS/TARGET_MCU_K64F/drivers/fsl_enet.c:493:29: warning: comparison between pointer and integer
if (txBuffSizeAlign != NULL)
^
link: mbed-os-example-blinky.elf
'arm-none-eabi-objcopy' -O binary mbed-os-example-blinky.elf mbed-os-example-blinky.bin
'arm-none-eabi-objcopy' -O ihex mbed-os-example-blinky.elf mbed-os-example-blinky.hex
===== bin file ready to flash: .build/mbed-os-example-blinky.bin =====
```
OR this …
> [Export - Make] Add message that informs the user which hex to flash

- rtos/RtosTimer.h
The non-irq timer functionality provided by the RtosTimer is now duplicated by the EventQueue.
Added this blurb to the head of RtosTimer.h to help migration:
> The RtosTimer has been superseded by the EventQueue. The RtosTimer and EventQueue duplicate the functionality of timing events outside of interrupt context, however the EventQueue has additional features to handle deferring other events to multiple contexts.
>
> For an example, the following code shows a simple use of the RtosTimer:
> ``` cpp
> DigitalOut led(LED1);
> void blink() {
>     led = !led;
> }
> 
> RtosTimer timer(&blink);
> int main() {
>     timer.start(1000); // call blink every 1s
>     wait_ms(5000);
>     timer.stop(); // stop after 5s
> }
> ```
> 
> This is the above example rewritten to use the EventQueue:
> ``` …
```
> rtos - Mark the RtosTimer class as deprecated

- targets/targets.json
Add I2C_ASYNCH capability for DISCO_F469NI
READY
Loop test can not be executed as there are only 1 I2C available instance by the ARDUINO pin.
But manual test is OK.
> Add I2C_ASYNCH capability for DISCO_F469NI

- targets/TARGET_NUVOTON/TARGET_M451/TARGET_NUMAKER_PFM_M453/device.h
- targets/TARGET_NUVOTON/TARGET_M451/device/TOOLCHAIN_ARM_MICRO/M453.sct
- targets/TARGET_NUVOTON/TARGET_M451/device/TOOLCHAIN_ARM_STD/M453.sct
- targets/TARGET_NUVOTON/TARGET_M451/device/TOOLCHAIN_GCC_ARM/M453.ld
- targets/TARGET_NUVOTON/TARGET_M451/device/TOOLCHAIN_IAR/M453.icf
- targets/TARGET_NUVOTON/TARGET_M451/serial_api.c
- targets/TARGET_NUVOTON/TARGET_NUC472/TARGET_NUMAKER_PFM_NUC472/device.h
- targets/TARGET_NUVOTON/TARGET_NUC472/device/TOOLCHAIN_ARM_MICRO/NUC472.sct
- targets/TARGET_NUVOTON/TARGET_NUC472/device/TOOLCHAIN_ARM_STD/NUC472.sct
- targets/TARGET_NUVOTON/TARGET_NUC472/device/TOOLCHAIN_GCC_ARM/NUC472.ld
- targets/TARGET_NUVOTON/TARGET_NUC472/device/TOOLCHAIN_IAR/NUC472_442.icf
- targets/TARGET_NUVOTON/TARGET_NUC472/serial_api.c
- targets/targets.json
This PR patches for the targets NuMaker-PFM-NUC472 and NuMaker-PFM-M453 and has the following modifications:
1. Fix greentea test failed. This is caused by no support for single UART H/W module shared by multiple serial S/W objects.
1. Reduce interrupt stack size from 12/4 KB to 2 KB.
1. Remove dead code in device.h.
> [NUC472/M453] Support single UART shared by multiple serial objects and other updates

- targets/targets.json
Add I2C_ASYNCH capability for NUCLEO_F410RB
It has wrongly disappeared with https://github.com/ARMmbed/mbed-os/pull/2765
READY
> NUCLEO_F410RB: Add I2C_ASYNCH capability

- features/FEATURE_LWIP/lwip-interface/lwip_stack.c
- features/netsocket/SocketAddress.cpp
1.  Fix lwip_mac_address buffer overflow. 
The size of lwip_mac_address is NSAPI_MAC_SIZE, but in mbed_lwip_set_mac_address(), the max size in snprintf is set to 19. This might overflow the lwip_mac_address buffer.
This patch sets the size of lwip_mac_address to NSAPI_MAC_SIZE + 1, and sets snprintf limit to NSAPI_MAC_SIZE.
2. netsocket - Fix set_ip_bytes out-of-bound access
set_ip_bytes() does a 16-byte memcpy from the input buffer to
the local nsapi_addr_t despite the address version.
If the address version is ipv4, the input buffer may only be
4-byte in size. This causes a out-of-bound access on the input buffer.
READY
NO
NONE
> Fix lwip_mac_address buffer overflow and set_ip_bytes out of bound access

- tools/project.py
The tests were assuming that the `hal` directory would contain both target code and common code. After the restructure, the target code lives in targets, so we should scan that too.
**READY**
#3117
> [Exporters] Append targets to scan list for exporting tests

- targets/TARGET_ONSEMI/TARGET_NCS36510/clock_map.h
- targets/TARGET_ONSEMI/TARGET_NCS36510/memory_map.h
- targets/TARGET_ONSEMI/TARGET_NCS36510/ncs36510Init.c
- targets/TARGET_ONSEMI/TARGET_NCS36510/ncs36510_user_trim.json
- targets/TARGET_ONSEMI/TARGET_NCS36510/rfAna_map.h
- targets/TARGET_ONSEMI/TARGET_NCS36510/sleep.c
- targets/TARGET_ONSEMI/TARGET_NCS36510/swversion.c
- targets/TARGET_ONSEMI/TARGET_NCS36510/trim_map.h
- targets/targets.json
- tools/add_fib.py
Adding user trim programming for NCS36510.  Attached is the test result.
[GCC_ARM_TestResults-28-10-2016.txt](https://github.com/ARMmbed/mbed-os/files/558213/GCC_ARM_TestResults-28-10-2016.txt)
> User trim values for NCS36510

- tools/toolchains/__init__.py
If, say, you compile with gcc_arm and kill it at just the right time you will have an empty dependency file. This empty dependency file will cause a python traceback in dependency parsing, preventing you from compiling until you next clean.
This PR lets that weird corner case compile.
**READY**
should resolve #3226 
We can simulate the very precise timing needed to reproduce this bug by simply emptying a `.d` file
1) Run any mbed compile command using gcc_arm in a working project (any target will do).
2) Find any `.d` file for the project (for example I'll use `BUILD/k64f/gcc_arm/main.d`)
3) Run this command, replacing my example file with a file chosen in step 2
```bash
echo -n > BUILD/k64f/gcc_arm/main.d
```
4) Run the mbed compile again to see the failure.
```
...
Scan: mbed
Scan: env …
```
> [Tools - Toolchains] Allow dependency parsing to fail, gracefully continuing

- targets/TARGET_Freescale/TARGET_K20XX/pwmout_api.c
Fix K20xx's PwmOut to calculate pwm clock from the bus clock instead of SystemCoreClock.
**READY**
NO
Build subtarget TARGET_TEENSY3_1 with CLOCK_SETUP defined as 0 and build again as 1. Create a user program setting PwmOut with a 1ms period, 50% duty cycle. Verify clock period with oscilloscope. Without this PR, the CLOCK_SETUP 1 config will produce a 2ms period.
> K20xx Calculate PWM clock relative to bus clock

- features/unsupported/tests/mbed/i2c_slave/main.cpp
Using default Arduino connector pins is easier to use when using this test.
**READY**
Tested with this i2c_slave test
> test i2c slave: use standard Arduino pins for NUCLEO_F411RE

- platform/toolchain.h
Oringinally #3245 by @micromint 
MBED_DEPRECATED macro breaks builds using Keil uVision4. The 'deprecated' attribute does not allow arguments using ARMCC 5.03 on Keil 4.74. Changing #ifdef order reinstates support for Keil uVision4. Tested with Keil 4.74, Keil 5.21 and GCC ARM Embedded 5.4 2016q3.
**READY**
> Change MBED_DEPRECATED def order to support Keil 4

- targets/TARGET_NXP/TARGET_LPC43XX/pwmout_api.c
Makes polarity of the LPC43XX PWM driver consistent with the LPC176X. Also allows override of the PWM mode at compile time by declaring PWM_MODE: 0 = 32-bit, 1 = 16-bit low (default), 2 = 16-bit high
**READY**
> Fix default polarity on LPC43XX PWM driver

- tools/build_api.py
- tools/test_api.py
This PR sets the baudrate in the test spec file (used by Greentea for automated testing) based on the mbed config setting for the stdio default baud rate: https://github.com/ARMmbed/mbed-os/blob/master/platform/mbed_lib.json#L9
There was another patch that was necessary to prevent an issue when getting the config data. Before, the `get_config` function in `build_api.py` was checking the equality of a set and a list. However the list's equality depends on order, so now it is casted it to a set to prevent an infinite loop.
**READY**
NO
FYI @stevew817
> Baudrate in test spec

- tools/test_api.py
When running 'mbed test' inside a virtual machine, I receive the following error:
```
File "C:\ARM\thing\mbed-os\tools\test_api.py", line 2095, in build_test_worker
bin_file = build_project(*args, **kwargs)
File "C:\ARM\thing\mbed-os\tools\build_api.py", line 452, in build_project
resources.inc_dirs)
File "C:\ARM\thing\mbed-os\tools\toolchains\__init__.py", line 807, in compile_sources
return self.compile_queue(queue, objects)
File "C:\ARM\thing\mbed-os\tools\toolchains\__init__.py", line 831, in compile_queue
p = Pool(processes=jobs_count)
File "c:\python27\lib\multiprocessing\__init__.py", line 232, in Pool
return Pool(processes, initializer, initargs, maxtasksperchild)
File "c:\python27\lib\multiprocessing\pool.py", line 159, in __init__ …
```
> Prevent process pool inside of process pool when building tests

- features/netsocket/UDPSocket.cpp
- features/netsocket/UDPSocket.h
Remove assertions on same-thread send/recv
Initially these assertions were added to protected simultaneous send/recv from the same socket when similarly purposed mutexes were removed.
However, simultaneous send/recv can still be useful if the payload is garunteed to be less than the MTU accross the entire connection. A good example is an application that sends small 4-byte updates from
multiple threads/interrupts but uses TCP to handle packet-loss and keep-alive.
related conversation https://github.com/ARMmbed/mbed-os/issues/3058
cc @c1728p9, @kjbracey-arm, @EduardPon
> nsapi - Remove assertions on same-thread send/recv

- platform/mbed_alloc_wrappers.cpp
- platform/mbed_stats.c
- platform/mbed_stats.h
Add clean stats api for stack usage, based on existing api for heap usage.
Returns cumulative values for all stacks to keep the api simple. Stack-specific stats could be added in the future.
Example:
``` cpp
#include "mbed_stats.h"
DigitalOut led1(LED1);
// main() runs in its own thread in the OS
// (note the calls to Thread::wait below for delays)
int main() {
for (int i = 0; i < 5; i++) {
led1 = !led1;
Thread::wait(500);
}
mbed_stats_heap_t heap_stats;
mbed_stats_heap_get(&heap_stats);
mbed_stats_stack_t stack_stats;
mbed_stats_stack_get(&stack_stats);
printf("------ stats ------\n");
printf("heap current size: %ld\n", heap_stats.current_size);
printf("heap max size: %ld\n", heap_stats.max_size);
printf("heap total size: %ld\n", heap_stats.total_size);
printf("heap …
```
> stats - Add cleaner stats API for stack usage

- features/unsupported/tests/mbed/i2c_master_slave_asynch/main.cpp
- targets/TARGET_STM/TARGET_STM32F4/common_objects.h
- targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_i2c.c
- targets/TARGET_STM/TARGET_STM32F4/i2c_api.c
This PR contains rework of F4 I2C driver to move most of the drivers functions to call STM32 cube HAL API instead of direct registers access . 
Because this API is common to all STM32 families, this is a first step towards merging the various (x9) i2c_api.c files into a common file. 
During the rework, other functionalities have been added: like usage of Interrupts as well in sync mode (not visible fro MBED API user), reset of IP in case of error, timeout calculated based on SystemCoreClock and I2C frequency
**READY**
IKS01A1 Hello world has been tested succesfully.
Also non regression tests results available here:
> Dev i2c stm32f4hal

- TESTS/mbed_functional/callback/main.cpp
- platform/Callback.h
This is a fix for a set of bugs related to using inherited member functions.
---
The type deduction for the callback constructors was to strict and prevented implicit casts for the context pointer stored internally.
As noted by @pan-, relaxing the contraints on the templated parameters allows C++ to correctly infer implicit casts such as conversions between child and parent classes when inheritance is
involved.
As an additional benefit, this may help the user experience by defering invalid type errors to when the types are expanded, limiting the number of error messages presented to users.
Also, adopting the same relaxed tpye-deduction in bound functions for consistency provides an alternative solution for the void pointer cast issue, which removes a larg amount of cruft.
---
Github is …
> callback - Relax type-deduction in callback class

- cmsis/core_caFunc.h
In "core_caFunc.c" Renesas added the following API of IAR compiler version.
- __v7_clean_dcache_all()
- __v7_clean_inv_dcache_all()
> Add API which cleans Dcache in IAR compiler.

- features/FEATURE_LWIP/TESTS/mbedmicro-net/gethostbyname/main.cpp
- features/FEATURE_LWIP/TESTS/mbedmicro-net/nist_internet_time_service/main.cpp
- features/FEATURE_LWIP/TESTS/mbedmicro-net/tcp_client_echo/main.cpp
- features/FEATURE_LWIP/TESTS/mbedmicro-net/tcp_client_hello_world/main.cpp
- features/FEATURE_LWIP/TESTS/mbedmicro-net/udp_echo_client/main.cpp
- targets/targets.json
That disables Ethernet by default and makes sure the Ethernet tests are
not failing when it's disabled.
**READY**
@sg- As mentioned in one of the tickets.
CC: @bridadan
> WiFi: Make WiFi default networking interface on Odin board

- tools/export/cdt/__init__.py
- tools/export/iar/__init__.py
- tools/export/iar/ewp.tmpl
- tools/export/iar/iar_nucleo_f746zg.ewp.tmpl
- tools/export/iar/iar_rz_a1h.ewp.tmpl
- tools/export/makefile/Makefile.tmpl
- tools/export/makefile/__init__.py
- tools/export/uvision/__init__.py
- tools/export/uvision/uvision.tmpl
- tools/memap.py
- tools/settings.py
Exporters should build into BUILD as mbed-cli does with the exception of target awareness
```
BUILD\<export builds things here>
BUILD\<target>\<toolchain>\<mbed-cli builds things here>
```
**READY**
Example program docs may need to be update and possibly any hardcoded scripts that CI uses
> Unify output directory for mbed-cli and exporters

- cmsis/core_cm0.h
- cmsis/core_cm0plus.h
- cmsis/core_cm3.h
- cmsis/core_cm4.h
- cmsis/core_cm7.h
- cmsis/core_sc000.h
- cmsis/core_sc300.h
Add data and instruction synchronization barriers to prevent interrupts from occurring after NVIC_DisableIRQ is called. This is a backport of changes made in CMSIS_5 [here](https://github.com/ARM-software/CMSIS_5/issues/110). This fixes #2242.
> Ensure isr cannot occur after NVIC_DisableIRQ

- features/mbedtls/importer/Makefile
- features/mbedtls/platform/inc/platform_mbed.h
The crypto hardware acceleration might require defining a lot of mbed
TLS specific macros. Enumerating all of them in `targets.json` creates
too much noise, therefore we move it into a target specific mbed TLS
header.
The target with crypto hardware acceleration has to
- indicate its capability in `targets.json` by adding "MBEDTLS_CONFIG_HW_SUPPORT"
to the "macros" section
- has to define his crypto hardware acceleration related macros
in an `mbedtls_device.h` header
- place the `mbedtls_device.h` file in the
`features/mbedtls/targets/TARGET_XXXX`
directory specific to the target
**READY**
NO
-
-
-
To test this PR, add crypto hardware acceleration code to your target:
- indicate this capability in `targets.json` by adding "MBEDTLS_CONFIG_HW_SUPPORT"
to the "macros" section
- define your …
> Move crypto hardware acceleration configuration.

- targets/TARGET_STM/TARGET_STM32F1/TARGET_NUCLEO_F103RB/PeripheralPins.c
Add CTS and RTS pins used for the Serial Flow Control.
READY
NO
> NUCLEO_F103RB - Add RTS/CTS pins for Serial Flow Control

- tools/config.py
import sys into `config.py`, something that I aparently forgot to do some time ago. This change should allow the config system to print the precise location of a config error in an app config instead of simply breaking with a 'sys not defined'-like error
**READY**
Should resolve #3281
> Add sys import to config

- tools/profiles/debug.json
This is a gcc specific flag that increases debug information, most useful is allowing the expansion of macros.
http://stackoverflow.com/questions/10475040/gcc-g-vs-g3-gdb-flag-what-is-the-difference/10475077#10475077
> Level 3 includes extra information, such as all the macro definitions present in the program. Some debuggers support macro expansion when you use -g3.
cc @theotherjimmy, @c1728p9
> Add '-g3' flag to gcc debug flags

- .travis.yml
- events/equeue/Makefile
- events/equeue/equeue.c
- events/equeue/tests/tests.c
The `equeue_chain` function is supposed to unchain the event queue from whatever queue it is chained to when passed a null target. Internally, this is accomplished by just calling `equeue_background` with null and letting the previously registered update function clean up the chaining.
However, `equeue_chain` did not appropriately check for null, causing it to unnecessarily allocate memory and leaving the update function in a bad state. Fixed with a simple null check.
should fix https://github.com/ARMmbed/mbed-os/issues/3277
cc @tommikas
> events - Fix unchaining of event queues

- tools/export/uvision/__init__.py
Fixes #3010. Does not add them to accepted file types, but instead does not fail. Header files will show up in the project tree as children of the files that depend on them.
**READY**
@nuket @sg- @theotherjimmy
> Fix issue with unrecognized uvision file types

- tools/test_api.py
Since the toolchain path info lives as a global variable, its not
propagating to the subprocesses that are created to compile the tests in
parallel. This change manually passes these global variables and then
reassigns them.
This seems to only be an issue with the IAR compiler, however I haven't thoroughly tested every environemnt and every compiler.
**READY**
NO
On a machine with the IAR compiler in the system PATH (`iccarm.exe`), run `mbed test --compile -m K64F -t IAR`. It will complete the library build but fail to build any tests.
Switch to these changes and the same command should complete successfully.
@maclobdell This may explain some of the issues you were …
> Passing toolchain path info to subprocesses

- features/FEATURE_LWIP/lwip-interface/lwip_stack.c
Added removal of ipv6 addresses to bring down function. Corrected address semaphore functionality on repeated bring up/down cycles.
READY
NO
None
None
None
> Added clearing of ipv6 addresses to lwip bringdown function

- tools/arm_pack_manager/__init__.py
PR #3097 removed the dependency on pyCurl, however a few references to it still remained. This PR removes these last references.
**READY**
NO
~- [ ] (Tests maybe if @theotherjimmy can suggest any)~
> Removing remaining references to Curl from ARM pack manager

- targets/TARGET_STM/TARGET_STM32F0/common_objects.h
- targets/TARGET_STM/TARGET_STM32F1/common_objects.h
- targets/TARGET_STM/TARGET_STM32F2/objects.h
- targets/TARGET_STM/TARGET_STM32F3/common_objects.h
- targets/TARGET_STM/TARGET_STM32F4/common_objects.h
- targets/TARGET_STM/TARGET_STM32F7/common_objects.h
- targets/TARGET_STM/TARGET_STM32L0/common_objects.h
- targets/TARGET_STM/TARGET_STM32L0/device/stm32l0xx_hal_spi.c
- targets/TARGET_STM/TARGET_STM32L1/common_objects.h
- targets/TARGET_STM/TARGET_STM32L1/device/stm32l1xx_hal_spi.c
- targets/TARGET_STM/TARGET_STM32L4/common_objects.h
- targets/TARGET_STM/stm_spi_api.c
- targets/targets.json
Up to now Aysnch API was not activated on L0 and L1 devices.
This is now done with this PR.
Activation required a few modifications to improve the IRQ handling performances as asynch API provides enhanced SPI throughput but also require high IRQ handling rate, and L0 / L1 are relatively slow MCUs. 
**READY**
The Asynch SPI trasnfers have been tested ok @ 100kHz, 450kHz and 1MHz, for all L0 and L1 boards.
Also non regression was run on NUCLEO_F411RE board.
> Dev spi asynch l0l1

- targets/TARGET_RENESAS/TARGET_RZ_A1H/gpio_irq_api.c
Renesas modified the  initial value of interrupt edge in "gpio_irq_init" function.
The value was "both egde(rise and fall)".So we modified it to "low revel".
> Bug fix of initial value of interrupt edge in "gpio_irq_init" function.

- targets/TARGET_NORDIC/TARGET_NRF5/TARGET_MCU_NRF52832/TARGET_UBLOX_EVA_NINA/PinNames.h
- targets/TARGET_NORDIC/TARGET_NRF5/TARGET_MCU_NRF52832/TARGET_UBLOX_EVA_NINA/device.h
- targets/targets.json
Adding new Maker board platform with mbed enabled with BLE, GNSS and Sensors.
The board implements: 
- NINA-B1 Bluetooth Low Energy module 
- EVA-M8Q GPS and GLONASS receiver
- MPU9250 9DOF IMU
- MKL26Z based CMSIS-DAP interface. 
> Adding mbed enabled Maker board with NINA-B1 and EVA-M8Q

- targets/TARGET_STM/TARGET_STM32F4/analogin_api.c
This is a fix of Issue #1685:
Measuring VBAT sets the ADC_CCR_VBATE bit in ADC->CCR, and there is not possibility with the ST HAL driver to clear it. If it isn't cleared, VBAT remains connected to the ADC channel in preference to temperature, so VBAT readings are returned in place of temperature.
This is a workaround until a better solution is done in ST HAL driver.
READY
NO
> STM32F4 AnalogIn - Clear VBATE and TSVREFE bits before configuring ADC channels

- platform/mbed_critical.c
Some developers prefer using a C++ compiler with C sources due to stricter syntax checking and other benefits. Currently [mbed_critical.c](https://github.com/ARMmbed/mbed-os/blob/master/platform/mbed_critical.c) is the only C source file in the mbed base library that does not build properly with a C++ compiler due to use of UINT32_MAX on an assertion. This change declares __STDC_LIMIT_MACROS on mbed_critical.c before the include of [critical.h](https://github.com/ARMmbed/mbed-os/blob/master/platform/critical.h) so the standard C limit macros are defined in stdint.h.
**READY**
Discussed in #3276 and proposal by @0xc0170 selected for this PR
__STDC_LIMIT_MACROS declaration previously added in #1920 and removed in #2054
> Support building mbed_critical.c with C++ compiler

- targets/TARGET_STM/TARGET_STM32F3/TARGET_DISCO_F303VC/PinNames.h
- targets/TARGET_STM/TARGET_STM32F3/TARGET_DISCO_F334C8/PinNames.h
- targets/TARGET_STM/TARGET_STM32F3/TARGET_NUCLEO_F303K8/PinNames.h
- targets/TARGET_STM/TARGET_STM32F3/TARGET_NUCLEO_F303RE/PinNames.h
- targets/TARGET_STM/TARGET_STM32F3/TARGET_NUCLEO_F303ZE/PinNames.h
- targets/TARGET_STM/TARGET_STM32F3/TARGET_NUCLEO_F334R8/PinNames.h
Add ADC_VREF label on some platforms where only ADC_VREF1, 2, etc... were defined. This is mainly to avoid compilation error with examples that use it.
READY
NO
> STM32 - Add ADC_VREF label

- targets/TARGET_STM/TARGET_STM32L4/TARGET_NUCLEO_L432KC/device/system_stm32l4xx.c
no HSE available by default for NUCLEO_L432KC
READY
OS2 and OS5 tests OK
> no HSE available by default for NUCLEO_L432KC

- targets/targets.json
DISCO_L053C8 doesn't support LSE
READY
MBED_16 OS2 test was previously FAIL, it is now OK
> DISCO_L053C8 doesn't support LSE

- targets/TARGET_STM/hal_tick_16b.c
- targets/TARGET_STM/hal_tick_32b.c
After PR #3213 has been merged we discovered that LPT tests were failed. This was due to the TIM_IT_UPDATE flag added in the HAL_Suspend/ResumeTick functions. With this PR, the LPT tests are now pass.
READY
NO
> STM32 - Remove TIM_IT_UPDATE flag in HAL_Suspend/ResumeTick functions

- drivers/I2C.h
- hal/i2c_api.h
This yet does not completely fixes the issue #2725. It's first step. The documentation corrections. HAL said that it write() returns bytes written that was partially true, it also returns failures (negative values). Based on that , I2C driver doc were updated to reflect this.
The second step would be to write tests to see if there are number of bytes written reported and failures. looking at targets, they vary in return values.
References:
- https://github.com/ARMmbed/mbed-os/blob/master/targets/TARGET_Silicon_Labs/TARGET_EFM32/i2c_api.c#L270
- https://github.com/ARMmbed/mbed-os/blob/master/targets/TARGET_STM/TARGET_STM32F4/i2c_api.c#L646 (this errors on non valid bytes written returned)
- https://github.com/ARMmbed/mbed-os/blob/master/targets/TARGET_NORDIC/TARGET_NRF5/i2c_api.c#L246 …
> I2C - correct return values for write functions (docs) - part 1

- targets/TARGET_STM/TARGET_STM32L4/TARGET_DISCO_L476VG/device/system_stm32l4xx.c
- targets/TARGET_STM/TARGET_STM32L4/TARGET_L476_L486/device/system_stm32l4xx.c
No HSE is available for DISCO_L476VG and NUCLEO_L476RG.
Associated define is then removed.
READY
OS2 and OS5 tests have been done, including USB
> STM32L476: no HSE is present in NUCLEO and DISCO boards

- targets/TARGET_ONSEMI/TARGET_NCS36510/aes_map.h
- targets/TARGET_ONSEMI/TARGET_NCS36510/analogin_api.c
- targets/TARGET_ONSEMI/TARGET_NCS36510/ncs36510Init.c
- targets/TARGET_ONSEMI/TARGET_NCS36510/objects.h
- targets/TARGET_ONSEMI/TARGET_NCS36510/pwm_map.h
- targets/TARGET_ONSEMI/TARGET_NCS36510/pwmout_api.c
Notes:
changes in register map for RevG silicon. Attached are the test results.
[IAR-Results-24-11-2016.txt](https://github.com/ARMmbed/mbed-os/files/610610/IAR-Results-24-11-2016.txt)
YES | NO
branch | PR
required changes in …
> Register map changes for RevG

- tools/project.py
Copied from #3313
>### Description
>- Type: Bug
>- Priority: Minor
>
>---------------------------------------------------------------
>## Bug
>
>**Target**
>Any
>
>**Toolchain:**
>GCC_ARM
>
>**Toolchain version:**
>Any
>
>**mbed-cli version:** 
>0.9.10
>
>**meed-os sha:**
>a1c0840b3d Merge pull request #3227 from ARMmbed/release-candidate
>
>**Expected behavior**
>```bash
>mbed export --profile ./mbed-os/tools/profiles/debug.json -i make_gcc_arm 
>```
>should use the debug profile when generating the Makefile.
>
>**Actual behavior**
>```bash
>Traceback (most recent call last):
>  File "/dev/mbed-os/tools/project.py", line 247, in <module>
>    main()
>  File "/dev/mbed-os/tools/project.py", line 239, in main
>    profile = extract_profile(parser, options, toolchain_name)
>  File …
```
> Fix project profile parsing

- tools/export/cmsis/__init__.py
When a target does not have a device name, we want to use a generic ARM cpu export target. This fixes a bug in the implementation of that functionality.
Reproduce:
Run `mbed export` on a target without a device name. It should not fail, as the intended logic was for this line to find a generic CPU target. However, as it is, it will fail.
@theotherjimmy
> [Exporters] Fix generic ARM CPU target in uvision

- targets/targets.json
NUCLEO_F429ZI board has an integrated LSE on the target, so it is better to use it instead of LSI.
READY
Tests are OK with https://github.com/ARMmbed/mbed-os/pull/3316 integration
> NUCLEO_F429ZI has integrated LSE

- features/netsocket/TCPServer.cpp
- features/netsocket/TCPServer.h
- features/netsocket/TCPSocket.cpp
- features/netsocket/TCPSocket.h
- features/netsocket/UDPSocket.cpp
- features/netsocket/UDPSocket.h
Don't send events on close()
It's currently possible to generate a socket event when a non-blocking socket is closed:
1. _pending is set to 0 in https://github.com/ARMmbed/mbed-os/blob/master/features/netsocket/TCPSocket.cpp#L22
when the socket is created.
2. close() calls event() in https://github.com/ARMmbed/mbed-os/blob/master/features/netsocket/Socket.cpp#L66
3. event() increments _pending, and since _pending is 1 it will call _callback() in https://github.com/ARMmbed/mbed-os/blob/master/features/netsocket/TCPSocket.cpp#L167
However, if send() (for example) is called, this can happen:
- send() is called and sets _pending to 0.
- when the data is sent, event() is called, which sets _pending to 1 and calls _callback().
- if close() is called at this point, there won't be an event …
> Don't send events on close()

- targets/TARGET_Freescale/TARGET_KSDK2_MCUS/TARGET_MCU_K64F/dma_reqs.h
- targets/TARGET_Freescale/TARGET_KSDK2_MCUS/TARGET_MCU_K64F/drivers/fsl_dspi_edma.c
- targets/TARGET_Freescale/TARGET_KSDK2_MCUS/TARGET_MCU_K64F/spi_api.c
- targets/TARGET_Freescale/TARGET_KSDK2_MCUS/api/dma_api.c
- targets/TARGET_Freescale/TARGET_KSDK2_MCUS/api/dma_api_hal.h
- targets/TARGET_Freescale/TARGET_KSDK2_MCUS/api/objects.h
- targets/targets.json
Implement the Asynch API's for the K64F SPI HAL driver. Both interrupt and DMA based asynch transfer is supported
**READY
Compilation using IAR toolchain is broken, below PR has the fix.
https://github.com/ARMmbed/mbed-os/pull/3256
[ ] Tests
Tested both the DMA and interrupt based ASYNCH functions on the HEXIWEAR board to test the display.
> K64F: SPI Asynch API implementation

- tools/test/examples/examples.json
- tools/test/examples/examples_lib.py
Turns on export building for many examples that we should be building, and filters exporters with the toolchain specified in the example JSON file.
> Enabled example export building for more examples

- tools/tests.py
Remove the limitation of USB_4 to ARM toolchain
Test is OK on  IAR and GCC_ARM .
READY
No
> USB_4 : test OK with IAR ,GCC_ARM(limitation to ARM not needed)

- tools/export/iar/__init__.py
Currently, IAR requires that device has a CMSIS pack to find the debug interface. With that assumption, if a debug interface cannot be found, it defaults to CMSIS-DAP. This change will mean that the default CMSIS-DAP is also used when there is not CMSIS pack at all. 
Fixes #3286
@theotherjimmy
> IAR export will not fail in the absence of a CMSIS pack

- TESTS/mbedmicro-rtos-mbed/malloc/main.cpp
Increase the stack size used in the malloc test to prevent stack overflows on Cortex-A devices.
> Increase stack size in malloc test for Cortex-A

- targets/TARGET_STM/TARGET_STM32L1/TARGET_NUCLEO_L152RE/device/system_stm32l1xx.c
- targets/TARGET_STM/mbed_rtx.h
The NUCLEO-L152RE can run up to 32 MHz even if clocked from HSE as can be configured in cubeMX
**READY**
Full non regression OK 
[report__mbed_os_non_regression_L1_fix_RCC__2016_12_06_12_02__ARM_IAR_GCC.zip](https://github.com/ARMmbed/mbed-os/files/634602/report__mbed_os_non_regression_L1_fix_RCC__2016_12_06_12_02__ARM_IAR_GCC.zip)
> STM32 NUCLEO-L152RE Update system core clock to 32MHz

- targets/TARGET_STM/TARGET_STM32F1/PeripheralPins.h
- targets/targets.json
- Fix Issue #3266
- Add external declaration of UART_CTS/RTS const tables
- Add the SERIAL_FC in device_has field in targets.json
READY
NO
> NUCLEO_F103RB - Add SERIAL_FC feature

- mbed.h
As well as updating the versionning in mbed.h ready for the release, this PR also kicks off the creation and testing of the associated mbed-os 2 build.
> Update MBED_LIBRARY_VERSION to 131 and mbed version macros for mbed-os-5.3.0

- targets/TARGET_RENESAS/TARGET_RZ_A1H/can_api.c
- targets/TARGET_RENESAS/TARGET_VK_RZ_A1H/can_api.c
Until now, when the frequency function of CAN driver was executed, signal no output, and the frequency could not be changed.
Since there was an error in the frequency changing procedure I modified it.
> Fix frequency function of CAN driver.

- targets/TARGET_STM/TARGET_STM32F0/TARGET_NUCLEO_F042K6/device/stm32f042x6.h
- targets/TARGET_STM/TARGET_STM32F0/TARGET_NUCLEO_F072RB/device/stm32f072xb.h
- targets/TARGET_STM/TARGET_STM32F0/TARGET_NUCLEO_F091RC/device/stm32f091xc.h
- targets/TARGET_STM/TARGET_STM32F0/analogin_api.c
- targets/TARGET_STM/TARGET_STM32F0/device/stm32f0xx_hal_conf.h
- targets/TARGET_STM/TARGET_STM32F0/gpio_irq_api.c
ST HAL assert is mapped onto MBED HAL assert, and can now be enabled easily.
Note for all STM32 targets:
- ST asserts are used to check each parameters in ST HAL function call
- They are not compiled by default, you have to define USE_FULL_ASSERT to enable them
OS2 and OS5 tests done.
Few updates have been needed to match ST HAL API.
READY
> STM32F0 : map ST HAL assert into MBED assert

- tools/options.py
- tools/utils.py
**READY**
YES
Anyone using the `--cflags`, `--cppflags`, or `--ldflags` arguments are advised that they have no affect, and should stop passing them. Please migrate any flag shenanigans to using `--profile`
> Remove deprecated flags args

- targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_dma.c
The ISR register is never re-evaluated in HAL_DMA_PollForTransfer for STM32F4.
This will cause the function to unnecessarily wait for timeout in some circumstances.
Putting 'tmpisr = regs->ISR;' at the end of the while loop solves it for the ODIN driver.
**READY**
NO
https://github.com/ARMmbed/mbed-os/issues/3272
Review by @LMESTM 
None
This has been reproduced with the private repo of the u-blox ODIN-drivers and the fix can therefore only be verified by u-blox for the UBLOX_EVK_ODIN_W2 target. The current ODIN-W2 driver binary for mbed-os v5.3.0 has a workaround therefore it's not affected.
- Get ublox ODIN drivers branch alar_sdio_optimizations
- Get mbed-os commit 9d8ec61
- Run WiFi and BT tests. WiFi will timeout because initialization is too slow(~15 sec)
The tests below have been …
> ISR register never re-evaluated in HAL_DMA_PollForTransfer for STM32F4

- tools/toolchains/arm.py
- tools/toolchains/iar.py
Both the ARM and IAR compilers use absolute paths to explicitly include their standard libraries. It seems that for both of these compilers, these paths are already in their default search paths, so using an absolute path is not necessary. This fixes an issue when exporting to make and the paths are incorrectly configured. This should now work out-of-the box.
**READY**
NO
Requesting @theotherjimmy and @screamerbg to review this since it modifies the toolchains
> Remove unnecessary absolute paths from IAR and ARM compilers

- tools/export/makefile/Makefile.tmpl
For some reason, make has issues issuing an `echo` command that doesn't use quotes when ran inside the Windows command prompt (not in bash). This PR adds quotes to the problematic `echo` commands.
**READY**
NO
> [make exporters] Adding quotes to echo statements

- targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_dma.c
- targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_dma.h
This is a fix to add the update of hdma->State variable as it was done in a previous version of HAL driver.
This change is required as we need to figure out which kind of event has triggered the IRQ (for example to know if it was a TX/RX buffer half-complete or a full-complete event) in order to call the right callback (specified by the mbed application programmer) with the right parameters.
With the old HAL DMA API we could figure this easily out by first calling HAL_DMA_IRQHandler() and then analyzing the states of the DMA stream (by using HAL_DMA_GetState()).
With the new HAL DMA API this approach does not work anymore. The state is not updated in the HAL_DMA_IRQHandler(), the state machine will stay in a Busy State until we abort the transfer. These states information have been …
> STM32F4 - FIX to add the update of hdma->State variable

- targets/TARGET_STM/i2c_api.c
Having a master I2C and a slave I2C communicating together on the same device is maybe not a real use case, but this PR allows to pass "master slave asynch" tests at higher frequencies than the default 100kHz for boards like NUCLEO_L152RE (32MHz) and NUCLEO_F042K6  (48MHz)
The 2nd commit restores the slave address in error cases, when no devices is found for instance or when bus is locked in a busy state.
**READY**
TESTED OK with  MBED_A29: i2c_master_slave_asynch.
> Fix stm i2c slave

- targets/TARGET_STM/i2c_api.c
This is PR contains a clean-up of the init phases which was not seen before but has been seen while moving F1 family to the common I2C code as well. So this PR is a pre-requisite to later introduction of F1 to common code (and F1 asynch I2C support at the same time)
**READY**
I2C non regression tests passed OK
> Fix stm i2c fix init

- features/FEATURE_LWIP/TESTS/mbedmicro-net/host_tests/tcp_echo_client.py
- features/FEATURE_LWIP/TESTS/mbedmicro-net/host_tests/udp_echo_client.py
**READY**
It seems that the 0 aka 'any port' doesn't work well on Mac, causing
[Errno 49] Can't assign requested address errors.
```
[1481634494.19][HTST][ERR] something went wrong in event main loop!
[1481634494.19][HTST][INF] ==== Traceback start ====
File "/usr/local/lib/python2.7/site-packages/mbed_host_tests/host_tests_runner/host_test_default.py", line 364, in run_test
callbacks[key](key, value, timestamp)
File "/Users/barsza01/devel/mbed/code/mbed-os/features/FEATURE_LWIP/TESTS/mbedmicro-net/host_tests/udp_echo_client.py", line 104, in _callback_target_ip
self.SERVER_IP = self.find_interface_to_target_addr(self.target_ip)
File "/Users/barsza01/devel/mbed/code/mbed-os/features/FEATURE_LWIP/TESTS/mbedmicro-net/host_tests/udp_echo_client.py", line …
```
> Fix network echo test host scripts for Mac

- targets/TARGET_STM/i2c_api.c
With ci test shiled tests, a few issues were faced and needed to be solved 
- the reference I2C test makes a mixed usage for unitary MBED APIs (start / stop / send & read bytes) and more advanced read and write APIs which autonomously manage start and stop. The code needed update to cope with this API use.
- also the eeprom driver checks if eeprom is ready by sending data of length = 0, the STM32 HAL provides a dedicated API for such case which we're using now
This allows to have the I2C eeprom test to pass on F1, F2, F4 and L1 families. 
Other families have not passed the tests yet - further work is needed as they embed a different I2C IP version - this will be done in a later PR.
**READY**
+-------------------+---------------+---------------+------------------------------------+--------+ …
> Fix ci shield eeprom test

- targets/TARGET_STM/TARGET_STM32F1/device/stm32f1xx_hal_conf.h
- targets/TARGET_STM/TARGET_STM32F1/gpio_irq_api.c
- targets/TARGET_STM/TARGET_STM32F1/pinmap.c
- targets/TARGET_STM/TARGET_STM32F1/rtc_api.c
ST HAL assert is mapped onto MBED HAL assert, and can now be enabled easily.
Note for all STM32 targets:
- ST asserts are used to check each parameters in ST HAL function call
- They are not compiled by default, you have to define USE_FULL_ASSERT to enable them
OS2 and OS5 tests done.
Few updates have been needed to match ST HAL API.
READY
> STM32F1 : map ST HAL assert into MBED assert

- targets/TARGET_STM/TARGET_STM32F2/device/stm32f2xx_hal_conf.h
- targets/TARGET_STM/TARGET_STM32F2/gpio_irq_api.c
ST HAL assert is mapped onto MBED HAL assert, and can now be enabled easily.
Note for all STM32 targets:
- ST asserts are used to check each parameters in ST HAL function call
- They are not compiled by default, you have to define USE_FULL_ASSERT to enable them
OS2 and OS5 tests done.
Few updates have been needed to match ST HAL API.
READY
> STM32F2 : map ST HAL assert into MBED assert

- targets/TARGET_STM/TARGET_STM32F3/TARGET_NUCLEO_F302R8/device/stm32f302x8.h
- targets/TARGET_STM/TARGET_STM32F3/TARGET_NUCLEO_F303K8/device/stm32f303x8.h
- targets/TARGET_STM/TARGET_STM32F3/TARGET_NUCLEO_F303RE/device/stm32f303xe.h
- targets/TARGET_STM/TARGET_STM32F3/TARGET_NUCLEO_F303ZE/device/stm32f303xe.h
- targets/TARGET_STM/TARGET_STM32F3/TARGET_NUCLEO_F334R8/device/stm32f334x8.h
- targets/TARGET_STM/TARGET_STM32F3/device/stm32f3xx_hal_conf.h
- targets/TARGET_STM/TARGET_STM32F3/gpio_irq_api.c
ST HAL assert is mapped onto MBED HAL assert, and can now be enabled easily.
Note for all STM32 targets:
- ST asserts are used to check each parameters in ST HAL function call
- They are not compiled by default, you have to define USE_FULL_ASSERT to enable them
OS2 and OS5 tests done.
Few updates have been needed to match ST HAL API.
READY
> STM32F3 : map ST HAL assert into MBED assert

- features/netsocket/Socket.cpp
During open, the socket checked the internal stack variable, assuming it would alway be null on a socket not connected to the network. However, when a socket is closed, the stack variable was not updated, causing the socket to incorrectly return a parameter error if reopened.
The simple fix was to set the stack to null on close. A non-null stack is a predicate for a non-null socket variable, so no additional checks are needed in socket functions.
Required for https://github.com/ARMmbed/mbed-os/pull/3265
> nsapi - Fixed open/close issue in Socket

- features/unsupported/tests/mbed/i2c_master_slave_asynch/main.cpp
0x90 is I2C slave device address which is used on by temperature sensor (like TMP102 temperature sensor, also on ci test shiled). So to avoid conflicts on a board where the sensor is used and we also want to test master / slave communication, I propose to change the default salve address to another one (if 0x80 is not suitable, feel free to propose another one)
> Change slave address in I2C master slave asynch test

- tools/test/examples/examples_lib.py
If an example's GitHub repository contains multiple child examples, the script was incorrectly filtering out all the child examples when compiling and exporting. This patch now handles this case correctly.
Also added one print message to the compile step so you know what's currently compiling.
**READY**
NO
> Correctly filtering examples in test script

- targets/TARGET_Freescale/TARGET_KSDK2_MCUS/api/i2c_api.c
This change is to match the change to the I2C API per the below PR:
https://github.com/ARMmbed/mbed-os/pull/3301#issuecomment-265695054
**READY**
> KSDK I2C: Update the return value to match the API documentation change

- features/unsupported/USBDevice/USBAudio/USBAudio.cpp
- features/unsupported/USBDevice/USBAudio/USBAudio.h
- features/unsupported/tests/usb/device/audio_cb/main.cpp
- tools/tests.py
Creation  : 
-  Call back api in USBAudio device for transmission complete and reception complete.
- Specific api for filling/reading  FIFO is also provided.
These apis allow to early  fill/empty  ISO endpoint FIFO. These early treaments which enable hardware reception/ transmission  avoid to miss any periodic packet in ISO mode. 
READY
This PR provides additional interfaces that can be optionally used by application. 
USB_8 test demonstrates these api. No migration is needed.
> USB audio callback  rx and tx

- targets/TARGET_RENESAS/TARGET_RZ_A1H/device/mmu_Renesas_RZ_A1.c
I modified the TTB setting of RO_DATA area.
The current setting of this area is "not executable".
Therefore, when trying to execute a program placed in this area, a prefetch abort will occur.
So I changed from "Sect_Normal_RO" to "Sect_Normal_Cod".
> [RZ/A1H]Fix TTB setting of RO_DATA area

- tools/detect_targets.py
> Remove unused arguments from detect targets

- targets/TARGET_NORDIC/TARGET_NRF5/TARGET_MCU_NRF52832/TARGET_UBLOX_EVK_NINA_B1/PinNames.h
- targets/TARGET_NORDIC/TARGET_NRF5/TARGET_MCU_NRF52832/TARGET_UBLOX_EVK_NINA_B1/device.h
- targets/targets.json
Rebased #3328 and squashed into one commit
cc @mazgch - please check if targets/targets.json is rebased properly
> Target: Add new target UBLOX_EVK_NINA_B1

- rtos/Thread.h
This change reflects the correct syntax for spawning a thread that will execute a local function with given parameters.
The currently provided example will not compile. Inspired by #3396.
@geky @0xc0170 
**READY**
Try to compile the currently provided example to view failure.
> Remove invalid thread::start example

- features/netsocket/TCPSocket.cpp
- features/netsocket/nsapi_types.h
A few new error codes are added to nsapi_error_t and
support for non-blocking socket connect is added.
Nanostack's connect call will be non-blocking.
Whereas LWIP connect call is currently blocking, and it could be changed now
to be non-blocking.
> [ONME-2844] Supporting non-blocking connect()

- features/netsocket/NetworkStack.h
- features/netsocket/Socket.h
- features/netsocket/nsapi_types.h
To allow a network stack to support both NSAPI and its own options, try to make
sure the NSAPI levels don't collide with level numbers likely to be used by
network stacks.
Distinguish between socket and stack options, and tighten up documentation. Add
IP MRU stack options as an example (implementation not immediately planned for
any stack, but could be useful).
> [ONME-2844] Avoid option level collisions

- TESTS/mbedmicro-rtos-mbed/threads/main.cpp
Previously, the RTOS threads test would conditionally change the thread stack size for all test cases based on the target. Now, it uses the default stack size for all targets when threads are created serially, and uses a 512 byte stack for the threads that are created in parallel.
Also, this should remove the last failing test case on the ARCH_PRO platform :)
**READY**
NO
Requesting reviews by @c1728p9 and @geky since they are familiar with all things RTOS and stack-sizey (yes that's a technical term)
Also requesting a review by @pan- as this may affect some of the BLE platforms/constrained mbeds.
> Limiting the thread stack for parallel threads test

- tools/project.py
- tools/project_api.py
Fixes https://github.com/ARMmbed/mbed-os/issues/2690
> Move clean functionality out of the export api

- tools/settings.py
This change was spurred by a confusing error. I attempted to compile for the RZ_A1H (a Cortex-A device), and I had the standalone ARM compiler in my system path, which supports Cortex-A. However, the default path for the ARM compiler in settings.py uses a Keil installation, which only supports Cortex-M. It found my Keil installation and used that instead, **causing a compiler error**. This change proposes to remove this default behavior and instead **requires the user to explicitly set the intended compiler path**, either by a settings file, mbed CLI, environment variables, or by placing the compiler in your PATH.
**READY**
**YES**
This will now require that a user sets the compiler paths via mbed CLI, environment variables, settings files, or by placing them in the system PATH.
I realize …
> Removing default toolchain paths

- targets/TARGET_STM/TARGET_STM32F1/can_api.c
- targets/TARGET_STM/TARGET_STM32F1/device/stm32f1xx_hal_can.h
Notes:
*  The transmit mailbox empty interrupt flag always keep if IRQ_TX interrupt enabled from can.write(...)
Repair the transmit mailbox (0,1,2) empty interrupt flag not clear BUG
**READY**
> Repair the transmit mailbox (0,1,2) empty interrupt flag not clear BUG

- features/FEATURE_LWIP/lwip-interface/lwip-eth/arch/TARGET_STM/TARGET_STM32F7/TARGET_DISCO_F746NG/stm32f7_eth_init.c
- features/FEATURE_LWIP/lwip-interface/lwip-eth/arch/TARGET_STM/TARGET_STM32F7/TARGET_DISCO_F769NI/stm32f7_eth_init.c
- features/FEATURE_LWIP/lwip-interface/lwip-eth/arch/TARGET_STM/TARGET_STM32F7/TARGET_F746_F756/stm32f7_eth_init.c
- features/FEATURE_LWIP/lwip-interface/lwip-eth/arch/TARGET_STM/TARGET_STM32F7/TARGET_NUCLEO_F767ZI/stm32f7_eth_init.c
See the detailed explanation of the issue here
https://github.com/ARMmbed/mbed-os/issues/3387
The ethernet buffers are located in the SRAM1 memory that has data cache enable.
Extract from the mbed.map:
```
DMARxDscrTab            0x20012aa4    0x80  Data  Gb  stm32f7_emac.o [8]
DMATxDscrTab            0x20012b24    0x80  Data  Gb  stm32f7_emac.o [8]
Rx_Buff                 0x20012ba4  0x17d0  Data  Gb  stm32f7_emac.o [8]
Tx_Buff                 0x20014374  0x17d0  Data  Gb  stm32f7_emac.o [8]
```
The DMA descriptors are written by the CPU, and kept in cache.
The Ethernet IP is then reading the DMA descriptor in the SRAM1 memory, that does not contains the requested information (still in cache)
You can see in the …
> Stm32f7 ethernet fix for IAR issue #3387

- tools/export/makefile/__init__.py
The error message is a bit better.
**READY**
```
Scan: basic
Scan: env
Scan: hal
File "project.py", line 244, in <module>
main()
File "project.py", line 240, in main
zip_proj=zip_proj, build_profile=profile)
File "project.py", line 93, in export
build_profile=build_profile, silent=silent)
File "D:\mbed-os-mbed-os-5.2\tools\project_api.py", line 229, in export_project
macros=macros)
File "D:\mbed-os-mbed-os-5.2\tools\project_api.py", line 90, in generate_project_files
exporter.generate()
File "D:\mbed-os-mbed-os-5.2\tools\export\cdt\__init__.py", line 14, in generate
super(Eclipse, self).generate()
File "D:\mbed-os-mbed-os-5.2\tools\export\makefile\__init__.py", line 82, in generate
ctx[key] = ctx['vpath'][0] + "/" + ctx[key]
TypeError: cannot concatenate …
```
> Improve error message when exporting for make without a linker script

- TESTS/mbedmicro-rtos-mbed/isr/main.cpp
- TESTS/mbedmicro-rtos-mbed/mail/main.cpp
- TESTS/mbedmicro-rtos-mbed/mutex/main.cpp
- TESTS/mbedmicro-rtos-mbed/queue/main.cpp
- TESTS/mbedmicro-rtos-mbed/semaphore/main.cpp
- TESTS/mbedmicro-rtos-mbed/signals/main.cpp
- TESTS/mbedmicro-rtos-mbed/threads/main.cpp
Thread spawning constructors are deprecated, start function should be
used instead.
**READY**
> Fix deprecated Thread ctor usage in RTOS tests

- targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/api/i2c_api.c
Update I2C driver to handle zero byte writes.
**READY
Tested using the ci-test-shield board, below is a link to the issue reported.
https://github.com/ARMmbed/ci-test-shield/issues/17
> MCUXpresso I2C: Handle 0 byte write

- features/FEATURE_COMMON_PAL/mbed-client-c/CHANGELOG.md
- features/FEATURE_COMMON_PAL/mbed-client-c/Makefile
- features/FEATURE_COMMON_PAL/mbed-client-c/module.json
- features/FEATURE_COMMON_PAL/mbed-client-c/nsdl-c/sn_nsdl_lib2.h
- features/FEATURE_COMMON_PAL/mbed-client-c/source/libCoap/src/sn_coap_builder.c
- features/FEATURE_COMMON_PAL/mbed-client-c/source/libCoap/src/sn_coap_protocol.c
- features/FEATURE_COMMON_PAL/mbed-client-c/source/libNsdl/src/include/sn_grs2.h
- features/FEATURE_COMMON_PAL/mbed-client-c/source/libNsdl/src/sn_grs2.c
- features/FEATURE_COMMON_PAL/mbed-client-c/source/libNsdl/src/sn_nsdl2.c
- features/FEATURE_COMMON_PAL/mbed-client-c/test/nsdl-c/unittest/Makefile
- features/FEATURE_COMMON_PAL/mbed-client-c/test/nsdl-c/unittest/makefile_defines.txt
- features/FEATURE_COMMON_PAL/mbed-client-c/test/nsdl-c/unittest/sn_coap_builder/Makefile
- features/FEATURE_COMMON_PAL/mbed-client-c/test/nsdl-c/unittest/sn_coap_builder/libCoap_builder_test.cpp
- features/FEATURE_COMMON_PAL/mbed-client-c/test/nsdl-c/unittest/sn_coap_header_check/Makefile
- features/FEATURE_COMMON_PAL/mbed-client-c/test/nsdl-c/unittest/sn_coap_parser/Makefile
- features/FEATURE_COMMON_PAL/mbed-client-c/test/nsdl-c/unittest/sn_coap_parser/test_sn_coap_parser.c
- features/FEATURE_COMMON_PAL/mbed-client-c/test/nsdl-c/unittest/sn_coap_protocol/Makefile
- features/FEATURE_COMMON_PAL/mbed-client-c/test/nsdl-c/unittest/sn_coap_protocol/libCoap_protocol_test.cpp
- features/FEATURE_COMMON_PAL/mbed-client-c/test/nsdl-c/unittest/sn_grs/Makefile
- features/FEATURE_COMMON_PAL/mbed-client-c/test/nsdl-c/unittest/sn_grs/test_sn_grs.c
- features/FEATURE_COMMON_PAL/mbed-client-c/test/nsdl-c/unittest/sn_nsdl/Makefile
- features/FEATURE_COMMON_PAL/mbed-client-c/test/nsdl-c/unittest/sn_nsdl/sn_nsdltest.cpp
- features/FEATURE_COMMON_PAL/mbed-client-c/test/nsdl-c/unittest/sn_nsdl/test_sn_nsdl.c
- features/FEATURE_COMMON_PAL/mbed-client-c/test/nsdl-c/unittest/sn_nsdl/test_sn_nsdl.h
- features/FEATURE_COMMON_PAL/mbed-client-c/test/nsdl-c/unittest/stubs/randLIB_stub.cpp
- features/FEATURE_COMMON_PAL/mbed-client-c/test/nsdl-c/unittest/stubs/randLIB_stub.h
Valgrind error fixes, CoAP library bugfixes and CoAP message id randomization. Added compile time flag to enable new memory optimized API.
**READY**
NO
> Update mbed-client-c version 3.0.4

- features/unsupported/tests/mbed/i2c_master_slave/main.cpp
- features/unsupported/tests/mbed/i2c_master_slave_asynch/main.cpp
- targets/TARGET_STM/TARGET_STM32F0/common_objects.h
- targets/TARGET_STM/TARGET_STM32F3/common_objects.h
- targets/TARGET_STM/TARGET_STM32F7/common_objects.h
- targets/TARGET_STM/TARGET_STM32L0/common_objects.h
- targets/TARGET_STM/TARGET_STM32L4/common_objects.h
- targets/TARGET_STM/i2c_api.c
This PR shall close my recent series of rework (and fixes) to get STM32 I2C into a single file.
This one covers the unitary start / stop / byte read and write functions for STM32 for F0, F3, F3, L0 and L4 families. 
Status READY
Test report:
To have ARM ci test shield I2C tests working ok as well on those targets, an update of the I2Ceeprom driver is also needed on top of this PR. The proposed patch has been submitted here:
https://developer.mbed.org/users/LMESTM/code/I2CEeprom/
With the I2Ceeprom driver update and this PR, the I2C ci test shield is tested ok:
+-------------------+---------------+---------------+------------------------------------+--------+--------+--------+--------------------+
| target            | platform_name | test suite    | test case                          | …
> Dev stm i2c v2 unitary functions

- targets/TARGET_STM/TARGET_STM32F0/can_api.c
- targets/TARGET_STM/TARGET_STM32F1/can_api.c
- targets/TARGET_STM/TARGET_STM32F2/can_api.c
- targets/TARGET_STM/TARGET_STM32F3/can_api.c
- targets/TARGET_STM/TARGET_STM32F4/can_api.c
- targets/TARGET_STM/TARGET_STM32F7/can_api.c
- targets/TARGET_STM/TARGET_STM32L4/can_api.c
This PR includes two commits which fix two things both related to the CAN read() method, but if you prefer two separate PRs, I can do it without any problem.
The first commit fixes bug #3463 (CAN read() return value).
*Disclaimer: Although this PR as only been tested on nucleo F303K8 and L476RG, I expect others series to work too.*
* STM32F0: checked registers with the reference manual of the F0 serie
* STM32F1: checked registers with the reference manual of the F1 serie
* STM32F2: has a cortex m3, this is assumed to be working as a F3
* STM32F3: successfully tested with a nucleo F303K8
* STM32F4: checked registers with the reference manual of the F4 serie
* STM32F7: wild guessed
* STM32L4: successfully tested with a nucleo L476RG
The second commit prevent the reset of the whole `RF0R` …
> Fix #3463 CAN read() return value

- targets/TARGET_NXP/TARGET_LPC15XX/pwmout_api.c
Currently, when there's a conflict on timer events (like PWM low compare and period reset), it defaults to "do nothing" (keep previous output value). When the PWM duty cycle is changed directly from 0 to 1, the only events are conflict events (because both match values are equal) and the PWM gets stuck low. This changes the conflict resolution rules for set to take priority.
(this conflict case only comes up when PWM duty cycle is 1, in the 0 case there was already special case code to force the output low and stop the timer)
> [LPC15xx] Ensure that PWM=1 is resolved correctly

- targets/TARGET_NXP/TARGET_LPC15XX/can_api.c
- Add support for TX interrupts.
- Allocates dedicated TX messageboxes (instead of runtime-allocating a messagebox when requested).
- Change RX and TX interrupt style from messagebox-based to controller based.
- This is the simplest implementation - both irq_set and filter modify the messagebox control registers, and both can be called at any time, in any order.  However, this could be implemented with a more complex read-modify-write of messagebox control registers.
- Add support for error-warning, error-passive, and bus-off status change interrupts.
- Since the controller hardware only provides a general error status change interrupt flag, it isn't possible to differentiate between which one caused the interrupt. Therefore, it is possible to have error-warning interrupts fire multiple …
> [LPC15xx] CAN implementation improvements

- features/unsupported/USBDevice/USBDevice/USBEndpoints_M453.h
- features/unsupported/USBDevice/USBDevice/USBEndpoints_NUC472.h
- features/unsupported/USBDevice/USBDevice/USBHAL_M453.cpp
- features/unsupported/USBDevice/USBDevice/USBHAL_NUC472.cpp
This PR includes no logic update and just removes Tab in USB HAL as requested in #3365.
> [NUC472/M453] Remove Tab in USB HAL

- tools/test_api.py
This fixes #3516. If an `mbed_app.json` file is used when compiling tests, the tools were incorrectly ignoring macros that were supplied on the command line. This PR fixes this so the macros propagate correctly.
**READY**
NO
Edit any test with the following code:
```c++
#ifdef MY_SILLY_MACRO
printf("MY_SILLY_MACRO is set!\r\n");
#else
printf("MY_SILLY_MACRO is NOT set!\r\n");
#endif
```
If run the following commands, you should see `MY_SILLY_MACRO is set!` printed in the test report:
```
mbed test -DMY_SILLY_MACRO --compile --clean
mbed test --run -v
```
However, if you add an `mbed_app.json` file with the following contents:
```json
{
"macros": ["MY_DUMMY_MACRO"]
}
``` …
> Preventing app_config from clobbering CLI macros

- features/FEATURE_LWIP/lwip-interface/lwip_stack.c
There were a few lingering issues with static IPv4 addresses that was preventing the `set_network` function from working with lwip.
1. lwip connected state being set incorrectly (thanks to @YixiaoLi for finding this)
2. default dns servers were not being set up
Generalized handling of dns servers when brought up with both ipv4 and ipv6 addresses. Falls back to google dns servers if not dns server is found through dhcp.
Also added support for the `add_dns_server` method to lwip to support custom servers.
should resolve https://github.com/ARMmbed/mbed-os/issues/3234
should resolve https://github.com/ARMmbed/mbed-os/issues/3524
cc @kjbracey-arm
> lwip - Fix static IP address issues with IPv4

- tools/export/cdt/__init__.py
Eclipse CDT expects the include paths to include the project name like '/<project>/<include-path>' for workspace include directories.
See issue #3529.
**READY**
NO
See issue #3529
> Correctly format include paths for eclipse export

- tools/project.py
This was spurred by https://github.com/ARMmbed/mbed-cli/issues/410.
Having a default target and ide in the `project.py` script is inconsistent with the rest of the tools. This PR removes them and makes `-m` and `-i` required arguments.
**READY**
YES - Though I doubt it will affect anyone. There is now no longer a default value for the target and the IDE. It will now error if neither of them are provided.
@theotherjimmy - Could you please make sure I haven't done anything with argparse settings?
@0xc0170 and/or @sarahmarshy - Will removing the default target and IDE cause any issues to your knowledge?
> Remove default -m and -i options for project.py

- tools/test/export/build_test.py
#3486 removed the clean argument, but forgot to update the build_test 
**READY**
https://github.com/ARMmbed/mbed-os/pull/3486
/morph export-build
> Remove deprecated clean argument

- targets/TARGET_STM/stm_spi_api.c
Fixes an SPI issue as reported here:  #3501
Also applicable to other NUCLEO boards tested on -ci-test-shield
Note:
To have the test completely PASS on NUCLEO_L476RG, this PR on ci-test-shield repo is also needed  https://github.com/ARMmbed/ci-test-shield/pull/21
Otherwise the test would fail at the "SPI - Object Definable" step.
In case Rx is not initialized its content might be random from stack.
This is causing problem in case of 8 bits read only as the left-side 8 bits
of the returned int value may contain this random byte data. This was for
instance detected when using SDFileSystem Lib.
READY
+-----------------------+---------------+---------------+------------------------+--------+--------+--------+--------------------+
| target                | platform_name | test suite    | test …
> STM: SPI: Initialize Rx in spi_master_write

- targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K64F/dma_reqs.h
- targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K64F/serial_api.c
- targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/api/objects.h
- targets/targets.json
K64F: Add support for SERIAL ASYNCH API
**READY
Tested both DMA and interrupt implementation using test code from below link:
https://developer.mbed.org/teams/SiliconLabs/code/Serial-LowPower-Demo/file/7136baf24c9c/main.cpp
> K64F: Add support for SERIAL ASYNCH API

- features/FEATURE_LWIP/lwip-interface/lwip_stack.c
Some error codes in TCP connect were being remapped incorrectly
```
condition               posix error     mbed error
good host, closed port  ECONNREFUSED    NSAPI_ERROR_NO_CONNECTION
bad host                EHOSTUNREACH    NSAPI_ERROR_NO_CONNECTION
bad network             ENETUNREACH     NSAPI_ERROR_NO_CONNECTION
```
Thanks to @infinnovation for finding this, verified with their test program in https://github.com/ARMmbed/mbed-os/issues/3246
cc @infinnovation, @c1728p9 
should resolve https://github.com/ARMmbed/mbed-os/issues/3246
> lwip - Fixed error codes for failed TCP connect

- rtos/rtx2/mbed_rtx_conf.h
Please review, this PR is against feature branch. Stack stats are part of the RTX API, however they have to be enabled otherwise 0 is returned.
An example:
```
uint32_t stack_size = osThreadGetStackSize(current_id);
uint32_t stack_space = osThreadGetStackSpace(current_id);
```
Tested with k64f, and -DMBED_STACK_STATS_ENABLED to get stack sizes via the API provided above
@bulislaw @c1728p9
> Stack watermark enable for mbed

- rtos/rtx2/TARGET_CORTEX_M/rtx_config.h
This patch is for feature_cmsis5 branch. 
Test tests-mbedmicro-rtos-mbed-malloc for ARMCC passing with this patch. ARMCC guide
says that these functions are weakly linked. This attribute used to be
in RTX for _mutex_* functions (therefore this test passes on master). Only _mutex_initialize is strongly linked thus no change there. Reference: http://www.keil.com/forum/16315/
The issue is created at CMSIS_5 repo for proper fix that we can propagate later.
Before this patch:
```
+----------+---------------+----------------------------------+----------------------------------+--------+--------+--------+--------------------+
| target   | platform_name | test suite                       | test case                        | passed | failed | result | elapsed_time (sec) | …
```
> RTX2: _mutex_* functions to be strongly-linked

- events/equeue/equeue_mbed.cpp
For equeue_sema_wait, -1 is used to indicate an infinite wait. This wasn't handled in the nonrtos implementation and caused undefined/weird behaviour after an overflow on integer multiplication.
On most boards, the infinite wait would return after ~50 days, on the STM32F4 the timeout killed all other timeouts for some reason.
tested on NUCLEO_F401RE
should resolve #3543
mirrored on https://github.com/ARMmbed/mbed-events/pull/27
cc @DavidPowell
> events - Fix overflow of timeout on STM32F4

- tools/export/exporters.py
Update exporter grouping code to group by directories in the root of the project rather than by the parent directory of each file. This reduces the number of groups and allows all mbed-os code to reside in its own folder.
> exporters - group by directories in prj root

- targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_K66F/drivers/fsl_enet.c
- targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_K66F/drivers/fsl_enet.h
- targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K64F/drivers/fsl_enet.c
- targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K64F/drivers/fsl_enet.h
This PR is a fix for issue 3358
https://github.com/ARMmbed/mbed-os/issues/3358
**READY
[ ] Tests
Ran the NET tests on K64 and K66 FRDM boards.
> MCUXpresso: Fix ENET driver to enable interrupts after interrupt handler is set

- tools/test/examples/update.py
as specified in the supplied .json file, in a user specified fork.
A pull request is then made from each fork to the ARMmbed master repo.
New usage:
python update.py <args>
Where <args> are:
[-c <file.json>] optional argument for example list, default
example.json
-U <github user with forked repos>
-T <github authorisation token>
tag
> Modify update command to directly edit the mbed-os.lib files for each example

- tools/export/cdt/pyocd_settings.tmpl
1. Pass the `DEBUG=1` flag to `make` for projects exported to Eclipse. Together with #3530 this enables builds with debug symbols from Eclipse again.
2. Enable symbol loading when starting a debug session.
@theotherjimmy
> Eclipse debug fixes (build w/ DEBUG=1 and load symbols)

- targets/TARGET_STM/sleep.c
Some code in deepsleep procedure has been wrongly deleted during code factorization procedure in https://github.com/ARMmbed/mbed-os/pull/3316
READY
https://github.com/ARMmbed/mbed-os/issues/3542
> STM32L4 deepsleep improvement

- targets/TARGET_RENESAS/TARGET_RZ_A1H/i2c_api.c
- targets/TARGET_RENESAS/TARGET_VK_RZ_A1H/i2c_api.c
Previously, when "length = 0" as failsafe, "return 0" is executed.
But we changed so that only START bit and STOP bit are executed same as other devices.
> Fix I2C driver for RZ/A1H

- tools/export/uvision/__init__.py
- tools/export/uvision/uvision.tmpl
> Alphabetize UVision groups

- targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K64F/serial_api.c
This PR fixes the issues highlighted in the below issue:
https://github.com/ARMmbed/mbed-os/issues/3535
**READY
Ran the test that was included in the PR, below is the output:
Hello and welcome to serial DMA fun!
_________________________________
-------- dma_serial_write_async_without_dma -------Howdy
Congratulations! You've made it through the gauntlet!
Sorry, looks like we hung.
________________________________
The last line is printed even for a pass as it is the result of a 2 second timer that is activated in the test
> K64F UART Asynch API: Fix synchronization issue

- targets/targets.json
Turn on the vector checksum on all LPC4088 variants. This checksum is required for an application to boot.
> LPC4088 - Fix vector checksum

- targets/TARGET_STM/TARGET_STM32F0/i2c_device.h
- targets/TARGET_STM/TARGET_STM32F3/i2c_device.h
- targets/TARGET_STM/TARGET_STM32F7/i2c_device.h
- targets/TARGET_STM/TARGET_STM32L0/i2c_device.h
- targets/TARGET_STM/TARGET_STM32L4/i2c_device.h
When building with the debug profile, certain ST plaforms error with
'get_i2c_timing' not being defined. This is because the function is not
defined as 'static inline', but just 'inline'.
**READY**
NO
Should fix the current export-build CI failure on #3534 
@LMESTM Would you double check this change since you were working on I2C for ST platforms?
@geky Would you please check this since you're a wizard at all things C/C++? :smile:
> Fixes linking errors when building with debug profile

- targets/targets.json
Dragonfly was failing RTC unit tests b/c RTC_LSI wasn't explicitly specified in targets.json and LSE is no longer populated by default. This PR sets RTC_LSI macro for Dragonfly builds so RTC is functional.
**READY**
> fix failing RTC initialization for MTS_DRAGONFLY_F411RE

- tools/export/iar/__init__.py
- tools/export/uvision/__init__.py
- tools/export/uvision/uvision.tmpl
- tools/options.py
- tools/project.py
This PR will turn on flags for debug symbols for all exporters. 
It also removes optimization flags from the compiler flags, as those are set in the IDE by the user. If they exist as a hard-coded flag, the user will not be able to use the IDE to turn them off, and instead will have to manually search through the considerably long compiler flags to turn them off (if they realize they their IDE setting did nothing). Not a big deal in some exporters, but uvision makes them into a single text box in the GUI, so you just have to arrow over. 
@janjongboom @theotherjimmy 
**READY**
Now, if users *do not* want debug flags when exporting, they should use:
`mbed export --profile default`
Related: #3532 
This is a more generalized version for *all* the exporters.
> Turn on debugging by default when exporting. Remove optimizations for IAR and Uvision

- features/FEATURE_LWIP/TESTS/mbedmicro-net/tcp_echo_parallel/main.cpp
- features/FEATURE_LWIP/TESTS/mbedmicro-net/udp_echo_parallel/main.cpp
This commit reduces the thread stack from 2k to 1k for each thread in
the parallel network tests. This allows the tests to run on more
constrained devices (like the LPC1768).
**READY**
NO
> Reduce thread stack size for parallel network tests

- tools/toolchains/__init__.py
Separate the logic for managing the ignores lists from the scan resources calls. Improves the speed of the scan by ignoring all subdirectories of an ignored directory instead of just the files. Allows ignores to be specific to a basepath. This is useful to the online compiler as it can change the basepath to allow ignores to affect imported libraries despite them not being a subdirectory of the project.
**READY**
> Refactor scan resources to account for base_paths

- tools/export/exporters.py
Assert that the length is greater than one rather than the value itself. This bug was introduced in the commit:
329be06ad02b82e045c1aadc799f88005276400a -
"exporters - group by directories in prj root"
> Fix invalid assert in exporters

- targets/targets.json
- tools/targets.py
> Target system - Inherit names from target parents

- tools/build.py
Commit 19d56fd40fc3130b970e03fd530ab340d4a65465 removed the default file
paths for the toolchains. This was done under the assumption that the
top-level compile scripts were properly checking that the toolchain
executable was availble. The build.py script was doing this in the wrong
place. This commit rearranges the script a bit so the check is performed
properly.
Should fix #3581.
**READY**
NO
@toyowata - Could you please confirm that I've fixed your issue?
@theotherjimmy - General code review please!
> Fixing toolchain executable not found error for build.py

- tools/arm_pack_manager/__init__.py
Fix tracebacks from trying to read dictionary values that don't exist and from incorrect variable names.
> arm-pack-manager - fix tracebacks

- tools/export/makefile/Makefile.tmpl
Allow `LINKER_SCRIPT` overrides via:
> `make LINKER_SCRIPT=something.ld -f Makefile`
The user can then set aside a block of flash memory for production config data by customizing the linker script like so: https://vilimpoc.org/blog/2016/12/25/flash-based-configuration-data-using-the-ld-linker/
> Allow user overrides of LINKER_SCRIPT Make variable

- targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K22F/trng_api.c
- targets/targets.json
Enabling TRNG driver. This should address the below issue:
https://github.com/ARMmbed/mbed-os/issues/3579
Ran the mbed tests on K22F FRDM board.
> K22F: Enable TRNG

- tools/export/makefile/Makefile.tmpl
- tools/export/makefile/__init__.py
- tools/export/makefile/make-gcc-arm.tmpl
- tools/toolchains/__init__.py
- tools/toolchains/arm.py
Refactor toolchains to use a common sys_libs variable. This allows the exporters to rely on that information.
**READY**
##Todos
> [toolchains] Refactor sys libs

- targets/TARGET_NORDIC/TARGET_NRF5/TARGET_MCU_NRF51822_UNIFIED/TARGET_DELTA_DFCM_NNN50/PinNames.h
- targets/TARGET_NORDIC/TARGET_NRF5/TARGET_MCU_NRF51822_UNIFIED/TARGET_DELTA_DFCM_NNN50/device.h
- targets/TARGET_NORDIC/TARGET_NRF5/TARGET_MCU_NRF51822_UNIFIED/TARGET_DELTA_DFCM_NNN50/mbed_overrides.c
- targets/targets.json
greentea tests are all passing
mbedgt: test case results: 175 OK
Please kindly review this PR
> Add DELTA_DFCM_NNN50 platform

- tools/export/cmsis/cpdsc.tmpl
- tools/export/exporters.py
- tools/export/iar/__init__.py
- tools/export/iar/ewp.tmpl
- configure the jinja Environment to raise exception when substitution
variables are not defined
- trim spaces and lines, to avoid empty lines in generated files
> Exporters: make jinja engine strict

- features/FEATURE_LWIP/TESTS/mbedmicro-net/host_tests/udp_shotgun.py
MacOS doesn't like the `s.connect((target_ip, 0))` any port construct and the tests are failing. Fix doesn't change the default behavior but provides a fallback.
**READY**
@bridadan @geky
> tests: Fix error on MacOS for udp_dtls_handshake test

- targets/TARGET_Silicon_Labs/TARGET_EFM32/TARGET_EFM32GG/device/TARGET_1024K/TOOLCHAIN_GCC_ARM/efm32gg.ld
A copy paste error snuck into the uVisor related updates to the EFM32GG
linker script. Fix the error by replacing "m_data" with "RAM".
Fixes: 89641bc7e0ce "uVisor: Update K64F and EFM32GG linker scripts"
**READY**
@AlessandroA @0xc0170
> EFM32GG: Fix GCC_ARM linker script

- targets/TARGET_STM/i2c_api.c
The temporary variable tmpreg was not used to set the new configuration and as a consequence this new configuration was not taken into account in the CR2 register.
READY
NO
> STM32 I2C : Fix bug in i2c_byte_read function

- features/FEATURE_BLE/targets/TARGET_NORDIC/TARGET_MCU_NRF51822/hal_patch/sleep.c
- mbed.h
- platform/sleep.h
- targets/TARGET_ARM_SSG/TARGET_BEETLE/sleep.c
- targets/TARGET_Atmel/TARGET_SAM_CortexM0P/sleep_api.c
- targets/TARGET_Atmel/TARGET_SAM_CortexM4/sleep_api.c
- targets/TARGET_Freescale/TARGET_K20XX/sleep.c
- targets/TARGET_Freescale/TARGET_KLXX/sleep.c
- targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/api/sleep.c
- targets/TARGET_Maxim/TARGET_MAX32600/sleep.c
- targets/TARGET_Maxim/TARGET_MAX32610/sleep.c
- targets/TARGET_Maxim/TARGET_MAX32620/sleep.c
- targets/TARGET_Maxim/TARGET_MAX32625/sleep.c
- targets/TARGET_NORDIC/TARGET_MCU_NRF51822/sleep.c
- targets/TARGET_NORDIC/TARGET_NRF5/sleep.c
- targets/TARGET_NUVOTON/TARGET_M451/sleep.c
- targets/TARGET_NUVOTON/TARGET_NUC472/sleep.c
- targets/TARGET_NXP/TARGET_LPC11U6X/sleep.c
- targets/TARGET_NXP/TARGET_LPC11UXX/sleep.c
- targets/TARGET_NXP/TARGET_LPC11XX_11CXX/sleep.c
- targets/TARGET_NXP/TARGET_LPC13XX/sleep.c
- targets/TARGET_NXP/TARGET_LPC176X/sleep.c
- targets/TARGET_NXP/TARGET_LPC408X/sleep.c
- targets/TARGET_NXP/TARGET_LPC43XX/sleep.c
- targets/TARGET_NXP/TARGET_LPC81X/sleep.c
- targets/TARGET_NXP/TARGET_LPC82X/sleep.c
- targets/TARGET_STM/sleep.c
- targets/TARGET_Silicon_Labs/TARGET_EFM32/sleep.c
- targets/TARGET_WIZNET/TARGET_W7500x/sleep.c
- targets/TARGET_ublox/TARGET_HI2110/sleep.c
Add sleep/deepsleep functions to platform layer which are replacing HAL
functions with the same name, rename existing symbols in HAL layer
to hal_sleep/hal_deepsleep. This way sleep functions
are always available, even if target doesn't implement them, which makes
the code using sleep clearer. It also enables us to make decision on in
which builds (debug/release) the sleep will be enabled.
**READY**
https://github.com/ARMmbed/mbed-os/pull/3566
CC: @0xc0170 @sg- @betzw
> Platform: Add sleep/deepsleep user facing functions

- drivers/FileSystemLike.h
- features/TESTS/filesystem/basic/basic.cpp
- features/TESTS/filesystem/fopen/fopen.cpp
- features/filesystem/README.md
- features/filesystem/fat/FATFileSystem.cpp
- features/filesystem/fat/FATFileSystem.h
- features/filesystem/test/fsfat_debug.h
- features/filesystem/test/fsfat_test.c
- features/filesystem/test/fsfat_test.h
- platform/retarget.cpp
This PR includes:
- fixes for the PAL team
These are the file system/mbed storage commits of interest in this PR:
```
* 1bed055 Updated filesystem README.md.
* 0f4ce2b Added errno codes to retarget, mkdir() and ftell() tests.
* 3ef1374 Filesystem: Added EEXIST reporting to mkdir through errno
* 359725c STORAGE: tests added for errno, ferror() and clearerr().
* a082218 FILESYSTEM: fopen() and basic test improvements.
* 40db0f5 Filesystem: Removed dependency on unistd.h
* d41562a Filesystem: Add support for stat
```
> Feature storage: Adding fopen(), EEXIST errno fixes for PAL team 

- rtos/rtx/TARGET_CORTEX_A/RTX_Conf_CA.c
- rtos/rtx/TARGET_CORTEX_A/rt_CMSIS.c
In CI, I receive an mbed assert of stack stats by running the following commands. Its assert is TIMEOUT.
```
mbed test -m RZ_A1H -t GCC_ARM -DMBED_STACK_STATS_ENABLED=1 --clean --compile
mbed test -m RZ_A1H -t GCC_ARM --run -n tests-mbed_drivers-stl_features -v
```
So, I fixed the process of related to stack stats (`osThreadInfoStackMax`).The Detail contents is here.
https://github.com/ARMmbed/mbed-os/issues/3273#issuecomment-268407191
> Fix Stack stats by running the test command with "-DMBED_HEAP_STATS_ENABLED=1"

- targets/TARGET_STM/TARGET_STM32F3/spi_api.c
- targets/TARGET_STM/i2c_api.c
2 fixes of compilation warnings
**READY**
Compilation of all STM targets OK.
> Fix warnings

- targets/TARGET_RENESAS/TARGET_VK_RZ_A1H/gpio_irq_api.c
Notes:
* missed external IRQ interrupt pin added!
This IRQ is used for signalling 'new data ready' from the touch controller of the VKLCD70RT (which is a companion board for VK_RZ_A1H).
#3632
> Missing IRQ pin fix for platform VK_RZ_A1H

- tools/toolchains/arm.py
- tools/toolchains/gcc.py
- tools/toolchains/iar.py
Before the toolchains would ignore error messages that contained the
string "Fatal error". This would lead to a silent failure unless the
compile command was ran with verbose options. This is now fixed.
**READY**
NO
> Adding fatal error detection to toolchains

- tools/export/uvision/__init__.py
- tools/export/uvision/uvision.tmpl
Add the correct output to the Core tag of Target Options within the
Uvision project file template
**READY**
https://github.com/ARMmbed/mbed-cli/issues/427
> [Exporters] Add core to uvision exporter template

- targets/TARGET_NORDIC/TARGET_MCU_NRF51822/sleep.c
Fixes a conflict between NRF51822 and DELTA_DFCM_NNN40.
Fix https://github.com/ARMmbed/mbed-os/issues/3672
@0xc0170 @sarahmarshy
> NRF51822: HAL: Restore WEAK declaration for hal_(deep)sleep

- platform/toolchain.h
Allow the section that code is placed in to be explicitly specified with the attribute MBED_SECTION.
> Add MBED_SECTION attribute

- tools/toolchains/arm.py
On the ARM toolchain linker flags specified in the build profile do not get passed to armlink. This patch adds these flags to the arguments sent to armlink.
> ARM - pass linker flags along to the linker

- docs/build_profiles.md
- rtos/rtos_idle.c
While waiting for tickless mode being implemented & stable, put system to sleep when going idle.
**READY**
**NO**
**#3607**
#3602 
#3693
> Put system to sleep when going idle

- tools/memap.py
Notes:
With this change the detailed option can also be applied to mbed os modules
**READY**
> Memap detailed function also for mbed os modules

- targets/TARGET_STM/i2c_api.c
This I2C IP is meant for automatic STOP, based on programmed number
of bytes to be sent or receivede, not a user triggered STOP.
So the state machiine needs to be reset in case we use this I2C mbed
unitary API (start / byte_write / byte_read / stop).
This PR allows to solve some remaining issues with i2c ci test shield on L4 / F3 / F7 boards.
##TESTS RESULTS
+----------------------+---------------+---------------+------------------------------------+--------+--------+--------+--------------------+
| target               | platform_name | test suite    | test case                          | passed | failed | result | elapsed_time (sec) |
+----------------------+---------------+---------------+------------------------------------+--------+--------+--------+--------------------+
| …
> STM32: I2C: reset state machine

- tools/synch.py
Fixed issue where some deleted files/folders where not being removed from
the repo.
Removed code no longer used/needed.
> Updated to allow for new directory structure for mbed-dev source.

- drivers/DirHandle.h
- features/TESTS/filesystem/fat_file_system/main.cpp
- features/filesystem/fat/FATDirHandle.cpp
This PR is a 1 line fix for #3705 and submitted to check whether there are any other CI breakages cause by commit:
```
Added d_type member of dirent struct to readdir 
```
> STORAGE: Pr 3705 fix for fat_file_system test missing symbols

- cmsis/core_cmSecureAccess.h
- features/FEATURE_UVISOR/includes/uvisor-lib/rtx/rtx_box_index.h
This issue was found when trying to integrate the GNU ARM Eclipse exporter PR here: https://github.com/ARMmbed/mbed-os/pull/3561
There are a few files that build fine in ALL the other build systems (seriously, the mbed build system, make exporters, IAR, AND uVision all work just fine) but that cause issues in the new Eclipse exporter. This seems to be related to build order.
These changes just add explicit includes in files that were causing issues.
**READY**
NO
This is currently blocking #3561 from coming in.
@Patater and/or @AlessandroA Are there other files where we should add these explicit includes?
> Fixing uvisor defines to fix build issues

- targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K64F/device/TOOLCHAIN_GCC_ARM/MK64FN1M0xxx12.ld
- targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F429xI/device/TOOLCHAIN_GCC_ARM/STM32F429xI.ld
- targets/TARGET_Silicon_Labs/TARGET_EFM32/TARGET_EFM32GG/device/TARGET_1024K/TOOLCHAIN_GCC_ARM/efm32gg.ld
With the RTOS, the STACK_SIZE specified here is unrelated to the stack
size available for the main thread (that runs pre_main). Save memory by
reducing the stack size to a more reasonable amount.
On uVisor, HEAP_SIZE is both a minimum available and maximum available
heap size. The heap can't grow beyond the end of the heap into the
neighboring stack. On all uVisor-supported platforms, guarantee at least
0x6000 bytes of heap space. This increases the portability of uVisor
applications as the memory available for legacy heap allocations is
guaranteed. This helps to avoid out of memory errors on platforms that
were previously guaranteeing less memory.
**READY**
@0xc0170 @AlessandroA
> uVisor: Standardize available legacy heap and stack

- tools/toolchains/gcc.py
GCC Assembler errors were being missed because it prints 'error' with a captial 'E'. This change allows the 'e' to be either lower case or upper case.
**READY**
NO
This may conflict with https://github.com/ARMmbed/mbed-os/pull/3653
Before, the tools would miss errors like the following when it was printed from the assembler:
```
/tmp/ccXLitIR.s: Assembler messages:
/tmp/ccXLitIR.s:677: Error: cannot honor width suffix -- `mov r1,#0'
/tmp/ccXLitIR.s:679: Error: cannot honor width suffix -- `mov r0,#0'
/tmp/ccXLitIR.s:727: Error: cannot honor width suffix -- `mov r1,#4'
/tmp/ccXLitIR.s:729: Error: cannot honor width suffix -- `neg r1,r1'
/tmp/ccXLitIR.s:731: Error: cannot …
```
> Adding case insensitive 'error' detection

- .travis.yml
- targets/targets.json
- tools/export/iar/__init__.py
- tools/export/iar/iar_definitions.json
- tools/test/targets/target_test.py
Add a CI test ensure that device_name exists inside the pack index.
> Enforce device_name is valid in targets.json

- tools/export/makefile/Makefile.tmpl
- tools/export/makefile/__init__.py
- tools/toolchains/gcc.py
This allows us to define parts of the linker script outside of the linker script itself. In particular, we are interested in restricting ROM to a subsection.
> Use the C Pre-Processor on GCC Linker scripts

- targets/TARGET_ONSEMI/TARGET_NCS36510/spi_api.c
SPI format function bugs fixed.
**READY**
SPI slave feature can be used.
This PR is one of the feature(SPI) from #3611. So PR #3611 will be invalid and can be closed.
No changes required
Can be tested with SPI ci-test-shield tests
> NCS36510: spi_format function bug fix

- tools/test_api.py
The worker_result variable was not guaranteed to have a `'result'` or `'reason'` key and accessing them before testing for them could result in an error when they are not provided. This patch changes the checks to prevent check for their existence before accessing them.
Moved this commit from #3706
> Fix access before variable defined bug in test_api

- tools/toolchains/__init__.py
- tools/toolchains/arm.py
- tools/toolchains/gcc.py
- tools/toolchains/iar.py
Create an API for generating the linker flags needed to redirect functions in an application. Linker redirection isn't currently being used but the PR here is to bring these changes main line since they will likely be useful in the future. This patch also adds support for linker flags, which is required for bootloader support.
> Add redirect support to toolchains

- features/unsupported/USBDevice/USBAudio/USBAudio.cpp
This PR fixes USB EP setting error in USBAudio library for NUC472/M453. It is because NUC472/M453 USB doesn't support configuration of the same EP number for IN/OUT simultaneously.
> [NUC472/M453] Fix USB EP setting error in USBAudio

- targets/TARGET_NUVOTON/TARGET_M451/TARGET_NUMAKER_PFM_M453/objects.h
- targets/TARGET_NUVOTON/TARGET_M451/device/TOOLCHAIN_GCC_ARM/m451_retarget.c
- targets/TARGET_NUVOTON/TARGET_M451/sleep.c
- targets/TARGET_NUVOTON/TARGET_M451/us_ticker.c
- targets/TARGET_NUVOTON/TARGET_NUC472/TARGET_NUMAKER_PFM_NUC472/objects.h
- targets/TARGET_NUVOTON/TARGET_NUC472/device/TOOLCHAIN_GCC_ARM/nuc472_retarget.c
- targets/TARGET_NUVOTON/TARGET_NUC472/sleep.c
- targets/TARGET_NUVOTON/TARGET_NUC472/us_ticker.c
- targets/TARGET_NUVOTON/nu_miscutil.h
- tools/export/iar/iar_definitions.json
This PR includes support for exporting IAR project and other bugfixes for NUMAKER_PFM_NUC472 and NUMAKER_PFM_M453 targets.
> [NUC472/M453] Export IAR project and other bugfixes

- targets/TARGET_STM/sleep.c
The LPR was not turned on when entering into STOP2. Now the deepsleep mode on the STM32L4 Nucleo board needs only 1.6uA instead of 10uA.
This is described in the STM RM0351 Reference manual, Section PWR registers BIT-14
Note: Stop 2 mode cannot be entered when LPR bit is set. Stop 1 is entered instead.
I am pretty happy that I figured this out.
Regards Helmut
> Fixed a problem that the STOP2 was falling back to STOP1

- features/filesystem/fat/FATFileSystem.cpp
Picked up by 'FSFAT_FOPEN_TEST_16: write/check n x 25kB data files.'
Static buffer was too small, simple fix.
cc @simonqhughes
> Filesystem: Fix buffer overflow in FATFileSystem::open 

- features/filesystem/bd/BlockDevice.cpp
- features/filesystem/bd/BlockDevice.h
- features/filesystem/bd/ChainingBlockDevice.cpp
- features/filesystem/bd/ChainingBlockDevice.h
- features/filesystem/bd/HeapBlockDevice.cpp
- features/filesystem/bd/HeapBlockDevice.h
- features/filesystem/bd/SlicingBlockDevice.cpp
- features/filesystem/bd/SlicingBlockDevice.h
- features/filesystem/fat/FATDirHandle.cpp
- features/filesystem/fat/FATDirHandle.h
- features/filesystem/fat/FATFileHandle.cpp
- features/filesystem/fat/FATFileHandle.h
- features/filesystem/fat/FATFileSystem.cpp
- features/filesystem/fat/FATFileSystem.h
- features/filesystem/fat/FATMisc.cpp
- features/filesystem/fat/FATMisc.h
mbed classes should be in the mbed namespace, no technical reason these weren't, we just hadn't gotten to them yet.
cc @simonqhughes
@theotherjimmy (let me know if I did the doxygen group wrong)
> Filesystem: Add mbed namespace to FATFileSystem and BlockDevice classes

- tools/memap.py
Issue #3711
**READY**
NO
mbed compile -t GCC_CR
> add GCC_CR as toolchain for memmap

- targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_rtc_ex.c
STM32L4 HAL update for RTC Wake Up Timer
This will be in the next official ST Cube driver delivery
READY
> STM32L4 HAL update for RTC Wake Up Timer

- tools/export/makefile/__init__.py
Before, `make_gcc_arm` would export a makefile with both linker flags in
the `$(LD)` make variable and the `$(LD_FLAGS)` make variable. This only
affected GCC based makefiles, as the `$(LD)` make variable would only
contain the linker for both ARMC5 and IAR. This patch enforces the
`$(LD)` behavior of ARMC5 and IAR on all of the compilers by truncating
`$(LD)` to just the command.
Resolves #3744
> Pass linker flags to the linker only once

- platform/mbed_board.c
MBED_CONF_PLATFORM_STDIO_CONVERT_NEWLINES was not used in mbed_error_vfprintf causing wrong behavior when the option was selected (no new line is some terminals like putty).
READY
mbed user: yariv colbeci
> fix in mbed_error_vfprintf

- features/FEATURE_LWIP/lwip-interface/lwip_stack.c
Added filtering to send minus event to lwip adaptation layer. Send minus events should not be conveyed to upper layers since they indicate that socket send would block on next call. Also in case of would block on sending, minus events can generate sending loop, where send minus event triggers new send in application.
READY
NO
None
None
None
> Added filter to send minus events to lwip adaptation

- features/unsupported/USBDevice/USBHID/USBHID.cpp
- features/unsupported/USBDevice/USBHID/USBHID_Types.h
- features/unsupported/USBDevice/USBHID/USBKeyboard.cpp
- features/unsupported/USBDevice/USBHID/USBMouse.cpp
While debugging for another issue, I made some formatting changes to existing code to better understand it myself.
* Changed generic USBHID report descriptor to use predefined macros for descriptor field types/sizes which are already used in USBMouse and USBKeyboard. Compiled result is identical to previous code.
* Tweaked configuration descriptor formatting so they can be more easily diffed
* Defined the remaining HID sublasses and protocols to provide give context to magic values
* Aligned comments
* Cleaned up redundancies in comments
**READY**
NO
CLA has been signed https://developer.mbed.org/users/ingram/
> Improve readability of USBHID related descriptors

- features/FEATURE_LWIP/TESTS/mbedmicro-net/host_tests/udp_shotgun.py
The speed of packets on the local network exceeds even the speed of the ethernet hardware on some of the less powerful devices. Adding a small delay which can be expected from a real DTLS handshake prevents this condition from occuring.
Let me know if there is still problems with this test as this delay may need to be refined.
cc @bridadan, @MarceloSalazar 
should resolve https://github.com/ARMmbed/mbed-os/issues/3549
> lwip: Added delay to dtls handshake test to compensate for local network

- TESTS/mbed_drivers/flashiap/main.cpp
- drivers/FlashIAP.cpp
- drivers/FlashIAP.h
Remove write function since this is not portable across targets and fix tests.
> Remove non-portable code from FlashIAP

- targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F746xG/TARGET_DISCO_F746NG/system_stm32f7xx.c
- targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F769xI/TARGET_DISCO_F769NI/system_stm32f7xx.c
- targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_conf.h
STM32F7 : remove multiple HSE_VALUE define value
READY
> STM32F7 : remove multiple HSE_VALUE define value

- targets/TARGET_STM/stm_spi_api.c
This fix address issue #3735
In case of prescaler_rank was 0, a -1 index was being used,
which resulted in initialization of the Init.BaudRatePrescaler with
random values.
Now let's better check index and avoid -1 operation, so that prescaler_rank
can be only from 0 to "last_index".
**READY**
Tested with various range of clock on L4 device, including max frequency as reported in the Issue
> STM32: spi_frequency table index fix

- features/unsupported/USBDevice/USBDevice/TARGET_STM/USBHAL_STM32F769NI.h
- features/unsupported/USBDevice/USBDevice/TARGET_STM/USBHAL_STM32L476VG.h
- features/unsupported/USBDevice/USBDevice/TARGET_STM/USBHAL_STM_144_64pins.h
Refer to issue #3756 
USB TX fifo is missing 1 for parameter length transmission
**READY**
NO
copy/paste the main example provided in the issue inside : features/unsupported/tests/usb/device/raw_hid/main.cpp
python tools/build.py --usb --rtos -m NUCLEO_F446ZE  -t GCC_ARM
python tools/make.py -m NUCLEO_F446ZE -t GCC_ARM --profile=debug -n USB_5
drag and drop the binary
> Fix #3756 for 64 bytes transfers

- TESTS/events/queue/main.cpp
- TESTS/events/timing/main.cpp
- events/equeue/equeue_mbed.cpp
- targets/TARGET_ONSEMI/TARGET_NCS36510/ncs36510_us_ticker_api.c
Whew, this was a long bug. Sorry for the delay.
Here's the history of the bug: https://github.com/ARMmbed/mbed-os/issues/3404, it's been causing small problems on the CI, but takes a while to pop up, proved difficult to nail down.
This patch has three parts:
- c0951c9 Fix the NCS36510 timer issue
- 1f9e239 Add tests to better check the low-level integration between mbed-events and hardware timers
- 0949164 Make mbed-events more tolerant of these sort of timing errors
As for exactly what the timing bug was:
> The NCS36510 is limited to 16bit timers. Construction of larger intervals is performed in software by counting the number of 16bit intervals that pass.
> 
> Either this counting takes a bit of time, or there is a math error somewhere (maybe a long critical section?), because there is …
> NCS36510: Fix the sporadic semaphore timing issue

- TESTS/events/queue/main.cpp
- events/Event.h
- events/EventQueue.h
While limitations in type inference prevent the event helper from infering the type of generic function objects, there is nothing technical preventing inference from the Callback class, where the function type is encoded in the template parameters.
With adoption of the Callback class as the standard function representation, it makes sense to support events created from callback objects.
This use case came up in client code that used a separate type for function pointers.
cc @pan- (I'm ccing you on anything with this much template stuff)
> events: Add support for infering event type from Callback objects

- drivers/InterruptIn.cpp
- drivers/SerialBase.cpp
- drivers/Ticker.cpp
- drivers/Ticker.h
- features/netsocket/Socket.cpp
- platform/Callback.h
The attach function is used several other places to indicate registration for interrupts. This differs significantly to its use in the Callback class. Additionally, the attach function is unnecessary given that simple assignment works just as well.
@pan-, I think this was being tracked in an issue of yours, but I can't find it now.
Hopefully we'll get a good chance to remove the bulk of these functions soon.
cc @pan-
> Callback: Deprecate attach member function in favor of simple assignment

- features/netsocket/Socket.cpp
- features/netsocket/Socket.h
Currently the Socket::attach function behaves differently than other attach functions in the mbed codebase.
There is quite a bit of discussion on the future of asynch socket apis (related issue https://github.com/ARMmbed/mbed-os/issues/3620), and given the current focus of mbed OS, I think it will take some time before we see a full-featured async user api mainlined.
In the meantime, I would like to change the name of the function to hopefully **1:** reduce some of the confusion around it and **2:** free up the attach name to potentially be used for a full-fledge async api in the future:
``` cpp
/** Register a callback on state change of the socket
*
*  The specified callback will be called on state changes such as when
*  the socket can recv/send/accept successfully and on when an error …
```
> nsapi: Rename attach -> sigio to decrease confusion on its behaviour

- TESTS/mbedmicro-rtos-mbed/mutex/main.cpp
Rework and extend RTOS mutex wrapper class tests.
**READY**
`mbed test -n tests-mbedmicro-rtos-mbed-mutex`
> Rework RTOS mutex tests

- targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F429xI/TARGET_NUCLEO_F429ZI/system_stm32f4xx.c
- targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F429xI/device/cmsis_nvic.c
- targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F429xI/device/nvic_addr.h
- targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F429xI/device/system_init_pre.c
- targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F439xI/TARGET_NUCLEO_F439ZI/system_stm32f4xx.c
- targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F439xI/device/cmsis_nvic.c
- targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F439xI/device/nvic_addr.h
- targets/TARGET_STM/TARGET_STM32F4/TARGET_UBLOX_EVK_ODIN_W2/device/cmsis_nvic.c
- targets/TARGET_STM/TARGET_STM32F4/TARGET_UBLOX_EVK_ODIN_W2/device/nvic_addr.h
- targets/TARGET_STM/TARGET_STM32F4/TARGET_UBLOX_EVK_ODIN_W2/device/system_stm32f4xx.c
The address of the vector table is hardcoded to the start of flash in many, if not all, ST targets. This causes a crash in applications that are using a bootloader.  This patch updates the boards STM32F429xI,
STM32F439xI and Odin so they properly handle updating the VTOR with a bootloader.
> Fix vector table bug when using bootloader on ST

- mbed.h
- platform/mbed_application.c
- platform/mbed_application.h
Add the function mbed_application_start() which allows a bootloader to transfer control to an application.
> Add a function to transfer control to another app

- targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KL27Z/spi_api.c
- targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KL43Z/spi_api.c
It was always true for valid values (if its not 8 neither 16 bits, fail).
Fixes #2989. Logical error. Tested - compile tests for these 2 platforms.
> NXP KL43Z/KL27Z: fix spi format bits check

- targets/TARGET_RENESAS/TARGET_RZ_A1H/gpio_irq_api.c
I modified the bug in PR #3289. But It seems not enough the changes.
For the reason, It occured the following issue.
https://github.com/ARMmbed/mbed-os/issues/3694
So I reviewed and re-modified about the setting of initial value of interrupt edge in "gpio_irq_init".
> Bug fix of initial value of interrupt edge in "gpio_irq_init" again

- targets/TARGET_STM/sleep.c
Remove compilation warning
Debug capability added
Set back US counter after deepsleep period
READY
> STM32 : minor update in sleep HAL file

- targets/targets.json
- tools/build_api.py
- tools/config.py
- tools/test/build_api/build_api_test.py
- tools/utils.py
To enable a boot-loader style application, overrides
"targets.bootloader_exec" or "targets.restrict_size" on a particular
target. These parameters are a bin or hex file and an integer, in bytes,
respectively. If either override is present, then an application region
is created after the boot-loader region, when "targets.bootloader_exec"
is present, and before post-application, when "targets.restric_size" is
present. The size of the boot-loader region is read from the file
provided in the configuration.
**READY**
> Enable boot-loader builds

- targets/TARGET_STM/rtc_api.c
Add debug capability
Add more detailed information in comments
Issue with sunday corrected
Issue with wrong rtc_isenabled status corrected (https://github.com/ARMmbed/mbed-os/issues/3668)
READY
> STM32 RTC api minor update

- tools/export/uvision/__init__.py
- tools/export/uvision/uvision.tmpl
Recently Keil released version 5.23 of their IDE. This version requires
the FPU to be set as part of the <Cpu> tag in the .uvprojx (XML project
file). This patch adds the appropriate FPU settings based on the
trailing F (FPU enabled) or FD (Double precesion FPU enabled) string of
the core.
- Resolves #3807 
- Resolves https://github.com/ARMmbed/mbed-os-example-wifi/issues/19
- Resolves https://github.com/ARMmbed/mbed-os-example-ble/issues/56
- Resolves https://github.com/ARMmbed/mbed-os-example-sockets/issues/16
- Resolves https://github.com/ARMmbed/mbed-os-example-blinky/issues/47
> Add the FPU field to the <Cpu> tag in Keil

- targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F429xI/TARGET_DISCO_F429ZI/system_stm32f4xx.c
- targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F429xI/TARGET_NUCLEO_F429ZI/system_stm32f4xx.c
- targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F429xI/device/TOOLCHAIN_ARM_MICRO/startup_stm32f429xx.s
- targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F429xI/device/TOOLCHAIN_ARM_STD/startup_stm32f429xx.s
- targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F429xI/device/TOOLCHAIN_IAR/startup_stm32f429xx.S
Startup file have been modified for GCC_ARM since the integration of uvisor.
This modification needs to be ported also for ARM and IAR, even if uvisor is not present on those toolchains.
**READY**
NO
#3397 
Before this PR, any DISCO_F429ZI test was running into timeout with ARM and IAR
Now it works
> fix for issue #3715: correction in startup files for ARM and IAR, alignment of system_stm32f429xx.c files

- targets/TARGET_STM/hal_tick_32b.c
Remove warning in TARGET_STM/hal_tick_32b.c
Add debug capability
Astyle run
READY
> STM32 remove warning in hal_tick_32b.c file

- targets/TARGET_STM/gpio_api.c
Fix #3771 by adding functions to enable GPIOF and GPIOG clocks for STM32L4 targets.
For GPIOG the VDDIO2 external VDD is also activated as it is the one who supply pins PG2 to PG15
> STM32L4 : Fix GPIO G port compatibility

- targets/targets.json
SPISLAVE enabled. 
Conflict resolved
**READY**
SPI slave features can be used.
This PR is one of the feature(SPISLAVE) from #3611. So PR #3611 will be invalid and can be closed.
This PR replaces #3724. Please close #3724
No changes required
Can be tested with SPISLAVE ci-test-shield tests
> NCS36510: SPISLAVE enabled (Conflict resolved)

- features/FEATURE_LWIP/TESTS/mbedmicro-net/gethostbyname/main.cpp
- features/FEATURE_LWIP/TESTS/mbedmicro-net/tcp_echo/main.cpp
- features/FEATURE_LWIP/TESTS/mbedmicro-net/tcp_echo_parallel/main.cpp
- features/FEATURE_LWIP/TESTS/mbedmicro-net/tcp_hello_world/main.cpp
- features/FEATURE_LWIP/TESTS/mbedmicro-net/udp_dtls_handshake/main.cpp
- features/FEATURE_LWIP/TESTS/mbedmicro-net/udp_echo/main.cpp
- features/FEATURE_LWIP/TESTS/mbedmicro-net/udp_echo_parallel/main.cpp
Sometimes when under heavy load, the CI machines can take a significant amount of time to bring up a python process (~10s). The timeouts for the network tests were chosen without much thought, and didn't leave much room for this sort of delay.
This patch brings up timeouts for ntetwork tests 20s -> 60s
cc @bridadan
> lwip: Increase timeout on network tests with python projects

- features/FEATURE_BLE/targets/TARGET_NORDIC/TARGET_MCU_NRF51822/sdk/source/drivers_nrf/pstorage/config/pstorage_platform.h
- targets/TARGET_NORDIC/TARGET_NRF5/sdk/drivers_nrf/pstorage/config/pstorage_platform.h
By default the number of pstorage pages is set 1 and all addresses are calculated in the pstorage module accordingly. Nordic recommends changing this macro to whatever number is suitable for the app ([see this answer from Petter Myhre](https://devzone.nordicsemi.com/question/53066/what-will-be-the-starting-address-of-pstorage-page-how-we-can-change-it/?answer=53085#post-id-53085)) which is not quite elegant given that pstorage_platform.h is part of the mbed-os repo. With this modification you can e.g. define PSTORAGE_NUM_OF_PAGES on the command line, however note that you should rebuild mbed-os with this setting as it affects pstorage_platform.c.
This patch modifies the source for both nRF51 and nRF52 families.
> Allow to redefine nRF's PSTORAGE_NUM_OF_PAGES outside of the mbed-os

- targets/TARGET_STM/pinmap.c
Up to now, speed was set for outputs and alternate, but this is
also valid for input configuration.
By default, let's configure high speed.
This is done first, because speed for some families like F1 is mixed
with Input/Output mode settings, so can be later over-ridden if needed.
**READY**
This is actually a missing piece in GPIO rework done here: #3665
> STM32: gpio SPEED - always set High Speed by default

- targets/TARGET_STM/gpio_object.h
Typo correction to avoid any error for future platforms.
READY
NO
> STM32 GPIO: Typo correction. Update comment (GPIO_IP_WITHOUT_BRR)

- targets/TARGET_STM/stm_spi_api.c
This is the proposed fix to issue #3849 
In case the selected frequency is higher than the requested one, it is
better to send a debug warning rather than an blocking error.
In case of such warning, user may need to redefine the clock tree setting
at higher level (reducing peripheral's input clocks during init phase).
This will avoid to block basic operations that would work anyway with a frequency higher than the requested one.
> STM32: change spi error to debug warning

- targets/TARGET_STM/TARGET_STM32L1/TARGET_XDOT_L151CC/objects.h
Define GPIO_IP_WITHOUT_BRR for xDot platform. Apparently the L151CC doesn't have GPIOx->BRR even though documentation says it does. GPIOx->BSRR must be used instead when setting output pin value to 0. This resolves #3823.
**READY**
> Define GPIO_IP_WITHOUT_BRR for xDot platform

- targets/TARGET_STM/can_api.c
On STM32F4 family, the CAN2 hw instance is using CAN1's filters.
HAL_CAN1_CLOCK_ENABLE must be activated.
This modification is not impacting other STM32 families behavior
**READY**
NO
Use the can autoloop test with only CAN2 activated on DISCO_F469NI
(test name **MBED_A27**, with `CAN can1(PB_5, PB_13);` instead of `CAN can1(PB_8, PB_9);`)
Without the patch, the` can.read `does not work (only write works) and MBED_A27 test is failed
With the patch, can.read works and MBED_A27 test is a success
> DISCO_F469NI: allow the use of CAN2 instance when CAN1 is not activated

- tools/arm_pack_manager/__init__.py
This patch will prevent the `UserWarning: Using slow pure-python
SequenceMatcher. Install python-Levenshtein to remove this warning` from
appearing in your terminal every compile. This seems like the right
thing to do (tm) because it can be very difficult to install
`python-levenshtein` in many environments.
> Ignore FuzzyWuzzy warnings

- rtos/rtx/TARGET_CORTEX_M/RTX_CM_lib.h
If the free memory on a device is small enough then the calculation to determine heap size could underflow to a large value. If this happens then malloc will never return failure and instead will cause a crash on allocation. This patch prevents the underflow so malloc works as expected even with low amounts of free memory.
This resolves #3210
> Prevent underflow in heap size calculation

- features/FEATURE_BLE/targets/TARGET_NORDIC/TARGET_MCU_NRF51822/hal_patch/sleep.c
The `sleep` function as been changed into `hal_sleep` by #3607.
Unfortunately the call to `sleep` in the hal_patch for the NRF51822 has not been
updated to `hal_sleep`. The result was a link time error for targets based on
NRF51822_LEGACY compiling with the mbed OS 5 tree.
**READY**
NO
> [NRF51822] Fix reference to sleep in hal_patch override

- targets/TARGET_STM/can_api.c
This fixes https://github.com/ARMmbed/mbed-os/issues/3792
PS: astyle done
READY
> STM32 CAN API: correct format and type

- targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L476xG/TARGET_DISCO_L476VG/system_stm32l4xx.c
- targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L476xG/TARGET_NUCLEO_L476RG/system_stm32l4xx.c
The APB2 clock was not set to the maximum possible value (80 MHz). The SPI clock can now go up to 40 MHz.
Discussion started in Issue #3735.
READY
NO
> STM32L476xG: set APB2 clock to 80MHz (instead of 40MHz)

- features/filesystem/bd/BlockDevice.h
- features/filesystem/bd/ChainingBlockDevice.cpp
- features/filesystem/bd/ChainingBlockDevice.h
- features/filesystem/bd/HeapBlockDevice.cpp
- features/filesystem/bd/HeapBlockDevice.h
- features/filesystem/bd/SlicingBlockDevice.cpp
- features/filesystem/bd/SlicingBlockDevice.h
From review for https://github.com/ARMmbed/mbed-os/pull/3762, several of the "getter" functions in the block device had the const attribute added. However, we forgot a few, which is especially annoying if they depend on each other.
cc @simonqhughes, @0xc0170
> bd: Fix missing const attributes on functions

- features/FEATURE_UVISOR/importer/Makefile
Fix `uvisor` build issues observed with GNU Make 4.2.1, caused by missing dependencies and wildcard patterns in core libs targets' pre-requisites.
Fixes issue #3905.
Tested successfully for building `uvisor` and `mbed-os` with GNU Make versions 4.2.1 and 3.81, with GCC_ARM toolchain version 6.3.0.
**READY**
NO
None
None
Refer to issue #3905.
> uVisor: Fix 'publish' and core libs dependencies

- targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F746xG/device/TOOLCHAIN_IAR/stm32f746xg.icf
NUCLEO_F746ZG has 319K RAM. But heap size is set to 32K. It is less than 64K minimum required for mbed-tls tls-client example. Moreover, the comment in the linker script says heap is 1/4 and stack is 1/8 of RAM. This is not true. 1/4 of RAM is 79K and 1/8 is 39K. Hence updating heap and stack sizes to correct 1/4 and 1/8 respectively.
NO
branch | PR
Use steps from issue 
https://github.com/ARMmbed/mbed-os-example-tls/issues/54 and
https://github.com/ARMmbed/mbed-os-example-tls/issues/52 @
> Fix heap and stack size for NUCLEO_F746ZG

- platform/mbed_stats.c
It's the same on master (this threadid is represented as uint32_t value). This resolves the error we saw with IAR:
```
[Error] mbed_stats.c@57,0: [Pe513]: a value of type "void *" cannot be assigned to an entity of type "uint32_t"
[ERROR]
stats[i].thread_id = threads[i];
```
@bulislaw
> Feature CMSIS5: stats: cast thread_id fix

- drivers/FileSystemLike.h
- features/unsupported/tests/mbed/file/main.cpp
- platform/mbed_retarget.h
- tools/build_api.py
Some file must have been indirectly including something that brought in `size_t`, since this type is notably missing from the mbed 2 builds. Fixed by including `stddef.h` which includes this definitions.
cc @bridadan
> Fix mbed 2 builds

- drivers/I2C.h
Correct the comment before `I2C::write(int, const char*, int, bool)` specifying the right return values.
**READY**
NO
> Correct return values for `I2C::write(int, const char*, int, bool)`

- rtos/Thread.cpp
- rtos/Thread.h
Calling Thread::start multiple times leads to undefined behavior since the Thread class was not designed to handle this.  Add an assert to trap immediately if Thread::start is called a second time to prevent this behavior.
> Trap earlier when a Thread instance is re-used

- tools/test/toolchains/api.py
- tools/toolchains/gcc.py
Resolves the github issue #3790: Blinky fails to build (on Mac) after
addition of linker script preprocessing feature. Paraphrasing, this
issue is that Homebrew on mac does not install `arm-none-eabi-gcc` in
the same location as `arm-none-eabi-cpp`, the C Pre-Processor. The tools
prior to this commit, and after turning on the pre-processing of the
linker-script will fail on any Mac homebrew installed toolchains.
This commit resolves the above issue by allowing the toolchain's path to
the executable to remain empty after a call to `check_executable`. When
this path is empty, the tools will search the PATH environment variable
for the executable.
> Use PATH env variable when gcc found in PATH

- targets/TARGET_RENESAS/TARGET_RZ_A1H/serial_api.c
Currently, there is the issue in register setting into serial_format().
The issue is that parameter for baudrate setting is initialed zero in this function.
In baudrate  is less 9600bps, the issue occurs. In baudrate  is over 9600, not occurs. When call serial_baud() before serial_format(), baudrate override and set with an incorrect value.
Therefore, I fixed register setting not to set the parameter of baudrate setting in serial_format().
> Fix  mistake register setting in serial_format()

- targets/TARGET_NORDIC/TARGET_NRF5/TARGET_MCU_NRF52832/TARGET_DELTA_DFBM_NQ620/mbed_overrides.c
- targets/targets.json
In targets.json, add lf_clock_rc_calib_timer_interval and
lf_clock_rc_calib_mode_config setting which are essential when using BLE
In mbed_overrides.c, create valuables instead of doing printf, those
valuables are intended to be used for debugging in runtime.
Please kindly review this PR
> [DELTA_DFBM_NQ620] Add RC calibration setting and revise mbed_overrides.c

- targets/TARGET_Silicon_Labs/TARGET_EFM32/common/cmsis_nvic.h
Linker magic was supplying the address of the vector table address into the pound define used in mbed_boot.c for relocating the vector table. mbed_cpy_nvic() expects the plain address to be loaded in the define.
This PR fixes the bug filed in #3903 
CC @bulislaw
> Wrong linker symbol for Silicon Labs VT relocation on CMSIS5 & GCC

- TESTS/mbedmicro-rtos-mbed/threads/main.cpp
- rtos/Thread.cpp
- rtos/Thread.h
New RTX supports naming threads, extend our wrapper to support this new functionality, add tests for the feature.
The change is for feature_cmsis5 branch and can be merged with failing CI.
> CMSIS5: RTOS: Add thread name option to wrapper

- features/FEATURE_LWIP/lwip-interface/lwip-eth/arch/TARGET_NXP/lpc17_emac.c
- rtos/mbed_boot.c
- targets/TARGET_Maxim/TARGET_MAX32630/gpio_irq_api.c
- targets/TARGET_Maxim/TARGET_MAX32630/rtc_api.c
- targets/TARGET_Maxim/TARGET_MAX32630/serial_api.c
- targets/TARGET_Maxim/TARGET_MAX32630/us_ticker.c
- targets/TARGET_NORDIC/TARGET_NRF5/us_ticker.c
Remove unused osTimerDef. This should fix any lpc17xx board in our code base (ARCH PRO, LPC1768). they should be green now
@bulislaw
> Feature cmsis5: Fixes for IAR

- features/TESTS/filesystem/heap_block_device/main.cpp
- features/TESTS/filesystem/util_block_device/main.cpp
Added to block device test during debug of SPIFBlockDevice and I2CEEBlockDevice. Currently this tests is duplicated for all block devices.
- Uses rand to select pseudorandom blocks, slightly better coverage and no longer will intensively wear block zero.
- Added nice printing of sizes
- Added preview of read/write data for debugging
- Added an error mask of where errors occured in block for debugging
> bd: Add randomness to block device test and more debug friendly output

- features/FEATURE_LWIP/lwip-interface/lwip-eth/arch/TARGET_NUVOTON/TARGET_NUC472/nuc472_netif.c
- targets/TARGET_NUVOTON/TARGET_M451/TARGET_NUMAKER_PFM_M453/PeripheralNames.h
- targets/TARGET_NUVOTON/TARGET_M451/TARGET_NUMAKER_PFM_M453/PinNames.h
- targets/TARGET_NUVOTON/TARGET_M451/can_api.c
- targets/TARGET_NUVOTON/TARGET_M451/dma.h
- targets/TARGET_NUVOTON/TARGET_M451/dma_api.c
- targets/TARGET_NUVOTON/TARGET_M451/pwmout_api.c
- targets/TARGET_NUVOTON/TARGET_M451/serial_api.c
- targets/TARGET_NUVOTON/TARGET_M451/spi_api.c
- targets/TARGET_NUVOTON/TARGET_NUC472/TARGET_NUMAKER_PFM_NUC472/PeripheralNames.h
- targets/TARGET_NUVOTON/TARGET_NUC472/TARGET_NUMAKER_PFM_NUC472/PinNames.h
- targets/TARGET_NUVOTON/TARGET_NUC472/analogin_api.c
- targets/TARGET_NUVOTON/TARGET_NUC472/can_api.c
- targets/TARGET_NUVOTON/TARGET_NUC472/dma.h
- targets/TARGET_NUVOTON/TARGET_NUC472/dma_api.c
- targets/TARGET_NUVOTON/TARGET_NUC472/pwmout_api.c
- targets/TARGET_NUVOTON/TARGET_NUC472/serial_api.c
- targets/TARGET_NUVOTON/TARGET_NUC472/spi_api.c
This PR patches for the targets NuMaker-PFM-NUC472 and NuMaker-PFM-M453 and has the following modifications:
1.  Support unique locally administered MAC address.
2.  Refine serial & SPI PDMA code
3.  Refine pwmout power-down condition
4. Refine pin/peripheral/pin map definitions
> [NUC472/M453] Support unique locally administered MAC address and other driver updates

- targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F429xI/device/TOOLCHAIN_IAR/stm32f429xx_flash.icf
- targets/TARGET_STM/TARGET_STM32F4/TARGET_UBLOX_EVK_ODIN_W2/device/TOOLCHAIN_IAR/stm32f439xx_flash.icf
Targets NUCLEO_F429ZI and UBLOX_EVK_ODIN_W2 have 192K RAM.
Heap size in PR #3871 was increased from 48K to 96K as tls-client
example failed with 48K heap. But this resulted in compilation failures
in mbed-client that requires 71K for global/static data.
Hence this PR reduces heap to 64K that minimum required by tls-client
to work. This also meets mbed-client data segment requirements.
NO
https://github.com/ARMmbed/mbed-os/pull/3871
branch | PR
It should fix issue …
> Heap size adjusted to work for both tls-client and mbed-client

- tools/export/gnuarmeclipse/__init__.py
- tools/project_api.py
When constructing a toolchain for export, we currently set the
`build_dir` to the `export_dir`. When exporting offline, the
`export_dir` is always set to the root of the project. The toolchains
ignore their `build_dir` when scanning for sorces, so when the exporters
use the toolchains to scan for their resources, they get nothing.
In this patch we set the `build_dir` of the toolchain that the exports
use to nothing. A path of nothing should not match anything, and will
therefore not ignore everything when scanning for resources.
> Don't set the build_dir to anything on export

- tools/export/e2studio/rz_a1h_cproject.tmpl
Added mbed_config.h to rz_a1h_cproject.tmpl
IN DEVELOPMENT
NO
> #3593 Added template entry to fix exported project build error.

- features/unsupported/tests/mbed/digitalin_digitalout/main.cpp
- features/unsupported/tests/mbed/digitalinout/main.cpp
- features/unsupported/tests/mbed/interruptin/main.cpp
- features/unsupported/tests/mbed/portinout/main.cpp
- features/unsupported/tests/mbed/portout_portin/main.cpp
To make tests easier for us, I change some pin configuration to align with ci-shield HW configuration
READY
> OS2 tests minor updates for STM32

- targets/TARGET_STM/TARGET_STM32F3/TARGET_STM32F302x8/TARGET_NUCLEO_F302R8/PeripheralPins.c
Add missing PB_8/PB_9 CAN pins. These pins were commented by mistake.
READY
NO
> NUCLEO_F302R8: Add missing PB_8/PB_9 CAN pins

- features/FEATURE_COMMON_PAL/mbed-coap/CHANGELOG.md
- features/FEATURE_COMMON_PAL/mbed-coap/mbed-coap/sn_coap_protocol.h
- features/FEATURE_COMMON_PAL/mbed-coap/module.json
- features/FEATURE_COMMON_PAL/mbed-coap/source/include/sn_coap_header_internal.h
- features/FEATURE_COMMON_PAL/mbed-coap/source/sn_coap_builder.c
- features/FEATURE_COMMON_PAL/mbed-coap/source/sn_coap_parser.c
- features/FEATURE_COMMON_PAL/mbed-coap/source/sn_coap_protocol.c
This commit includes
- Error fixes done on mbed-coap merge back to mbed OS.
- Detailed CHANGELOG  is available here (https://github.com/ARMmbed/mbed-coap/compare/v4.0.2...v4.0.3)
**READY**
**NO**
Check the full changelog (https://github.com/ARMmbed/mbed-coap/compare/v4.0.2...v4.0.3
- Unit Tests passing, CI tests for Client passing
> mbed-coap error fixes merge to mbed OS

- TESTS/mbed_hal/flash/functional_tests/main.cpp
This PR fixes the test code `mbed-os-tests-mbed_hal-flash`.
> [Greentea] Fix test code mbed-os-tests-mbed_hal-flash

- platform/mbed_retarget.h
This patch fixes the declaration of the DIR type and related functions
so that they can be called from C code. This is necessary when enabling
functionality that uses the filesystem in mbed TLS.
**READY**
> Fix C declaration of dir functions and types

- tools/check_release.json
- tools/check_release.py
Fixed results output summary.
General tidy up of long lines.
Added a new field to json file, target_list, to allow the user to
override the set of targets used for the compilation.
> Fixed/improved error parsing from API messages.

- targets/TARGET_Freescale/TARGET_KLXX/TARGET_KL46Z/flash_api.c
- targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K64F/flash_api.c
- targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F429xI/device/flash_api.c
- targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F439xI/device/flash_api.c
- targets/TARGET_STM/TARGET_STM32F4/TARGET_UBLOX_EVK_ODIN_W2/flash_api.c
- tools/flash_algo/c_blob_mbed.tmpl
- tools/flash_algo/extract.py
- tools/flash_algo/flash_algo.py
Check in scripts which are able to generate flash algos for supported
targets.
To initially download all packs the following command should be run:
```
>> python extract.py --rebuild_all
```
After that all supported targets can be rebuilt by running:
```
>> python extracts.py
```
Finally, to rebuild an individual target you can used its pack name:
```
>> python extract.py --target STM32F302R8
```
> Check in algo generation code

- TESTS/mbed_hal/flash/functional_tests/main.cpp
The header is already included inside of flash_api.h if the target
uses CMSIS flash algos. If it doesn't, the file shouldn't be included,
since it doesn't exist.
**READY**
NO
Run the flash tests on a device that implements the flash API using the HAL functions directly, without using the CMSIS flash algorithms. On current master, the test will fail to compile, because flash_data.h doesn't exist.
> Remove explicit include of flash_data.h in flash api test

- targets/TARGET_Silicon_Labs/TARGET_EFM32/common/objects.h
- targets/TARGET_Silicon_Labs/TARGET_EFM32/lp_ticker.c
* Using PinName as bitfield doesn't work without warnings, since NC
needs all 32 bits to be represented.
* lp_ticker should not be freed when interrupt is disabled, since this
will kill the timebase. This change makes the lp_ticker related tests pass.
> [Silicon Labs] Fix compile warnings and ticker test failure

- targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KW24D/TARGET_FRDM/PeripheralPins.c
- targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KW24D/TARGET_FRDM/PinNames.h
Add missing SPI defines and Arduino connector definitions
**READY
> KW24D: Add missing SPI defines and Arduino connector definitions

- tools/config.py
Before, the types were not checked and just expected. The old behavior
would cause lots of tracebacks, or, much worse, convert things like:
```json
{
"*": {
"target.macros_add": "CONFIG_GPIO_AS_PINRESET"
}
}
}
```
into a definition of each of the letters as macros that expand to
nothing, causing massive compilation problems.
I resolved this by adding some type checking to the config data. Now
there is a type check for most of the fields within a library and
application configurations.
resolves https://github.com/ARMmbed/mbed-os/issues/3985
> Add some type checking of configs

- targets/TARGET_NORDIC/TARGET_NRF5/serial_api.c
This fixes an off-by-one error in the async serial write code for the NRF5 target.
**READY**
User should make sure to remove any workarounds they might have added to circumvent this issue.
See #4002.
> Fixed OBOE in async serial tx for NRF52 target, fixes #4002

- targets/TARGET_STM/i2c_api.c
If I2C slave support is included, then the I2C error handler would always reset the I2C address, resulting in incorrectly changing the I2C state to listen for a controller configured as I2C master.  This change conditionalizes the address setting to only occur if the controller was in slave mode when the error occurred.
READY
NO
None
None
None
Create a build for an STM32 based board with DEVICE_I2CSLAVE and DEVICE_I2C_ASYNCH enabled (current default).  Create an I2C master and issue a .transfer() call to a non-existent I2C device address, so that the transfer will be NACKed.  HAL_I2C_ErrorCallback() will be called on the NACK and call i2c_slave_address(), resulting in the state being set to LISTEN.  Subsequent I2C transfer attempts to any address will then immediately fail because …
> STM32: Correct I2C master error handling

- targets/TARGET_Silicon_Labs/TARGET_EFM32/common/objects.h
- targets/TARGET_Silicon_Labs/TARGET_EFM32/flash_api.c
- targets/targets.json
Implements the flash HAL API for EFM32 and EFR32.
**READY**
NO
branch | PR
Bugfix to flash API test | [#4036](https://github.com/ARMmbed/mbed-os/pull/4036)
Run the flash HAL and flash IAP tests on any EFM32GG, WG, LG, PG1 or PG12, or EFR32MG1 or MG12 target. They pass if the test bugfix referenced above is applied.
> [Silicon Labs] Add flash HAL API support

- targets/TARGET_Silicon_Labs/mbed_rtx.h
When using ARM Compiler 5, the RTX config hard-coded the heap and stack
sizes to specific values. This prevented the RTX HAL from dynamically
allocating unused memory as heap space.
Specifically, the HEAP_START define prevents this logic in RTX_CM_lib.h
from activating. The rest of the defines are also set in that header,
and should be removed from here.
> [Silicon Labs] Enable dynamic heap with ARMCC

- features/unsupported/USBHost/USBHostHub/USBHostHub.cpp
If device is disconnected from hub during the hub port reset request, the reset function keeps waiting for reset done.  
READY
> USBHOST : fix device disconnection from hub during hub port reset

- tools/profiles/debug.json
- tools/profiles/develop.json
- tools/profiles/release.json
By default, ld sets page alignment of sections to 0x8000, which bloats
up elf file size. This behavior is unnecessary for MCU.
Example:
1. page alignment on
mbed.elf file size 144936
Program Headers:
Type           Offset   VirtAddr   PhysAddr   FileSiz MemSiz  Flg Align
LOAD           0x008000 0x00000000 0x00000000 0x00400 0x00400 R   0x8000
LOAD           0x008400 0x00000400 0x00000400 0x00010 0x00010 R   0x8000
LOAD           0x008410 0x00000410 0x00000410 0x0ab3c 0x0ab3c RWE 0x8000
LOAD           0x018000 0x20000000 0x0000af4c 0x008d0 0x008d0 RW  0x8000
LOAD           0x01b81c 0x0000b81c 0x0000b81c 0x00000 0x00004 RW  0x8000
LOAD           0x020000 0x1fff0000 0x1fff0000 0x00000 0x00400 RW  0x8000
LOAD           0x0188d0 0x200008d0 0x200008d0 0x00000 0x08860 RW  0x8000
2. page …
> tools - turn off page alignment of sections

- targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KW41Z/trng_api.c
- targets/targets.json
Add support to use the TRNG module for entropy generation.
**READY
Passed mbed compliance tests.
> Add TRNG support for KW41Z

- tools/config.py
The error messages related to missing or broken device names in the
targets.json file were bad/just python tracebacks. This PR changes that
behavior, by having the Config object raise ConfigExceptions for those
mis-configurations.
Resolves #4057
messages seen are good.
- `mbed_app.json`
```
{
"target_overrides":{
"NCS36510":{
"target.restrict_size": "0x40000"
}
}
}
```
- `mbed compile -m NCS36510`
```
[ERROR] Bootloader not supported on this target.
```
- add `"bootloader_supported": true` to `targets.json`
- `mbed compile -m NCS36510`
```
[ERROR] Bootloader not supported on this target: targets.json `device_name` not specified.
```
- add `"device_name": "NCS36510"` to `targets.json`
- `mbed compile -m NCS36510`
```
[ERROR] Bootloader not supported on this target: targets.json …
```
> Improve error messages for bootloader build errors

- targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_K66F/device/TOOLCHAIN_GCC_ARM/MK66FN2M0xxx18.ld
Move bss section to m_data_2 Section. This should fix below issue:
https://github.com/ARMmbed/mbed-os/issues/3978
**READY
Passed the mbed K66F test suite
> K66F: Move bss section to m_data_2 Section

- features/FEATURE_COMMON_PAL/nanostack-hal-mbed-cmsis-rtos/arm_hal_interrupt.c
- features/FEATURE_COMMON_PAL/nanostack-hal-mbed-cmsis-rtos/arm_hal_timer.cpp
- features/FEATURE_COMMON_PAL/nanostack-hal-mbed-cmsis-rtos/ns_event_loop.c
- features/nanostack/FEATURE_NANOSTACK/targets/TARGET_NCS36510/NanostackRfPhyNcs36510.cpp
* Use statically allocated blocks for mutexes
* Use statically allocated blocks for threads.
**NOTE:** For statically allocated blocks, we are forced to use RTX types and headers, so we are not anymore directly compatible with CMSIS-RTOS2.
But this is how the example documentation does it anyway.
**READY**
**TODO:**
> Update Nanostack drivers to CMSIS2/RTX5

- tools/targets/__init__.py
- tools/toolchains/__init__.py
- tools/toolchains/arm.py
- tools/toolchains/gcc.py
- tools/toolchains/iar.py
The tools now use the extension provided by `OUTPUT_EXT` to determine the file
type of the output executable.
Resolves https://github.com/ARMmbed/mbed-os/issues/3973
> Use OUTPUT_EXT to pick binary type

- targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_K66F/device/TOOLCHAIN_GCC_ARM/MK66FN2M0xxx18.ld
- targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_K82F/device/TOOLCHAIN_GCC_ARM/MK82FN256xxx15.ld
- targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KL27Z/device/TOOLCHAIN_GCC_ARM/MKL27Z64xxx4.ld
- targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KL43Z/device/TOOLCHAIN_GCC_ARM/MKL43Z256xxx4.ld
- targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KL82Z/device/TOOLCHAIN_GCC_ARM/MKL82Z128xxx7.ld
- targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KW24D/device/TOOLCHAIN_GCC_ARM/MKW24D512xxx5.ld
- targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KW41Z/device/TOOLCHAIN_GCC_ARM/MKW41Z512xxx4.ld
Reduce heap allocation in the GCC linker file, this should address the below issues.
https://github.com/ARMmbed/mbed-os/issues/3978
https://github.com/ARMmbed/mbed-os/issues/3763
**READY
> Issue 3763: Reduce heap allocation in the GCC linker file

- features/unsupported/USBDevice/USBDevice/USBEndpoints.h
- targets/TARGET_STM/TARGET_STM32L0/TARGET_DISCO_L053C8/USBHAL_STM32L053C8.h
- targets/TARGET_STM/TARGET_STM32L0/TARGET_DISCO_L053C8/USBHAL_STM_TARGET.h
- targets/TARGET_STM/TARGET_STM32L0/TARGET_DISCO_L053C8/device/system_stm32l0xx.c
Add the support of USB Device on the DISCO_L053C8 platform.
USB_1 (HID) and USB_4 (Serial) tests are OK.
Fix Issue #4010 
READY
NO
> DISCO_L053C8: Add support of USB Device

- targets/TARGET_STM/TARGET_STM32L0/TARGET_DISCO_L053C8/device/TOOLCHAIN_IAR/stm32l053xx.icf
- targets/TARGET_STM/TARGET_STM32L0/TARGET_NUCLEO_L031K6/device/TOOLCHAIN_IAR/stm32l031xx.icf
- targets/TARGET_STM/TARGET_STM32L0/TARGET_NUCLEO_L053R8/device/TOOLCHAIN_IAR/stm32l053xx.icf
I decreased heap and stack size for some "small" OS2 targets:
- DISCO_L053C8
- NUCLEO_L053R8
- NUCLEO_L031K6
READY
> [STM32L0] reduce IAR heap and stack size for small targets

- targets/TARGET_Silicon_Labs/TARGET_EFM32/common/objects.h
- targets/TARGET_Silicon_Labs/TARGET_EFM32/trng/sl_trng.c
- targets/TARGET_Silicon_Labs/TARGET_EFM32/trng/sl_trng.h
- targets/TARGET_Silicon_Labs/TARGET_EFM32/trng/trng_api.c
- targets/targets.json
Adding support for the TRNG peripheral present on Series 1 Configuration 2 devices.
**READY**
NO
> [Silicon Labs] Add TRNG support

- targets/TARGET_STM/TARGET_STM32L4/common_objects.h
- targets/TARGET_STM/TARGET_STM32L4/flash_api.c
- targets/targets.json
This PR activates FLASH for L4 targets. 
Flash hal tests running ok.
```
+-------------------+---------------+----------------------+--------+--------------------+-------------+
| target            | platform_name | test suite           | result | elapsed_time (sec) | copy_method |
+-------------------+---------------+----------------------+--------+--------------------+-------------+
| NUCLEO_L476RG-IAR | NUCLEO_L476RG | tests-mbed_hal-flash | OK     | 13.2               | shell       |
+-------------------+---------------+----------------------+--------+--------------------+-------------+
mbedgt: test suite results: 1 OK
mbedgt: test case report:
+-------------------+---------------+----------------------+-------------------------------+--------+--------+--------+--------------------+
| …
```
> 17q2 l4 flash

- features/FEATURE_LWIP/lwip-interface/lwip-eth/arch/TARGET_NXP/lpc17_emac.c
From opt.h:
> IP_SOF_BROADCAST_RECV (requires IP_SOF_BROADCAST=1) enable the broadcast filter on recv operations.
The IP_SOF_BROADCAST_RECV option does not enable or disable recieving broadcast packets, it only enables a software filter. The lpc1768 was using the IP_SOF_BROADCAST_RECV to disable recieving broadcasts entirely.
This resulted in an issue for certain DHCP servers, which apparently can respond to discover packets via broadcast.
Tested locally with with dump provided by @chrissnow
related: https://github.com/ARMmbed/mbed-os/issues/4018, https://github.com/ARMmbed/mbed-os-example-sockets/issues/17
cause: https://github.com/ARMmbed/mbed-os/pull/3482
cc: @chrissnow, @toyowata, @kjbracey-arm
> lpc1768: Remove invalid use of IP_SOF_BROADCAST_RECV option

- tools/build_api.py
Resolves #4055
The add_regions_to_profile function assumed that there would always be a
profile to add regions to. If the profile is not specified, we would get
a traceback. Instead of bombing horribly, we should just elide adding
the region list to the profile when it does not exist.
@0xc0170 
@tkaman
> Elide adding regions to profile when empty

- tools/profiles/debug.json
The extra space between "--no_wrap_diagnostics" and "-e" is inconsistent with the development and release targets.
It bugs people (like me) that have little OCD tics 😉.
> Removed superfluous space

- targets/TARGET_Silicon_Labs/TARGET_EFM32/TARGET_EFM32PG/device/TARGET_256K/TOOLCHAIN_GCC_ARM/efm32pg1b.ld
- targets/TARGET_Silicon_Labs/TARGET_EFM32/TARGET_EFM32PG12/device/TOOLCHAIN_GCC_ARM/efm32pg12b.ld
- targets/TARGET_Silicon_Labs/TARGET_EFM32/TARGET_EFR32MG1/device/TOOLCHAIN_GCC_ARM/efr32mg1p.ld
- targets/TARGET_Silicon_Labs/TARGET_EFM32/TARGET_EFR32MG12/device/TOOLCHAIN_GCC_ARM/efr32mg12p.ld
- targets/TARGET_Silicon_Labs/TARGET_EFM32/common/mbed_overrides.c
Linker assert should take main app flash offset into account. Also, HFXO should not be re-initialized when bootloader has already initialized it (and core is already running from it).
> [Silicon Labs] Bugfix for bootloader on Pearl and Mighty Gecko

- tools/export/embitz/__init__.py
- tools/export/gnuarmeclipse/__init__.py
- tools/export/makefile/__init__.py
Notes:
Although the post_binary_hooks are not used by the exporters at this time, the exporters do set up a POST_BINARY_WHITELIST and reject anything with a post_binary_hook not in the whitelist. This prevents LPCTargets from working with exporters. This patch adds the LPCTarget to the whitelist of all exporters.
**READY**
Resolves ARMmbed/mbed-cli#468
> Fix mbed-cli issue #468. Add LPCTargetCode.lpc_patch to POST_BINARY_WHITELIST

- platform/mbed_semihost_api.c
The current implementation of semihost_disabledebug() hangs when used
with mbed interface firwmare revision 21164, the first version which
added support for this semihost call. I encountered this hang when
running a Release build on my mbed-LPC1768 board as the RTOS attempted
to disable the debugger before the idle thread put the CPU to sleep.
The 21164 interface firmware expects that R1 points to a valid argument
block but the current implementation passes in NULL. The fix was to
pass in a dummy block which is ignored by the newer 141212 revision of
the firmware and allows the 21164 version to proceeed without halting
the CPU until a manual reset.
Before this fix semihost_disabledebug() did work with the latest
mbed interface firmware revision 141212 but I rarely use this revision
of the …
> Modify semihost_disabledebug() to support more interface FW revs

- tools/export/iar/__init__.py
- tools/export/iar/ewd.tmpl
- tools/export/iar/iar_definitions.json
The default CMSIS-DAP interface speed (Auto) is causing troubles in debug communication (at least on Nordic's DKs). It was changed to 2 MHz for Nordic targets. An extra option "--drv_vector_table_base=0x0" was also added for these, so the debug session is not started with a jump to the application's reset handler, but to the SoftDevice's one instead.
**READY**
NO
> IAR exporter: extended debugger settings template with modifiable options needed for Nordic targets

- hal/mbed_ticker_api.c
- targets/TARGET_Freescale/TARGET_KLXX/us_ticker.c
Ticker can cause a crash if you disable interrupts for longer than the Ticker object's interval, if you have at least one other timed event in the system.
This problem has two causes.
1.  ticker_insert_event() leaves the event linked list in an inconsistent state before calling set_interrupt(), which can recurse back into ticker_insert_event(), which will again modify the list.  This can cause crashes in different ways depending on the particular path through the code, but with the Ticker setup described above, it will usually create a cycle in the list (head->A->B->A->B...) that causes an infinite loop the next time someone tries to traverse the list.
The fix is to complete all manipulations to the list pointers BEFORE calling set_interrupt().
2.  TARGET_KLXX/us_ticker.c has a separate …
> Ticker - kl25z bugfix for handling events in the past

- features/FEATURE_LWIP/lwip-interface/lwip-eth/arch/TARGET_NXP/lpc17_emac.c
Originally the LPC17xx ethernet ISR would be linked in to all mbed-os based
firmware because it was named ENET_IRQHandler() so that it would be
automatically placed in the FLASH image's interrupt vector table. This
meant that programs which made no use of the lwIP stack still pulled in
this ISR.
This commit changes the name of the routine so that the ISR isn't
automatically placed in the interrupt vector table at link time but is
instead dynamically placed in the interrupt vector table at runtime
when the lwIP stack is initialized. Now the ethernet ISR is only linked
in when it is actually needed.
Example arm-none-eabi-size output for a simple LED blinking program
showing the before and after size results:
text	   data	    bss	    dec	    hex	filename
13208	    148	   7784	  21140	   5294 …
> Only link in LPC17xx ethernet ISR as needed

- tools/config.py
> Raise error when mbed_app.json is bad

- tools/export/__init__.py
It was causing tracebacks on the website. The make_key function of the
export object would use the basepath of every file and would not prefix
it with the export path. I don't know why we added the prefix in the
first place, so I removed it. Further, using any path other than "."
would result in ".." being the only group. that's definitely strange
behavior, but easy to work around: just pass in "."
> Fix a small bug in subtract_basepath

- targets/TARGET_NORDIC/TARGET_NRF5_SDK13/TARGET_MCU_NRF52840/sdk/sdk_config.h
- targets/TARGET_NORDIC/TARGET_NRF5_SDK13/spi_api.c
- targets/targets.json
Fix capability by using SPI instead of SPIM peripheral and resign from SPI_ASNCHRONUS capability.
SPIM peripheral has the bug which imposed on one-byte transfer.
tests-api-spi is also fixed by this PR.
**READY**
##Test result:
```{{__version;1.3.0}}
{{__timeout;40}}
{{__host_test_name;default_auto}}
>>> Running 6 test cases...
{{__testcase_name;SPI - Object Definable}}
{{__testcase_name;SPI - SD card exists}}
{{__testcase_name;SPI - SD Write}}
{{__testcase_name;SPI - SD Read}}
{{__testcase_name;SPI - SD 2nd Write}}
{{__testcase_name;SPI - SD 2nd Read}}
>>> Running case #1: 'SPI - Object Definable'...
{{__testcase_start;SPI - Object Definable}}
{{__testcase_finish;SPI - Object Definable;1;0}}
>>> 'SPI - Object Definable': 1 passed, 0 failed
>>> Running case #2: 'SPI - SD card exists'... …
```
> [NRF52840]: enabled SdBlockDevice capability

- README.md
Much OSS on github uses these CI badges to indicating to their users that they:
1. Use CI.
2. Have a stable project.
I think we should do the same thing.
Further, I edited the README to remove passive voice.
I don't think this is needed. Just view the diff.
@AnotherButler
> Edit the README and add Travis CI badges

- targets/TARGET_NXP/TARGET_LPC176X/TARGET_MBED_LPC1768/PinNames.h
See discussion in issue #4099. I've only tested this by compiling an I2C app with an LPC1768 target and then running the result. I have yet to be able to successfully run 'mbed test' in my environment (against stable, head, etc.), so I'm not able to demonstrate the results of that.
> Add SCL and SDA defs for I2C[0-2]; redefine I2C_[SCL,SDA] to I2C2

- tools/toolchains/__init__.py
I don't know what this affected, or even if it affected anything.
> Fix a scoping typo in toolchains

- targets/TARGET_STM/PeripheralPins.h
- targets/TARGET_STM/TARGET_STM32F4/TARGET_MTS_DRAGONFLY_F411RE/PeripheralPins.c
- targets/TARGET_STM/TARGET_STM32F4/TARGET_MTS_MDOT_F405RG/PeripheralPins.c
- targets/TARGET_STM/TARGET_STM32F4/TARGET_MTS_MDOT_F411RE/PeripheralPins.c
- targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F401xC/TARGET_DISCO_F401VC/PeripheralPins.c
- targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F401xE/TARGET_NUCLEO_F401RE/PeripheralPins.c
- targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F407xG/TARGET_ARCH_MAX/PeripheralPins.c
- targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F407xG/TARGET_DISCO_F407VG/PeripheralPins.c
- targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F410xB/TARGET_NUCLEO_F410RB/PeripheralPins.c
- targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F411xE/TARGET_ELMO_F411RE/PeripheralPins.c
- targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F411xE/TARGET_NUCLEO_F411RE/PeripheralPins.c
- targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F412xG/TARGET_NUCLEO_F412ZG/PeripheralPins.c
- targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F429xI/TARGET_DISCO_F429ZI/PeripheralPins.c
- targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F429xI/TARGET_NUCLEO_F429ZI/PeripheralPins.c
- targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F439xI/TARGET_NUCLEO_F439ZI/PeripheralPins.c
- targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F446xE/TARGET_B96B_F446VE/PeripheralPins.c
- targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F446xE/TARGET_NUCLEO_F446RE/PeripheralPins.c
- targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F446xE/TARGET_NUCLEO_F446ZE/PeripheralPins.c
- targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F469xI/TARGET_DISCO_F469NI/PeripheralPins.c
- targets/TARGET_STM/TARGET_STM32F4/TARGET_UBLOX_EVK_ODIN_W2/PeripheralPins.c
- targets/TARGET_STM/TARGET_STM32F4/analogin_api.c
Internal ADC pin are now out of PinMap_ADC array.
Test MBED_A8 is still OK.
READY
> STM32F4 Internal ADC channels rework

- tools/export/gnuarmeclipse/__init__.py
- tools/export/gnuarmeclipse/makefile.targets.tmpl
PR #3706 changed the behavior of `.ld` files in mbed-os. After that PR, all `.ld` files are passed through the C pre-processor before handing them off to the linker. This PR changes the GNU ARM Eclipse exporter to do that pre-processing as well.
At the moment, the implementation pre-processes the linker script for all profiles, when it only needs one. This is because I was not able to find a way to get the linker other flags as a make variable. @ilg-ul is it possible to get the linker other flags in a Makefile variable for the `makefile.targets` extension?
> Update gnuarmeclipse to preprocess linker scripts

- tools/export/__init__.py
- tools/export/qtcreator/__init__.py
- tools/export/qtcreator/config.tmpl
- tools/export/qtcreator/creator.tmpl
- tools/export/qtcreator/files.tmpl
- tools/export/qtcreator/includes.tmpl
This commit adds minimal support to `mbed export` to generate [Qt Creator Generic Projects](http://doc.qt.io/qtcreator/creator-project-generic.html).
**READY**
---
Link to my profile, with signed contributor agreement: https://developer.mbed.org/users/cvtsi2sd/
> Support for Qt Creator Generic project export and associated Makefile

- tools/build_api.py
- tools/config.py
- tools/test/build_api/build_api_test.py
This patch allows a user to configure the artifact name through the 
`mbed_app.json` file.
Suggested by @andrewleech in #4103
```json
{
"artifact_name" : "FooBar"
}
```
This will rename the executable in your application from `<dirname(app-dir)>.bin` to `FooBar.bin`
The precedence is (fall through if not specified):
1. Command line argument.
2. `mbed_app.json` `artifact_name` key
3. Name of the directory that contains the project.
> Allow configuration of artifact name in app config

- platform/mbed_retarget.cpp
Fixed compiler warning about `openmode_to_posix()` being declared but never referenced.
> Fixed compiler warning in mbed_retarget.cpp

- drivers/CAN.cpp
Updated `CAN` to use new `Callback` assignment API in order to fix compiler warnings.
> Updated CAN to new Callback API

- targets/TARGET_STM/PeripheralPins.h
- targets/TARGET_STM/TARGET_STM32F4/TARGET_MTS_DRAGONFLY_F411RE/PeripheralPins.c
- targets/TARGET_STM/TARGET_STM32F4/TARGET_MTS_MDOT_F405RG/PeripheralPins.c
- targets/TARGET_STM/TARGET_STM32F4/TARGET_MTS_MDOT_F411RE/PeripheralPins.c
- targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F401xC/TARGET_DISCO_F401VC/PeripheralPins.c
- targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F401xE/TARGET_NUCLEO_F401RE/PeripheralPins.c
- targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F407xG/TARGET_ARCH_MAX/PeripheralPins.c
- targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F407xG/TARGET_DISCO_F407VG/PeripheralPins.c
- targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F410xB/TARGET_NUCLEO_F410RB/PeripheralPins.c
- targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F411xE/TARGET_ELMO_F411RE/PeripheralPins.c
- targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F411xE/TARGET_NUCLEO_F411RE/PeripheralPins.c
- targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F412xG/TARGET_NUCLEO_F412ZG/PeripheralPins.c
- targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F429xI/TARGET_DISCO_F429ZI/PeripheralPins.c
- targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F429xI/TARGET_NUCLEO_F429ZI/PeripheralPins.c
- targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F439xI/TARGET_NUCLEO_F439ZI/PeripheralPins.c
- targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F446xE/TARGET_B96B_F446VE/PeripheralPins.c
- targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F446xE/TARGET_NUCLEO_F446RE/PeripheralPins.c
- targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F446xE/TARGET_NUCLEO_F446ZE/PeripheralPins.c
- targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F469xI/TARGET_DISCO_F469NI/PeripheralPins.c
- targets/TARGET_STM/TARGET_STM32F4/TARGET_UBLOX_EVK_ODIN_W2/PeripheralPins.c
- targets/TARGET_STM/TARGET_STM32F4/analogin_api.c
Reverts ARMmbed/mbed-os#4118
C030 merged to master while this was in a pipeline to test. The commit on master this merged with was before that target was on master therefore a breakage. @jeromecoutant Can you update the change to be compatible with the C030 as well. Thanks.
> Revert "STM32F4 Internal ADC channels rework"

- tools/build_api.py
- tools/export/__init__.py
- tools/make.py
- tools/project.py
Added the ability to list toolchains, ides, and targets in addition to just dumping them as a matrix. This is useful for bash tab completion and other piping.
NO
> Added list options for --supported command

- rtos/mbed_boot.c
Based on top of #4164 (that one should get in first), to allow me to bug-hunt the last bug in there!
How does this fixes the last 2 issues (those tests that use printf). They use printf with a new line. printf with just fflush(stdout) worked, but with newline it failed (hey, we got a deadlock in here). From the DLIB specifications for IAR threaded support: http://supp.iar.com/FilesPublic/UPDINFO/005691/arm/doc/infocenter/DLIBThreadSupport.html 
``The lock and unlock implementation must survive nested calls.``. 
This was the case here, printf() invokes multiple times the lock on the same file in some cases (the last one that caused wait forever was flushone IAR internal function). 
To reproduce the problem easily ``printf("\n"); in the main()`` , this call would never return.
Test results: …
> cmsis5 iar: system/file mutex to be recursive

- rtos/mbed_boot.c
CMSIS does not provide ALIGNED for IAR currently (tested with 7.8 IAR), thus we were getting a failure to create a new thread (pre_main thread). MBED_ALIGNED should work for any compiler we support.
As an addition, ThreadNew function returns NULL if it fails (in our case, it was not aligned stack memory), thus we return an error if it fails.
Test results:
```
+----------+---------------+-------------------------------------+----------------------------------------+--------+--------+--------+--------------------+
| target   | platform_name | test suite                          | test case                              | passed | failed | result | elapsed_time (sec) |
+----------+---------------+-------------------------------------+----------------------------------------+--------+--------+- …
```
> CMSIS5 rtos: fix main stack alignment for IAR

- platform/mbed_sleep.h
- targets/TARGET_Maxim/TARGET_MAX32630/sleep.c
- tools/profiles/debug.json
- Introduce new macro `MBED_DEBUG` that's only defined for debug profile. Right now NDEBUG is defined only for release profile, which makes it impossible to separate develop and debug builds features.
- Profile used by online IDE is develop, we probably don't want disable sleep for profile which people actually may use in 'production'. This PR makes sleep a noop only for the debug builds.
**READY**
CC: @theotherjimmy @0xc0170
> Debug build flag + change to sleep behavior in debug mode

- events/equeue/equeue_mbed.cpp
- events/equeue/equeue_platform.h
Before, if the semaphore recieved a wait of zero, the semaphore would erronously drop the ticker event to wake up the device, causing the device to go to sleep without any mechanism to wake itself up.
During a dispatch operation, the event queue dispatches all events that have expired, so the call to equeue_sema_wait very rarely has a wait of zero. But this can happen when an event is posted just after a dispatch has occured.
The rtos version handles this correctly:
https://github.com/ARMmbed/mbed-os/blob/master/events/equeue/equeue_mbed.cpp#L105
related issue https://github.com/ARMmbed/mbed-os/issues/3857
cc @pan-, @tbondar, @nvlsianpu
> events: Fix zero wait condition in non-rtos semaphore

- targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F437xG/TARGET_UBLOX_C030/system_stm32f4xx.c
- targets/targets.json
XTAL by using Macro USE_DEBUG_8MHz_XTAL
HSE is now set to 12MHz and the PLL default is 12MHz. This is because all hardware will work from local crystal and not the 8MHz debug chip clock. 
Created a new Macro USE_DEBUG_8MHz_XTAL to switch back to the 8MHz debug chip clock if the user wishes.
> U-BLOX_C030: Default XTAL is now 12MHz onboard. Option to use Debug 8MHz

- targets/TARGET_STM/TARGET_STM32L0/common_objects.h
- targets/TARGET_STM/TARGET_STM32L0/flash_api.c
- targets/targets.json
This PR contains the flash API implementation for L0 STM32 family.
READY 
Test report on L073RZ
```
+-----------------------+---------------+-----------------------------+-------------------------------+--------+--------+--------+--------------------+
| target                | platform_name | test suite                  | test case                     | passed | failed | result | elapsed_time (sec) |
+-----------------------+---------------+-----------------------------+-------------------------------+--------+--------+--------+--------------------+
| NUCLEO_L073RZ-GCC_ARM | NUCLEO_L073RZ | tests-mbed_drivers-flashiap | FlashIAP - init               | 1      | 0      | OK     | 0.05               |
| NUCLEO_L073RZ-GCC_ARM | NUCLEO_L073RZ | tests-mbed_drivers-flashiap | FlashIAP - program …
```
> STM32 L0: Add Flash API support

- platform/mbed_board.c
Fix the following compiler warning.
Compile [ 63.7%]: mbed_board.c
[Warning] mbed_board.c@99,36: comparison between signed and unsigned integer expressions [-Wsign-compare]
READY
NO
NONE
NONE
NONE
NONE
> Fix mbed_board.c compiler warning

- tools/export/gnuarmeclipse/__init__.py
- tools/export/gnuarmeclipse/mbedignore.tmpl
There are subtleties about where the exporters generate files when using
the online exporers-as-a-service. Simply calling open does not do the 
correct thing in this environment. The `self.gen_file` method can be used
instead to account for these differences.
I saw an exception generated by the online build system recently.
This was the traceback:
```python-traceback
IOError: [Errno 13] Permission denied: '.mbedignore'
File "django/core/handlers/base.py", line 132, in get_response
response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "django/views/decorators/vary.py", line 21, in inner_func
response = func(*args, **kwargs)
File "piston/resource.py", line 190, in __call__
result = self.error_handler(e, request, meth, em_format)
File "piston/resource.py", line 188, in …
```
> Generate GNU ARM Eclipse .mbedignore file with jinja2

- tools/toolchains/__init__.py
Resolves #3940
The issue mentioned above can me sumarized as:
This does not work:
```bash
mbed compile --source ./
```
This works:
```bash
mbed compile --source .
```
Both should work.
The include directories passed to `--source` are added as-is to the list
of include directories. GCC, and possibly other compilers, on Windows 
does not like the path `./` and will ignore it when searching for header
files.
Remove trailing `/`s before appending include paths to when scanning 
resources.
> Fix include paths for Windows builds

- tools/export/cmsis/__init__.py
Then try to export any project online to cmsis. You will get this 
trackback (unbeknownst to you):
```python-traceback
TypeError: join() takes at least 1 argument (0 given)
File "django/core/handlers/base.py", line 132, in get_response
response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "django/views/decorators/csrf.py", line 58, in wrapped_view
return view_func(*args, **kwargs)
File "django/contrib/auth/decorators.py", line 22, in _wrapped_view
return view_func(request, *args, **kwargs)
File "mbed/repositories/views.py", line 1601, in web_export
name=repo.slug)
File "mbed_compiler/export.py", line 149, in export
notify=notify
File "tools/project_api.py", line 222, in export_project
macros=macros)
File "tools/project_api.py", line 89, in generate_project_files …
```
> Fix Traceback in CMSIS export.

- features/FEATURE_UVISOR/importer/Makefile
This is a quick PR to update the uVisor exporter script. It has no effect on mbed OS.
Ready
NO
This PR blocks a uVisor PR: https://github.com/ARMmbed/uvisor/pull/422
@0xc0170
> uVisor: Fix copy of quick-start doc in exporter script

- targets/TARGET_Silicon_Labs/TARGET_EFM32/pwmout_api.c
Fixes a bug causing the `pwmout_all_inactive` function to return the inverse of the actual state. If one of the CC channel pins is enabled it means a channel is active so it should return `true`.
The bug seems to have been introduced in mbed 3 (a81fdc461d). Before `pwmout_all_inactive` just checked if the route was enabled (which doesn't really work...)
This PR also contains some cleanup in `pwm_init`.
**READY**
Note: I only tested this on the EFM32 Happy Gecko MCU (EFM32HG_STK3400 target).
Since `pwm_free` is not called in `~PWMOut` (see #3106), this bug currently does not cause any problems. However, when enabling this functionality, e.g by adding the folowing destructor to PWMOut:
```cpp
~PwmOut() {
core_util_critical_section_enter();
pwmout_free(&_pwm); …
```
> EFM32: Fixed `pwmout_all_inactive` being inversed

- rtos/mbed_boot.c
We missed ``mbed_main`` to invoke prior ``main()``.
Before this patch:
```
+----------+---------------+---------------------------------------+--------+--------------------+-------------+
| target   | platform_name | test suite                            | result | elapsed_time (sec) | copy_method |
+----------+---------------+---------------------------------------+--------+--------------------+-------------+
| K64F-IAR | K64F          | tests-mbedmicro-mbed-call_before_main | FAIL   | 9.73               | shell       |
+----------+---------------+---------------------------------------+--------+--------------------+-------------+
```
After this patch:
```
+----------+---------------+---------------------------------------+--------+--------------------+-------------+
| target   | …
```
> mbed boot: fix IAR mbed_main

- rtos/rtx2/TARGET_CORTEX_M/core_cm.h
Include arm_math.h so __CLZ is defined for cortex-m0 when compiling for IAR. This fixes "__cmsis_iar_clz" is undefined errors.
> Fix IAR compilation for cortex-m0

- targets/TARGET_NORDIC/TARGET_NRF5/us_ticker.c
bug:
If rtc overflow occur while setting of timestamp then the compare event ocurr (erroneously) in 512s.
This cause https://github.com/ARMmbed/mbed-os/issues/3857 issue.
changes:
- move rtc ovf handler at the beginning of rtc handler for mitigate the case (mitigate issue for execution from rtc handler)
- add repeating of operation of set a timestamp in case that rtc overflow occurred during the operation.
**READY**
> [NRF5]: fix rtc overflow-while-set-timestamp issue

- targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F412xG/device/TOOLCHAIN_IAR/stm32f412xx.icf
- targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F469xI/device/TOOLCHAIN_IAR/stm32f469xx.icf
- targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F756xG/device/TOOLCHAIN_IAR/stm32f756xg.icf
- targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F767xI/device/TOOLCHAIN_IAR/stm32f767xi.icf
- targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F769xI/device/TOOLCHAIN_IAR/stm32f769xi.icf
Following https://github.com/ARMmbed/mbed-os/pull/3920
I have updated the heap size for all targets with 192K RAM and more
READY
OS5 results are coming.
OS2 tests:
> STM32 increase IAR heap size for big RAM targets

- tools/tests.py
This should solve #4114. This PR removes an old Filesystem mbed 2 test. The source directory for the test doesn't exist anymore, so we should probably remove the test listing!
**READY**
NO
FYI @pranavshandilya, @geky
> Removing old filesystem test

- targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_K66F/device/TOOLCHAIN_ARM_STD/MK66FN2M0xxx18.sct
- targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_K82F/device/TOOLCHAIN_ARM_STD/MK82FN256xxx15.sct
- targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KL27Z/device/TOOLCHAIN_ARM_STD/MKL27Z64xxx4.sct
- targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KL43Z/device/TOOLCHAIN_ARM_STD/MKL43Z256xxx4.sct
- targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KL82Z/device/TOOLCHAIN_ARM_STD/MKL82Z128xxx7.sct
- targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KW24D/device/TOOLCHAIN_ARM_STD/MKW24D512xxx5.sct
- targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KW41Z/device/TOOLCHAIN_ARM_STD/MKW41Z512xxx4.sct
- targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K22F/TARGET_MCU_K22F512/device/TOOLCHAIN_ARM_STD/MK22FN512xxx12.sct
- targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K64F/device/TOOLCHAIN_ARM_STD/MK64FN1M0xxx12.sct
Update ARM linker files to eliminate reserving RAM for stack & heap. Heap and stack size is determined via the RTOS. This should fix the below issue:
https://github.com/ARMmbed/mbed-os/issues/3763
**READY
Ran & passed mbed-os tests.
> MCUXpresso: Update ARM linker files to eliminate reserving RAM for stack & heap

- tools/config/__init__.py
- tools/config/header.tmpl
The config system is a huge file, and seems to be growing to support 
things such as bootloader. This implies that the Config class may grow
to beyond the size of this one file.
Furthermore, I saw an error generated by the online build system recently.
This was the traceback:
```python-traceback
ValueError: max() arg is an empty sequence
File "mbed/build_tasks/tasks.py", line 33, in perform_build
result = _perform_build(build_params)
File "mbed/build_tasks/tasks.py", line 139, in _perform_build
result = build(build_params=build_params)
File "mbed_compiler/build.py", line 223, in build
mbed_compiler.build_api.build_program(build_params=build_params, notify=notify)
File "mbed_compiler/build_api.py", line 227, in build_program
resources.objects = toolchain.compile_sources(resources, …
```
> Move config system into it's own folder and refactor header generation

- tools/export/lpcxpresso/lpc1549_project.tmpl
Export for LPCXpresso and LPC1549
```python-traceback
File "/home/jimbri01/src/armmbed/mbed-os-example-fat-filesystem/mbed-os/tools/project.py", line 247, in <module>
main()
File "/home/jimbri01/src/armmbed/mbed-os-example-fat-filesystem/mbed-os/tools/project.py", line 243, in main
build_profile=profile)
File "/home/jimbri01/src/armmbed/mbed-os-example-fat-filesystem/mbed-os/tools/project.py", line 93, in export
build_profile=build_profile, silent=silent)
File "/home/jimbri01/src/armmbed/mbed-os-example-fat-filesystem/mbed-os/tools/export/__init__.py", line 329, in export_project
macros=macros)
File "/home/jimbri01/src/armmbed/mbed-os-example-fat-filesystem/mbed-os/tools/export/__init__.py", line 196, in generate_project_files
exporter.generate()
File …
```
> Fix typo in LPCExpresso exporter template

- tools/export/iar/__init__.py
Delete a linker script. 
For example:
```bash
rm mbed-os/targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K64F/device/TOOLCHAIN_IAR/MK64FN1M0xxx12.icf 
```
Then try to export that Target to IAR:
```python-traceback
File "/home/jimbri01/src/armmbed/mbed-os-example-fat-filesystem/mbed-os/tools/project.py", line 247, in <module>
main()
File "/home/jimbri01/src/armmbed/mbed-os-example-fat-filesystem/mbed-os/tools/project.py", line 243, in main
build_profile=profile)
File "/home/jimbri01/src/armmbed/mbed-os-example-fat-filesystem/mbed-os/tools/project.py", line 93, in export
build_profile=build_profile, silent=silent)
File "/home/jimbri01/src/armmbed/mbed-os-example-fat-filesystem/mbed-os/tools/export/__init__.py", line 329, in export_project …
```
> Fail IAR exports without linker scirpts with NotSupportedException

- events/equeue/equeue_mbed.cpp
If you have compiled mbed-os with gcc version 6 you may have seen this warning:
```
Compile [ 10.9%]: equeue_mbed.cpp
[Warning] equeue_mbed.cpp@51,13: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
```
This pr removes the warning.
Several opaque buffers are used to to wrap c++ classes to pass to the c layer. The reinterpret cast to c++ classes is fine as long as the underlying buffer is not interpreted as different incompatible types, or else the behaviour is undefined.
In the equeue_tick_init function, placement new is used to initialize the buffers. However, this interprets the buffer as a simple array of bytes, not the actual class type. Later the buffer is casted to the class type. From the point of view of the compiler, these two types are …
> events: Remove strict-aliasing warning

- platform/mbed_board.c
[Warning] mbed_board.c@99,36: comparison between signed and unsigned
integer expressions [-Wsign-compare] is seen during compilation.
Fix the warning and small improvements.
1. Change type of loop variable "i" to the same type as "size".
Size is > 0 checked by the if statement and the for loop stops at i == size
so none can be negative. However size still needs to be signed
to detect error codes from vsnprintf.
2. Reduced scope of stdio_out_prev and make sure it's initialized.
3. Define a name for the error buffer size and use vsnprintf instead
of vsprintf to avoid writing outside of the array.
NOTE: the `if(size > 0)` statement doesn't need to change. If
the message to write is larger than the buffer size vsnprintf
truncates it automatically but still returns a positive value.
READY
1. …
> Fix gcc [-Wsign-compare] warning

- targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F746xG/TARGET_DISCO_F746NG/PeripheralPins.c
- targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F746xG/TARGET_NUCLEO_F746ZG/PeripheralPins.c
- targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F756xG/TARGET_NUCLEO_F756ZG/PeripheralPins.c
- targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F767xI/TARGET_NUCLEO_F767ZI/PeripheralPins.c
- targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F769xI/TARGET_DISCO_F769NI/PeripheralPins.c
- targets/TARGET_STM/TARGET_STM32F7/analogin_api.c
Internal ADC pin are now out of PinMap_ADC array
READY
> STM32F7 Internal ADC channels rework

- targets/TARGET_NORDIC/TARGET_NRF5_SDK13/us_ticker.c
Patch for fix:
- rtc overflow-while-set-timestamp issue
- timer has a race condition
It's copy of PR #4016 for the NRF52840 port  source code
**READY**
> [NRF52840]:  fix rtc overflow-while-set-timestamp issue

- targets/targets.json
The `UBLOX_C030` board comes in a number of versions, each of which has its own board ID.  This change makes `UBLOX_C030` a private target that the specific board versions can inherit.  The two board IDs allocated at the moment are `UBLOX_C030_U201` (for the Sara-U201 2G/3G module) and `UBLOX_C030_N211` (for the NBIoT module), hence these are the two new targets.  The targets are identical right now; they will diverge once the mbed Cellular API comes along.
Note that this change is built on top of the change from @philwareublox in pull request #4133.
The `UBLOX_C030` boards are not on the market yet, hence this change cannot cause any customer surprises.
> [UBLOX_C030] create target hierarchy for the specific versions of the C030 board

- tools/export/__init__.py
- tools/export/vscode/__init__.py
- tools/export/vscode/launch.tmpl
- tools/export/vscode/settings.tmpl
- tools/export/vscode/tasks.tmpl
Adds the Visual Studio Code exporter. See also https://github.com/ARMmbed/mbed-os/pull/3568 and https://github.com/ARMmbed/mbed-os/pull/3679.
* [Non-recursive includes](https://github.com/Microsoft/vscode-cpptools/issues/546) are broken in Visual Studio Code on Windows and Linux. Will be fixed upstream. Works on Windows.
> Feature vscode

- features/FEATURE_LWIP/lwip-interface/lwip-sys/arch/lwip_sys_arch.c
- features/FEATURE_LWIP/lwip-interface/lwip-sys/arch/sys_arch.h
Reduces the size of an mbox object from 180 bytes (45w) to 72 bytes (18w). Since the mbox is used in many places in lwip as a lightweight message buffer, this saves roughly 1kB of ram.
Memory comparison of the tcp_echo_parallel test:
```
+---------+----------+-----------+------------+-------+------+-----------+-------------+
|         | target   | toolchain | static_ram | stack | heap | total_ram | total_flash |
+---------+----------+-----------+------------+-------+------+-----------+-------------+
| master  | ARCH_PRO | GCC_ARM   |      20396 |  3072 | 2048 |     25516 |      109397 |
+---------+----------+-----------+------------+-------+------+-----------+-------------+
| rtx5    | ARCH_PRO | GCC_ARM   |      21464 |  3072 | 2048 |     26584 |      112145 | …
```
> lwip: Adopt lightweight mbox implementation based on event flags

- features/FEATURE_BLE/ble/services/iBeacon.h
The previous core_cmInstr was removed, we use cmsis_compiler.h. 
Before the patch:
```
[ERROR] "./mbed-os/cmsis/arm_math.h", line 298: Warning:  #2803-D: unrecognized GCC pragma
"./mbed-os/cmsis/arm_math.h", line 299: Warning:  #2803-D: unrecognized GCC pragma
"./mbed-os/cmsis/arm_math.h", line 300: Warning:  #2803-D: unrecognized GCC pragma
"./mbed-os/cmsis/arm_math.h", line 301: Warning:  #2803-D: unrecognized GCC pragma
"./mbed-os/cmsis/arm_math.h", line 7218: Warning:  #2803-D: unrecognized GCC pragma
"./mbed-os/features/FEATURE_BLE/ble/services/iBeacon.h", line 19: Error:  #5: cannot open source input file "core_cmInstr.h": No such file or directory
.\source\main.cpp: 5 warnings, 1 error
```
After the patch:
```
Image: .\BUILD\NRF51_DK\ARM\BLE_Beacon.hex
```
Tested with BLE_Beacon …
> ble: beacon fix cmsis header

- features/unsupported/USBDevice/USBDevice/USBHAL_KL25Z.cpp
- features/unsupported/USBDevice/USBSerial/USBCDC.cpp
- features/unsupported/USBDevice/USBSerial/USBCDC.h
- features/unsupported/USBDevice/USBSerial/USBSerial.cpp
- features/unsupported/USBDevice/USBSerial/USBSerial.h
1. added call to busReset() to KL25Z HAL; now the USB stack survives if you disconnect the cable, similar to LPC40 
2. busReset callback to update terminal_connected in USBCDC 
3. new bool USBSerial::connected() to read protected terminal_connected property, useful when you want to check if the terminal is ready from main app
> USB: bus reset for KL25Z fix, USBSerial update

- TESTS/mbedtls/ecp/main.cpp
Notes:
Removed using namespace utest::v1 and types from the namespace Ex: utest::v1::status_t. To avoid ambiguity with same name types. 
YES | NO
branch | PR …
> Disambiguate utest::v1 types and remove using statement

- features/unsupported/USBDevice/USBHID/USBKeyboard.h
Minor change - List of key modifiers updated to include the
logo/GUI/windows key. Also added the options to specify the right hand
versions of the keys rather than just the left if for some reason
someone wants to do this.
Changes are limited to the keyboard header file and are backwards
compatible.
The new modifier values are in line with the table given on page 56 of
this document http://www.usb.org/developers/hidpage/HID1_11.pdf
> USB: Added support for the logo key to the keyboard

- TESTS/mbed_drivers/race_test/main.cpp
Fixes #4196. As someone might not be aware that settting default_lib to small has
some implications regarding thread safety, therefore we print an error.
> tests: race test - add not supported for single threaded env

- targets/TARGET_ONSEMI/TARGET_NCS36510/device/TOOLCHAIN_IAR/NCS36510.icf
The IAR linker file allocates the heap size by default to 0x4000, which for this target is causing the mbed-os-example-mesh-minimal application not to be able to fit into the RAM.  It has been changed to 0x3000 (12K, which is 1/4 of the total 48K RAM).  This change both passes all mbed OS tests and allows the mesh minimal example to compile with IAR and run.
helps fix https://github.com/ARMmbed/mbed-os-example-mesh-minimal/issues/63
cc: @pradeep-gr @radhika-raghavendran @danclement @jacobjohnson-ON 
please review and confirm this looks good to you.
**READY**
NO
None
branch | PR
n/a
none
none
n/a
> [NCS36510] Reduce default heap size allocated by IAR to 1/4 of RAM

- tools/test/examples/examples.json
Adding nanostack border router example to the list as requested by @MarceloSalazar 
@MarceloSalazar @SeppoTakalo - what configurations are supported - any toolchain? k64f and k66f and stm32 nucleo f429? Let me know, I can update this
> test - add nanostack to examples.json file

- tools/test/examples/update.py
Added the ability to specify a branch to update rather than a fork
Replaced print commands with the use of a logger
Updated the run_cmd functions in line with previous improvements
Tested locally , branch option tested during oob for 5.4.1 and standard updates tested for full 5.4.1 release.
> Update.py: New feature - update a branch instead of a fork, plus general improvements.

- TESTS/events/timing/main.cpp
A units mistake led to passing 20000 seconds instead of 20000 milliseconds to greentea. The would cause the test to spin for 6 hours if it got stuck anywhere.
@bridadan noticed this popping up during testing of the feature_cmsis5 branch
cc @bulislaw
> Fix timeout units in events timing test

- targets/TARGET_NORDIC/TARGET_NRF5_SDK13/trng_api.c
- targets/targets.json
TRNG hal support for nRF52840 using nordic's TRNG peripheral.
> [NRF52840]: TRNG support

- targets/targets.json
xDot targets has device_name missing so uvision will not export.
**READY**
Resolves #4221
> fixed missing device_name for xDot and removed progen

- tools/config/header.tmpl
Tested with ARM
Before this patch
```
Compile [  5.3%]: analogout_api.c
[Warning] mbed_config.h@30,0:  #1-D: last line of file ends without a newline
Compile [ 10.5%]: analogin_api.c
[Warning] mbed_config.h@30,0:  #1-D: last line of file ends without a newline
Compile [ 15.8%]: startup_LPC17xx.S
[Warning] mbed_config.h@30,0:  #1-D: last line of file ends without a newline
Compile [ 21.1%]: can_api.c
[Warning] mbed_config.h@30,0:  #1-D: last line of file ends without a newline
```
After this patch:
```
Compile [  2.2%]: AnalogIn.cpp
Compile [  4.4%]: BusIn.cpp
Compile [  6.7%]: BusOut.cpp
Compile [  8.9%]: BusInOut.cpp
Compile [ 11.1%]: FlashIAP.cpp
Compile [ 13.3%]: Ethernet.cpp
Compile [ 15.6%]: I2C.cpp
Compile [ 17.8%]: CAN.cpp
Compile [ 20.0%]: I2CSlave.cpp
Compile [ 22.2%]: …
```
> Config: config header file should contain new line

- targets/TARGET_STM/TARGET_STM32F4/TARGET_UBLOX_EVK_ODIN_W2/sdk/wifi_emac/wifi_emac_api.cpp
When attempting to perform a test build of various mbed-os targets with
GCC configured to build -std=gnu++11, all of the targets built
successfully except for this one. It gave errors like this:
```
../mbed-os/targets/TARGET_STM/TARGET_STM32F4/TARGET_UBLOX_EVK_ODIN_W2/sdk/wifi_emac/wifi_emac_api.cpp: In function 'emac_interface_t* wifi_emac_get_interface()':
../mbed-os/targets/TARGET_STM/TARGET_STM32F4/TARGET_UBLOX_EVK_ODIN_W2/sdk/wifi_emac/wifi_emac_api.cpp:331:38: error: use of deleted function 'emac_interface::emac_interface()'
_intf = new emac_interface_t();
^
In file included from ../mbed-os/targets/TARGET_STM/TARGET_STM32F4/TARGET_UBLOX_EVK_ODIN_W2/sdk/wifi_emac/wifi_emac_api.cpp:9:0:
../mbed-os/hal/emac_api.h:150:16: note: 'emac_interface::emac_interface()' is implicitly deleted …
```
> Fix C++11 build error w/ u-blox EVK-ODIN-W2

- targets/TARGET_STM/TARGET_STM32F0/device/stm32f0xx_hal_def.h
- targets/TARGET_STM/TARGET_STM32F1/device/stm32f1xx_hal_def.h
- targets/TARGET_STM/TARGET_STM32F2/device/stm32f2xx_hal_def.h
- targets/TARGET_STM/TARGET_STM32F3/device/stm32f3xx_hal_def.h
- targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_def.h
- targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_def.h
- targets/TARGET_STM/TARGET_STM32L0/device/stm32l0xx_hal_def.h
- targets/TARGET_STM/TARGET_STM32L1/device/stm32l1xx_hal_def.h
- targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_def.h
This PR solves #3932
Before this patch, many warnings like below were generated
during compilation with ArmCC
[Warning] lwip_ethernet.h@57,0:  3135-D: attribute does not apply to any entity
This happens here as ``--gnu`` option of ArmCC is being used, which
enables the GNU compiler extensions that the ARM compiler supports.
This is solved by adding a extra check on __CCARM .
**READY**
All STM32 based boards compile OK
The patch was also tested with F429ZI Ethernet tests
> STM32 Fixed warning related to __packed redefinition

- targets/targets.json
This patch enable the LWIP feature for the LPC4088 and LPC4088_DM boards.
The lwIP stack support already this hardware.
See: ./features/FEATURE_LWIP/lwip-interface/lwip-eth/arch/TARGET_NXP/lpc17_emac.c
> LPC4088: Enable LWIP feature

- tools/build_api.py
- tools/config/__init__.py
- tools/test/config_test/test29/mbed_app.json
- tools/test/config_test/test29/test_data.py
This patch changes the behavior when a bootloader is specified, but not
present. It is now considered a Bad Config™.
Take the mbed-os-example-bootloader-blinky example and delete the 
`bootloader` directory. You will now see a ~nice~awful IOError.
Do the steps to reproduce, but with this branch as mbed-os. The error 
message that you will get it a ConfigException: 
"Bootloader <your-filename> not found".
> Error when bootloader is specified but does not exist

- tools/build_api.py
- tools/config/__init__.py
- tools/make.py
- tools/test.py
- tools/toolchains/__init__.py
The `--build-data` switch is used to specify a file that will be filled
with build metadata.
Testing
> Add --build-data switch to mbed compile and test

- features/FEATURE_COMMON_PAL/nanostack-hal-mbed-cmsis-rtos/arm_hal_interrupt.c
- features/FEATURE_COMMON_PAL/nanostack-hal-mbed-cmsis-rtos/ns_event_loop.c
- features/FEATURE_LWIP/lwip-interface/lwip-sys/arch/lwip_sys_arch.c
- features/FEATURE_LWIP/lwip-interface/lwip-sys/arch/sys_arch.h
- features/FEATURE_UVISOR/source/rtx/secure_allocator.c
- features/FEATURE_UVISOR/source/rtx/uvisor_semaphore.c
- rtos/MemoryPool.h
- rtos/Mutex.h
- rtos/Queue.h
- rtos/Semaphore.h
- rtos/Thread.h
- rtos/mbed_boot.c
- rtos/mbed_rtos_storage.h
mbed OS requires access to internal RTX structures, to use them as RTOS
object's backing storage. To avoid contaminating multiple places across
mbed sources, all required types are typedefed in one header file.
@0xc0170
> CMSIS5: Encapsulate usage of private RTX structures to one header file

- cmsis/TARGET_CORTEX_M/cmsis_compiler.h
- cmsis/arm_math.h
- docs/cmsis_rtx.md
Cherry-picking some work I have done here https://github.com/ARMmbed/mbed-os/pull/4223 (so that one stays smaller with only relevant mbed 2 backward compatible changes).
This PR includes 3 commits that are also upstream (as noted in the commits) - aligned is not there, noted in the our docs.
> cmsis5: fix warnings for ARMCC and IAR - aligned, compiler macro and arm_math

- targets/targets.json
I will try again with the comma deleted as @theotherjimmy suggested in 
my previous attempt. If this fails CI, I truly give up :)
targets/targets.json already added MCU_LPC11U35_501 as an extra label
but it didn't have LPC11U35_501 (without the MCU_ prefix). Both of
these target names are used as folder names to organize files
specific to this device. For example the LPC11U35.ld linker script used
by GCC_ARM for this target is located in a TARGET_LPC11U35_501 folder.
I switched to using inheritance to properly setup the target labels
based on @theotherjimmy comments on PR #4252. Everything in the
XADOW_M0 target appears to have been copy/pasted from LPC11U35_501
anyway so inheritance seems to be the best way to set the values of
the XADOW_M0 properties.
> Inherit Xadow M0 target from LPC11U35_501

- tools/build_api.py
- tools/build_travis.py
- tools/tests.py
- tools/toolchains/__init__.py
Clean-up - removal of targets cmsis5 branch do not support.
cherry-picked from #4223 where it was tested.
> cmsis5: remove devices that are not supported

- doxygen_options.json
- platform/CThunk.h
- platform/CallChain.h
- platform/Callback.h
- platform/CircularBuffer.h
- platform/DirHandle.h
- platform/FileLike.h
- platform/FileSystemLike.h
- platform/LocalFileSystem.h
- platform/SingletonPtr.h
- platform/Stream.h
- platform/Transaction.h
- platform/mbed_application.h
- platform/mbed_critical.h
- platform/mbed_error.h
- platform/mbed_interface.h
- platform/mbed_mem_trace.h
- platform/mbed_rtc_time.h
- platform/mbed_wait_api.h
- platform/toolchain.h
Fix warnings and errors when building API docs in the mbed-os/platform directory using doxygen. Still a rouge warning that I haven't yet gotten to the bottom of but other eyes are welcome. Doxyfile attached that is used to build this (matches the developer site settings)
[doxyfile-developer.txt](https://github.com/ARMmbed/mbed-os/files/960056/doxyfile-developer.txt)
```
C:\dev\mbed-os>doxygen doxyfile-developer
deprecated:11: warning: explicit link request to 'type' could not be resolved
deprecated:14: warning: explicit link request to 'type' could not be resolved
deprecated:17: warning: explicit link request to 'type' could not be resolved
deprecated:53: warning: explicit link request to 'type' could not be resolved
deprecated:83: warning: explicit link request to 'type' could not be …
```
> [platform] Update doxygen comments

- features/FEATURE_LWIP/lwip-interface/lwip-eth/arch/TARGET_NXP/lpc17_emac.c
Unused variable causes compiler warning:
```
/features/FEATURE_LWIP/lwip-interface/lwip-eth/arch/TARGET_NXP/lpc17_emac.c: In function 'lpc_enetif_input':
1>[path removed]\features\FEATURE_LWIP\lwip-interface\lwip-eth\arch\TARGET_NXP\lpc17_emac.c(405,18): warning :  unused variable 'ethhdr' [-Wunused-variable]
```
**READY**
NO
none
none
turn on compiler flag "-Wunused-variable"
> Removed unused variable in TARGET_NXP/lpc17_emac.c

- features/TESTS/filesystem/fat_filesystem/main.cpp
- features/filesystem/fat/ChaN/ffconf.h
The standard is intentionally vague on if filesystems must have '.' and '..' entries, allowing filesystems to omit this concept completely. However, if '.' and '..' entries are present, they **must** appear during directory iteration:
http://pubs.opengroup.org/onlinepubs/9699919799/functions/readdir.html
The '.' and '..' entries are common on FAT filesystems and in most other filesystems. Not providing '.' and '..' entries deviates from convention in a way that may cause user's code to not work when ported to a different filesystem.
This enables '.' and '..' entries in the FAT filesystem.
Note: After this patch, '.' and '..' entries will show up during directory iteration. **This is a breaking change**, but needed to match conventions on host PCs.
I also need to check if the sd-driver …
> Filesystem: Include '.' and '..' in directory iteration

- platform/Stream.cpp
Proposal following discussion on #687 
On small targets there might be memory issues that lead to failing on file allocaiton / opening during Stream creation.
The consequence was application continues running, but any printf
to the Serial object whose Stream was not properly created
would not show any error (and characters would not show either)
Let's add a check to be properly inform user of the error.
**READY**
> Add error check in Stream constructor

- targets/targets.json
Odin WiFi driver is not compatible with sleep right now, disabling it as a workaround.
Closing https://github.com/ARMmbed/mbed-os/issues/4244
**READY**
@andreaslarssonublox
> Odin: Disable sleep as it's not compatible with WiFi driver

- features/FEATURE_LWIP/lwip-interface/emac_lwip.c
- features/FEATURE_LWIP/lwip-interface/lwip_stack.c
Power up emac before reading its settings, such as mac address, for some emac settings are only available after device is powered up.
READY
NO
#3758 
NONE
NONE
NONE
> lwip - power up emac before reading its settings

- targets/TARGET_STM/TARGET_STM32F3/device/stm32f3xx_hal_pcd.h
The USB ISTR register consists of a mix of bits that are
write-zero-to-clear and read only bits.  As such, to clear a bit in
the ISTR, you should simply write the bitwise-NOT of the bit to clear.
Previously, the __HAL_PCD_CLEAR_FLAG() macro would do a bitwise-AND
with the ISTR register contents to clear a bit, but this could result
in another bit being inadvertently cleared if it is set by hardware
between the read and the write of the ISTR register.
Similarly, the USB endpoint registers have two bits that are
write-zero-to-clear, USB_EP_CTR_RX and USB_EP_CTR_TX, but the
PCD_CLEAR_RX_EP_CTR() and PCD_CLEAR_TX_EP_CTR() macros wrote back the
last read value for one of these bits when clearing the other bit.
This could result in inadvertent clearing of one of these bits if it
were set by the …
> STM32F3: Correct handling of USB ISTR and endpoint registers

- tools/targets/__init__.py
Use Intelhex::write_hex_file instead of IntelHex::tofile do the work.
Mentioned records types has no sense for nordic devices.
Sucha a record comes from *.hex file from the mbed-os sources build.
This PR solves https://github.com/ARMmbed/mbed-os/issues/4237
> avoid 03/05 intel-hex records for nordic devices

- targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F429xI/device/TOOLCHAIN_IAR/stm32f429xx_flash.icf
Decrease the interrupt stack size of the NUCLEO_F429ZI to save space when building for IAR.
This is a cherry pick of 78d28ffaffe9e0eaa50b19ece36de5df49c824cf from the CMSIS_5 branch.
> Limit ISR stack to 4k on NUCLEO_F429ZI

- features/unsupported/USBHost/USBHost/TARGET_STM/USBEndpoint_STM.cpp
- features/unsupported/USBHost/USBHost/TARGET_STM/USBHALHost_STM.cpp
- features/unsupported/USBHost/USBHost/USBEndpoint.h
- features/unsupported/USBHost/USBHost/USBHALHost.h
- features/unsupported/USBHost/USBHost/USBHost.cpp
- features/unsupported/USBHost/USBHost/USBHostConf.h
- features/unsupported/USBHost/USBHost/USBHostTypes.h
- features/unsupported/USBHost/USBHostHID/USBHostKeyboard.cpp
- features/unsupported/USBHost/USBHostHID/USBHostKeyboard.h
- features/unsupported/USBHost/USBHostHID/USBHostMouse.cpp
- features/unsupported/USBHost/USBHostHID/USBHostMouse.h
- features/unsupported/USBHost/USBHostHub/USBHostHub.cpp
- features/unsupported/USBHost/USBHostHub/USBHostHub.h
- targets/TARGET_STM/TARGET_STM32F2/device/stm32f2xx_hal_hcd.c
- targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_hcd.c
- targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_hcd.c
- targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_hcd.c
This list of commit brings:
- full speed device support connected on hub for target stm.
- small speed devices connected to hub are not supported
READY
> USBHOST hub support for TARGET_STM

- targets/TARGET_NUVOTON/TARGET_M451/TARGET_NUMAKER_PFM_M453/objects.h
- targets/TARGET_NUVOTON/TARGET_M451/dma_api.c
- targets/TARGET_NUVOTON/TARGET_M451/pwmout_api.c
- targets/TARGET_NUVOTON/TARGET_M451/serial_api.c
- targets/TARGET_NUVOTON/TARGET_NUC472/TARGET_NUMAKER_PFM_NUC472/objects.h
- targets/TARGET_NUVOTON/TARGET_NUC472/dma_api.c
- targets/TARGET_NUVOTON/TARGET_NUC472/pwmout_api.c
- targets/TARGET_NUVOTON/TARGET_NUC472/serial_api.c
This PR includes the following bugfixes for NUMAKER_PFM_NUC472/NUMAKER_PFM_M453 targets.
1. Fix serial error with sync/async calls interlaced.
1. Remove unreleased register setting from flash algorithm.
1. Other minor bugfixes
> [NUC472/M453] Fix serial error with sync/async calls interlaced

- targets/TARGET_STM/TARGET_STM32F2/TARGET_NUCLEO_F207ZG/PeripheralPins.c
- targets/TARGET_STM/TARGET_STM32F2/TARGET_NUCLEO_F207ZG/PinNames.h
- targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F429xI/TARGET_NUCLEO_F429ZI/PeripheralPins.c
- targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F429xI/TARGET_NUCLEO_F429ZI/PinNames.h
- targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F439xI/TARGET_NUCLEO_F439ZI/PeripheralPins.c
- targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F439xI/TARGET_NUCLEO_F439ZI/PinNames.h
- targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F746xG/TARGET_NUCLEO_F746ZG/PeripheralPins.c
- targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F746xG/TARGET_NUCLEO_F746ZG/PinNames.h
- targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F756xG/TARGET_NUCLEO_F756ZG/PeripheralPins.c
- targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F756xG/TARGET_NUCLEO_F756ZG/PinNames.h
- targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F767xI/TARGET_NUCLEO_F767ZI/PeripheralPins.c
- targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F767xI/TARGET_NUCLEO_F767ZI/PinNames.h
- targets/targets.json
STM32 NUCLEO boards with Ethernet connector are:
- NUCLEO_F207ZG
- NUCLEO_F429ZI
- NUCLEO_F746ZG
- NUCLEO_F767ZI
If you are using Ethernet, and not SPI Arduino pins:
=> keep your board with the default configuration
If you are using SPI Arduino pins, and not Ethernet:
=> you should remove the JP6 bridge on the front side of the board
If you need SPI Arduino and Ethernet:
=> you have to patch the NUCLEO board on the back side: set solder bridge SB121 to off, and SB122 to on
=> D11 is no more connected to PA_7 but to PB_5
=> enable ETHERNET_SPI_D11_CONFLICT macro in mbed_app.json file
READY
> STM32 NUCLEO boards with Ethernet connector: solve conflict with D11 arduino pin

- features/FEATURE_LWIP/lwip-interface/EthernetInterface.cpp
- features/FEATURE_LWIP/lwip-interface/lwip-sys/lwip_random.c
- features/FEATURE_LWIP/lwip-interface/lwip-sys/lwip_random.h
- features/FEATURE_LWIP/lwip-interface/lwip-sys/lwip_tcp_isn.c
- features/FEATURE_LWIP/lwip-interface/lwip-sys/lwip_tcp_isn.h
- features/FEATURE_LWIP/lwip-interface/lwip_stack.c
- features/FEATURE_LWIP/lwip-interface/lwipopts.h
Added support for common pal random library to LWIP.  This corrects issue: https://github.com/ARMmbed/mbed-os/issues/3891
Integrated LWIP TCP sequence number initialization reference code to mbed LWIP stack.
Corrected LWIP adaptation Coverity and compiler warnings.
READY
NO
None
None
None
> LWIP random library and TCP sequence number improvements

- mbed.h
- rtos/rtos.h
Currently the MBED_VERSION on master is set to 5.2.1 and 5.0.123 which is confusing. I can see two ways of fixit that:
- After we make a release we make a change on master to reflect the last released mbed version
- We set it to 0 to avoid cofusion and set it to release version for release branch. @adbridge favors this solution.
One possible issue with second approach is if someone will get an idea of disabling/enabling features basing on MBED_VERSION macro in their app, not that it would work now very well, so maybe it's not a problem after all.
> Set mbed minor and patch version to 0 for master

- tools/export/iar/__init__.py
Compiling with some IAR exports would result in a warning/error message saying
```
[Su004]: Option -O can only occur once
```
This is a Bad Thing^TM.
Resolves  https://github.com/ARMmbed/mbed-cli/issues/487
We had an incomplete filter for optimization options that would be put in the 
miscellaneous options section of the IAR project XML. It did not filter out 
some options, like `-Oh` and `-Ohz`
This patch fixes this bug by filtering out a wider range of optimization options
from the miscellaneous flags section.
> Revome duplicate optimization flags in IAR export

- targets/TARGET_STM/stm_spi_api.c
Default timeout of 10ms was reported in #4300
There seems to be conditions or use cases where the system is loaded with
higher priority tasks so that SPI transfer would be delayed more than 10ms.
This PR is sent because of request for a quick fix and this should unblock the situation, nevertheless I am not sure that the problem is entirely understood.
How to reproduce the issue was not explained in the ticket.
The patch was not tested and needs to be tested by reporters of the issue #4300
> Increase stm32 timeout for spi transfers

- targets/TARGET_ONSEMI/TARGET_NCS36510/device/TOOLCHAIN_ARM/NCS36510.sct
- targets/TARGET_ONSEMI/TARGET_NCS36510/device/TOOLCHAIN_GCC_ARM/NCS36510.ld
- targets/TARGET_ONSEMI/TARGET_NCS36510/device/TOOLCHAIN_IAR/NCS36510.icf
- targets/TARGET_ONSEMI/TARGET_NCS36510/device/cmsis_nvic.c
Fix the ram address of the vector table on the NCS36510. Also reserve space for it in the linker scripts.
This is based on  94a0256cad2485b23638bde3072641b45ce8b554 from the CMSIS_5 branch.
> Fix RAM vector table for NCS36510

- targets/targets.json
This change is part of CMSIS5 update. Enabling CMSIS_VECTAB_VIRTUAL for
Nordic platform is necessary to preserve platform specific NVIC ops.
Notes:
* Taken from https://github.com/ARMmbed/mbed-os/pull/4294
CC: @pan- @c1728p9 @nvlsianpu
> Enable CMSIS_VECTAB_VIRTUAL for Nordic platforms

- TESTS/events/queue/main.cpp
- TESTS/mbed_drivers/race_test/main.cpp
- TESTS/mbed_drivers/stats/main.cpp
- TESTS/mbed_drivers/stl_features/main.cpp
- TESTS/mbedmicro-rtos-mbed/basic/main.cpp
- TESTS/mbedmicro-rtos-mbed/isr/main.cpp
- TESTS/mbedmicro-rtos-mbed/mail/main.cpp
- TESTS/mbedmicro-rtos-mbed/malloc/main.cpp
- TESTS/mbedmicro-rtos-mbed/mutex/main.cpp
- TESTS/mbedmicro-rtos-mbed/queue/main.cpp
- TESTS/mbedmicro-rtos-mbed/semaphore/main.cpp
- TESTS/mbedmicro-rtos-mbed/signals/main.cpp
- TESTS/mbedmicro-rtos-mbed/threads/main.cpp
- features/FEATURE_LWIP/TESTS/mbedmicro-net/tcp_echo_parallel/main.cpp
- features/FEATURE_LWIP/TESTS/mbedmicro-net/udp_echo_parallel/main.cpp
- features/TESTS/filesystem/heap_block_device/main.cpp
- targets/TARGET_ARM_SSG/mbed_rtx.h
- targets/TARGET_NORDIC/mbed_rtx.h
Reduce RAM consumption so all tests can still be built when using CMSIS/RTX5. Also reduce clutter by removing the per target stack size defines in the tests.
> Reduce test overhead in preperation for CMSIS 5

- targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L476xG/TARGET_DISCO_L476VG/system_stm32l4xx.c
- targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L476xG/TARGET_NUCLEO_L476RG/system_stm32l4xx.c
- targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L476xG/device/TOOLCHAIN_ARM_MICRO/stm32l476xx.sct
- targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L476xG/device/TOOLCHAIN_ARM_STD/stm32l476xx.sct
- targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L476xG/device/TOOLCHAIN_GCC_ARM/STM32L476XX.ld
- targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L476xG/device/TOOLCHAIN_IAR/stm32l476xx.icf
- targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L476xG/device/cmsis_nvic.c
- targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L476xG/device/nvic_addr.h
- targets/targets.json
Adds up bootloader support to L476RG
Tested ok with mbed-os-example-bootloader-blinky
Firmware update found
Starting applicationÿApplication started now...............................................................................................
> 17q2 l4 bootloader

- platform/mbed_sdk_boot.c
There's already PR (to master) that reintroduces cmain.S to fix IAR nonrtos bootup sequence. Thus we should update this comment to reflect that change
> mbed sdk boot: fix IAR note

- tools/toolchains/__init__.py
Strangely, python does not seem to treat streams as unicode by default. 
Therefore, we need to manually decode the STDERR stream from the compiler before
we use it as it might contain not-ascii characters.
Resolves #4318
cc @teetak01
> Decode STDERR from compiler

- features/FEATURE_LWIP/lwip-interface/lwipopts.h
Current version of lwIP has a bug in its checksum-on-copy code - see
#4140 and https://savannah.nongnu.org/bugs/?50914
Pending a fix from lwIP, set LWIP_CHECKSUM_ON_COPY to 0 to work around.
Will impact performance.
@mikaleppanen , @geky - if there's not a patch for the bug in the next few days, I think we should do this.
> Disable lwIP checksum-on-copy

- features/netsocket/nsapi_dns.cpp
Observed during investigation of
https://github.com/ARMmbed/mbed-os/issues/4246 - DNS queries sent
the entire buffer, not just the bit filled in.
Inefficient, especially for 6LoWPAN, and a security hole - the trailing
data could be previously-used heap.
> NSAPI - Don't send trailing garbage in DNS queries

- tools/config/__init__.py
- tools/test/toolchains/api.py
- tools/toolchains/__init__.py
This allows a user to build a completely customized bootloader configuration.
The new configuration options are:
- `target.mbed_app_start`: The start address of the application
- `target.mbed_app_size`: The size of the application
When elided, the defaults are:
- `target.mbed_app_start` defaults to the start of ROM
- `target.mbed_app_size` defaults to the remaining ROM from the start of the application
Checks are performed to verify that:
- `target.mbed_app_start` is a location in ROM
- `target.mbed_app_size` + `target.mbed_app_start` is also a location in ROM or 1 byte past the end of ROM
and size, respectively
> Add support for Unmanaged Bootloader

- mbed.h
Allows access to mbed debug printing when including `mbed.h`
Currently, you must include `mbed_debug.h` in addition to `mbed.h` if you want to use the debug print function.
> Include mbed_debug.h in mbed.h

- targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_dma.c
- targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_dma.h
Fix for #4262 
This fixes potential corner case issues relating to
stopping, starting, init/deinit, and setting callbacks.
The issue is only found with the stm32f4xx targets.
> stm32f4xx: Consider all DMA ready/busy states in conditionals

- targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/libraries/experimental_section_vars/section_vars.h
After https://github.com/ARMmbed/mbed-os-example-ble/pull/80 was merged, the Austin Example build CI correctly started failing for NRF51_DK and NRF52_DK with IAR with a mulitple symbol definition:
```
Error[Li006]: duplicate definitions for "fs_config"; in "Z:\home\jimbri01\src\a
rmmbed\mbed-os-example-ble\BLE_EddystoneService\BUILD\NRF51_DK\iar\mb
ed-os\targets\TARGET_NORDIC\TARGET_NRF5\TARGET_SDK11\libraries\fds\fd
s.o"
, and "Z:\home\jimbri01\src\armmbed\mbed-os-example-ble\BLE_Eddystone
Service\BUILD\NRF51_DK\iar\source\PersistentStorageHelper\nrfPersiste
ntStorageHelper\nrfConfigParamsPersistence.o"
[ERROR] Error[Li006]: duplicate definitions for "fs_config"; in "Z:\home\jimbri01\src\a
rmmbed\mbed-os-example-ble\BLE_EddystoneService\BUILD\NRF51_DK\iar\mb …
```
> Add static to NRF5 SDK11 macro definition

- cmsis/TOOLCHAIN_IAR/cmain.S
This reverts commit 5f294451030ee1f7982afbb41c2badb7b986d822 - but only partially.
cmain.S for IAR is still required to keep mbed SDK boot process as it was. This
startup file for IAR is active for non-rtos projects.
Fixes #4330
Thanks to @YarivCol for reporting this. Tested locally with blinky mbed OS and mbed-dev gpio example (K64F board) - thus should be compatible with all new changes (new mbed boot that is coming to mbed OS).
> Revert partially "Remove Cortex A support from CMSIS/RTOS"

- tools/test/examples/examples.json
- tools/test/examples/examples_lib.py
Currently the CI is aware of the GitHub repository and the mbed developer site mercurial repo mirror when it is building and testing mbed OS example applications. It will pick the mbed developer site repo if it is defined in the `examples.json` file in the test folder: https://github.com/ARMmbed/mbed-os/blob/master/tools/test/examples/examples.json#L20
This is not always the desirable behavior, as GitHub is often used as the staging point for changes.
This PR adds an explicit flag to the `examples.json` file that allows you to specify which repo source to use during testing.
**READY**
NO
Currently blocking https://github.com/ARMmbed/mbed-os/pull/4294
> Allow examples to specify which repo source to use for testing

- rtos/rtx5/mbed_rtx_conf.h
CI shield test (SPI test) may need 7 mutexes
DEPENDENT ON #4294 
Once that officially lands on Master, this PR should be rebased and then retargeted to Master.
> Add up OS_MUTEX_NUM for ARMCC compiler

- tools/export/vscode/settings.tmpl
Since the vscode C++ plugin has been upgraded to 0.11 the intellisense engine has changed, and it does not understand the mbed code base.
Quick fix is to set the engine back to the previous engine.
See https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/LanguageServer/FAQ.md#what-is-the-difference-between-includepath-and-browsepath-in-c_cpp_propertiesjson
Need a proper patch though, created #4380 as a follow up.
@sg- @theotherjimmy
> Fix vscode intellisense engine to 'Tag Parser'

- tools/export/uvision/__init__.py
There was a bug in the supported check for uvision that disabled all generic
core based exports. This PR fixes that bug
> Allow generic core exports to UVision

- features/nanostack/FEATURE_NANOSTACK/mbed-mesh-api/README.md
- features/nanostack/FEATURE_NANOSTACK/mbed-mesh-api/mbed-mesh-api/mesh_interface_types.h
- features/nanostack/FEATURE_NANOSTACK/mbed-mesh-api/source/thread_tasklet.c
Thread minimal end device operating mode added.
READY
NO
Can be tested manually by using mesh minimal example
> Thread med support

- features/nanostack/FEATURE_NANOSTACK/mbed-mesh-api/source/ThreadInterface.cpp
Thread device needs to wait for connectivity:
* routers will create new network and get local connectivity
* end device will get connectivity once attached to existing network
* devices without network settings gets connectivity once commissioned and attached to network
This PR removes connection timeout from Thread interface connect method. Then end devices and devices without network configuration settings will try connection for ever. This change does not affect to routers as they will get local connectivity.
**READY**
NO
* Set flag thread-use-static-link-config to false to get uncommissioned device
* Once device is started the ThreadInterface connect method does not …
> Adjust Thread interface connect timeout

- cmsis/TOOLCHAIN_IAR/cmain.S
> Update cmain.S license

- features/FEATURE_COMMON_PAL/mbed-coap/CHANGELOG.md
- features/FEATURE_COMMON_PAL/mbed-coap/source/sn_coap_protocol.c
This commit includes
- Fix for https://github.com/ARMmbed/mbed-client/issues/481
- Detailed Changelog available here https://github.com/ARMmbed/mbed-coap/compare/v4.0.3...v4.0.4
**READY**
NO
Detailed Changelog available here https://github.com/ARMmbed/mbed-coap/compare/v4.0.3...v4.0.4
> Fix for blockwise observation failure

- tools/test/build_api/build_api_test.py
- tools/toolchains/__init__.py
Each of C, C++, ASM and linker now depend on their command line invocations.
For example, adding `-DFoo` to the mbed CLI invocation (`mbed compile -DFoo`)
would force a complete recompile. Further, switching build profiles will force
all C and C++ to recompile. The assembler flags are the same ¯\\\_(ツ)\_/¯.
Resolves #2412 
the appropriate rebuild
> Have objects depend on their respective compiler invocations

- features/unsupported/USBHost/USBHostMSD/USBHostMSD.cpp
- features/unsupported/USBHost/USBHostMSD/USBHostMSD.h
- features/unsupported/tests/usb/host/mass_storage/main.cpp
Since BlockDevice has been introduced USBHostMSD is no more supported.
With this patch USBhostMSD inherits from BlockDevice , and can be used with  FATFileSystem class.
As USBHostMSD does not inherit from FATFilesystem any more, the code using the class has to be modified.  
READY
> Usb host msd block device

- tools/export/iar/iar_definitions.json
Enable IAR exporter for nRF52840-xxAA devices
**READY**
> enable iar exporter for nRF52840

- targets/TARGET_STM/TARGET_STM32F3/TARGET_STM32F302x8/device/cmsis_nvic.c
- targets/TARGET_STM/TARGET_STM32F3/TARGET_STM32F303x8/device/cmsis_nvic.c
- targets/TARGET_STM/TARGET_STM32F3/TARGET_STM32F303xC/device/cmsis_nvic.c
- targets/TARGET_STM/TARGET_STM32F3/TARGET_STM32F303xE/device/cmsis_nvic.c
- targets/TARGET_STM/TARGET_STM32F3/TARGET_STM32F334x8/device/cmsis_nvic.c
The STM32F3 cmsis_nvic code is currently checking for a specific flash address when determining if the vector table is in flash or RAM.  By changing the test to instead see if the vector table base is NOT set to
the RAM address, it simplifies the code, and removes the dependency on the flash vectors being located at a specific address.  This becomes important when adding a custom boot loader, which requires that the flash vector table location in the mbed project be at a different address.
READY
NO
None
None
None
Create an STM32F3 based project but with the flash vector table moved to a different location (requires modifying the VECT_TAB_OFFSET setting in your target's system_stm32f3xx.cpp file, and moving the KEEP(*(.isr_vector)) line from your target's ld file (e.g. STM32F303XC.ld) to a …
> STM32F3: Remove dependence upon a specific flash vector table location

- targets/TARGET_STM/TARGET_STM32F0/can_device.h
- targets/TARGET_STM/TARGET_STM32F1/can_device.h
- targets/TARGET_STM/TARGET_STM32F2/can_device.h
- targets/TARGET_STM/TARGET_STM32F3/can_device.h
- targets/TARGET_STM/TARGET_STM32F4/can_device.h
- targets/TARGET_STM/TARGET_STM32F7/can_device.h
- targets/TARGET_STM/TARGET_STM32L4/can_device.h
- targets/TARGET_STM/can_api.c
Can init function needs 11 bits at the same level to synchronize to the CAN bus. 
In some cases this cannot occur (refer to #3863 where the object is initialized at a lower frequency than the bus and the bus is very busy). We thus need a timeout mechanism to exit the init function.
in TARGET_STM/can_api.c: 
```
/* Get tick */
tickstart = HAL_GetTick();
can->BTR = btr;
can->MCR &= ~(uint32_t)CAN_MCR_INRQ;
while ((can->MSR & CAN_MSR_INAK) == CAN_MSR_INAK) {
if((HAL_GetTick() - tickstart ) > 2)
{
status = 0;
break;
}
}
if (status ==0) {
error("can ESR  0x%04x.%04x + timeout status %d", (can->ESR&0XFFFF0000)>>16, (can->ESR&0XFFFF), status);
}
```
**READY**
NO
refer to #3863 : need a 1st device that overloads the CAN bus with a high frequency. Then try to initialize the 2nd device with a low …
> Fix for #3863: STM Check can sync error

- TESTS/mbed_drivers/race_test/main.cpp
Simple fix, this condition was added recently and the logic was unfortunately inverted.
cc @jeromecoutant
> race tests: fix conditional check for MBED_RTOS_SINGLE_THREAD being defined

- features/TESTS/filesystem/mbr_block_device/main.cpp
- features/TESTS/filesystem/multipart_fat_filesystem/main.cpp
- features/filesystem/bd/MBRBlockDevice.cpp
- features/filesystem/bd/MBRBlockDevice.h
- features/filesystem/fat/ChaN/ff.cpp
- features/filesystem/fat/ChaN/ffconf.h
- features/filesystem/fat/FATFileSystem.cpp
- features/filesystem/fat/FATFileSystem.h
The MBRBlockDevice adds support for standard storage partitioning. This is the standard partitioning scheme everyone knows and loves (and is probably using underneath their OS). For more information:
https://en.wikipedia.org/wiki/Master_boot_record
Here's the example:
``` cpp
#include "HeapBlockDevice.h"
#include "MBRBlockDevice.h"
// Create a block device with 64 blocks of size 512
HeapBlockDevice mem(64*512, 512);
// Partition into two partitions with ~half the blocks
MBRBlockDevice::partition(&mem, 1, 0x00, 0*512, 32*512);
MBRBlockDevice::partition(&mem, 2, 0x00, 32*512);
// Create a block device that maps to the first 32 blocks (excluding MBR block)
MBRBlockDevice part1(&mem, 1);
// Create a block device that maps to the last 32 blocks
MBRBlockDevice part2(&mem, 2); …
```
> bd: Add MBR block device for standard storage partitioning

- targets/targets.json
- tools/build.py
- tools/build_api.py
- tools/export/__init__.py
- tools/make.py
- tools/options.py
- tools/project.py
- tools/test.py
This PR will disable building of Cortex-A targets for the mean time. The tools 
bits that disable Cortex-A are (currently) in a single commit that can be 
reverted to re-enable Cortex-A support.
> Disable Cortex-A in tooling for better error messages

- mbed.h
This PR is trying to address issues with using latest master. The version macros that we have currently on master brings confusion as they are set to values that are valid - the releases that are out there, thus do not indicate that this is development version and might bring confusion.
If we remove them, then any sw that is on bleeding edge, can easily use these as follows:
```
#ifndef MBED_VERSION
// bleeding edge, be aware you are using moving target
#else
// some compatiblity layers
#if defined(MBED_VERSION == x.x.x)
// do something special for x.x.x version
#endif
#endif
```
We considered using specific version for devel (like patch set to -1), this however does not protect sw anyhow. Removing these macros should be more clear than it is now (using really old values that are valid …
> mbed: version macros are not defined on master

- features/FEATURE_BLE/targets/TARGET_NORDIC/TARGET_NRF5/source/btle/btle_security.h
- features/FEATURE_BLE/targets/TARGET_NORDIC/TARGET_NRF5/source/btle/btle_security_pm.cpp
- features/FEATURE_BLE/targets/TARGET_NORDIC/TARGET_NRF5/source/nRF5xSecurityManager.h
Implementation of SecurityManager::getAddressesFromBondTable (SD API <3, 5>)
**READY**
> [NRF52840]: SecurityManager::getAddressesFromBondTable

- targets/targets.json
- tools/build.py
- tools/build_api.py
- tools/export/__init__.py
- tools/make.py
- tools/options.py
- tools/project.py
- tools/test.py
- tools/test/build_api/build_api_test.py
I found my prior implementation of disabling Cortex-A unsatisfactory.
This PR actually fixes a long-standing bug: you can compile mbed OS 5 for mbed OS 2 only targets.
> Disallow building of mbed OS 2 + RTOS, and remove mbed OS 5 support for Cortext-A

- mbed.h
Certain public APIs are being added to mbed.h so as to make them
part of namespace mebd.
APIs being added are:
* drivers/UARTSerial.h
* platform/ATCmdParser.h
* platform/mbed_poll.h
* netsocket/nsapi_ppp.h
**READY**
NO
> Adding APIs to namespace mbed

- tools/build_api.py
- tools/config/__init__.py
- tools/options.py
The two commits in this PR do independent things:
We currently do not allow a user to override noncumulative attributes in the app
config. Attempting to override `target.core`, `target.default_lib` or
`target.default_toolchain` will error out with "Atempted to override undefined 
parameter". 
Instead, lets allow user to do this.
This commit  delays evaluation of the build profiles until after the app config has had a chance to override things.
> Allow target attribute overrides in app config and pick toolchain with default_toolchain

- features/FEATURE_LWIP/lwip-interface/EthernetInterface.cpp
- features/FEATURE_LWIP/lwip-interface/lwip_stack.c
- features/FEATURE_LWIP/lwip-interface/lwip_stack.h
- features/FEATURE_LWIP/lwip-interface/ppp_lwip.cpp
External EMAC drivers are currently directly attaching to lwip_stack.c
via mbed_lwip_bringup et al. Restore the original prototypes changed in #4119 to avoid
compatibility breakage.
Fix some other type mismatches between lwip_stack.c and lwip_stack.h.
Ultimately #4079 should give a better way of EMAC drivers attaching.
> Restore mbed OS 5.4 mbed_lwip_ function prototypes

- features/filesystem/fat/ChaN/ff.cpp
- features/filesystem/fat/ChaN/ff.h
- features/filesystem/fat/ChaN/ffconf.h
- features/filesystem/fat/FATFileSystem.cpp
This is necessary for support of block devices with >512 byte blocks, such as most SPI flash parts. This is necessary for FAT support of SPI flash parts.
- Enabled support of up to 4096 byte blocks
- Added support for heap-backed buffers using _FS_HEAPBUF
- Necessary to avoid stack overflows
- Avoids over-aggresive allocations of _MAX_SS
- Enabled _FS_TINY to further reduce memory footprint
- Haven't found a downside for this yet except for possible thread contention
cc @simonqhughes
> FAT: Add support for block sizes of 512-4096 bytes

- features/unsupported/USBDevice/USBDevice/USBEndpoints_KL25Z.h
- features/unsupported/USBDevice/USBDevice/USBHAL_KL25Z.cpp
Move memory allocation to be done at a different location. Currently allocated
in a function that is called from the interrupt handler. 
This is a fix for https://github.com/ARMmbed/mbed-os/issues/4250
**READY
https://github.com/ARMmbed/mbed-os/pull/4277
Passed USB tests when compiled with IAR, GCC_ARM and ARM toolchains
> Issue#4250: Fix USB driver for Kinetis devices

- targets/targets.json
Add IAR to post_binary_hook toolchains
Notes:
When building our Dragonfly code (target MTS_DRAGONFLY_F411RE) with ARM or GCC_ARM, our boot loader is properly pre-pended to the bin file. However, when building with the IAR compiler, it is not. Both targets, MTS_DRAGONFLY_F411RE and MTS_MDOT_F411RE need the boot loader pre-pended to the bin file to function. This change adds the bin during post build.
READY
There are no API changes.
None
Make sure the boot loader is pre-pended when compiling with IAR... I have confirmed for both products.
None.
Compile …
> MTS_DRAGONFLY_F411RE/MTS_MDOT_F411RE: add IAR to post_binary_hook toolchains

- targets/TARGET_STM/TARGET_STM32F1/device/stm32f1xx_hal_i2c.c
- targets/TARGET_STM/TARGET_STM32F2/device/stm32f2xx_hal_i2c.c
- targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_i2c.c
- targets/TARGET_STM/TARGET_STM32L1/device/stm32l1xx_hal_i2c.c
- targets/TARGET_STM/pinmap.c
This PR fixes issue reported in #4214 
This requires an update in HAL but also a fix in the GPIO management of F1 family targets
**READY**
Test reported in #4214 is passed ok with the fix.
CI test cases passed ok as well on all 4 families where fix applies:
+-------------------+---------------+---------------+--------+--------------------+-------------+
| target            | platform_name | test suite    | result | elapsed_time (sec) | copy_method |
+-------------------+---------------+---------------+--------+--------------------+-------------+
| NUCLEO_F091RC-ARM | NUCLEO_F091RC | tests-api-i2c | OK     | 59.24              | shell       |
| NUCLEO_F103RB-ARM | NUCLEO_F103RB | tests-api-i2c | OK     | 73.24              | shell       |
| NUCLEO_F207ZG-ARM | NUCLEO_F207ZG | tests-api-i2c …
> Fix i2c communication with pcf8574 on stm32 targets of f1, f2, f4 and l1 families 

- features/FEATURE_COMMON_PAL/mbed-coap/module.json
- features/FEATURE_COMMON_PAL/mbed-coap/source/include/sn_coap_protocol_internal.h
- features/FEATURE_COMMON_PAL/mbed-coap/source/sn_coap_parser.c
- features/FEATURE_COMMON_PAL/mbed-coap/source/sn_coap_protocol.c
This commit includes:
* Add support for sending response to duplicate messages
* Add randomness for retransmission time
* Fix usage sn coap blockwise max time data stored
* CoAP parser option handler does not seem to handle "Option Length" completely according to spec
* Handle '0' value if duplication buffer size is set through the sn_coap_protocol_set_duplicate_buffer_size()
READY
NO
Detailed Changelog available here https://github.com/ARMmbed/mbed-coap/compare/v4.0.4...v4.0.6
> mbed-coap fixes

- features/frameworks/greentea-client/source/greentea_metrics.cpp
- features/storage/FEATURE_STORAGE/cfstore/source/cfstore_svm.cpp
- features/storage/FEATURE_STORAGE/cfstore/source/cfstore_test.c
- features/storage/FEATURE_STORAGE/cfstore/source/configuration_store.c
- features/storage/FEATURE_STORAGE/storage-volume-manager/source/storage_volume.cpp
- features/storage/FEATURE_STORAGE/storage-volume-manager/source/storage_volume_manager.cpp
Fix deprecation warnings in config store and fix a warning in greentea metrics.
> Warning fixes

- tools/test/toolchains/api.py
I swapped two letters in "location". my bad.
Testing is covered by travis, so this is good to go when that finishes
> Fix typo in test code

- features/filesystem/bd/MBRBlockDevice.cpp
- targets/TARGET_Realtek/TARGET_AMEBA/sdk/soc/realtek/common/bsp/basic_types.h
> Proper fix for 1fa30b7403176349557d6aea2f02a2075aa6f03b

- targets/TARGET_STM/hal_tick_16b.c
- targets/TARGET_STM/us_ticker_16b.c
This Pull requests contains several fixes around 16 bits tickers. 
Those fixes are addressing points that were raised in #1701 , #2519, #2598, #4217 
Changes will also be aligned with changes ongoing in #4417. (needs LL include)
So this PR will be rebased after #4417 is merged.
**READY**
**F0**
**F1**
**L0**
> Fix corner cases in STM32 16bit tickers

- targets/TARGET_STM/TARGET_STM32F0/serial_device.c
- targets/TARGET_STM/TARGET_STM32F1/serial_device.c
- targets/TARGET_STM/TARGET_STM32F2/serial_device.c
- targets/TARGET_STM/TARGET_STM32F3/serial_device.c
- targets/TARGET_STM/TARGET_STM32F4/serial_device.c
- targets/TARGET_STM/TARGET_STM32F7/serial_device.c
- targets/TARGET_STM/TARGET_STM32L0/serial_device.c
- targets/TARGET_STM/TARGET_STM32L1/serial_device.c
- targets/TARGET_STM/TARGET_STM32L4/serial_device.c
- targets/TARGET_STM/serial_api.c
- targets/TARGET_STM/serial_api_hal.h
Reworked the serial_format() function for STM32F0x devices to take the format in the form:
`data_bits - parity - stop_bits`
(E.g. 8 - N - 1) where data_bits exclude the parity bit.
Added a case for 7 bits data as at least STM32F0x1/STM32F0x2/STM32F0x8 support 7 bits data.
Consolidated serial_format() and uart_init() functions into a general TARGET_STM serial_api.c file since the functions are common to all STM targets.
DONE
YES
After this is merged, behaviour for STM32s will be consistent with the API behaviour for other manufacturers. Users won't be able to specify 9bits data + (parity != none). Users will have to review their applications to ensure the way they specify their format takes into account that the parity bit is no longer included in the data_bits count.
Fixes #4189
> STM32s Serial: Correct handling of parity bits

- targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/api/lp_ticker.c
When initializing the RTC on Kinetis devices, handle the case where the time overflow interrupt is pending and the case where the time alarm flag is pending. These flags persist across reset and if not handled will cause a crash when powering up the low power ticker.
This problem manifested as a lp_ticker test failure on the K22F and K64F on CI only when running a nightly. This problem has been present but was made obvious by PR #4094 which configures all tickers to interrupt at least every MBED_TICKER_INTERRUPT_TIMESTAMP_MAX_DELTA (~31 minutes). This caused the RTC alarm to fire 31 minutes after the lp_ticker or lp_timeout test and caused the next run of the lp_ticker test to crash on boot.
> Safely initialize RTC on kinetis devices

- features/FEATURE_LWIP/lwip-interface/lwip-eth/arch/TARGET_NXP/lpc17_emac.c
The semaphore xTXDCountSem had the count to match the number of resources available, but was being used as a binary semaphore in a loop to listen for events. This patch updates the logic to make use of the resource count.
With RTX5 the OS traps with an error if the a semaphore is released more times than its count with an error similar to "Semaphore 10000e6c error -17". Because xTXDCountSem is being used as a binary semaphore it triggered this trap. With this patch the semaphore is no longer used as a binary semaphore and no longer traps.
> Fix semaphore usage on lpc1768 emac

- features/FEATURE_COMMON_PAL/nanostack-hal-mbed-cmsis-rtos/arm_hal_timer.cpp
Intent is to use 2kB for stack, not 16kB, but the divide operand
has been forgotten here.
During a CMSIS2/RTX2 work this typo has appeared in our timer. Caused RAM usage to jump 14kB up.
**READY**
Should be included in 5.5 RC2
> Fix typo that used 16kB for stack.

- doxyfile_options
- doxygen_options.json
- events/Event.h
- events/EventQueue.h
**NOTE** The commit history is not cleaned up and pulls in a lot of duplicate changes from @sg-'s pull request linked below. Putting this review up to get eyes on the doxygen changes as the structure changed a decent amount for how I documented the overloaded functions. This also pulls in Jimmy's CI changes so I can get a CI run in.  
**Commit history will be cleaned up prior to merging.**
**Note to reviewers:** In particular *Event.h* and *EventQueue.h* are the modified files that are unique to this PR.
_______________________________________________________________________________________________________
Documentation changes to Doxygen descriptions for the Event module to allow Doxygen to build without errors/warnings. 
All overloaded functions had refereed to the base function with …
> Doxygen EventQueue updates to not produce warnings and errors [DOC Changes Only]

- targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L476xG/TARGET_DISCO_L476VG/system_stm32l4xx.c
- targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L476xG/TARGET_NUCLEO_L476RG/system_stm32l4xx.c
- targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L476xG/device/TOOLCHAIN_ARM_MICRO/stm32l476xx.sct
- targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L476xG/device/TOOLCHAIN_ARM_STD/stm32l476xx.sct
- targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L476xG/device/TOOLCHAIN_GCC_ARM/STM32L476XX.ld
- targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L476xG/device/TOOLCHAIN_IAR/stm32l476xx.icf
- targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L476xG/device/nvic_addr.h
- targets/targets.json
Rebase against master for: #4063 
> 17q2 l4 bootloader - Rebase

- features/nanostack/FEATURE_NANOSTACK/targets/TARGET_NCS36510/NanostackRfPhyNcs36510.cpp
RTX porting for this driver was done against the previous API that
have now been reverted.
Please take this into 5.5 RC2
> Fix compilation for NCS36510 RF driver.

- TESTS/mbed_hal/rtc_time/main.cpp
- platform/mbed_mktime.c
- platform/mbed_mktime.h
- targets/TARGET_Atmel/TARGET_SAM_CortexM4/rtc_api.c
- targets/TARGET_NUVOTON/TARGET_M451/rtc_api.c
- targets/TARGET_NUVOTON/TARGET_NUC472/rtc_api.c
- targets/TARGET_NXP/TARGET_LPC176X/rtc_api.c
- targets/TARGET_NXP/TARGET_LPC408X/rtc_api.c
- targets/TARGET_NXP/TARGET_LPC43XX/rtc_api.c
- targets/TARGET_RENESAS/TARGET_RZ_A1H/rtc_api.c
- targets/TARGET_RENESAS/TARGET_VK_RZ_A1H/rtc_api.c
- targets/TARGET_Realtek/TARGET_AMEBA/rtc_api.c
- targets/TARGET_STM/rtc_api.c
Remove usage of mktime and localtime from RTC drivers. This PR was taken from #4479 and expanded to cover all the targets since they have the same issue as ST devices. @pan- feel free to modify this as necessary.
> Fix rtc api time conversion

- targets/TARGET_Silicon_Labs/TARGET_EFM32/common/objects.h
- targets/TARGET_Silicon_Labs/TARGET_EFM32/trng/sl_trng.c
- targets/TARGET_Silicon_Labs/TARGET_EFM32/trng/sl_trng.h
- targets/TARGET_Silicon_Labs/TARGET_EFM32/trng/trng_api.c
- targets/targets.json
Moving PR #4051 to master
CC: @stevew817
> Silicon Labs: Add TRNG support

- tools/config/__init__.py
This should allow a user to build correctly in the online complier
> Use absolute paths for bootloader binaries

- targets/TARGET_Silicon_Labs/TARGET_EFM32/TARGET_EFM32PG/device/TARGET_256K/TOOLCHAIN_GCC_ARM/efm32pg1b.ld
- targets/TARGET_Silicon_Labs/TARGET_EFM32/TARGET_EFM32PG12/device/TOOLCHAIN_GCC_ARM/efm32pg12b.ld
- targets/TARGET_Silicon_Labs/TARGET_EFM32/TARGET_EFR32MG1/device/TOOLCHAIN_GCC_ARM/efr32mg1p.ld
- targets/TARGET_Silicon_Labs/TARGET_EFM32/TARGET_EFR32MG12/device/TOOLCHAIN_GCC_ARM/efr32mg12p.ld
- targets/TARGET_Silicon_Labs/TARGET_EFM32/common/mbed_overrides.c
Rebase against master for: #4073
> [Silicon Labs] Bugfix for bootloader on Pearl and Mighty Gecko - Rebase

- platform/mbed_sdk_boot.c
Remove naked attribute that should not be defined for sw init hook, as it
should return.
cc @adamgreen
> mbed sdk boot: fix gcc sw init hook attribute

- drivers/AnalogOut.h
- drivers/BusIn.h
- drivers/BusInOut.h
- drivers/BusOut.h
- drivers/CAN.h
- drivers/DigitalIn.h
- drivers/DigitalInOut.h
- drivers/DigitalOut.h
- drivers/Ethernet.h
- drivers/InterruptManager.h
- drivers/PortInOut.h
- drivers/PortOut.h
- drivers/PwmOut.h
- drivers/Timer.h
- drivers/TimerEvent.h
- features/filesystem/Dir.h
- features/filesystem/FileSystem.h
- features/filesystem/bd/ChainingBlockDevice.h
- features/filesystem/bd/HeapBlockDevice.h
- features/filesystem/bd/SlicingBlockDevice.h
- features/filesystem/fat/FATFileSystem.h
- hal/can_helper.h
- platform/DirHandle.h
- platform/FileHandle.h
- platform/mbed_error.h
- platform/mbed_interface.h
- platform/mbed_mem_trace.h
**READY**
#4425 
branch | PR
doxygen-template | [https://github.com/deepikabhavnani/mbed-os/tree/doxygen-template]
> Doxygen template

- doxyfile_options
- doxygen_options.json
- features/frameworks/utest/utest/utest_case.h
- features/frameworks/utest/utest/utest_default_handlers.h
- features/frameworks/utest/utest/utest_types.h
- hal/gpio_api.h
- hal/storage_abstraction/Driver_Storage.h
- hal/ticker_api.h
- rtos/MemoryPool.h
- rtos/Semaphore.h
- rtos/Thread.h
**NOTE**: This is a combination of PRs: #4435, #4452, #4464, see those for more discussion.
They were merged into this PR as 
a) One PR had some fixes required in the other two
b) Each branch modified the doxyfile_options and doxygen_options.json files, simpler to merge as one.
_______________________________________________________________________________________________________
Documentation changes to Doxygen descriptions for the RTOS (mbed components only, exclude CMSIS/RTX doc), HAL, and features/Framework modules to allow Doxygen to build without errors/warnings. 
https://github.com/ARMmbed/mbed-os/pull/4425
https://github.com/ARMmbed/mbed-os/pull/4434
https://github.com/ARMmbed/mbed-os/pull/4435
https://github.com/ARMmbed/mbed-os/pull/4452 …
> Doxygen combined HAL, RTOS, and features/Framework updates to not produce warnings and errors [DOC Changes Only]

- platform/FileSystemLike.h
- platform/mbed_retarget.cpp
Exactly what is says on the tin. There were quite a few prs that came in at once related to the retarget layer. Unfortunately they conflicted during merge and had to be rebased by a few different people. End result is a few odds and ends that are dead.
cc @sg-
> Clean up dead classes in retarget layer

- targets/TARGET_NORDIC/TARGET_NRF5/TARGET_MCU_NRF52840/sdk/sdk_config.h
- targets/TARGET_NORDIC/TARGET_NRF5/spi_api.c
- targets/targets.json
**NOTE** This is a duplicate PR of #4478. There was a merge conflict after some recent changes were pushed up to master. I used the GitHub fix conflicts shiny button which created a merge commit. I wasn't able to undo it in a clean way, so I moved the rebase to this branch.
_______________________________________________________________________________________________
Rebase against master for: #4088 
Changes from the original commit to targets/TARGET_NORDIC/TARGET_NRF5_SDK13/spi_api.c have been removed as the following commit removed those files as orphans: 
https://github.com/ARMmbed/mbed-os/commit/708dd4703d969bb85043cf09009e7e5607d1f3b1
> NRF52840: enabled SdBlockDevice capability

- platform/mbed_sdk_boot.c
- tools/build_api.py
This was a breakage from the latest cmsis5 boot process unification. However, this PR does not completely fixes it. It fixes for non cortex-m0. We will need to address removal of this functionality for cortex-m0.
Without this patch, ticker test would end up in the hard fault..
With this patch, interrupts are properly running.
Note: if anyone test only this patch with debug profile and with ARM toolchain, there is another problem at least with ticker test. This test invokes ``fflush`` from ISR and we now define MBED_TRAP_ERRORS_ENABLED, thus this ends calling exit() via error() function :/  Not saying this is correct - https://github.com/ARMmbed/mbed-os/blob/master/features/unsupported/tests/mbed/ticker/main.cpp#L7 :-) Just that I did not realized fflush is related to this changeset …
> mbed sdk boot: copy vectors addition

- platform/mbed_retarget.cpp
To maintain backwards compatibility, keep error trapping turned off on mbed 2 builds.
> Disable error trapping for mbed 2 builds

- features/FEATURE_LWIP/lwip-interface/lwip-eth/arch/TARGET_STM/TARGET_STM32F2/stm32f2_eth_conf.c
- features/FEATURE_LWIP/lwip-interface/lwip-eth/arch/TARGET_STM/TARGET_STM32F4/stm32f4_eth_conf.c
- features/FEATURE_LWIP/lwip-interface/lwip-eth/arch/TARGET_STM/TARGET_STM32F7/stm32f7_eth_conf.c
- features/FEATURE_LWIP/lwip-interface/lwip-eth/arch/TARGET_STM/stm32xx_emac.c
Disabled lwip ethernet ipv6 multicast filter for STM boards.
This is correction to https://github.com/ARMmbed/mbed-os/issues/4432
READY
NO
None
None
None
> Disabled lwip ethernet ipv6 multicast filter for STM boards

- TESTS/mbed_hal/rtc_time/main.cpp
Fix errors causing mktime to fail on IAR.
> Fix mktime test

- tools/test/examples/examples.json
> Add mbed-os-example-cellular to release data

- features/FEATURE_LWIP/lwip-interface/lwip-eth/arch/TARGET_STM/stm32xx_emac.c
The function _eth_arch_low_level_input() is meant to pass data into LWIP and to prepare the ethernet buffers to receive more data. If the LWIP heap is empty and the call to pbuf_alloc() in _eth_arch_low_level_input returns null, the ethernet receive buffers are not updated to receive data. Because of this the ethernet RX interrupt will not fire. Since the RX interrupt is the only thing that triggers a call to _eth_arch_low_level_input(), the receive buffers will never get cleared, and the device stops receiving data. 
To prevent this from happening, this patch ensures that the function _eth_arch_low_level_input() clears the receive buffers even if a new pbuf for the data couldn't be allocated.
This issue can be reproduce by running the test …
> STM32 - fix bug where sockets stop receiving data

- tools/export/uvision/__init__.py
Uvision only knows how to do so many of the post-binary hooks that we have in
mbed OS. This PR makes it impossible to export in a way that would create broken
binaries when working in uvision.
**ready**
- /morph export-build
> Filter support with a white list of post-bin hooks in uvision

- tools/export/__init__.py
In the online environment, you can export a project and expect to see a file 
named "GettingStarted.html". This file is not exported offline. This patch
changes the offline behavior to match the online one.
**ready**
- /morph export-build
> Export static files from mbed export

- tools/test/examples/examples_lib.py
Currently when building examples in CI, the following command is run for each TARGET, TOOLCHAIN, and EXAMPLE combination:
```
cd <EXAMPLE> && mbed compile -t <TOOLCHAIN> -m <TARGET> --silent
```
The `--silent` hides valuable debug information when certain errors occur. This PR enables verbose mode to reveal this information. The command will now become:
```
cd <EXAMPLE> && mbed compile -t <TOOLCHAIN> -m <TARGET> -v
```
**READY**
FYI @c1728p9
> Enable verbose builds when running example build tests

- .travis.yml
Preventative maintenance for exporters. The build tools are able to handle 
incorrectly named libraries, but the exporters can't. This PR adds a CI check
in Travis CI that will prevent incorrectly named libraries from coming in.
**ready**
- Just Travis CI is fine
> Check for correct library naming in Travis CI

- targets/TARGET_STM/TARGET_STM32F0/serial_device.c
- targets/TARGET_STM/TARGET_STM32F1/serial_device.c
- targets/TARGET_STM/TARGET_STM32F2/serial_device.c
- targets/TARGET_STM/TARGET_STM32F3/serial_device.c
- targets/TARGET_STM/TARGET_STM32F4/serial_device.c
- targets/TARGET_STM/TARGET_STM32F7/serial_device.c
- targets/TARGET_STM/TARGET_STM32L0/serial_device.c
- targets/TARGET_STM/TARGET_STM32L1/serial_device.c
- targets/TARGET_STM/TARGET_STM32L4/serial_device.c
- targets/TARGET_STM/serial_api.c
This PR is the answer to request in #899 
In case of OVERRUN on a serial interface when using the polling method, the OVERRUN flag is reset so
that next characters can be received.  
**READY**
> STM32: serial: clear Overrun flag if it is set when checking if readable

- features/filesystem/fat/FATFileSystem.cpp
- features/filesystem/fat/FATFileSystem.h
At some point the "mount" parameter for "f_mount" was name "force". This led to a bit of confusion that ended with the default mount function never calling block device init.
This is fine, since the block device can be manually initialized, but a better user experience is where the filesystem initializes the block device for the user.
This is backwards compatible due to the repeatability of the block device init functions.
related issues #4526, https://github.com/ARMmbed/mbed-os/issues/4407
> fatfs: Fixed initialization of block device in mount/unmount functions

- features/frameworks/greentea-client/source/greentea_metrics.cpp
This exposes the reporting of reserved heap and stack to mbed-greentea when the memory stats are enabled.
Note: Reporting of reserved stack is already performed by the thread layer
related pr https://github.com/ARMmbed/greentea/pull/228
cc @bridadan, @studavekar
> greentea: Add reporting of reserved heap

- targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L476xG/device/TOOLCHAIN_ARM_MICRO/stm32l476xx.sct
- targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L476xG/device/TOOLCHAIN_ARM_STD/stm32l476xx.sct
- targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L476xG/device/TOOLCHAIN_GCC_ARM/STM32L476XX.ld
- targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L476xG/device/TOOLCHAIN_IAR/stm32l476xx.icf
Fix to #4553
Following Merge pull request #4063 from LMESTM/17q2_L4_bootloader
the NUCLEO_L476RG binairies could not boot anymore.
The change done in #4063 was derived from work on NUCLEO_L429ZI target
which supports uvisor. The VECTORS defintiion is introduced as part of
uvisor support and requires further changes in ld file which were missing.
As uvisor is not considered yet, we remove VECTORS for now and will
introduce only when needed.
While fixing this issue, I also found out that FLASH size was wrongly defined 
and fixed this in 2nd commit
**READY**
Tested with basic OS2 and OS5 localy
> Fix NUCLEO_L476RG linker scripts

- tools/export/__init__.py
- tools/project.py
Resolves https://github.com/ARMmbed/mbed-cli/issues/504
**ready**
- /morph export-build
> Support app config option for export

- platform/mbed_retarget.cpp
- rtos/Semaphore.cpp
Before RTX 5, the semaphore count limit was UINT16_MAX as a side effect of using a uint16_t ([here](https://github.com/ARMmbed/mbed-os/blob/5fff7e1daeb395aa3d1ecf3f9ec3f4fead3de0c2/rtos/rtx/TARGET_CORTEX_M/rt_TypeDef.h#L139)). After https://github.com/ARMmbed/mbed-os/pull/4294 was merged, the count limit was dropped to the arbitrary value 1024 ([here](https://github.com/ARMmbed/mbed-os/blob/master/rtos/Semaphore.cpp#L30)). Additionally, https://github.com/ARMmbed/mbed-os/pull/4389 added an assert that would halt if the semaphore count exceeded this limit ([here](https://github.com/ARMmbed/mbed-os/blob/master/rtos/rtx5/TARGET_CORTEX_M/rtx_semaphore.c#L285) and [here](https://github.com/ARMmbed/mbed-os/blob/master/platform/mbed_retarget.cpp#L1017)).
This is especially problematic for …
> RTOS: Fix semaphore

- features/FEATURE_LWIP/lwip-interface/lwip_stack.c
resolve wifi example test fail before lwip is init
We find for REALTEK_RTL8195AM target, the wifi example will hang at mbed_lwip_bringup().
> resolve lwip init twice issue

- features/FEATURE_LWIP/lwip-interface/lwipopts.h
lwipopts_conf.h is used by target dependent Ethernet drivers for
configuring various parameters.
By default, Ethernet is enabled and in this case lwipopts_conf.h
will be included.
In case of PPP  being enabled, it is desirable to not pull in any Ethernet
related code.
**READY**
NO
> Check Ethernet before including lwipopts_conf.h

- targets/TARGET_NXP/TARGET_LPC176X/TARGET_UBLOX_C027/ublox_low_level_api.c
- targets/TARGET_NXP/TARGET_LPC176X/TARGET_UBLOX_C027/ublox_low_level_api.h
- targets/TARGET_NXP/TARGET_LPC176X/objects.h
- targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F437xG/TARGET_UBLOX_C030/PeripheralPins.c
- targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F437xG/TARGET_UBLOX_C030/PinNames.h
- targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F437xG/TARGET_UBLOX_C030/onboard_modem_api.c
- targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F437xG/TARGET_UBLOX_C030/system_stm32f4xx.c
- targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F437xG/TARGET_UBLOX_C030/ublox_low_level_api.c
- targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F437xG/TARGET_UBLOX_C030/ublox_low_level_api.h
- targets/targets.json
This change implements the platform support which allows both the mbed-os OnboardModem and the u-blox PPP and AT data drivers to be used with both the u-blox C027 and u-blox C030 platforms.
> Platform support for new CellularInterface in UBLOX_C027 and UBLOX_C030_U201.

- tools/export/uvision/uvision.tmpl
We were seeing extraordinarily long build times in Uvision 5.24. Sometimes > than 20 minutes for blinky. @bridadan reported 10 minute builds during export-build tests, even on the CI machines. I've found that enabling Uvision's "browse information," which is essentially their indexer, is responsible for this. With this option turned off, I saw a **19** minute reduction in build time when compiling blinky for NUCLEO_F439ZI.
As a note, I realize this is an important feature for the IDE. If a user tries to use it when the option is turned off, Uvision provides instructions for turning it on. 
**READY**
In uvision, go to: options for target > output> browse information. Try compiling with it on/off. 
@theotherjimmy
> Turn off "browse information" in Uvision template

- tools/export/gnuarmeclipse/.cproject.tmpl
Notes:
* I have accepted the Contributor Agreement on Tue 25 Oct 2016.
There is a minor issue with the Eclipse exporter which causes a warning of an unresolved include of `mbed_config.h`. This PR solves it by adding the project directory path to the include. Actually, all includes have the project directory path, just not this one.
**READY**
NO
> Fix unresolved include of mbed_config.h in Eclipse

- targets/TARGET_STM/TARGET_STM32F0/spi_device.h
- targets/TARGET_STM/TARGET_STM32F1/spi_device.h
- targets/TARGET_STM/TARGET_STM32F2/spi_device.h
- targets/TARGET_STM/TARGET_STM32F3/spi_device.h
- targets/TARGET_STM/TARGET_STM32F4/spi_device.h
- targets/TARGET_STM/TARGET_STM32F7/spi_device.h
- targets/TARGET_STM/TARGET_STM32L0/spi_device.h
- targets/TARGET_STM/TARGET_STM32L1/spi_device.h
- targets/TARGET_STM/TARGET_STM32L4/spi_device.h
- targets/TARGET_STM/stm_spi_api.c
This PR contains a change in SPI driver to improve performances by accessing to registers directly (using LL layer in STM32 SDK, which provides inline functions to access it.
See  #4246 
Resolves #3445 
**READY**
Waiting for 2 other PRS:
There were 2 pending dependencies of upgrading STM32 SDK for 
F4 (#4299) => MERGED 
F2 (#4402) => MERGED
This SDK updates will include the LL API that is used here.
I will rebase when this is done - but this PR can be used for test by anyone interested in it, and review can happen in parallel.
CI tests passed ok 
+-------------------+---------------+---------------+--------+--------------------+-------------+
| target            | platform_name | test suite    | result | elapsed_time (sec) | copy_method | …
> Stm32 spi : use LL API to improve performances

- tools/build.py
- tools/get_config.py
- tools/make.py
- tools/options.py
- tools/project.py
- tools/targets/__init__.py
- tools/test.py
- tools/test/targets/target_test.py
Enhancement to provide simple method of adding or overriding target definitions without modifying mbed-os library.
If the file extra_targets.json exists in the working directory load it over the top of the built in targets.json for defining new and overriding built in mbed target definitions.
This is currently just a suggestion for replacing functionality removed in PR #2691 below.
Not ready for merging, open for discussion of direction before considering writing docs/tests
branch | PR
no_custom_targets | [Removed custom targets from config system]( https://github.com/ARMmbed/mbed-os/pull/2691 )
> Add extra_targets.json support to build tools

- targets/TARGET_STM/TARGET_STM32F0/TARGET_NUCLEO_F070RB/device/system_stm32f0xx.c
Nucleo-F070RB have a wrong divisor when it initial the clock.
**READY**
**NO**
Run display message to UART
Fixes #4361
> Nucleo-F070RB It doesn't work when use internal clock

- targets/TARGET_STM/TARGET_STM32L0/TARGET_DISCO_L072CZ_LRWAN1/PinNames.h
Pull request to fix issue #4404
> DISCO_L072CZ_LRWAN1: PC_13 definition missing in PinNames.h fix

- tools/toolchains/__init__.py
Graph of the first commit compared to master in the next comment.
The remaining commits allow us to _correctly_ elide much processing. In particular, if we delay scanning of features until we try access their respective resource objects, we can avoid scanning some resources by never trying to access their resource objects. Turns out that this optimization saves us ~1/2 of the scan resources time!
> Improve directory scanning performance

- drivers/UARTSerial.cpp
- drivers/UARTSerial.h
Fixes issue #4537. SerialBase and UARTSerial happened to have same names
for the mutex locking that confused the system of holding a mutex in interrupt context.
UARTSerial has to change so as to provide empty implementations for lock() and unlock()
becuase it uses SerialBase from interrupt context only or from its own critical section,
so no extra locks required.
Private locks for UARTSerial itself are renamed to api_lock() and api_unlock().
**READY**
Doesn't change behaviour.
NO
> Avoid lock collision b/w SerialBase & UARTSerial

- tools/export/iar/iar_definitions.json
Add missing definitions to support IAR for this platform.
Fix Issue #4535 
**READY**
NO
> NUCLEO_F767ZI: Add missing IAR definitions

- features/unsupported/USBDevice/USBDevice/TARGET_STM/TARGET_STM32L0/TARGET_DISCO_L072CZ_LRWAN1/USBHAL_STM32L072CZ.h
- features/unsupported/USBDevice/USBDevice/TARGET_STM/TARGET_STM32L0/TARGET_DISCO_L072CZ_LRWAN1/USBHAL_STM_TARGET.h
- targets/TARGET_STM/TARGET_STM32L0/TARGET_DISCO_L072CZ_LRWAN1/device/system_stm32l0xx.c
- tools/build_travis.py
This pull request enable the USB Device on this platform. Clock setting has been updated to enable the HSI48 clock of the device.
**READY**
USB_1 and USB_4 tests are OK.
NO
> DISCO_L072CZ_LRWAN1: Add support of USB Device

- targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_conf.h
HSE timeout value is set to 100ms
This is aligned with official ST cube since v1.11.0
This fix #1096 
READY
> STM32F4 set HSE timeout value to 100ms

- tools/export/iar/__init__.py
Some of this stuff began to bother me, so I fixed it.
> Fix style issues in IAR exporter

- cmsis/TOOLCHAIN_IAR/cmain.S
This fixes #4602 issue, mbed_main should be invoked right before the real main
Tested on nucleo l476rg, using mbed_a21 test
Sorry for the formatting, my terminal was not set properly :)
before this patch:
```
{{timeout;20}}
{{host_test_name;default_auto}}
{{description;Call function mbed_main before main}}
{{test_id;MBED_A21}}
{{start}}
MBED: main() starts now!
{{failure}}
{{end}}
```
after this patch:
```
call before main()
{{timeout;20}}
{{host_test_name;default_auto}}
{{description;Call function mbed_main before main}}
{{test_id;MBED_A21}}
{{start}}
MBED: main() starts now!
{{success}}
{{end}}
```
cc @jeromecoutant @c1728p9
> cmain IAR: add mbed main

- features/filesystem/bd/HeapBlockDevice.cpp
- features/filesystem/bd/MBRBlockDevice.cpp
Looks like an init call was missing to the MBRBlockDevice's child block device. This went unnoticed during testing since not all block devices need an init call to function.
I also added an asert on init to the Heap block device, which will at least find these issues if we run filesystem tests.
related issue https://github.com/ARMmbed/mbed-os/issues/4526
cc @netanelgonen, @theotherjimmy
> bd: Fix missing init in MBRBlockDevice

- targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L475xG/TARGET_DISCO_L475VG_IOT01A/system_stm32l4xx.c
- targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L475xG/device/TOOLCHAIN_ARM_MICRO/stm32l475xx.sct
- targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L475xG/device/TOOLCHAIN_ARM_STD/stm32l475xx.sct
- targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L475xG/device/TOOLCHAIN_GCC_ARM/STM32L475XX.ld
- targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L475xG/device/TOOLCHAIN_IAR/stm32l475xx.icf
- targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L475xG/device/nvic_addr.h
This PR updates all toolchains startup files after CMSIS5 big update. This is a copy/paste of the code present in the DISCO_L476VG platform (similar device).
Before this patch the program does not even start.
After this patch:
```
+--------+---------------------------+-----------+-------------+---------------------------------------+--------------------+---------------+-------+
| Result | Target                    | Toolchain | Test ID     | Test Description                      | Elapsed Time (sec) | Timeout (sec) | Loops |
+--------+---------------------------+-----------+-------------+---------------------------------------+--------------------+---------------+-------+
| OK     | DISCO_L475VG_IOT01A[F549] | ARM       | DTCT_1      | Simple detect test                    |        0.47 …
```
> DISCO_L475VG_IOT01A: Fix startup files for cmsis5

- rtos/rtx5/TARGET_CORTEX_M/rtx_mutex.c
The prev-pointer of the running threads mutex list was not set when
multiple mutexes are acquired at a time. This leads to a corrupted list
if the mutexes are not freed in reversed order.
Original commit for CMSIS_5:
commit 729f6ab08540342b7de7612fac103539d5b2f168
Author: Jonatan Antoni <jonatan.antoni@arm.com>
Date:   Wed Apr 19 15:38:43 2017 +0200
Fix ported from CMSIS_5 repo to address #4630 
**READY**
Close #4630 
It's a point fix brought over from CMSIS repo, but we should still think about having some process to update CMSIS in regular intervals (eg each CMSIS patch release?)
@0xc0170 @c1728p9
> RTX: Fixed RTXv5 mutex owner list handling.

- tools/test/examples/examples.json
- tools/test/examples/pr.tmpl
- tools/test/examples/update.py
Previously if updating a branch in the ARMmbed version of an example
repo, the branch would be created initially from master. This update
allows the new branch to be created from any pre-existing branch.
This update also moves the branch / fork / tag configuration data to the
json config file. It thus simplifies the command line.
-b on its own now indicates use the branch information in the config
-f on its own now indicates use the fork information in the config
> Update branching option to branch from another branch.

- features/filesystem/fat/FATFileSystem.cpp
At some point this was replaced by `fat_error_remap`. `fat_filesystem_set_errno` is unreferenced by any other function and can be removed.
> fatfs: Remove unused fat_filesystem_set_errno function

- events/equeue/equeue_mbed.cpp
- events/equeue/equeue_platform.h
This provides the correct binary semaphore behaviour that was expected by the equeue layer, removes concerns around semaphore overflow, and reduces the number of spurious wakeups which may save a bit of power.
This also fixes some issues we were seeing around the RTX 5 changes to semaphore behaviour.
related issue https://github.com/ARMmbed/mbed-os/pull/4500
cc @pan-, @tomasfrisbergublox, @hesolium
> events: Adopt osEventFlags from RTX 5

- targets/TARGET_STM/TARGET_STM32L1/TARGET_XDOT_L151CC/xdot_low_power.c
Enable HSI after waking from stop mode so ADC is functional
**READY**
> XDOT_L151CC: enable HSI after waking from stop mode so ADC functions

- rtos/MemoryPool.h
- rtos/Queue.h
Destructors of `MemoryPool` and `Queue` were not defined leaving a resource leak after destruction of any instance of this kind of objects. 
This PR adds a destructor for these types which correctly release the resources. As a side effect it also fix the default destructor of the `Mail` class.
**READY**
NO
> rtos: Fix MemoryPool and Queue destructor

- targets/TARGET_STM/us_ticker_32b.c
This fixes setting the new event for us ticker. As it was, the interrupt would
fire 2x. It should either fire ISR immediately or set it in the future.
Tested with ODIN target and a test case for setting events in the past that will come as a separate PR.
As I understood the code, we either generate event and enable it OR set new compare value and enable it. This fixes the failures we have seen in #4628 and possibly in our CI for basic timer tests.
before this patch:
```
+-----------------------+-------------------+----------------------------+--------+--------------------+-------------+
| target                | platform_name     | test suite                 | result | elapsed_time (sec) | copy_method |
+-----------------------+-------------------+----------------------------+--------+---- …
```
> STM32: fix us ticker set event timestamp double ISR possibility

- targets/TARGET_STM/TARGET_STM32L0/analogin_api.c
With default sampling time, the MBED2 and CI test shield tests would fail
because the stabilization slope of ADC is relatively slow.
ERROR (out:0.8000) - (in:0.7407) = (0.0593)
ERROR (out:0.9000) - (in:0.8354) = (0.0646)
ERROR (out:1.0000) - (in:0.9289) = (0.0711)
This is related to the 10kOhms resistors used to connect Ain to
Aout mounted on the CI shileds, and internal capacitance of L0 targets.
If connecting Ain and Aout with wires, bypassing the resistors, the test
is passed. So we're increasing the sampling time to let the automated
ci shiled tests PASS.
OK    (out:0.8000) - (in:0.7863) = (0.0137)
OK    (out:0.9000) - (in:0.8869) = (0.0131)
OK    (out:1.0000) - (in:0.9844) = (0.0156)
Notes:
* Pull requests will not be accepted until the submitter has agreed to the [contributer …
> Increase L0 ADC sample time

- targets/TARGET_STM/TARGET_STM32L0/flash_api.c
The initial comments were copied from L4 implementation but do not apply
to L0 targets where 1 sector is composed of a constant number of pages.
> Correct comments in flash api for STM32 L0 targets

- platform/mbed_retarget.cpp
only for mbed 2 needed.
This is as it used to be, reverting the removal. uARM does not have any hook
that we could use for mbed sdk init and copy nvic, therefore _open is used that
should be sufficient, but not ideal.
For more information, visit https://github.com/ARMmbed/mbed-os/pull/2160/files#r76563844.
cc @c1728p9 @bulislaw @jeromecoutant @LMESTM
> retarget: fix microlib for mbed 2

- targets/TARGET_ONSEMI/TARGET_NCS36510/ncs36510_us_ticker_api.c
Do not ticker read in ISR, use reminder to schedule the next interrupt, this should make ticker much faster.
read - disable Timer0 while reading it, if ISR is pending just reread the time again via read() function
These 2 improvements should decrease time spent when reading/scheduling ticker
events.
Tested with ticker test for GCC ARM and ARM, multiple times. Prior this patch , the times were at the limit thus ticker would fail seldom (quite often). With this patch, the ticker reading is much faster (not only reading the t ime, but also ISR as it was reading previously thus was slow) and we are for ticker in the middle of the range <min-max> time.
@studavekar @c1728p9 @geky Please review, can cherry pick this to host time improvements, should fix the failure there and make it green I hope …
> ncs36510: us ticker improvements

- features/netsocket/cellular/generic_modem_driver/TESTS/unit_tests/default/main.cpp
If a test is empty, it leads to undef. Therefore if a test requires additional
details, it should print an error [NOT SUPPORTED].
This will require nighlty to verify.
This is the fix for the patch came from #4446
@hasnainvirk
> Cellular: not-supported error if MODEM_ON_BOARD not defined

- tools/export/iar/iar_definitions.json
This definition requires IAR 7.80.2 and higher.
It will be readded once we all update to the latest IAR 7.80 patch release. For
future, please any new target should state what are the requirements on tools to
avoid this suprises. + run export build to verify this requirement
Tested locally, now with this patch - `project.py: error: DISCO_F413ZH not supported by iar`
cc @adbridge @studavekar 
@adustm @bcostm @LMESTM @jeromecoutant Just that you know, I'll send another patch reenabling this that will get in once we all update
> IAR: remove stm32f413 from definitions

- tools/toolchains/__init__.py
This fixes a problem when the path to include files have spaces.
See https://github.com/ARMmbed/mbed-os-example-uvisor/issues/31 for an
example of this problem.
Signed-off-by: Mo Chen <mo.chen@arm.com>
> Put quotes around include files

- features/mbedtls/targets/TARGET_STM/TARGET_STM32L4/TARGET_NUCLEO_L486RG/mbedtls_device.h
- features/mbedtls/targets/TARGET_STM/aes_alt.c
- targets/targets.json
Add hw acceleration for mbedTLS/aes on NUCLEO_L486RG
Please be aware that this device does not support 192bit key size.
The aes selftest and gcm selftest shall be modified not to run this key size. As it is located in the official mbedtls stack, I did not touch it.
is #3962
~~DO NOT MERGE~~
Run aes seltest from TESTS/mbedtls/selftest/main.cpp
```
+-------------------+---------------+------------------------+-----------------------------+--------+--------+--------+--------------------+
| target            | platform_name | test suite             | test case                   | passed | failed | result | elapsed_time (sec) |
+-------------------+---------------+------------------------+-----------------------------+--------+--------+--------+--------------------+
| NUCLEO_L486RG-IAR | …
```
> STM32L486RG/mbedtls: add aes hw acceleration

- targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F767xI/device/TOOLCHAIN_ARM_MICRO/startup_stm32f767xx.S
- targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F767xI/device/TOOLCHAIN_ARM_STD/startup_stm32f767xx.S
- targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F767xI/device/TOOLCHAIN_GCC_ARM/startup_stm32f767xx.S
> Add the correct startup s file in TARGET_STM32F767

- tools/targets/lint.py
The linting script for targets.json (tools/targets/lint.py) is a utility for
avoiding common pit-falls of defining targets, and detecting style 
inconsistencies between targets. 
A target's inheritance must look like one of these:
```
MCU -> Board
MCU -> Module -> Board
Family -> MCU -> Board
Family -> MCU -> Module -> Board
Family -> SubFamily -> MCU -> Board
Family -> SubFamily -> MCU -> Module -> Board
```
For each of these target roles, some rules are in place:
1. For Family, MCU and SubFamily, the following keys are allowed
- `core`
- `extra_labels`
- `features`
- `bootloader_supported`
- `device_name`
- `post_binary_hook`
- `default_tool chain`
- `public`
- `config`
- `target_overrides`
2. MCU's are required to have, and Families and SubFamilies may have:
- `release_versions`
- …
> Add script to lint targets.json

- tools/build_api.py
Notes:
Done it with the online ide
This is a simple fix, it seems last time it was changed the verbose option went missing, and it masks others
READY (trivial fix for the build system)
NO
branch | PR
> added the missing verbose=verbose to printout the command line correctly at build_api.py

- tools/export/gnuarmeclipse/.cproject.tmpl
Fixes a bug where quoting gets stripped by the shell used in the makefile
and another bug where the lack of escaping would cause parser errors in
eclipse.
Resolves #4622
> Double escape defines in gnuarmeclipse export

- drivers/SPI.cpp
- drivers/SPI.h
1. Private _acquire() function is added to avoid multiple locking/unlocking
2. format and frequenct functions updated to use appropriate function calls
instead of a aquire()
#4626 
**READY**
> _acquire() function added & removed duplication in format/freq calls

- tools/get_config.py
This annoyed me! I fixed it!
When running `mbed compile --config`, the config options would be printed unsorted. This PR makes all the config options sorted!
Before:
```
C:\Users\bridan01\Documents\dev\m_mbed\mbed>mbed compile --config
Scan: .
Scan: FEATURE_LWIP
Scan: FEATURE_ETHERNET_HOST
Scan: FEATURE_LOWPAN_BORDER_ROUTER
Scan: FEATURE_LOWPAN_HOST
Scan: FEATURE_LOWPAN_ROUTER
Scan: FEATURE_NANOSTACK
Scan: FEATURE_NANOSTACK_FULL
Scan: FEATURE_THREAD_BORDER_ROUTER
Scan: FEATURE_THREAD_END_DEVICE
Scan: FEATURE_THREAD_ROUTER
Configuration parameters
------------------------
lwip.enable-ppp-trace = 0 (macro name: "MBED_CONF_LWIP_ENABLE_PPP_TRACE")
lwip.addr-timeout = 5 (macro name: …
```
> Sort the config parameters before printing them

- drivers/FlashIAP.cpp
- hal/flash_api.h
- hal/mbed_flash_api.c
On some platforms, the in-application memory is not memory mapped
and therefore cannot be accessed using memcpy.
The flash_read function added to flash_api.h (with a weak
implementation using memcpy in mbed_flash_api.c) can be used for
reading data from areas that are not memory mapped.
> FlashIAP: Add explicit read function to flash_api.h

- targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F429xI/device/flash_api.c
- targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F429xI/device/flash_data.h
- targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F439xI/device/flash_api.c
- targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F439xI/device/flash_data.h
- targets/TARGET_STM/TARGET_STM32F4/TARGET_UBLOX_EVK_ODIN_W2/device/flash_data.h
- targets/TARGET_STM/TARGET_STM32F4/common_objects.h
- targets/targets.json
Rebase against master for: #4066 
> Replace CMSIS flash driver by SDK flash driver

- features/mbedtls/importer/Makefile
A new target is added to deploy mbedtls tests along with source code in mbed-os. Separate target is added to prevent changes in current deployment process. For some time it would only be used in staging CI to observer test stability. Also it gives the ability to only import tests for testing mbedtls with mbed-os i.e. only deploy tests for testing purpose.
**READY**
YES | NO
Does not depend but will be used with mbedtls PR https://github.com/ARMmbed/mbedtls/pull/930
branch | PR
- Check out mbedtls inside ```mbed-os/features/mbedtls/importer/TARGET_IGNORE/``` …
> Add new target in mbedtls importer Makefile for mbedtls tests

- targets/TARGET_STM/TARGET_STM32F0/TARGET_NUCLEO_F070RB/device/TOOLCHAIN_GCC_ARM/startup_stm32f070xb.S
This reduces the number of loads inside of the .data copy loop by 3 by using one more register. It should work on any STM32 with at least 5 general-purpose registers. If only 4 are available, then 1 load could still be removed from the original implementation.
READY
NO
Run any program with a non-empty `.data` section (globals, for instance).
> Improve the startup code on the STM32F070

- features/filesystem/fat/FATFileSystem.cpp
In the Chan implementation of the fatfs, paths can be prefixed with a drive number (ie "2:/hi/hello/filehere.txt" for drive 2). This is used internally to lookup the storage that is in use. Full support of multiple fatfs simultaneously requires path prefixes being applied for every function that takes a path.
Note: This is only an issue when multiple fatfss are used simultaneously. Repeated use of a single fatfs instance (even with different storages) do not show this issue.
Note: this is only required filesystems after the first mounted filesystem. The first filesystem has no penalty.
related issue https://github.com/ARMmbed/mbed-os/issues/4526
cc @netanelgonen
> fatfs: Add full support for multiple fs volume prefixes

- targets/TARGET_NORDIC/TARGET_NRF5/TARGET_MCU_NRF52832/TARGET_UBLOX_EVK_NINA_B1/PinNames.h
Set LED4 the same as LED3 to get tests-mbedmicro-rtos-mbed-timer to pass for UBLOX_EVK_NINA_B1
This is part of getting the target pass mbed Enabled tests.
If not fixed the test will fail with:
[1498813581.77][CONN][RXD] mbed assertation failed: obj->pin != (PinName)NC, file: C:\git\ARMmbed\mCMSIS-RTOS error: User Timer Callback Queue overflow (status: 0x3, task ID: 0x0, timer ID: 0x200053EC)
READY
NO
None
None
N/A
N/A
> Fix LED4 for UBLOX_EVK_NINA_B1

- tools/toolchains/__init__.py
inc paths might be a list or might not be (just single string). If they don't, we are ending up with non valid include paths (one letter include paths).
This as result would not compile. 
As inc_dirs might be just `D:/SomePath`, extend this would lead to producing [`D`, `:`, `S`..........] thus we were not able to compile with tools/build.py for instance. This is an example I was seeing
`[DEBUG] INC DIRS: ['C', ':', '\\', 'C', 'o', 'd', 'e', '\\', 'm', 'b', 'e', 'd', '-', 'o', 's', '\\', 'B', 'U', 'I', 'L', 'D', '\\', 'm', 'b', 'e', 'd', '\\', '.', 't', 'e', 'm', 'p', '\\', 'T', 'A', 'R', 'G', 'E', 'T', '_', 'N', 'U', 'C', 'L', 'E', 'O', '_', 'F', '4', '1', '1', 'R', 'E', '\\', 'T', 'O', 'O', 'L', 'C', 'H', 'A', 'I', 'N', '_', 'I', 'A', 'R']`
@jeromecoutant This should fix the issue you …
> tools: fix toolchain extend inc paths

- targets/TARGET_Realtek/TARGET_AMEBA/TARGET_RTL8195A/device/rtl8195a.h
By removing these headfile includes shall it prevent confusion
> Remove unused header files includes for REALTEK_RTL8195AM

- targets/TARGET_STM/TARGET_STM32F0/serial_device.c
- targets/TARGET_STM/TARGET_STM32F3/serial_device.c
- targets/TARGET_STM/TARGET_STM32F7/serial_device.c
- targets/TARGET_STM/TARGET_STM32L0/serial_device.c
- targets/TARGET_STM/TARGET_STM32L4/serial_device.c
Depending on families, different HAL macros are defined to check the
state of serial interrupts. In several cases, we can find only 1 macro:
__HAL_UART_GET_IT_SOURCE
Checks whether the specified UART interrupt has occurred or not
But in F0, F3, F7, L0, L4 there are 2 different macros
__HAL_UART_GET_IT
Checks whether the specified UART interrupt has occurred or not
__HAL_UART_GET_IT_SOURCE
Checks whether the specified UART interrupt source is enabled.
In the later case, __HAL_UART_GET_IT_SOURCE was being used so far,
but actually needs to be replaced by __HAL_UART_GET_IT. Using the right
macro, we also check the proper flags accordingly.
This PR solves issue #3452 
**READY**
Tested with simple test that produce an overrun condition, and making sure the board won't freeze.
Test code below, …
> STM32: serial: use proper macro to check  interrupt

- targets/TARGET_STM/TARGET_STM32F4/analogin_api.c
To get a valid VBAT measurement on F4 targets, it is required to increase
the sampling time to its maximum value.
This PR solves the issue reported here #4326
**READY**
Tested on NUCLEO_F446RE target with VBAT measurements and non-regression OK
+-----------------------+---------------+-----------------------+--------+--------------------+-------------+
| target                | platform_name | test suite            | result | elapsed_time (sec) | copy_method |
+-----------------------+---------------+-----------------------+--------+--------------------+-------------+
| NUCLEO_F446RE-GCC_ARM | NUCLEO_F446RE | tests-api-analogin    | OK     | 12.65              | shell       |
| NUCLEO_F446RE-GCC_ARM | NUCLEO_F446RE | tests-api-analogout   | OK     | 11.8               | shell       |
| …
> STM32: F4: Increase ADC sampling time for VBAT

- features/FEATURE_LWIP/lwip-interface/lwipopts.h
- features/FEATURE_LWIP/lwip-interface/mbed_lib.json
PPP is running close to the edge of its default thread stack size of 512 bytes.  When it experiences an FCS error on the incoming data (caused by character loss when the incoming serial rate is too high for it to process in time) it performs some additional work which overruns the thread's stack, hitting the OS "stack underflow" check.
Increasing the  PPP stack size to 768 bytes resolves this problem.
Note: this change already discussed at some length with @kjbracey-arm.
Run `PPPCellularInterface` with the UART serial port running at 460800 or higher and wait for the OS stack check to be hit.
> Increase default PPP stack size from 512 bytes to 768 bytes.

- TESTS/mbed_hal/flash/functional_tests/main.cpp
- platform/mbed_toolchain.h
ARMCC seemed to be inlining time_cpu_cycles() but with a different number of clock cycles in the loop, GCC worked fine.
**READY**
NO
#4640
> Fix timing issues found in "Flash - clock and cache test"

- features/filesystem/fat/FATFileSystem.cpp
Unlike the other disk_ioctl options, GET_SECTOR_SIZE is interpreted as a 16-bit WORD, instead of a 32-bit DWORD. This caused an unaligned access error on M0 platforms.
disk_ioctl documentation:
http://elm-chan.org/fsw/ff/doc/dioctl.html
related issue https://github.com/ARMmbed/mbed-os/issues/4649
cc @LMESTM
> fatfs: Fix unaligned access in disk_ioctl

- features/nanostack/FEATURE_NANOSTACK/mbed-mesh-api/source/LoWPANNDInterface.cpp
Thread already changed interface connection timeout to wait forever, 
so the lowpan ND needs to change too.
Device needs to wait for connectivity:
-routers will create new network and get local connectivity
-end device will get connectivity once attached to existing network
-devices without network settings gets connectivity once
commissioned and attached to network
> [ONME-3089] - Adjust lowpan ND interface connect timeout

- targets/TARGET_NORDIC/TARGET_NRF5/i2c_api.c
- targets/TARGET_NORDIC/TARGET_NRF5/spi_api.c
Add Support for sharing resources between SPI and TWI instancess.
This fix the issue #4357: NRF52 doesn't support simultaneous use of I2C and SPI.
Now this resources are reserved by each of hal driver using nRF5 SDK's serial-box mechanism.
**READY**
>  Fix the issue #4357: NRF52 doesn't support simultaneous use of I2C and SPI.

- tools/export/__init__.py
- tools/export/cmsis/__init__.py
- tools/export/embitz/__init__.py
- tools/export/exporters.py
- tools/export/gnuarmeclipse/__init__.py
- tools/export/iar/__init__.py
- tools/export/makefile/__init__.py
- tools/export/qtcreator/__init__.py
- tools/export/uvision/__init__.py
- tools/project.py
Resolves #4709
Also changes the API of the exporters to be more flexible WRT changes in
TARGET_MAP. The old API would pre-compute a supported list at import time.
This new API includes a class method for computing support for one target
or all targets. This might improve performace for single exports, as only
the current combination of support is checked instead of the whole matrix.
> Parse and use custom targets in exporters

- TESTS/mbedmicro-rtos-mbed/threads/main.cpp
- rtos/Thread.cpp
- rtos/Thread.h
During the CMSIS/RTX update, it became obvious that our test coverage is quite poor. This PR tries to extend tests to all Thread functions. It also fixes issues found during tests development.
**READY**
> Extend tests for RTOS Thread class

- targets/TARGET_STM/can_api.c
…y at startup regardless of the value set in the constructor. Issue #3863
Fixing the issue described in #3863 
**READY**
NO
> STM32: Fix the CAN initializing to the wrong frequency

- targets/TARGET_STM/gpio_irq_api.c
When disabling GPIO irq, also the falling / rising edge settings need
to be reset (EXTI_RTSR and EXTI_FTSR registers).
See #2959:
If not reset, the same EXTI line can be later enabled again with a wrong
Rising / Falling configuration. This was especially seen and reported in 
ci-test tests-api-interruptin on NUCLEO_F446RE target where DIO2=PA_10 and
DIO6=PB_10 were successively tested: as they are sharing the same EXTI_LINE
(EXTI_10), this resulted in calling the irq_handler with wrong
IRQ_FALL/IRQ_RAISE parameter and donothing being called in loop
Also after correctly disabling, another commit handles the save restore part.
Finally en error is added in case of spurious interrupt to make it easily detectable.
**READY**
NUCLEO_F446RE ci-test-shield passed ok …
> Correctly enable / disable InterruptIn Edges detection

- TESTS/mbedmicro-rtos-mbed/semaphore/main.cpp
- rtos/Semaphore.h
Add more unit style tests for Semaphore class and rework existing test.
**READY**
CC: @0xc0170
> Test: RTOS: Semaphore: Rework tests

- targets/TARGET_STM/mbed_rtx.h
Arranged INITIAL_SP entries per RAM size and removed duplicated targets. More readable now I guess...
**READY**
NO
> STM: cleanup mbed_rtx.h file

- targets/targets.json
Set copy_method and reset_method in targets.json which is needed for
htrun.
Enable greentea testing on CM3DS_MPS2 target.
Set copy_method and reset_method in targets.json which is needed for htrun.
NO
Support reset and flash for ARM MPS2 board.: https://github.com/ARMmbed/htrun/pull/160
branch | PR
> Enable greentea testing on CM3DS_MPS2 target

- platform/mbed_toolchain.h
The subtlety of where to mark functions as weak created an issue for at least one user, so added a warning in the documentation.
cc @marcuschangarm
> Toolchain: Add a note about weak functions and header files

- targets/TARGET_STM/TARGET_STM32L0/TARGET_DISCO_L053C8/PeripheralPins.c
- targets/TARGET_STM/TARGET_STM32L0/TARGET_NUCLEO_L053R8/PeripheralPins.c
- Type: Bug
- Related issue: https://developer.mbed.org/questions/78531/DAC-error-Unknown-DAC-channel/
- Priority: Blocker
---------------------------------------------------------------
**Target**
DISCO_L053C8
NUCLEO_L053R8
**Toolchain:**
ALL
**mbed-os sha:**
efc5c47e55b8a30c2acb366808975411e4bae7fd
Resolves #4730 
@bcostm @LMESTM Could you review?
> Correct DAC pin assignment

- features/FEATURE_BLE/ble/GattCharacteristic.h
- features/FEATURE_BLE/ble/services/HeartRateService.h
* Contributer agreement: [Signed](https://developer.mbed.org/users/Nodraak/)
* Description: Fix issue #4661
* Status: Ready
> [BLE/HRM] Fix #4661

- drivers/UARTSerial.cpp
- drivers/UARTSerial.h
Add a `set_baud()` method to `UARTSerial()`, simply handing it on to `SerialBase:baud()`.  See #4609 for reasons why this is necessary.
With this in place the `CellularInterface` can instantiate the file handle it requires with `UARTSerial()` running at a baud rate of 115200 (which all modems can be relied upon to auto-baud at).  Then, once the modem is up and running, it can send the modem an `AT+IPR` command giving a higher baud rate that the modem supports but would not be able to auto-baud at (e.g. 460800).  This way we can get nice fast connections.
This has been tested on the u-blox C030 board with a Sara-U201 modem, eventually running at 460800 bits/s.
> Add set_baud() method to UARTSerial().

- features/FEATURE_COMMON_PAL/mbed-trace/.gitignore
- features/FEATURE_COMMON_PAL/mbed-trace/CMakeLists.txt
- features/FEATURE_COMMON_PAL/mbed-trace/mbed-trace/mbed_trace.h
- features/FEATURE_COMMON_PAL/mbed-trace/module.json
- features/FEATURE_COMMON_PAL/mbed-trace/source/mbed_trace.c
- features/FEATURE_COMMON_PAL/mbed-trace/test/Test.cpp
This commit fixes https://github.com/ARMmbed/mbed-trace/issues/70
**READY**
NO
https://github.com/ARMmbed/mbed-trace/pull/71
> Fix inconsistent mbed-trace dummy defines and original function declarations

- targets/TARGET_Realtek/TARGET_AMEBA/flash_api.c
- targets/TARGET_Realtek/TARGET_AMEBA/flash_ext.c
- targets/TARGET_Realtek/TARGET_AMEBA/flash_ext.h
The FlashIAP is supposed to have access to the full application
memory, so the address scope has been changed to encompass
the entire external flash.
The address translation has also been changed to reflect the memory
layout in the documentation:
Realtek Ameba1 Memory Layout: 5.1 Flash Memory
Needs API change from https://github.com/ARMmbed/mbed-os/pull/4720 to work.
Tested using GCC and ARM.
```
+---------------------------+-------------------+-----------------------------+---------------------------+--------+--------+--------+--------------------+
| target                    | platform_name     | test suite                  | test case                 | passed | failed | result | elapsed_time (sec) |
+---------------------------+-------------------+-----------------------------+--------- …
```
> REALTEK_RTL8195AM: FlashIAP read and address scope

- targets/TARGET_STM/i2c_api.c
Some I2C devices require specific zero length read/write sequences which
the HAL_I2C_IsDeviceReady() redirect interferes with.  After Removing
these redirects, it was confirmed that zero length reads and writes
would both still work correctly for detecting presence/absence of an
I2C device on a bus.
READY
NO
Run I2C CI tests on all STM32 targets to confirm no regressions
Build an STM32 based target image with an instantiated I2C bus and use an oscilloscope or I2C bus analyzer to confirm that both an I2C read without data and an I2C write without data can be generated, and the expected results returned, using code such as:
`#include <mbed.h>`
...
`I2C testI2c(PA_10, PA_9);`
`printf("Write to 0x54 = %d\r\n", testI2c.write(0x54, 0, 0)); // Non-existent I2C device (expect 1 result)` …
> STM32: Remove i2c_read() and i2c_write() redirects to HAL_I2C_IsDeviceReady()

- rtos/mbed_boot.c
- rtos/rtx5/TARGET_CORTEX_M/rtx_lib.c
- rtos/rtx5/mbed_rtx_conf.h
ARMC requires variable number of dynamic mutexes. We use combination of RTX mutex pool and heap allocation to achieve that.
**READY**
CC: @0x6d61726b @c1728p9 
Closes #4688
> Boot: Make ARMC library mutexes dynamic

- targets/TARGET_STM/TARGET_STM32F0/serial_device.c
- targets/TARGET_STM/TARGET_STM32F1/serial_device.c
- targets/TARGET_STM/TARGET_STM32F2/serial_device.c
- targets/TARGET_STM/TARGET_STM32F3/serial_device.c
- targets/TARGET_STM/TARGET_STM32F4/serial_device.c
- targets/TARGET_STM/TARGET_STM32F7/serial_device.c
- targets/TARGET_STM/TARGET_STM32L0/serial_device.c
- targets/TARGET_STM/TARGET_STM32L1/serial_device.c
- targets/TARGET_STM/TARGET_STM32L4/serial_device.c
There was a hidden  bug in the uart irq handler that was seen when reaching high baud rates as described in details in #4722 .  The RXE flags shouldn't be erased in the uart_irq as erasing the flag is actually done when reading the data in the data register. At low baudrate, this has usually not effect, but at igh baud rates, this can actually erase a new newly arrived data, not yet read by application. This would cause data loss at application layer.
The 2nd commit of this PR consist in using TXE (room in byte FIFO for posting next data) flag instead of TC (transmission complete), in order to improve overall performance. Also this is now in line with TxIrq definition from SerialBAse.h : TxIrq for transmit buffer empty
**READY**
Dependency to #4707 
This has been tested by @RobMeades in …
> Avoid data loss with serial interrupt used at high baudrates 

- targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L475xG/TARGET_DISCO_L475VG_IOT01A/PeripheralPins.c
- targets/TARGET_STM/TARGET_STM32L4/analogin_api.c
2 corrections for DISCO_L475VG_IOT: 
- Pins connected to serial debug printf are removed from the unavailable pins
- Alternate AnalogIn pins were not available
READY
> DISCO_L475VG_IOT : pin update

- features/frameworks/utest/utest/utest_specification.h
Add a constructor which explicitly takes the number of test cases. This allows a test case array created at runtime to be used.
> Add support for runtime test specification

- platform/mbed_application.h
- platform/mbed_critical.c
A define which expands to more defines is not portable across all compilers and GCC warns about this. Restructure this so the behavior is defined. This fixes the GCC warning:
"this use of "defined" may not be portable"
> Fix non-portable defines

- TESTS/mbed_hal/flash/functional_tests/main.cpp
The test assumed that data written to flash would be memory mapped
and directly accessible. On some platform this is not the case
and data has to read back through an explicit read command.
The test has been changed to use the flash read command instead
of direct memory access.
READY
Fix for merged API change here: https://github.com/ARMmbed/mbed-os/pull/4720
> mbed-hal: Fixed flash test

- targets/TARGET_STM/TARGET_STM32F1/device/stm32f1xx_hal_i2c.c
- targets/TARGET_STM/TARGET_STM32F2/device/stm32f2xx_hal_i2c.c
- targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_i2c.c
- targets/TARGET_STM/TARGET_STM32L1/device/stm32l1xx_hal_i2c.c
MBED_A29 test was FAILED for F1/F2/F4/L1 since #4299 and even with #4365
| OK     | NUCLEO_F103RB | ARM       | MBED_A20    | I2C master/slave test   |        0.28        |       30      |  1/1  |
| OK     | NUCLEO_F103RB | ARM       | MBED_A29    | i2c_master_slave_asynch |        0.47        |       30      |  1/1  |
| OK     | NUCLEO_F103RB | uARM      | MBED_A20    | I2C master/slave test   |        0.28        |       30      |  1/1  |
| OK     | NUCLEO_F103RB | uARM      | MBED_A29    | i2c_master_slave_asynch |        0.44        |       30      |  1/1  |
| OK     | NUCLEO_F103RB | GCC_ARM   | MBED_A20    | I2C master/slave test   |        0.33        |       30      |  1/1  |
| OK     | NUCLEO_F103RB | GCC_ARM   | MBED_A29    | i2c_master_slave_asynch |        0.47        | …
> STM32 I2C : correct async issue

- targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F767xI/device/TOOLCHAIN_GCC_ARM/startup_stm32f767xx.S
Many tests are failed with NUCLEO_F767ZI and GCC_ARM since #4659 
READY
| OK     | NUCLEO_F767ZI | GCC_ARM   | DTCT_1      | Simple detect test                    |        0.51        |       10      |  1/1  |
| OK     | NUCLEO_F767ZI | GCC_ARM   | EXAMPLE_1   | /dev/null                             |        3.45        |       20      |  1/1  |
| OK     | NUCLEO_F767ZI | GCC_ARM   | MBED_10     | Hello World                           |        0.38        |       5       |  1/1  |
| OK     | NUCLEO_F767ZI | GCC_ARM   | MBED_11     | Ticker Int                            |       11.37        |       15      |  1/1  |
| OK     | NUCLEO_F767ZI | GCC_ARM   | MBED_12     | C++                                   |        1.35        |       10      |  1/1  |
| OK     | NUCLEO_F767ZI | GCC_ARM …
> NUCLEO_F767ZI : boot issue with GCC

- targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/api/spi_api.c
The latest HAL extension was not applied to the LPC MCUXpresso targets.
Tested build for both broken targets (same HAL implementation used).
> LPC MCUXpresso: fix write_fill argument for block write function

- tools/export/__init__.py
- tools/export/atmelstudio/__init__.py
- tools/export/coide/__init__.py
- tools/export/e2studio/__init__.py
- tools/export/exporters.py
- tools/export/kds/__init__.py
- tools/export/lpcxpresso/__init__.py
- tools/export/simplicity/__init__.py
These exporters are planned for removal in mbed OS 5.6. To keep an exporter
around, a pull request to remove one of the "Deprecate *" commits should be
submitted against mbed-os along with an update to that exporer to make it
better conform to the best practices of an exporter from the
"adding exporters" documentation. For your convinience, the applicable section
is reproduced below:
> For the best user experience, an exporter:
> - Takes input from the resource scan.
> - Uses the flags in the build profiles.
> - Has a single template file for each file type they produce. For example, an eclipse CDT project would have one template for `.project` files and one for `.cproject` files.
> - Does not call mbed CLI. It is possible to export from the website, which will not include mbed CLI in the …
> Deprecate unsupported exporters

- TESTS/mbedmicro-rtos-mbed/mutex/main.cpp
- rtos/Mutex.h
Add descriptions, fix small issues and timings
**READY**
> RTOS: Mutex: Rework tests

- features/FEATURE_COMMON_PAL/nanostack-libservice/mbed-client-libservice/nsdynmemLIB.h
- features/FEATURE_COMMON_PAL/nanostack-libservice/module.json
- features/FEATURE_COMMON_PAL/nanostack-libservice/source/nsdynmemLIB/nsdynmemLIB.c
- features/FEATURE_COMMON_PAL/nanostack-libservice/test/libService/unittest/nsdynmem/dynmemtest.cpp
Update Nanostack/mbed-client libservice subtree - to provide new nsdynmemLIB API added in https://github.com/ARMmbed/nanostack-libservice/pull/60
Changes are an API extension, so should be no backwards compatibility issues.
Update required for mbed-client - discussed with @yogpan01 
Squashed patch contains only that nsdynmemLIB change, plus the Yotta change in https://github.com/ARMmbed/nanostack-libservice/pull/59, which does not affect mbed-os.
> Nanostack+mbed-client libservice update

- targets/TARGET_STM/TARGET_STM32F1/TARGET_BLUEPILL_F103C8/device/system_clock.c
Notes:
fixed the BLUEPILL (and likely other F1XX devices) oscillator setup
Problem described in issue #4753 
READY
NO
as said, it may impact other F1xx branches, but the HSI (fallback of the startup procedure) was doing 64Mhz), so systems may do faster than expected
I started the mbed build app in a remote target with GDB, and printed SystemCoreClock
> Bluepill: hse config fix

- targets/TARGET_NORDIC/TARGET_NRF5/TARGET_MCU_NRF52832/TARGET_VBLUNO52/PinNames.h
- targets/TARGET_NORDIC/TARGET_NRF5/TARGET_MCU_NRF52832/TARGET_VBLUNO52/device.h
- targets/targets.json
This PR add new target for the VBLUno52 board (VNG Bluetooth Low Energy UNO nRF52832)
+ The VBLUno52 board
nRF52832 ARM Cortex-M4F processor
Bluetooth Low Energy 5.0
DAPLink interface
UNO pinout
4 power
Pinout : 
**READY**
NO
Pass all test case in mbed test suite
[test_result_vbluno52.zip](https://github.com/ARMmbed/mbed-os/files/1153317/test_result_vbluno52.zip)
> Add support for the VBLUno52 board

- platform/mbed_stats.h
Doxygen wasn't very descriptive of what the functions actually do.
**READY**
> Improve documentation for memory stat ops

- features/FEATURE_BLE/ble/GapAdvertisingData.h
*CLA accepted: username on mbed is nodraak*
Fix issue #4799. I renamed[1] the function to prevent resolving issues for the compiler and added the necessary `const` and cast to make everything compile and work.
**READY**
NO
[1]: I followed the convention used by the other methods `addData` and `updateData`: `xxData` for public methods and `xxField` for private methods.
> Fix infinite calling loop

- tools/export/__init__.py
- tools/export/exporters.py
Signed-off-by: Johan Stokking <johan@stokking.nl> (ARM mbed OS developer site username **johanstokking**)
Closes #4802 
Replaces #4803 
**READY**
> Copy static files only

- .travis.yml
For testing purposes to find out why travis started failing suddenly
I checked travis-ci docs, they recommend using just pip install as they run in virtualenv. This however does not explain why it suddenly started failing.
> Travis: fix install phase - not use sudo

- tools/build_api.py
- tools/export/__init__.py
- tools/export/gnuarmeclipse/__init__.py
- tools/toolchains/__init__.py
This patch set resolves issue #3919 by unifying the logic for computing
excluded paths into `scan_resources`. This relieves the exporter from
having to compute this information itself, and significantly speeds up
exporters that had to compute exclusions (GNU ARM Eclipse at this time).
> Collect ignored directories in scan and use in exporters

- tools/test/examples/examples_lib.py
- tools/toolchains/__init__.py
Is blocking the release. Whoops
> Correct supported check in exporter tests

- features/mbedtls/targets/TARGET_STM/TARGET_STM32F7/TARGET_NUCLEO_F756ZG/mbedtls_device.h
Enable HW acceleration for SHA256 algorithm on STM32F756ZG
is #3961
READY
To test this feature, you have to modify TESTS/mbedtls/selfttest/main.cpp in order to call sha256 self test:
add:
`#include "mbedtls/sha256.h"`
then
```
#if defined(MBEDTLS_SHA256_C)
MBEDTLS_SELF_TEST_TEST_CASE(mbedtls_sha256_self_test)
#endif
```
then
```
#if defined(MBEDTLS_SHA256_C)
Case("mbedtls_sha256_self_test", mbedtls_sha256_self_test_test_case),
#endif
```
> NUCLEO_F756ZG/mbedtls: Add hw acceleration for SHA256

- TESTS/mbed_hal/lp_us_tickers/main.cpp
This test exercises us ticker API
- init should be executed just once
- read timestamp
- setting interrupts
Disable interrupt shall be also tested, should be proparly in its own test,
as it is the very last function to be executed (we dont have API to reenable interrupts), thus cant be in the same test unit.
Need to add documentation to this test.
This is very basic test, init version that can expand. I can add disable also but it is own file, was thinking something like this:
```
void test_us_ticker_disable_interrupt(void)
{
// we use here ticker API to set properly callback to set our complete flag
const ticker_data_t *us_ticker = get_us_ticker_data();
ticker_event_t event;
const uint32_t future_margin = 1000; // 1ms margin for interrupt to be fired 
complete = false; …
```
> test: add us ticker test

- TESTS/mbedmicro-rtos-mbed/queue/main.cpp
- rtos/Queue.h
Rework C++ RTOS Queue API docs and tests
**READY**
> RTOS: Queue tests & docs rework

- features/mbedtls/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F439xI/mbedtls_device.h
- features/mbedtls/targets/TARGET_STM/TARGET_STM32F7/TARGET_NUCLEO_F756ZG/mbedtls_device.h
- features/mbedtls/targets/TARGET_STM/md5_alt.c
- features/mbedtls/targets/TARGET_STM/md5_alt.h
- features/mbedtls/targets/TARGET_STM/sha1_alt.c
- features/mbedtls/targets/TARGET_STM/sha256_alt.c
- targets/targets.json
From workshop branch, rebased on top of master
For more info, see #4160
@adustm @RobMeades please review first
> F756/F439: add mbedtls md5 hash feature

- features/FEATURE_COMMON_PAL/mbed-coap/CHANGELOG.md
- features/FEATURE_COMMON_PAL/mbed-coap/module.json
- features/FEATURE_COMMON_PAL/mbed-coap/source/include/sn_coap_protocol_internal.h
- features/FEATURE_COMMON_PAL/mbed-coap/source/sn_coap_protocol.c
Fixes errors reported in Github 
- https://github.com/ARMmbed/mbed-os/issues/4798
- Fixed Lwm2m blockwise data transfer (using Block1 option) with Leshan
- https://github.com/ARMmbed/mbed-client/issues/512
-  Fixed an ongoing blocktransfer (Block 1 option) interruption by out of order Block to return error 4.08 Request Entity Incomplete as specified in the coap specification. 
- https://github.com/ARMmbed/mbed-client/issues/511
- Fixed detected duplicate message duplications will not stop mbed-client
**READY**
NO
https://github.com/ARMmbed/mbed-coap/pull/29
https://github.com/ARMmbed/mbed-coap/pull/28 …
> Updating mbed-coap to version 4.0.8

- tools/export/makefile/__init__.py
- tools/export/makefile/make-gcc-arm.tmpl
Issue #3673
The make_gcc_arm exporter for mbed os 2 fails with linker errors for wrapper functions. These can be fixed by adding the libraries to the linker group
**READY**
NO
import mbed classic program
mbed export -i make_gcc_arm
make
will fail with messages like:
```
undefined` reference to `__wrap__free_r'
```
> fix unresolved linker msg: __wrap_

- tools/export/cdt/__init__.py
- tools/export/cdt/pyocd_settings.tmpl
1. Rename Eclipse `.launch` file according to project name:
Since Eclipse supports working with multiple projects in the same workspace, .launch file name should include project name for creating unique per-project `.launch` file.
2. Fix CDT debugger settings on Linux - remove `.exe` suffix
On Linux machines `arm-none-eabi-gdb` executable do not have `.exe` suffix.
On Windows machines - it is possible to run an executable without explicit `.exe` suffix.
This change fixes debugger settings for Linux hosts
READY
NO
N/A
N/A
N/A
On a Linux host execute following steps:
1. cd mbed-os-example-blinky
2. `mbed export -m K64F -i eclipse_gcc_arm`
3. Launch eclipse
4. Click `File->Import->General->Existing Projects into Workspace` 
5. Build
6. Launch the debugger
> Enhancement - exporter/cdt

- tools/export/iar/iar_definitions.json
mbed exporter: Add IAR support for various NXP platforms
**READY
> mbed exporter: Add IAR support for various NXP platforms

- targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_mmc.c
Maybe I'm wrong, but I think the check here is incorrect. This gets evaluated as:
```
if((hmmc->MmcCard.Class) & (SDIO_CCCC_ERASE == 0U))
```
Because `==` has higher precedence than `&`.
> STM32F4_HAL_MMC erase command check is wrong. == has higher precedence than &

- targets/TARGET_Atmel/TARGET_SAM_CortexM0P/i2c_api.c
- targets/TARGET_Atmel/TARGET_SAM_CortexM0P/pwmout_api.c
I know these are mbed 2 targets, but I still think we should fix these bugs.
Found them using cppcheck.
> SAM_CortexM0P uses uninitialized memory in i2c and uses out of bounds array in pwmout

- features/unsupported/USBHost/targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L475xG/TARGET_DISCO_L475VG_IOT01A/USBHALHost_DISCO_L475VG_IOT01A.h
- features/unsupported/USBHost/targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L475xG/TARGET_DISCO_L475VG_IOT01A/USBHALHost_STM_TARGET.h
Add support of USBHost for the DISCO_L475VG_IOT01A target.
**READY**
NO
> DISCO_L475VG_IOT01A: Add support of USBHost

- targets/TARGET_ONSEMI/TARGET_NCS36510/device/TOOLCHAIN_IAR/NCS36510.icf
- targets/targets.json
- tools/targets/NCS.py
Dual flash and Hex file support added.  This is a separate pull request to replace #4397.  The changes are the same as the latest revisions on the previous PR, including the changes requested by @maclobdell.
READY
#4397 
Build output will be hex file. Post build script will insert FIB, User trim and trims gap.
Post script generates hex and binary file. Binary file required if user uses boot loader to download.
1. Clone latest branch of mbed-os, and modify NCS.py, ncs36510.icf, and targets.json
2. Clone mbed-os-example-blinky, and delete main.cpp
3. Update mbed-os.lib to point to local mbed-os library.  
4. mbed deploy ( or copy library into project) make sure changes are present in blinky project.  
5. mbed test -m NCS36510 -t IAR --compile  (Also tested with GCC and ARM)
6. mbed test -m …
> Dual Flash and Hex file support on NCS36510

- targets/TARGET_STM/can_api.c
This PR corrects a wrong value of the CAN_BTR_SJW bits position. Take the opportunity to use generic names defined in ST HAL driver.
Fix Issue #4763 
**READY**
NO
> STM32 CAN: Fix issue with speed function calculation

- targets/TARGET_STM/sleep.c
> Make HAL & US tickers idle safe

- targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K64F/spi_api.c
DSPI driver is update to support write_fill for default TX data. Dependent on PR #4805 
**READY**
> Use DSPI SDK driver API's in SPI HAL driver

- tools/export/vscode/__init__.py
The new Intellisense engine for Visual Studio Code requires a list of defines so it can properly index the code. Add the list of defines to the exporter.
In this PR I'm not switching to the new engine yet, because the new engine also needs the location of a bunch of v7m / cstdlib headers which come with the compiler, and I'm not sure how to automate this as their location depends on where your compiler was installed.
> Add list of defines to vscode exporter

- targets/TARGET_Realtek/TARGET_AMEBA/RTWInterface.cpp
To prevent new and delete frequently, use placement new to create instance at local array.
> Optimize memory usage of wifi scan for REALTEK_RTW8195AM

- targets/TARGET_NXP/TARGET_LPC11U6X/spi_api.c
- targets/TARGET_NXP/TARGET_LPC11UXX/spi_api.c
- targets/TARGET_NXP/TARGET_LPC11XX_11CXX/spi_api.c
- targets/TARGET_NXP/TARGET_LPC13XX/spi_api.c
- targets/TARGET_NXP/TARGET_LPC176X/spi_api.c
- targets/TARGET_NXP/TARGET_LPC408X/TARGET_LPC4088/spi_api.c
- targets/TARGET_NXP/TARGET_LPC408X/TARGET_LPC4088_DM/spi_api.c
- targets/TARGET_NXP/TARGET_LPC43XX/spi_api.c
This PR fix mask bits for SPI clock rate issue.  See https://github.com/ARMmbed/mbed-os/issues/4847 more detail information.
**READY**
*  LPC176x - LPC1768
* LPC11Uxx - LPC11U24
* LPC11U6x - LPCXpresso11U68
* LPC4337 - LPCXpresso4337
* LPC11xx_11Cxx - LPC1114
* LPC4088/DM - LPC4088 QuickStart board
LPC13xx has not been tested as we have no official target hardware.
> HAL LPCs SPI: Fix mask bits for SPI clock rate

- cmsis/TOOLCHAIN_GCC/TARGET_CORTEX_A/cache.S
- cmsis/TOOLCHAIN_IAR/TARGET_CORTEX_A/cache.S
This was removed during cmsis5 update. Here is original file:
https://github.com/ARMmbed/mbed-os/blob/mbed-os-5.4/cmsis/TOOLCHAIN_IAR/TARGET_CORTEX_A/cache.s
This was pointed out to me in one of the issues here, can't recall to reference this. That this file is missing and should be reverted.
cc @TomoYamanaka @toyowata Please review
> Fix Cortex-A cache file

- tools/build_api.py
- tools/make.py
- tools/memap.py
- tools/test.py
- tools/test/memap/memap_test.py
- tools/test_api.py
- tools/toolchains/__init__.py
Generates a detailed report by analysing static memory information from the map file.
The information from the map file is combined with the information from the BUILD directory (compiled objects and path to these objects), including the main application and user libraries.
In addition, it's now possible to visualise compiler libraries and identify other miscellaneous objects introduced by the toolchain. 
By default, memap generates a report with depth=2, but it's possible to specify a different depth level, and even to enable a full report (depth=0).
It has been tested with the three major toolchains: GCC, ARM and IAR compiler.
**READY**
NO
@sg- @theotherjimmy @screamerbg please review
```
$ mbed compile -t <toolchain> -m <target>    # displays memap info with depth=2 (default)
$ python …
```
> Enhance memap, and configure depth level

- platform/mbed_critical.c
Using macro available in CMSIS, instead of re-defining it. Issue #4866
> Using CMSIS/RTX Exclusive access macro

- tools/export/__init__.py
fixed adding a list and a tuple
traceback when exporting to zipfile could happen. Staticfiles were added as tuple to list.
**READY**
> fix export static_files to zip

- TESTS/mbedmicro-rtos-mbed/event_flags/main.cpp
- rtos/EventFlags.cpp
- rtos/EventFlags.h
Added the ability to set, clear or wait for event flag, it will be useful for building drivers with block like api.
for example building block device that preforms async operations on top of the spi driver to allow the system to do other tasks, in that case event flag will be waited in program, erase, etc... and the event flag will be set in the callback of async operation.
> Add cpp API for CMSIS OS 2 EventFlags

- features/TESTS/filesystem/util_block_device/main.cpp
- features/filesystem/bd/ProfilingBlockDevice.cpp
- features/filesystem/bd/ProfilingBlockDevice.h
This utility block device just has internal counters for keeping track of the number of bytes read/programmed/erased. Required for filesystem benchmarking.
> bd: Add ProfilingBlockDevice for measuring higher-level applications

- targets/TARGET_STM/mbed_rtx.h
INITIAL_SP missing when compile, here is a quick fix
> target BLUEPILL_F103C8 compile fix

- drivers/CAN.cpp
Replaced the deprecated function call .attach() with an assignment.
Fixes #4821 Deprecated Callback function used
> Fix compiler warning for deprecated function call

- features/filesystem/FileSystem.cpp
- features/filesystem/FileSystem.h
- features/filesystem/fat/FATFileSystem.cpp
- features/filesystem/fat/FATFileSystem.h
- platform/mbed_retarget.h
This function provides a shortcut to reformatting a mounted filesystem.
Usage without mounted filesystem:
``` cpp
BlockDevice *bd = user_provided;
int err = fs.mount(bd);
if (err) {
fs.reformat(bd);
}
// fs is now mounted
```
Usage with mounted filesystem:
``` cpp
fs.reformat();
// fs is now mounted
```
Formatting without mounting
``` cpp
BlockDevice *bd = user_provided;
FATFileSystem::format(bd);
// fs is not mounted
```
Also, since this function is a virtual member of the FileSystem class, the user does not need to know the underlying filesystem to reformat the underlying storage.
can replace https://github.com/ARMmbed/mbed-os/pull/4886
resolves #4903
related https://github.com/ARMmbed/mbed-os/issues/4407
cc @netanelgonen, @sg-, @pan-, @theotherjimmy
> fs: Add FileSystem::reformat

- .travis.yml
`ppa:terry.guo/gcc-arm-embedded` has been [deprecated](https://launchpad.net/gcc-arm-embedded/+announcement/13824) in favor of `ppa:team-gcc-arm-embedded/ppa`
This also means switching from `4.9.3.2015q3` to `6-2017q2`
**READY**
NO
> Update gcc-arm-embedded PPA in Travis

- platform/mbed_retarget.cpp
From #4830, implementing Option A. This saves ~3.3kB in firmware that's not using scanf otherwise. It also likely saves a few bytes of stack since buf is 5 bytes smaller.
READY
NO
> Remove excessive use of printf/scanf in mbed_fdopen/_open

- platform/mbed_board.c
- targets/targets.json
Reopening this PR from the [previous PR](https://github.com/ARMmbed/mbed-os/pull/4883).  I accidentally closed the previous one.
Unified the LED error sequence for all boards. Previously the LED sequence for boards with 4 LEDs was a patterned sequence, and for other boards, a fixed blinking LED. The new sequence is a repeating sequence of 4 fast pulses, followed by 4 slow pulses.
Fixes #1295 LED error patterns
> Modify LED error sequence to be more recognisable

- targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F410xB/device/TOOLCHAIN_ARM_MICRO/stm32f410xb.sct
- targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F410xB/device/TOOLCHAIN_ARM_STD/stm32f410xb.sct
On F410RB, the size reserved to vectors with ARM toolchain was not properly
defined,which was not the case for other toolchains.
This would cause few tests to fail like EXAMPLE_1 with below error:
HOST: Unknown property: mbed assertation failed: _ptr == (T *)&_data, file: C:/github/mbed/BUILD/mbed/platform/SingletonPtr.h, line 91
EXAMPLE_1 was failed before and is now passed:
```
+--------+---------------------+-----------+-----------+------------------+--------------------+---------------+-------+
| Result | Target              | Toolchain | Test ID   | Test Description | Elapsed Time (sec) | Timeout (sec) | Loops |
+--------+---------------------+-----------+-----------+------------------+--------------------+---------------+-------+
| OK     | NUCLEO_F410RB[F61A] | ARM       | …
```
> STM32: fix F410RB vectors size

- features/FEATURE_COMMON_PAL/mbed-coap/CHANGELOG.md
- features/FEATURE_COMMON_PAL/mbed-coap/module.json
- features/FEATURE_COMMON_PAL/mbed-coap/source/include/sn_coap_protocol_internal.h
- features/FEATURE_COMMON_PAL/mbed-coap/source/sn_coap_protocol.c
Fixes error reported in Github.
- https://github.com/ARMmbed/mbed-coap/issues/24
- https://github.com/ARMmbed/mbed-os/issues/4374
READY
NO
https://github.com/ARMmbed/mbed-coap/pull/30
https://github.com/ARMmbed/mbed-coap/pull/31
> Update mbed-coap to version 4.0.9

- rtos/MemoryPool.h
Provide fix for pool buffer size.
Add assertion to forbid creation of MemoryPool object with queue size equal to 0.
Update of free() function description.
Provide updates in MemoryPool.h file.
Ready
Fix in MemoryPool.h provides availability to create MemoryPool objects for types which sizes are not multiple of 4 bytes (fix alignment issue).
> Update of MemoryPool.h header file.

- tools/toolchains/iar.py
This fixes IAR build failure https://github.com/ARMmbed/mbed-os/issues/4879 .
> disable -f option for assembly files for IAR

- targets/TARGET_STM/TARGET_STM32F1/pin_device.h
It is required to enable AFIO clock before using __HAL_AFIO_REMAP_xy
macros, which was missing here. Without clocks enable, the remap
actually doesn't occur. This would possibly cause some PIOs (part of
PB_3, PB_4, PA_13, PA_14, PA_15) to not behave as expected.
In most cases AFIO clock was enabled in stm_pin_SetAFPin function, so
that this bug was not visible. But there were few cases left were
stm_pin_DisconnectDebug would be called first. A typical case was
with GCC_ARM in case a DigitalInOut variable is declared as global.
**READY**
Few MBED2 tests were failing on GCC_ARM/IAR before the fix.
Now: 
Test ID | Test Description | Target | Toolchain | Result
-- | -- | -- | -- | --
MBED_A5 | DigitalIn DigitalOut | NUCLEO_F103RB | ARM | OK
MBED_A5 | DigitalIn DigitalOut | NUCLEO_F103RB | …
> STM32: F1 GPIO: Enable AFIO clock

- features/unsupported/USBDevice/USBDevice/USBEndpoints.h
- features/unsupported/USBDevice/USBDevice/USBHAL.h
- features/unsupported/USBDevice/targets/TARGET_NUVOTON/TARGET_M451/USBHAL_M453.cpp
- features/unsupported/USBDevice/targets/TARGET_NUVOTON/TARGET_M480/USBEndpoints_M480.h
- features/unsupported/USBDevice/targets/TARGET_NUVOTON/TARGET_M480/USBHAL_M480.cpp
- features/unsupported/USBDevice/targets/TARGET_NUVOTON/TARGET_NUC472/USBHAL_NUC472.cpp
- features/unsupported/USBHost/targets/TARGET_NUVOTON/TARGET_M480/USBHALHost_M480.cpp
- features/unsupported/tests/rtos/mbed/file/main.cpp
- targets/TARGET_NUVOTON/TARGET_M480/device/StdDriver/m480_hsusbd.c
- targets/TARGET_NUVOTON/TARGET_M480/device/StdDriver/m480_sys.h
- targets/TARGET_NUVOTON/TARGET_M480/device/StdDriver/m480_usbd.c
- targets/TARGET_NUVOTON/TARGET_M480/device/StdDriver/m480_usbd.h
- tools/build_travis.py
This PR includes the following updates:
1. Support USB device/host on `NUMAKER_PFM_M487` target.
1. Support USB device/host for chip series, not just on `NUMAKER_PFM_NUC472`/`NUMAKER_PFM_M453` targets.
> M487: Support USB device/host

- targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F439xI/TARGET_UBLOX_EVK_ODIN_W2/PinNames.h
UBLOX_ODIN_EVK_W2 is missing the abstract button definitions originally
introduced with PR https://github.com/ARMmbed/mbed-os/pull/4249.
Fix two tab to spaces issues on the go as well.
Fix abstract buttons for UBLOX_EVK_ODIN_W2.
**READY**
NO
Mbed OS generic documentation for board porting would have to list the abstract button definition as a requirement.
N/A
Compile a test app which used BUTTON1 or BUTTON2.
> UBLOX_EVK_ODIN_W2- add BUTTON1/2 definitions

- platform/mbed_application.c
Fix a calculation error in in powerdown_nvic preventing the last
group of 32 interrupts from getting powered down. The ARMv7m reference
manual states ""the total number of interrupt lines is up
to (32*(INTLINESNUM+1)).".
Also rename isr_count to isr_groups_32 for clarity, since this is
actually the number of 32 interrupt groups.
> Fix ISR powerdown in mbed_application.c

- features/mbedtls/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F439xI/mbedtls_device.h
STM32F439xI-family AES hardware acceleration occasionally produces
incorrect output (https://github.com/ARMmbed/mbed-os/issues/4928).
Don't enable AES HW acceleration on STM32F439xI-family targets by
default until issue #4928 is fixed.
**READY for REVIEW as WORKAROUND**
- @adustm to perform initial investigation of #4928 
- If a fix to #4928 is ready before the next patch release, this workaround PR will be discarded.
This is a workaround for issue #4928
> mbedtls: STM32F439xI: Don't enable AES acceleration by default

- tools/test_api.py
As this variable is not in scope, should not be referenced.
~Fixes #4392~ No, you can't do "fixes PR#" only "fixes issue#" makes sense
Fixes #4930 
~I am not certain this is a proper fix. The variable is not in the scope in execute() . Should it be passed somehow there, or just ignored ? This fixes it as we are not using undefined variable. The question is how it should be passed to execute function or should not and this is correct?~
@theotherjimmy update: I passed stats depth correctly.
Tested with singletest.py. With this patch, it builds. Without, build does not even start, it crashes silently - FAIL build.
@MarceloSalazar @theotherjimmy You might know better, replace this patch or push to my branch.
> test: fix stats depth variable scope

- TESTS/mbed_drivers/flashiap/main.cpp
- targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F401xE/device/flash_data.h
- targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F410xB/device/flash_data.h
- targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F411xE/device/flash_data.h
- targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F413xH/device/flash_data.h
- targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F446xE/device/flash_data.h
- targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F469xI/device/flash_data.h
- targets/TARGET_STM/TARGET_STM32F4/flash_api.c
- targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F746xG/device/flash_data.h
- targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F756xG/device/flash_data.h
- targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F767xI/device/flash_data.h
- targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F769xI/device/flash_data.h
- targets/TARGET_STM/TARGET_STM32F7/common_objects.h
- targets/TARGET_STM/TARGET_STM32F7/flash_api.c
- targets/TARGET_STM/TARGET_STM32L0/flash_api.c
- targets/TARGET_STM/TARGET_STM32L1/flash_api.c
- targets/TARGET_STM/TARGET_STM32L4/flash_api.c
- targets/targets.json
Several updates concerning Flash API support on STM32 targets.
- As reported in #4966 the page size of STM32 F4 was set to a wrong value. The flash memory of these targets can be programmed 1 byte at a time which corresponds to the page size in flash API. 
- Moving the page size to 1 byte, led to a needed change in the set of tests, as reported #4972
- After those updates, the series also enables the flash API on more devices including full F4 and F7 devices. 
**READY**
tests-mbed_drivers-flashiap and tests-mbed_hal-flash  PASSED OK on ARM and GCC-ARM on L0, L1, L4, F4 and F7 STM32 targets.
[reports.zip](https://github.com/ARMmbed/mbed-os/files/1256737/reports.zip)
> Stm32 flash update
