ARMmbed/mbed-os

targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_K66F/device/cmsis_nvic.h, targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KW24D/device/cmsis_nvic.h, targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K22F/TARGET_MCU_K22F512/device/cmsis_nvic.h, targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K64F/device/cmsis_nvic.h
K66F,KW24D,K22F,K64F: Fix NVIC_NUM_VECTORS value
**READY**
=> K66F,KW24D,K22F,K64F: Fix NVIC_NUM_VECTORS value

mbed.h, platform/CriticalSectionLock.h
Critical section class RAII addition
I realized we dont have it here, and often used C API. This file is based on the class we used to have in core-util module (same thing, no changes, just different location).
cc @pan- @sg- @c1728p9 @bulislaw
=> platform: add CriticalSectionLock

targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KL27Z/device/cmsis_nvic.h, targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KL43Z/device/cmsis_nvic.h, targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KL82Z/device/cmsis_nvic.h
Fix a crash on boot due to incorrectly size vector count. This patch also reduces the ram vector size for devices which reserved too much space.
=> Fix crashes on boot on some Kinetis devices

features/filesystem/fat/FATFileSystem.cpp, features/filesystem/fat/FATFileSystem.h
Some block devices (for example I2C EEPROM) can be erased at the byte level. These aren't really block devices, but fall under the block device API. For these devices, the fat filesystem needs to use a lower bound on the block size. In this case we used 512 bytes is used since it is already a standard.
=> fatfs: Add lower bound to block sizes

features/netsocket/TCPSocket.cpp, features/netsocket/TCPSocket.h, features/netsocket/UDPSocket.cpp, features/netsocket/UDPSocket.h
Synchronization in sockets required binary semaphores which is not available
in RTX5, hence switching to event flags.
Issue #4575
PR should be merged after PR #4517. EventFlags Class implementation is picked up from this PR.
PR #4517 
PR #4560
=> Use EventFlags instead of Semaphores

events/mbed_events.h, events/mbed_lib.json, events/mbed_shared_queues.cpp, events/mbed_shared_queues.h, features/FEATURE_COMMON_PAL/nanostack-hal-mbed-cmsis-rtos/arm_hal_timer.cpp
First pass at a couple of shared event queues.
To allow components with a simple need to schedule a few events to not
have to create their own threads, with all the associated memory
overhead, add 2 central calls to get shared normal and an
interrupt-deferral event queues, each dispatched on their own shared
threads.
One initial in-tree user in this PR - the Nanomesh/mbed-client timer.
First out-of-tree users would be 6LoWPAN radio drivers like atmel-rf-driver.
=> mbed_events.h: Add ability to request a shared event queue

targets/TARGET_STM/TARGET_STM32F4/analogin_api.c
To get a valid VREF measurement on STM32F4 targets, it is required to increase
the sampling time to its maximum value.
Issue reported here:
[https://developer.mbed.org/questions/78792/STM32_ADC_InternalChannels-program-does-/]()
**READY**
NO
#4691 
ST_INTERNAL_REF 36013
=> STM32F4: Increase ADC sample time for VREF

TESTS/mbedmicro-rtos-mbed/mail/main.cpp
New test suite for mail class
**READY**
To pass Mail test following fix should be merged first: https://github.com/ARMmbed/mbed-os/pull/4941
=> Extends test set for Mail class

targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_spi.c, targets/TARGET_STM/stm_spi_api.c
This PR contains the required changes for supporting SPI 3-wires mode communication.
This allows to save 1 pin in constrained PCB designs. 
**READY**
This mode has been validated by using a ST Sensor by @mapellil @nikapov-ST 
The SPI standard mode has been tested with tests-api-spi of ci-test-shield suite and has not shown any regression on any of all STM32 target families.
=> Stm32 spi 3 wires mode support

features/FEATURE_BLE/ble/BLE.h, features/FEATURE_BLE/ble/BLEProtocol.h, features/FEATURE_BLE/ble/Gap.h, features/FEATURE_BLE/ble/GapAdvertisingParams.h, features/FEATURE_BLE/ble/GattCallbackParamTypes.h, features/FEATURE_BLE/ble/GattCharacteristic.h, features/FEATURE_BLE/ble/GattService.h, features/FEATURE_BLE/ble/services/DFUService.h, features/FEATURE_BLE/ble/services/HeartRateService.h, features/FEATURE_BLE/ble/services/LinkLossService.h, features/FEATURE_BLE/ble/services/UARTService.h
Some misguidances, some typos, some stylistics, some doxygen misuses.
**READY**
NO
=> Fix BLE API docs

targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F439xI/TARGET_UBLOX_EVK_ODIN_W2/PinNames.h
Odin target was missing LED_RED/GREEN/BLUE definitions that other client targets used. Adding these definitions removes the need to #ifdef around Odin targets in client source when referencing LEDs.
Majority of whitespace changes were to line up the assignments. Lines 157-159 are the import changes with the addition of:
```c++
LED_RED     = LED1,
LED_GREEN   = LED2,
LED_BLUE    = LED3,
```
CC @mray19027
=> Add LED color remapping definitions to Odin target

features/FEATURE_LWIP/lwip-interface/lwip-eth/arch/TARGET_Freescale/k64f_emac.c
Save 1K of RAM by using only 1 thread for RX and TX, and running the PHY check in lwIP's context.
This makes the driver function more a bit more like the Nanostack one in https://github.com/ARMmbed/sal-nanostack-driver-k64f-eth, and could be viewed as a first step towards unification as an EMAC driver.
=> Reduce K64F Ethernet driver to 1 thread

features/FEATURE_LWIP/lwip-interface/lwipopts.h
Commit f602c936 incorrectly started defining `LWIP_DEBUG` as either `0` or `1`.
lwipopts.h locally was changed to use `#if`, but all existing users continued to use `#ifdef`. Therefore defining it to `0` was accidentally enabling it for quite a few users.
This would have pulled in some unwanted lwIP code, and affected some drivers, eg k64f_emac.c allocating an extra 2K of stack.
Correct lwipopts.h to either define it as `1` or leave it undefined, and change the `#if` tests back to `#ifdef`, so all are consistent.
=> Correct LWIP_DEBUG definition

targets/TARGET_STM/TARGET_STM32F4/TARGET_MTS_DRAGONFLY_F411RE/device/system_clock.c, targets/TARGET_STM/TARGET_STM32F4/TARGET_MTS_MDOT_F411RE/device/system_clock.c, targets/TARGET_STM/TARGET_STM32L1/TARGET_XDOT_L151CC/device/system_clock.c, targets/TARGET_STM/TARGET_STM32L1/TARGET_XDOT_L151CC/xdot_low_power.c
The current behavior prevents linking out `printf()` and friends in release builds. This patch makes blinky on xDot use 15K(!!!!) less flash when compiling release build with GCC_ARM.
/cc @chrissnow This pushes my bootloader for xDot to 22K on GCC, 21K on ARMCC.
@reissjason @sg-
=> MTS targets: Don't use any printf() calls when NDEBUG is defined

targets/TARGET_NXP/TARGET_LPC176X/device/TOOLCHAIN_IAR/LPC17xx.icf
Since mbed-os 5.4.3, something increased foot print of mbed-os and the applications
that were barely fitting in started to spill.
IAR toolchain for LPC176x target family is set to use 2 RAM regions (32K each). RAM region
2 is being used for ETH/USB and 1 is being used for vector table, stack/heap/static data.
In this commit we have decreased heap size allocation from 8K to 7K so that the is more room for static data.
=> Adjust Stack size Allocation (IAR, LPC176x)

events/equeue/equeue_platform.h, rtos/Mail.h, rtos/RtosTimer.h, rtos/TARGET_CORTEX/mbed_rtos_storage.h, rtos/TARGET_CORTEX/mbed_rtx_conf.h, rtos/Thread.cpp, rtos/Thread.h, rtos/rtos.h
Make calls to cmsis-os to get thread state, stack size, and max stack usage rather than accessing internal RTX data directly. Wrap the code which has no public RTX function in TARGET_CORTEX_M since this needs to be defined for RTX to be included.
=> Remove use of internal RTX types

targets/TARGET_NXP/TARGET_LPC176X/device/TOOLCHAIN_IAR/LPC17xx.icf
This reverts commit fce2ca212263c58089c7bd54e48dfba00316ad3f. With the current heap for IAR (no dynamic yet), 2 tcp/udp tests fail with not enough heap memory.
@hasnainvirk @kjbracey-arm @geky 
parallel tests fail, they allocate on heap Echo class
```
// Startup echo threads in parallel
for (unsigned int i = 0; i < MBED_CFG_UDP_CLIENT_ECHO_THREADS; i++) {
echoers[i] = new Echo;
echoers[i]->start(i, uuid);
}
```
Should Arch PRO decrease any config there in those tests ,as not having enough heap ? With previous heap, there was not enough memory left for cellullar application, with the current our 2 tests fail due to not enough heap. I do not see the requirements for parallel testing - how much heap these test require. I can spot there 2x buffers 64bytes plus other objects, multiplied by 3, …
=> Revert "Adjusting Stack size Allocation (IAR, LPC176x)"

tools/export/uvision/__init__.py, tools/export/uvision/uvision.tmpl
Bootloader projects require DMBED_APP_START and DMBED_APP_SIZE flags passing to the linker, CLI does this but export did not.
**READY**
NO
Export a bootloader project and it does not have the linker flags set.
=> Export uVision linker flags so that bootloader projects build correctly

TESTS/mbed_hal/sleep_manager/main.cpp, TESTS/mbed_hal/sleep_manager_racecondition/main.cpp, drivers/CAN.cpp, drivers/CAN.h, drivers/I2C.cpp, drivers/I2C.h, drivers/SPI.cpp, drivers/SPI.h, drivers/SerialBase.cpp, drivers/SerialBase.h, drivers/Ticker.cpp, drivers/Ticker.h, drivers/Timeout.h, drivers/Timer.cpp, drivers/Timer.h, hal/mbed_sleep_manager.c, mbed.h, platform/DeepSleepLock.h, platform/mbed_sleep.h, rtos/rtos_idle.c
This goes to feature-hal-spec, based on the sleep manager work that is here #4882 . Review only the last commit (at the moment SHA 34f9f43). This goes to `feature-hal-spec` branch = work in progress
To move further with sleep, I am sending this early to get feedback.
The goal is to have deepsleep locks for those drivers that depend on high speed clocks (it can be that some drivers for a target might support deep sleep but this is not usual, plus speed is limited often).
@bulislaw @c1728p9 @pan-
=> Add sleep manager API

.travis.yml
=> Travis: fix the latest breakage - use group:

targets/TARGET_STM/us_ticker_16b.c
Fixes test suggested in #5004.
Fixing regression introduced in commit
"Ticker: add fire interrupt now function".
In above mentioned commit, the management of timestamp being in the past
has been moved to higher layer (hal/mbed_ticker_api.c), but the reset of
oc_int was missing when implementing the new us_ticker_fire_interrupt
function - which is fixed now.
**READY**
=> STM32_us_ticker_16b: keep code to cope with past event

TESTS/mbed_drivers/lp_timeout/main.cpp, TESTS/mbed_drivers/timeout/main.cpp, TESTS/mbed_hal/lp_ticker/main.cpp, TESTS/mbed_hal/sleep_manager_racecondition/main.cpp, drivers/Ticker.cpp, targets/TARGET_ONSEMI/TARGET_NCS36510/sleep.c, targets/targets.json
Couple of fixes here:
- lp ticker - use Timer to wait (this will however need more investigation with wait_ms as it should work, I'll create a tracking issue for this, this should be the functionally same affect for this test)
- sleep manager - decrease the stack for Threads as the default one is too big for the test purposes (out of memory for small targets)
See failures: https://github.com/ARMmbed/mbed-os/pull/4987#issuecomment-328255913
Whats left to do - nrf52 critical section - seems like the critical section does not work, look at sleep manager  race condition. It fails. This is interesting as we have some race conditions tests, for instance also for threads. I'll review the test again, are we using it correctly, and the bug is in nordic implementation of critical section, as the …
=> Fixing lp ticker and sleep manager tests

cmsis/TARGET_CORTEX_M/cmsis_compiler.h, platform/CThunk.h, rtos/TARGET_CORTEX/rtx5/TARGET_M23/TOOLCHAIN_GCC/irq_armv8mbl.S, rtos/TARGET_CORTEX/rtx5/TARGET_M23/TOOLCHAIN_IAR/irq_armv8mbl.S, rtos/TARGET_CORTEX/rtx5/TARGET_M33/TOOLCHAIN_GCC/irq_armv8mml.S, tools/targets/__init__.py, tools/toolchains/__init__.py, tools/toolchains/gcc.py, tools/toolchains/iar.py
Added RTX + tools support for GCC only.
IAR 7.8 Cortex-23 does not support exclusive and secure commands. Move to IAR 8.0 requires changed in either Thread class or CMSIS (Ideal would be CMSIS).  Hence dropping IAR in this PR
Required for : Rebased Nuvoton code for M2351 - PR #4892 
Dependent on IAR 8.0 support
=> Initial support for Cortex M-23/M-33 devices.

TESTS/mbed_hal/flash/functional_tests/main.cpp
fix the armc6 compile error,  ARM 6 is compatible with GCC  so unify GCC and ARM 6 code 
```
00:00:44.012         [DEBUG] Output: ./TESTS/mbed_hal/flash/functional_tests/main.cpp:82:11: error: no flag-preserving variant of this instruction available
00:00:44.012         [DEBUG] Output:     "%=:\n\t"
00:00:44.013         [DEBUG] Output:           ^
00:00:44.013         [DEBUG] Output: <inline asm>:2:2: note: instantiated into assembly here
00:00:44.013         [DEBUG] Output:         SUB  r0, #1
```
__asm behavior between arm 5 and arm 6
1. For embedded assembly, you **cannot** use the __asm keyword on the **function declaration**.
2. The __asm keyword can incorporate inline GCC syntax assembly code into a function
[reference 6.8](http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc. …
=> use gcc assembly for arm 6

tools/export/__init__.py, tools/export/makefile/__init__.py, tools/export/uvision/__init__.py, tools/export/uvision/uvision.tmpl
None of the exporters can handle them, so just don't do it
Resolves #5092
=> Disable response files on export

targets/TARGET_Realtek/TARGET_AMEBA/TARGET_RTL8195A/device/rtl8195a_compiler.h, targets/TARGET_Realtek/TARGET_AMEBA/sdk/soc/realtek/common/bsp/basic_types.h
This should fix the extremely long compile times for the Realtek
RTL8195AM board. Could I get someone from Realtek to review?
=> Correct long call macros for ARMC6

tools/profiles/debug.json, tools/profiles/develop.json, tools/profiles/release.json
Which allows it to be parsed, and dependency information is restored!
Resolves #5110
=> Emit dependency information with ARMC6

targets/TARGET_Realtek/TARGET_AMEBA/rtw_emac.cpp
Changed error print to assert function, since using malloc instead of new.
This PR is to close review comment related to emac_interface_t in PR #4938 
https://github.com/ARMmbed/mbed-os/pull/4938/files/6bd28ecb685542237808f9e009dbb9510372d14c#diff-5cc67fcf86ead5e18c66e794b692d326L220
=> Changed error print to assert

rtos/TARGET_CORTEX/mbed_rtx_idle.cpp
mbed_rtx_idle: uVisor: Don't attempt to sleep
When uVisor is enabled, don't attempt to sleep. Attempting to sleep will fail, as per <https://github.com/ARMmbed/uvisor/issues/420>.
Fixes OOB issue https://github.com/ARMmbed/mbed-os-example-uvisor/issues/55
**READY**
=> mbed_rtx_idle: uVisor: Don't attempt to sleep

features/netsocket/cellular/generic_modem_driver/PPPCellularInterface.cpp
From C++11 and beyond string literals must be seperated by space
so that they are recongizable as seperate tokens.
Context macro in PPPCellularInterface (CTX) has been causing issues
as it was not augmented with a space from a nearby string literal.
=> Separate string literal from macro

targets/TARGET_NORDIC/TARGET_NRF5/TARGET_MCU_NRF51822_UNIFIED/device/TOOLCHAIN_ARM_STD/TARGET_MCU_NORDIC_32K/nRF51822.sct, targets/TARGET_NORDIC/TARGET_NRF5/TARGET_MCU_NRF51822_UNIFIED/device/TOOLCHAIN_ARM_STD/TARGET_MCU_NRF51_16K_S110/nRF51822.sct, targets/TARGET_NORDIC/TARGET_NRF5/TARGET_MCU_NRF51822_UNIFIED/device/TOOLCHAIN_ARM_STD/TARGET_MCU_NRF51_16K_S130/nRF51822.sct, targets/TARGET_NORDIC/TARGET_NRF5/TARGET_MCU_NRF52832/device/TOOLCHAIN_ARM_STD/nRF52832.sct, targets/TARGET_NORDIC/TARGET_NRF5/TARGET_MCU_NRF52840/device/TOOLCHAIN_ARM_STD/nRF52832.sct, targets/TARGET_NORDIC/TARGET_NRF5/reloc_vector_table.c, tools/hooks.py, tools/targets/__init__.py, tools/toolchains/__init__.py
**READY**
This should correct the booting of nordic devices so that they boot with
ARM6
=> Correct booting on Nordic devices with ARMC6

rtos/TARGET_CORTEX/rtx5/TARGET_M23/TOOLCHAIN_ARM/irq_armv8mbl.S, tools/test/build_api/build_api_test.py, tools/toolchains/arm.py
Tools updated to support ARMC6 toolchain for Cortex-M23. Also added ARM context switch assembly file.
Known Issue:
ARMC6_PATH set using `mbed config -G` command is not working. Set environment variable "MBED_ARMC6_PATH" for time being.
=> ARMC6 support for Cortex-M23

features/nanostack/FEATURE_NANOSTACK/coap-service/source/include/coap_security_handler.h
Notes:
Fix macro redefinition warning/error by adding guards around the macros that could be redefined. 
This will fix https://github.com/ARMmbed/coap-service/issues/75.
**READY**
NO
branch | PR
required changes in the build environment, tools, compilers, …
=> Fix redefinition of mbed TLS error codes

targets/TARGET_Realtek/TARGET_AMEBA/TARGET_RTL8195A/device/TOOLCHAIN_ARM_STD/rtl8195a.sct, targets/TARGET_Realtek/TARGET_AMEBA/TARGET_RTL8195A/device/TOOLCHAIN_GCC_ARM/rtl8195a.ld, targets/TARGET_Realtek/TARGET_AMEBA/TARGET_RTL8195A/device/TOOLCHAIN_IAR/rtl8195a.icf, targets/TARGET_Realtek/TARGET_AMEBA/us_ticker.c
commit f7bc12626d06 (Re-work Rtl8195AM ticker) tried to address ticker drifting issue, but in
fact broke ticker functionality.This patch adjusts us_ticker porting to un-break it, and to fix the following tests:
mbed-os-tests-mbed_drivers-ticker
mbed-os-tests-mbed_drivers-timeout
mbed-os-tests-mbedmicro-rtos-mbed-isr
mbed-os-features-frameworks-utest-tests-unit_tests-minimal_async_scheduler
mbed-os-features-frameworks-utest-tests-unit_tests-case_control_async
mbed-os-features-frameworks-utest-tests-unit_tests-case_async_validate
Changes are:
1. Dont disable timer after every us_ticker interrupt. That basically
breaks ticker functionality.
2. Fine-tune us to tick conversion macro. Previous conversion method
yields 1 tick drift every 2 ms.
3. Remove special placement of ticker objects. No …
=> RTL8195AM - Fix us_ticker porting

.travis.yml
pip requires --user flag when installing executables outside of sudo context
see https://github.com/ARMmbed/mbed-os/pull/5055
cc @0xc0170, @theotherjimmy
=> Travis: Fix requirements install

features/mbedtls/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F439xI/mbedtls_device.h, features/mbedtls/targets/TARGET_STM/aes_alt.c, features/mbedtls/targets/TARGET_STM/aes_alt.h
tls-client example is calling aes_encrypt with 4 separated instances (ctx), in ECB mode.
There is a moment where we have : 
```
call aes_set_key(ctx3)   <-- here the key of ctx3 is copied in ctx3->key
call aes_encrypt(ctx3)   <-- here ctx3->key is copied in the hardware registers
call aes_set_key(ctx4)   <-- here the key of ctx4 is copied in ctx4->key
call aes_encrypt(ctx4)   <-- here ctx4->key is copied in the hardware registers
call aes_encrypt(ctx3)   <-- PROBLEM: hardware registers still contain the key of ctx4
call aes_encrypt(ctx3)...
```
I have added 
ctx->hcryp_aes.Phase = HAL_CRYP_PHASE_READY;
in aesecb_encrypt function so that the firmware manages all the time the copy of ctx->key in hardware registers
I have removed the workaround implemented by @patater in #4934 
**READY** …
=> Fix use of AES_ALT on STM32F439 for example-tls-client 

features/mbedtls/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F439xI/mbedtls_device.h
STM32F439xI-family MD5, SHA1 and SHA256 hardware acceleration
occasionally produces incorrect output (#5079).
Don't enable MD5, SHA1 and SHA256 HW acceleration on STM32F439xI-family
targets by default until issue #5079 is fixed.
READY for REVIEW as WORKAROUND
=> mbedtls: Disable MD5, SHA1, SHA256 HW ACC for STM32F439xI

TESTS/mbed_drivers/lp_timeout/main.cpp, TESTS/mbed_hal/lp_ticker/main.cpp, TESTS/mbedmicro-rtos-mbed/mutex/main.cpp, TESTS/mbedmicro-rtos-mbed/queue/main.cpp, TESTS/mbedmicro-rtos-mbed/semaphore/main.cpp, TESTS/mbedmicro-rtos-mbed/threads/main.cpp
Remove the direct use of the microsecond and low power ticker from the tests. This enforces that sleep mode is properly locked when using timers. Furthermore, this prepares the codebase for new ticker changes which allow differing clock frequencies and timer bit widths.
=> Remove direct use of us and lp ticker from tests

tools/memap.py, tools/profiles/debug.json, tools/profiles/develop.json, tools/profiles/release.json, tools/test/memap/arm.map, tools/test/memap/gcc.map, tools/test/memap/iar.map, tools/test/memap/parse_test.py, tools/toolchains/arm.py
Improves performance by 10-15x on my machine. See below for individual compiler comparisons.
Resolves #4976
Resolves #5124
Resolves #5127 
Todo:
=> Refactor memap for speed

features/filesystem/bd/BlockDevice.h, features/filesystem/fat/ChaN/ffconf.h, features/filesystem/fat/FATFileSystem.cpp
The block device API is currently tied very closely to flash devices. This is because flash devices are our primary targets, but it does make porting to other non-flash block devices a bit more confusing than is necessary (this includes SD cards, FTLs, and more ridiculous spinny disks).
These are a few tweaks from offline discussions with @deepikabhavnani that should improve things:
1. Provide default for erase function
This means the function can simply be omitted from the SD card repo and the block device should behave as expected
2. Add trim function to provide hints for unused blocks
See https://en.wikipedia.org/wiki/Trim_(computing) for prior art
This allows a filesystem to hint when blocks are no longer in use, and can allow much better wear leveling performance when an FTL is …
=> bd: Tweaked block device API to fit SD cards and FTLs better

drivers/FlashIAP.h, hal/flash_api.h
This unit is the minimum writable size that flash controller supports.
Raised here https://github.com/ARMmbed/mbed-os/issues/4966
@LMESTM @LiyouZhou @c1728p9
=> flash: add note about program size

TESTS/mbedmicro-rtos-mbed/threads/main.cpp, rtos/TARGET_CORTEX/mbed_rtx_handlers.c
Hook was added in RTX4 code to assist test framework to log thread info on thread terminate, which was not working with RTX5.
**READY**
Execute test mbed-os-tests-mbedmicro-rtos-mbed-threads with MBED_STACK_STATS_ENABLED set to 1.
@c1728p9 @bulislaw
=> Add thread terminate hook

targets/TARGET_STM/TARGET_STM32L1/TARGET_XDOT_L151CC/PinNames.h, targets/targets.json
=> Add new target: L-TEK FF1705

targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KW24D/device/TOOLCHAIN_ARM_STD/MKW24D512xxx5.sct, targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KW24D/device/TOOLCHAIN_GCC_ARM/MKW24D512xxx5.ld, targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KW24D/device/TOOLCHAIN_IAR/MKW24D512xxx5.icf, targets/targets.json
Adds support for building the Mbed bootloader for the FRDM-KW24D platform.  The bootloader provides the mechanism to do firmware updates.
Review
27 and 217
In bootloader project
mbed compile -m PLATFORM -t TOOLCHAIN
Copy compiled bootloader to FRDM-KW24D
Attach a ci-test-shield with a FAT32 formatted SD card inserted to the FRDM-KW24D
Connect the serial terminal, reset the board, and observer the bootloader initialization
=> Add bootloader support for NXP FRDM-KW24D

TESTS/mbed_drivers/stats/main.cpp, platform/mbed_alloc_wrappers.cpp
Heap stats were not calculated for IAR, since we didn't have mechanism to hook IAR functions.
IAR has internal heap statistic data, which can be enabled and used. Below is the reference link
https://www.iar.com/support/tech-notes/general/iar-dlib-library-heap-usage-statistics/
Only current heap size (with 8 bytes of overhead per malloc) and max heap size is reported. 
Below is the output for simple malloc program allocating and freeing 1000 bytes of memory
```
Allocating 1000 bytes
Current heap: 1008
Total heap size: 65536
Freeing 1000 bytes
Current heap after: 0
Total heap size: 65536
```
=> Add heap stats for IAR

features/filesystem/FileSystem.cpp
When building mbed-os with the third-party tool VisualGDB, it fails compiling after an exported project has been imported.
Building the filesystem driver failed because the Managed class was missing two includes (invalid use of incomplete type 'class mbed::Dir' / invalid use of incomplete type 'class mbed::File')
READY
NO
Take exported package of Online Compiler, import it into VisualGDB and compile it.
=> missing includes for filesystem.cpp (build with VisualGDB fails)

tools/export/makefile/Makefile.tmpl, tools/export/makefile/__init__.py
`armasm` seem to preprocess asm with the `.S` extension on linux, but the
windows build of Arm Compiler 5 seems to omit the preprocessing step
unless you have a `.sx` extension. Odd.
Resolves #5145
=> Force preprocessing of asm for make_armc5

tools/export/GettingStarted.html
@AnotherButtler, could you confirm that this new link is where we store
errata for exporters and is current?
Sort of repairs #5146
=> Update link in GettingStarted to current docs

targets/TARGET_NXP/TARGET_LPC176X/device/TOOLCHAIN_IAR/LPC17xx.icf, targets/TARGET_NXP/TARGET_LPC176X/device/flash_api.c
The topmost 32 bytes used by IAP functions, this was not included in the RAM
end previously.
Running test multiple times to be certain this fixes it. The last 10 runs -- all OK
```
+-------------+---------------+-----------------------------+---------------------------+--------+--------+--------+--------------------+
| target      | platform_name | test suite                  | test case                 | passed | failed | result | elapsed_time (sec) |
+-------------+---------------+-----------------------------+---------------------------+--------+--------+--------+--------------------+
| LPC1768-IAR | LPC1768       | tests-mbed_drivers-flashiap | FlashIAP - init           | 1      | 0      | OK     | 0.05               |
| LPC1768-IAR | LPC1768       | tests-mbed_drivers-flashiap | …
```
=> LPC1768: RAM end adjust fix

tools/build_api.py, tools/project.py
=> Check for mbed 5 support on export

features/netsocket/cellular/generic_modem_driver/PPPCellularInterface.cpp
Look-up of the APN for a cellular connection in `APN_db.h` was failing because the call to `apncfg()`, which requires the IMSI, was being made before the IMSI had been retrieved from the modem.
[ARMmbed/easy-connect #41](https://github.com/ARMmbed/easy-connect/pull/41)
=> Fix cellular APN_db.h lookup.

targets/TARGET_STM/TARGET_STM32F4/TARGET_MTS_DRAGONFLY_F411RE/device/system_clock.c, targets/TARGET_STM/TARGET_STM32F4/TARGET_MTS_MDOT_F411RE/device/system_clock.c, targets/TARGET_STM/TARGET_STM32L1/TARGET_XDOT_L151CC/device/system_clock.c, targets/TARGET_STM/TARGET_STM32L1/TARGET_XDOT_L151CC/xdot_low_power.c
Instead of using #if NDEBUG, we can directly invoke debug() function. Fixes #5013
@janjongboom @sg- @mfiore02
=> mts targets: fix debug() usage

drivers/Timer.cpp, drivers/Timer.h
Release the deep sleep lock when running instances of the Timer class are deleted. This ensures that deep sleep locks are properly released by the Timer class.
=> Release deep sleep lock in destructor of Timer class

drivers/PwmOut.h
As discussed here https://github.com/ARMmbed/mbed-os/pull/5157, PWMOut should lock deepsleep while active.
As PWMOut in most cases depend on high speed freq clock, it should lock deepsleep while active.
cc @c1728p9 @ccli8
=> PWMOut: lock deesleep addition

platform/Callback.h
Fixed by zeroing the uninitialized memory. A more "correct" approach may be to add an additional op for equality, and use the "==" operator on the F type in the generate function. But this adds the requirement that F supports equality.
cc @0xc0170, @pan- 
fixes #5017
=> cb: Fix uninitialized memory used for equality check

targets/TARGET_STM/TARGET_STM32F4/flash_api.c, targets/TARGET_STM/TARGET_STM32F7/flash_api.c, targets/TARGET_STM/TARGET_STM32L0/flash_api.c, targets/TARGET_STM/TARGET_STM32L1/flash_api.c, targets/TARGET_STM/TARGET_STM32L4/flash_api.c
Rather than Unlocking flash during flash object creation, and leaving
the flash possibly continuously unlocked a(s object might bever be freed),
we decide to Unlock then Lock again at each erase or program call.
This solves issue #4967 
**READY**
```
+-------------------+---------------+-----------------------------+--------+--------------------+-------------+
| target            | platform_name | test suite                  | result | elapsed_time (sec) | copy_method |
+-------------------+---------------+-----------------------------+--------+--------------------+-------------+
| NUCLEO_L073RZ-ARM | NUCLEO_L073RZ | tests-mbed_drivers-flashiap | OK     | 80.59              | shell       |
| NUCLEO_L073RZ-ARM | NUCLEO_L073RZ | tests-mbed_hal-flash        | OK     | 79.9               | …
```
=> STM32: Lock / Unlock flash for each operation

targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L432xC/device/TOOLCHAIN_ARM_MICRO/startup_stm32l432xx.S, targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L432xC/device/TOOLCHAIN_ARM_MICRO/stm32l432xx.sct, targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L432xC/device/TOOLCHAIN_ARM_STD/startup_stm32l432xx.S, targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L432xC/device/TOOLCHAIN_ARM_STD/stm32l432xx.sct, targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L432xC/device/TOOLCHAIN_GCC_ARM/STM32L432XX.ld, targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L432xC/device/TOOLCHAIN_IAR/stm32l432xx.icf, targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L432xC/device/cmsis_nvic.h, targets/TARGET_STM/mbed_rtx.h
RAM size is increased from 48k to 64k for STM32L432KC as proposed in #4823 
WARNING: you have to update ST-Link FW to V2J29M18
http://www.st.com/en/development-tools/stsw-link007.html
READY
All OS2 and OS5 tests have been checked
=> STM32L432KC: increase RAM size from 48k to 64k

features/filesystem/Dir.cpp
Should leave the Dir in an openable state, currently does not since it thinks it's in use by the fs it failed to open on.
=> fs: Fix dir open during failure condition

features/FEATURE_BLE/ble/services/UARTService.h
If only buffer-full events and LF characters trigger the flush of
the send buffer then only line-based communication can be
implemented over the BLE UART Service. This patch extends the
service API by adding an explicit `flush` method to force sending
the buffer contents, thus enabling protocols with short (e.g.,
single character) messages.
**READY**
NO
=> Add flush to the BLE UART Service

drivers/Ticker.h
=> Ticker class description update - small interval warning

targets/TARGET_RENESAS/TARGET_RZ_A1H/can_api.c, targets/TARGET_RENESAS/TARGET_VK_RZ_A1H/can_api.c
Notes:
* Bug fix.
* The CAN module produce a substantially different message ID, when using Extended mode.
* The CAN module hardly receives external messages from the bus (produced from nods other than VK_RZ_A1H platforms), so I tweaked the SJW field to be more tolerant to the incoming message's frequency (bitrate).
Just use the CAN in extended mode and try to receive a message from node which is clocked exactly at 500 kbps.
=> [RZ_A1H] Correct CAN Message ID and recetption rate in extended mode

drivers/InterruptIn.cpp
As we can check if callback was attached, we use NULL assignment.
Just a cosmetic change, that follows what we did for other attach() drivers.
@sg- @geky
=> InterruptIn: Use NULL callback by default

platform/mbed_retarget.cpp, platform/mbed_rtc_time.cpp
Move clock() function from mbed_rtc_time.cpp to mbed_retarget.cpp as this is more suitable place for this function.
This PR is a result of discussion from [PR#5087:](https://github.com/ARMmbed/mbed-os/pull/5087)
> > There is no information in documentation neither header file about clock() function. Maybe this function should be removed? It is used nowhere and it looks like this is not API.
> I think it's a implementation of standard library function, maybe it's not the best place for it, you could try opening new PR and moving it to mbed_retarget.cpp.
READY
NO
=> Move clock() function from mbed_rtc_time.cpp to mbed_retarget.cpp.

.coveragerc
I noticed recently, that our coverage numbers changed when we updated a
package we depend on. This is nonsense. Our coverage numbers should
reflect only our code.
=> Omit libraries and tests from tools coverage numbers

drivers/UARTSerial.h
`UARTSerial` inherits both `FileHandle::readable()` [public] and
`SerialBase::readable()` [private], so calling `readable()` on a UARTSerial
object produces an ambiguous member error.
Add `using` declarations to direct towards the `FileHandle` versions of
`readable` and `writable`.
There's currently no ambiguity for `writable`, as `SerialBase` uses the
spelling `writeable`, but add a `using` directive for that anyway, in case
`SerialBase` gains `writable` later.
Resolves issue #5035
=> UARTSerial: Avoid readable() ambiguity

drivers/Ticker.cpp, drivers/Ticker.h, drivers/Timer.cpp, drivers/Timer.h
Fix for issue #5076.
This PR contains fix to be able to enter deep-sleep mode while using low power ticker/timer.
READY
YES
After this fix is when low power ticker/timer is in use deep-sleep will not be disabled.
=> Enable deepsleep for LowPowerXXX objects

TESTS/mbed_drivers/ticker/main.cpp
New test suite for Ticker class
**READY**
Test fails on NUCLEO_F070RB board
Waiting fix for https://github.com/ARMmbed/mbed-os/issues/5004
=> Extends test set for Ticker class

targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F439xI/TARGET_UBLOX_EVK_ODIN_W2/PinNames.h
Second portion of this PR: https://github.com/ARMmbed/mbed-os/pull/4995
Whitespace changes to fit new LED names and remove trailing whitespaces.
=> Adjust whitespace in Odin PinNames file to fit verbose LED pin mappings

features/FEATURE_LWIP/lwip-interface/lwip_stack.c
Mapped lwip internal ERR_BUF error value to NSAPI_ERROR_NO_MEMORY. 
This corrects issue: https://github.com/ARMmbed/mbed-os/issues/4981
READY
NO
None
None
None
=> Mapped lwip buffer error to nsapi no memory error

tools/export/ds5_5/__init__.py, tools/export/e2studio/__init__.py
Notes:
* This is the PR supposed to fix the ds5 & e2studio exporters. but I very much doubt it will fix the online exporter issue.
* Online Project exporter persistently refuses to work. The details can be found in issue #3768, which obviously continues to be an issue.
* No information for used RAM and ROM in the online compiler, when compiling projects for VK_RZ_A1H platform.
Try to export standard mbed_blinky project for platform VK_RZ_A1H with the online compiler (export option) for toolchains IAR or ds5 or e2studio.
=> ds5 & e2studio export fix

rtos/TARGET_CORTEX/rtx5/rtx_kernel.c
The osKernelGetTickCount() is the only function to get kernel tick information, however it's not allowed to access in ISR.
The implementation is already enabled in API v2.1.1.
https://github.com/ARM-software/CMSIS_5/commit/f32dc4c2c51a68d614a92d59dd634d8edecb4e69
=> Enable access to kernel tick information in ISR

targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC54608/TARGET_LPCXpresso/PinNames.h
=> LPC54608: Swap LED pin connections to match naming on the board

targets/TARGET_Freescale/TARGET_K20XX/rtc_api.c, targets/TARGET_Freescale/TARGET_KLXX/rtc_api.c, targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/api/rtc_api.c, targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/api/rtc_api.c
There is no hardware limitation in writing a 0 value to the seconds register.
=> Kinetis RTC HAL: Allow writing 0 to the seconds register

targets/TARGET_Silicon_Labs/TARGET_EFM32/us_ticker.c
There's overflow counter that needs to be 0, and
CC0 flag set.
Fixes #5051
Tested with example in the issue, the callback is fired as it should. I've been testing it with leopard gecko (any efm32 should do the trick).
cc @fkjagodzinski
=> EFM32: fix fire interrupt (set flags)

tools/test/toolchains/api_test.py, tools/toolchains/iar.py
Fixes #5181
This PR moves the passing of ld flags when compiling with `IAR` to the
constructor.
This PR also adds tests that certify that all toolchains pass all
arguments from their build profiles both:
- In the constructor
- On the command line invocation
This is stronger than the prior guarantee, which was: The compilers (C,
C++, Assembler) all pass their build profile arguments to the command
line invocation.
=> tools/toolhains - Test for flag passing in constructor

targets/targets.json
As pointed in #4753, clock selection algo doesn't support both HSE_ON and HSE_BYPASS configuration.
As HSE_ON is not available on default HW, we have removed the choice from the default SW configuration.
I have updated the ST wiki page according to this:
https://developer.mbed.org/teams/ST/wiki/Automatic-clock-configuration
Thx
READY
=> STM32 : Disable HSE XTAL choice from the default clock source

rtos/Thread.h
=> Doxygen comment fix for Thread class

rtos/TARGET_CORTEX/rtx5/TARGET_M33/TOOLCHAIN_ARM/irq_armv8mml.S, rtos/TARGET_CORTEX/rtx5/TARGET_M33/TOOLCHAIN_GCC/irq_armv8mml.S, rtos/TARGET_CORTEX/rtx5/TARGET_M33/TOOLCHAIN_IAR/irq_armv8mml.S
RTX5 context switcher files from RTX5 added to mbed-os code, Required to support ARMv8-Mainline architecture.
=> Cortex-M33: Add RTX5 context switcher files

hal/mbed_ticker_api.c, platform/mbed_retarget.cpp, platform/mbed_wait_api_no_rtos.c, platform/mbed_wait_api_rtos.cpp
Update platform code to use the ticker common layer rather than using HAL us ticker directly. This both ensures that the underlying ticker is properly initialized and that the value read is in microseconds with full 32-bit range.
=> Ensure us_ticker is initialized before it is used

targets/TARGET_NORDIC/TARGET_NRF5/gpio_api.c
The allocation of GPIOTE channels for DigitalIn is unwanted behavior.
This caused early run-out of GPIOTE channels for InterruptPin.
This patch replacing input configuration that is using gpiote driver by configuration that is
using gpio hal.
Fix for InterruptPin part of ct-test-shield test issue https://github.com/ARMmbed/mbed-os/issues/5133
=> Fix: DigitalIn of nRF5x was allocating GPIOTE channel

targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_rtc_ex.c
This corrects #5136 
Function from L4 family makes F7 works.
READY
| DISCO_F746NG-ARM      | DISCO_F746NG  | tests-mbed_drivers-lp_timeout | 1ms LowPowerTimeout                 | 1      | 0      | OK     | 0.05               |
| DISCO_F746NG-ARM      | DISCO_F746NG  | tests-mbed_drivers-lp_timeout | 1sec LowPowerTimeout                | 1      | 0      | OK     | 1.04               |
| DISCO_F746NG-ARM      | DISCO_F746NG  | tests-mbed_drivers-lp_timeout | 1sec LowPowerTimeout from deepsleep | 1      | 0      | OK     | 1.07               |
| DISCO_F746NG-ARM      | DISCO_F746NG  | tests-mbed_drivers-lp_timeout | 1sec LowPowerTimeout from sleep     | 1      | 0      | OK     | 1.06               |
| DISCO_F746NG-ARM      | DISCO_F746NG  | tests-mbed_drivers-lp_timeout | 500us …
=> STM32F7 : RTC Wake Up Timer issue

hal/sleep_api.h, platform/mbed_sleep.h, targets/TARGET_NXP/TARGET_LPC176X/sleep.c
This goes to feature-hal-spec branch, update to sleep API. This was previously part of sleep manager, but should come as separate patch that will require testing and further target updates.
Sleep - within 10us
Deepsleep - within 10ms
Note about mbed boards with interface, moved to lpc176x, as they are target related,
should be documented in the target documentation.
The tests will come as separate PR, to conform to this updates to sleep API.
cc @bulislaw @c1728p9
=> Sleep API update (branch feature-hal-spec-sleep)

TESTS/mbed_drivers/ticker/main.cpp, drivers/Timer.cpp
If a LowPowerTimer is started and then goes out of scope then a deep sleep lock underflow can occur. This is because the the variable '_lock_deepsleep' is checked when starting the timer but is not checked in the destructor, which unconditionally releases the deep sleep lock. This bug was introduced in #5148
=> Fix  LowPowerTimer and nightly builds

TESTS/mbed_drivers/sleep_lock/main.cpp, drivers/CAN.cpp, drivers/SerialBase.cpp, drivers/SerialBase.h, drivers/Ticker.h, platform/DeepSleepLock.h
Fix problems which could leave deep sleep locked unintentionally, along with adding tests to verify this behavior is fixed.
=> Fix deep sleep lock bugs

platform/mbed_toolchain.h, targets/TARGET_NXP/TARGET_LPC176X/device/CRP.c, targets/TARGET_NXP/TARGET_LPC176X/device/TOOLCHAIN_ARM_MICRO/LPC1768.sct, targets/TARGET_NXP/TARGET_LPC176X/device/TOOLCHAIN_ARM_MICRO/startup_LPC17xx.S, targets/TARGET_NXP/TARGET_LPC176X/device/TOOLCHAIN_ARM_STD/LPC1768.sct, targets/TARGET_NXP/TARGET_LPC176X/device/TOOLCHAIN_ARM_STD/startup_LPC17xx.S, targets/TARGET_NXP/TARGET_LPC176X/device/TOOLCHAIN_GCC_ARM/LPC1768.ld, targets/TARGET_NXP/TARGET_LPC176X/device/TOOLCHAIN_IAR/LPC17xx.icf, targets/TARGET_NXP/TARGET_LPC176X/device/TOOLCHAIN_IAR/startup_LPC17xx.S, targets/targets.json
Enable bootloaders for LPC1768 targets.
CRP word was being added to application builds which would overlap the bootloader and cause an sector erase inside the bootloader region.
Linker scripts have been updated.
**READY**
NO
=> Lpc1768 bootloader support

tools/detect_targets.py, tools/test/detect_targets_test.py, tools/test_api.py
This adds the additional information of the interface version (IE DAPlink, OpenSDA, etc) to the command `mbed detect`
This has proved useful when debugging applications, particularly when encountering interface issues. Not knowing about mbedls, I found it difficult to debug my application, where the USB driver and board was crashing when dragging the .bin to the disk for deployment in Windows 10. This information is a "nice to have" for a quick reference for mbed developers.
**Example output:**
```
...Desktop\mbed Workspace\mbed-os>mbed detect
[mbed] Detected K64F, port COM4, mounted D:, interface version 0243
[mbed] Supported toolchains for K64F
+--------+-----------+-----------+-----------+-----------+-----------+
| Target | mbed OS 2 | mbed OS 5 |    ARM    |  GCC_ARM  |    IAR    | …
```
=> Added interface version information to mbed detect command.

tools/export/iar/iar_definitions.json, tools/export/sw4stm32/__init__.py
NUCLEO_L486RG is not handled by tool scripts for exporters.
With this PR we can export and debug this target.
READY
=> Allow exporters for NUCLEO_L486RG

tools/export/gnuarmeclipse/__init__.py
Type: Bugfix
Resolves: #5186 
**Ready**
Hi, 
So this is a fix for #5186 tested on windows only. So can someone test this on the other systems mbed and the exporter is running.
cheers 
mathias
=> Add quotes to preprocessor path on export

platform/mbed_retarget.cpp
GCC's newlib library depends on fstat to get in-flight information about a file's type an size. A working fstat for regular files is needed for seek and related functions to work correctly.
Side note about testing this and https://github.com/ARMmbed/mbed-os/pull/5183, I have tests inbound, which is what's finding these bugs. They're currently targeting littlefs [here](https://github.com/ARMmbed/mbed-littlefs/tree/littlefs-test-conversion), but I will also bring them over the FAT filesystem once they're up and running.
=> fs: Fix fstat retarget for regular files

tools/test/examples/examples_lib.py
more info on https://github.com/ARMmbed/mbed-os/issues/5239
=> Add retry to handle git clone failure

platform/mbed_retarget.h
Currently code written for GCC may not work on ARM/IAR due to missing retarget definitions. This is manifested in littlefs/spiffs and may impact users.
- missing O_ flags
- missing S_IF flags
- missing system types
- missing stat structure
- exhaustive list of errno codes
These were missing and causing tests written against the filesystem to fail. Tests are inbound for a later pr. Currently these definitions are available in GCC, but missing in ARM/IAR. This patch fixes that.
Note: Yes there are a bunch of errno codes that we may never use, but that just means we won't have to worry about naming errors for a while now.
=> fs: Add missing retarget definitions for ARM/IAR

TESTS/mbed_drivers/ticker/main.cpp
In test_case_2x_callbacks two tickers are setup to repeatedly reschedule each other. When these tickers are deleted this rescheduling is still occurring and can lead to a deleted ticker being scheduled.
When this happens the following error message is displayed:
Thread 0x0 error -6: Not allowed in ISR context
Note - this problem was not detected by CI since the test reported the correct results back to the host test and only experienced this error on tear down.
This problem can be reproduced on an nrf51 by first building the ticker
test with:
```
> mbed test -t GCC_ARM -m NRF51_DK -n tests-mbed_drivers-ticker --compile -DMBED_TRAP_ERRORS_ENABLED=1 -DMBED_HEAP_STATS_ENABLED=1 -DMBED_STACK_STATS_ENABLED=1
```
And then running testing with:
```
> mbed test -t GCC_ARM -m NRF51_DK -n …
```
=> Prevent use of deleted ticker in Ticker test

hal/ticker_api.h
Fix an incorrect warning on the use of `ticker_insert_event_us` with a `timestamp` from the past. For reference look at:
* [`/hal/mbed_ticker_api.c`](https://github.com/ARMmbed/mbed-os/blob/5bddd881e98101f5c491cccf3367894ecb4e89dd/hal/mbed_ticker_api.c#L120)
* [`/TESTS/mbed_hal/ticker/main.cpp`](https://github.com/ARMmbed/mbed-os/blob/5bddd881e98101f5c491cccf3367894ecb4e89dd/TESTS/mbed_hal/ticker/main.cpp#L941)
**READY**
@bulislaw @0xc0170
=> Fix an incorrect comment in ticker API

targets/TARGET_STM/i2c_api.c
As reported by MBED user Fran6Jack:
I2C bus are usually 5V tolerant on all STM32 processor.
If an external device on the I2C bus requires 5V operation,
we usually acheive it by using 5V external pull-ups on the bus.
Since signaling uses open-drain output on I2C for both signal SCL and SDA
any 5V tolerant MCU will work on a 5V I2C bus. Having pull-up activated on a 5V externally pull bus, cause the pin to clamp on the STM32 die diode and could damage the IC (There is a note in STM32 datasheet specifying this issue).
It is understood by all the community that I2C bus should always be
externally pulled by physical resistor. I2C initialization should then
be ALWAYS OpenDrainNoPull by default.
Up to now, this I2C driver was setting pull up by default as it helps
basic testing, like 1 master …
=> STM: I2C: Configure pins in OpenDrainNoPull by default (no pullup)

TESTS/network/wifi/get_interface.cpp, TESTS/network/wifi/main.cpp, TESTS/network/wifi/template_mbed_app.txt, TESTS/network/wifi/wifi-constructor.cpp, TESTS/network/wifi/wifi_connect.cpp, TESTS/network/wifi/wifi_connect_disconnect_repeat.cpp, TESTS/network/wifi/wifi_connect_nocredentials.cpp, TESTS/network/wifi/wifi_connect_params_channel.cpp, TESTS/network/wifi/wifi_connect_params_channel_fail.cpp, TESTS/network/wifi/wifi_connect_params_null.cpp, TESTS/network/wifi/wifi_connect_params_valid_secure.cpp, TESTS/network/wifi/wifi_connect_params_valid_unsecure.cpp, TESTS/network/wifi/wifi_connect_secure.cpp, TESTS/network/wifi/wifi_connect_secure_fail.cpp, TESTS/network/wifi/wifi_get_rssi.cpp, TESTS/network/wifi/wifi_scan.cpp, TESTS/network/wifi/wifi_scan_null.cpp, TESTS/network/wifi/wifi_set_channel.cpp, TESTS/network/wifi/wifi_set_credential.cpp, TESTS/network/wifi/wifi_tests.h
Implement 100% function coverage for WifiInterface as specified
in "Wifi test plan"
Idea is to have full coverage of `WiFiInterface` API callbacks. Does not test any of the socket functionality, those will be provided later, perhaps within https://github.com/ARMmbed/mbed-os/pull/4795
Uses idea of separating the code which detects the interface into one singe file `get_interface.c` and its callback `get_interface()` which always gives a new initialised interface and destroys the previous one. Assumption is that destructor should clean up the driver state and constructor should bring it in sane condition. That allows us to write all test cases separately, everyone within their own file for easy maintain.
Verified in ESP8266, does not pass without fixing the driver. …
=> Implement functional Wifi tests

targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F439xI/TARGET_UBLOX_EVK_ODIN_W2/PeripheralNames.h, targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F439xI/TARGET_UBLOX_EVK_ODIN_W2/PinNames.h, targets/targets.json
Moved STDIO_UART defines to targets.json for UBLOX_EVK_ODIN_W2 instead of hardcoded.
The default UART(D2/D8) can be overriden in mbed_app.json like this to use UART_3 instead:
"UBLOX_EVK_ODIN_W2": {
"target.usb_tx": "D1",
"target.usb_rx": "D0",
"target.stdio_uart": "UART_3"
}
}
Should be reviewed and tested by @andrewc-arm to make sure it solves #5129
NO
https://github.com/ARMmbed/mbed-os/issues/5129
None
None
Have only run one test case to verify that it is still possible to run 'mbed test'.
=> Moved STDIO_UART defines for UBLOX_EVK_ODIN_W2

targets/TARGET_NORDIC/TARGET_NRF5/TARGET_MCU_NRF51822_UNIFIED/analogin_api.c
Previous the voltage range was ste to 1.2 v from SoC internal reference source.
This caused problem with testing. It is unexpected that range is much
shorter than vdd as well.
Fix for analog part of ct-test-shield test issue https://github.com/ARMmbed/mbed-os/issues/5133
=> Extend nRF51 AnalogIn voltage range to 3.6 V

targets/TARGET_STM/TARGET_STM32F1/analogin_api.c, targets/TARGET_STM/TARGET_STM32F3/analogin_api.c, targets/TARGET_STM/TARGET_STM32L4/analogin_api.c
Add ADC calibration in the initialization phase.
Tested with a basic analogin read example. Without the calibration the read value is not precise enough.
**READY**
NO
=> STM32: add ADC calibration for L4, F1, F3 devices

targets/TARGET_Realtek/mbed_rtx.h
Fix ARMC6 guard and cleanup mbed_rtx.h
READY
NO
NONE
NONE
NONE
NONE
=> RTL8195AM - Fix and cleanup mbed_rtx.h

features/FEATURE_BLE/ble/GattService.h
The constructor doc incorrectly suggested that only short (16-bit)
UUIDs were accepted. The same doc also referred to properties
instead of characteristics. (And to "value length", which seemed to
be completely out of place in the context of the current code.)
**READY**
NO
=> Fix documentation of BLE GattCharacteristic

TESTS/mbed_drivers/echo/main.cpp
1) if we receive more than one __sync, previous handshake would consider
it as echo_count and try to decode the value. Now we skip superfluous __sync.
2) reduce the uart load produced by the test, as we are heavily running tests in
parallel and not one-to-one this update was required.
=> Fix echo test handshake and reduce uart load

features/mbedtls/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F437xG/mbedtls_device.h, targets/targets.json
Enable crypto HW acceleration for STM43F437xG platforms, i.e. ublox C030 family boards.
`mbed-os-example-tls/benchmark/` before:
```
SHA-256                  :       2936 KB/s
SHA-512                  :        886 KB/s
AES-CBC-128              :       2315 KB/s
AES-CBC-192              :       2031 KB/s
AES-CBC-256              :       1810 KB/s
AES-GCM-128              :        708 KB/s
AES-GCM-192              :        679 KB/s
AES-GCM-256              :        652 KB/s
AES-CCM-128              :        957 KB/s
AES-CCM-192              :        857 KB/s
AES-CCM-256              :        776 KB/s
CTR_DRBG (NOPR)          :       1922 KB/s
CTR_DRBG (PR)            :       1361 KB/s
HMAC_DRBG SHA-256 (NOPR) :        337 KB/s
HMAC_DRBG SHA-256 (PR)   :        296 KB/s
RSA-2048 …
```
=> Enable crypto HW acceleration for STM32F437xG platforms

TESTS/mbedmicro-rtos-mbed/timer/main.cpp
Add unit tests for Timer class.
READY
NO
=> Add test for Timer class.

TESTS/mbed_hal/ticker/main.cpp, hal/lp_ticker_api.h, hal/mbed_lp_ticker_api.c, hal/mbed_ticker_api.c, hal/mbed_us_ticker_api.c, hal/ticker_api.h, hal/us_ticker_api.h, platform/mbed_retarget.cpp
Allow tickers to specify their native frequency and number of bits. This allows the conversion to happen in common code rather than in each vendor's implementation.
=> Update ticker to map closely to hardware

TESTS/mbed_drivers/lp_timeout/main.cpp, TESTS/mbed_hal/lp_ticker/main.cpp
Use sleep() as entry function + check to be certain we
are entering deepsleep when required by test (should be allowed as we use LowPower object).
This has dependency on fixing this issue https://github.com/ARMmbed/mbed-os/issues/5076 (the test now fails, and will be fixed as today).
Tested using K64F and GCC ARM , these 2 tests affected, one failure at the moment
@jeromecoutant
=> Test: deepsleep() API replacement

targets/TARGET_NORDIC/TARGET_NRF5/i2c_api.c
Change implementation of timeout to one that is using us_ticker hal.
Timeout is now configurable by I2C_TIMEOUT_VALUE_US macro and this
value will be imported if was defined externally.
Fix for : https://github.com/ARMmbed/mbed-os/issues/4826
=> nRFx: Use us ticker for I2C timeout

drivers/UARTSerial.cpp, drivers/UARTSerial.h, platform/mbed_poll.cpp
System's wait_ms() spins to achieve a precise delay - we don't want this.
Call Thread::wait directly.
This PR is partly for testing, and to initiate discussion. I would personally like to see wait_ms() changed, or an alternative call in mbed_wait_api() brought in to avoid the unwanted CPU-sapping spin.
=> Avoid wait_ms() spin

TESTS/mbed_drivers/lp_timer/main.cpp
Add test for Low Power Timer. This test is created based on regular Timer test.
READY
NO
=> Add Low Power Timer test.

targets/TARGET_Silicon_Labs/TARGET_EFM32/analogin_api.c
Fixes #5115.
`analogin_read_u16` returns a value in the range `0x0000 - 0xFFF0`
since the resolution of the ADC is 12 bits. However, in
`analogin_read` this value gets divided by `0xFFFF` assuming the range
is `0x0000-0xFFFF`. This causes a small error in the value returned by
`AnalogIn::read` for the EFM32 target.
=> Fix analogin scaling for EFM32 target

targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F446xE/TARGET_NUCLEO_F446RE/system_clock.c, targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F446xE/device/TOOLCHAIN_GCC_ARM/STM32F446XE.ld, targets/targets.json
This simply adds support for bootloader for STM32F446RE target (NUCLEO_446RE)
**READY**
NO
=> Add bootloaderd support to NUCLEO_F446RE target

tools/test/examples/examples.py, tools/test/examples/examples_lib.py
Allows custom build profiles to be passed to the example build script.
=> Add profile argument to mbed-os example build tools

features/FEATURE_LWIP/lwip-interface/lwipopts.h, features/FEATURE_LWIP/lwip-interface/mbed_lib.json
We currently set the lwIP pbuf pool size small - to 5 x 576-byte
buffers.
This is insufficient to hold a single DTLS handshake flight, so can
cause cloud client connections to fail. STM-based platforms are failing
handshake because of this. (K64F works because it doesn't use the pbuf
pool for reception, but lwIP does recommend drivers use the pbuf pool).
Not changing the default memory sizes here, as intended for a patch
release, but adding mbed configuration options to allow the numbers to
be adjusted for memory tuning in an application.
In a future minor revision, I would recommend increasing the default
PBUF_POOL_SIZE - we are well below lwIP's out-of-the-box default - and
offsetting by a reduction in MEM_SIZE for the drivers that don't use
PBUF_RAM.
=>   lwIP: Add memory configs to JSON

targets/TARGET_STM/TARGET_STM32F0/analogout_device.c, targets/TARGET_STM/TARGET_STM32F3/analogout_device.c, targets/TARGET_STM/TARGET_STM32F4/analogout_device.c, targets/TARGET_STM/TARGET_STM32F7/analogout_device.c, targets/TARGET_STM/TARGET_STM32L0/analogout_device.c, targets/TARGET_STM/TARGET_STM32L1/analogout_device.c, targets/TARGET_STM/TARGET_STM32L4/analogout_device.c
This is an extension of PR #5188 to all other STM32 platforms:
- initializes the sConfig structure to zero
- initializes the object handle State variable to its Reset value
Prevent a potential issue with tests-api-analogout with GCC_ARM 
**READY**
NO
#5188
=> STM32: Fix analogout structure/variable wrong initialization

rtos/TARGET_CORTEX/mbed_rtx_conf.h
The current mbed-os drivers rely on a tickrate of 1ms for timing. This means that if OS_TICK_FREQ is set to any value other than 1000 then mbed-os driver will no longer delay for the correct amount of time. To prevent this from happening this patch triggers a compile time error if a tickrate other than 1m is used.
=> Error if OS tickrate is changed

targets/TARGET_STM/rtc_api.c
- Initialize the structures at init phase to zero.
- Initialize the handle State variable to RESET state.
Solve ST internal RTC test on NUCLEO_F030R8 with GCC_ARM.
**READY**
NO
Structures initialization also done in PR #5188 and #5263
ST_INTERNAL_REF 36019
=> STM32: Initialize RTC structures at init phase.

targets/TARGET_STM/rtc_api.c
This is a FIX for #5159.
lp_ticker driver is the known registered user of RTC handler API.
In case, a lp_ticker is set in the past, the lp_ticker_fire_interrupt
will be called which itself sets the RTC interrupt as pending by calling
NVIC_SetPendingIRQ(RTC_WKUP_IRQn). This all happens without actual
programing of the RTC wake-up.
As a result the RTC HW and corresponding HAL layer doesn't expect an
interrupt to happen and will not call HAL_RTCEx_WakeUpTimerEventCallback.
To sove this situation, we will not use HAL_RTCEx_WakeUpTimerEventCallback
weak definition but rather call handler whenever an RTC interrupt fires.
Notes:
* …
=> STM32: RTC: Call irq_handler whenever interrupt fires

features/filesystem/bd/HeapBlockDevice.h
Small example in the HeapBlockDevice header file was not valid, added size parameters to program and read calls.
@geky Wasn't sure who was the best person to put on here was, figured you were closest to filesystem changes at the moment and last touched this file.  ¯/\_(ツ)_/¯ Feel free to change the reviewer to someone else.
=> Update HeapBlockDevice example

features/filesystem/bd/HeapBlockDevice.h
https://github.com/ARMmbed/Handbook/pull/287#issuecomment-337388320 brought up some ambiguity in the difference between the constructors in HeapBlockDevice. Added a small blurb to avoid having to go to the source to see what the difference is.
Does this sound more in line with what you were thinking for the block parameter description @sg-?
=> Add additional note on the HeapBlockDevice constructor block parameter

tools/toolchains/__init__.py
Should ignore nothing, currently ignores everything
An empty .mbedignore is easy to create when tinkering with a local repo
cc @marcuschangarm, @theotherjimmy
=> Fix behaviour of empty .mbedignore

TESTS/mbedmicro-rtos-mbed/basic/main.cpp
No functional changes only refactoring
**READY**
=> Basic test refactoring

targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_K66F/device/TOOLCHAIN_ARM_STD/MK66FN2M0xxx18.sct, targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_K66F/device/TOOLCHAIN_GCC_ARM/MK66FN2M0xxx18.ld, targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_K66F/device/TOOLCHAIN_IAR/MK66FN2M0xxx18.icf, targets/targets.json
Updates the linker files and configuration to enable flash in-application-programming and bootloader support on K66F.  This requires updates to the flash drivers for K66F, which are in a separate PR.  
Hold until https://github.com/ARMmbed/mbed-os/pull/4982 is merged.   
NO
https://github.com/ARMmbed/mbed-os/pull/4982
N/A
N/A
This was tested with https://github.com/ARMmbed/mbed-os-example-bootloader and was successful.  
cc @mmahadevan108
=> add flash iap and bootloader support to K66F

TESTS/mbedmicro-rtos-mbed/rtostimer/main.cpp, rtos/RtosTimer.h
RTOS `RtosTimer`:
* added unit tests,
* reworked API docs based on CMSIS-RTOS2 API docs.
**READY**
=> Rtostimer tests

tools/targets/REALTEK_RTL8195AM.py
Respect [GCC_ARM|ARM|IAR]_PATH from mbed_settings.py, for users might set path through that file instead of system path.
READY
NO
NONE
NONE
NONE
=> RTL8195AM - Respect Toolchains paths in post bulid script.

TESTS/mbedmicro-rtos-mbed/event_flags/main.cpp
New test suite for EventFlags class
**READY**
=> Extends test set for EventFlags class

targets/targets.json
The generic Flash support for L4 and L0 families is already there,
but was not activated by default on 2 recentely added boards:
DISCO_L475VG_IOT01A and DISCO_L072CZ_LRWAN1
This is done now.
**READY**
```
+-------------------------+---------------------+-----------------------------+--------+--------------------+-------------+
| target                  | platform_name       | test suite                  | result | elapsed_time (sec) | copy_method |
+-------------------------+---------------------+-----------------------------+--------+--------------------+-------------+
| DISCO_L475VG_IOT01A-ARM | DISCO_L475VG_IOT01A | tests-mbed_drivers-flashiap | OK     | 19.08              | default     |
| DISCO_L475VG_IOT01A-ARM | DISCO_L475VG_IOT01A | tests-mbed_hal-flash        | OK     | 18.91 …
```
=> Activate FLASH hal support on 2 STM32 boards

targets/TARGET_STM/trng_api.c
HAL_RNG_GetRandomNumber is a deprecated API and replaced here with a call to HAL_RNG_GenerateRandomNumber. Doing so, we also rework the driver to use the 4 bytes returned by a call to HAL_RNG_GenerateRandomNumber instead of 1 byte out of 4.
HAL_RNG_GenerateRandomNumber was not returning any error code, so now we can also check the return code.
A second commit ensures that there is a single user at a time. 
**READY**
```
+-----------------------+---------------+------------------------+--------+--------------------+-------------+
| target                | platform_name | test suite             | result | elapsed_time (sec) | copy_method |
+-----------------------+---------------+------------------------+--------+--------------------+-------------+
| NUCLEO_F091RC-ARM     | NUCLEO_F091RC | …
```
=> STM32: TRNG: remove call to deprecated HAL_RNG_GetRandomNumber

hal/lp_ticker_api.h, hal/mbed_lp_ticker_api.c, hal/mbed_us_ticker_api.c, hal/us_ticker_api.h
Add API to set IRQ handler for high frequency ticker and low power ticker.
This is done to be able to test HAL ticker API without using mbed upper layers to connect IRQ handler.
READY
YES
Add API to set IRQ handler for high frequency ticker and low power ticker.
Original IRQ handler is set as default ticker IRQ handler.
ARMmbed:feature-hal-spec-ticker | https://github.com/ARMmbed/mbed-os/pull/5233
=> Add API to set ticker IRQ handler.

targets/TARGET_STM/TARGET_STM32F2/analogout_device.c, targets/TARGET_STM/TARGET_STM32F2/objects.h
- Align the code with the STM32F0 devices.
- Add initialization of the `obj->handle.State variable` (this solves the tests-api-analogout GCC_ARM issue)
**READY**
NO
ST_INTERNAL_REF 36562
=> NUCLEO_F207ZG: Analogout improvement

tools/test/toolchains/arm_support_test.py, tools/toolchains/arm.py
Fixes #5266 when deployed to the online compiler
Fixes #5345
Also corrects offline compiling of uARM for every target that supports uARM but
not ARM.
TODO:
=> Tools: Check for toolchain and core support for Arm Compilers

targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/api/lp_ticker.c
Fix for Issue #5150 
Replacement for https://github.com/ARMmbed/mbed-os/pull/5314 (travis not active)
cc @mmahadevan108
=> MCUXpresso: Fix LPTimer issue when using multiple timeout objects

platform/FileSystemHandle.h
Was drivers, should be platform, wasn't updated during move
cc @sg-, @theotherjimmy
=> doxygen: Change FileSystemHandle group to platform

targets/TARGET_Realtek/TARGET_AMEBA/us_ticker.c
Switch to timer 2 for us_ticker for timer 6 might be used
for power saving.
Signed-off-by: Tony Wu <tonywu@realtek.com>
=> Fix us_ticker collision and race for RTL8195AM

features/FEATURE_LWIP/lwip-interface/lwip-eth/arch/TARGET_STM/stm32xx_emac.c, targets/TARGET_STM/TARGET_STM32F0/serial_device.c, targets/TARGET_STM/TARGET_STM32F1/serial_device.c, targets/TARGET_STM/TARGET_STM32F2/serial_device.c, targets/TARGET_STM/TARGET_STM32F3/serial_device.c, targets/TARGET_STM/TARGET_STM32F4/serial_device.c, targets/TARGET_STM/TARGET_STM32F7/serial_device.c, targets/TARGET_STM/TARGET_STM32L0/flash_api.c, targets/TARGET_STM/TARGET_STM32L0/serial_device.c, targets/TARGET_STM/TARGET_STM32L1/flash_api.c, targets/TARGET_STM/TARGET_STM32L1/serial_device.c, targets/TARGET_STM/TARGET_STM32L4/serial_device.c, targets/TARGET_STM/i2c_api.c
Remove compilation warnings due to unused variables, missing parenthesis and identical left/right operands.
**READY**
NO
=> STM32: Remove compilation warnings

TESTS/mbed_hal/lp_ticker_api_tests.h, TESTS/mbed_hal/ticker_api_tests.h, TESTS/mbed_hal/us_ticker_api_tests.h, hal/lp_ticker_api.h, hal/us_ticker_api.h
Add the Ticker HAL API specification along with the prototypes for tests which verify it.
=> Ticker specification (branch feature-hal-spec-ticker) 

TESTS/mbedmicro-rtos-mbed/MemoryPool/main.cpp
Add test for MemoryPool.
READY
No
=> Add MemoryPool test.

targets/TARGET_NXP/TARGET_LPC408X/TARGET_LPC4088/ethernet_api.c
LPC4088 ethernet_api build warning fixes to address https://github.com/ARMmbed/mbed-os/issues/5318
Looked like an issue with using a typedef on packed structs in the way it was originally written (https://stackoverflow.com/questions/12213866/is-attribute-packed-ignored-on-a-typedef-declaration).
Does this look reasonable? Tested on a locally exported blinky example for make_armc5. Saw the same warnings as the above issue before moving the PACKED attribute to the end of the struct declaration.
As a quick sanity check I ran the following with and without the PACKED attribute in the struct declaration to confirm the attribute was not silently dropped.
```c++
#define MBED_PACKED(struct) struct __attribute__((packed))
#define PACKED MBED_PACKED()
int main(void) {
struct test {
unsigned char a; …
```
=> Fix ethernet API build warnings for LPC4088

tools/test/examples/examples.json, tools/test/examples/update.py
All the examples cloned from Mercurial should use the new
os.mbed.com domain. Thus update corrects that.
A new option has been added to the update.py script , -s which shows
the status of any PRs raised against the examples that are tagged with
the current release label.
Add mbed-cloud-client-example-internal to examples list.
=> Improve domain handling and status checking of updated examples.

features/filesystem/bd/ChainingBlockDevice.cpp
Change address subtraction when moving through block devices to be the size of the entire block device not the block size.
=> ChainingBlockDevice: changing blocks address fix

TESTS/mbedmicro-rtos-mbed/mail/main.cpp
This test cause out of memory error ("Operator new[] out of memory") when run on NUCLEO_F070RB with GCC_ARM compiler
Thread stack was changed from 384B to 320B to reduce heap usage
**READY**
NO
=> mail test: fix out of memory problem for NUCLEO_F070RB

TESTS/mbedmicro-rtos-mbed/semaphore/main.cpp
This test cause out of memory error ("Operator new[] out of memory") when run on NUCLEO_F070RB with GCC_ARM compiler
Thread stack was changed from 512B to 320B to reduce heap usage
**READY**
NO
=> semaphore test: fix out of memory problem for NUCLEO_F070RB

features/filesystem/bd/SlicingBlockDevice.cpp, features/filesystem/bd/SlicingBlockDevice.h
Slightly simplifies the SlicingBlockDevice constructor setup. Example in the header still works correctly.
@geky
=> SlicingBD: replace second constructor with default parameter

TESTS/host_tests/rtc_reset.py, TESTS/mbed_hal/rtc/main.cpp, TESTS/mbed_hal/rtc/rtc_test.h, TESTS/mbed_hal/rtc_reset/main.cpp, TESTS/mbed_hal/rtc_reset/rtc_reset_test.h, hal/rtc_api.h, targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KL82Z/TARGET_USENSE/mbed_overrides.c, targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/api/rtc_api.c, targets/TARGET_STM/rtc_api.c, targets/TARGET_Silicon_Labs/TARGET_EFM32/rtc_api.c, targets/targets.json
Add the RTC HAL API specification along with tests which verify it.
=> RTC specification with test headers (branch feature-hal-spec-rtc)

tools/export/makefile/Makefile.tmpl
The build system does not do this, so this is a consistency fix
Found in #5359
=> Remove include from assember in makefile exporter

tools/export/iar/iar_definitions.json
Add IAR support for Toshiba TMPM066
**READY**
=> Added IAR export for TMPM066

TESTS/mbed_drivers/race_test/main.cpp
This test cause out of memory error ("Operator new[] out of memory") when run on NUCLEO_F070RB with GCC_ARM compiler
Since there is no need to place `Thread` objects on heap, it was moved from heap to main stack.
In the result more heap memory is available for test purpose and "out of memory" problem doesn't occur anymore
**READY**
NO
=> race test: fix out of memory problem for NUCLEO_F070RB

TESTS/mbed_drivers/lp_ticker/main.cpp
New test suite for LowPowerTicker class
**READY**
##Blocked 
#5185 fixedy by https://github.com/ARMmbed/mbed-os/pull/5347 (merged)
#5150 fixedy by https://github.com/ARMmbed/mbed-os/pull/5347 (merged)
=> Test set for LowPowerTicker class

drivers/UARTSerial.cpp, drivers/UARTSerial.h
Add passthrough APIs to enable the flow control and format methods from
SerialBase to be accessed.
Modify the RX data pump so it stops reading data and disables the IRQ
when the buffer is full, to allow UART automatic flow control to work.
In principle it would also be possible as a future enhancement to
provide XON/XOFF flow control, or manual RTS/CTS control using GPIO, but
this commit at least restores the functionality present in Serial,
SerialBase and RawSerial that was missing in UARTSerial.
Implements #4428
=> UARTSerial: add flow control and format APIs

platform/mbed_retarget.cpp
See https://github.com/ARMmbed/mbed-os/issues/5362
We should be reporting ENODEV when we resolve a path to no filesystem
cc @TeroJaasko, @kjbracey-arm
=> fs: Correct errno when not finding a mounted filesystem

TESTS/mbedmicro-rtos-mbed/malloc/main.cpp
This test cause out of memory error ("Operator new[] out of memory") when run on NUCLEO_F070RB with GCC_ARM compiler
Changes was introduced to reduce heap allocations
Now test threads uses static memory as a stack memory
**READY**
NO
=> malloc test: fix out of memory problem for NUCLEO_F070RB 

rtos/Thread.cpp
Ensure both the stack and stack size used in the Thread class are aligned to 8 bytes. This prevents the runtime error "Thread 0 error -11: Unknown" due to incorrect stack alignment.
=> Ensure Thread stack is 8 byte aligned

features/FEATURE_LWIP/lwip-interface/lwip-eth/arch/TARGET_STM/stm32xx_emac.c
This is a proposed fix to #5294
On STM32 F767 rev A devices ,Ethernet peripheral had problems on RMII
interface, on MII this was not the case.
This commits implements a tentative workaround for the issue rerfered to
as Ethernet erroneous data received in RMII configuration in the Errata
sheet below:
http://www.st.com/content/ccc/resource/technical/document/errata_sheet/group0/23/a6/11/0b/30/24/46/a5/DM00257543/files/DM00257543.pdf/jcr:content/translations/en.DM00257543.pdf
Note that the issue has been fixed in 'Z' revision. of STM32 F767 MCUs.
**READY**
```
+-----------------------+---------------+--------------------------------------------------------------+--------+--------------------+-------------+
| target                | platform_name | test suite …
```
=> STM32: Ethernet: Workaround for STM32_F767 revA

TESTS/mbedmicro-rtos-mbed/mail/main.cpp, TESTS/mbedmicro-rtos-mbed/queue/main.cpp, rtos/Mail.h, rtos/Queue.h
Functions to allow the user to know the state of the queue or mail
=> RTOS : added empty and full functions to Mail and Queue

drivers/InterruptManager.cpp, drivers/InterruptManager.h, platform/CallChain.cpp, platform/CallChain.h
Deprecate the CallChain and InterruptManager classes since these are dead code which is not part of mbed-os's public API.
=> Deprecate CallChain and InterruptManager

tools/test_configs/RealtekInterface.json, tools/test_configs/config_paths.json, tools/test_configs/target_configs.json
This change adds necessary configuration files to configure Wifi tests for Realtek Ameba board.
=> Add RealTek WiFi test configuration

targets/TARGET_ONSEMI/TARGET_NCS36510/i2c.h, targets/TARGET_ONSEMI/TARGET_NCS36510/i2c_api.c, targets/TARGET_ONSEMI/TARGET_NCS36510/ncs36510_i2c.c
Three main issues were found and corrected:
1) The 0x13 special case section in write data in ncs36510_i2c.c didn't have a write++ command.
2) In the same write function, the WDAT8 command was put before the 0x13 section and this is not correct
3) Needed to add wait_us(0) before and after the register writes for apparent clock domain crossing delay times until registers are stable in HW
There were also a handful of other tweaks related to general code maintenance and moving some status register checks to the proper locations.
This pull request addresses some I2C issues that were found by CI test shield and by a customer.  This pull request solves #5007 and #3511.
Fully tested by extensive ON Semiconductor tests based on CI test shield hardware as well as fully verified on CI test shield …
=> ONSEMI: Fix a few issues related to I2C

tools/test_configs/target_configs.json
Changing this to none as result of build failures. Wifi needs own configuration
per an enviroment. By setting this to none, net wifi tests are skipped for Realtek platform (skipped build, otherwise failures expected).
See https://github.com/ARMmbed/mbed-os/pull/5291 that enabled this. 
@SenRamakri @SeppoTakalo
Note for @adbridge @theotherjimmy We shall rerun CI prior the integration for changes that are at least a week older or more - to get uptodate results to avoid failures like this one (happens seldomly but happens)
=> test: realtek net config default  to none

targets/TARGET_Realtek/TARGET_AMEBA/flash_ext.h
The Realtek RTL8195AM has 2 MiB of external flash. This change
enables the FlashIAP driver to gain access to the full flash.
=> Increase flash size on Realtek RTL8195AM

features/FEATURE_LWIP/lwip-interface/lwip-eth/arch/TARGET_STM/stm32xx_emac.c
to all applicable devices part of F77x/F76x series.
This is an extension of #5411 and covers a comment that was done but could not be corrected in time before merge.
**READY**
Verified ok on DISCO_F769NI and NUCLEO_F767ZI
```
+-----------------------+---------------+--------------------------------------------------------------+--------+--------------------+-------------+
| target                | platform_name | test suite                                                   | result | elapsed_time (sec) | copy_method |
+-----------------------+---------------+--------------------------------------------------------------+--------+--------------------+-------------+
| DISCO_F769NI-ARM      | DISCO_F769NI  | features-feature_lwip-tests-mbedmicro-net-connectivity       | OK     | 35.51 …
```
=> STM32: Extend Ethernet RMII workaround

TESTS/mbedmicro-rtos-mbed/malloc/main.cpp
Suplement for #5338
- thread stack alignment was removed : the alignment isn't necessary with #5405."
- change stack array to two dimensional array 
**READY**
NO
https://github.com/ARMmbed/mbed-os/pull/5338
=> malloc test: change stack array to two dimensional array

TESTS/mbedmicro-rtos-mbed/rtostimer/main.cpp
The `RtosTimer` test suite needs a fix/workaround for **NRF51_DK** board. As pointed out in [this comment on #5323](https://github.com/ARMmbed/mbed-os/pull/5323#issuecomment-340061590) `tests-mbedmicro-rtos-mbed-rtostimer` failed during _ci-morph-test_ of a PR not related to `RtosTimer`. I'm unable to reproduce this behaviour on my NRF51_DK locally, but have found several failed _ci-morph-tests_:
* [build 151](http://mbed-ci-master-2.austin.arm.com:8081/job/test_matrix_raas/151/target=NRF51_DK,toolchain=IAR/testReport/junit/NRF51_DK-IAR/tests-mbedmicro-rtos-mbed-rtostimer/Test_restart_changes_timeout/),
* [build 154](http://mbed-ci-master-2.austin.arm.com:8081/job/test_matrix_raas/154/target=NRF51_DK,toolchain=GCC_ARM/testReport/junit/NRF51_DK-GCC_ARM/tests-mbedmicro-rtos-mbed-rtostimer/Te …
=> RtosTimer tests update

targets/targets.json
@MarceloSalazar Enabling mbed-cloud-client on DISCO_L475VG_IOT01A. tested internally
=> Add bootloader support for DISCO_L475VG_IOT01A

features/nanostack/FEATURE_NANOSTACK/targets/TARGET_SL_RAIL/NanostackRfPhyEfr32.cpp
This PR introduces a threaded wrapper for the SiliconLabs RAIL radio driver in [NanostackRfPhyEfr32.cpp](https://github.com/ARMmbed/mbed-os/compare/master...ryankurte:fix/nanostack-efr32-threading) resolving the issue raised in #5155.
**READY**
Tested on the EFR32FG target which will be the subject of another PR.
=> Fix for Nanostack threading on EFR32 devices

targets/TARGET_ONSEMI/TARGET_NCS36510/ncs36510_us_ticker_api.c
Use Timer1, it is used for us ticker isr handling. Plus reset target counter,
that should be 0, go to upper ticker isr handler immediately.
Found during #5307
cc @maciejbocianski @danclement @jacobjohnson-ON
=> ncs36510: fire interrupt correct timer fix

TESTS/events/queue/main.cpp
Reduce memory consumption to make it "passed" on  NUCLEO_F070RB + GCC_ARM compiler
**READY**
NO
=> event queue test: fix out of memory for NUCLEO_F070RB

events/equeue/equeue_mbed.cpp, events/mbed_lib.json
…use LowPowerTimer, LowPowerTimeout and LowPowerTicker instead of Timer/Timeout/Ticker.
This way, on SiLabs boards the low power sleep states will be used when using event queue.
=> equeue: add config option to use different timer classes

features/FEATURE_LWIP/lwip-interface/lwip-eth/arch/TARGET_NXP/lpc17_emac.c
Ethernet on LPC1768 is broken in 5.6 as per #5298
This corrects the placement of Ethernet memory with the ARM compiler.
**READY**
NO
branch | PR
Build the TCPSocket_Example with 5.5.7 and it will work, any 5.6\master will fail to get an IP, using static IP will still fail to work properly.
Fixes #5298
=> LPC1768: Fix ETHMEM_SECTION placement for ARM

features/FEATURE_LWIP/lwip-interface/lwip/src/core/lwip_tcp.c, features/FEATURE_LWIP/lwip-interface/lwip_stack.c
Addresses https://github.com/ARMmbed/mbed-os/issues/5318
Project built in exported projects (tested with make_armc5 in particular) or on the online compiler will generate a good amount of build warnings. These small fixes should resolve the LWIP warnings (and add error checking on ppp_lwip_disconnect calls).
=> Remove build warnings in LWIP

platform/CircularBuffer.h
This implementation returns the number of available (stored) transactions in the buffer. It was introduced to improve efficiency.
**READY**
=> CircularBuffer(): get available transactions

targets/targets.json
Mark HEXIWEAR target to support bootloader. Verified to work using mbed-client-testapp
READY
=> HEXIWEAR: define HEXIWEAR target to support bootloader.

targets/TARGET_NORDIC/TARGET_NRF5/TARGET_MCU_NRF52832/TARGET_RBLAB_BLENANO2/PinNames.h, targets/TARGET_NORDIC/TARGET_NRF5/TARGET_MCU_NRF52832/TARGET_RBLAB_BLENANO2/device.h, targets/targets.json
Cribbed from https://github.com/redbear/mbed-os/commit/4bf42f2e205e81ffb50a013b16c0366607bf8146
I'm not sure if if there are any copyright issues here with what is
effectively a set of config files. A few folks have been bugging me (and
the redbear folks) for these changes, so I wanted them somewhere
centralized.
=> Add support for RedBear's BLE Nano 2

TESTS/mbed_hal/rtc/main.cpp, TESTS/mbed_hal/rtc/rtc_test.h, TESTS/mbed_hal/rtc_reset/main.cpp, TESTS/mbed_hal/rtc_reset/rtc_reset_test.h, hal/rtc_api.h
This patch provides updates of artefacts provided in PR https://github.com/ARMmbed/mbed-os/pull/5226.
This patch provides the following updates:
- description of RTC HAL API tests in given/when/then format,
- minor fixes in existing test cases,
- additional test cases.
**READY**
NO
feature-hal-spec-rtc | https://github.com/ARMmbed/mbed-os/pull/5226
master | https://github.com/ARMmbed/mbed-os/pull/5363
Provided additional test case rtc_enabled_test() is in conflict with rtc_persist_test() test case. 
Documentation describes rtc_isenabled() function as follows:
> RTC has the time set and is counting
I assume that some test should be created for this function, but its behaviour is unclear. I understand this description as follows:
"RTC is counting" - RTC has been initialised by means of …
=> Update of RTC HAL API specification and tests.

targets/TARGET_Realtek/TARGET_AMEBA/flash_api.c
The Page size has been set to 1 byte instead of the previous 256.
Although 256 is the physical page size, the driver supports
writing 1 byte at a time.
=> Increase flash program granularity on Realtek RTL8195AM

targets/TARGET_Realtek/TARGET_AMEBA/ota_api.c, targets/TARGET_Realtek/TARGET_AMEBA/ota_api.h
Moved defines, typedefs and function prototypes from ota_api.c to
ota_api.h so that these can be included in applications.
=> Reorganize defines for firmware updates on Realtek RTL8195AM

TESTS/netsocket/socket_sigio/main.cpp
This fixes netsocket failure on arch pro target by limiting the size of EventQueue instance.
**READY**
Related to #5335 
@geky
=> Limit size of equeue for sigio netsocket test

hal/qspi_api.h
Destination branch: feature-qspi
Adding new QSPI HAL header file. This should help to use memory-maped devices
as memories, graphical displays.
The API consist of few functions, most important are read/write/write_command functions.
The command format is:
```
----------------------------------------------
| Instruction | Address | Alt | Dummy | Data |
----------------------------------------------
```
We define only synch API at the moment. This patch contains only a header file.
We will provide an implementation for a target.
@jeromecoutant @LMESTM @kl-cruz @stevew817 @mmahadevan108 @Archcady @TomoYamanaka @jessexm @jacobjohnson-ON please have a look, might be interested in this, any feedback welcome!
cc @maclobdell @screamerbg @MarceloSalazar @ashok-rao
=> feature-qspi: QSPI HAL addition

targets/TARGET_STM/TARGET_STM32F1/device/stm32f1xx_hal_smartcard.c, targets/TARGET_STM/TARGET_STM32F2/device/stm32f2xx_hal_smartcard.c, targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_smartcard.c
This is a follow-up of PR #5303. In order to avoid losing that was proposed in #5303 but that could not be merged as it is we are proposing this new PR. We are taking only the fix part, and leaving behind application related changes.
Proposal: close #5303 and use this PR instead. 
Re-casting with tmp the uint8_t* pData pointer to uint16_t* brings a
memory corruption and typically can corrupt the size parameter. This
is fixed with this commit.
STM32 Internal ticket reference : 39116
=> STM32: HAL smartcard, fix memory corruption in Receive

tools/test/examples/examples.json
All examples should be public repositories. 
mbed-cloud-client-example-internal is not and thus needs to be removed.
=> Remove mbed-cloud-client-example-internal.

targets/TARGET_STM/TARGET_STM32F0/can_device.h, targets/TARGET_STM/TARGET_STM32F1/can_device.h, targets/TARGET_STM/TARGET_STM32F2/can_device.h, targets/TARGET_STM/TARGET_STM32F3/can_device.h, targets/TARGET_STM/TARGET_STM32F4/can_device.h, targets/TARGET_STM/TARGET_STM32F7/can_device.h, targets/TARGET_STM/TARGET_STM32L4/can_device.h, targets/TARGET_STM/can_api.c
Add support of CAN3. Previously only CAN1 and CAN2 were supported.
Tested OK with a TX/RX loop program using a NUCLEO_F767ZI (CAN_RX) and NUCLEO_F446RE (CAN_TX).
Fix issue #5484 
**READY**
NO
=> STM32: Add support of CAN3

targets/TARGET_NORDIC/TARGET_NRF5/gpio_api.c
For api usage like DigitalOut led(LED1, 1) the hal function gpio_write()
sets the output before f. gpio_mode() is called. gpio_mode() clears the
output as it take never writen parameters (gpio_cfg_t.init_hight).
This patch use internal hardware register of GPIO output instedad of above paramiter latch
for retaining proper writen state.
Fix for https://github.com/ARMmbed/mbed-os/issues/5462#issuecomment-343127875
=> Fix bug for issue:  initial pin value not retained

targets/TARGET_STM/TARGET_STM32L0/TARGET_DISCO_L072CZ_LRWAN1/device/system_clock.c, targets/targets.json
- Align the SetSysClock_PLL_HSE function with SetSysClock_PLL_HSI
- Minor change concerning the MCO pin output used for debug
- Add a comment in target.json for the HSE clock configuration
**READY**
NO
=> DISCO_L072CZ_LRWAN1: HSE clock configuration improvement

targets/TARGET_ONSEMI/TARGET_NCS36510/i2c.h, targets/TARGET_ONSEMI/TARGET_NCS36510/i2c_api.c, targets/TARGET_ONSEMI/TARGET_NCS36510/ncs36510_i2c.c
Same as https://github.com/ARMmbed/mbed-os/pull/5394, but this time the right destination branch
@adbridge
=> ONSEMI: Fix I2C issues

TESTS/mbed_drivers/lp_timer/main.cpp, TESTS/mbed_drivers/timer/main.cpp, TESTS/mbedmicro-rtos-mbed/timer/main.cpp
- LowPoterTimer test gives sometimes failed result while testing measured time accumulation. The check which verifies if total number of elapsed milliseconds is valid fails. Test assumes that delta value equal to 1 ms is sufficient for all test cases, which is not true since in case where time measurement is performed few times in sequence the measurement error also accumulates and 1 ms might be not enough. To solve this problem delta value for milliseconds tests must be updated.
- Since Timer test location is invalid it has been moved to more suitable location: TESTS/mbed_drivers/. Additionally fixed invalid comments and used more suitable ASERT macros.
- Provide fix for Issue https://github.com/ARMmbed/mbed-os/issues/5468. Increased DELTA value.
READY
NO
=> Provide fixes for Timer and LowPowerTimer tests.

tools/test_api.py, tools/test_configs/__init__.py, tools/test_configs/target_configs.json
This change fixes a bug with @sarahmarshy's configurable network driver tests. These tests can be invoked with an existing interface inside mbed OS or a new NSAPI implementation via:
`mbed test -m [MCU] -t gcc_arm -n mbed-os-tests-netsocket* --test-config ethernet`
or
`mbed test -m [MCU] -t gcc_arm -n mbed-os-tests-netsocket* --test-config path\to\config\file`
Bug fixed allows for any board with LWIP (not just K64F or Odin) to run mbed OS network tests. Also fixed a comment that describes what the `get_test_config` function returns.
Edit:
Also, `mbed test -m [MCU] -t gcc_arm -n mbed-os-tests-netsocket*` will by default choose the Ethernet interface for any target with LWIP.
branch | PR
mbed-os/master | [Add configurable network driver tests …
=> Fix for configurable network driver tests

TESTS/mbedmicro-rtos-mbed/signals/main.cpp
New test suite for Thread signals
**READY**
=> Extends test set for Thread signals

features/FEATURE_LWIP/lwip-interface/lwip_stack.c, features/netsocket/Socket.cpp, features/netsocket/Socket.h, features/netsocket/TCPSocket.h, features/netsocket/UDPSocket.cpp, features/netsocket/nsapi_types.h
Continuation of initial pull request that only added IPv4 support. Extensive rework largely took place in lwip_stack.c to add IPv4/IPv6 logic.
Tested by enabling IPv6 in mbed_lib and mbed_app.json using the following test script on two K64Fs hooked up to a common router, one acting as a broadcast node and the other as a receiver.
```c++
#include "EthernetInterface.h"
const char* MCAST_GRP = "FF02::1";
//const char* MCAST_GRP = "229.0.0.1";
const int MCAST_PORT = 5007;
#ifdef SEND
int main() {
DigitalOut led(LED2);
EthernetInterface eth;
eth.connect();
UDPSocket sock;
sock.open(&eth);
SocketAddress multicast_group;
multicast_group.set_ip_address(MCAST_GRP);
multicast_group.set_port(MCAST_PORT);
char out_buffer[] = "very important data";
while (true) {
printf("Multicast to …
```
=> Add IPv4 and IPv6 multicast implementation for UDPSocket

features/filesystem/fat/FATFileSystem.cpp
Working implementations of dir_rewind and dir_seek are provided for FATFileSystem,
I believe that this fixes #5440 and obviates the need for API changes proposed in #5441.
**READY**
NO
=> FATFileSystem: provide working dir_rewind and dir_seek

targets/TARGET_STM/TARGET_STM32L0/TARGET_DISCO_L072CZ_LRWAN1/device/TOOLCHAIN_ARM_MICRO/stm32l072xz.sct, targets/TARGET_STM/TARGET_STM32L0/TARGET_DISCO_L072CZ_LRWAN1/device/TOOLCHAIN_ARM_STD/stm32l072xz.sct, targets/targets.json
DISCO_L072CZ_LRWAN1 can use LSE from LORA module
**READY**
+-------------------------+---------------------+-------------------------+----------------------------------+--------+--------+--------+--------------------+
| target                  | platform_name       | test suite              | test case                        | passed | failed | result | elapsed_time (sec) |
+-------------------------+---------------------+-------------------------+----------------------------------+--------+--------+--------+--------------------+
| DISCO_L072CZ_LRWAN1-ARM | DISCO_L072CZ_LRWAN1 | tests-mbed_drivers-rtc  | RTC strftime                     | 1      | 0      | OK     | 10.93              |
| DISCO_L072CZ_LRWAN1-ARM | DISCO_L072CZ_LRWAN1 | tests-mbed_hal-rtc_time | mk time …
=>  DISCO_L072CZ_LRWAN1 can use LSE from LORA module

TESTS/mbedmicro-rtos-mbed/malloc/main.cpp
Test refactoring
Few test added: malloc(0), free(NULL), malloc(large size)
**READY**
=> malloc test refactoring

TESTS/mbedmicro-rtos-mbed/heap_and_stack/main.cpp
Test refactoring and alignment to coding standards
Added test for main stack
**READY**
NO
=> heap_and_stack test refactoring

targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/api/analogin_api.c
Fix #5304 according to [UM10912.pdf](https://www.nxp.com/docs/en/user-guide/UM10912.pdf) (Chapter 44.3)
Ready
=> lpc546xx: fix adc

features/unsupported/USBDevice/targets/TARGET_STM/USBHAL_IP_OTGFSHS.h, features/unsupported/USBDevice/targets/TARGET_STM/USBHAL_STM32.h, targets/targets.json
Add support of USB Device on the DISCO_F429ZI board.
Tested OK with USB_1 test.
**READY**
NO
=> STM32: Add USB Device on DISCO_F429ZI

platform/mbed_retarget.cpp
Setting errno (part of thread local storage) caused hardfault with IAR8.x versions. TLS is not supported, hence using main thread TLS area for all threads.
=> Fixed: errno update failure with IAR8.x

platform/mbed_retarget.cpp, platform/mbed_retarget.h
Remove the condition code around the defines in mbed_retarget.h so all toolchains use the defined values. Exclude a small subset of values for GCC since these are in its standard header files.
=> Use retarget defines where possible

targets/TARGET_STM/TARGET_STM32L4/serial_device.c, targets/targets.json
In targets.json there is no SERIAL_ASYNC defined for the NUCLEO_L432KC developer board.
When adding this option, a bug in targets/TARGET_STM/TARGET_STM32L4 was encountered which was leading to compile errors.
=> NUCLEO_L432KC: Fixed async serial

tools/build_api.py
If map file parsing fails then memap_instance is set to None. To prevent a traceback when parsing fails check if this is None before trying to access any of its fields.
=> Prevent traceback when memap fails to parse

targets/TARGET_NUVOTON/TARGET_M480/lp_ticker.c, targets/TARGET_NUVOTON/TARGET_M480/us_ticker.c
See #5366 for all the approval and details
=> Nuvoton: fix lpticker interrupt

targets/TARGET_NUVOTON/TARGET_M480/trng_api.c, targets/TARGET_NUVOTON/TARGET_NUC472/trng_api.c
This PR refines code with TRNG_Get, to let TRNG_Get() support 32 bytes unalignment on NUC472/M487 platforms.
#5434
#5449 
Passed Mbed Cloud-Client-restricted(R1.2.4-LA) OTA test.
@0xc0170 
@Ronny-Liu 
@ccli8 
@samchuarm
=> Nuvoton: TRNG_Get support 32 bytes unalignment

drivers/UARTSerial.cpp, drivers/UARTSerial.h, features/netsocket/TCPSocket.cpp, features/netsocket/TCPSocket.h, platform/FileHandle.h
FileHandle and TCPSocket both have POSIX-like write calls. Both of them only ever write as much as currently fits into the buffer or underlying stack in one go.
It would be advantageous if we were to follow the spirit of POSIX a bit more closely and make those write calls write everything when in blocking mode - POSIX does try to write everything when blocking, and only returns early if interrupted by a signal.
As we don't have signals, we can guarantee to always write everything when blocking (if no errors), and this could make callers' lives easier.
First commit here updates TCPSocket for testing. A commit for UARTSerial.cpp and FileHandle.h will follow.
See commit message for the TCPSocket for more excruciating detail and POSIX spec quotes.
=> Make POSIX-like writes write everything when blocking

rtos/TARGET_CORTEX/mbed_boot.c, rtos/TARGET_CORTEX/rtx5/RTX/Source/rtx_lib.c
armcc fopen allocated a mutex using the retargeted system-level _mutex_initialize function. Interestingly, malloc also uses this same _mutex_initialization function, which prevents a full solution relying on malloc. The solution previously implemented involved using the rtx mutex pool for the first 8 mutexes, then falling back on malloc.
The previous implementation relied on osMutexNew returning an error on out-of-memory. An unrelated change causes osMutexNew to instead assert (except for release mode). This meant if you exceed 8 system- level mutexes in armcc you will hit an assert. Since the filesystem code can call fopen an unlimited number of times, this is a problem.
Solution is to keep track of which static mutexes we've allocated, so we know before calling osMutexNew if we need to …
=> Fixed mutex assert in armcc fopen and related memory leak

platform/mbed_retarget.cpp
free() checks for NULL, no need to add another check.
Micro-optimisation tweak - not for patch.
=> Remove pointless null check in operator delete

targets/targets.json
Support bootloader for DISCO_F429ZI
It's tested using following environment.
- ARMmbed/mbed-cloud-client-example-internal with esp8266.
- mbed-cloud-sdk-javascript-quickstart
https://github.com/ARMmbed/mbed-cloud-client-example-internal/pull/209
https://github.com/ARMmbed/mbed-bootloader-internal/pull/72
https://github.com/ARMmbed/sd-driver/pull/73
=> Support bootloader for DISCO_F429ZI

targets/TARGET_Realtek/TARGET_AMEBA/TARGET_RTL8195A/PinNames.h
Based on the Mbed OS website the A3 is connected to "DAC", however there
is no define for DAC. In order to get the Realtek RTL8195AM to even compile
with mbed-os-example-client now, we must have the A3 defined - it is one of
the standard Arduino header pins. Therefore, setting it as NC.
Realtek will hopefully push a proper fix sooner or later, if there is a
more meaningful define for the A3 pin. They do state however that the
A0-A3 pins are not GPIO capable anyway.
Ref: https://os.mbed.com/platforms/Realtek-RTL8195AM/
Notes:
- This is just a template, so feel free to use/remove the unnecessary things
**READY**
With the caveat …
=> Realtek RTL8195AM A3 fix

platform/mbed_critical.c, platform/mbed_critical.h
The LDREX/STREX implementations of the compare-and-swap functions were
weak (they could spuriously fail when the value was expected), whereas
the critial section implementation was strong, and the documentation has
no suggestion that there might be spurious failures.
Rationalise by adding a retry loop for STREX failure, so that it only
returns false when the value is not expected.
Fixes https://github.com/ARMmbed/mbed-os/issues/5556
=> Make LDREX/STREX CAS functions strong

targets/TARGET_Silicon_Labs/TARGET_EFM32/us_ticker.c
The us_timer code was written based on MHz integer multiple HF clock frequencies, in order to optimize away some long division instructions. EFR32 doesn't conform to that (38.4), and so the timestamp ticks were off by 1%. Enough to trip up some CI tests on TB_SENSE_12 (resolves #5496)
**READY**
=> Fix issue with timer timebase on EFR32

features/unsupported/USBDevice/targets/TARGET_STM/USBHAL_IP_OTGFSHS.h, targets/targets.json
Add a new `usb_speed` configuration in targets.json in order to select between the FS or HS USB connectors present on the board.
**READY**
NO
=> DISCO_F746NG: add usp_speed configuration

targets/TARGET_STM/stm_spi_api.c
This patch handles the case of SPI slave mode without MISO (NC).
In case MISO is not connected, we consider that SPI will be configured in
3 wires mode (CLK / MOSI / CS, but no MISO). In this case, the MOSI line
is bi-directional : SPI_DIRECTION_1LINE.
But as this is not supported yet in slave mode, we force it to
SPI_DIRECTION_2LINES. In this case slave SPI will receive data on MOSI
but nothing will be sent back to master as MISO is not connected.
This FIX addresses the issue reported in: #5554
=> STM32: SPI 3 wires mode not supported in SPI slave

targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K64F/trng_api.c
K64F `trng_get_byte` function assumed memory for byte was zero initialized. 
That means that [this line](https://github.com/sarahmarshy/mbed-os/blob/cefcb8cff31662553015da0dd32fc404ee623ec1/targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K64F/trng_api.c#L60) would OR random data with data existing in memory. All values will eventually reach 255 if called many times.
Use this test program to replicate the issue:
```c++
#define RANDOM_BUFF_SIZE 3                                                           /**< Random numbers buffer size. */
#include "hal/trng_api.h"
int main(void)
{
uint32_t err_code;
while (true)
{
trng_t trng_obj;
trng_init(&trng_obj);
uint8_t p_buff[RANDOM_BUFF_SIZE];
size_t output_length;
uint8_t length = trng_get_bytes(&trng_obj, p_buff, …
```
=> Fix bug in K64F trng_api.c

drivers/QSPI.cpp, drivers/QSPI.h, hal/qspi_api.h
Some clean-up, the most important is setting the address size to none if address phase is skipped, this allowed me to get disco f469ni communicate with a memory device at least to get register read ! 😄  This however shows that setting address size or value is not ideal, and we should review my proposition for having disabled flag to be more clear how to enable/disable a format phase.
The rest is just style changes, I'll carry on with testing.
=> Feature QSPI: fixes for driver

drivers/QSPI.cpp, drivers/QSPI.h, hal/qspi_api.h
To be able to skip any phase in the format, use bus width set to NONE. Previously this
was done via SIZE definitions, this however did not provide flexibility to skip instruction phase
or data (as all of them can be done via 0-4 lines).
This way any format phase can be skipped if bus width is set to NONE.
@SenRamakri Please review
=> Feature QSPI: add disabled flag to format phases

tools/build_api.py, tools/options.py
Resolves https://github.com/ARMmbed/mbed-os-example-blinky/issues/99
=> Update Cortex-A build errors

targets/TARGET_STM/can_api.c
- Bug fix
- Target STM32, Peripheral CAN
The RTR bit that defines the type of CAN message (Data or Remote) was written as bit0 in CAN_TIxR (the CAN TX mailbox).
According to [Reference Manual](http://www.st.com/content/ccc/resource/technical/document/reference_manual/02/35/09/0c/4f/f7/40/03/DM00083560.pdf/files/DM00083560.pdf/jcr:content/translations/en.DM00083560.pdf) p. 1606 of STM32L476RG, also verified for STM32F103, STM32F302 (seems to be the same for all STM32 offering CAN: 
Bit 0 **TXRQ**: Transmit mailbox request
Set by software to request the transmission for the corresponding mailbox.
Cleared by hardware when the mailbox becomes emp
Bit 1 **RTR**: Remote transmission request
0: Data frame
1: Remote frame
The RTR bit has been shifted by 1 to the left in order to put it in the …
=> STM32 - CAN - Fix RTR position bit in TX mailbox register

rtos/TARGET_CORTEX/mbed_rtx_idle.cpp
Remove unnecessary inclusion of `rtx_core_cm.h` from `mbed_rtx_idle.cpp`.
**READY**
=> Remove unnecessary inclusion of an internal RTX header

targets/TARGET_Realtek/TARGET_AMEBA/RTWInterface.cpp
Adds checks that SSID is non-empty and that password is 8-63 characters
long when security is enabled
Enables checking of SSID and password validity when set_credentials() is called
**READY**
NO
...\mbed-os> mbed test --compile -t ARM -m REALTEK_RTL8195AM --app-config .\TESTS\network\wifi\template_mbed_app.txt -n tests-network-wifi
...\mbed-os> mbedhtrun -f .\BUILD\tests\REALTEK_RTL8195AM\ARM\TESTS\network\wifi\wifi.bin -d X: -p COMY:9600
=> REALTEK_RTL8195AM Wifi driver - adds check of credentials validity

TESTS/netsocket/gethostbyname/main.cpp, TESTS/netsocket/socket_sigio/main.cpp, TESTS/netsocket/tcp_echo/main.cpp, TESTS/netsocket/tcp_hello_world/main.cpp, TESTS/netsocket/udp_echo/main.cpp
Some tests have been updated:
tests-netsocket-gethostbyname:
-	MBED_DNS_TEST_HOST define is replaced by MBED_CONF_APP_DNS_TEST_HOST to allow user to change host name for local tests
tests-netsocket-udp_echo:
-	UUID lines are removed as they were not used
-	If MBED_CONF_APP_ECHO_SERVER_ADDR and MBED_CONF_APP_ECHO_SERVER_PORT are not defined (default case), test is using Greentea to get server information (code before OS 5.6.1 version)
tests-netsocket-tcp_echo:
-	UUID lines are removed as they were not used
-	If MBED_CONF_APP_ECHO_SERVER_ADDR and MBED_CONF_APP_ECHO_SERVER_PORT are not defined (default case), test is using Greentea to get server information (code before OS 5.6.1 version)
-	TCP_ECHO_PREFIX is no more a mandatory feature
tests-netsocket-tcp_hello_world:
-	HTTP_SERVER_NAME and …
=> Ethernet tests update

features/unsupported/USBDevice/targets/TARGET_STM/USBHAL_IP_OTGFSHS.h, features/unsupported/USBDevice/targets/TARGET_STM/USBHAL_STM32.h
Add support of USB Device on DISCO_F413ZH platform.
Tested OK with USB_1 test.
**READY**
NO
=> STM32: Add USB Device on DISCO_F413ZH

tools/export/cmsis/__init__.py
They referred to PDSC files before
At least a partial resolution to #5467
@rspelta @MarceloSalazar dose this resolve the error on import for you?
If so, does this correctly select the flash algorithm for you?
=> Correct pack_* members to refer to PACK files

features/frameworks/unity/unity/unity.h
It is useful to get some information about FAIL tests.
This define adds the float support in the error prints
Ex before:
[1510238846.92][CONN][RXD] :316::FAIL: Values Not Within Delta
With the patch:
[1510238777.90][CONN][RXD] :316::FAIL: Expected 1.000000 Was 0.999424
Thx
**READY**
=> Unity framework : add float support in error print

targets/TARGET_STM/lp_ticker.c, targets/TARGET_STM/rtc_api.c, targets/TARGET_STM/rtc_api_hal.h, targets/TARGET_STM/sleep.c, targets/targets.json
Updates done after several internal tests.
**READY**
RTC and LPT tests have been checked for all STM32 families
#5106 updates have also been verified
=> STM32 Low Power Timer feature updates

TESTS/host_tests/rtc_calc_auto.py, TESTS/mbed_hal/rtc_time/main.cpp, TESTS/mbed_hal/rtc_time_conv/main.cpp, platform/mbed_mktime.c, platform/mbed_mktime.h, targets/TARGET_Atmel/TARGET_SAM_CortexM4/rtc_api.c, targets/TARGET_NUVOTON/TARGET_M451/rtc_api.c, targets/TARGET_NUVOTON/TARGET_M480/rtc_api.c, targets/TARGET_NUVOTON/TARGET_NANO100/rtc_api.c, targets/TARGET_NUVOTON/TARGET_NUC472/rtc_api.c, targets/TARGET_NXP/TARGET_LPC176X/rtc_api.c, targets/TARGET_NXP/TARGET_LPC408X/rtc_api.c, targets/TARGET_NXP/TARGET_LPC43XX/rtc_api.c, targets/TARGET_RENESAS/TARGET_RZ_A1H/rtc_api.c, targets/TARGET_RENESAS/TARGET_VK_RZ_A1H/rtc_api.c, targets/TARGET_STM/rtc_api.c
Add support for extended RTC.
Add tests for extended RTC.
Provide support to use whole 32-bit range (unsigned int) to hold time since UNIX epoch.
The supported time range is now from the 1st of January 1970 at 00:00:00 to the 7th of February 2106 at 06:28:15.
Add support for two types of RTC devices:
- RTCs which handles all leap years in the mentioned year range correctly. Leap year is determined by checking if the year counter value is divisible by 400, 100, and 4.
- RTCs which handles leap years correctly up to 2100. The RTC does a simple bit comparison to see if the two lowest order bits of the year counter are zero. In this case 2100 year will be considered incorrectly as a leap year, so the last valid point in time will be 28.02.2100 23:59:59 and next day will be 29.02.2100 …
=> Add support and tests for extended RTC

.travis.yml
Significantly reduces the overhead we have on spinning up Travis jobs, which was mostly spent downloading gcc-arm-embedded. Cuts the cost of the smaller jobs in half.
Before:
After:
The most useful thing to us is it reduces how long it takes to debug issues with Travis.
cc @bridadan, @0xc0170, @theotherjimmy
=> Add caching of apt-get + pip to .travis.yml

targets/TARGET_STM/TARGET_STM32F4/can_device.h, targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F769xI/TARGET_DISCO_F769NI/PeripheralNames.h, targets/TARGET_STM/TARGET_STM32F7/can_device.h, targets/TARGET_STM/can_api.c
This fixes CAN3 for STM32 platforms. Checked with two NUCLEO-F413ZH boards (added in https://github.com/ARMmbed/mbed-os/pull/5608).
I was not able to receive any data on STM32F413ZH. It was because the filter number 14 is not in the valid range for CAN3.
This restriction also holds for STM32F767ZI (checked in both RM0430 for STM32F413 and RM0410 for STM32F767), which has been originally used to test CAN3 in https://github.com/ARMmbed/mbed-os/pull/5486.
Also, this PR sets correct indexes for interrupt handlers.
=> STM32: Fix CAN3

tools/export/e2studio/__init__.py
The update to the e2studio exporter in 2cbca704d8 was inconsistent about
it's naming of the "jinja context creation" function. This pull request
resolves that naming problem.
When deployed to the website, #5612 is resolved
=> Correct typo? in e2studio exporter code

TESTS/mbed_platform/SingletonPtr/main.cpp
Add tests for SingletonPtr
**READY**
NO
=> Add SingletonPtr test

TESTS/mbed_drivers/race_test/main.cpp, platform/mbed_retarget.cpp
Implement the functions __cxa_guard_acquire, __cxa_guard_release and __cxa_guard_abort for ARMCC so local static object construction is thread safe. Also update the race test to properly detect this bug.
=> Protect local static object construction in ARMCC

features/FEATURE_BLE/ble/BLE.h, features/FEATURE_BLE/source/BLE.cpp
To avoid duplication in applications and help developers this provides them with printable strings for ble error codes.
**READY**
NO
=> BLE: added function converting error codes into strings

tools/export/GettingStarted.html
@AnotherButler  please review 
Reported https://github.com/ARMmbed/mbed-os-example-blinky/issues/105
=> Export: fix link in gettingstarted template

features/nanostack/FEATURE_NANOSTACK/coap-service/source/coap_message_handler.c, features/nanostack/FEATURE_NANOSTACK/coap-service/source/coap_service_api.c, features/nanostack/FEATURE_NANOSTACK/coap-service/source/include/coap_security_handler.h, features/nanostack/FEATURE_NANOSTACK/mbed-mesh-api/mbed_lib.json
1. Fix IAR compilation error: https://github.com/ARMmbed/mbed-os-example-mesh-minimal/issues/155
2. Update Thread PSKd default value to be uppercase characters like described in specification.
**READY**
=> Mesh fix for mbed os 5.7 oob

features/FEATURE_LWIP/lwip-interface/lwip-eth/arch/TARGET_Freescale/k64f_emac.c
Added a work around to lwip k64f ethernet Ipv6 multicast groups handling.
This is a work around for problem described in:
https://github.com/ARMmbed/mbed-os/issues/4372
READY
NO
None
None
None
=> Fixed lwip k64f ethernet driver ipv6 multicast groups

.travis.yml, tools/build_travis.py
Use matrix for our targets, to get smaller jobs that can run in parallel.
=> Travis: define matrix builds for mbed 2 jobs

rtos/TARGET_CORTEX/mbed_boot.c, rtos/TARGET_CORTEX/mbed_rtx_conf.h
This is fix for - https://github.com/ARMmbed/mbed-os/issues/5664
Previously we used OS_MUTEX_NUM define to pre-allocate Mutex objects for ARMCC libs. But that doesn't guarantee that they will be avaliable for ARMCC usage always as any other client can grab them before ARMCC lib requires that to be used/initialized. This change is to statically allocate memory for Mutex objects for ARMCC to ensure ARMCC have them when it needs.
=> Statically allocate ARMCC required mutex objects

tools/detect_targets.py, tools/test/detect_targets_test.py
Fixed detect_targets.py to use mbedls_tools.list_mbeds() per deprecation message on get_details_txt and updated associated detect_targets_test.py tests.
Use the command 'mbed detect' from Mbed CLI
https://github.com/ARMmbed/mbed-os/issues/5712
=> Fixed call to deprecated get_details_txt

tools/export/iar/iar_definitions.json
The `mbed export -i IAR -m DISCO_L475VG_IOT01A` command is failing.
With this PR, it is supported.
**READY**
NO
before:
`mbed export -i IAR -m DISCO_L475VG_IOT01A` gives
```
project.py: error: DISCO_L475VG_IOT01A not supported by iar
[mbed] ERROR: "c:\python27\python.exe" returned error code 2.
```
after:
it works
=> Add IAR exporter for STM32L475VG (mcu of DISCO_L475VG_IOT01A)

targets/TARGET_STM/TARGET_STM32F3/device/stm32f3xx_hal_comp_ex.h, targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F412xG/TARGET_NUCLEO_F412ZG/system_clock.c, targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F413xH/TARGET_DISCO_F413ZH/system_clock.c, targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_spi.h
Issue comes only when ST HAL macro USE_FULL_ASSERT is enabled
**READY**
=> STM32 : correct compilation issue with USE_FULL_ASSERT macro

targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F437xG/TARGET_UBLOX_C030/battery_charger_i2c.cpp, targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F437xG/TARGET_UBLOX_C030/battery_charger_i2c.h, targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F437xG/TARGET_UBLOX_C030/min_battery_voltage.cpp, targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F437xG/TARGET_UBLOX_C030/min_battery_voltage.h
This is a fix for on board BQ24295 battery charger on UBLOX C030 application board. This allows longer USB cables or USB ports with lower output voltages to power the board correctly. An I2C interface is used to set the battery voltage in boot sequence. 
**READY**
- Tested on UBLOX_C030 application boards using the battery charger driver
- New files introduced in vendor specific TARGET_UBLOX_C030 folder
=> C030 Battery Charger Voltage Fix

features/nanostack/FEATURE_NANOSTACK/targets/TARGET_SL_RAIL/NanostackRfPhyEfr32.cpp
Fixes the `SL_ACK_PEND` flag which is currently larger than `osRtxThreadFlagsLimit`, evaluated in `isrRtxThreadFlagsSet` at `rtx_thread.c:1491`.
This causes an `osErrorParameter` on receiving packets that require acknowledgements.
=> Nanostack EFR32 flag fix

features/FEATURE_LWIP/lwip-interface/lwip_stack.c, targets/TARGET_Realtek/TARGET_AMEBA/RTWInterface.cpp
Fix in lwip_stack to pass greentea test for Realtek RTL8195A platform
Notes:
This is a fix in the lwip stack to ensure that the netif is not being initialized twice. In the earlier version the netif was being inialized twice and hence the test "bring the network up and down twice" was faling.
**READY**
No other changes other than in lwip_stack.c
None
- [X ] Tests. (Tested with latest mbed-os and mbedgt)
No change in build/test environment needed.
download and run the greentea test corresponding to the test using the command
mbed test -n mbed-os-tests-netsocket-connectivity --test-config Realtek_wifi
Before running the command …
=> Fixing for greentea test mbed-os-tests-netsocket-connectivity

rtos/Thread.cpp
Call to osThreadTerminate is guarded by local_id != 0 check, to avoid parameter error fault when deleting or terminating Thread object that was not started.
**READY**
NO
On any target (tested with FRDM-K64F):
```
RawSerial output(USBTX, USBRX);
int main(int argc, char **argv)
{
output.baud(115200);
output.printf("\r\nStarting mbed\r\n");
{
rtos::Thread dummyToTriggerError(osPriorityNormal, 0x500);
}
while(1);
}
```
output:
```
Starting mbed
Thread 0x0 error -4: Parameter error
```
=> Fix fatal parameter error when deleting/terminating Thread object

TESTS/mbedmicro-rtos-mbed/CircularBuffer/main.cpp, platform/CircularBuffer.h
This PR provides:
- proposal of updating the CircularBuffer class (assertion for CounterType).
- CircularBuffer test.
**READY**
NO
=> CircularBuffer class modification and test

TESTS/network/wifi/wifi_connect_params_valid_secure.cpp, TESTS/network/wifi/wifi_get_rssi.cpp, TESTS/network/wifi/wifi_scan.cpp, TESTS/network/wifi/wifi_set_credential.cpp
Greentea testcase WIFI-SCAN fails arbitrarily
Greentea testcase WIFI-SET-CREDENTIAL doesn't try WEP with valid credentials
Greentea testcase WIFI-GET-RSSI uses arbitrary RSSI value limits
Greentea testcase WIFI-CONNECT-PARAMS-VALID-SECURE assumes WPA2
Testcases in question either have unnecessary expectations about signal quality or make unnecessary assumptions about security features available. Testcases also assume that max password length is 64 characters when 802.11 says it's 63.  We might have also access points with hidden SSIDs in vicinity but the scan test didn't like about those too much. This PR addresses all these issues.
**READY**
NO
...\mbed-os> mbed test --compile -t ARM -m REALTEK_RTL8195AM --app-config .\TESTS\network\wifi\template_mbed_app.txt -n tests-network-wifi …
=> Greentea Wifi testcase fixes

tools/config/__init__.py, tools/test.py, tools/test_configs/__init__.py
Fixes #5543
This change allows for `mbed test` to build with an `mbed_app.json` file by default if one exists in the project's root directory (i.e. for running the [ci-test-shield tests](https://github.com/ARMmbed/ci-test-shield)). However, if the `mbed_app.json` file is not in the root directory, then it's location needs to be specified in the command with the `--app-config` parameter.
**Before fix:**
If you run the [ci-test-shield tests](https://github.com/ARMmbed/ci-test-shield) with `mbed test -t GCC_ARM -m NUCLEO_F207ZG -n tests* --compile` without a specified `--app-config` you get the following errors related to the unspecified `mbed_app.json`:
```
[Error] Mixed.cpp@68,22: 'MBED_CONF_APP_I2C_SDA' was not declared in this scope
[Error] Mixed.cpp@68,44: 'MBED_CONF_APP_I2C_SCL' was …
```
=> Fix for default test config file

targets/targets.json, tools/export/uvision/uvision.tmpl
device_name key is required to add Cloud Client support / enable bootloader support for this target.
**READY**
None.
=> Add device_name for TB_SENSE_12.

platform/CircularBuffer.h
Fix #5578 by including the header file that introduces `MBED_STATIC_ASSERT` macro.
=> Fix PR5578

targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_eth.c
Pending official update from STM, add memory barriers to the Ethernet
HAL code for the STM32F7xx family.
Cortex-M7 has a merging write buffer that is not automatically flushed
by accesses to devices, so without these DMBs, we sometimes lose synch
with the transmitter.
The DMBs are architecturally needed in every version of this HAL, but
adding just to the STM32F7 version for now to clear test, as the
problem has only been observed on Cortex-M7-based devices.
Fixes #5622.
=> Add memory barriers to STM32F7xx Ethernet

tools/memap.py
Build failed as code section was not included while generation of map file. 
Fix by @theotherjimmy 
Resolution was added as part of secure support, since that PR is delayed picking up mbed-os issues separately.
=> Build failed as code section was not included in map.

features/nanostack/FEATURE_NANOSTACK/mbed-mesh-api/mbed_lib.json, features/nanostack/FEATURE_NANOSTACK/mbed-mesh-api/source/nd_tasklet.c, features/nanostack/FEATURE_NANOSTACK/mbed-mesh-api/source/thread_tasklet.c
When specifying a full channel mask in .lib and setting the channel
to zero, device does proper channel scan.
For Thread, channel must be specified for router.
Sleepy devices don't respect the channel settings but do a full channel
scan at the start.
+ Modified the channel mask print to use hex.
Please review: @artokin @mikter
=> Allow 6LoWPAN applications to leave out channel specification.

tools/export/iar/iar_definitions.json
- ADuCM3029 is the MCU name for EV_COG_AD3029LZ
- ADuCM4050 is the MCU name for EV_COG_AD4050LZ
**READY**
NO
mbed export -i iar -m EV_COG_AD3029LZ
mbed export -i iar -m EV_COG_AD4050LZ
=> Enable IAR export for EV_COG_AD3029LZ and EV_COG_AD4050LZ

features/FEATURE_LWIP/lwip-interface/lwip_stack.c
Return NSAPI_ERROR_PARAMETER when:
Binding to a non-local address
Socket listen() is called without calling bind() first
Socket accept() is called without calling listen() first
=> lwip: fix socket behaviour

tools/toolchains/__init__.py
Fix for #5676. In some cases relative_object_path can result in path's like "path\to\.\some\file.o", which in turn can result in duplicate file names in the linker list (second entry would be in the form of "path\to\some\file.o")
READY
NO
=> Fix for #5676 make.py generates duplicate file entries in link_files.txt

platform/mbed_alloc_wrappers.cpp, platform/mbed_mem_trace.cpp, platform/mbed_mem_trace.h
This change fix "trace inside trace" issue in mem_trace module
It prevents from tracing `malloc`/`free` calls inside `__wrap__realloc_r`/`__wrap__calloc_r`/`SUB_REALLOC`/`SUB_CALLOC`
**READY**
Change `mbed_mem_trace` module API
add functions: `mbed_mem_trace_level_incr` `mbed_mem_trace_level_decr`
YES
=> platform: fix mem_trace trace level guard

platform/mbed_retarget.cpp
Access to serial_putc was not guarded under DEVICE_SERIAL define. In case DEVICE_SERIAL is not selected this will give compilation error.
Resolution was added as part of secure support, since that PR is delayed picking up mbed-os issues separately.
=> Access to serial device is allowed when DEVICE_SERIAL is defined

TESTS/network/wifi/get_interface.cpp, TESTS/network/wifi/main.cpp
Most of our IP stacks don't allow removal of interfaces so
interface destructor can not reliably clean up. Therefore we
cannot rely its behaviours in test case.
Instead run interface->disconnect() in case interface was already
created.
**READY**
NO
=> Remove destruction of WiFi interface in test runs

targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F439xI/TARGET_MODULE_UBLOX_ODIN_W2/TARGET_UBLOX_EVK_ODIN_W2/hal_overrides.c
This PR will set the ODIN EVK LEDs in a defined off state on startup.
It should fix https://github.com/ARMmbed/mbed-os/issues/5367.
**READY**
NO
None
No
N/A
See https://github.com/ARMmbed/mbed-os/issues/5367
=> Added init for ODIN EVK LEDs to be off by default

features/FEATURE_COMMON_PAL/nanostack-hal-mbed-cmsis-rtos/mbed_lib.json, features/FEATURE_COMMON_PAL/nanostack-hal-mbed-cmsis-rtos/ns_event_loop.c, features/FEATURE_COMMON_PAL/nanostack-hal-mbed-cmsis-rtos/ns_event_loop.h, features/FEATURE_COMMON_PAL/nanostack-hal-mbed-cmsis-rtos/ns_hal_init.c
This has the same content as https://github.com/ARMmbed/mbed-os-confidential-m/pull/7, just the target repo and branch are different.
=> Eventloop in main thread

features/FEATURE_COMMON_PAL/nanostack-hal-mbed-cmsis-rtos/arm_hal_interrupt.c, features/FEATURE_COMMON_PAL/nanostack-hal-mbed-cmsis-rtos/mbed_lib.json
(This PR has the same content as https://github.com/ARMmbed/mbed-os-confidential-m/pull/8)
The nanostack hal's critical section uses a mutex for mutual exclusion,
which is nice for many use cases. But when one needs to use the critical
section from interrupts, the RTX will have a assertion failure and panic.
Add a configurable for mbed_lib, which can be used to enable a alternative
version of critical section, which uses the underlying OS primitives, which
disables the interrupts.
Note: the default behavior is not changed, one needs to override the
"nanostack-hal.critical-section-usable-from-interrupt" to have "true".
Reason for this change is that there is a need for sending events using
nanostack event queue from interrupt context, eg. from a socket callback.
**READY**
YES | NO
Note: …
=> nanostack-hal: add alternative critical section implementation

platform/CriticalSectionLock.h
Change CriticalSectionLock member functions `void lock/unlock()` to static ones 
`static void lock/unlock()` to allow more meaningful `lock`/`unlock` usage
**READY**
Although the class API is changed, usage is not affected since class member access syntax is allowed for static functions
YES
#5420
=> CriticalSectionLock class improvement

.travis.yml, targets/TARGET_RENESAS/TARGET_RZ_A1H/device/os_tick_ostm.c, targets/TARGET_RENESAS/TARGET_VK_RZ_A1H/device/VKRZA1H.h, targets/TARGET_RENESAS/TARGET_VK_RZ_A1H/serial_api.c, targets/TARGET_RENESAS/TARGET_VK_RZ_A1H/us_ticker.c, targets/targets.json, tools/build_api.py, tools/build_travis.py
device header file not needed in cmsis implementation, thus removed - causing problems to build cmsis lib in mbed 2
another fix is for renesas target code that implements os tick, should only be available if rtos is present
Tested locally with GCC ARM
@ARMmbed/team-renesas please verify this patch
=> Renesas: fix cmsis lib build

features/FEATURE_LWIP/lwip-interface/EthernetInterface.cpp, features/FEATURE_LWIP/lwip-interface/EthernetInterface.h, features/FEATURE_LWIP/lwip-interface/lwip/src/include/lwip/netif.h, features/FEATURE_LWIP/lwip-interface/lwip_stack.c, features/FEATURE_LWIP/lwip-interface/lwip_stack.h, features/FEATURE_LWIP/lwip-interface/ppp_lwip.cpp, features/nanostack/FEATURE_NANOSTACK/mbed-mesh-api/mbed-mesh-api/MeshInterfaceNanostack.h, features/nanostack/FEATURE_NANOSTACK/mbed-mesh-api/source/MeshInterfaceNanostack.cpp, features/nanostack/FEATURE_NANOSTACK/mbed-mesh-api/source/ThreadInterface.cpp, features/netsocket/NetworkInterface.cpp, features/netsocket/NetworkInterface.h, features/netsocket/cellular/generic_modem_driver/PPPCellularInterface.cpp, features/netsocket/cellular/generic_modem_driver/PPPCellularInterface.h, features/netsocket/nsapi_ppp.h, features/netsocket/nsapi_types.h
This adds connection status callback registering, and connection status reporting to NetworkInterface, and implementation of these to CellularInterface, mesh and ethernet interfaces
**READY**
YES
In NetworkInterface new APIs:
-attach() for connection status callback registering
-get_connection_status()
-set_blocking()
In PPPCellularInterface:
-connection_status_cb() removed
-  Documentation needs to be updated
=> Network interface: Add status callback register

targets/TARGET_STM/TARGET_STM32F0/common_objects.h, targets/TARGET_STM/TARGET_STM32F0/flash_api.c, targets/TARGET_STM/TARGET_STM32F1/common_objects.h, targets/TARGET_STM/TARGET_STM32F1/flash_api.c, targets/targets.json
- Add support of Flash API for STM32F0 and STM32F1 devices.
- Same code as STM32F3 devices.
- Activated on **NUCLEO_F070RB**, **NUCLEO_F072RB**, **NUCLEO_F091RC** and **NUCLEO_F103RB** boards only
- Flash tests OK
**READY**
NO
#5697
=> STM32: Add support of Flash API for STM32F0 and STM32F1 devices

targets/targets.json
Some EFM32 targets with bootloader support are missing the required `device_name`. This PR fixes it using an analogy to other targets.
Notes:
* I have accepted the [contributor agreement](https://os.mbed.com/contributor_agreement/).
**READY**
NO
=> Add missing device_name for targets with bootloader

TESTS/network/emac/README.md, TESTS/network/emac/emac_ctp.cpp, TESTS/network/emac/emac_ctp.h, TESTS/network/emac/emac_initialize.h, TESTS/network/emac/emac_membuf.cpp, TESTS/network/emac/emac_membuf.h, TESTS/network/emac/emac_test_broadcast.cpp, TESTS/network/emac/emac_test_initialize.cpp, TESTS/network/emac/emac_test_unicast.cpp, TESTS/network/emac/emac_test_unicast_frame_len.cpp, TESTS/network/emac/emac_tests.h, TESTS/network/emac/emac_util.cpp, TESTS/network/emac/emac_util.h, TESTS/network/emac/main.cpp, TESTS/network/emac/template_mbed_app.txt
Added basic greentea tests for EMAC wifi interface. The test case inserts it between emac driver and lwip to be able to sent and received messages.
Protocol used for testing is "ethernet configuration testing protocol" (CTP). One device in ethernet segment needs to be configured as CTP echo server, to reply to messages sent by device that is tested. Test case .json file can be used to configure different settings for test case/echo server.
READY
NO
None
None
None
=> Tests for wifi emac interface

targets/TARGET_STM/TARGET_STM32F0/serial_device.c, targets/TARGET_STM/TARGET_STM32F1/serial_device.c, targets/TARGET_STM/TARGET_STM32F2/serial_device.c, targets/TARGET_STM/TARGET_STM32F3/serial_device.c, targets/TARGET_STM/TARGET_STM32F4/serial_device.c, targets/TARGET_STM/TARGET_STM32F7/serial_device.c, targets/TARGET_STM/TARGET_STM32L0/serial_device.c, targets/TARGET_STM/TARGET_STM32L1/serial_device.c, targets/TARGET_STM/TARGET_STM32L4/serial_device.c, targets/TARGET_STM/serial_api.c, targets/TARGET_STM/serial_api_hal.h
- serial_init, serial_free and serial_baud functions moved from serial_device.c (specific to each STM32 family) to serial_api.c (common STM32 file)
- default baudrate value was hardcoded to 9600
- Value is set now to MBED_CONF_PLATFORM_STDIO_BAUD_RATE for STDIO
- Value is set now to MBED_CONF_PLATFORM_DEFAULT_SERIAL_BAUD_RATE for other use
- UART init will not be stopped before calling serial_baud function
- for LPUART, init procedure can update the clock source depending on expected baudrate
This should close #5389 issue
**READY**
OS2 and OS5 tests verified for all STM32 targets
=> STM32 UART init update

targets/TARGET_NORDIC/TARGET_NRF5/nordic_critical.c
current critical section implementation makes possible that interrupt
signals are lost.
This patch introduce usage of sdk5 origin implementation in which
sd_nvic_critical_region_enter/exit is calling each time critical region
is enter/exit. This fixes the issue.
=> fix nordic critical section

TESTS/mbed_drivers/mem_trace/main.cpp
- tests refactoring and align to coding standards
- multithreaded test added
**HOLD**
NO
Requires following PR :
https://github.com/ARMmbed/mbed-os/pull/5614
=> mem_trace tests refactoring

targets/TARGET_STM/TARGET_STM32F3/common_objects.h, targets/TARGET_STM/TARGET_STM32F3/flash_api.c, targets/targets.json
- Add support of Flash API for STM32F3 devices.
- Activated on **NUCLEO_F303RE** and **NUCLEO_F303ZE** boards only (other F3 boards are not mbedOS5 compliant)
- Flash tests OK --> [report_test5_flash_STM32F303xE_ARM.txt](https://github.com/ARMmbed/mbed-os/files/1555590/report_test5_flash_STM32F303xE_ARM.txt)
**READY**
NO
=> STM32: Add support of Flash API for STM32F3 devices

targets/TARGET_Analog_Devices/TARGET_ADUCM302X/TARGET_ADUCM3029/api/analogin_api.c, targets/TARGET_Analog_Devices/TARGET_ADUCM4X50/TARGET_ADUCM4050/api/analogin_api.c
- Cleared data structures in analogin_init();
- Set buffer for 1 sample in analogin_read_u16. Before it assumes the buffer is set outside by the higher layer. Now it's temporarily located on the stack since only the ADC value is returned.
Ready
NO
N/A
branch | PR
N/A
N/A
N/A
N/A
=> AD: Fix ADC driver

TESTS/mbed_drivers/lp_timer/main.cpp
In tests-mbed_drivers-lp_timer, since low power timer is less accurate than regular timer,
there is a delta time based on CPU clock frequency.
For ex, STM32F7 has a system core clock set to 216MHz, then delta time is only 370us.
With the current formula, we think that this delta time is too aggressive for high frequency targets.
So we propose to set a kind of minimum delta time around 500us.
Thx
**READY**
=> lp_timer test : add a minimum delta value

tools/profiles/develop.json, tools/profiles/release.json
This allows minimal debugging and allows tools like
[mbed-os-linker-report](https://github.com/armmbed/mbed-os-linker-report) to work properly.
Because debugging info is kept in .elf file and not flashed to device
there is no side effects to flash sizes.
=> Add minimal debug info to release and develop profiles.

targets/TARGET_STM/rtc_api.c
After deep sleep period, RTC clock has to be synchronized.
This patch makes it OK for all applications (even if RTC has been configured before target reset).
**READY**
=> STM32 : Fix issue to exit deepsleep when RTC has not been initialized

tools/memap.py, tools/test/memap/gcc.map, tools/test/memap/iar.map, tools/test/memap/memap_test.py, tools/test/memap/parse_test.py
Includes a parser refactor, as I got a bit irritated by seeing `_gcc`
suffixed method names.
Resolves #5772
=> Correct memap path handling on windows

features/filesystem/littlefs/littlefs/lfs.c, features/filesystem/littlefs/littlefs/tests/test_seek.sh
This bug was a result of an annoying corner case around intermingling signed and unsigned offsets. The boundary check that prevents seeking a file to a position before the file was preventing valid seeks with
positive offsets.
This corner case is a bit more complicated than it looks because the offset is signed, while the size of the file is unsigned. Simply casting both to signed or unsigned offsets won't handle large files.
from https://github.com/geky/littlefs/issues/4
note: intended for patch
=> littlefs: Fix positive seek bounds checking

TESTS/host_tests/rtc_calc_auto.py
Result was not defined, thus causing attribute error
```
AttributeError: 'RTC_time_calc_test' object has no attribute '_RTC_time_calc_test__result'
```
@mprse @maciejbocianski  please review
=> RTC test: fix __result variable

features/FEATURE_COMMON_PAL/mbed-coap/source/sn_coap_builder.c, features/FEATURE_COMMON_PAL/mbed-coap/source/sn_coap_protocol.c
* Implements CoAP part of IOTUPD-2326
Support for sending BLOCK2 GET request. This change is needed to get FW update over CoAP feature to work.
READY
=> Support for BLOCK2 blockwise messages GET request handling

features/filesystem/FileSystem.cpp, features/filesystem/FileSystem.h, features/filesystem/fat/FATFileSystem.cpp, features/filesystem/fat/FATFileSystem.h, features/filesystem/littlefs/LittleFileSystem.cpp, features/filesystem/littlefs/LittleFileSystem.h, platform/FileSystemHandle.cpp, platform/FileSystemHandle.h, platform/mbed_retarget.cpp, platform/mbed_retarget.h
The API is as per posix standard, but does not provide stats for file/directory. Stats buffer (block size, total block count, free block count) is filled for mounted filesystem.
~Todo: Littlefs statvfs code~
CC @geky 
Related Issue: https://github.com/ARMmbed/mbed-os/issues/5702
=> Added statvfs API to get storage statistics

TESTS/host_tests/rtc_calc_auto.py, TESTS/mbed_hal/rtc_time_conv/main.cpp
Reduce number of tested cases as follows:
For each of the following years test example time of the first and last day of each month:
- first - 1970
- example not leap year (not divisible by 4)
- example leap year (divisible by 4 and by 100 and by 400)
- example leap year (divisible by 4 and not by 100)
- example not leap year (divisible by 4 and by 100)
- last fully supported  - 2105
Test execution time on K64F is now ~39 sec.
**READY**
NO
=> RTC time conversion test - reduce test execution time.

TESTS/mbed_hal/flash/functional_tests/main.cpp
The current 0.1% clock tolerance is too small for certain platforms
which natural variance is larger than this. This commit increases the
tolerance to 0.5% instead.
Sample output from time_cpu_cycles called repeatedly in init,
before running any flash tests:
[1515706585.63][CONN][RXD] diff: 49316
[1515706585.69][CONN][RXD] diff: 49256
[1515706585.75][CONN][RXD] diff: 49286
[1515706585.81][CONN][RXD] diff: 49256
[1515706585.87][CONN][RXD] diff: 49225
[1515706585.94][CONN][RXD] diff: 49286
[1515706585.99][CONN][RXD] diff: 49317
[1515706586.06][CONN][RXD] diff: 49255
[1515706586.12][CONN][RXD] diff: 49286
[1515706586.18][CONN][RXD] diff: 49285
[1515706586.24][CONN][RXD] diff: 49286
[1515706586.31][CONN][RXD] diff: 49347
[1515706586.36][CONN][RXD] diff: 49347
[1515706586.43][CONN][RXD] diff: …
=> Increase clock tolerance in Flash HAL test

TESTS/netsocket/tcp_echo/main.cpp, TESTS/netsocket/tcp_hello_world/main.cpp, tools/test_configs/ESP8266Interface.json, tools/test_configs/config_paths.json, tools/test_configs/target_configs.json
This PR contains following changes:
New ESP8266 Test config and a config for selecting the buffer size used in tcp_echo test. 
tcp_hello_world test has also been fixed to receive all the data from socket until there in no more data to be read.
=> ESP8266 Test Config and fixes for tests tcp_echo/tcp_hello_world

features/filesystem/fat/FATFileSystem.cpp
FATFilesystem declares sector count and size as uint32_t and block device class arguments are addr and size which is uint64_t. While passing arguments to program/read/write API's of block device, multiplication of uint32_t*uint32_t was not type-casted to uint64_t which resulted in truncation.
Example of FAT corruption:
If sector 0x800000 is accessed with block size 0x200, addr to be passed 0x1 0000 0000 (0x800000*0x200), but actual address passed was 0x0000 0000 which resulted in over-writting the root directory, and hence corrupted filesystem.
=> Fix: Sector/Size overflow from uint32_t

targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F407xG/TARGET_DISCO_F407VG/PinNames.h, targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F407xG/TARGET_DISCO_F407VG/system_clock.c, targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F407xG/device/TOOLCHAIN_IAR/startup_stm32f407xx.S, targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F407xG/device/TOOLCHAIN_IAR/stm32f407xx.icf, targets/targets.json
DISCO_F407VG : alignment with other STM32
- clock source is now a user choice
- IAR tool chain is available
**READY**
All OK
=> DISCO_F407VG : alignment with other STM32

targets/TARGET_STM/TARGET_STM32F2/TARGET_NUCLEO_F207ZG/device/flash_data.h, targets/TARGET_STM/TARGET_STM32F2/flash_api.c, targets/TARGET_STM/TARGET_STM32F2/objects.h, targets/targets.json
- Add support of Flash API for STM32F2 devices.
- Same code as for STM32F4 devices.
- Activated on **NUCLEO_F207ZG** board only
- Flash tests OK
**READY**
NO
#5697 
#5776
=> STM32: Add support of Flash API for STM32F2 devices

rtos/ConditionVariable.h, rtos/EventFlags.h, rtos/Mail.h, rtos/MemoryPool.h, rtos/Mutex.h, rtos/Queue.h, rtos/RtosTimer.h, rtos/Semaphore.h, rtos/Thread.h
Extend docs for RTOS functions to include information whether they are ISR safe.
**READY**
=> Add notes about ISR safety to RTOS doxygen

targets/TARGET_STM/lp_ticker.c, targets/TARGET_STM/rtc_api.c, targets/TARGET_STM/rtc_api_hal.h, targets/TARGET_STM/sleep.c, targets/targets.json
STM32L0, L4, F7 and few F4 chip are supporting STM32 LPTIM feature.
We propose to allow user to use LPTIM for MBED LowPowerTimer API instead of using RTC wakeup timers.
By default, all targets that are supporting this feature have been configured.
**READY**
=> STM32 LOWPOWERTIMER : introduce LPTIM feature

features/netsocket/TCPSocket.h, features/netsocket/UDPSocket.h
* Clarify `recv()` call to return zero on end-of-stream.
* Clarify `recvfrom()` to actually return size of datagram, not some arbitrary size.
CC: @kjbracey-arm @sg-
=> Clarify TCPSocket::recv() and UDPSocket::recvfrom() documentation.

platform/mbed_alloc_wrappers.cpp, platform/mbed_retarget.cpp
The C++ "operator new" and "operator delete" (and their array
variants) were logging the the caller address wrong. In practice
if one used "operator new", the logged caller address pointed
to mbed_retarget.cpp, not to the client. Fix this by exposing
the alloc wrappers to the the retarget.
Note: this fixes only the ARMCC variants, as the GCC ones have
different different API and implementation.
Related mbed-os issue: https://github.com/ARMmbed/mbed-os/issues/5221
**IN DEVELOPMENT**, GCC should also be fixed.
NO
Note: the GCC target is equally broken, but this PR is not fixing that.
Test code
```
class test_class
{
public:
uint32_t member;
};
static void do_the_test()
{
void *mem_malloc = malloc(100);
void *mem_calloc = calloc(60, 2);
test_class* cpp_new_obj = new test_class;
uint8_t* …
```
=> platform: make C++ allocation wrappers log the correct caller address

features/FEATURE_BLE/targets/TARGET_NORDIC/TARGET_NRF5/source/btle/custom/custom_helper.cpp, features/FEATURE_BLE/targets/TARGET_NORDIC/TARGET_NRF5/source/btle/custom/custom_helper.h, features/FEATURE_BLE/targets/TARGET_NORDIC/TARGET_NRF5/source/nRF5xGattServer.cpp
Notes:
- Have agreed to contributor agreement on mbed site (user: dschuler)
Looking through the mbed BTLE sources, I can find the characteristic presentation format descriptor, BLE_UUID_DESCRIPTOR_CHAR_PRESENTATION_FORMAT, as well as a struct to hold the format in GattCharacteristic::PresentationFormat_t. However, when I add this descriptor to a characteristic and test using Nordic's NRF52 DK board, the descriptor does not appear.
Nordic seems to handle this presentation format differently from other descriptors, along with BLE_UUID_DESCRIPTOR_CHAR_USER_DESC. So, here I added a code path to handle the presentation format the similarly. Tested again on the NRF52 DK, everything appears to be working well.
**READY**
This does not change any APIs or behavior, but should allow a user to pass a …
=> Add presentation format descriptor support for nRF5x

TESTS/mbed_drivers/ticker/main.cpp, TESTS/mbed_drivers/timer/main.cpp, TESTS/mbed_hal/sleep/main.cpp, TESTS/mbed_hal/sleep/sleep_api_tests.h, hal/sleep_api.h, targets/targets.json
This PR provides:
- HAL Sleep test case specification to the sleep_api.h file.
- test and test header to Sleep HAL API.
**READY**
NO
Implementation of the following test cases still needs to be added:
- RTC should wake up a target from this mode - RTC alarm functionality is not yet available.
- a watchdog timer should wake up a target from this mode - watchdog functionality is not yet available.
- the processor can be woken up by external pin interrupt - @bulislaw @theotherjimmy @0xc0170  I need some information how CI environment is build and if there is any option to create such case. I tried to set USBRX pin as interrupt input pin and send some data from python part of test in order to wake up the board from sleep. This solution worked on K64F, but on NUCLEOF070RB did not - it looks …
=> Add tests for Sleep HAL API

targets/TARGET_Silicon_Labs/TARGET_EFM32/TARGET_EFM32PG/TARGET_EFM32PG_STK3401/device_peripherals.h, targets/TARGET_Silicon_Labs/TARGET_EFM32/TARGET_EFM32PG12/TARGET_EFM32PG12_STK3402/device_peripherals.h, targets/TARGET_Silicon_Labs/TARGET_EFM32/TARGET_EFR32MG1/TARGET_EFR32MG1_BRD4150/device_peripherals.h, targets/TARGET_Silicon_Labs/TARGET_EFM32/TARGET_EFR32MG1/TARGET_TB_SENSE_1/device_peripherals.h, targets/TARGET_Silicon_Labs/TARGET_EFM32/TARGET_EFR32MG12/TARGET_TB_SENSE_12/device_peripherals.h, targets/TARGET_Silicon_Labs/TARGET_EFM32/common/mbed_overrides.c
Allow custom targets to override the DCDC settings by defining EMU_DCDCINIT_STK_DEFAULT to target-specific initialization values. This feature was requested in #5783 
**READY**
Custom targets need to define EMU_DCDCINIT_STK_DEFAULT if they need different DCDC initialisation settings versus the defaults in em_emu.h
=> Allow overriding of DCDC settings per target

features/filesystem/littlefs/LittleFileSystem.cpp
deepikabhavnani did the hard work in tracking this issue down.  Block addresses are not cast to the correct type until after multiplying to convert to byte addresses. This results in an overflow when the storage is larger than 4 GB.
same as https://github.com/ARMmbed/mbed-os/pull/5829
related to https://github.com/ARMmbed/mbed-os/issues/5780
cc @deepikabhavnani 
note: intended for patch
=> littlefs: Fix block addr overflow

targets/TARGET_Silicon_Labs/TARGET_EFM32/common/clocking.h, targets/TARGET_Silicon_Labs/TARGET_EFM32/lp_ticker.c, targets/TARGET_Silicon_Labs/TARGET_EFM32/rtc_api.c, targets/TARGET_Silicon_Labs/TARGET_EFM32/rtc_api_HAL.h, targets/TARGET_Silicon_Labs/TARGET_EFM32/us_ticker.c
This commit fixes #5840. Fix verified by running mbed_hal-lp_ticker test suite on both EFM32GG and EFM32PG12 with preloaded RTC counter such that it wrapped in the middle of the suite.
Also removes explicit sleep blocking from the us_ticker implementation, since sleep blocking for us tickers is done at mbed HAL level now. This was causing one of the lp_ticker tests to fail.
**READY**
NO
=> Fix for Silicon Labs RTC

targets/TARGET_STM/can_api.c
This PR fixes a wrong configuration of the STM32 CAN ID and MASK filters resulting that only some IDs and MASKs were working correctly (Thanks @zh0umu).
**READY**
**NO**
#5765 
#5351
=> STM32 CAN: fix wrong ID and MASK filter

platform/mbed_critical.c
Fixes #5555 bug.
In case there is not yet defined __EXCLUSIVE_ACCESS, neither MBED_EXCLUSIVE_ACCESS that
we are introducing, use architecture macros to find out if MBED_EXCLUSIVE_ACCESS can be
enabled.
First I thought that these could be added to `CORE_LABELS` that we have in tools/targets/init file. That might be better placement, but @theotherjimmy did not like the proposal. If we add a new core, this would need to be defined. In this case it might be overlooked.
=> critical: fix set exclusive access if not yet defined

targets/TARGET_STM/lp_ticker.c, targets/TARGET_STM/rtc_api.c, targets/TARGET_STM/rtc_api_hal.h
For each low power timer/ticker start, lp_ticker_read function is called 3 or 4 times.
lp_ticker_read duration was around 58us.
It is now reduced to 9us.
Hope it will solve #5790 
**READY**
=> STM32 LPT optimisation

targets/TARGET_NUVOTON/TARGET_M451/gpio_api.c, targets/TARGET_NUVOTON/TARGET_M480/gpio_api.c, targets/TARGET_NUVOTON/TARGET_NANO100/gpio_api.c, targets/TARGET_NUVOTON/TARGET_NUC472/gpio_api.c
This PR adds missing `gpio_is_connected` for all Nuvoton targets.
=> Nuvoton: Add gpio_is_connected

features/nanostack/FEATURE_NANOSTACK/nanostack-interface/NanostackInterface.cpp
Add support for recently introduced NSAPI generic socket options to
control group membership. Previously applications using Nanostack would
have had to use Nanostack's native socket options.
=> NSAPI: Add Nanostack multicast membership support

.travis.yml, features/filesystem/littlefs/littlefs/.travis.yml, features/filesystem/littlefs/littlefs/lfs.c
This was a small hole in the logic that handles initializing the lookahead buffer. To imitate exhaustion (so the block allocator will trigger a scan), the lookahead buffer is rewound a full lookahead and set up to look like it is exhausted. However, unlike normal allocation, this rewind was not kept aligned to a multiple of the scan size, which is limited by both the lookahead buffer and the total storage size.
This bug went unnoticed for so long because it only causes problems when the block device is both:
1. Not aligned to the lookahead buffer (not a power of 2)
2. Smaller than the lookahead buffer (< 64 blocks)
While this seems like a strange corner case for a block device, this turned out to be very common for internal flash, especially when a handful of blocks are reserved for code. …
=> littlefs: Fix issue with immediate exhaustion and small unaligned storage

features/filesystem/littlefs/littlefs/lfs.c, features/filesystem/littlefs/littlefs/tests/test_files.sh
In the open call, the LFS_O_TRUNC flag was correctly zeroing the file, but it wasn't actually writing the change out to disk. This went unnoticed because in the cases where the truncate was followed by a file write, the updated contents would be written out correctly.
Marking the file as dirty if the file isn't already truncated fixes the problem with the least impact. Also added better test cases around truncating files.
resolves https://github.com/ARMmbed/mbed-os/issues/5820
from https://github.com/geky/littlefs/issues/7
note: intended for patch
=> littlefs: Fix file truncation without writes

features/nanostack/FEATURE_NANOSTACK/coap-service/Makefile, features/nanostack/FEATURE_NANOSTACK/coap-service/source/coap_message_handler.c, features/nanostack/FEATURE_NANOSTACK/coap-service/source/include/coap_message_handler.h
Fix issue https://github.com/ARMmbed/coap-service/issues/88.
**READY**
Device commissioning in Thread network was broken.  With this fix the commissioning is working like described in: https://os.mbed.com/docs/v5.7/tutorials/mesh.html#thread-commissioning
=> Thread commissioning fix

TESTS/mbed_hal/lp_us_tickers/main.cpp, TESTS/mbed_hal/lp_us_tickers/ticker_api_tests.h, hal/us_ticker_api.h
This PR contains:
- modification of the requirement for the ticker init function (result of the following discussion https://github.com/ARMmbed/mbed-os/pull/5233#pullrequestreview-86677815).
- update of the test case to be consistent with new requirement.
- fix in the us/lp ticker test implementation (The intention was to use ticker_overflow_delta equal to 0 for low power ticker tests and ticker_overflow_delta equal to 50 for high frequency ticker tests. Current implementation is invalid since for devices which provide LOW_POWER_TIMER feature delta is equal to 0 and for devices without this feature delta is equal 50.)
**READY**
NO
=> Ticker requirement and test update

features/unsupported/USBDevice/USBDevice/USBDevice.cpp, features/unsupported/USBDevice/targets/TARGET_Freescale/USBHAL_KL25Z.cpp
Make the following improvements and fixes:
1. Update the Kinetis USB driver so that endpointReadResult only reads the result of the last read and does not trigger a new read. Instead move the code to trigger new reads into endpointRead.
1. Fix the race condition in controlIn caused by a call to EP0read() followed immediately by  EP0readStage(). This is done by setting up to read the next setup packet (ignoring the status stage)
in endpointReadResult rather than in EP0readStage. This makes the function EP0readStage unnecissary.
1. Remove the Kinetis workaround in controlOut in USBDevice.cpp since point 2 fixes this bug. For more info on this see the PR which added this workaround - https://github.com/ARMmbed/mbed-os/pull/414
=> Kinetis USB improvements and fixes

features/unsupported/USBDevice/targets/TARGET_NXP/USBHAL_LPC17.cpp, features/unsupported/USBDevice/targets/TARGET_NXP/USBHAL_LPC40.cpp
Fix USB race condition and add data throttling.
=> LPC USB stability fixes

features/unsupported/USBHost/USBHost/USBDeviceConnected.h, features/unsupported/USBHost/USBHost/USBEndpoint.h, features/unsupported/USBHost/USBHost/USBHost.cpp
Notes:
- This is just a template, so feel free to use/remove the unnecessary things
- Rewrite the USBHost module callbacks in the new form.
- Fix a bug related to defining `MAX_HUB_NB` macro, the variable `k` is declared if the macro is not zero [as you can see here](https://github.com/ARMmbed/mbed-os/blob/master/features/unsupported/USBHost/USBHost/USBHost.cpp#L65), and after, used without testing `MAX_HUB_NB` which leads to undefined reference error durring compilation if `MAX_HUB_NB=0`.
**READY**
NO
- …
=> Some enhancements for the USBHost feature and small bug fix

targets/targets.json
This PR add new BOARD_ID for the VBLUno51 board. 
The mbed Enabled process for the VBLUno51 board 
**READY**
NO
Signed-off-by: iotvietmember <robotden@gmail.com>
=> mbed Enabled certificate for the VBLUno51 board

tools/export/__init__.py, tools/export/nb/Makefile.tmpl, tools/export/nb/__init__.py, tools/export/nb/configurations.tmpl, tools/export/nb/mbedignore.tmpl, tools/export/nb/project.tmpl
Added a Netbeans Exporter which creates following items:
- `nbproject` Directory
- `nbproject/configurations.xml`
- `nbproject/project.xml`
- `./.mbedignore` (which contains the nbproject Folder)
-  `./Makefile` (Netbeans Makefile)
**READY**
- Linking works and is using the Linker Script
- Code Assistance works with one exclusion in `mbed-os/rtos/TARGET_CORTEX/rtx5/core_cm.h` -> Line 57: #error "Unknown ARM Architecture!"
File `__init__.py`  in `mbed-os\tools\export` is modified and has a new configuration:
- netbeans
NONE
NONE
Execute following command to get a Netbeans Project:
`mbed-cli export -i netbeans`
=> Exporter for Netbeans GCC_ARM

hal/mbed_ticker_api.c
Perform update of the present time in critical section.
**READY**
NO
While working on new lp ticker driver for NRF51_DK board (https://github.com/ARMmbed/mbed-os/pull/5629), some problems with lp ticker has been detected.
Performed test:
```
volatile int cnt = 0;
void isr()
{
cnt++;
}
void test()
{
{
Timer timer;
LowPowerTicker ticker;
timer.start();
ticker.attach_us(isr, 1000);
int val = 0;
int buf = 0;
while(val < 1) {
val = timer.read();
if(val != buf) {
printf("--> val: %d \n", val);
buf = val;
}
}
ticker.detach();
printf("---> cnt: %d \n", cnt);
}
}
```
We expect that isr() function will be executed about 1000 times and exit from while loop is after one second:
```
val: 1
cnt: ¬1000
```
Test results without this fix NRF51_DK/GCC_ARM:
```
[1516363480.03][CONN][RXD] --> val: 3 …
```
=> Provide fix for issue #5835 - Tickers update should be atomic

rtos/TARGET_CORTEX/mbed_rtx_idle.cpp
I could not find a reason from the logs why this locking was present if tickless is enabled. 
Please review
=> RTX idle: sleep without locked deep sleep fix

features/FEATURE_COMMON_PAL/mbed-coap/CHANGELOG.md, features/FEATURE_COMMON_PAL/mbed-coap/mbed-coap/sn_coap_protocol.h, features/FEATURE_COMMON_PAL/mbed-coap/module.json, features/FEATURE_COMMON_PAL/mbed-coap/source/include/sn_coap_protocol_internal.h, features/FEATURE_COMMON_PAL/mbed-coap/source/sn_coap_builder.c, features/FEATURE_COMMON_PAL/mbed-coap/source/sn_coap_protocol.c
This includes check Entity Too Large check for block1 and request server to resend data with supported block size.
New API to control whether coap itself sends a next GET(block2) request or not
Fixes error IOTCLT-2203 mbed-coap does not handle PUT or POST if they indicate a smaller block size preference
**READY*
NO
=> CoAP v4.1.1

targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F746xG/TARGET_NUCLEO_F746ZG/system_clock.c, targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F746xG/device/TOOLCHAIN_ARM_MICRO/stm32f746xg.sct, targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F746xG/device/TOOLCHAIN_ARM_STD/stm32f746xg.sct, targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F746xG/device/TOOLCHAIN_GCC_ARM/STM32F746xG.ld, targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F746xG/device/TOOLCHAIN_IAR/stm32f746xg.icf, targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F767xI/TARGET_NUCLEO_F767ZI/system_clock.c, targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F767xI/device/TOOLCHAIN_ARM_MICRO/stm32f767xi.sct, targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F767xI/device/TOOLCHAIN_ARM_STD/stm32f767xi.sct, targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F767xI/device/TOOLCHAIN_GCC_ARM/STM32F767xI.ld, targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F767xI/device/TOOLCHAIN_IAR/stm32f767xi.icf, targets/TARGET_STM/mbed_overrides.c, targets/targets.json
- Add bootloader support to the **NUCLEO_F746ZG** and **NUCLEO_F767ZI** platforms
- Fix issue #5718 (was related to cache, see questions below)
- Tested OK on these 2 platforms using mbed-os-example-bootloader example
**READY**
**NO**
- We tried first to disable the caches using the macros:
```
SCB_InvalidateICache();
SCB_DisableICache();
SCB_CleanInvalidateDCache();
SCB_DisableDCache();
```
but it didn't work. Do you know why and what is missing ?
- We think that the cache activation should be done in another place for example in the `platform/mbed_application.c` file. What do you think ?
=> STM32F7: Add bootloader support

targets/TARGET_STM/TARGET_STM32L0/device/stm32l0xx_hal_rcc.c, targets/TARGET_STM/TARGET_STM32L1/device/stm32l1xx_hal_rcc.c, targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_rcc.c
This should fix #5830 
When wake up is too early after deep sleep,
it seems that some register didn't have time to be reset.
**READY**
=> STM32LX : HAL_RCC_OscConfig update in PLL configuration

targets/targets.json
Disables RTC for NCS36510 since feature is blocking https://github.com/ARMmbed/mbed-os/pull/5087 from building correctly, and issue will not be resolved soon (https://github.com/ARMmbed/mbed-os/issues/5308).
**READY**
Unblocks https://github.com/ARMmbed/mbed-os/pull/5087
=> Remove RTC as a supported peripheral for NCS36510

targets/TARGET_STM/serial_api.c
Fix an issue with 7-bit data format.
Should fix Issue #5881 
**READY**
NO
=> STM32: fix serial 7bit data format

targets/TARGET_RENESAS/TARGET_RZ_A1XX/TARGET_RZ_A1H/device/cmsis.h
To get cmsis nvic definitions, this header file should be included
in cmsis.h file.
Fixes #5886
@JanneKiiskila @ARMmbed/team-renesas
=> RZ_A1H: cmsis nvic include fix

targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L475xG/device/TOOLCHAIN_IAR/stm32l475xx.icf
DISCO_L475VG_IOT01A has 128 k of SRAM (32k in SRAM2 + 96k in SRAM1)
At the moment, for IAR toolchain, SRAM2 only contains the nvic vector. 
With this PR:
Use the entire SRAM2 with NVIC buffer + stack
Increase HEAP size to 0x10000 in SRAM1
Increase the available SRAM1 by 0x2000
**READY**
I'm working on the wifi driver and I've had memory mapping issues with mbed-tls-client example
=> ST-DISCO_L475VG_IOT01A: Improve SRAM use for IAR toolchain

targets/targets.json
Add DEVICE_HAS TRNG for NRF52_DK in `targets.json`.
**READY**
@marcuschangarm
=> [feature-nrf52] Add TRNG device_has for NRF52_DK

targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/TARGET_MCU_NRF52832/device/TOOLCHAIN_GCC_ARM/NRF52832.ld, targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/TARGET_MCU_NRF52840/device/TOOLCHAIN_GCC_ARM/NRF52840.ld
When linking on GCC the SoftDevice expects certain observer sections to be present.
=> [feature-nrf52] Add GCC linker sections for NRF52 SoftDevice

TESTS/mbed_platform/critical_section/main.cpp
New test suite for critical section
**READY**
~~#5346~~
#5346  - Add Critical Section HAL API specification
=> Test set for critical section

targets/TARGET_STM/TARGET_STM32F4/TARGET_MTB_MTS_DRAGONFLY/PeripheralNames.h, targets/TARGET_STM/TARGET_STM32F4/TARGET_MTB_MTS_DRAGONFLY/PinNames.h, targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F412xG/TARGET_MTB_MXCHIP_EMW3166/PeripheralNames.h, targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F412xG/TARGET_MTB_MXCHIP_EMW3166/PinNames.h, targets/targets.json
Here is a proposition
- to align with other STM32
- and to remove compilation warnings :
[Warning] PeripheralNames.h@38,0: "STDIO_UART" redefined
**READY**
=> MTB_XX : STDIO configuration

.travis.yml
The self-hosted littlefs-fuse testing in Mbed OS is currently dependent on the master of littlefs-fuse, which is a moving target. Locking this to a specific hash will remove this problem. Other options could be to commit the littlefs-fuse wrapper into mbed-os specifically for testing, or remove fuse testing.
see https://github.com/ARMmbed/mbed-os/pull/5903#issuecomment-359792709
cc @theotherjimmy, @0xc0170 
Note: I don't think device testing is needed
=> littlefs: Set specific hash for littlefs-fuse testing in Travis

features/unsupported/tests/mbed/ticker/main.cpp
- The MBED_11 test was failed/unstabled on our test bench since mbed revision 153 / mbed-os-5.6.2
- It was due to the use of printf inside ticker callback. Replacing it with `RawSerial `solved the issue
- More discussion in PR #5842 (closed)
**READY**
NO
=> Fix issue with MBED_11 test (mbed2)

targets/TARGET_NXP/TARGET_LPC408X/TARGET_LPC4088/spi_api.c
The Pin P5_3 (p31) was missing from the NXP LPC4088 SPI PinMap for SSEL.
Adding this Pin allows usage of SPISlave with SSP2 using the SSEL pin.
The pin and its SSP2_SSEL function is both documented in https://os.mbed.com/media/uploads/embeddedartists/lpc4088_qsb_pinning.xlsx as well as in UM10562 LPC408x/407x User manual Rev. 3 — 12 March 2014 chapter 7.4.1.4 Table 90 (https://www.nxp.com/docs/en/user-guide/UM10562.pdf).
Notes:
- This is just a template, so feel free to use/remove the unnecessary things
If this PR changes …
=> NXP LPC4088: Add missing SPI SSEL pin to Pinmap

targets/TARGET_Silicon_Labs/TARGET_EFM32/flash_api.c
Add MSC_Init()/MSC_Deinit() to flash_init()/flash_free() in flash_api.c for TARGET_EFM32. This allows using the FLASH IAP without calling the EFM32 HAL MSC_Init()/MSC_Deinit() functions in the application code.
This increases also the portability of the application code.
Furthermore the using of the FLASH IAP is more straight forward, because the writing and erasing functions in flash_api.c do not throw an error when they are not initialized.
**READY**
NO
=> Add missing EFM32 HAL flash init/deinit function calls

platform/CriticalSectionLock.h
Macro MBED_DEPRECATED_SINCE is defined in platform/mbed_toolchain.h which was not included.
If someone used member functions lock or unlock (which are prefixed with MBED_DEPRECATED_SINCE since some time), there would be a compile error instead of a warning.
Including mbed_toolchain.h fixes that.
**READY**
Use CriticalSectionLock.lock() in a cpp file where CriticalSectionLock.h is included before mbed.h - compile error will occur.
=> CriticalSectionLock: fixing missing include

tools/targets/lint.py
Fix some typos I found in the target linter tool
=> fix typos in lint.py

targets/TARGET_STM/TARGET_STM32F0/serial_device.c
Issue flagged here: https://os.mbed.com/forum/mbed/topic/28545/ 
On some F0 devices, multiple USART are sharing the same IRQ vector and this case was not managed.
Tested on NUCLEO_F091RC and NUCLEO_F070RB boards using two usarts (USART3 and USART4).
**READY**
NO
=> STM32F0: fix issue with usarts sharing the same irq vector

TESTS/mbed_hal/critical_section/critical_section_test.h, TESTS/mbed_hal/critical_section/main.cpp
This PR contains critical section HAL API tests.
Test were created based on documentation provided in PR #5346 
**READY**
NO
~~in order to run these tests #5346 has to be merged first,~~
=> Add tests for critical section HAL API

rtos/TARGET_CORTEX/mbed_rtx_idle.cpp
Remove the assert that the tick count of the OS matches the tick count of the tickless timer as this occurs frequently when debugging. This is because the function svcRtxKernelResumeonly increments the OS's tick count until the next wakeup event so if the device was halted by a debugger past the next wakeup event the tick counts will be out of sync.
=> Remove tickless assert for tick count

TESTS/mbed_drivers/rtc/main.cpp
Add RTC time test.
Test verifies RTC time() and set_time() functions.
READY
NO
=> Add RTC time test.

targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F413xH/TARGET_NUCLEO_F413ZH/PeripheralNames.h, targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F413xH/TARGET_NUCLEO_F413ZH/PinNames.h, targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L433xC/TARGET_NUCLEO_L433RC_P/PeripheralNames.h, targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L433xC/TARGET_NUCLEO_L433RC_P/PinNames.h
#5795 patches are missing for NUCLEO_F413ZH and NUCLEO_L433RC_P
STDIO_UART_TX and STDIO_UART_RX can be now user defined like all other STM32 targets
Thx
**READY**
=> STM32 NUCLEO F413ZH and L433RC : STDIO configuration

features/netsocket/nsapi_dns.cpp
Documentation states that `nsapi_dns_query_multiple` returns the number of
addresses found on success - it was returning 0.
Overloads using `SocketAddress` are relying on the return value, meaning
those calls didn't work at all.
Fixes #5921.
=> Correct return value of nsapi_dns_query_multiple

tools/export/e2studio/__init__.py, tools/export/e2studio/launch5x.tmpl
We have a Open OCD lunch file included in the exporter template. However Open OCD ID has changed 
from _gnuarmeclipse_ to _gnumcueclipse_. Hence this patch adds updates to existing launch file with new ID and also kept the old launch file for e2 studio 5.x compatibility. 
**READY**
NO
Export a project to e2 studio and import in e2 studio 6.x. Launch file doesn't appear on debug configurations dialog.
=> Add OpenOCD 5x launch file to e2 studio and update naming

tools/build_api.py, tools/make.py, tools/memap.py
Looks like this:
```
$ mbed compile -m ARCH_PRO -t GCC_ARM
Building project mbed-os-prettyoutput (ARCH_PRO, GCC_ARM)
Scan: .
Scan: env
Scan: mbed
Scan: FEATURE_LWIP
Text 70.5KB Data 2.72KB BSS 7.43KB                 ROM 73.2KB RAM 10.1KB
ROM [|||||||                                             ]  73.2KB/512KB
RAM [||||||||||||||||                                    ]   10.1KB/32KB
Image: BUILD/ARCH_PRO/GCC_ARM/mbed-os-prettyoutput.bin
```
This is an alternative to the pretty table output that provides useful information about memory consumption without using as much screen real-estate as the pretty table output. You may also note this matches what is displayed on the website, which is an added plus.
cc @theotherjimmy, @0xc0170
=> Add pretty bars for compile output

tools/export/nb/__init__.py
Fixed a  bug on multiple Sub-Directories with same name.
Was not discovered correctly before.
Problem occured on path with same name like:
storage/filesystem/littlefs/littlefs
**READY**
mbed export -i netbeans
=> Netbeans Exporter Bugfix

targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L432xC/device/stm32l432xx.h, targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L433xC/device/stm32l433xx.h, targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L475xG/device/stm32l475xx.h, targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L476xG/device/stm32l476xx.h, targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L486xG/device/stm32l486xx.h, targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L496xG/device/stm32l496xx.h, targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_uart_ex.c, targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_uart_ex.h
Issue found by @marcemmers in #5941 
Some functions were missing in L4 CUBE HAL drivers to enable/disable UART Clock in Stop Mode
**READY**
=> STM32L4 : add missing ST HAL UART functions

targets/TARGET_NORDIC/TARGET_NRF5/TARGET_MCU_NRF52832/TARGET_MTB_UBLOX_NINA_B1/PinNames.h, targets/TARGET_NORDIC/TARGET_NRF5/TARGET_MCU_NRF52832/TARGET_MTB_UBLOX_NINA_B1/device.h, targets/targets.json
Adding ublox NINA B1 as a new target.
Needs addition of new HW in CI.
cc @screamerbg  @chris-styles @studavekar
=> Adding MTB ublox NINA-B1 as a new target

features/filesystem/bd/BlockDevice.h, features/filesystem/bd/ChainingBlockDevice.cpp, features/filesystem/bd/ChainingBlockDevice.h, features/filesystem/bd/ExhaustibleBlockDevice.cpp, features/filesystem/bd/ExhaustibleBlockDevice.h, features/filesystem/bd/MBRBlockDevice.cpp, features/filesystem/bd/MBRBlockDevice.h, features/filesystem/bd/ObservingBlockDevice.cpp, features/filesystem/bd/ObservingBlockDevice.h, features/filesystem/bd/ProfilingBlockDevice.cpp, features/filesystem/bd/ProfilingBlockDevice.h, features/filesystem/bd/ReadOnlyBlockDevice.cpp, features/filesystem/bd/ReadOnlyBlockDevice.h, features/filesystem/bd/SlicingBlockDevice.cpp, features/filesystem/bd/SlicingBlockDevice.h, features/filesystem/littlefs/LittleFileSystem.cpp
Right now, all block devices must effectively sync data on read/program, or else the power resilience gauruntees of littlefs don't hold true.
This is fine with the current state of the block device, which just write through any buffers provided (since external flash is much cheaper than internal caching and speed is a secondary concern to code footprint). However, in order to provide a decent FTL a syncing mechanic is necessary to ensure storage is up to date with in-flight data.
``` cpp
class BlockDevice {
/** Ensure data on storage is in sync with the driver
*
*  @return         0 on success or a negative error code on failure
*/
virtual int sync();
}
```
cc @deepikabhavnani
=> bd: Add sync function to the block device API

targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L443xC/device/stm32l443xx.h
PR #5947 requires some additional defines.
This PR completes #5904 and fixes the latent "conflict".
READY
=> fixes a silent conflict with PR #5947

features/mbedtls/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F439xI/mbedtls_device.h, features/mbedtls/targets/TARGET_STM/md5_alt.c, features/mbedtls/targets/TARGET_STM/sha1_alt.c, features/mbedtls/targets/TARGET_STM/sha256_alt.c
Fix #5079 
Support of call to mbedtls_x_finish without calling mbedtls_x_update.
**READY**
Before the PR: failure occurs in case of an empty input and mbedtls_xx_update is not called between xxx_start and xxx_finish
After this PR: 
- SHA1 / SHA256 / MD5 hardware acceleration is activated for STM32F439xI
- An empty input can be encrypted correctly even is the call to mbedtls_xxx_update has been omited
~~[] To do: test MD5, as it is not compiled in mbed-os (I could not find a way to activate it, can someone help me for this ?)~~ [edit 12.14.2017 -> MD5 link issue is now fixed.]
Use the test available in #5079
=> Fix #5079. Support of call to mbedtls_x_finish without calling mbedtls_x_update

targets/TARGET_STM/TARGET_STM32L0/TARGET_STM32L0x2xZ/TARGET_CMWX1ZZABZ_078/PeripheralNames.h, targets/TARGET_STM/TARGET_STM32L0/TARGET_STM32L0x2xZ/TARGET_CMWX1ZZABZ_078/PeripheralPins.c, targets/TARGET_STM/TARGET_STM32L0/TARGET_STM32L0x2xZ/TARGET_CMWX1ZZABZ_078/PinNames.h, targets/TARGET_STM/TARGET_STM32L0/TARGET_STM32L0x2xZ/TARGET_CMWX1ZZABZ_078/system_clock.c, targets/TARGET_STM/TARGET_STM32L0/TARGET_STM32L0x2xZ/device/TOOLCHAIN_ARM_STD/startup_stm32l082xZ.S, targets/TARGET_STM/TARGET_STM32L0/TARGET_STM32L0x2xZ/device/TOOLCHAIN_ARM_STD/stm32l082xZ.sct, targets/TARGET_STM/TARGET_STM32L0/TARGET_STM32L0x2xZ/device/TOOLCHAIN_GCC_ARM/STM32L082xZ.ld, targets/TARGET_STM/TARGET_STM32L0/TARGET_STM32L0x2xZ/device/TOOLCHAIN_GCC_ARM/startup_stm32l082xZ.S, targets/TARGET_STM/TARGET_STM32L0/TARGET_STM32L0x2xZ/device/TOOLCHAIN_IAR/startup_stm32l082xZ.S, targets/TARGET_STM/TARGET_STM32L0/TARGET_STM32L0x2xZ/device/TOOLCHAIN_IAR/stm32l082xZ.icf, targets/TARGET_STM/TARGET_STM32L0/TARGET_STM32L0x2xZ/device/cmsis.h, targets/TARGET_STM/TARGET_STM32L0/TARGET_STM32L0x2xZ/device/cmsis_nvic.h, targets/TARGET_STM/TARGET_STM32L0/TARGET_STM32L0x2xZ/device/hal_tick.h, targets/TARGET_STM/TARGET_STM32L0/TARGET_STM32L0x2xZ/device/stm32l082xx.h, targets/TARGET_STM/TARGET_STM32L0/TARGET_STM32L0x2xZ/device/stm32l0xx.h, targets/TARGET_STM/TARGET_STM32L0/TARGET_STM32L0x2xZ/device/system_stm32l0xx.h, targets/TARGET_STM/TARGET_STM32L0/TARGET_STM32L0x2xZ/objects.h, targets/TARGET_STM/mbed_rtx.h, targets/targets.json, tools/build_travis.py, tools/export/sw4stm32/__init__.py
This PR add support for the STM32L082CZ and murata's CMWX1ZZABZ-078  module.
This was tested with @kivaisan on [mbed-os-example-lora](/ARMmbed/mbed-os-example-lora)
WORK IN PROGRESS
- #5937
=> add support for the murata's module CMWX1ZZABZ-078 based on STM32L0

targets/TARGET_STM/TARGET_STM32F0/serial_device.c, targets/TARGET_STM/TARGET_STM32F1/serial_device.c, targets/TARGET_STM/TARGET_STM32F2/serial_device.c, targets/TARGET_STM/TARGET_STM32F3/serial_device.c, targets/TARGET_STM/TARGET_STM32F4/serial_device.c, targets/TARGET_STM/TARGET_STM32F7/serial_device.c, targets/TARGET_STM/TARGET_STM32L0/serial_device.c, targets/TARGET_STM/TARGET_STM32L1/serial_device.c, targets/TARGET_STM/TARGET_STM32L4/serial_device.c, targets/TARGET_STM/serial_api.c
- There was an issue with the `serial irq index` used in the STM32 serial api implementation. On some platforms the indexes was wrong and this results to wrong usart access.
- The issue has been flagged in #5916 and #5931
- A fix has been found by @marcemmers (thanks again!) and done for STM32L0 devices in PR #5917. But this PR has been closed due to this one covering all STM32 devices.
**READY**
NO
@marcemmers can you please test it in your application for the STM32L0 ?
=> STM32: Fix usart irq index

tools/build_api.py, tools/config/__init__.py, tools/export/gnuarmeclipse/__init__.py, tools/test/config/bootloader_missing/bootloaders/mbed_lib.json, tools/test/config/bootloader_missing/test_data.json, tools/toolchains/__init__.py
This PR lets libraries and targets configure boot loader parameters like any other parameter. This allows a release of a boot loader as an mbed library, with an `mbed_lib.json` that contains links to the boot loader binaries.
The following patch, to `mbed-os-example-bootloader-blinky`, shows how this allows a standalone `bootloader` directory to contain all information required to merge a boot loader.
```diff
diff --git a/bootloader/mbed_lib.json b/bootloader/mbed_lib.json
new file mode 100644
index 0000000..eea6b25
--- /dev/null
+++ b/bootloader/mbed_lib.json
@@ -0,0 +1,24 @@
+{
+    "name": "bootloader_images",
+    "target_overrides": {
+        "K64F": {
+            "target.bootloader_img": "K64F.bin"
+        },
+        "NUCLEO_F429ZI": {
+            "target.bootloader_img": …
```
=> Let libraries, targets configure bootloader

tools/export/sw4stm32/__init__.py
The check was being inherited from GNUARMEclipse, which only checks for
toolchain support. This updated check takes the `BOARDS` dict into account
=> Correct SW4STM32 supported check

tools/export/vscode/__init__.py
Prevents overwriting VS Code files which are customizable by the user. `launch.json` is used to define the debugger and target, `settings.json` includes all possible project-specific VS Code settings, `tasks.json` defines the build tasks.
The only file which is still being overwritten is the list of includes: `c_cpp_properties.json`
Fixes https://github.com/ARMmbed/mbed-os/issues/5958
**READY**
NO
=> VS Code exporter: do not overwrite existing (launch|settings|tasks).json

platform/mbed_preprocessor.h
Added macros: 
1. Calculate string length MBED_STRLEN()
2. Calculate variable arguments MBED_COUNT_VA_ARGS()
=> Pre-processor common macro addition 

targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F746xG/TARGET_NUCLEO_F746ZG/system_clock.c, targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F746xG/device/TOOLCHAIN_ARM_MICRO/stm32f746xg.sct, targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F746xG/device/TOOLCHAIN_ARM_STD/stm32f746xg.sct, targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F746xG/device/TOOLCHAIN_GCC_ARM/STM32F746xG.ld, targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F746xG/device/TOOLCHAIN_IAR/stm32f746xg.icf, targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F767xI/TARGET_NUCLEO_F767ZI/system_clock.c, targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F767xI/device/TOOLCHAIN_ARM_MICRO/stm32f767xi.sct, targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F767xI/device/TOOLCHAIN_ARM_STD/stm32f767xi.sct, targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F767xI/device/TOOLCHAIN_GCC_ARM/STM32F767xI.ld, targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F767xI/device/TOOLCHAIN_IAR/stm32f767xi.icf, targets/TARGET_STM/mbed_overrides.c, targets/targets.json
- First trial done in PR #5821 but reverted in PR #5932 due to a sync issue with CI tests on ARM side. Not reproduce on my side.
- The only thing I changed compared to the previous PR is the Cache initialization which is done first in the mbed_sdk_init function.
Waiting ci-test result to see if sync issue is still present or not.
=> STM32F7: Add bootloader support (new trial)

targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_SDK_14_2/TARGET_SOFTDEVICE_S132/mbed_lib.json, targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_SDK_14_2/TARGET_SOFTDEVICE_S140/mbed_lib.json, targets/targets.json
SoftDevice can be swapped even easier now:
"*": {
"target.extra_labels_remove": ["SOFTDEVICE_COMMON", "SOFTDEVICE_S140"],
"target.extra_labels_add": ["SOFTDEVICE_NONE"]
}
}
=> [feature-nrf528xx] Switch to managed bootloader for SoftDevice merge on NRF52

tools/config/definitions.json
This will prevent a user from doing the invalid:
```json
{
"*": {
"foo": {},
"foo.foo.foo": true
}
}
```
=> Restrict target_overrides usage

targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_spi_ex.c, targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_spi_ex.h, targets/TARGET_STM/stm_spi_api.c
In STM32F0/F3/F7/L4, there is a FIFO that needs to be flushed before starting transfers.
NB: some HAL files were missing for STM32F7 (ST_INTERNAL_REF 43358)
**READY**
=> STM32 SPI ASYNC - Add FIFO flush before transfer

rtos/ConditionVariable.cpp, rtos/ConditionVariable.h, rtos/Kernel.cpp, rtos/Kernel.h, rtos/Mutex.cpp, rtos/Mutex.h, rtos/Semaphore.cpp, rtos/Semaphore.h, rtos/Thread.cpp, rtos/Thread.h
Give C++ access to the RTOS's absolute timebase, reducing the need to run private Timers and similar. Allows wait_until functionality, and makes it easier to avoid time drift.
Explicitly state that ticks are milliseconds in mbed OS, despite CMSIS-RTOS 2 permitting different tick rates.
Try to cover over the breaking API change potentially upcoming in CMSIS-RTOS 2.1.1,
when it reduces the tick count from 64-bit to 32-bit. (See https://github.com/ARM-software/CMSIS_5/issues/277)
Add "wait_until" methods to Thread, ConditionVariable, Semaphore and Mutex.
See also #3648 (wait_until for condition variables) and #5378 (EventQueue should use RTOS tick count).
=> Add absolute millisecond tick count to RTOS classes

targets/targets.json
ff_lpc546xx currently inherits from target lpc546xx. This results in error in mbed online compiler:
`Error: Library name 'platform' is not unique (defined in '/extras/mbed_7130f322cb7e/TARGET_LPC546XX/mbed_lib.json' and '/extras/mbed_7130f322cb7e/TARGET_FF_LPC546XX/mbed_lib.json')`
when compiling examples with mbed library (compiling with mbed-os works fine).
=> lpc546xx and ff_lpc546xx: create parent object MCU_LPC546XX

features/TESTS/filesystem/heap_block_device/main.cpp, features/TESTS/filesystem/mbr_block_device/main.cpp, features/TESTS/filesystem/util_block_device/main.cpp, targets/TARGET_STM/TARGET_STM32L1/TARGET_MTB_MTS_XDOT/PeripheralNames.h, targets/TARGET_STM/TARGET_STM32L1/TARGET_MTB_MTS_XDOT/PeripheralPins.c, targets/TARGET_STM/TARGET_STM32L1/TARGET_MTB_MTS_XDOT/PinNames.h, targets/TARGET_STM/TARGET_STM32L1/TARGET_MTB_MTS_XDOT/device.h, targets/TARGET_STM/TARGET_STM32L1/TARGET_MTB_MTS_XDOT/device/TOOLCHAIN_ARM_MICRO/startup_stm32l151xc.S, targets/TARGET_STM/TARGET_STM32L1/TARGET_MTB_MTS_XDOT/device/TOOLCHAIN_ARM_MICRO/stm32l151rc.sct, targets/TARGET_STM/TARGET_STM32L1/TARGET_MTB_MTS_XDOT/device/TOOLCHAIN_ARM_STD/startup_stm32l151xc.S, targets/TARGET_STM/TARGET_STM32L1/TARGET_MTB_MTS_XDOT/device/TOOLCHAIN_ARM_STD/stm32l151rc.sct, targets/TARGET_STM/TARGET_STM32L1/TARGET_MTB_MTS_XDOT/device/TOOLCHAIN_GCC_ARM/STM32L151XC.ld, targets/TARGET_STM/TARGET_STM32L1/TARGET_MTB_MTS_XDOT/device/TOOLCHAIN_GCC_ARM/startup_stm32l151xc.S, targets/TARGET_STM/TARGET_STM32L1/TARGET_MTB_MTS_XDOT/device/TOOLCHAIN_IAR/startup_stm32l152xc.S, targets/TARGET_STM/TARGET_STM32L1/TARGET_MTB_MTS_XDOT/device/TOOLCHAIN_IAR/stm32l152xc.icf, targets/TARGET_STM/TARGET_STM32L1/TARGET_MTB_MTS_XDOT/device/cmsis.h, targets/TARGET_STM/TARGET_STM32L1/TARGET_MTB_MTS_XDOT/device/cmsis_nvic.h, targets/TARGET_STM/TARGET_STM32L1/TARGET_MTB_MTS_XDOT/device/hal_tick.h, targets/TARGET_STM/TARGET_STM32L1/TARGET_MTB_MTS_XDOT/device/stm32l151xc.h, targets/TARGET_STM/TARGET_STM32L1/TARGET_MTB_MTS_XDOT/device/stm32l1xx.h, targets/TARGET_STM/TARGET_STM32L1/TARGET_MTB_MTS_XDOT/device/system_clock.c, targets/TARGET_STM/TARGET_STM32L1/TARGET_MTB_MTS_XDOT/device/system_stm32l1xx.h, targets/TARGET_STM/TARGET_STM32L1/TARGET_MTB_MTS_XDOT/objects.h, targets/TARGET_STM/TARGET_STM32L1/TARGET_MTB_MTS_XDOT/xdot_eeprom.c, targets/TARGET_STM/TARGET_STM32L1/TARGET_MTB_MTS_XDOT/xdot_eeprom.h, targets/TARGET_STM/TARGET_STM32L1/TARGET_MTB_MTS_XDOT/xdot_low_power.c, targets/TARGET_STM/TARGET_STM32L1/TARGET_MTB_MTS_XDOT/xdot_low_power.h, targets/targets.json
Adding MTS xDOT (MTB) as a new target.
**READY**
@0xc0170 , attaching GT logs below. GCC and ARMCC are Passing while IAR is failing due to low RAM (32K) on this target. Tagging @geky for pointers on this.
[MTB_xDOT_GT_Log_ARMCC_Pass.txt](https://github.com/ARMmbed/mbed-os/files/1678794/MTB_xDOT_GT_Log_ARMCC_Pass.txt)
[MTB_xDOT_GT_Log_GCC_Pass.txt](https://github.com/ARMmbed/mbed-os/files/1678796/MTB_xDOT_GT_Log_GCC_Pass.txt)
[MTB_xDOT_GT_Log_IAR_Fail.txt](https://github.com/ARMmbed/mbed-os/files/1678797/MTB_xDOT_GT_Log_IAR_Fail.txt)
cc @screamerbg @chris-styles @studavekar
=> Adding MTB_MTS_XDOT as a new target

TESTS/mbed_platform/FileHandle/TestFile.h, TESTS/mbed_platform/FileHandle/main.cpp
This PR contains Mbed retargeting systems tests for C library FILE functions
NO
#5714
=> Add FileHandle tests

tools/export/makefile/__init__.py, tools/export/uvision/__init__.py, tools/toolchains/arm.py
Fixes #5796
Fix for targets which include the c preprocessor in the ARM and ARMC6 scatter file.
**READY**
NO
1. Pull the mbed-os-example-blinky app
2. Import the latest mbed-os (>= mbed-os-5.5.4)
3. Compile with either the ARM or ARMC6 compiler and target the MultiTech xDot
(e.g. mbed compile -t ARMC6 -m xdot_l151cc)
4. Verify the app builds
=> ARMC5+6: Specify CPU for ARM scatter file preprocessor

tools/build_api.py
Resolves #6005
@marcuschangarm
=> Take OUTPUT_EXT into account in managed bl

targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L476xG/device/TOOLCHAIN_IAR/stm32l476xx.icf, targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L486xG/device/TOOLCHAIN_IAR/stm32l486xx.icf
- These devices have 2 SRAM areas
- Before this PR only SRAM1 was used for Stack and Heap
- Now both SRAM are used: Stack placed in SRAM2 and Heap in SRAM1
- Continuation of PR #5844 done for STM32L475 device
**READY**
Tested OK on NUCLEO_L476RG
NO
Fixes https://github.com/ARMmbed/mbed-os/issues/5859.
=> STM32L476/486: Improve SRAM usage for IAR

targets/targets.json
Add missing flash device feature to the K82F board
**READY**
NO
None.
None.
=> Add missing flash device feature to the K82F board

tools/config/__init__.py, tools/test/config/config_test.py
An offset was used as if it were an address, which breaks some targets
Testing included
=> Correct auto-sizing last region of bl

platform/FileHandle.cpp, platform/FileHandle.h, platform/mbed_lib.json, platform/mbed_retarget.cpp, platform/mbed_retarget.h
To complete the move to POSIX-ness and FileHandle-ness, close the loop by reworking mbed_retarget.cpp so that everything is a `FileHandle`.
This adds:
* POSIX file APIs - `open`/`close`/`read`/`write`/`lseek`/`isatty`/`fsync`/`fstat`/`fdopen`/`poll`.
* The ability to have buffered `stdin`/`stdout` using `UARTSerial` with a simple JSON change.
* The ability for target or application to change stdin/stdout/stderr to be a custom `FileHandle` by overriding weak functions..
* The option of CRLF conversion for any `isatty()` stream, not just stdin/stdout/stderr.
=> Complete mbed_retarget FileHandle rework

targets/TARGET_RENESAS/TARGET_RZ_A1XX/TARGET_GR_LYCHEE/trng_api_esp32.cpp
Related to the review of #5857, I fixed the TRNG function for GR-LYCHEE.
- I modified to zeroize "recv_data" before the function return.
- I added the processing that check the return value of I2C.read function. If return value is error, "output"  is zeroized before  function return.
https://github.com/ARMmbed/mbed-os/pull/5857
@cmonr 
Could you revert #5967 when this PR passed?
=> RZ_A1LU: Fix TRNG function

tools/toolchains/gcc.py
GCC_ARM throws warning if both architecture and core are set (though correct). If CPU option is set correctly, architecture is set by compiler itself.
@0xc0170
=> M33: -march not required if -mcpu is set

TESTS/mbed_drivers/ticker/main.cpp
This PR contains fix for mbed_drivers-ticker tests.
Despite the test was always green there was hidden bug in `test_case_2x_callbacks` subtest detected in #5955 and #5892. 
In effect of this bug (source code 1):
- `ticker_callback_1_switch_to_2` was called only once
- `ticker2` was never been fired because it was repeatedly detached just before fire and attached again
Fix for this bug (source code 2) showed that time measure with repeatedly rescheduled ticker is not accurate. When we use ticker without rescheduling (like in `test_case_1x_ticker`) ticker callback is executed within ticker interval time - not extra time is added to ticker interval until the callback execution time is less then ticker interval time.
Test `test_case_2x_callbacks` (after fix - source code 2) at each …
=> Ticker tests fix

features/FEATURE_COMMON_PAL/mbed-coap/CHANGELOG.md, features/FEATURE_COMMON_PAL/mbed-coap/mbed-coap/sn_coap_protocol.h, features/FEATURE_COMMON_PAL/mbed-coap/module.json, features/FEATURE_COMMON_PAL/mbed-coap/source/sn_coap_protocol.c
Add new API to remove sent blockwise message from the linked list.
This change is related to ticket:
https://jira.arm.com/browse/IOTCLT-2376
**READY**
=> Update mbed-coap to version 4.2.0

platform/CThunk.h
Cortex-M23 doesn't support ARMv8-M Main Extension and so doesn't support:
```
ldm  r0, {r0, r1, r2, pc}
```
Fix it by going Cortex-M0/M0+ way:
```
ldm  r0, {r0, r1, r2, r3}
bx   r3
```
@cyliangtw @deepikabhavnani
=> M23: Fix CThunk error on Cortex-M23

features/nanostack/FEATURE_NANOSTACK/mbed-mesh-api/mbed-mesh-api/MeshInterfaceNanostack.h, features/nanostack/FEATURE_NANOSTACK/mbed-mesh-api/mbed-mesh-api/ThreadInterface.h, features/nanostack/FEATURE_NANOSTACK/mbed-mesh-api/source/MeshInterfaceNanostack.cpp, features/nanostack/FEATURE_NANOSTACK/mbed-mesh-api/source/ThreadInterface.cpp, features/nanostack/FEATURE_NANOSTACK/mbed-mesh-api/source/include/thread_tasklet.h, features/nanostack/FEATURE_NANOSTACK/mbed-mesh-api/source/thread_tasklet.c
Notes:
New setters for mesh-api to be used by the Thread network.
Needed by customers when deploying devices for commissioning.
NO
=> Mesh-api setters for eui64 and pskd

targets/TARGET_NORDIC/TARGET_NRF5/TARGET_MCU_NRF51822_UNIFIED/TARGET_MTB_LAIRD_BL600/PinNames.h, targets/TARGET_NORDIC/TARGET_NRF5/TARGET_MCU_NRF51822_UNIFIED/TARGET_MTB_LAIRD_BL600/device.h, targets/targets.json
Adding Laird BL600 as a new target.
**READY**
@0xc0170 .. attaching GT logs below. Please note from the logs that only 1 test case "Test timers: 2x callbacks" in the suite "mbed-os-tests-mbed_drivers-ticker" is failing in both GCC and IAR while rest all tests are passing. ARMCC however passes everything. Any thoughts on this will be helpful. Thank you.
[MTB_BL600_GT_ARMCC_Pass.txt](https://github.com/ARMmbed/mbed-os/files/1686555/MTB_BL600_GT_ARMCC_Pass.txt)
[MTB_BL600_GT_GCC_Fail.txt](https://github.com/ARMmbed/mbed-os/files/1686556/MTB_BL600_GT_GCC_Fail.txt)
[MTB_BL600_GT_IAR_Fail.txt](https://github.com/ARMmbed/mbed-os/files/1686557/MTB_BL600_GT_IAR_Fail.txt)
cc @screamerbg @chris-styles @studavekar
=> Adding LAIRD_BL600 MTB

targets/TARGET_RENESAS/TARGET_RZ_A1XX/TARGET_GR_LYCHEE/device/inc/RZ_A1LU.h, targets/TARGET_RENESAS/TARGET_RZ_A1XX/TARGET_RZ_A1H/device/inc/RZ_A1H.h
Renesas mbed boards incorporate NVIC Wrapper because Cortex-A9 use GIC. For example, `NVIC_SystemReset()` is defined in `nvic_wrapper.c` and declared in `nvic_wrapper.h`.
Because I removed one of include processing accidentally, I fixed the lack.
In relation to Issue #5886.
=> Fix NVIC Wrapper include for Renesas

features/filesystem/fat/FATFileSystem.cpp
Resolves the compiler warnings first mentioned [here](https://github.com/ARMmbed/mbed-os/pull/5503#issuecomment-356636356):
../mbed-os/features/filesystem/fat/FATFileSystem.cpp: In member function 'virtual void FATFileSystem::dir_seek(mbed::fs_dir_t, off_t)':
../mbed-os/features/filesystem/fat/FATFileSystem.cpp:661:16: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
if (offset < dh->dptr) {
~~~~~~~^~~~~~~~~~
../mbed-os/features/filesystem/fat/FATFileSystem.cpp:664:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
while (dh->dptr < offset) {
~~~~~~~~~^~~~~~~~
I don't actually understand how `dir_seek()` is doing its job, though. Can someone explain?
=> fix compiler warning

targets/TARGET_STM/serial_api.c
Working on using the LPUART in stop mode.
Always switching to LSE when available when baudrates are below or equal to 9600.
This is at least still blocked by the `SerialBase::attach()` where `sleep_manager_lock_deep_sleep()` is called.
This breaks when compiling on an STM32L4 because the HAL doesn't have the function `HAL_UARTEx_EnableClockStopMode()`. The HAL should have the same function as the STM32L0 has because the peripheral also has the same settings. For example, see chapter 41.4.11 of the ST RM0351 and the UCESM bit in CR3.
=> STM32L0/4 Enable use of LPUART in stop mode

features/FEATURE_BLE/ble/pal/GapTypes.h
Fix programming error highlighted by #5993 .
**READY**
NO
#5993
=> Ble: fix size function in advertising_data_t and address_t.

.gitignore
This PR adds some files to the .gitignore list :
- `.mbedls-mock.lock` : generated by `mbedls -m id:name`
- `.hypothesis` : generated by api_tests
- `.cache` : generated by pytest
- `tags` : generated by ctags
READY
=> add few files to gitignore list

features/TESTS/filesystem/multipart_fat_filesystem/main.cpp, features/filesystem/bd/MBRBlockDevice.cpp, features/filesystem/fat/FATFileSystem.cpp
Regression after ChanFS update ([here](https://github.com/ARMmbed/mbed-os/pull/5490)): Due to parameter changes in the f_mkfs function, the option to use a separate block for MBR (FDISK) was turned back on. This should be off (SFD) as it conflicts with an explicit MBR when using the MBRBlockDevice.
For more info see https://github.com/ARMmbed/mbed-os/pull/3936/commits/d1468a68ab123de353ea83ad93b07db267408602
I also added a test that prevents this regression in the future, but at the moment it can't run in CI due to memory restrictions. (related: https://github.com/ARMmbed/mbed-os/issues/6008, [IOTMORF-2062](https://jira.arm.com/browse/IOTMORF-2062))
cc @deepikabhavnani 
should fix https://github.com/ARMmbed/mbed-os/issues/5999
=> fatfs: Remove extra MBR block

tools/build_api.py
The introduction of pretty-bar had broken the handling of
"mbed compile"'s "--stats-depth" argument. No matter what one gave
as parameter to it, the result output is just using the default 2.
Fix the logic in build_api.
**READY**
NO
<none>
<none>
```"mbed compile -m K64F -t GCC_ARM --stats-depth 1"``` and ```"mbed compile -m K64F  -t GCC_ARM --stats-depth 10"``` both give same output on current Mbed OS master. This PR fixes the parameter handing.
=> tools: build: fix handing of "--stats-depth"

targets/TARGET_Realtek/TARGET_AMEBA/TARGET_RTL8195A/serial_api.c
This PR fixes issue #5805. The changes have been made only in one file.
The "CONFIG_MBED_ENABLED" macro has been put so that the software is compatible with our own internal SDK.
The other changes is to add support for loguart hardware in the normal serial api. 
**READY/**
NO
=> fix for issue "serial example callback not working"

targets/TARGET_NORDIC/TARGET_NRF5/TARGET_MCU_NRF51822_UNIFIED/TARGET_OSHCHIP/PinNames.h, targets/TARGET_NORDIC/TARGET_NRF5/TARGET_MCU_NRF51822_UNIFIED/TARGET_OSHCHIP/device.h, targets/targets.json
Add a target for the [OSHChip](http://oshchip.org/), a miniature nRF51822 board, along with pin name definitions
The documentation is confusing regarding the use of config parameters in target definitions. I had to read through the python code to discover the necessary key was `overrides` and not `target_overrides`. The documentation should probably be updated to include more information on this. This is being recified in ARMMbed/handbook#398
=> add OSHChip as an mbed target

tools/detect_targets.py
As mut['mcu'] can be "None" on unknown targets, the detect_targets script crashes when one of these boards is connected.
This happens when "mbed-cli detect -vv" is ran when a STEVAL-3DP001V1 board is connected. Which does not provide a html file with a target_id, and thus cannot be looked up in the mbedls platform database.
http://www.st.com/en/evaluation-tools/steval-3dp001v1.html
Notes:
- This is just a template, so feel free to use/remove the unnecessary things
If this PR changes any APIs or behaviors, give a short …
=> Prevent detect_targets.py tool script from crashing on known targets

hal/mbed_ticker_api.c
When ticker is not driven by the 1 MHz clock and HAL driver need to perform conversion between microseconds and ticks, then the interrupt might be scheduled in the past. For details see issue https://github.com/ARMmbed/mbed-os/issues/6054.
This patch provides fix for such case. While scheduling next interrupt an interrupt is fired immediately when ticker last read tick is equal to the calculated tick when interrupt should be generated.
**READY**
NO
branch | PR
ARMmbed:feature-hal-spec-ticker | [https://github.com/ARMmbed/mbed-os/pull/5629]()
ARMmbed:feature-hal-spec-ticker| [https://github.com/ARMmbed/mbed-os/pull/6052]()
=> Fix for issue #6054 - interrupts scheduled in the past.

targets/TARGET_NUVOTON/TARGET_M451/rtc_api.c, targets/TARGET_NUVOTON/TARGET_M480/rtc_api.c, targets/TARGET_NUVOTON/TARGET_NANO100/rtc_api.c, targets/TARGET_NUVOTON/TARGET_NUC472/rtc_api.c
This PR includes rework on RTC. H/W RTC just supports year range 2000~2099, but time/set_time requires POSIX time which starts from 1970. The rework fixes it by using H/W RTC to keep elapsed time since some time point rather than real date time.
It updates the following Nuvoton targets:
- NUMAKER_PFM_NUC472
- NUMAKER_PFM_M453
- NUMAKER_PFM_M487
- NUMAKER_PFM_NANO130
https://github.com/ARMmbed/mbed-os/pull/6028
=> Nuvoton: Rework RTC

rtos/TARGET_CORTEX/mbed_rtx_conf.h, rtos/TARGET_CORTEX/rtx5/RTX/Config/RTX_Config.h, rtos/TARGET_CORTEX/rtx5/RTX/Source/rtx_lib.c
Secure functions were not accessible from Timer/Idle thread this PR should fix that with changes from CMSIS and config options in mbed-os
Pulling in https://github.com/ARM-software/CMSIS_5/commit/d20b8aad7f5e4188608ff0c26246cc6e4961b1ba#diff-7467c87f859f0e1a8e5f93ef0c118c43
Resolves: https://github.com/ARM-software/CMSIS_5/issues/252
@bulislaw - I am not sure if we should add conf options (MBED_CONF_APP_IDLE_THREAD_TZ_MOD_ID / MBED_CONF_APP_TIMER_THREAD_TZ_MOD_ID) or simply set OS_TIMER_THREAD_TZ_MOD_ID / 
OS_IDLE_THREAD_TZ_MOD_ID as 1.
=>  RTX changes pulled in from d20b8aa 

rtos/TARGET_CORTEX/rtx5/RTX/Source/TOOLCHAIN_ARM/TARGET_M23/irq_armv8mbl.S, rtos/TARGET_CORTEX/rtx5/RTX/Source/TOOLCHAIN_ARM/TARGET_M23/irq_armv8mbl_ns.S, rtos/TARGET_CORTEX/rtx5/RTX/Source/TOOLCHAIN_ARM/TARGET_M33/irq_armv8mml.S, rtos/TARGET_CORTEX/rtx5/RTX/Source/TOOLCHAIN_ARM/TARGET_M33/irq_armv8mml_ns.S, rtos/TARGET_CORTEX/rtx5/RTX/Source/TOOLCHAIN_GCC/TARGET_M23/irq_armv8mbl.S, rtos/TARGET_CORTEX/rtx5/RTX/Source/TOOLCHAIN_GCC/TARGET_M23/irq_armv8mbl_ns.S, rtos/TARGET_CORTEX/rtx5/RTX/Source/TOOLCHAIN_GCC/TARGET_M33/irq_armv8mml.S, rtos/TARGET_CORTEX/rtx5/RTX/Source/TOOLCHAIN_GCC/TARGET_M33/irq_armv8mml_fp.S, rtos/TARGET_CORTEX/rtx5/RTX/Source/TOOLCHAIN_GCC/TARGET_M33/irq_armv8mml_fp_ns.S, rtos/TARGET_CORTEX/rtx5/RTX/Source/TOOLCHAIN_GCC/TARGET_M33/irq_armv8mml_ns.S, rtos/TARGET_CORTEX/rtx5/RTX/Source/TOOLCHAIN_IAR/TARGET_M23/irq_armv8mbl.S, rtos/TARGET_CORTEX/rtx5/RTX/Source/TOOLCHAIN_IAR/TARGET_M23/irq_armv8mbl_common.S, rtos/TARGET_CORTEX/rtx5/RTX/Source/TOOLCHAIN_IAR/TARGET_M23/irq_armv8mbl_ns.S, rtos/TARGET_CORTEX/rtx5/RTX/Source/TOOLCHAIN_IAR/TARGET_M33/irq_armv8mml.S, rtos/TARGET_CORTEX/rtx5/RTX/Source/TOOLCHAIN_IAR/TARGET_M33/irq_armv8mml_ns.S, tools/importer/cmsis_importer.json, tools/toolchains/gcc.py
CMSIS repo does not support pre-processor defines, hence multiple assembly files are added for secure/non-secure and floating point tools.
Mbed OS tools support assembly file pre-processing, but the build system does not support multiple assembly files for each target, hence updating the assembly files.
@0xc0170 @bulislaw 
Once this PR is merged to the master, SHA should be recorded in `cmsis_importer.json` script so that files are not over-written in next CMSIS update.
=> RTX5: Pre-processor defines used for assembly

targets/targets.json
=> STM32F429ZI add SERIAL_ASYNCH

targets/TARGET_NUVOTON/TARGET_M451/lp_ticker.c, targets/TARGET_NUVOTON/TARGET_M451/us_ticker.c, targets/TARGET_NUVOTON/TARGET_M480/lp_ticker.c, targets/TARGET_NUVOTON/TARGET_M480/us_ticker.c, targets/TARGET_NUVOTON/TARGET_NANO100/lp_ticker.c, targets/TARGET_NUVOTON/TARGET_NANO100/us_ticker.c, targets/TARGET_NUVOTON/TARGET_NUC472/lp_ticker.c, targets/TARGET_NUVOTON/TARGET_NUC472/us_ticker.c
This PR includes rework on us_ticker/lp_ticker. Because upper layer (hal/mbed_ticker_api.c) has addressed ticker frequency/bit size/some wrap-around issues, us_ticker/lp_ticker are reworked to make code more concise and reasonable.
It update the following Nuvoton targets:
- NUMAKER_PFM_NUC472
- NUMAKER_PFM_M453
- NUMAKER_PFM_M487
- NUMAKER_PFM_NANO130
https://github.com/ARMmbed/mbed-os/pull/6028
=> Nuvoton: Rework us_ticker and lp_ticker

.travis.yml, events/equeue/equeue_platform.h
Removed the dependencies and added a compilation test in Travis to protect against this regression in the future.
cc @janjongboom, @kjbracey-arm 
should fix https://github.com/ARMmbed/mbed-os/issues/6100
=> equeue: Removed RTOS dependencies with RTOS not present

hal/reset_reason_api.h, hal/watchdog_api.h
Add missing doxy tags for HAL API groups, the closing tags are already there.
=> Feature watchdog: Add definition of reset reason and watchdog doxy groups

TESTS/events/timing/main.cpp
In the `Testing accuracy of equeue semaphore` test case result is printed out in each loop iteration. This gives lots of prints during test case execution.
Since debug prints should not exist in the final test version I suggest to print information only in case of failure.
Additionally time needed to print single info is about ~25 ms (K64F/GCC_ARM). The while loop is designed to execute until 20000 ms elapses, so this print has also impact on number of times the loop is executed (number of semaphore accuracy checks).
**READY**
NO
=> tests-events-timing - print debug info only in case of failure.

tools/toolchains/gcc.py
Simplify parsing of error and warning messages for GCC_ARM.
First, the parsing method is a little bit confusing and hacky and sometimes the column parsing by calculating the ^ position fails and on the output it shows "0" instead of the correct warning/error column. Instead I am parsing the column out of  the gcc_arm output.
Second, the regex for the "INDEX_PATTERN" is not necessary anymore.
**READY**
NO
`mbed compile -t GCC_ARM --profile release`
note: mcu (TARGET) must/should be configured in ".mbed"
=> Simplify and Improve error/warning parser for gcc_arm

tools/export/e2studio/__init__.py, tools/export/exporters.py, tools/export/gnuarmeclipse/__init__.py, tools/export/mcuxpresso/__init__.py, tools/export/nb/__init__.py
Resolves #5989
@bmcdonnell-ionx, @loverdeg-ep Are there other files that could use the
same behavior?
=> Avoid blowing away .mbedignore files in exporters

.travis.yml
Every once in a while, Travis will fail on a `sudo apt-get update -qq` due to some connectivity issue to the default Ubuntu PPA URLs.
The problem is transient and not easily reproducible (suspect it's an issue with the remote server coming under sudden load), but makes the build appear to fail when it does occur. 
**READY**
Tested within an Ubuntu VM. Command would continue until NAT was reconnected.
=> Modified 'apt-get update' to loop until successful

features/mbedtls/targets/TARGET_NUVOTON/TARGET_M480/TARGET_NUMAKER_PFM_M487/mbedtls_device.h, features/mbedtls/targets/TARGET_NUVOTON/TARGET_M480/ecp/ecp_internal_alt.c, targets/TARGET_NUVOTON/TARGET_M480/crypto/crypto-misc.c, targets/TARGET_NUVOTON/TARGET_M480/crypto/crypto-misc.h, targets/TARGET_NUVOTON/TARGET_NUC472/crypto/crypto-misc.c
This PR includes support for cryptography ECP H/W accelerator.
=> M487: Support ECP H/W accelerator

targets/targets.json
Issue reported by @atoy40 in
https://github.com/ARMmbed/mbed-os/pull/5795#issuecomment-363441054
wiki page https://os.mbed.com/teams/ST/wiki/STDIO will be updated
Correct mbed_app.json format is :
"NUCLEO_L073RZ": {
"target.stdio_uart_tx": "tx pin name",
"target.stdio_uart_rx": "rx pin name",
}
}
**READY**
=> STM32 STDIO pin redefinition

targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K64F/us_ticker.c, targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/api/lp_ticker.c
Issue with interrupt scheduling has been found while working on PR https://github.com/ARMmbed/mbed-os/pull/6052.
Delta calculation from lp_ticker_set_interrupt() function:
https://github.com/ARMmbed/mbed-os/blob/04f0f2b1aa7abb6acb2dfcaa2cb2696520aa6e38/targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/api/lp_ticker.c#L138
Lets assume that `timestam` == `now_us`.
Expected delta value should be `0` and in this current version is `0xFFFFFFFF`.
The following condition:
`timestamp > now_us`
should have the following form:
`timestamp >= now_us`
Additionally modified us ticker driver to provide the same logic.
**READY**
NO
=> K64F lp ticker driver - calculation bug fix.

features/filesystem/littlefs/littlefs/lfs.c, features/filesystem/littlefs/littlefs/lfs.h, features/filesystem/littlefs/littlefs/tests/test_alloc.sh
Rather than tracking all in-flight blocks blocks during a lookahead, littlefs uses an ack scheme to mark the first allocated block that hasn't reached the disk yet. littlefs assumes all blocks since the last ack are bad or in-flight, and uses this to know when it's out of storage.
However, these unacked allocations were still being populated in the lookahead buffer. If the whole block device fits in the lookahead buffer, _and_ littlefs managed to scan around the whole storage while
an unacked block was still in-flight, it would assume the block was free and misallocate it.
The fix is to only fill the lookahead buffer up to the last ack. The internal free structure was restructured to simplify the runtime calculation of lookahead size.
note: intended for patch
cc @deepikabhavnani
=> littlefs: Fix incorrect lookahead population before ack

drivers/Ticker.h
Ticker constructor calls directly target specific ticker init function. Currently there is no problem, since ticker interface initialization functions are protected against multi-calls and simply returns if not called for the first time (interface initialization can be performed only once). According to the new Thicker HAL API requirements:
> The function ticker_init allows the ticker to keep counting and disables the ticker interrupt.
Disabling interrupts while some Ticker interrupts are already scheduled for sure will destroy the schedule. Ticker interface should be initialized only here:
https://github.com/ARMmbed/mbed-os/blob/ccff46d9a3c960dae72d08c399e214a3eaeb63c7/hal/mbed_ticker_api.c#L36
This function is protected against multi-calls and ensures that ticker interface will be …
=> Remove ticker interface initialization while Ticker creation.

TESTS/netsocket/tcp_echo/main.cpp, TESTS/netsocket/tcp_echo_parallel/main.cpp, TESTS/netsocket/tcp_packet_pressure/main.cpp, TESTS/netsocket/tcp_packet_pressure_parallel/main.cpp, TESTS/netsocket/udp_echo_parallel/main.cpp, TESTS/netsocket/udp_packet_pressure/main.cpp, TESTS/netsocket/udp_packet_pressure_parallel/main.cpp
Netsocket tests  with MBED_EXTENDED_TESTS were not configurable as "level 0" tests.
- All test parameters can be set now in mbed_app json file.
- Tests are also possible now in a local network (no internet access) by disabling ECHO_SERVER_ADDR in the json file.
Astyle has been applied
**READY**
| NUCLEO_F429ZI-GCC_ARM | NUCLEO_F429ZI | tests-netsocket-connectivity                 | OK     | 21.66              | default     |
| NUCLEO_F429ZI-GCC_ARM | NUCLEO_F429ZI | tests-netsocket-gethostbyname                | OK     | 19.84              | default     |
| NUCLEO_F429ZI-GCC_ARM | NUCLEO_F429ZI | tests-netsocket-ip_parsing                   | OK     | 17.63              | default     |
| NUCLEO_F429ZI-GCC_ARM | NUCLEO_F429ZI | tests-netsocket-socket_sigio                 | OK     | 26.36 …
=> NETSOCKET MBED_EXTENDED_TESTS json configuration

targets/TARGET_NORDIC/TARGET_NRF5/flash_api.c, targets/targets.json
The way flash writes and erases are done on the NRF52 changes depends on whether the SoftDevice is enabled or not.
This change does a runtime check before erasing and writing, and then chooses the correct function to perform the action.
=> Make NRF52 flash work with SoftDevice

drivers/QSPI.cpp, drivers/QSPI.h
The current `command_transfer` assumes that address is first 4 bytes in the tx buffer but not yet documented.
We need to provide address somehow, for commands like erase sector or similar where address should be passed.  How this address is passed?
I can change this to document what buffer should contain or we provide address as an argument (to be aligned with other API).
=> Feature QSPI: add address to command transfer

.travis.yml
If $MBED_BOT is not configured in Travis (ie: if mbed-os is forked and the user had not setup a token yet), the build will fail in a non-obvious way.
**READY**
=> Add quotes around MBED_BOT parameter

targets/TARGET_NORDIC/TARGET_NRF5x/trng_api.c, targets/targets.json
When multiple TRNG objects are initialized, destroying the first
object will turn the TRNG off for the other objects.
This fix adds a counter to ensure that only when the last object
is destroyed will it cause the TRNG to be disabled.
=> [feature-nrf528xx] Fix TRNG for NRF52

tools/make.py
Some toolchains (GCC) may emit error messages with unicode symbols based on the your localization settings. Instead of being passed to the user as is, the unicode causes an exception.
I'm not sure exactly what the correct fix is regarding python2+3 compat, but changing `str` to `unicode` seems to work on my setup (x86_64-linux-gnu-gcc 5.4.0 + python 2.7.12 + mbed-os-5c7cd1f + LANG=en_US.UTF-8)
cc @theotherjimmy
=> tools: Let unicode error messages through

tools/toolchains/__init__.py
=> Correct single file excludes for some exporters

platform/FilePath.cpp
Current behaviour ends up undefined when the constructor leaves early. Now FilePath just discards leading slashes and otherwise asserts if the path is bad.
Note: The correct behavior should be to return ENOENT in this case, but in order to propagate errors this layer would require quite a bit of restructuring. Since this is currently blocking https://github.com/ARMmbed/mbed-os/issues/5959 and assert is a good compromise.
related https://github.com/ARMmbed/mbed-os/issues/5959, https://github.com/ARMmbed/mbed-os/issues/6090
release patch
cc @deepikabhavnani, @kegilbert
=> retarget: Fix path behaviour without leading slash

TESTS/mbed_hal/sleep_manager_racecondition/main.cpp
This RP contains fix for `sleep_manager_racecondition` test for very slow devices (like NRF51)
It fixes the test itself as well as side effects of fix introduced in #5046 (us ticker: fix fire interrupt handling)
The idea of the test was to test race condition between main thread and interrupt handler calling the same function. To efficiently test this, each handler call should interrupt main thread to make race more likely. On very slow devices (like NRF51) when we set very low ticker period (e.g less then 1000us for NRF51) there is no much time for thread scheduling. On such slow devices, setting period to 500 us cause that main thread is scheduled very rarely and only handler is constantly called making test unreliable. Fix introduced in #5046 (us ticker: fix fire interrupt handling) …
=> sleep_manager_racecondition test fix for devices with low CPU clock

TESTS/mbed_drivers/flashiap/main.cpp, drivers/FlashIAP.cpp, drivers/FlashIAP.h
A few FlashIAP driver modifications
- Support programming across sectors.
- Support program size not aligned to page size.
READY
=> FlashIAP driver modifications

targets/TARGET_NORDIC/TARGET_NRF5/TARGET_MCU_NRF52832/sdk/nrf_drv_config.h, targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/drivers_nrf/hal/nrf_rng.h, targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/drivers_nrf/rng/nrf_drv_rng.c, targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/drivers_nrf/rng/nrf_drv_rng.h, targets/TARGET_NORDIC/TARGET_NRF5/trng_api.c, targets/targets.json
Use SoftDevice API to get random numbers when present and active,
otherwise read random numbers directly from TRNG peripheral.
=> Add TRNG for NRF52832

tools/build_api.py, tools/make.py, tools/memap.py
This reverts commit 471d99c68fab68ebbcbc285b6db138735323be63
cc @screamerbg, @MarceloSalazar @cmonr 
alternative to https://github.com/ARMmbed/mbed-os/pull/6155
reverts https://github.com/ARMmbed/mbed-os/pull/5929
intended for patch
=> Revert "Added pretty bar printing for compile output"

TESTS/mbed_platform/FileHandle/main.cpp
It removes test customisation against different c stdlibs behaviour under ARMCC/IAR/GCC compilers.
Now the test flow is the same on all compilers
#5895
#5571
=> platform: FileHandle test - remove optimization for stdlib diversity

features/filesystem/littlefs/littlefs/lfs.c, features/filesystem/littlefs/littlefs/tests/test_paths.sh
Before this patch, when calling lfs_mkdir or lfs_file_open with root as the target, littlefs wouldn't find the path properly and happily run into undefined behaviour.
The fix is to populate a directory entry for root in the lfs_dir_find function. As an added plus, this allowed several special cases around root to be completely dropped.
should fix https://github.com/ARMmbed/mbed-os/issues/6090
cc @deepikabhavnani, @kegilbert 
code size 10073B (-0.35%)
intended for patch
=> littlefs: Fix handling of root as target for create operations

features/FEATURE_BLE/source/generic/GenericGap.cpp
This PR contains two _fixes_ for GenericGap::connect: 
* Accept NULL values passed as connection and scan parameters
* Blindly stop ongoing scan process otherwise if the user didn't stop the scan process before the connection; the connect operation fails.
**READY**
NO
=> BLE: Fix generic gap connect

features/filesystem/fat/FATFileSystem.cpp
This is in response to https://github.com/ARMmbed/mbed-os/issues/6072
A lot of the error codes in fatfs were mapped incorrectly. This patch revisits the error code mapping to try to correct these mistakes. I'm open to feedback on these.
| ChanFS                  | was        | should be  | ChanFS description                                               |
| ----------------------- | ---------- | ---------- | ---------------------------------------------------------------- |
| FR_OK                   | 0          | 0          | Succeeded                                                        |
| FR_DISK_ERR             | EIO        | EIO        | A hard error occurred in the low level disk I/O layer            |
| FR_INT_ERR              | ~EBADF~    | -1         | Assertion failed …
=> fatfs: Update error code mapping

targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F437xG/TARGET_UBLOX_C030/PinNames.h, targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F437xG/TARGET_UBLOX_C030/onboard_modem_api.c, targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F437xG/TARGET_UBLOX_C030/ublox_low_level_api.c, targets/targets.json
UBLOX_C030_R410M added. The board port is ready in this submission, integration of cellular and GNSS module interfaces will follow. ARM, IAR and GCC toolsets are supported and all mbed platform tests pass.
**READY**
UBLOX_C030_R410M
=> C030 R410M Target Added

TESTS/mbed_drivers/timerevent/main.cpp, drivers/TimerEvent.h, targets/TARGET_ARM_SSG/TARGET_BEETLE/us_ticker.c, targets/TARGET_Freescale/TARGET_KLXX/us_ticker.c, targets/TARGET_Maxim/TARGET_MAX32600/us_ticker.c, targets/TARGET_Maxim/TARGET_MAX32610/us_ticker.c, targets/TARGET_Maxim/TARGET_MAX32620/us_ticker.c, targets/TARGET_Maxim/TARGET_MAX32625/us_ticker.c, targets/TARGET_Maxim/TARGET_MAX32630/us_ticker.c, targets/TARGET_NORDIC/TARGET_MCU_NRF51822/us_ticker.c, targets/TARGET_NORDIC/TARGET_NRF5/common_rtc.h, targets/TARGET_NORDIC/TARGET_NRF5/lp_ticker.c, targets/TARGET_NORDIC/TARGET_NRF5/us_ticker.c
`TimerEvent`:
* updated docs in the header file,
* added unit tests,
* added a fix from @0xc0170 (with an update from @maciejbocianski) for multiple boards failing to pass new test ceses, fixes #5284.
**READY**
=> TimerEvent tests

targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F439xI/TARGET_MODULE_UBLOX_ODIN_W2/TARGET_MTB_UBLOX_ODIN_W2/PinNames.h
Clean up of Pin names for ODIN MTB. Required to build examples from online compiler.
=> ODIN MTB LEDs Fix

TESTS/mbed_drivers/rtc/main.cpp, TESTS/mbed_hal/lp_ticker/lp_ticker_api_tests.h, TESTS/mbed_hal/lp_ticker/main.cpp, TESTS/mbed_hal/lp_us_tickers/main.cpp, hal/lp_ticker_api.h, targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K64F/us_ticker.c, targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/api/lp_ticker.c, targets/targets.json
This PR ports us/lp ticker K64F drivers to the new HAL API, enables support for ticker on K64F and also provides little modifications to the HAL ticker tests (resolve issues found while porting ticker driver).
1. Adapt K64F us ticker driver to the new standards.
Here only cosmetic changes were required since US ticker is already driven by 1MHz clock, so us <-> ticks conversion is not required.
Init routine needed to be modified since according to the requirements init should disable us ticker interrupt.
2. Adapt K64F lp ticker driver to the new standards.
Low power ticker time counter is created based on RTC which is driven by 32KHz clock. Additional low power timer is used to generate interrupts (in case when sleep time does not exceed 2 sec otherwise interrupt is scheduled in two steps …
=> us/lp ticker - port K64F platform to new HAL api

features/FEATURE_COMMON_PAL/nanostack-hal-mbed-cmsis-rtos/mbed_lib.json, features/FEATURE_COMMON_PAL/nanostack-hal-mbed-cmsis-rtos/ns_event_loop.c, features/FEATURE_COMMON_PAL/nanostack-hal-mbed-cmsis-rtos/ns_event_loop.h, features/FEATURE_COMMON_PAL/nanostack-hal-mbed-cmsis-rtos/ns_hal_init.c
This has the same content as ARMmbed/mbed-os-confidential-m#7 and https://github.com/ARMmbed/mbed-os/pull/5752, just the target repo and branch are different.
Copypasta from commit:
--8<--8<--8<--8<--8<
The separate eventloop thread may not be necessary on all uses, as one
can use the existing main thread for event dispatching. Add a
conditional nanostack-hal.event-loop-dispatch-from-application, which
disables the thread creation.
Note: the ns_hal_init must be ran from the same thread which will be
used to execute the event loop later.
--8<--8<--8<--8<--8<
By removing the separate event loop thread, one saves about 6KB of RAM in mbed cloud client example side.
**READY**
Unless one sets the "nanostack-hal.event-loop-dispatch-from-application" to true, the existing behavior is not changed. …
=> Eventloop in main thread to master

features/netsocket/cellular/generic_modem_driver/PPPCellularInterface.cpp, features/netsocket/cellular/generic_modem_driver/mbed_lib.json
If the user does not provide an APN when using `PPPCellularInterface`, the driver currently uses the APN "internet" as a default.  It includes the capability to look up the APN based on the IMSI of the SIM however this behaviour is only available under the compilation switch `MBED_CONF_PPP_CELL_IFACE_APN_LOOKUP`.
With this change APN look-up is the default behaviour.  If the user specifies an APN then that still takes precedence and if the look-up fails then, finally, "internet" is used, so this should have no adverse effect on existing users.
All of the cellular interface tests in `mbed-os-features-netsocket-cellular-generic_modem_driver-tests-unit_tests-default` pass after making this change.
This change depends upon the fix in #6160.
=> Make APN lookup the default behaviour for PPPCellularInterface

features/FEATURE_LWIP/lwip-interface/lwip-eth/arch/TARGET_CM3DS_MPS2/lwipopts_conf.h, features/FEATURE_LWIP/lwip-interface/lwip-eth/arch/TARGET_CM3DS_MPS2/mps2_emac.c, targets/TARGET_ARM_SSG/TARGET_CM3DS_MPS2/SDK/smsc9220_eth.c
This pull request contains bug fixes for the CM3DS target.
It is the pull request 1 among the 4 concerning CM3DS Maintenance. Please check #6119 for the full scope.
Other pull requests regarding this target:
* CM3DS Maintenance Pull Request: Bug fixes (1/4) #6167
* CM3DS Maintenance Pull Request: Memory changes (2/4) #6168
* CM3DS Maintenance Pull Request: TRNG support (3/4) #6169
* CM3DS Maintenance Pull Request: Driver updates (4/4) #6170
=> CM3DS Maintenance Pull Request: Bug fixes (1/4)

platform/mbed_retarget.cpp, targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L475xG/device/TOOLCHAIN_GCC_ARM/STM32L475XX.ld, targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L476xG/device/TOOLCHAIN_GCC_ARM/STM32L476XX.ld, targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L486xG/device/TOOLCHAIN_GCC_ARM/STM32L486XX.ld, targets/TARGET_STM/TARGET_STM32L4/l4_retarget.c, targets/TARGET_STM/mbed_rtx.h, targets/targets.json
STM32L475 STM32L476 and STM32L486 devices have 32kbytes of SRAM2 that is used only for interrupt vector at the moment.
With this PR, the stack is now located in SRAM2.
This gives more space in SRAM1 for variables and heap. 
**It is mandatory for heavy applications like IOT connections**
This has already been pushed and merged for IAR toolchain. ARM Toolchain will come soon
Note that the mbed-os code for GCC_ARM is made for heap and stack in the same RAM area. I've rewritten __wrap__sbrk (code already available in mbed-os) and used a new define in targets.json : TWO_RAM_REGIONS
@ARMmbed/team-avnetsilica Please pay attention. I have modified your GCC_ARM linker file and added TWO_REGION_RAM in targets.json for SILICA_SENSOR_NODE. It compiles and link, but I can't test it.
If you don't want …
=> Use SRAM2 32Kbytes on STM32L475 / L476 and L486 devices

targets/TARGET_STM/rtc_api.c
Fix found during RTC tests with reset.
Tests status verified in master and in feature-hal-spec-rtc branches
@mprse
=> STM32 RTC : update free function

.travis.yml, tools/test/config/invalid_key/test_data.json, tools/test/config/invalid_key_lib/test_data.json, tools/test/toolchains/api_test.py, tools/toolchains/arm.py
Temporary solution, python3 will be added back when working (see #6200)
Travis doesn't recognize version matrices when inside a matrix include job. Instead, it breaks in a way that isn't reported as an error.
cc @theotherjimmy, @0xc0170, @deepikabhavnani, @cmonr 
intended for patch
introduced in #5848
related https://github.com/travis-ci/travis-ci/issues/9275
=> Travis: Tear out python3 testing to get CI working again

tools/toolchains/__init__.py
When overriding the OUTPUT_EXT variable in compilation configuration,
bugs appear:
* The bin variable is not None as the 'elf' string is not interned.
* When that is fixed, the function returns None instead of returning the
path of the ELF file.
The bug fix in this pull request is needed to make the changes of the pull request #6168 work.
@theotherjimmy
=> Fix a bug using ELF as output extension

platform/mbed_sleep.h
* Qualify inclusion of sleep_api.h
* use standard `inline` qualification instead of the non standard `__INLINE`
=> Platform: Improve mbed_sleep.h

rtos/TARGET_CORTEX/rtx5/RTX/Source/TOOLCHAIN_GCC/TARGET_M33/irq_armv8mml.S
Fix typo in irq_armv8mml.S
Signed-off-by: Tamas Kaman <tamas.kaman@arm.com>
Because of this typo building this assembly file failed
For testing I simply run the build again and the build error was gone.
-  Fix
=> Build issue for M33 core

targets/TARGET_NUVOTON/TARGET_M451/TARGET_NUMAKER_PFM_M453/PinNames.h, targets/TARGET_NUVOTON/TARGET_M480/TARGET_NUMAKER_PFM_M487/PinNames.h, targets/TARGET_NUVOTON/TARGET_NANO100/TARGET_NUMAKER_PFM_NANO130/PinNames.h, targets/TARGET_NUVOTON/TARGET_NUC472/TARGET_NUMAKER_PFM_NUC472/PinNames.h
This PR is to add I2C & Serial pin name definition for compatibility in existing mbed samples.
It updates the following Nuvoton targets and passed Greentea test:
- NUMAKER_PFM_NUC472
- NUMAKER_PFM_M453
- NUMAKER_PFM_M487
- NUMAKER_PFM_NANO130
=> Nuvoton: Add I2C & Serial Pin Name

TESTS/mbed_hal/flash/functional_tests/main.cpp
Measure the time drift over longer duration
Fix for  issues: https://github.com/ARMmbed/mbed-os/issues/6224 
[ x ] Fix
=> Flash test: fix the time over a longer range

targets/TARGET_NORDIC/TARGET_NRF5x/PeripheralPins.h, targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/TARGET_MCU_NRF52832/PeripheralPins.c, targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/TARGET_MCU_NRF52832/config/sdk_config.h, targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/TARGET_MCU_NRF52840/PeripheralPins.c, targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/TARGET_MCU_NRF52840/config/sdk_config.h, targets/TARGET_NORDIC/TARGET_NRF5x/analogin_api.c
Use new SDK API and fixed return value to be normalized to 16 bit as per the Mbed HAL specification.
=> [feature-nrf528xx] Update analogin_api.c for NRF52 SDK 14.2

TESTS/mbedmicro-rtos-mbed/systimer/main.cpp, rtos/TARGET_CORTEX/SysTimer.cpp, rtos/TARGET_CORTEX/SysTimer.h, rtos/TARGET_CORTEX/mbed_rtx_idle.cpp
Add tests for an `RtosTimer` class introduced with **TICKLESS mode** support in #4991.
* extracted a `RtosTimer` class from https://github.com/ARMmbed/mbed-os/blob/a519b8449b391cc61d230e0b360e5af936e80ac6/rtos/TARGET_CORTEX/mbed_rtx_idle.cpp#L49 as `rtos/SysTimer`,
* added unit tests.
**READY**
Issues to be resolved before merge:
* ~#5284~
=> Tests for SysTimer (the idle loop timer for tickless mode)

tools/config/__init__.py
```                                                                                                      
[ERROR] OrderedDict([(u'help', u'Address of the active application firmware in flash'), (u'value', u'POST_APPLICATION_ADDR'), (u'required', 1)]) is not valid under any of the given schemas,OrderedDict([(u'help', u'Flash sector address for SOTP sector 1'), (u'macro_name', u'PAL_INTERNAL_FLASH_SECTION_1_ADDRESS'), (u'value', [])]) is not valid under any of the given schemas
```
```
[ERROR] 1 is not of type u'string'
```
```                                                                                                      
[ERROR] in ./mbed_app.json element config.application-start-address.required: 1 is not of type u'boolean'; in ./mbed_app.json element …
```
=>                                Improve invalid configuration error messages                                                             

.github/pull_request_template.md
Please use these 2 sections for describing a pull request. They should be part
of every pull request.
The type specifies what is expected from the pull request and when it can be
released. For instance a feature pull request can't be expected to go to the
patch release.
Important: do not mix pull request types !
I added also required to description (is Required placed there good, or any other suggestions?)
=> pull request: add required info

TESTS/host_tests/system_reset.py, TESTS/mbed_platform/system_reset/main.cpp, drivers/CAN.cpp, drivers/I2C.cpp, drivers/PwmOut.h, drivers/SPI.cpp, drivers/SerialBase.cpp, drivers/Ticker.h, drivers/Timeout.h, drivers/Timer.h, features/nanostack/FEATURE_NANOSTACK/targets/TARGET_SL_RAIL/NanostackRfPhyEfr32.cpp, hal/mbed_sleep_manager.c, mbed.h, platform/DeepSleepLock.h, platform/mbed_interface.c, platform/mbed_power_mgmt.h, platform/mbed_sleep.h, platform/mbed_wait_api_rtos.cpp, platform/sleep.h, rtos/TARGET_CORTEX/mbed_rtx_idle.cpp, targets/TARGET_Atmel/TARGET_SAM_CortexM0P/drivers/system/reset/TARGET_SAMD21/reset.h, targets/TARGET_Atmel/TARGET_SAM_CortexM0P/drivers/system/reset/TARGET_SAML21/reset.h, targets/TARGET_Atmel/TARGET_SAM_CortexM0P/drivers/system/reset/TARGET_SAMR21/reset.h, targets/TARGET_Atmel/TARGET_SAM_CortexM4/drivers/pmc/sleep.c, targets/TARGET_NUVOTON/nu_timer.h, targets/TARGET_ONSEMI/TARGET_NCS36510/sleep.c, targets/TARGET_Silicon_Labs/TARGET_EFM32/i2c_api.c, targets/TARGET_Silicon_Labs/TARGET_EFM32/pwmout_api.c, targets/TARGET_Silicon_Labs/TARGET_EFM32/serial_api.c, targets/TARGET_Silicon_Labs/TARGET_EFM32/spi_api.c
* Add official Mbed API for reseting the system using CMSIS call.
* Add tests
=> Add system_reset call

features/nvstore/README.md, features/nvstore/TESTS/nvstore/functionality/main.cpp, features/nvstore/mbed_lib.json, features/nvstore/source/nvstore.cpp, features/nvstore/source/nvstore.h
Adding the NVStore feature.
READY
NO
None.
branch | PR
- Documentation
- Need to move configuration of area addresses and sizes from targets.json to local mbed_lib.json.
See README.md for testing instructions.
=> Add NVStore (A.K.A SOTP) feature

features/FEATURE_BLE/ble/Gap.h, features/FEATURE_BLE/source/generic/GenericGap.cpp, features/FEATURE_BLE/targets/TARGET_ARM_SSG/TARGET_BEETLE/source/ArmBLE.cpp, features/FEATURE_BLE/targets/TARGET_Maxim/MaximBLE.cpp, features/FEATURE_BLE/targets/TARGET_NORDIC/TARGET_MCU_NRF51822/source/btle/btle.cpp, features/FEATURE_BLE/targets/TARGET_NORDIC/TARGET_NRF5/source/btle/btle.cpp
Add the address type of the broadcaster in advertising packets received.
**READY**
NO, vendors code is updated in this PR.
=> BLE: Add address type in AdvertisementCallbackParams_t.

targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/TARGET_MCU_NRF52832/device/TOOLCHAIN_GCC_ARM/NRF52832.ld, targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/TARGET_MCU_NRF52832/device/TOOLCHAIN_IAR/nRF52832.icf, targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/TARGET_MCU_NRF52840/device/TOOLCHAIN_IAR/nRF52840.icf
GCC and IAR ISR stack sizes have been set to 0x800.
(ARM compiler does not set stack size explicitly).
Note that the GCC linker script for NRF52840 already has the correct stack size.
=> [feature-nrf528xx] Fix ISR stack size inconsistencies on NRF52 series

targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F437xG/TARGET_UBLOX_C030/min_battery_voltage.c
In pull request #6117 a better mechanism for the I2C initialisation that is required for all C030 platforms was introduced.  However, there was a bug in that mechanism which, depending on an uninitialised stack variable, could result in a failure to boot.  This PR fixes that bug.
In `set_minimum_battery_voltage()` change the order of initialisation so that `i2c_init()` is called before `i2c_frequency()` as `i2c_frequency()` requires a valid I2C object.  Zero the I2C object since `i2c_init()` has to set a default frequency for its timeouts to work and it will only do that if the `hz` field of the object was zero to begin with.
All platform tests pass reliably after this change.
[C030_U201_Mbed_Tests_Logs.txt](https://github.com/ARMmbed/mbed-os/files/1771520/C030_U201_Mbed_Tests_Logs.txt)
=> C030 platform I2C initialisation fix

targets/TARGET_NORDIC/TARGET_NRF5x/PeripheralPinsDefault.c, targets/TARGET_NORDIC/TARGET_NRF5x/object_owners.c, targets/TARGET_NORDIC/TARGET_NRF5x/object_owners.h, targets/TARGET_NORDIC/TARGET_NRF5x/pinmap_ex.c, targets/TARGET_NORDIC/TARGET_NRF5x/pinmap_ex.h
The NRF52 series can map digital signals to any physical pin which
makes it challenging to associate pin names with hardware instances.
* pinmap_ex:
Keep track of which hardware instance is in use and what pins are
associated with it. Currently only supports I2C and SPI, but
provides a mechanism for allocating the shared I2C/SPI hardware.
* PeripheralPinsDefault:
Optional pin map for pre-assigning hardware instances at compile
time. This makes it easier to optimize hardware utilization.
* Helper functions for sharing hardware peripherals on NRF52
Common functions for getting and setting the instance owner of a 
hardware peripheral. Used for reconfiguring SPI/I2C after change  
of ownership.
=>  [feature-nrf528xx] Extended PeripheralPins and pinmap for NRF52 series

tools/project.py
Resolves https://github.com/ARMmbed/mbed-cli/issues/590
I have a project structured like:
```
fat-fs
├── README.md
└── main.cpp
mbed-os
```
And I want to export. Using the new configuration available on master of Mbed CLI:
```
```
:smile:
=> Correct mbed export with multiple --source params

targets/TARGET_NORDIC/TARGET_NRF5/TARGET_MCU_NRF52832/PeripheralNames.h, targets/TARGET_NORDIC/TARGET_NRF5/TARGET_MCU_NRF52840/PeripheralNames.h
This change makes it possible to customize the STDIO pins, which is needed by the Client Lite.
=> NRF52: Customize STDIO pins from config system

TESTS/network/emac/README.md, TESTS/network/emac/emac_TestMemoryManager.cpp, TESTS/network/emac/emac_TestMemoryManager.h, TESTS/network/emac/emac_TestNetworkStack.cpp, TESTS/network/emac/emac_TestNetworkStack.h, TESTS/network/emac/emac_ctp.cpp, TESTS/network/emac/emac_ctp.h, TESTS/network/emac/emac_initialize.h, TESTS/network/emac/emac_membuf.cpp, TESTS/network/emac/emac_membuf.h, TESTS/network/emac/emac_test_initialize.cpp, TESTS/network/emac/emac_test_memory.cpp, TESTS/network/emac/emac_test_multicast_filter.cpp, TESTS/network/emac/emac_test_unicast.cpp, TESTS/network/emac/emac_test_unicast_burst.cpp, TESTS/network/emac/emac_test_unicast_frame_len.cpp, TESTS/network/emac/emac_tests.h, TESTS/network/emac/emac_util.cpp, TESTS/network/emac/emac_util.h, TESTS/network/emac/main.cpp, TESTS/network/emac/template_mbed_app.txt
Converted existing EMAC greentea test cases to support new EMAC implementation in feature-emac  branch. 
Added test network stack and memory manager classes under EMAC greentea tests to enable testing of the network interface. Updated test cases. Added new test cases for burst sending, multicast filtering and out-of-memory testing.
See README.md in the pull request for more information about EMAC greentea test implementation and test cases.
=> Emac greentea tests for feature-emac

rtos/TARGET_CORTEX/mbed_rtx_handlers.c
Modifies the underflow error in RTX to be reported as an overflow error, for user clarity.
=> Modifies error text reported from RTX from 'underflow' to 'overflow'

features/cellular/UNITTESTS/at/at_cellularstack/test_at_cellularstack.cpp
nsapi_socket_t errors fixed in unittests
No code changes done, so should be trivial merge
- [X ] Fix
=> Unittests fixed

targets/TARGET_Maxim/TARGET_MAX32625/PeripheralPins.c, targets/TARGET_Maxim/TARGET_MAX32625/TARGET_MAX32625MBED/PinNames.h, targets/TARGET_Maxim/TARGET_MAX32625/TARGET_MAX32625NEXPAQ/PinNames.h, targets/TARGET_Maxim/TARGET_MAX32625/analogin_api.c, targets/TARGET_Maxim/TARGET_MAX32625/i2c_api.c, targets/TARGET_Maxim/TARGET_MAX32625/serial_api.c, targets/TARGET_Maxim/TARGET_MAX32625/spi_api.c, targets/TARGET_Maxim/TARGET_MAX32625/us_ticker.c
MAX32625: Fix serial interrupts and I2C master; Improve SPI block write, us ticker performance, ADC functionality 
Fix problems with missing serial objects for interrupts.
Remove automatic stop signaling after read transaction to allow repeated start after read.
Improve SPI block write by replacing byte write loop with hardware assisted block transaction.
Improve performance of us ticker.
Increase analog input range by 2x.
Tested all supported toolchains with MAX32625MBED.
=> Fix max32625mbed

targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC54114/TARGET_LPCXpresso/mbed_overrides.c, targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC546XX/TARGET_FF_LPC546XX/mbed_overrides.c, targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC546XX/TARGET_LPCXpresso/mbed_overrides.c, targets/targets.json
* mcu_lpc546xx: move "release_versions" to children
* fix clock in lpc546xx related boards. Namely the wait() function took longer when adc was enabled
related issues: #5887
cc: @mmahadevan108
=> mcu_lpc546xx: move "release_versions" to children and fix clock 

events/equeue/equeue.c
Building with (GNU Tools for Arm Embedded Processors 7-2017-q4-major) 7.2.1 20170904 gives this warning
../events/equeue/equeue.c: In function 'equeue_incid':
../events/equeue/equeue.c:40:17: warning: '<<' in boolean context, did you mean '<' ? [-Wint-in-bool-context]
if (!(e->id << q->npw2)) {
=> Clarify intention between comparison to zero and the shift operation

TESTS/host_tests/sync_on_reset.py, TESTS/host_tests/watchdog_reset.py, TESTS/mbed_drivers/watchdog/Watchdog_tests.h, TESTS/mbed_drivers/watchdog/main.cpp, TESTS/mbed_drivers/watchdog_reset/Watchdog_reset_tests.h, TESTS/mbed_drivers/watchdog_reset/main.cpp, TESTS/mbed_hal/watchdog/main.cpp, TESTS/mbed_hal/watchdog/watchdog_api_tests.h, TESTS/mbed_hal/watchdog_reset/main.cpp, TESTS/mbed_hal/watchdog_reset/watchdog_reset_tests.h, TESTS/mbed_hal/watchdog_timing/main.cpp, TESTS/mbed_hal/watchdog_timing/watchdog_timing_tests.h, targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K64F/watchdog_api.c, targets/TARGET_STM/TARGET_STM32F4/watchdog_api.c
Add tests for new Watchdog API introduced in #5488:
* `tests-mbed_hal-watchdog`,
* `tests-mbed_hal-watchdog_reset`,
* `tests-mbed_hal-watchdog_timing`,
* `tests-mbed_drivers-watchdog`,
* `tests-mbed_drivers-watchdog_reset`.
CC @bulislaw @0xc0170 @scartmell-arm
=> Add tests for Watchdog HAL API

TESTS/usb_device/basic/USBTester.cpp, TESTS/usb_device/basic/USBTester.h, platform/USBPhy.h, platform/USBPhyEvents.h, platform/USBPhyTypes.h, targets/TARGET_NXP/TARGET_LPC176X/usb/USBHAL_LPC17.cpp, targets/TARGET_NXP/TARGET_LPC176X/usb/USBPhyHw.h, usb/device/USBDevice/EndpointResolver.h, usb/device/USBDevice/USBDevice.cpp, usb/device/USBDevice/USBDevice.h, usb/device/USBDevice/USBDevice_Types.h
Expand USBPhy API, cleanup the code and add doxygen.
=> USBDevice HAL specification improvements

events/README.md, features/FEATURE_BLE/targets/TARGET_CORDIO/README.md, features/FEATURE_BLE/targets/TARGET_NORDIC/TARGET_MCU_NRF51822/sdk/README.md, features/mbedtls/README.md, features/nvstore/README.md
This pull request solves some minor typo's in two readme.md files.
events/README.md and features/mbedtls/README.md
=> Small typo fixes in readme.md files

features/nvstore/source/nvstore.h
Allow NVStore header file content to show up when generating Doxygen (DOXYGEN_ONLY option is on).
=> NVStore: Enclose header file with DOXYGEN_ONLY option as well.

tools/build_api.py
Allow toolchain build profiles to omit language entries
Currently the `prepare_toolchain` function in `build_api.py` expects all profiles to contain all language keys. When writing a toolchain profile to overlay on the default profiles this can cause unexpected behaviour: ie. if you don't have an entry for the key there is an opaque error.
The workaround is to have a profile.json file that looks like this:
"TOOLCHAIN": {
"common": [],
"asm": [],
"c": [],
"cxx": ["-flag"],
"ld": []
}
but it would be nice to allow this
"TOOLCHAIN": {
"cxx": ["-flag"],
}
This pull request allows this by modifying the code that gets the language key from the dictionary.
=> Allow build profiles to omit language entries

targets/TARGET_Realtek/TARGET_AMEBA/TARGET_RTL8195A/analogin_api.c, targets/TARGET_Realtek/TARGET_AMEBA/TARGET_RTL8195A/device/TOOLCHAIN_ARM_STD/rtl8195a.sct, targets/TARGET_Realtek/TARGET_AMEBA/TARGET_RTL8195A/device/rtl8195a_init.c, targets/TARGET_Realtek/TARGET_AMEBA/TARGET_RTL8195A/log_uart_api.c, targets/TARGET_Realtek/TARGET_AMEBA/TARGET_RTL8195A/pwmout_api.c, targets/TARGET_Realtek/TARGET_AMEBA/TARGET_RTL8195A/serial_api.c, targets/TARGET_Realtek/TARGET_AMEBA/TARGET_RTL8195A/spi_api.c, targets/TARGET_Realtek/TARGET_AMEBA/TARGET_RTL8195A/trng_api.c, targets/TARGET_Realtek/TARGET_AMEBA/sdk/common/api/platform/platform_stdlib.h
fix section error, ARM compiler uses IRAM1.bss to calculate the heap size
fix conflict of _memset between Ameba's library and ARM compiler's library, use standard memset() instead of _memset() in case of ARM compiler
rebase update for #6061
=> rtl8195am: fix ARM section error

features/FEATURE_COMMON_PAL/mbed-coap/CHANGELOG.md, features/FEATURE_COMMON_PAL/mbed-coap/mbed-coap/sn_coap_protocol.h, features/FEATURE_COMMON_PAL/mbed-coap/module.json, features/FEATURE_COMMON_PAL/mbed-coap/source/sn_coap_protocol.c
Add new API to clear whole sent blockwise message list.
=> Update mbed-coap to version 4.3.0

targets/TARGET_NORDIC/TARGET_NRF5/TARGET_MCU_NRF52832/TARGET_MTB_LAIRD_BL652/PinNames.h, targets/TARGET_NORDIC/TARGET_NRF5/TARGET_MCU_NRF52832/TARGET_MTB_LAIRD_BL652/device.h, targets/targets.json
Adding Laird BL652 as a new target.
Greentea: all tests passing. Logs attached below.
[GT_log_ARMCC_Pass.txt](https://github.com/ARMmbed/mbed-os/files/1748049/GT_log_ARMCC_Pass.txt)
[GT_log_GCC_Pass.txt](https://github.com/ARMmbed/mbed-os/files/1748050/GT_log_GCC_Pass.txt)
[GT_log_IAR_Pass.txt](https://github.com/ARMmbed/mbed-os/files/1748051/GT_log_IAR_Pass.txt)
cc @screamerbg @chris-styles @0xc0170
=> Adding Laird BL652 as new target

rtos/TARGET_CORTEX/TARGET_CORTEX_M/TOOLCHAIN_ARM/except.S, rtos/TARGET_CORTEX/TARGET_CORTEX_M/TOOLCHAIN_GCC/except.S, rtos/TARGET_CORTEX/TARGET_CORTEX_M/TOOLCHAIN_IAR/except.S, rtos/TARGET_CORTEX/TARGET_CORTEX_M/mbed_rtx_fault_handler.c, rtos/TARGET_CORTEX/TARGET_CORTEX_M/mbed_rtx_fault_handler.h
This fixes some formatting issues in crash dump and also adds more info like return stack info, privilege level and mode to the crash dump.
=> Fix for Crash dump formatting issues and adding more info to crash dump

TESTS/host_tests/rtc_reset.py, TESTS/mbed_hal/rtc/main.cpp, TESTS/mbed_hal/rtc_reset/main.cpp, targets/targets.json
This PR provides the following changes:
- Enable RTC support for STM32 family,
- Adapt RTC drivers to the new RTC HAL API standards (free function keeps RTC time and disables only access to the backup domain) - skipped this has been already done by @jeromecoutant in this commit https://github.com/ARMmbed/mbed-os/pull/6217/commits/45cbdc889ff1f80e257f7db1eb1146765f633336 - Thank you!.
- RTC test fix: verify if rtc_isenabled() returns 1 in case when init is done and RTC time is set. Some platforms use RTC for low power timer, so RTC may be already enabled.
- RTC test fix: increase test timeout (verified that on some platforms 30s is not enough).
=> STM32 Family: update tests and enable RTC support

features/filesystem/fat/FATFileSystem.cpp
Reverts https://github.com/ARMmbed/mbed-os/pull/6120
This pr was a part of work spanning 5.7-5.9. There is not an immediate urgency for it to land on 5.8. During the review process of the 5.8 release it was noted that this change may cause problems for users that are relying on the existing (but broken) error codes.
To minimize noise, the plan is to revert the error code changes until 5.9, where it can land along with proper testing and documentation from related filesystem work.
I'll recreate https://github.com/ARMmbed/mbed-os/pull/6120 targeting 5.9 if this revert makes it into 5.8.
cc @kegilbert, @deepikabhavnani, @adbridge, @sg-, @kjbracey-arm, @JanneKiiskila
=> fatfs: Revert "Update error code mapping"

targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_MIMXRT1050/TARGET_EVK/PinNames.h
This target defines few PullUp values, one should be defined to be PullUp that
an application can use. We use the same value as PullDefault
@ARMmbed/team-nxp Please review
=> MIMXRT: define PullUp default value

features/cellular/UNITTESTS/target_h/platform/mbed_power_mgmt.h
Fixed Cellular Unit tests by adding one stub header. No code changes.
=> Cellular tests: fix power mgmt stub

targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/api/rtc_api.c, targets/targets.json
This PR enables RTC support for K64F board and adapts RTC driver to the new standards:
- rtc_free() does not stop the RTC from counting. Only disables clock gate since processor no longer needs to read RTC registers
- rtc_isenabled() returns 1 if the RTC is initialized and the time has been set; 0 otherwise.
Needs preceding PR: https://github.com/ARMmbed/mbed-os/pull/6161 which provides minor updates in RTC test.
=> K64F: adapt RTC drivers to the new standards

tools/test/examples/examples.json
Note: an exact clone of this PR: https://github.com/ARMmbed/mbed-os/pull/6304
Looking to get this into CI and generate 5.8.0-rc2 before the night's end.
Add mbed-os-example-lorawan and mbed-os-example-nvstore to the examples list to be test compiled in the ci.
=> Add lorawan and nvstore examples for testing.

targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_K66F/us_ticker.c, targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_K82F/us_ticker.c, targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KL27Z/us_ticker.c, targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KL43Z/us_ticker.c, targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KL82Z/us_ticker.c, targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KW24D/us_ticker.c, targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KW41Z/us_ticker.c, targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K22F/us_ticker.c, targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K24F/us_ticker.c, targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K64F/us_ticker.c, targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_IMX/us_ticker.c
=> MCUXpresso_MCUS: Apply K64F us_ticker fix across all MCU's

targets/TARGET_NORDIC/TARGET_NRF5x/README.md, targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/TARGET_MCU_NRF52832/config/sdk_config.h, targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/TARGET_MCU_NRF52840/config/sdk_config.h, targets/TARGET_NORDIC/TARGET_NRF5x/i2c_api.c, targets/TARGET_NORDIC/TARGET_NRF5x/objects.h, targets/TARGET_NORDIC/TARGET_NRF5x/spi_api.c
This PR re-implements SPI and I2C in a way that lets both drivers share the underlying hardware. From the new README.md file:
The TWI/TWIM (I2C) and SPI/SPIM module shares the same underlying hardware and each instance can only provide one functionality at a time. Both the NRF52832 and NRF52840 have 2 TWI/TWIM modules and 3 SPI/SPIM:
| Instance 0 | Instance 1 | Instance 2 |
| :---:      | :---:      | :---:      |
| SPI0/SPIM0 | SPI1/SPIM1 | SPI2/SPIM2 |
| TWI0/TWIM0 | TWI1/TWIM1 |            |
When instantiating a new Mbed SPI object or I2C object, the object will be assigned a hardware instance. By default, the HAL implementation will automatically pick a hardware instance based on the assigned pins in the following order:
1. The driver will look up the pins in the configuration table …
=> [feature-nrf528xx] NRF52 SPI and I2C re-implementation

targets/TARGET_Silicon_Labs/TARGET_EFM32/gpio_irq_api.c
Resolves https://github.com/ARMmbed/mbed-os/issues/6205
Background: I have a peripheral which generates interrupts with pulses of 50 µs. When using `MBED_TICKLESS` with the MCU in deep sleep, the ISR wouldn't be called. It was found out that the MCU wakes, but misses the pulse, resulting in `IRQ_NONE`.
This is a performance optimization which removes a check of the expected pin state, offloading it to the user. See more [here](https://github.com/ARMmbed/mbed-os/issues/6205#issuecomment-371825072).
=> EFM32: make gpio interrupts faster by offloading expected pin state check to user

targets/TARGET_STM/TARGET_STM32F4/TARGET_MTS_MDOT_F411RE/device/TOOLCHAIN_IAR/stm32f411xe.icf
Fix for applications targeting the mts_mdot_f411re target with the IAR compiler.  Need the reset vector table to also have a 64 kB offset to compensate for the presence of a 64 kB bootloader.
Verified by building and running the mbed-os-example-blinky app successfully with the following environment:
* IAR EWARM 7.80.1
* mbed-cli 1.3.0
Fixes #6181
=> mts_mdot_f411re: Fix for Multi-Tech mDot IAR linker script

targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_K82F/peripheral_clock_defines.h, targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/api/i2c_api.c
A. Enable internal pullup resistor for sda and scl lines.
B. Update the implmentation for byte read and write
1. Start function: Issue repeat start when bus is busy
2. Byte write function: Do not call SDK function as this does
not work for some of the Kinetis device
3. Byte read function: Do not call SDK function as this would
issue a START and STOP signal which is not required for
I2C byte functions
C. Fix K82F I2C ci-test shield failure
Ran the I2C ci-test shield tests to confirm
=> MCUXpresso: Fix test failures seen with ci-test shield

platform/ATCmdParser.cpp
The newline handling between methods `ATCmdParser::process_oob()` and `ATCmdParser::vrecv()` is not aligned among those in the sense that in `ATCmdParser::process_oob()`:
- the newline characters _'\n'_ and _'\r'_ are **not** handled in a unified way
- the `_output_delimiter` is used to detect the end-of incoming messages, which is **not** correct for every kind of AT commands based modules (instead a kind of _input delimiter_ would be required) and as a consequnce
- method `ATCmdParser::process_oob()` might **fail** to correctly recognize `oobs` under certain runtime conditions
=> [ATCmdParser]: Align `process_oob()` to `vrecv()`'s newline handling

features/lorawan/lorastack/phy/LoRaPHY.cpp, features/lorawan/lorastack/phy/LoRaPHYAS923.cpp, features/lorawan/lorastack/phy/LoRaPHYAU915.cpp, features/lorawan/lorastack/phy/LoRaPHYCN470.cpp, features/lorawan/lorastack/phy/LoRaPHYCN779.cpp, features/lorawan/lorastack/phy/LoRaPHYEU433.cpp, features/lorawan/lorastack/phy/LoRaPHYEU868.cpp, features/lorawan/lorastack/phy/LoRaPHYIN865.cpp, features/lorawan/lorastack/phy/LoRaPHYKR920.cpp, features/lorawan/lorastack/phy/LoRaPHYUS915.cpp, features/lorawan/lorastack/phy/LoRaPHYUS915Hybrid.cpp
Some fixes to LoRa PHY:
- Fix initialization of phy_params.payloads_with_repeater.size. This value was not set at all but instead a incorrect (phy_params.payloads.size) was set.
- Fix RX2 datarate verification. Earlier only the minimum datarate value was accepted.
=> Fixes to LoRa PHY

targets/TARGET_RENESAS/TARGET_RZ_A1XX/TARGET_RZ_A1H/device/inc/iodefines/iodefine_typedef.h
Regarding RZ_A1H, Since I removed the macro definition accidentally in iodefine_typedef, I fixed the lack of it.
=> Fix macro definition of iodefine_typedef for RZ_A1H

events/EventQueue.h
Added note about immediate firing of periodic events
see https://github.com/ARMmbed/mbed-os/issues/6256
cc @pauluap, @kjbracey-arm
=> events: Added note about immediate firing of periodic events

targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC/flash_api.c, targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC/objects.h, targets/targets.json
Passed the flash tests
1. LPC54114:
mbedgt: test on hardware with target id: 105400001b4ee77600000000000000000000000097969905
mbedgt: test suite 'mbed-os-tests-mbed_hal-flash' .................................................... OK in 14.28 sec
test case: 'Flash - buffer alignment test' ................................................... OK in 0.14 sec
test case: 'Flash - clock and cache test' .................................................... OK in 0.10 sec
test case: 'Flash - erase sector' ............................................................ OK in 0.14 sec
test case: 'Flash - init' .................................................................... OK in 0.08 sec
test case: 'Flash - mapping alignment' ....................................................... OK in 0.05 sec
test …
=> Flash support: Add flash support for LPC54114 & LPC546XX

TESTS/mbed_drivers/lp_timeout/main.cpp, TESTS/mbed_drivers/timeout/main.cpp, TESTS/mbed_drivers/timeout/timeout_tests.h
Added unit tests for timeout classes
* `Timeout`,
* `LowPowerTimeout`.
**READY**
Preceding PR's needed:
* ~#5046~ -- provides a fix for several boards failing to handle a delay of 0 us,
* ~#5347~ -- provides a fix for #5150,
Issues to be resolved before merge:
* ~#5159~
* ~#5431~ 
* ~#5284~
=> Timeout & LowPowerTimeout tests

features/nanostack/FEATURE_NANOSTACK/mbed-mesh-api/mbed_lib.json
This pulls in the help that was in the Markdown moved from this repo to the handbook in #5731 and being discussed in https://github.com/ARMmbed/Handbook/pull/366
=> mbed-mesh-api: add JSON help

events/equeue/equeue.c, events/equeue/equeue.h, events/equeue/tests/tests.c
Change break_dispatch from a counting semaphore which needs the same number of calls to dispatch_forever() as number of calls to break_dispatch() to a squashable flag which will only break once for any number of calls to break_dispatch()  between calls to dispatch_forever()
Resolves #6204
=> Remove windup behavior from break_dispatch

tools/default_settings.py, tools/settings.py, tools/toolchains/__init__.py
This feature increases the comfortability of the mbed-cli within an offline IDE.
It allows the developer to jump directly to the error/warning instead of searching for the file and position.
Per default, mbed compile prints errors/warnings on output not in a link format, therefore it is not possible to click, i.e. in an IDE, on the errors/warnings and jump to the position of the file, or even know where (path) it is.
This feature generates an absolute path, because some IDEs are not parsing relatives paths correctly (i.e. VSCode).
In the linked picture, a compare between the default compile output and the newly one with the link is visualized.
[compare mbed compile output](http://www.screencast.com/t/6Aiy7brcWC7)
It is possible to activate/deactive the feature by setting this define …
=> Add parameter in tools settings to show error/warning as Link

features/nvstore/source/nvstore.h
Enclosing NVStore class with comments for Doxygen sake.
=> NVStore: add comments in header file for Doxygen formatting sake.

targets/targets.json
This fixes #6252 .  2 fixes here:
- two ram region used for L486 based targets (linker already defined two regions, macro was not set)
- the most important - use hex for Wise 1570 target
cc @ARMmbed/team-st-mcd 
@kimlep01 @mirelachirica @kivaisan I do not have the board to test it, please can you?
=> Fix for #6252

targets/TARGET_STM/rtc_api.c
When LSE is configured for RTC, LSI should not be affected
This fixes #6265 
@Mathgoat
=> STM32 RTC init

tools/export/iar/iar_definitions.json
=> Enable iar export option for MTB_ADV_WISE_1510

targets/TARGET_Realtek/TARGET_AMEBA/TARGET_RTL8195A/device/TOOLCHAIN_ARM_STD/rtl8195a.sct, targets/TARGET_Realtek/TARGET_AMEBA/TARGET_RTL8195A/device/TOOLCHAIN_GCC_ARM/rtl8195a.ld
Ameba has two memory blocks: SDRAM(2M) and SRAM(512KB). SRAM has better access performance than SDRAM. So some timing critical codes must be moved to SRAM.
fix for mbed-os issue #5778
rebase for #6289
=> rtl8195am : fix gpio toggle slow

TESTS/usb_device/basic/USBTester.cpp, targets/TARGET_Freescale/usb/USBEndpoints_Kinetis.h, targets/TARGET_Freescale/usb/USBPhyHw.h, targets/TARGET_Freescale/usb/USBPhy_Kinetis.cpp, targets/targets.json, usb/device/USBDevice/USBDevice.cpp, usb/device/USBDevice/USBDevice.h
- Add Kinetis USBPhy
- Add extra checks to USBDevice
- Fix read_start behavior when configuring
=> Add Kinetis USB Phy

TESTS/mbed_hal/watchdog_timing/main.cpp
Increased time measurement margins in `tests-mbed_hal-watchdog_timing`.
As it turned out during [this CI test run](http://mbed-os-logs.s3-website-us-west-1.amazonaws.com/?prefix=logs/6269/1218) for #6269, the timing margins were too tight for UBLOX_EVK_ODIN_W2 board.
CC @bulislaw @0xc0170 @scartmell-arm @jamesbeyond
=> Fix watchdog timing accuracy test for UBLOX_EVK_ODIN_W2

targets/TARGET_Analog_Devices/TARGET_ADUCM302X/TARGET_ADUCM3029/api/flash_api.c, targets/TARGET_Analog_Devices/TARGET_ADUCM4X50/TARGET_ADUCM4050/api/flash_api.c
- sector size is 0x800 bytes
- writeable unit size is 0x8 bytes
- flash start address is 0x0
- total ADuCM3029 on chip flash size is 0x40000 bytes
- total ADuCM4050 on chip flash size is 0x7F000 bytes
- #6318
`mbed test -t gcc_arm -m EV_COG_AD3029LZ -n mbed-os-features-nvstore-tests-nvstore-functionality,mbed-os-tests-mbed_drivers-flashiap,mbed-os-tests-mbed_hal-flash`
=> ADI: Fix on chip flash minimal programmable unit size

TESTS/usb_device/basic/USBTester.cpp, TESTS/usb_device/basic/USBTester.h, platform/USBPhy.h, targets/TARGET_Freescale/usb/USBPhyHw.h, targets/TARGET_Freescale/usb/USBPhy_Kinetis.cpp, targets/TARGET_NXP/TARGET_LPC176X/usb/USBHAL_LPC17.cpp, targets/TARGET_NXP/TARGET_LPC176X/usb/USBPhyHw.h, usb/device/USBDevice/USBDevice.cpp, usb/device/USBDevice/USBDevice.h
This PR adds bugfixes/improvements along with an API change to allow for zero copy USB transfers for endpoints. Changes before the commit `Update USBPhy to allow zero copy transfers` are the improvements and bug fixes. Changes after this are to update the code for this API.
Updated docs for this change can be found here:
https://github.com/ARMmbed/Handbook/pull/457
State diagram for previous USB endpoint API:
State diagram for enhanced USB endpoint API:
=> USB updates and enhancements

TESTS/host_tests/reset_reason.py, TESTS/mbed_drivers/reset_reason/ResetReason_tests.h, TESTS/mbed_drivers/reset_reason/main.cpp, TESTS/mbed_hal/reset_reason/main.cpp, TESTS/mbed_hal/reset_reason/reset_reason_api_tests.h, targets/TARGET_STM/reset_reason.c
Add tests for new Reset Reason API introduced in #5488:
* `tests-mbed_hal-reset_reason`,
* `tests-mbed_drivers-reset_reason`.
These testes were originally developed as a part of #5751, but are now separate to improve readability.
CC @bulislaw @0xc0170 @scartmell-arm @jamesbeyond
=> Add tests for Reset Reason API

tools/export/makefile/__init__.py, tools/export/uvision/uvision.tmpl
Without that fix, the generated `uvision` and `make_armc5` exports would not include the different project folders in the search path of the assembly command line. It forces the user of using `#include` with relative path.
These issues were discovered while doing the export test if the pull request #6168
=> Add include search path when preprocessing assembly files for uvision and make_armc5 exports

TESTS/mbed_hal/flash/functional_tests/main.cpp
Has been causing intermittent morph test failures with NRF52_DK boards
Disables the flash clock and cache tests. For a few weeks, this test would intermittently fail specifically against the NRF52_DK built against the GCC_ARM compiler.
An example failure:
```[1520888953.94][CONN][INF] found KV pair in stream: {{__testcase_finish;Flash - buffer alignment test;1;0}}, queued...
[1520888954.03][CONN][RXD] >>> Running case #6: 'Flash - clock and cache test'...
[1520888954.11][CONN][INF] found KV pair in stream: {{__testcase_start;Flash - clock and cache test}}, queued...
[1520888954.77][CONN][RXD] :273::FAIL: Values Not Within Delta 3016 Expected 603210 Was 590241
[1520888954.77][CONN][INF] found KV pair in stream: {{__testcase_finish;Flash - clock and cache test;0;1}}, queued... …
```
=> Disables flash clock and cache test

features/cellular/easy_cellular/EasyCellularConnection.cpp, features/cellular/easy_cellular/EasyCellularConnection.h, features/cellular/framework/AT/AT_CellularNetwork.cpp, features/cellular/framework/targets/QUECTEL/BC95/QUECTEL_BC95.cpp, features/cellular/framework/targets/QUECTEL/BC95/QUECTEL_BC95_CellularPower.h, features/cellular/framework/targets/QUECTEL/BC95/QUECTEL_BC95_CellularSIM.cpp, features/cellular/framework/targets/QUECTEL/BC95/QUECTEL_BC95_CellularSIM.h, features/cellular/framework/targets/QUECTEL/BC95/QUECTEL_BC95_CellularStack.cpp, features/cellular/framework/targets/QUECTEL/BG96/QUECTEL_BG96.cpp
Issues fixed:  getting host by name, socket send/recv iterations, SIM state retrieval. Additionaly, cellular APN lookup decision logic is fixed.
These issues were found when testing BC95 against https://github.com/ARMmbed/mbed-os-example-cellular.
=> Cellular: BC95 echo test fixes

targets/TARGET_STM/rtc_api.c
Division in a while loop is removed
You can read the study here:
https://github.com/ARMmbed/mbed-os/issues/6272#issuecomment-373017620
@marcemmers
=> STM32 LPTICKER : optimize RTC wake up timer init

features/filesystem/fat/FATFileSystem.cpp
Fix for: https://github.com/ARMmbed/sd-driver/issues/84
@geky @marcuschangarm
=> dir seek fixed - dptr was not updated before checking

features/cellular/framework/AT/AT_CellularNetwork.cpp
This pull request resolves the problem of test case 'attach' of cellular test suite introduced by ARM.
If AT+COPS=0 is sent and modem is already in automatic selection mode, the modem starts searching for another PLMN (different to that already in use) and takes some time. This is not required if the module is already in automatic selection mode. In this pull request, AT+COPS? is sent first to check if the module is already in automatic selection mode or not. If it is, there is no need for AT+COPS=0, otherwise it is sent and then waits for the module to register.
=> Cellular: update attach test

features/filesystem/littlefs/littlefs/lfs.c, features/filesystem/littlefs/littlefs/tests/test_dirs.sh, features/filesystem/littlefs/littlefs/tests/test_files.sh
Like most of the lfs_dir_t functions, lfs_dir_append is responsible for updating the lfs_dir_t struct if the underlying directory block is moved. This property makes handling worn out blocks much easier by removing the amount of state that needs to be considered during a directory update.
However, extending the dir chain is a bit of a corner case. It's not changing the old block, but callers of lfs_dir_append do assume the "entry" will reside in "dir" after lfs_dir_append completes.
This issue only occurs when creating files, since mkdir does not use the entry after lfs_dir_append. Unfortunately, the tests against extending the directory chain were all made using mkdir.
cc @deepikabhavnani, @kegilbert 
intended for patch
=> littlefs: Fix issue updating dir struct when extended dir chain

features/FEATURE_LWIP/lwip-interface/lwip_stack.c
Corrected LWIP TCP flagging. Some TCP code was not flagged which caused compilation error in UDP only configuration.
=> Corrected lwip adaptation TCP flagging

targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L433xC/TARGET_NUCLEO_L433RC_P/PinNames.h
This PR makes some corrections on pins definitions:
- corrects the LEDs
- remove A6 and A7 (don't exist on Arduino connector)
- add D14 and D15
Problem with the LED has been identified here:
https://os.mbed.com/questions/80256/Cant-compile-NUCLEO-L433RC-P-board/
[x] Fix
[  ] Refactor
[  ] New target
[  ] Feature
[  ] Breaking change
=> NUCLEO_L433RC_P: fix pins definitions

features/FEATURE_COMMON_PAL/mbed-coap/CHANGELOG.md, features/FEATURE_COMMON_PAL/mbed-coap/mbed-coap/sn_coap_protocol.h, features/FEATURE_COMMON_PAL/mbed-coap/mbed-coap/sn_config.h, features/FEATURE_COMMON_PAL/mbed-coap/module.json, features/FEATURE_COMMON_PAL/mbed-coap/source/include/sn_coap_protocol_internal.h, features/FEATURE_COMMON_PAL/mbed-coap/source/sn_coap_protocol.c
Make sn_coap_protocol_send_rst as public needed for CoAP ping sending
Allow disabling resendings by defining SN_COAP_DISABLE_RESENDINGS
=> Update mbed-coap to version 4.4.0

targets/TARGET_NUVOTON/TARGET_M451/serial_api.c, targets/TARGET_NUVOTON/TARGET_M480/serial_api.c, targets/TARGET_NUVOTON/TARGET_NANO100/serial_api.c, targets/TARGET_NUVOTON/TARGET_NUC472/serial_api.c
In UART DMA transfer, it is PDMA INT rather than UART INT to go INT path. So remove unnecessary UART INT in UART DMA transfer.
=> Nuvoton: Remove unnecessary UART INT in UART DMA transfer

tools/toolchains/arm.py
Fix armcc recompile errors during elf2bin stage. Errors shown as follows:
Elf2Bin: mbed-os-example-wifi
Error: Q0147E: Failed to create Directory .\BUILD\REALTEK_RTL8195AM\ARM\mbed-os-example-wifi.bin\IMAGE2_TABLE: File exists
Finished: 0 information, 0 warning and 1 error messages.
[ERROR] Error: Q0147E: Failed to create Directory .\BUILD\REALTEK_RTL8195AM\ARM\mbed-os-example-wifi.bin\IMAGE2_TABLE: File exists
Finished: 0 information, 0 warning and 1 error messages.
Fix issue #6306
=> armcc - remove fromelf output before regenerating one

targets/TARGET_ARM_SSG/TARGET_CM3DS_MPS2/README.md, targets/TARGET_ARM_SSG/TARGET_CM3DS_MPS2/device/TOOLCHAIN_ARM_STD/MPS2.sct, targets/TARGET_ARM_SSG/TARGET_CM3DS_MPS2/device/TOOLCHAIN_ARM_STD/startup_MPS2.S, targets/TARGET_ARM_SSG/TARGET_CM3DS_MPS2/device/TOOLCHAIN_GCC_ARM/MPS2.ld, targets/TARGET_ARM_SSG/TARGET_CM3DS_MPS2/device/TOOLCHAIN_IAR/MPS2.icf, targets/TARGET_ARM_SSG/TARGET_CM3DS_MPS2/device/cmsis_nvic.h, targets/TARGET_ARM_SSG/TARGET_CM3DS_MPS2/device/memory_zones.h, targets/TARGET_ARM_SSG/mbed_rtx.h, targets/targets.json
This pull request contains memory changes for the CM3DS target.
It is the pull request 2 among the 4 concerning CM3DS Maintenance. Please check #6119 for the full scope.
Other pull requests regarding this target:
* CM3DS Maintenance Pull Request: Bug fixes (1/4) #6167
* CM3DS Maintenance Pull Request: Memory changes (2/4) #6168
* CM3DS Maintenance Pull Request: TRNG support (3/4) #6169
* CM3DS Maintenance Pull Request: Driver updates (4/4) #6170
=> CM3DS Maintenance Pull Request: Memory changes (2/4)

platform/mbed_critical.c, platform/mbed_critical.h
Code clean up - the atomic code is confused about the use and meaning of `volatile`. It's using casts internally where not necessary, and potentially forcing users to insert casts.
Only visible change to application code is that
volatile uint8_t my_volatile;
core_util_atomic_incr_u8(&my_volatile, 1);
will now work - previously it would have required
core_util_atomic_incr_u8((uint8_t *)&my_volatile, 1);
This will continue to work:
uint8_t my_non_volatile;
core_util_atomic_incr_u8(&my_non_volatile, 1);
Change broken into two individual commits to try to avoid impression that the net change is just expecting users to be providing volatile objects - see commit messages for more detail.
(Given the lack of a full suite of atomic operations including load and store, it's probably the case that …
=> Sort out volatiles in the atomic functions

.travis.yml, usb/device/USBSerial/USBCDC.cpp, usb/device/USBSerial/USBCDC.h, usb/device/USBSerial/USBSerial.cpp, usb/device/USBSerial/USBSerial.h, usb/device/utilities/AsyncOp.cpp, usb/device/utilities/AsyncOp.h, usb/device/utilities/LinkEntry.h, usb/device/utilities/LinkedList.h, usb/device/utilities/LinkedListBase.cpp, usb/device/utilities/LinkedListBase.h
Update the USBCDC and USBSerial classes to the new API. This PR also updates the blocking behavior to unblock at the appropriate times and to let the processor sleep when blocking rather than busy waiting.
=> Update USBCDC and USBSerial

targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_adc.c
Issue detected in #6398 
Only 1 internal channel could be configured which was wrong.
@maskedw
=> STM32L4 ADC correct internal channel management

TESTS/mbedmicro-rtos-mbed/CircularBuffer/main.cpp, platform/CircularBuffer.h
Added `peek` API to view data of CircularBuffer without popping.
=> Peek API to view data of buffer without popping

TESTS/host_tests/pyusb_basic.py, TESTS/usb_device/basic/USBTester.cpp, TESTS/usb_device/basic/USBTester.h, TESTS/usb_device/basic/main.cpp
USB generic test suite
In development
=> USB generic tests

targets/TARGET_STM/qspi_api.c
The ST HAL code is waiting for the correctly shifted vlue
(for a direct write into the HW register)
=> Fix Address.Size and AlternateByes.Size by shifting them

targets/TARGET_STM/qspi_api.c
Adding QSPI_DATA_NONE activates the transfer
of the command inside HAL_QSPI_COMMAND function
(otherwise a command that does not send data or address will not be transmitted)
=> QSPI: Fix Instruction with no data command

features/netsocket/emac-drivers/TARGET_STM_EMAC/stm32xx_emac.cpp, features/netsocket/emac-drivers/TARGET_STM_EMAC/stm32xx_emac.h
Changed EMAC STM driver to loop RX frame reading. Changed HAL_ETH_GetReceivedFrame to HAL_ETH_GetReceivedFrame_IT to get the next frame correctly.
[X] Fix
[ ] Refactor  
[ ] Feature  
=> Changed STM emac driver to loop RX frame reading

targets/TARGET_Realtek/TARGET_AMEBA/TARGET_RTL8195A/log_uart_api.c, targets/TARGET_Realtek/TARGET_AMEBA/TARGET_RTL8195A/serial_api.c
- fix for issue #6358
- add Mask & UnMask Tx FIFO empty interrupt for LogUart
- fix LogUart interrupt enable
- fix LogUart interrupt handler
- coding style fix
=> rtl8195am: fix LogUART Tx interrupt crash

drivers/QSPI.cpp, drivers/QSPI.h
It can change depending on the chosen command, not only at start.
This way we avoid to launch init function and break the internal status variables.
=> QSPI: Dummy cycles count is not an init parameter, but a command parameter

tools/get_config.py
`mbed compile --config` currently fails for me on master with:
```
File "/home/jimmy/src/armmbed/fat-fs/mbed-os/tools/get_config.py", line 31, in <module>
from config import Config
File "/home/jimmy/src/armmbed/mbed-os/tools/config/__init__.py", line 33, in <module>
from ..utils import json_file_to_dict, intelhex_offset, integer
ValueError: Attempted relative import beyond toplevel package
```
This is related to the incorrect path to the config import
=> Correct get_config imports

drivers/SerialWireOutput.h
Added the SerialWireOutput driver to the mbed namespace
See issue #6421 
See why this is a good idea in #5679
[X] Fix  
[ ] Refactor  
[ ] Feature  
=> Added SerialWireOutput to mbed namespace

drivers/InterruptIn.cpp, drivers/InterruptIn.h
Currently there's no way to specify the `PinMode` (`PullUp`, `PullDown`, etc.) in the `InterruptIn` constructor. So I added one, like `DigitalIn`.
Later: Would it make even more sense to have `InterruptIn` inherit from `DigitalIn`?
=> Interrupt in pin mode

targets/TARGET_NUVOTON/TARGET_M451/flash_api.c, targets/TARGET_NUVOTON/TARGET_M480/flash_api.c, targets/TARGET_NUVOTON/TARGET_NUC472/flash_api.c
This PR includes a bugfix for NVSTORE test (mbed-os-features-nvstore-tests-nvstore-functionality) failed.
[X] Fix
[ ] Refactor
[ ] New target
[ ] Feature
=> Nuvoton: Fix NVSTORE test failed

targets/TARGET_STM/qspi_api.c
With 32 previous value, we cannot write in the memory, it returns an error (invalid address)
Don't you think that this size should become a parameter of the object init function in a later version ?
Kind regards
=> QSPI: STM - change default FlashSize to 64Mbit = 8Mbytes = 0x800000

targets/TARGET_NORDIC/TARGET_NRF5x/PeripheralPinsDefault.c, targets/TARGET_NORDIC/TARGET_NRF5x/README.md, targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/TARGET_MCU_NRF52832/PeripheralNames.h, targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/TARGET_MCU_NRF52832/TARGET_DELTA_DFBM_NQ620/PinNames.h, targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/TARGET_MCU_NRF52832/TARGET_MTB_UBLOX_NINA_B1/PinNames.h, targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/TARGET_MCU_NRF52832/TARGET_NRF52_DK/PinNames.h, targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/TARGET_MCU_NRF52832/TARGET_RBLAB_BLENANO2/PinNames.h, targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/TARGET_MCU_NRF52832/TARGET_UBLOX_EVA_NINA/PinNames.h, targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/TARGET_MCU_NRF52832/TARGET_UBLOX_EVK_NINA_B1/PinNames.h, targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/TARGET_MCU_NRF52832/TARGET_VBLUNO52/PinNames.h, targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/TARGET_MCU_NRF52832/config/sdk_config.h, targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/TARGET_MCU_NRF52840/PeripheralNames.h, targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/TARGET_MCU_NRF52840/TARGET_NRF52840_DK/PinNames.h, targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/TARGET_MCU_NRF52840/config/sdk_config.h, targets/TARGET_NORDIC/TARGET_NRF5x/mbed_lib.json, targets/TARGET_NORDIC/TARGET_NRF5x/objects.h, targets/TARGET_NORDIC/TARGET_NRF5x/pinmap_ex.c, targets/TARGET_NORDIC/TARGET_NRF5x/pinmap_ex.h, targets/TARGET_NORDIC/TARGET_NRF5x/serial_api.c
From the README:
The serial implementation uses the UARTE module which works exclusively through EasyDMA and RAM buffers. For optimal performance, each configured instance (NRF52832 has 1, NRF52840 has 2) has three buffers statically assigned:
1. Rx DMA buffer, which EasyDMA is currently writing to.
1. Rx DMA buffer, pre-loaded in EasyDMA for automatic switchover.
1. Rx FIFO buffer, for serving data to the application.
When the first DMA buffer is full or flushed the interrupt handler will automatically copy the DMA buffer to the FIFO buffer. This happens in interrupt context to avoid data loss and with UARTE interrupts set at the highest priority. The FIFO buffer is backed by the Nordic atomic fifo, which can be read and written to safely without disabling interrupts. 
All buffers can be …
=> [feature-nrf528xx] Serial re-implementation for the NRF52 series

TESTS/host_tests/pyusb_basic.py
USB generic tests change to fix OSX behavior
`CLEAR/SET_FEATURE` requests on `CTRL_IN` endpoint was removed from `set_clear_feature_test`
[X] Fix  
[ ] Refactor  
[ ] Feature  
=> Fix for USB set_clear_feature_test for OSX

targets/targets.json
This was used for Doxygen in the past, but now the Doxygen uses a
whitelist of directories to scan. I think it makes sense to remove this
if only to avoid confusion.
[x] Fix 
[ ] Refactor 
[ ] New target 
[ ] Feature 
=> Remove supertarget

tools/export/__init__.py
This bug was found on the website, is already going to be deployed
independent of this PR. This just upstreams the changes
=> Avoid incorrect config errors on export with many --source

features/FEATURE_LWIP/lwip-interface/lwip_stack.c
Glue code was inspecting lwIP's netconn `type`, checking directly for `NETCONN_UDP` and `NETCONN_TCP`.
Unfortunately the type byte has some flag bits like "IPv6", which means the tests fail if it's an IPv6 socket. So, for example, TCP socket options were rejected for IPv6.
Add the necessary `NETCONNTYPE_GROUP` macros to fix this.
=> lwIP: fix some IPv6 errors, eg TCP keepalive

doxyfile_options, doxygen_options.json, features/nanostack/FEATURE_NANOSTACK/mbed-mesh-api/mbed-mesh-api/LoWPANNDInterface.h, features/nanostack/FEATURE_NANOSTACK/mbed-mesh-api/mbed-mesh-api/MeshInterfaceNanostack.h, features/nanostack/FEATURE_NANOSTACK/mbed-mesh-api/mbed-mesh-api/NanostackEthernetInterface.h, features/nanostack/FEATURE_NANOSTACK/mbed-mesh-api/mbed-mesh-api/ThreadInterface.h, features/nanostack/FEATURE_NANOSTACK/mbed-mesh-api/mbed-mesh-api/mesh_interface_types.h, features/nanostack/FEATURE_NANOSTACK/nanostack-interface/NanostackEthernetPhy.h, features/nanostack/FEATURE_NANOSTACK/nanostack-interface/NanostackInterface.h, features/nanostack/FEATURE_NANOSTACK/nanostack-interface/NanostackPhy.h, features/nanostack/FEATURE_NANOSTACK/nanostack-interface/NanostackRfPhy.h
* Add missing Doxygen descriptions for Nanostack and Mesh-API files.
* Enable building of Doxygen documentation for Nanostack related headers.
=> Add missing Doxygen descriptions for Nanostack

TESTS/usb_device/basic/USBTester.cpp
Change the name reported by USBTester from CDC DEVICE to MBED TEST DEVICE to make it more recognizable.
=> Update USBTester product name

TESTS/host_tests/pyusb_basic.py, TESTS/usb_device/basic/main.cpp
OSX machines don't allow you to reset USB devices. Skip this test on OSX so testing can still be used.
=> Skip USB reset tests on OSX

TESTS/mbed_drivers/timeout/timeout_tests.h, TESTS/mbedmicro-rtos-mbed/systimer/main.cpp, features/unsupported/tests/utest/lp_ticker/lp_ticker.cpp, rtos/TARGET_CORTEX/SysTimer.cpp, rtos/TARGET_CORTEX/SysTimer.h, targets/targets.json
Fix rebase error for LP ticker feature branch
[x] Fix  
[ ] Refactor  
[ ] Feature  
@0xc0170
=> Fix rebase error for LP ticker feature branch

tools/export/exporters.py, tools/export/gnuarmeclipse/__init__.py, tools/export/uvision/__init__.py
The size of uvision include paths can break the exporter with very large
projects. Some nordic devices are very large projects by themselves.
[x] Fix  
[ ] Refactor  
[ ] Feature  
=> Minimize the size of uvision include paths

TESTS/mbed_hal/common_tickers/main.cpp
Provide fixes for HAL lp/us ticker test.
[X] Fix  
[ ] Refactor  
[ ] Feature  
=> Provide fixes for HAL ticker test

targets/TARGET_Silicon_Labs/TARGET_EFM32/resetreason_api.c, targets/TARGET_Silicon_Labs/TARGET_EFM32/watchdog_api.c, targets/targets.json
Implementation of both watchdog and reset reason APIs for all Silicon Labs parts.
Test results:
```
+---------------------------+-------------------+-----------------------------+-----------------------------+--------+--------+--------+--------------------+
| target                    | platform_name     | test suite                  | test case                   | passed | failed | result | elapsed_time (sec) |
+---------------------------+-------------------+-----------------------------+-----------------------------+--------+--------+--------+--------------------+
| EFM32PG12_STK3402-GCC_ARM | EFM32PG12_STK3402 | tests-mbed_hal-reset_reason | tests-mbed_hal-reset_reason | 1      | 0      | OK     | 33.53              |
+---------------------------+-------------------+------------------- …
```
=> Implement watchdog and reset reason APIs on Silicon Labs parts

hal/TARGET_FLASH_CMSIS_ALGO/flash_data.h
This should make some of the data more clear to a user
Documentation update for flash algo CMSIS
Feedback received here https://github.com/ARMmbed/mbed-os/issues/6318#issuecomment-373258346
cc @li-ho
=> flash: add docs for user defined data

targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KL82Z/TARGET_FRDM/mbed_overrides.c, targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KL82Z/TARGET_USENSE/mbed_overrides.c, targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KL82Z/peripheral_clock_defines.h, targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KL82Z/serial_api.c
Fixes UART issues seen on the KL82Z FRDM board.
=> KL82Z: Update the clock selection method for LPUART module

targets/TARGET_Silicon_Labs/TARGET_EFM32/TARGET_EFM32PG12/device/TOOLCHAIN_ARM_STD/startup_efm32pg12b.S, targets/TARGET_Silicon_Labs/TARGET_EFM32/TARGET_EFR32MG1/device/TOOLCHAIN_ARM_STD/startup_efr32mg1p.S, targets/TARGET_Silicon_Labs/TARGET_EFM32/TARGET_EFR32MG12/device/TOOLCHAIN_ARM_STD/startup_efr32mg12p.S
EFR32MG1, EFR32MG12 and EFM32PG12 didn't have a fixed ARMCC linker script yet.
=> Fix initial SP for new Silicon Labs targets on ARMCC

targets/TARGET_NORDIC/TARGET_NRF5x/serial_api.c
Fixed a bug preventing serial_putc from working when interrupts were disabled. 
Added resource counting and implemented missing serial_free function.
[x] Fix  
[ ] Refactor  
[ ] Feature  
=> [feature-nrf528xx] NRF52 serial bug fix and serial_free implementation

targets/TARGET_NUVOTON/TARGET_M451/lp_ticker.c, targets/TARGET_NUVOTON/TARGET_M451/us_ticker.c, targets/TARGET_NUVOTON/TARGET_M480/lp_ticker.c, targets/TARGET_NUVOTON/TARGET_M480/us_ticker.c, targets/TARGET_NUVOTON/TARGET_NANO100/lp_ticker.c, targets/TARGET_NUVOTON/TARGET_NANO100/us_ticker.c, targets/TARGET_NUVOTON/TARGET_NUC472/lp_ticker.c, targets/TARGET_NUVOTON/TARGET_NUC472/us_ticker.c
This PR includes the fixes with us_ticker/lp_ticer:
1. Check timer active flag after enabling timer counting
1. Remove unnecessary TIMER_Start in the end of lp_ticker_set_interrupt
1. Add missing delay in lp_ticker
=> Nuvoton: Fix us_ticker/lp_ticker

targets/targets.json
This PR activates tickless mode on Silicon Labs targets.
Tests ran:
With lp_ticker backed by RTC: (EFM32LG, EFM32WG, EFM32GG, EFM32HG, EFM32ZG all use the same peripheral so would be covered by this test)
```+-------------------------+-----------------+----------------------------------------------+--------+--------------------+-------------+
| target                  | platform_name   | test suite                                   | result | elapsed_time (sec) | copy_method |
+-------------------------+-----------------+----------------------------------------------+--------+--------------------+-------------+
| EFM32LG_STK3600-GCC_ARM | EFM32LG_STK3600 | tests-mbedmicro-rtos-mbed-basic              | OK     | 30.57              | default     |
| EFM32LG_STK3600-GCC_ARM | EFM32LG_STK3600 …
```
=> Enable tickless mode on Silicon Labs targets

TESTS/host_tests/pyusb_basic.py
Change the direction used in set interface to match the USB specification. This allows USB tests to pass on OSX.
=> Fix USB tests

features/FEATURE_BLE/ble/pal/MemorySecurityDb.h, features/FEATURE_BLE/ble/pal/SecurityDb.h, features/FEATURE_BLE/targets/TARGET_CORDIO/CordioBLE.h
Fix for #6476.
The SecurityDb/MemorySecurityDb had some casing inconsistencies across the BLE security manager implementation which created some compilation issues when compiling from a case-sensitive filesystem.
This PR fixes these inconsistencies.
[X] Fix  
[ ] Refactor  
[ ] Feature  
=> [BLE] Fixed inconsistent casing issue for SecurityDb

targets/TARGET_NORDIC/TARGET_NRF5x/serial_api.c
Off-by-one error prevented UART from being disabled even when no  instance(s) were in user.
[x] Fix  
[ ] Refactor  
[ ] Feature  
=> [feature-nrf528xx] Fix off-by-one error in NRF52 serial implementation

tools/build_api.py, tools/config/__init__.py
A recent PR of mine stopped the exporters from using the build_api's
unified scan_resourcses method. Instead, I moved the supported check to
the earliest location that we have this informaiton: the end of the
config object's load_resources method.
[x] Fix  
[ ] Refactor  
[ ] Feature  
=> Move Mbed 5 support check so that it affects the exporters

features/nvstore/TESTS/nvstore/functionality/main.cpp
On the NRF52, the NVStore test is running at the stack boundary so on certain compiler versions the test will fail due to stack overflow. This PR increases the stack size for the NRF52 target.
[x] Fix  
[ ] Refactor  
[ ] Feature  
=> Inrease thread stack size to 1024 bytes in NVStore test for NRF52

drivers/QSPI.cpp, drivers/QSPI.h
QSPI::configure_format is supposed to modify command format, not the hw module itself. 
It should not call the QSPI::_initialize function
_mode (clock polarity and clock phase) is only used at initialization of the module.
Then : _mode (clock polarity and phase) cannot be modified inside QSPI::configure_format. This has been moved to QSPI::QSPI function
I've reverted PR#6429 commit, since now dummy count can be modified inside configure_format again.
[X] Fix
[ ] Refactor
[ ] New target
[ ] Feature
cc @0xc0170
=> Qspi fix configure format

drivers/Timeout.cpp
Detach in the Timeout::handler so deep sleep is properly unlocked.
[X] Fix  
[ ] Refactor  
[ ] Feature  
=> Fix deep sleep locking for Timeout class

.travis.yml
Added test to check line-ending problems. Related to this discussion: https://github.com/ARMmbed/mbed-os/pull/6450
[x] Fix  
[ ] Refactor  
[ ] Feature  
=> Test line-ending problems

targets/TARGET_Analog_Devices/TARGET_ADUCM302X/TARGET_ADUCM3029/api/us_ticker.c, targets/TARGET_Analog_Devices/TARGET_ADUCM4X50/TARGET_ADUCM4050/api/us_ticker.c
- fix us_ticker_fire_interrupt() bugs of EV_COG_AD3029LZ and EV_COG_AD4050LZ
- ensure us_ticker_irq_handler() is called only when GP2 timer expires
- set us_ticker_set_interrupt() time interval to be 9.846 us
- set us_ticker_fire_interrupt() time interval to be 0.03846 us
- #6448
- #6319
mbed test -m EV_COG_AD3029LZ -t GCC_ARM -n mbed-os-tests-mbed_drivers-timerevent,mbed-os-tests-mbed_platform-critical_section
mbed test -m EV_COG_AD4050LZ -t GCC_ARM -n mbed-os-tests-mbed_drivers-timerevent,mbed-os-tests-mbed_platform-critical_section
=> ADI: Fix EV_COG_AD3029LZ and EV_COG_AD4050LZ us_ticker_fire_interrupt() minimal time interval

features/netsocket/SocketAddress.cpp
If newlib is compiled without C99 switch, `%hhu` will be missing. Newlib sources:
https://github.com/eblot/newlib/blob/2a63fa0fd26ffb6603f69d9e369e944fe449c246/newlib/libc/stdio/vfscanf.c#L588-L596
Created as https://os.mbed.com/forum/bugs-suggestions/topic/30567/
Proceed there for more info.
[x] Fix  
[ ] Refactor  
[ ] Feature  
=> Fix IPv4 address parsing due to not-so-portable scanf modifier

features/lorawan/lorastack/phy/LoRaPHY.cpp
- Arm internal ref: IOTCELL-754
There was a parsing issue in cflist handling and it is fixed in this PR:
https://github.com/ARMmbed/mbed-os/issues/6556
[X] Fix
[ ] Refactor
[ ] New target
[ ] Feature
=> LoRa: Fixed cflist decoding issue

tools/config/__init__.py
Resolves #5908
[✓] Fix  
[ ] Refactor  
[ ] Feature  
=> Error on invalid mbed_lib JSON

tools/toolchains/__init__.py
It was possible before to compile files starting with a `.`, I have removed that capability. I also stopped recording the base path of files we are not adding to the build.
Resolves #5331
[x] Fix  
[ ] Refactor  
[ ] Feature  
=> Exclude files like `.main.cpp` from builds

TESTS/mbed_hal/common_tickers/main.cpp
Update the ticker common test to clean up after each case by restoring the ticker IRQ handler. This allows tickers to function normally after each case has completed.
=> Restore ticker state after each test

targets/TARGET_STM/TARGET_STM32L4/l4_retarget.c, targets/TARGET_STM/mbed_rtx.h
The following targets did not compile tests before this change:
* NUCLEO_L476RG
* NUCLEO_L486RG
They now compile tests
[✓] Fix  
[ ] Refactor  
[ ] Feature  
=> Correct armc6 detection logic for STM32L4

features/lorawan/LoRaWANStack.cpp, features/lorawan/LoRaWANStack.h, features/lorawan/lorastack/mac/LoRaMac.cpp, features/lorawan/lorastack/mac/LoRaMac.h, features/lorawan/lorastack/phy/loraphy_target.h, features/lorawan/mbed_lib.json, features/lorawan/system/lorawan_data_structures.h
Refactored and cleaned up some internal code. 
Tested manually by running tests locally
[ ] Fix  
[ X] Refactor  
[ ] Feature  
=> LoRa: Stack cleanup

features/mbedtls/importer/adjust-config.sh
This PR adds a check for the NV_SEED option in the script that imports the Mbed TLS library.
[x] Fix  
[ ] Refactor  
[ ] Feature  
=> Add an NV_SEED test to the config adjustment script

features/cellular/framework/AT/ATHandler.cpp, features/cellular/framework/AT/ATHandler.h, features/cellular/framework/AT/AT_CellularDevice.cpp, features/cellular/framework/AT/AT_CellularDevice.h, features/cellular/framework/targets/TELIT/HE910/TELIT_HE910.cpp, features/cellular/framework/targets/TELIT/HE910/TELIT_HE910.h
For some modems there is a minimum delay between the end of the response of the previous command and the beginning of a new command, and this change takes into account that kind of requirement. The delay set to 20 ms for Telit HE910 modems. The change is tested with a Telit HE910 modem
[ X ] Fix  
[ ] Refactor  
[  ] Feature  
=> cellular: ATHandler send delay

targets/targets.json
remove this target from json file as this is not a real target but a parent target
[ X] Fix  
[ ] Refactor  
[ ] Feature  
=> remove MODULE_UBLOX_ODIN_W2 from targets.json

.travis.yml
Using credentials avoids rate-limiting based on Travis's IP address
Sometimes curl commands against the Github API fail. Turns out this is caused by rate-limiting when credentials aren't provided, which is then based on Travis's IP address. Always using credentials even for GETs to public endpoints fixes the problem.
Note, this isn't high priority since right now we're only using uncredentialed GETs in status messages.
[✓] Fix  
[ ] Refactor  
[ ] Feature  
=> Travis: Fix rate-limit issue with Github requests

TESTS/mbed_hal/lp_ticker/main.cpp
Add overflow protection for HAL lp ticker tests. 
[X] Fix  
[ ] Refactor  
[ ] Feature  
=>  tests-mbed_hal-lp_ticker: Add overflow protection.

features/nvstore/source/nvstore.cpp
I believe the below code is a typo:
**mbed-os/features/nvstore/source/nvstore.cpp**:
```
memcpy(_flash_area_params, 0, sizeof(_flash_area_params));
```
And I fix as below:
```
memset(_flash_area_params, 0, sizeof(_flash_area_params));
```
Because `_flash_area_params` will be re-initialized later, the typo won't cause trouble on most targets. But it will on **NUMAKER_PFM_M2351** port of which is on-going. **NUMAKER_PFM_M2351** is Cortex-M23 based and has TrustZone support. Read flash address `0` is not always legal because flash is partitioned into secure/non-secure.
[X] Fix  
[ ] Refactor  
[ ] Feature  
=> Fix typo with NVStore

features/lorawan/LoRaWANBase.h, features/lorawan/LoRaWANInterface.cpp, features/lorawan/LoRaWANInterface.h, features/lorawan/LoRaWANStack.cpp, features/lorawan/LoRaWANStack.h, features/lorawan/lorastack/mac/LoRaMac.cpp, features/lorawan/lorastack/mac/LoRaMac.h, features/lorawan/lorastack/mac/LoRaMacChannelPlan.cpp, features/lorawan/lorastack/mac/LoRaMacChannelPlan.h, features/lorawan/lorastack/mac/LoRaMacCommand.cpp, features/lorawan/lorastack/mac/LoRaMacCommand.h, features/lorawan/lorastack/mac/LoRaMacCrypto.cpp, features/lorawan/lorastack/phy/LoRaPHY.cpp, features/lorawan/lorastack/phy/LoRaPHY.h, features/lorawan/lorastack/phy/LoRaPHYUS915Hybrid.h, features/lorawan/lorastack/phy/lora_phy_ds.h, features/lorawan/system/LoRaWANTimer.cpp, features/lorawan/system/LoRaWANTimer.h
Internal include paths were using paths starting with lorawan which is not necessary.
In some cases .cpp files included it's .h file with full internal path.
These are now harmonised in this PR.
This is 5.9 content
[ ] Fix  
[ X] Refactor  
[ ] Feature  
=> LoRa: Internal include paths corrected

features/lorawan/LoRaWANBase.h, features/lorawan/LoRaWANInterface.cpp, features/lorawan/LoRaWANInterface.h, features/lorawan/LoRaWANStack.cpp, features/lorawan/LoRaWANStack.h
This is a fix for issue #6389.
Currently when application receives RX_DONE event from stack, it has to provide the correct port
value to receive method in order to read the received message. The problem is that current
API does not provide any way to know in to which port message was received.
This commit introduces a new receive() method, which instead of checking these values, will return
them to application.
This is mbed-os 5.9 content.
[ ] Fix  
[ ] Refactor  
[X] Feature  
=> Lora: Introduce new receive API which returns port and flags

targets/targets.json
As noticed in Issue #6549 the clock_source configuration was incorrectly set for this board. The MCU is clocked with an external clock on OSCIN pin and not using an XTAL on OSCIN/OSCOUT pins.
Tested OK on all compilers.
[X] Fix  
[ ] Refactor  
[ ] Feature  
=> DISCO_F769NI: set clock_source to USE_PLL_HSE_EXTC

platform/mbed_lib.json, platform/mbed_poll.cpp
Similar to `use-lowpower-timer-ticker` in `events/`
This allows to use LEUART / LPUART with an ability to enter deep sleep.
For example, the cellular modem can stay constantly connected, listening for events, without preventing deep sleep.
=> Add an option to use LowPowerTimer for poll

features/lorawan/LoRaWANStack.cpp, features/lorawan/lorastack/mac/LoRaMac.cpp
Small fixes to LoRa stack
[X] Fix  
[ ] Refactor  
[ ] Feature  
=> Lora: small fixes

features/lorawan/lorastack/phy/LoRaPHYAU915.cpp
Bug was reported by @tpet93 and it was correctly diagnosed that channels
were not being set in the phy_params structure. This commit fixes the bug
and sets up channels correctly.
[X] Fix  
[ ] Refactor  
[ ] Feature  
=> [IOTCELL] Setting up channels for AU915

features/FEATURE_COMMON_PAL/mbed-coap/CHANGELOG.md, features/FEATURE_COMMON_PAL/mbed-coap/module.json, features/FEATURE_COMMON_PAL/mbed-coap/source/sn_coap_protocol.c
Contains one error fix:
IOTCLT-2469 CoAP UDP retransmission does not work for blocks after first one for requests (Eg. registration POST)
NOTE! These are internal changes required for cloud client. This has no direct relevance to any mbed-os functionality.
[X] Fix  
[ ] Refactor  
[ ] Feature  
=> Update mbed-coap to version 4.4.2

features/cellular/easy_cellular/CellularConnectionFSM.cpp, features/cellular/easy_cellular/CellularConnectionFSM.h, features/cellular/framework/AT/AT_CellularNetwork.cpp
Separated context activation in CellularConnectionFSM state machine.
@AriParkkila please review.
[X] Fix  
[ ] Refactor  
[ ] Feature  
=> Cellular: Separated context activation in CellularConnectionFSM.

targets/TARGET_Realtek/TARGET_AMEBA/TARGET_RTL8195A/PinNames.h, targets/TARGET_Realtek/TARGET_AMEBA/sdk/soc/realtek/8195a/fwlib/hal_i2c.h
Fix hundreds of excessive compiler warnings due to out of enum type range
Examples shown as follows:
mbed-os.lib/targets/TARGET_Realtek/TARGET_AMEBA/sdk/soc/realtek/8195a/fwlib/hal_i2c.h", Line: 329, Col: 34
mbed-os.lib/targets/TARGET_Realtek/TARGET_AMEBA/TARGET_RTL8195A/PinNames.h", Line: 172, Col: 11
[x ] Fix  
[ ] Refactor  
[ ] Feature  
=> rtl8195am - fix excessive compiler warnings

features/FEATURE_LWIP/lwip-interface/lwip_stack.c
```
In file included from .././features/FEATURE_LWIP/lwip-interface/lwip/src/include/lwip/ip_addr.h:43:0,
from .././features/FEATURE_LWIP/lwip-interface/lwip/src/include/lwip/netif.h:46,
from ../features/FEATURE_LWIP/lwip-interface/lwip_stack.h:23,
from ../features/FEATURE_LWIP/lwip-interface/lwip_stack.c:23:
../features/FEATURE_LWIP/lwip-interface/lwip_stack.c: In function 'mbed_lwip_socket_bind':
.././features/FEATURE_LWIP/lwip-interface/lwip/src/include/lwip/ip4_addr.h:171:40: warning: the comparison will always evaluate as 'false' for the address of 'ip_addr' will never be NULL [-Waddress]
#define ip4_addr_isany(addr1) ((addr1) == NULL || ip4_addr_isany_val(*(addr1)))
^
.././features/FEATURE_LWIP/lwip-interface/lwip/src/include/lwip/ip_addr.h:272:49: note: in expansion of macro …
```
=> Macro expansion results in a constant boolean expression

targets/TARGET_STM/TARGET_STM32F1/device/stm32f1xx_hal_pcd.c, targets/TARGET_STM/TARGET_STM32F2/device/stm32f2xx_hal_pcd.c, targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_pcd.c, targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_pcd.c, targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_pcd.c
This issue was initiated by a compiler warning
```
Compile: stm32f7xx_hal_pcd.c
../targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_pcd.c: In function 'PCD_WriteEmptyTxFifo':
../targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_pcd.c:1310:11: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
if (len > ep->maxpacket)
^
../targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_pcd.c:1325:13: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
if (len > ep->maxpacket)
^
```
My first pass at fixing this issue concentrated on the comparison itself.  The implementation can be seen at https://github.com/pauluap/mbed-os/commit/c6ca03df764a16b4a36e5598f881acf601fb9b0f
Upon inspection, I determined that there were …
=> STM32 PCD negative numbers issue

targets/TARGET_Maxim/TARGET_MAX32625/rtc_api.c, targets/TARGET_Maxim/TARGET_MAX32625/spi_api.c, targets/TARGET_Maxim/TARGET_MAX32625/us_ticker.c
Fix issue: #5309
Simplify tickers to stop emulating 1us ticks by using native timer resolutions.
Implement ticker get info functions.
Separate rtc and lp ticker init status by implementing separate functions.
Add mbed_critical include file to disable compiler warning messages.
Tested all supported toolchains with MAX32625MBED.
[X] Fix  
[ ] Refactor  
[ ] Feature  
=> Rework us_ticker and rtc_api/lp_ticker | Fix compiler warning for spi_api

targets/TARGET_NXP/TARGET_LPC408X/sleep.c
Since revision 5499db1e8 (mbed-os-5.6.0) a hardfault occurs after a **power-cycle**. It doesn't occur after a reset when the application has been downloaded using drag-and-drop or via debugger. This is probably the reason why this problem isn't detected when testing new mbed releases.
The hardfault occured in hal_sleep(). Adding a __NOP after __WFI solves the problem although I don't fully understand why. 
- Revision ca661f9d2 is the last revision where the problem doesn't occur.  
- The problem doesn't occur when compiling with GCC instead of ARM compiler
- This issue describes a similar, but not identical problem and led me to test adding a __NOP: [https://github.com/ARMmbed/mbed-os/issues/5065](https://github.com/ARMmbed/mbed-os/issues/5065)
[ X] Fix  
[ ] Refactor  
[ …
=> LPC4088: Fix hardfault occuring after power-cycle

targets/TARGET_NXP/mbed_rtx.h, targets/targets.json
Fix support for building LPC11C24.
Based on: https://os.mbed.com/blog/entry/Reducing-memory-usage-by-tuning-RTOS-con/
```
rtos/*
features/FEATURE_CLIENT/*
features/FEATURE_COMMON_PAL/*
features/FEATURE_UVISOR/*
features/frameworks/*
features/cellular/*
features/lorawan/*
features/net/*
features/filesystem/*
features/netsocket/*
features/storage/*
```
[X] Fix  
[ ] Refactor  
[ ] Feature  
=> Add mbed-os 5 build support for LPC11C24

targets/TARGET_NUVOTON/TARGET_M451/spi_api.c, targets/TARGET_NUVOTON/TARGET_M480/spi_api.c, targets/TARGET_NUVOTON/TARGET_NANO100/spi_api.c, targets/TARGET_NUVOTON/TARGET_NUC472/spi_api.c
This PR includes fixes with SPI for Nuvoton targets.
- NUMAKER_PFM_NUC472
- NUMAKER_PFM_M453
- NUMAKER_PFM_M487
- NUMAKER_PFM_NANO130
1. Introduce SPI_ENABLE_SYNC/SPI_DISABLE_SYNC to simplify SPI enable/disable control.
1. Use vector rather than SPI enable bit to judge if asynchronous transfer is on-going (`spi_active`).
1. Fix SPI DMA transfer.
1. Refine SPI code.
[x] Fix  
[ ] Refactor  
[ ] Feature  
=> Nuvoton: Fix issues with SPI

targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KL27Z/device/MKL27Z644_features.h, targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KL27Z/drivers/fsl_flash.c, targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KL27Z/drivers/fsl_flash.h, targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KL43Z/device/MKL43Z4_features.h, targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KL43Z/drivers/fsl_flash.c, targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KL43Z/drivers/fsl_flash.h, targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KL82Z/device/MKL82Z7_features.h, targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KL82Z/drivers/fsl_flash.c, targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KL82Z/drivers/fsl_flash.h, targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KW24D/device/MKW24D5_features.h, targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KW24D/drivers/fsl_flash.c, targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KW24D/drivers/fsl_flash.h, targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KW41Z/drivers/fsl_flash.c, targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KW41Z/drivers/fsl_flash.h, targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K22F/TARGET_MCU_K22F512/device/MK22F51212_features.h, targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K22F/drivers/fsl_flash.c, targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K22F/drivers/fsl_flash.h, targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/api/sleep.c, targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC/sleep.c, targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC546XX/TARGET_FF_LPC546XX/device.h, targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC546XX/TARGET_LPCXpresso/device.h
Fixes the Deep sleep implementation for the MCUXpresso SoC's. This is based on testing using the latest sleep manager that invokes deepsleep mode in the idle loop
=> Fix deep sleep implementation

platform/DirHandle.h, platform/FileHandle.h
In this refactoring we fix only the inline documentation of function which already has the MBED_DEPRECATED macro but the @deprecated  is not updated.
[x] Refactor
=> Adding missing @deprecated to function inline documentation

features/cellular/framework/API/CellularNetwork.h, features/cellular/framework/AT/AT_CellularNetwork.cpp, features/cellular/framework/AT/AT_CellularNetwork.h
Added detach from cellular network.
@AriParkkila  please review.
Internal ref to defect: IOTCELL-758
[ ] Fix  
[ ] Refactor  
[x] Feature  
=> Cellular: add detach from the network

tools/get_config.py
I made get_config a little nicer to read, and the output a little nicer
to read.
before
```
Macros
------
Defined with "macros": [u'UNITY_INCLUDE_CONFIG_H']
Generated from configuration parameters: [u'MBED_CONF_LORA_DEVICE_ADDRESS=0x00000000', u'MBED_CONF_CELLULAR_USE_APN_LOOKUP=1', u'MBED_CONF_LORA_DEVICE_EUI={0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}', u'MBED_CONF_LWIP_IPV4_ENABLED=1', u'MBED_CONF_LWIP_DEFAULT_THREAD_STACKSIZE=512', u'MBED_CONF_LWIP_IP_VER_PREF=4', u'MBED_CONF_EVENTS_PRESENT=1', u'NSAPI_PPP_IPV4_AVAILABLE=1', u'MBED_CONF_PLATFORM_FORCE_NON_COPYABLE_ERROR=0', u'MBED_CONF_DRIVERS_UART_SERIAL_RXBUF_SIZE=256', u'NVSTORE_MAX_KEYS=16', u'MBED_CONF_LWIP_ADDR_TIMEOUT=5', u'CFSTORE_STORAGE_DISABLE=0', u'MBED_LFS_BLOCK_SIZE=512', …
```
=> Cleanup get_config (mbed compile --config)

features/lorawan/LoRaWANBase.h, features/lorawan/LoRaWANInterface.h, features/lorawan/lorawan_types.h, features/lorawan/system/lorawan_data_structures.h
Any data structure used in LoRaWANBase class should be available
in a separate header in order to make the code easy to port and
easy to read as the developer doesn't need to know about all the
internal data structures being used in Mbed LoRaWAN stack.
[ ] Fix  
[X] Refactor  
[ ] Feature  
=> [IOTCELL-741] Separating public data structures

targets/TARGET_Maxim/TARGET_MAX32630/spi_api.c
Improve SPI block write by replacing byte write loop with hardware assisted block transaction.
Tested all supported toolchains with MAX32630FTHR.
[X] Fix  
[ ] Refactor  
[ ] Feature  
=> Improve SPI block write

tools/targets/REALTEK_RTL8195AM.py
The online compiler can be very picky about what is and is not allowed in a post-build scirpt. For a while now, the Realtek post-build script has been preventing anyone from successfully compiling for the RTL8195AM in the online compiler. This refactor changes the code that was failing to be much simpler, and it works in the website. I have tested this on a staging site. 
For reference, the traceback:
```
File "/usr/src/mbed-sdk/tools/toolchains/__init__.py", line 1152, in link_program
self.binary(r, elf, bin)
File "/usr/src/mbed-sdk/tools/hooks.py", line 54, in wrapper
post_res = tooldesc["post"](t_self, *args, **kwargs)
File "/usr/src/mbed-sdk/tools/targets/__init__.py", line 538, in binary_hook
rtl8195a_elf2bin(t_self, elf, binf)
File …
```
=> Use pyelftools for Realtek post-build script

features/FEATURE_COMMON_PAL/nanostack-hal-mbed-cmsis-rtos/arm_hal_timer.cpp, features/FEATURE_COMMON_PAL/nanostack-hal-mbed-cmsis-rtos/ns_event_loop.c
nanostack-hal: timer: conditionalize the use of high pri event thread
nanostack-hal.critical-section-usable-from-interrupt -tunable was
previously added to optionally make critical section code interrupt safe.
The IRQ safe critical section is a prequisite for interrupt safe timer
callbacks.
The same flag can be used to enable calling of the timer callbacks
directly from the timer interrupt context, without bouncing them via
event thread. This removes the code and RAM consumed by EventQueue
and the thread serving the high priority events.
If the system does not have any dependencies on mbed_shared_queues,
by setting this flag the static RAM usage is now further reduced
by ~1600 bytes and code size by 4KB.
Note: the default behavior is not changed, one needs to override the …
=> Nanostack hal timer shortcut

tools/export/iar/iar_definitions.json
Add IAR export for STM32L496AG. Required for the DISCO_L496AG platform.
[X] Fix  
[ ] Refactor  
[ ] Feature  
=> Add IAR export for STM32L496AG

targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC/i2c_api.c, targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC54114/drivers/fsl_i2c.c, targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC546XX/drivers/fsl_i2c.c
These failures were seen when running the ci-shield tests. All I2C tests pass after these patches.
[X] Fix  
[ ] Refactor  
[ ] Feature  
=> Fix MCUXpresso LPC I2C driver 

targets/TARGET_Analog_Devices/TARGET_ADUCM302X/TARGET_ADUCM3029/TARGET_EV_COG_AD3029LZ/PinNames.h, targets/TARGET_Analog_Devices/TARGET_ADUCM4X50/TARGET_ADUCM4050/TARGET_EV_COG_AD4050LZ/PinNames.h
Apart from Reset  and Boot buttons, there are 2 more general purpose buttons:
- BUTTON1
- BUTTON2
=> ADI: Add BUTTON pin names for EV_COG_AD4050LZ and EV_COG_AD3029LZ

tools/config/__init__.py, tools/test/config/invalid_key/test_data.json, tools/test/config/invalid_key_lib/test_data.json, tools/test_api.py
Modifies tools to complete Python 3 porting.
Tested using the following command within two Python virtual environments (Python 2.7.14 and 3.6.4): `reset && find . -name *pyc -delete && clear && PYTHONPATH=. coverage run -a -m pytest tools/test`
[ ] Fix  
[X] Refactor  
[ ] Feature  
=> Updates tools to be runnable in Python 3

features/FEATURE_LWIP/lwip-interface/lwip-sys/arch/lwip_sys_arch.c
lwIP was using us_ticker unnecessarily, complicating the code and
potentially causing grief with power saving, and possible glitches
on timer wrap. Switch it to use the RTOS tick count.
[ ] Fix  
[X] Refactor  
[ ] Feature  
=> Stop lwIP using us_ticker

targets/TARGET_Realtek/TARGET_AMEBA/TARGET_RTL8195A/i2c_api.c, targets/TARGET_Realtek/TARGET_AMEBA/TARGET_RTL8195A/log_uart_api.c, targets/TARGET_Realtek/TARGET_AMEBA/TARGET_RTL8195A/pwmout_api.c, targets/TARGET_Realtek/TARGET_AMEBA/TARGET_RTL8195A/spi_api.c, targets/TARGET_Realtek/TARGET_AMEBA/rtw_emac.cpp, targets/TARGET_Realtek/TARGET_AMEBA/sdk/common/api/wifi/wifi_conf.c, targets/TARGET_Realtek/TARGET_AMEBA/sdk/common/api/wifi/wifi_promisc.c, targets/TARGET_Realtek/TARGET_AMEBA/sdk/common/api/wifi/wifi_util.c, targets/TARGET_Realtek/TARGET_AMEBA/sdk/common/drivers/wlan/realtek/src/osdep/lwip_intf.c, targets/TARGET_Realtek/TARGET_AMEBA/sdk/common/network/dhcp/dhcps.c, targets/TARGET_Realtek/TARGET_AMEBA/sdk/os/os_dep/osdep_service.c, targets/TARGET_Realtek/TARGET_AMEBA/sdk/os/os_dep/tcm_heap.c, targets/TARGET_Realtek/TARGET_AMEBA/sdk/soc/realtek/8195a/fwlib/hal_ssi.h
Fix trivial compiler warnings, no logic changed.
[X] Fix
[ ] Refactor
[ ] New target
[ ] Feature
=> rtl8195am - Fix more compiler warnings

targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC/objects.h, targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC/trng_api.c, targets/targets.json
LPC546XX: Add TRNG support
| LPC546XX-ARM | LPC546XX      | mbed-os-tests-mbedtls-multi                                                          |
Crypto: sha256_multi                                                                              | 1      | 0      | OK
| 0.82               |
| LPC546XX-ARM | LPC546XX      | mbed-os-tests-mbedtls-multi                                                          |
Crypto: sha256_split                                                                              | 1      | 0      | OK
| 0.28               |
| LPC546XX-ARM | LPC546XX      | mbed-os-tests-mbedtls-selftest                                                       |
mbedtls_entropy_self_test                                                                         | 1      | 0      | OK
| …
=> LPC546XX: Add TRNG support

TESTS/usb_device/basic/main.cpp
USB device reset test fix.
reset_count flag should be cleared before test start
[X] Fix  
[ ] Refactor  
[ ] Feature  
=> USB reset test fix

features/cellular/easy_cellular/CellularConnectionFSM.cpp, features/cellular/easy_cellular/CellularConnectionFSM.h, features/cellular/easy_cellular/EasyCellularConnection.cpp, features/cellular/easy_cellular/EasyCellularConnection.h, features/cellular/framework/API/CellularNetwork.h, features/cellular/framework/AT/AT_CellularNetwork.cpp, features/cellular/framework/AT/AT_CellularNetwork.h
Added possibility to specify plmn to CellularConnectionFSM which to use when registering to a cellular network.
Internal ref to defect: IOTCELL-745
@AriParkkila please review
[ ] Fix  
[ ] Refactor  
[X] Feature  
=> Cellular: add plmn for CellularConnectionFSM

features/FEATURE_COMMON_PAL/nanostack-hal-mbed-cmsis-rtos/arm_hal_timer.cpp
Avoid static data/code overhead when Nanostack HAL isn't in use.
Preparation for removal of FEATURE_COMMON_PAL.
[ ] Fix  
[X] Refactor  
[ ] Feature  
=> Use SingletonPtr in Nanostack HAL

features/lorawan/LoRaWANStack.cpp, features/lorawan/LoRaWANStack.h, features/lorawan/lorawan_types.h, features/lorawan/mbed_lib.json
Currently lora stack will automatically send an empty uplink message to lora gateway in case of:
- Node received message with pending bit set.
- Node received MAC command which requires instant response (sticky MAC command)
- Node received confirmed message in class C mode
This commit makes this configurable via config item
"automatic-uplink-message": {
"help": "In case of pending bit, class c confirmed message or sticky MAC command, stack will automatically send empty uplink message",
"value": true
}
Default value is true. If sending an empty message fails, stack will send event AUTOMATIC_UPLINK_ERROR application.
If automatic uplink sending is disabled, stack will send application UPLINK_REQUIRED -event to indicate
application should issue a new uplink to gateway as soon as possible.
[ …
=> Lora: Make automatic uplink message configurable

features/filesystem/littlefs/littlefs/lfs.c, features/filesystem/littlefs/littlefs/lfs.h, features/filesystem/littlefs/littlefs/tests/test_alloc.sh
Two somewhat related issues were found over here: https://github.com/geky/littlefs/issues/46
After quite a bit of discussion the result is some fixes a bit of simplification of the lookahead management. Most significantly, removing the dependency on integer overflow. This should hopefully remove a lot of the issues we've been seeing around allocation.
1. Fix issue with lookahead trusting old lookahead blocks 
One of the big simplifications in littlefs's implementation is the complete lack of tracking free blocks, allowing operations to simply drop blocks that are no longer in use.
However, this means the lookahead buffer can easily contain outdated blocks that were previously deleted. This is usually fine, as littlefs will rescan the storage if it can't find a free block in the lookahead …
=> littlefs: Fix some issues with lookahead trust

tools/config/__init__.py
The documentation currently claims that libraries are allowed to
override target configuration. This fixes a bug that would prevent a
library configuration from overriding a target configuration.
Application configuration is unaffected.
[X] Fix  
[ ] Refactor  
[ ] Feature  
=> Allow library configs to override target configs

usb/device/USBDevice/USBDevice.cpp, usb/device/USBDevice/USBDevice.h
Add the helper function endpoint_remove_all which removes all added endpoints. This is useful for class drivers switching between different USB configurations.
[ ] Fix  
[ ] Refactor  
[X] Feature  
=> Add endpoint_remove_all helper function

targets/TARGET_Maxim/TARGET_MAX32620C/i2c_api.c
Remove stop after each read to allow sending repeated start.
Tested all supported toolchains with MAX32620FTHR.
[x] Fix  
[ ] Refactor  
[ ] Feature  
=> Remove automatic I2C stop after each read

targets/TARGET_TOSHIBA/TARGET_TMPM46B/flash_api.c, tools/export/iar/iar_definitions.json
Add IAR export and nvstore page size fix for TMPM46B
[X] Fix  
[ ] Refactor  
[ ] Feature  
=> Add IAR export and nvstore page size fix for TMPM46B

features/cellular/UNITTESTS/at/at_cellularnetwork/at_cellularnetworktest.cpp, features/cellular/UNITTESTS/at/at_cellularnetwork/test_at_cellularnetwork.cpp, features/cellular/UNITTESTS/at/at_cellularnetwork/test_at_cellularnetwork.h, features/cellular/UNITTESTS/stubs/AT_CellularNetwork_stub.cpp, features/cellular/framework/AT/AT_CellularNetwork.cpp, features/cellular/framework/AT/AT_CellularNetwork.h
Fixed cellular unit tests. 
Moved one method from protected to public as it was accidentally set as protected in AT_CellularNetwork. Now that method also can be unit tested.
@AnttiKauppila please review
Internal ref to defect: IOTCELL-799
[X] Fix  
[ ] Refactor  
[ ] Feature  
=> Fixed cellular unittests

.github/pull_request_template.md
This basically make the default PR template looks like this PR.
[ ] Fix  
[x] Refactor  
[ ] Feature  
=> make PR type box list "fancier" without making it a github tasklist

drivers/UARTSerial.cpp
Appears when complied with -O3 optimization level
```
Compile: UARTSerial.cpp
../drivers/UARTSerial.cpp: In member function 'void mbed::UARTSerial::tx_irq()':
../drivers/UARTSerial.cpp:314:31: warning: 'data' may be used uninitialized in this function [-Wmaybe-uninitialized]
SerialBase::_base_putc(data);
```
[X] Fix  
[ ] Refactor  
[ ] Feature  
=> Uninitialized variable warning in UARTSerial at -O3

requirements.txt
SHA 14255ca introduced the lines that are reported to be breaking.
future module in requirements fixes it
Reference: https://pypi.python.org/pypi/future
Fixes #6489
[X] Fix  
[ ] Refactor  
[ ] Feature  
=> requirements: add future

features/FEATURE_LWIP/lwip-interface/LWIPInterface.cpp, features/FEATURE_LWIP/lwip-interface/LWIPStack.h, features/FEATURE_LWIP/lwip-interface/ppp_lwip.cpp, features/nanostack/FEATURE_NANOSTACK/mbed-mesh-api/mbed-mesh-api/MeshInterfaceNanostack.h, features/nanostack/FEATURE_NANOSTACK/mbed-mesh-api/mbed-mesh-api/NanostackEthernetInterface.h, features/nanostack/FEATURE_NANOSTACK/mbed-mesh-api/source/LoWPANNDInterface.cpp, features/nanostack/FEATURE_NANOSTACK/mbed-mesh-api/source/MeshInterfaceNanostack.cpp, features/nanostack/FEATURE_NANOSTACK/mbed-mesh-api/source/NanostackEthernetInterface.cpp, features/nanostack/FEATURE_NANOSTACK/mbed-mesh-api/source/ThreadInterface.cpp, features/netsocket/EMACInterface.cpp, features/netsocket/EMACInterface.h, features/netsocket/OnboardNetworkStack.h
Nonblocking connect implementations of set_blocking() and attach()
were working on the assumption that associated OnboardNetworkStack::Interface
already been created.
This is not the case, and it is desirable to defer
the creation until first NetworkInterface::connect(), as creation
invokes EMAC power-up, and may need to take time and return errors.
Change the implementations to remember callback and blocking settings,
and pass them to the ONS::Interface as it's created and brought up.
[X] Fix  
[ ] Refactor  
[ ] Feature  
=> feature-emac: Rework nonblocking connect

targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KL27Z/device/MKL27Z644_features.h
It should unblock #6697. Adding one more addition on top of #6468
```
Library: mbed.ar
Copy: mbed_board.o
Copy: mbed_sdk_boot.o
Copy: mbed_retarget.o
Completed in: (18.42)s
Build successes:
* ARM::KL27Z
```
cc @mmahadevan108 
[X] Fix  
[ ] Refactor  
[ ] Feature  
=> KL27Z: Flash protection macro addition

hal/mbed_lp_ticker_api.c, hal/mbed_lp_ticker_wrapper.cpp, targets/TARGET_STM/lp_ticker.c, targets/targets.json
STM32 LPTICKER update for targets supporting ST LPTIM
Targets: STM32L0, STM32L4, STM32F7 and few STM32F4
@bulislaw @LMESTM @c1728p9 @screamerbg 
[ ] Fix  
[x] Refactor  
[ ] Feature  
=> STM32 LPTICKER update for targets supporting LPTIMER

tools/build_api.py, tools/test/config/app_override_libs/targets.json, tools/test/config/compound_inheritance/targets.json, tools/test/config/double_define/targets.json, tools/test/config/feature_compesition/targets.json, tools/test/config/feature_recursive_add/targets.json, tools/test/config/feature_recursive_complex/targets.json, tools/test/config/feature_remove/targets.json, tools/test/config/feature_uvisor/targets.json, tools/test/config/macro_inheritance/targets.json, tools/test/config/override_labels_libs/targets.json, tools/test/config/override_labels_libs_more/targets.json, tools/test/config/override_labels_targets/targets.json, tools/test/config/override_precidence/targets.json, tools/test/config/override_undefined/targets.json, tools/test/config/override_undefined_libs/targets.json, tools/test/config/override_with_labels/targets.json, tools/test/config/simple_features/targets.json, tools/test/config/simple_iheritance/targets.json
Before this change it is possible to compile with a compiler that a
device port does not support. Afterwards it will not be.
It is possible to override the supported toolchains in the application
configuration and compile with the unsupported toolchain after this change.
Resolves #5109
[✓] Fix  
[ ] Refactor  
[ ] Feature  
=> Prevent compiling with unsupported compilers

features/lorawan/LoRaWANInterface.cpp, features/lorawan/LoRaWANInterface.h, features/lorawan/LoRaWANStack.cpp, features/lorawan/LoRaWANStack.h, features/lorawan/lorastack/mac/LoRaMac.cpp, features/lorawan/lorastack/mac/LoRaMac.h, features/lorawan/lorastack/mac/LoRaMacCrypto.cpp, features/lorawan/lorastack/mac/LoRaMacCrypto.h, features/lorawan/system/lorawan_data_structures.h
LoRaMacCrypto was the last source that was not yet converted to a C++ class. Since that is now a C++ class, also singleton pattern can be removed from LoRa stack. This will simplify the code and enable easier tracking of memory consumption and further refactorings.
[ ] Fix  
[X] Refactor  
[ ] Feature  
=> Lora: Remove singleton pattern

TESTS/host_tests/device_echo.py, TESTS/mbed_drivers/echo/main.cpp
Previously, the echo test followed a flow like the following:
```
-STEP-	-HOST PC-                  -DEVICE-
0	send _sync
1				   echo back _sync
2				   send echo_count
3	echo back echo_count
4	send first echo packet
5				   echo back echo packet
(repeat steps 4 + 5)
```
However, as noted by issue #6659, this test would somtimes fail between
steps 4 and 5. To ensure each KV pair makes it to the correct destination,
we usually write the KV back. Step 4 does not wait for this to happen
and starts sending echo packets. So the device is acting as the "echo
server".
This change makes the host PC the "echo server". The idea being that the
device will be slower and the host pc should always be able to keep up
with it, not the other way around.
[x] Fix
[ ] Refactor
[ ] New target
[ ] Feature
[ ] …
=> Modifying echo test to be driven more from the device.

features/cellular/easy_cellular/CellularConnectionFSM.cpp
Cellular: fixed possible crash bug in cellular state machine.
After stop() call there might have been a call to null pointer.
@AriParkkila please review
[X] Fix  
[ ] Refactor  
[ ] Feature  
=> Cellular: fixed null pointer bug in cellular fsm

targets/TARGET_STM/rtc_api.c, targets/TARGET_STM/rtc_api_hal.h
There is no functional update.
This is mainly to prevent potential issues with CI and all test environnment when the ticker branch will be merged.
Thx
[ ] Fix
[X] Refactor
[ ] New target
[ ] Feature
=> STM32 RTC Init minor update

targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC/gpio_irq_api.c
GPIO IRQ is available on pins for Ports 0 & 1. Add a check to return error for other ports.
[X] Fix
[ ] Refactor
[ ] New target
[ ] Feature
=> LPC546XX: Add check for GPIO IRQ

targets/TARGET_STM/lp_ticker.c, targets/TARGET_STM/rtc_api.c, targets/TARGET_STM/rtc_api_hal.h, targets/TARGET_STM/sleep.c, targets/targets.json
STM32 LPTICKER update for targets supporting RTC
This completes #6474
And should be the last PR from ST in the ticker feature branch
Targets: 
- STM32L1, STM32F0, STM32F3, most of STM32F4
- STM32L0, STM32L4, STM32F7 and few STM32F4 if user decides to disable lpticker_lptim config
@bulislaw @c1728p9 @screamerbg
[ ] Fix
[X] Refactor
[ ] New target
[ ] Feature
=> STM32 LPTICKER update for targets supporting RTC

features/FEATURE_COMMON_PAL/nanostack-hal-mbed-cmsis-rtos/mbed_lib.json, features/nanostack/FEATURE_NANOSTACK/mbed-mesh-api/mbed_lib.json, features/nanostack/FEATURE_NANOSTACK/sal-stack-nanostack/mbed_lib.json
Most of the help fields were correct. Just add field specifying
acceptable ranges.
[X] Fix
[ ] Refactor
[ ] New target
[ ] Feature
=> Clarify mesh configuration values.

targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC/pinmap.c
We cannot rely on the default value as a pin could be use for Analog purposes in which this bit is cleared. This was discovered when running AnalogIn ci-shield tests that uses the pin for Analog Input and then switches the pin to GPIO output.
[X] Fix
[ ] Refactor
[ ] New target
[ ] Feature
=> LPC54XXX: Set the pin function to Digital mode

TESTS/mbed_drivers/lp_ticker/main.cpp, TESTS/mbed_drivers/timer/main.cpp, TESTS/mbed_drivers/timerevent/main.cpp, TESTS/mbed_hal/common_tickers/main.cpp, TESTS/mbed_hal/lp_ticker/main.cpp, targets/TARGET_NORDIC/TARGET_NRF5/common_rtc.c, targets/TARGET_NORDIC/TARGET_NRF5/common_rtc.h, targets/TARGET_NORDIC/TARGET_NRF5/lp_ticker.c, targets/TARGET_NORDIC/TARGET_NRF5/us_ticker.c, targets/TARGET_NORDIC/TARGET_NRF5/us_ticker.h, targets/targets.json
1. us ticker driver for NRF_51_DK board:
According to new ticker standards the following requirements for us ticker are not met on NRF_5xxx boards:
- has a frequency between 250KHz and 8MHz (currently is driven by 32kHz clock)
- ticker increments by 1 each tick (currently is scaled to 1 MHz by incrementing counter by ~31)
Since BLE softdevice uses TIMER0 the proposition is to use high speed TIMER1 for us ticker configured as follows:
- TIMER counter width: 16 bits (max)
- TIMER frequency: 1MHz
This solution also uses Timer's capture/compare register 0 to specify interrupt time and Timer's capture/compare register 1 to read current timer value.
<del>
2. sleep/deep-sleep driver for NRF_5xxx boards:
According to new sleep mode standards the following requirement is not met on NRF_5xxx …
=> NRF_51_DK - adapt lp/us ticker drivers to the new standards

features/lorawan/lorastack/phy/LoRaPHY.cpp, features/lorawan/lorastack/phy/LoRaPHY.h, features/lorawan/lorastack/phy/LoRaPHYKR920.cpp, features/lorawan/lorastack/phy/LoRaPHYKR920.h
band_t structure in phy parameters was not being filled in properly
and we were spilling over the array boundary for bands.
In addition to that two utility functions are added to perform safety
checking taking in the frequency and filling out band information plus
boundary value checks.
[X ] Fix
[ ] Refactor
[ ] New target
[ ] Feature
=> LoRaWAN: Memory corruption due to band mishandling

targets/TARGET_NORDIC/TARGET_NRF5x/serial_api.c
I'm migrating an existing project to the recently-merged nrf52 / sdk 14.2 codebase in master.
I use a uart serial with match character for automatic depacketizing.
On current master I now get an assert fail as it's testing that  `char_match == SERIAL_RESERVED_CHAR_MATCH` where I believe it should be the opposite; `char_match` should not be allowed to be  `SERIAL_RESERVED_CHAR_MATCH`
This is with GCC and the debug.json build profile.
[X] Fix
[ ] Refactor
[ ] New target
[ ] Feature
=> nrf5x: Fix assert test on SERIAL_RESERVED_CHAR_MATCH

features/lorawan/lorastack/mac/LoRaMac.cpp, features/lorawan/lorastack/mac/LoRaMacCommand.cpp, features/lorawan/lorastack/mac/LoRaMacCommand.h
In order to have smaller and better testable methods, instead of having a big
switch-case -style add_mac_command(), each MAC command is now separated to an
own method.
This has been tested with our internal Lora tests.
[ ] Fix
[X] Refactor
[ ] New target
[ ] Feature
=> Lora: Split add_mac_command() into separate methods

.astyleignore, .astylerc, .travis.yml
This is a new feature - be on master to check the code and be part of Mbed OS 5.9 when most of our codebase actually is conforming to the style. 
Checking only files that has changed within the pull request. More PR will come later to start updating the code base
[ ] Fix  
[ ] Refactor  
[X] Feature  
=> AStyle addition to travis

features/filesystem/bd/MBRBlockDevice.cpp
Add asserts for overlapping MBR parititions. This takes advantage of "is_valid_erase" of the underlying block device, but then has to iterate through all partitions to check if any overlap.
related [IOTMORF-2320](https://jira.arm.com/browse/IOTMORF-2320)
cc @deepikabhavnani, @JaniSuonpera, @jenia81, @mottigondabi 
[ ] Fix  
[ ] Refactor  
[x] Feature  
=> mbr: Added assertions for overlapping partitions

features/cellular/framework/AT/ATHandler.cpp
Fix AT Handler compile warning in read routine + returned length. Unit tests are also passing after these changes.
[X] Fix
[ ] Refactor
[ ] New target
[ ] Feature
=> Cellular: Fix AT Handler compile warning

TESTS/mbed_hal/sai/main.cpp, TESTS/mbed_hal/sai/sai_api_tests.h, targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_K66F/TARGET_FRDM/PinNames.h, targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K64F/TARGET_FRDM/PinNames.h, targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/api/sai_api.c
Add SAI HAL API test.
This test has been created based on the following requirements:
https://github.com/ithinuel/mbed-os/blob/fdf7ba4143957fb2c3b6454a34eb3f3518412154/hal/sai_api.h#L30-L77
IN DEVELOPMENT
PR https://github.com/ARMmbed/mbed-os/pull/6136 - provides SAI HAL API definition and example drivers for K66F and NUCLEO-F411RE platforms. Needs to be merged before this one.
Missing test cases:
- `sai_init()` returns `SAI_RESULT_CONFIG_MISMATCH` if the device is not able to support this configuration at this point time because of other 'live' constraints (such as a shared  format/clock configuration with a sibling).
- `sai_xfer()` returns false if the fifo is full and `*psample` could not be pushed.
- extend requirements and tests.
@ithinuel please review.
=> Add SAI HAL API tests.

features/filesystem/littlefs/littlefs/lfs.c, features/filesystem/littlefs/littlefs/tests/test_paths.sh
Paths such as the following were causing issues:
/tea/hottea/.
/tea/hottea/..
Unfortunately the existing structure for path lookup didn't make it very easy to introduce proper handling in this case without duplicating the entire skip logic for paths. So the lfs_dir_find function had to be restructured a bit.
One odd side-effect of this is that now lfs_dir_find includes the initial fetch operation. This kinda breaks the fetch -> op pattern of the dir functions, but does come with a nice code size reduction.
related https://github.com/geky/littlefs/issues/51
cc @deepikabhavnani, @kegilbert 
[x] Fix
[ ] Refactor
[ ] New target
[ ] Feature
=> littlefs: Fix issue with trailing dots in file paths

features/lorawan/lorastack/phy/LoRaPHY.cpp
In LoRa TX power value 0 means the maximum allowed TX power and values >0
are limiting the allowed TX power to lower.
tx_config was incorrectly checking the power level and causing the maximum
TX power to be always used. Lora gateway can request node to use lower TX
power with LinkAdrReq MAC command.
This fix proposal has been tested with our internal LoRa tests.
[X] Fix
[ ] Refactor
[ ] New target
[ ] Feature
=> Lora: Fix max tx power check

targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F411xE/TARGET_NUCLEO_F411RE/system_clock.c, targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F411xE/device/TOOLCHAIN_ARM_STD/stm32f411re.sct, targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F411xE/device/TOOLCHAIN_GCC_ARM/STM32F411XE.ld, targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F411xE/device/TOOLCHAIN_IAR/stm32f411xe.icf, targets/targets.json
Add bootloader support for NUCLEO_F411RE board.
Tested with mbed-bootloader + blinky, with all three compilers.
Ref: https://github.com/ARMmbed/mbed-os/pull/5228 - bootloader support for NUCLEO_F446RE
[ ] Fix
[ ] Refactor
[X] New target
[ ] Feature
=> Add bootloader support for NUCLEO_F411RE target

targets/TARGET_ARM_SSG/TARGET_CM3DS_MPS2/device/TOOLCHAIN_ARM_STD/startup_MPS2.S, tools/export/uvision/uvision.tmpl, tools/toolchains/arm.py
The arm assembler would include many, many include paths on the command
line corresponding to anywhere it's possible to locate a header file.
This caused the following problem in uvision:
```
assembling startup_nrf52832.S...
startup_nrf52832.S: error: A3907U: Via file
'.\build\startup_nrf52832._ia' command too long for buffer.
```
We work around this issue by dropping the include paths from the
assembler in both `mbed compile` and `mbed export`. This has the
advantage that it's consistent with IAR.
[X] Fix
[ ] Refactor
[ ] New target
[ ] Feature
=> Drop include paths for ARM assembler

TESTS/mbed_drivers/sai/main.cpp
Since currently we have only "placeholder" implementation for `SAI/SAITransmitter/SAIReceiverand` classes and real "real" C++ implementation is under development current test provides only loop-back communication test using one format.
Test needs to be updated when real implementation is ready.
IN DEVELOPMENT
Provide real test when the real implementation is ready.
=> Add SAI/SAITransmitter/SAIReceiver class tests.
