- libraries/mbed/targets/hal/TARGET_RENESAS/TARGET_RZ_A1H/spi_api.c
Hi,
We midified frequency setting processing of SPI.
In case of off-line compiler, there is no problem about the frequency setting processing.
But in case of online compiler, the frequency setting processing will be error.
So, modify frequency setting processing of SPI to pass in online compiler.
Regards,
Hamanaka
> [RZ_A1H]Modify frequency setting processing of SPI

- workspace_tools/toolchains/gcc.py
This support is supported by:
- gcc-arm-none-eabi-4_7-2013q1
- gcc-arm-none-eabi-4_9-2014q4
> workspace_tools/toolchains/gcc.py: Use 'cortex-m0plus' support for ARM Cortex M0+

- libraries/rtos/rtx/TARGET_CORTEX_M/rt_CMSIS.c
This is a fix for issue #285.  This fix is similar to that proposed by
@oresths in the original issue.
There is code in rt_init_stack() which compares the task_id against the
value of 1 before writing MAGIC_WORD to the bottom of the stack.  This
is supposed to stop the write from occurring for the main thread but
svcThreadCreate() doesn't initialize the P_TCB's task_id field until
after rt_init_stack() is executed.  If any dynamic memory allocation
has occurred before the main thread is started (from the standard C
startup code) then this write could overwrite data in that allocation.
This change:
* moves the task_id initialization in svcThreadCreate() to happen
before the call to rt_init_context() is made.
* cleans up some comments in svcThreadCreate() which appear to
reference older …
> RTX: Main thread should not write MAGIC_WORD to stack

- libraries/rtos/rtos/Thread.cpp
- libraries/rtos/rtx/TARGET_CORTEX_M/cmsis_os.h
Stack should be 8 byte aligned on ARM.
Fix the automatic correction of the alignment in rt_init_stack,
and make sure that all stacks are aligned by the compiler.
> Fix stack aligment.

- workspace_tools/export/__init__.py
#Problem 
Some offline exporters are having issues, (Think BLE and the need for a 3rd party flash algorithm with Keil V4), currently there is no good way to help people out
#Solution 
Add a readme.html to every offline exporter that redirects people to a page where we keep a list of the known errata for each platform and compiler. Part of the web address is the platform and compiler so they will automatically jump down the page to where their platform and compiler are.
> Add readme.html to every exported project

- libraries/mbed/targets/cmsis/TARGET_NXP/TARGET_LPC43XX/system_LPC43xx.c
I was getting Hard Faults in even the simplest of samples before I made
these fixes.
* WaitUs() did nothing on optimized builds.  I added the volatile
qualifier to the cyc variable to make sure that the delay loop
doesn't get optimized out.
* I removed the #ifdef which skipped the fpuInit() call when building
with GCC.
> Fixes to get LPC4330 GCC based builds to run

- libraries/mbed/targets/hal/TARGET_NXP/TARGET_LPC11XX_11CXX/TARGET_LPC11XX/PinNames.h
- libraries/mbed/targets/hal/TARGET_NXP/TARGET_LPC82X/TARGET_LPC824/PeripheralNames.h
- libraries/mbed/targets/hal/TARGET_NXP/TARGET_LPC82X/TARGET_LPC824/PinNames.h
- libraries/mbed/targets/hal/TARGET_NXP/TARGET_LPC82X/TARGET_SSCI824/PeripheralNames.h
- libraries/mbed/targets/hal/TARGET_NXP/TARGET_LPC82X/TARGET_SSCI824/PinNames.h
On LPC1114 platforms, if user set P0_0 as DigitalOut and set it to low, LPC1114 will be in reset condition. To avoid this situation, p4, xp4 and dp23 was removed from PinNames.h.
On LPC824 platforms, I2C pin names were crossed.
> [LPC1114] remove reset pin name to protect people. [LPC824] I2C pin names were crossed

- workspace_tools/build_release.py
- workspace_tools/build_travis.py
LPC11U37H_401 target support added to build_travis.py and build_release.py
> LPC11U37H_401 target support added to build_travis.py and build_release.py

- libraries/rtos/rtx/TARGET_CORTEX_M/RTX_CM_lib.h
This fixes issue #856 reported by @neilt6.
I tested on mbedLPC1768 and mbedLPC11U24 using the GCC_ARM toolchain.
> Correct warning when assigning HEAP_START to stack_pointer

- libraries/mbed/targets/hal/TARGET_NXP/TARGET_LPC11UXX/TARGET_LPC11U37H_401/PinNames.h
- libraries/tests/mbed/dir_sd/main.cpp
- libraries/tests/mbed/sd/main.cpp
- libraries/tests/mbed/sd_perf_fatfs/main.cpp
- libraries/tests/mbed/sd_perf_fhandle/main.cpp
- libraries/tests/mbed/sd_perf_stdio/main.cpp
On-Board SD Card support for LPC11U37H_401 board, test cases related to SD Card updated too.
> On-Board SD Card support for LPC11U37H_401 board

- libraries/mbed/common/us_ticker_api.c
- libraries/mbed/hal/us_ticker_api.h
- libraries/mbed/targets/hal/TARGET_NORDIC/TARGET_MCU_NRF51822/us_ticker.c
The underlying us_tickers used for comparison are still 32-bits; keeping a 64-bit timestamp isn't going to be useful.
fixes #838
> switching timestamp_t back to 32-bits.

- libraries/mbed/common/us_ticker_api.c
- libraries/mbed/hal/us_ticker_api.h
- libraries/mbed/targets/hal/TARGET_NORDIC/TARGET_MCU_NRF51822/us_ticker.c
There was a project header file which does not exist in mbed SDK, neither
some defines used from it most probably. This commit reverts those parts.
@rgrover If APP_TIMER_INIT should be initialized differently, send a new PR. I used values which were there before the 839 PR
> HAL - NRF51822 - us ticker fix for the #839

- libraries/mbed/targets/hal/TARGET_NXP/TARGET_LPC81X/i2c_api.c
Quick fix of block read and write. The i2c_start() is still wrong: it
should setup the slave address before initiating a Start condition. Status
read is also wrong in i2c_do_read().
> I2C blockread and blockwrite fixed for LPC812

- libraries/mbed/common/BusIn.cpp
- libraries/mbed/common/BusInOut.cpp
- libraries/mbed/common/BusOut.cpp
MBED_ASSERT was defined in mbed_assert.h.
Signed-off-by: Jun-Ru Chang <jrjang@gmail.com>
> Include missing header file

- libraries/mbed/targets/cmsis/TARGET_NXP/TARGET_LPC81X/TARGET_LPC812/system_LPC8xx.c
- libraries/mbed/targets/cmsis/TARGET_NXP/TARGET_LPC81X/system_LPC8xx.h
- libraries/mbed/targets/hal/TARGET_NXP/TARGET_LPC81X/serial_api.c
The LPC812 was running on the IRC at 12MHz rather than at the rated and expected 30MHz. The PLL settings were fixed and the MainClock and SystemCoreClock calculation was fixed.
The serial_api was fixed to use the correct MainClock value. Enjoy a speed increase of 2.5 !
> Fix and enable the PLL for the LPC812

- libraries/mbed/targets/hal/TARGET_STM/TARGET_NUCLEO_F070RB/gpio_object.h
- libraries/mbed/targets/hal/TARGET_STM/TARGET_NUCLEO_F103RB/gpio_object.h
- libraries/mbed/targets/hal/TARGET_STM/TARGET_NUCLEO_F302R8/gpio_object.h
- libraries/mbed/targets/hal/TARGET_STM/TARGET_NUCLEO_F303RE/gpio_object.h
- libraries/mbed/targets/hal/TARGET_STM/TARGET_NUCLEO_F334R8/gpio_object.h
- libraries/mbed/targets/hal/TARGET_STM/TARGET_NUCLEO_L053R8/gpio_object.h
- libraries/mbed/targets/hal/TARGET_STM/TARGET_NUCLEO_L152RE/gpio_object.h
- libraries/mbed/targets/hal/TARGET_STM/TARGET_STM32F3XX/gpio_object.h
- libraries/mbed/targets/hal/TARGET_STM/TARGET_STM32F4XX/gpio_object.h
Should be available for all mbed targets
> Targets - gpio_is_connected() for STM targets where it was not implemented

- workspace_tools/export/gcc_arm_nucleo_f103rb.tmpl
- workspace_tools/export/gcc_arm_nucleo_f302r8.tmpl
- workspace_tools/export/gcc_arm_nucleo_l152re.tmpl
* Additional maintenance.
Refer to commit  #708 .
> [Export][GCC_ARM][Makefile][tmpl] Fixed parallel build errro and others.

- workspace_tools/export_test.py
Apparently the export() function takes an extra_symbols parameter that wasn't being passed, causing runtime errors. This fixes it.
> Fix export_test.py extra_symbols issue.

- libraries/mbed/common/us_ticker_api.c
- libraries/mbed/hal/us_ticker_api.h
This function will allow us to have a tickless wakeup from deepstop using a low-speed RTC timer.
> Added function to get the timestamp of the next us_ticker event.

- libraries/mbed/api/rtc_time.h
- libraries/mbed/common/rtc_time.c
Initially from Karls question here:
http://developer.mbed.org/questions/6337/setTime-and-time-exported-with-__weak-fo/#answer6545?compage=1#c15936.
Currently the C time functions only work with internal RTC. Sometimes
you either want to use an external one, or your target does not even
have an internal RTC. I added function attach_rtc(...) where the default
functions can be overridden at runtime.
Verified it to work properly with LPC1768/LPC11u24, both with and without DS1307 RTC connected and used as source for time. I don't think the init and isenabled functions are really important to have, but you can just set them as NULL (did so myself when testing).
> [API] Added option to modify RTC source

- libraries/rtos/rtx/TARGET_CORTEX_M/RTX_CM_lib.h
- libraries/rtos/rtx/TARGET_CORTEX_M/RTX_Conf_CM.c
I am not sure if it's the right SP, but the basic blink code works.
What does the SP stand for? Stack pointer?
Also, if you could tell me where to look for the correct address, I would.
I looked in the reference manual and the programming manual that STM provides, with no luck.
Cheers
> Added support for Nucleo F303RE

- libraries/net/eth/EthernetInterface/EthernetInterface.h
- libraries/net/eth/lwip-eth/arch/TARGET_STM/lwipopts_conf.h
- libraries/net/eth/lwip-eth/arch/TARGET_STM/stm32f4_emac.c
- libraries/net/lwip/lwip/core/memp.c
net support for Seeed Arch Max (stm32f407 + dp83848, RMII interface)
> [net] add target Seeed Arch Max (stm32f407)

- libraries/mbed/targets/hal/TARGET_Freescale/TARGET_K20XX/objects.h
- libraries/mbed/targets/hal/TARGET_Freescale/TARGET_K20XX/pwmout_api.c
The old code for the K20 PWM had an issue where calling for example
pwm.period and pwm.write after each other resulted in the pwm.write
function setting the pulsewidth with the value of the old pwm period.
This makes sure it waits until the latest pwm period is written before
it will do so.
It was in legacy PWM mode, which should be the same as what the KLxx for example use, but this was not the same apparantly. The KSDK MCUs solve this issue using: "Did you try turning it off and on again" (which gives glitches on the ouput). This does not give glitches, only downside is that the code waits until the last update happened when doing multiple changes in a row. Alternative would be to store the written value in a variable in the code too, but then I consider this option better.
But really …
> [HAL] K20DXX PWM fix

- workspace_tools/singletest.py
- workspace_tools/test_api.py
Description
========
Now using ```-f``` switch will filter target platforms to test when you use for example auto-detection (```--auto``` option). Use comma to pass more MCU names to ```-f``` filter.
You can't apply regular expression on names, only give full platform name!
For system connected with two boards: ```NUCLEO_L053R8``` and ```KL25Z``` we can check configuration (using switch ```--config```):
We can see both boards are detected and we will test both of them if test suite will be executed without ```-O``` or ```--config``` option.
```
$ singletest.py --auto --config
MBEDLS: Detecting connected mbed-enabled devices...
MBEDLS: Detected NUCLEO_L053R8, port: COM35, mounted: E:
MBEDLS: Detected KL25Z, port: COM89, mounted: F:
MUTs configuration in auto-detected: …
```
> Added to option --auto handler for -f <mcu> filter switch. 

- workspace_tools/export/gcc_arm_hrm1017.tmpl
explora26@i5-GA-H77:/tmp/BLE_iBeacon$ make merge 
srec_cat mbed/TARGET_ARCH_BLE/TARGET_NORDIC/TARGET_MCU_NRF51822/Lib/s110_nrf51822_7_0_0/s110_nrf51822_7.0.0_softdevice.hex -intel BLE_iBeacon.hex -intel -o combined.hex -intel --line-length=44
srec_cat:
mbed/TARGET_ARCH_BLE/TARGET_NORDIC/TARGET_MCU_NRF51822/Lib/s110_nrf51822_7_0_0/s110_nrf51822_7.0.0_softdevice.hex:
open: No such file or directory
make: *** [merge] Error 1
The softdevice path is incorrect
> [HRM1017] Fix the incorrect softdevice path.

- libraries/mbed/targets/hal/TARGET_STM/TARGET_NUCLEO_F103RB/gpio_object.h
This should fix busIn/Out test
> Nucleo F103RB - gpio_is_connected method readdition

- libraries/USBDevice/USBSerial/USBCDC.cpp
It believe it would be better to use the "Data Terminal Ready" signal to determine when the host has connected and can accept characters.
> Using "Data Terminal Ready" signal to determine when the host is connected.

- workspace_tools/host_tests/host_test.py
- workspace_tools/host_tests/host_tests_plugins/host_test_plugins.py
- workspace_tools/host_tests/host_tests_plugins/module_copy_mbed.py
- workspace_tools/host_tests/host_tests_plugins/module_copy_shell.py
* Added timeouts (delays) on serial port and mounting point accesses in host_test and copy plugins to prevent serial/disk I/O errors when device remounts USB iface of interface chip.
* Also some Freedom boards (KL25Z, KL46Z) can cause re-mounting issues when (experimental) parallel test execution is turn on option ```--parallel```.
This implementation hopefully solves both problems.
There was a problem with U-BLOX interface chip which is re-mounting and causing serial / mount point I/O when test suite is executed.
See here: http://developer.mbed.org/questions/6743/singletestpy-need-wait-between-end-of-co
Fix is adding pooling for serial port and mount point so we are only flashing and reading from serial when both are available (when accessing).
```
$ singletest.py -i test_spec.json -M …
```
> Added timeouts (delays) on serial port and mounting point

- libraries/mbed/targets/hal/TARGET_Freescale/TARGET_K20XX/analogin_api.c
- libraries/mbed/targets/hal/TARGET_Freescale/TARGET_K20XX/sleep.c
- libraries/mbed/targets/hal/TARGET_Freescale/TARGET_KLXX/analogin_api.c
- libraries/mbed/targets/hal/TARGET_Freescale/TARGET_KLXX/sleep.c
The power consumption was reported by Paul Staron to be 100uA higher
when an AnalogIn was used previously.
Problem 1 is that 40uA was used by the async ADC clock, which is never
actually used, so it is disabled. Problem 2 is that setting it for high
speed mode increased it by another 60uA while in deepsleep. This
currently seems to me to be possibly a bug in the design, but the
workaround is checking if this is the case before going to deepsleep,
and if yes, disable it. Afterwards it is re-enabled.
The KSDK ones have different AnalogIn code, could very well be same issue though.
> [HAL][K20XX/KLXX] Fixed deepsleep power consumption when AnalogIn is used

- libraries/tests/mbed/vtor_reloc/main.cpp
The vector table must be 256 aligned to work reliably, it must have been working by accident up to now.  This modification tested on a u-blox c027 board.  Without the change the value of `SCB->VTOR` and the location of `int_table` just before the call to `test_once()` in the second part of the test are as follows:
`SCB->VTOR 0x10000280, int_table 0x100002a0`
...and obviously the test fails.  With the change they are as follows:
`SCB->VTOR 0x10000400, int_table 0x10000400`
...and the test passes.
See issue:
https://github.com/mbedmicro/mbed/issues/993
> Vector table must be 256 aligned

- setup.py
Adding a missing install requirement: Jinja2
> workspace_tools/setup.py: missing install requirement jinja2

- libraries/mbed/targets/cmsis/TARGET_RENESAS/TARGET_RZ_A1H/TOOLCHAIN_GCC_ARM/startup_RZ1AH.s
- libraries/mbed/targets/cmsis/TOOLCHAIN_GCC/TARGET_CORTEX_A/cache.s
Hi,
We fixed a bug as below.
When export RZ/A1H project of GCC from web compiler, build will be error because some assembler file use // comments.
Regards,
Hamanaka
> Fix a bug that build error will occur in GCC.

- libraries/mbed/targets/hal/TARGET_NXP/TARGET_LPC82X/serial_api.c
- Add check_duplication() function to detect UART duplication which is
reported by #942 
- Confirmed to pass MBED_A9 test case (Serial Echo at 115200)
- Add a variable initialize code to prevent GCC warning
> [LPC824] Add UART channel duplication check

- libraries/rtos/rtx/TARGET_CORTEX_A/rt_CMSIS.c
- libraries/rtos/rtx/TARGET_CORTEX_M/rt_CMSIS.c
* Add #pragma Ospace to prevent internal fault of armcc 5.04 and 5.05
* Reported by
http://developer.mbed.org/questions/5003/Compiling-latest-github-with-ARM-DS5-fai/
> [RTOS] Add workaround for internal fault

- libraries/mbed/targets/hal/TARGET_RENESAS/TARGET_RZ_A1H/i2c_api.c
Hi,
We fix a bug as below.
When the following conditions, may not be the normal communication in I2C.
1. A device for I2C address was not found
2. Set "repeated = true".
Regards,
Hamanaka
> Fix a bug that there is a case that can not be normal communication in I2C.

- libraries/USBDevice/USBAudio/USBAudio.cpp
- libraries/USBDevice/USBAudio/USBAudio.h
- libraries/USBDevice/USBDevice/USBEndpoints_KL25Z.h
- libraries/USBDevice/USBDevice/USBEndpoints_LPC11U.h
- libraries/USBDevice/USBDevice/USBEndpoints_LPC17_LPC23.h
- libraries/USBDevice/USBDevice/USBEndpoints_RZ_A1H.h
- libraries/USBDevice/USBDevice/USBEndpoints_STM32F4.h
- libraries/USBDevice/USBHID/USBKeyboard.cpp
- libraries/USBDevice/USBHID/USBKeyboard.h
- libraries/USBDevice/USBHID/USBMouseKeyboard.cpp
- libraries/USBDevice/USBHID/USBMouseKeyboard.h
- libraries/USBDevice/USBMIDI/USBMIDI.cpp
- libraries/USBDevice/USBMIDI/USBMIDI.h
- libraries/USBDevice/USBMSD/USBMSD.cpp
- libraries/USBDevice/USBMSD/USBMSD.h
- libraries/USBDevice/USBSerial/USBSerial.cpp
- libraries/USBDevice/USBSerial/USBSerial.h
Macros exist in each of the USBEndpoints_<target>.h files for assigning default endpoints for bulk, interrupt and isochronous functions. These macros are used by the various device classes. The callback functions in the classes, however, are hard coded to specific endpoint numbers. I have added additional macros to alias the callback functions to ensure that they match the assigned endpoints for a given target.
All currently supported USBDevice targets have used the same endpoint assignments, so no problem has arisen. We are currently working on adding a new target in which the endpoint assignments will be different from the other targets and encountered this issue.
> Added macros to alias the endpoint callback functions to support configurability

- libraries/mbed/targets/hal/TARGET_NXP/TARGET_LPC82X/TARGET_LPC824/device.h
- libraries/mbed/targets/hal/TARGET_NXP/TARGET_LPC82X/TARGET_SSCI824/device.h
- libraries/mbed/targets/hal/TARGET_NXP/TARGET_LPC82X/i2c_api.c
- libraries/mbed/targets/hal/TARGET_NXP/TARGET_LPC82X/us_ticker.c
Fixed hardcoded MRT_Clock_MHz so that the code will also work at a SystemCoreClock different from 30MHz. Optimized time calculations for us_ticker_read. Same modifications as done previously for LPC812.
> Fixed hardcoded MRT_Clock_MHz

- libraries/mbed/targets/hal/TARGET_NXP/TARGET_LPC11U6X/device.h
- libraries/mbed/targets/hal/TARGET_NXP/TARGET_LPC11U6X/sleep.c
- libraries/mbed/targets/hal/TARGET_NXP/TARGET_LPC11U6X/sleep_api.c
The LPC11U68 target didn't have sleep defined for it, so I added it in this branch. I don't have the actual board, so this needs to be tested on the hardware.
> Added sleep and deepsleep for LPC11U68. Needs testing on board

- libraries/tests/mbed/sleep/main.cpp
- workspace_tools/tests.py
- Add LPC11U68 target in MBED_4 test case
- Add wakeup pin for LPC11U68 target and set PullUp mode
> Add LPC11U68 support in Sleep test case

- libraries/rtos/rtx/TARGET_CORTEX_A/rt_CMSIS.c
- libraries/rtos/rtx/TARGET_CORTEX_M/rt_CMSIS.c
pragma push/pop/Ospace are only supported by ARM compiler. Change
predefined marco from __arm__ to __CC_ARM. Warning messages are
shown as below.
[Warning] rt_CMSIS.c@1867: 1866:0: warning: ignoring #pragma push
[-Wunknown-pragmas] ignoring #pragma Ospace  [-Wunknown-pragmas]
[Warning] rt_CMSIS.c@1884: 1866:0: warning: ignoring #pragma push
[-Wunknown-pragmas] ignoring #pragma pop  [-Wunknown-pragmas]
Change-Id: Ife657b710d694449b30dc4b3150cd49c883fc080
Signed-off-by: Jun-Ru Chang <jrjang@gmail.com>
> [RTOS] fix compilation warning

- workspace_tools/build_release.py
There is currently an issue when trying to export a program for the LPC824 using the LPCXpresso toolchain. The toolchain relies on GCC_CR, so this is being added to the build release list.
> Add GCC_CR to LPC824, fixes LPCXpresso exporter

- workspace_tools/build_api.py
Our MAXWSNENV platform will include the BLE stack as a prebuilt library. This change is necessary to include the library files in the mbed build.
> Added copying of library files.

- libraries/USBDevice/USBMIDI/MIDIMessage.h
- libraries/USBDevice/USBMIDI/USBMIDI.cpp
- libraries/USBDevice/USBMIDI/USBMIDI.h
- libraries/tests/usb/device/midi/main.cpp
- workspace_tools/host_tests/midi.py
USBMIDI support was incomplete, SysEx support was missing. This PR add SysEx, with some refactoring to manage MIDI messages > 3 bytes and USB MIDI multiple packets.
> Add SysEx to USBMIDI device

- libraries/USBDevice/USBMIDI/MIDIMessage.h
- libraries/USBDevice/USBMIDI/USBMIDI.cpp
- libraries/USBDevice/USBMIDI/USBMIDI.h
- libraries/mbed/targets/hal/TARGET_NXP/TARGET_LPC11U6X/pwmout_api.c
- libraries/mbed/targets/hal/TARGET_NXP/TARGET_LPC15XX/pwmout_api.c
- libraries/mbed/targets/hal/TARGET_NXP/TARGET_LPC81X/pwmout_api.c
- libraries/mbed/targets/hal/TARGET_NXP/TARGET_LPC82X/pwmout_api.c
* Some targets which use SCT timer for PwmOut have a bug: PWM
signal does not come out when period is set more than 65536us. (issue #1050)
* Fix SCT counter mode from 16-bit Low to 32-bit Unified mode
* Fix wrong cast size (uint64_t) for 32-bit register
* Some TABs convert to white spaces
* Affected with LPC812, LPC824, LPC1549 and LPC11U68
> [NXP's HAL] Fix PwmOut period using SCT

- workspace_tools/targets.py
The LSI clock of Arch Max is 32 KHz, and not sure other STM32F4xx targets have the same LSI clock or not, so define the macro to avoid using the one in [stm32f4xx_hal_conf.h](https://github.com/mbedmicro/mbed/blob/master/libraries/mbed/targets/cmsis/TARGET_STM/TARGET_STM32F4/stm32f4xx_hal_conf.h#L122)
> [Arch Max] fix LSI clock value for Arch Max (STM32F407)

- .travis.yml
- workspace_tools/build_api.py
- workspace_tools/build_release.py
- workspace_tools/ci_templates/library_build/build_report.html
- workspace_tools/ci_templates/library_build/build_report_table.html
- workspace_tools/ci_templates/library_build/report.html
- workspace_tools/ci_templates/scripts.js
- workspace_tools/ci_templates/tests_build/build_report.html
- workspace_tools/ci_templates/tests_build/build_report_table.html
- workspace_tools/ci_templates/tests_build/report.html
- workspace_tools/singletest.py
- workspace_tools/test_api.py
This pull request adds some features that are useful for integrating our build system with Continuous Integration tools. These features include:
- Provide a toolchain filter for build_release script to allow for easy compilation on multiple platforms (ex.  IAR is not supported on Linux, so this is not included when building on Linux)
- Create HTML build report specifically for mbed library and tests (templates built with jinja2)
- Reorganize test building by moving the building of required libraries (RTOS, Ethernet, etc) to the up front, before any tests are built. This removes redundancy and improves reporting.
I have been testing this on my own VMs and everything seems to be running smoothly. Let me know if you have any thoughts on how things have been organized.
> Continuous Integration Features

- libraries/mbed/targets/cmsis/TARGET_STM/TARGET_STM32F4/TARGET_NUCLEO_F411RE/system_stm32f4xx.c
HAL: NUCLEO_F411RE - Corrected USB clock frequency
Modified the main PLL settings so that the USB clock will run at a proper 48MHz instead of 44.44MHz. Consequently, the core clock will now run at 96MHz instead of 100MHz.
> NUCLEO-F411RE USB clock frequency fix

- libraries/mbed/targets/cmsis/TARGET_Freescale/TARGET_K20XX/TARGET_TEENSY3_1/TOOLCHAIN_GCC_ARM/MK20DX256.ld
- libraries/mbed/targets/cmsis/TARGET_Freescale/TARGET_K20XX/TARGET_TEENSY3_1/TOOLCHAIN_GCC_ARM/startup_MK20DX256.s
- libraries/mbed/targets/cmsis/TARGET_Freescale/TARGET_K20XX/TARGET_TEENSY3_1/system_MK20DX256.c
- libraries/rtos/rtx/TARGET_CORTEX_M/RTX_CM_lib.h
- libraries/rtos/rtx/TARGET_CORTEX_M/RTX_Conf_CM.c
- libraries/rtos/rtx/TARGET_CORTEX_M/TARGET_M4/TOOLCHAIN_GCC/HAL_CM4.s
This pull request should fix the GCC_ARM toolchain issue as well as the RTOS library support for the TEENSY3_1 target (Issues #845 and #612). Both fixes have been tested in hardware and work well.
What I'm not sure about is if the settings for OS_TASKCNT and OS_SCHEDULERSTKSIZE are really the optimal values.
> Fixed GCC_ARM toolchain issue and RTOS library support for TEENSY3_1

- CONTRIBUTING.md
- libraries/tests/mbed/sd/main.cpp
- libraries/tests/mbed/sd_perf_fatfs/main.cpp
- libraries/tests/mbed/sd_perf_fhandle/main.cpp
- libraries/tests/mbed/sd_perf_stdio/main.cpp
The old pin definitions were all for Port D pins, which are incorrect. These improper pin mappings caused all tests to fail.
Pin definitions were replaced with the definitions as stated here -
http://developer.mbed.org/media/uploads/sam_grove/xk64f_sensors.jpg.pagespeed.ic.RCpM8talCK.webp
Tests now pass on the K64F Sch Rev D1
> Replaced SPI pin definitions for K64F in SD tests

- workspace_tools/build.py
- workspace_tools/build_travis.py
- workspace_tools/make.py
- workspace_tools/singletest.py
The scripts are not python3 compatible so we should explicitly call
python2.  Some distributions use python3 as the default python interpreter ([ArchLinux](https://www.archlinux.org/news/python-is-now-python-3/) for example) so executing the scripts directly fails on those platforms.
> workspace_tools: Use python2 in shebang

- libraries/mbed/targets/cmsis/TARGET_STM/TARGET_STM32L0/stm32l0xx_hal_rcc.c
> Nucleo L053R8 - multiple definition error for PLLMulTable fix

- libraries/mbed/hal/can_api.h
- libraries/mbed/targets/hal/TARGET_NXP/TARGET_LPC11XX_11CXX/TARGET_LPC11CXX/can_api.c
- libraries/mbed/targets/hal/TARGET_NXP/TARGET_LPC15XX/can_api.c
- libraries/mbed/targets/hal/TARGET_NXP/TARGET_LPC176X/can_api.c
- libraries/tests/mbed/can_loopback/main.cpp
- workspace_tools/tests.py
I've partially implemented the can_mode HAL functions for the LPC1549/LPC11Cxx and LPC1768 platforms.
On the LPC1549/LPC11Cxx which use the C_CAN controller, I've implemented everything except for GlobalTest mode. On the LPC1768, I implemented everything except for GlobalTest mode and SilentTest mode. Based on my preliminary testing, I'm not sure if it's possible to do SilentTest mode, but it's not entirely obvious what is required of SilentTest mode. Is there official API documentation describing what the behavior is expected for each mode?
As LocalTest mode is substantially new, I've added an automated test case, MBED_A27, which does a simple loopback test that verifies it sees the messages it sends out. It only requires that a CAN transceiver is wired up to the controller with …
> Implement some CAN modes for the LPC1549/LPC11Cxx/LPC1768

- libraries/mbed/api/SerialBase.h
Calling SerialBase::attach(NULL, IrqType type) disables interrupt for the given IrqType while calling SerialBase::attach(NULL, NULL, IrqType type) does not.
This pull request adds the same functionality to the latter call.
> Added missing functionality for disabling interrupts in SerialBase.h

- libraries/mbed/targets/hal/TARGET_Freescale/TARGET_KPSDK_MCUS/spi_api.c
Depending on the format by default the Freescale SPI peripheral does not
give proper delay between SPI transfers. So code has been added which
sets half a period delay between SPI transfers.
See the following picture:
http://static.tweakers.net/ext/f/gAoTfuAGPXuMgtqbCm34UOJ9/full.png
This is related to https://github.com/mbedmicro/mbed/issues/840 (you can see the same clock issue in the pic there). This issue: https://github.com/mbedmicro/mbed/issues/968 does not seem to be solved by this, in mode 3 the MOSI line goes up stil way too soon.
> [HAL][KSDK] Fix issue with KSDK SPI timing

- libraries/rtos/rtos/Thread.cpp
- libraries/rtos/rtos/Thread.h
Added functionality to clear consumed signal flags on thread waiting. Example of use:
```
Thread * _th;
// .....
// .....
// Waits for signal flag 1 or 2... 
for(;;){
osEvent oe = _th->signal_wait((1 | 2), 0);
if(oe.status == osEventSignal && (oe.value.signals & 1) != 0){
_th->signal_clr(1);
// add handling code for signal flag 1
}
if(oe.status == osEventSignal && (oe.value.signals & 2) != 0){
_th->signal_clr(2);
// add handling code for signal flag 2
}
}
```
> Updated Thread.cpp|.h to support signal clear

- libraries/mbed/targets/hal/TARGET_Maxim/TARGET_MAX32600/device.h
- libraries/mbed/targets/hal/TARGET_Maxim/TARGET_MAX32600/rtc_api.c
- libraries/mbed/targets/hal/TARGET_Maxim/TARGET_MAX32600/sleep.c
- libraries/mbed/targets/hal/TARGET_Maxim/TARGET_MAX32600/us_ticker.c
- libraries/mbed/targets/hal/TARGET_Maxim/TARGET_MAX32610/device.h
- libraries/mbed/targets/hal/TARGET_Maxim/TARGET_MAX32610/rtc_api.c
- libraries/mbed/targets/hal/TARGET_Maxim/TARGET_MAX32610/sleep.c
- libraries/mbed/targets/hal/TARGET_Maxim/TARGET_MAX32610/us_ticker.c
The adding of the low-power ticker API in #1079 caused build failures in the MAX32600MBED and MAXWSNENV platforms. This commit fixes these failures by implementing the low-power ticker for these platforms.
> [MAX32600MBED,MAXWSNENV] Added low-power ticker.

- libraries/mbed/targets/cmsis/TARGET_Maxim/TARGET_MAX32600/system_max32600.c
- libraries/mbed/targets/cmsis/TARGET_Maxim/TARGET_MAX32610/system_max32610.c
- libraries/mbed/targets/hal/TARGET_Maxim/TARGET_MAX32600/rtc_api.c
- libraries/mbed/targets/hal/TARGET_Maxim/TARGET_MAX32610/rtc_api.c
Fixed some corner case issues with waking up from the low-power ticker.
> [MAX32600MBED,MAXWSNENV] addressed low-power ticker corner cases

- libraries/mbed/targets/hal/TARGET_NXP/TARGET_LPC11XX_11CXX/TARGET_LPC11CXX/can_api.c
While compiling and running the updated MBed repository code for the LPC11c14, I discovered that the can_api.c file in the \LPC11XX_11CXX\LPC11CXX target folder was not building correctly. It appears that there is a spurious "CANCNTL_LBACK" which should actually be "CANTEST_LBACK." I have modified the file to mirror the contents of the can_api.c file in the LPC15XX target folder and it appears to work now.
> Fix bug with CAN loopback implementation on LPC11c14

- README.md
- workspace_tools/export/simplicityv3.py
- workspace_tools/export/simplicityv3_slsproj.tmpl
* Remove references to auto-included libraries
* Update Happy Gecko STK ID
* Apply workaround for known linker input ordering issue
> [Silicon Labs] Update exporter for Simplicity Studio

- docs/BUILDING.md
Corrected minor spelling mistakes and sentences in BUILDING.md.
> Minor spelling correction

- libraries/rtos/rtx/TARGET_CORTEX_M/RTX_CM_lib.h
- libraries/rtos/rtx/TARGET_CORTEX_M/RTX_Conf_CM.c
- workspace_tools/build_travis.py
- workspace_tools/tests.py
* Add RTOS support for Nucleo STM32L152RE
* Add RTOS tests for the target
* Add RTOS build for build travis
> [RTOS] Add Nucleo STM32L152RE platform

- libraries/tests/utest/i2c_eeprom_asynch/i2c_eeprom_asynch.cpp
- libraries/tests/utest/lp_ticker/lp_ticker.cpp
- libraries/tests/utest/serial_asynch/serial_asynch.cpp
- libraries/tests/utest/spi_asynch/spi_master_asynch.cpp
- workspace_tools/tests.py
Peripheral unit tests require target pins definitions. I included K64F pins definitions there as
a show case what is required to define per target.
> Asynch Unit tests (Serial, SPI, I2C, low power ticker)

- workspace_tools/utils.py
Some issues fixed:
1. Added command validation before running a command. The validation assures that the command resolves to an executable file. Descriptive feedback is printed on error.
2. Falsely giving errors for modules that have not been extracted from their .egg. These modules can be imported but false errors were given that they are not installed on the system.
Feedback example:
````
manos@box:~/tmp/mbed/workspace_tools$ python -B build.py -m LPC1768 -t uARM
..
ERROR: run_cmd: Command 'C:/Program Files/ARM/armcc_4.1_791/bin/armcc' can't be found
````
> Fixes for premature error checking

- libraries/mbed/targets/cmsis/TARGET_RENESAS/TARGET_RZ_A1H/inc/iodefines/lvds_iodefine.h
- libraries/mbed/targets/hal/TARGET_RENESAS/TARGET_RZ_A1H/i2c_api.c
Hi,
We fixed bugs of I2C and update a header file of Video driver.
I2C
Bugs are as below.
- In I2C, modify the time-out of Nack is slow problem.
- In I2C, modify Write function and Read function does not work correctly with split run.
Header file
Update the header file for the Video driver support.
Regards,
Hamanaka
> [RZ_A1H]Fix bugs of I2C and Update a header file of Video driver.

- workspace_tools/utils.py
The last change, additional tests if comand is existing, doesn't work under Windows because commands are tested only without extensions but under Windows this is not successful.
> [utils.py] windows problem

- libraries/mbed/targets/hal/TARGET_STM/TARGET_STM32F4/spi_api.c
Due to typo in the #ifdef it would completely skip the ARCH-MAX when
changing the SPI code, causing it to be stuck at lowest frequency.
> [HAL][ARCH-MAX] SPI was fixed to minimum frequency

- workspace_tools/host_tests/host_tests_plugins/host_test_plugins.py
- workspace_tools/host_tests/host_tests_plugins/module_copy_shell.py
- workspace_tools/singletest.py
- workspace_tools/test_api.py
- workspace_tools/test_exporters.py
It was impossible to run test using ```singletest.py``` on more than 1 device of the same type (e.g. two Freedom K64F boards).
Before this change test suite (```singletest.py```) would only run tests for one board per type connected skipping (ignoring) other boards. 
**Note**:
* ```mbed-ls``` was modified to generate extra unique names (human friendly format) for each connected mbed device. This name is used by ```singletest.py``` and can be used by other applications to drive automation with mbedls and mbed devices.
**Example:**
Two NUCLEO_L152RE boards connected to host computer, both with unique TargetId and assigned readable ```platform_name_unique```.
```
$ mbedls
+---------------------+----------------------------+-------------------+-------------------+------------------------------ …
```
> Tools: Added support for testing of multiple targets of the same type (board type)

- workspace_tools/export/gcc_arm_nrf51822.tmpl
The main source code has removed the s110 softdevice in favour of s130. This fixes the GCC ARM export template.
> Update nRF51822 softdevice to s130 in GCC export sciprt

- libraries/mbed/targets/hal/TARGET_NORDIC/TARGET_MCU_NRF51822/TARGET_DELTA_DFCM_NNN40/PinNames.h
- libraries/mbed/targets/hal/TARGET_NORDIC/TARGET_MCU_NRF51822/TARGET_DELTA_DFCM_NNN40/mbed_overrides.c
Hi,
update flash function name, because it is the same as WIFI_API flash function name.
And redefine analog pinout
Thanks
Marco
> modify overrides flash_init/flash powerdown and PinName

- libraries/mbed/targets/hal/TARGET_STM/TARGET_STM32F4/pwmout_api.c
All STM32F4xx targets with a clock frequency larger than 100MHz (F405, F407, F429, F446), have two different maximal timer frequencies: SYSCLK and SYSCLK/2. The pwm frequency calculation was based only on SYSCLK. For Nucleo targets this was OK but for some Discovery and some other targets the pwm frequency was partly wrong, depending on the used timer.
This PR reads out the specific timer clock configuration and calculates the correct pwm frequency.
> [STM32F4xx] correction of PWM frequency calculation 

- libraries/mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/gpio_api.c
- libraries/mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/gpio_object.h
- libraries/mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/objects.h
- libraries/mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/pwmout_api.c
Optimized the footprint per instance of the PwmOut and GPIO objects. Should at least tens of bytes in any give program for EFM32 kits.
> [Silicon Labs] Improvements in RAM footprint of HAL.

- libraries/tests/mbed/wfi/main.cpp
- workspace_tools/host_tests/__init__.py
- workspace_tools/host_tests/wfi_auto.py
- workspace_tools/tests.py
This test ensures that the WFI instruction actually waits for an interrupt. On some HAL implementations, there appears to be a ticker interrupt that fires constantly for internal timing purposes. This however triggers the WFI instruction, causing unexpected behavior.
> Added tests for the WFI instruction

- workspace_tools/export_test.py
The file test_env.h is missing, so the projects created with workspace_tools/export_test.py do not compiler, e.g. gcc_arm for LPC1768.
> Copy missing files to be able to compile export_test projects

- workspace_tools/build_release.py
What the title says. This will be useful specifically with CI tools so we can create smaller, more incremental builds in addition to large nightlies.
> Added platform filter to build_release.py

- workspace_tools/singletest.py
- workspace_tools/test_api.py
This pull request adds an option so only the last test result from a --waterfall test will be added to the report file. This makes it easier to track progress across several builds.
> Consolidate waterfall test results

- libraries/mbed/api/TimerEvent.h
Reverting latest change in the TimerEvent, which removed us ticker api header file inclusion -> was not pulled in to mbed.h,
> TimerEvent - include us ticker - fixing us_ticker_read() not available

- libraries/mbed/api/I2C.h
- libraries/mbed/api/SPI.h
- libraries/mbed/api/SerialBase.h
- libraries/mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/spi_api.c
@Sissors revieW!
- fixing also usage of spi buffers length in the EFM32 HAL
> SPI - transfer() unification

- libraries/USBDevice/USBDevice/USBHAL_LPC11U.cpp
The USB suspend status changed interrupt is now correctly reported on LPC11UXX platforms.
> [USBDevice] LPC11UXX suspend status fix

- libraries/mbed/targets/hal/TARGET_STM/TARGET_STM32L1/rtc_api.c
Since there is not yet any abstraction API for low-power wakeup timer....
The MOTE_L152RC platform needs to application access RtcHandle in order to set RTC Alarm.
RTC Alarm wakes up CPU from deep sleep, after some time delay.
> allow outside access to RtcHandle

- libraries/mbed/targets/cmsis/TARGET_NORDIC/TARGET_MCU_NRF51822/nrf_delay.h
- libraries/mbed/targets/hal/TARGET_NORDIC/TARGET_MCU_NRF51822/serial_api.c
These trivial changes silence annoying GCC warnings that are enabled under `-Wall`.
I've annotated each one individually.
I have accepted the mbed contributor agrreement - I have the same username on mbed.org.
> Fix GCC compilation warnings.

- libraries/tests/mbed/serial_nc_rx/main.cpp
- libraries/tests/mbed/serial_nc_tx/main.cpp
- workspace_tools/host_tests/__init__.py
- workspace_tools/host_tests/serial_nc_rx_auto.py
- workspace_tools/host_tests/serial_nc_tx_auto.py
- workspace_tools/tests.py
These tests ensure that an mbed platform correctly handles having Serial pins set to NC. It tests to ensure that the target can only transmit or only receive (respectively for serial_nc_tx and serial_nc_rx).
> Added tests that ensure correct handling of setting Serial pins to NC

- libraries/rtos/rtos/Thread.cpp
- libraries/rtos/rtos/Thread.h
Added stack checking methods to the Thread class for Cortex-M targets. The stack memory size, currently free stack memory, and currently used stack memory are calculated using the TCB. The maximum stack memory usage is determined by filling the stack with a magic word, and finding the high water mark.
> [RTOS] Added stack checking methods to Thread

- workspace_tools/singletest.py
- workspace_tools/test_api.py
Before if a build error occurred when running singletest.py, the return code would still be `0`, indicating no error. It now sets an error code of -1. Not sure if that's the right number, but at least it's nonzero :)
> Changing return status of singletest.py if a build failure occurs

- workspace_tools/build_release.py
This fixes an issue where the MICRONFCBOARD does not compile when using the build_release.py script.
> Fixed name for MICRONFCBOARD in build_release.py

- libraries/mbed/CMakeLists.txt
- libraries/mbed/module.json
This builds with target descriptions derived from both mbed-gcc and mbed-armcc, requires yotta >= 0.4.4.
cc @jaustin @rgrover
> Make it possible to build the core mbed library with yotta

- libraries/USBDevice/USBDevice/USBEndpoints.h
- libraries/mbed/targets/cmsis/TARGET_Freescale/TARGET_KLXX/TARGET_KL26Z/MKL26Z4.h
- libraries/mbed/targets/cmsis/TARGET_Freescale/TARGET_KLXX/TARGET_KL26Z/TOOLCHAIN_ARM_MICRO/MKL26Z4.sct
- libraries/mbed/targets/cmsis/TARGET_Freescale/TARGET_KLXX/TARGET_KL26Z/TOOLCHAIN_ARM_MICRO/startup_MKL26Z4.s
- libraries/mbed/targets/cmsis/TARGET_Freescale/TARGET_KLXX/TARGET_KL26Z/TOOLCHAIN_ARM_MICRO/sys.cpp
- libraries/mbed/targets/cmsis/TARGET_Freescale/TARGET_KLXX/TARGET_KL26Z/TOOLCHAIN_GCC_ARM/MKL26Z4.ld
- libraries/mbed/targets/cmsis/TARGET_Freescale/TARGET_KLXX/TARGET_KL26Z/TOOLCHAIN_GCC_ARM/startup_MKL26Z4.S
- libraries/mbed/targets/cmsis/TARGET_Freescale/TARGET_KLXX/TARGET_KL26Z/TOOLCHAIN_IAR/MKL26Z4.icf
- libraries/mbed/targets/cmsis/TARGET_Freescale/TARGET_KLXX/TARGET_KL26Z/TOOLCHAIN_IAR/startup_MKL26Z4.s
- libraries/mbed/targets/cmsis/TARGET_Freescale/TARGET_KLXX/TARGET_KL26Z/cmsis.h
- libraries/mbed/targets/cmsis/TARGET_Freescale/TARGET_KLXX/TARGET_KL26Z/cmsis_nvic.c
- libraries/mbed/targets/cmsis/TARGET_Freescale/TARGET_KLXX/TARGET_KL26Z/cmsis_nvic.h
- libraries/mbed/targets/cmsis/TARGET_Freescale/TARGET_KLXX/TARGET_KL26Z/system_MKL26Z4.c
- libraries/mbed/targets/cmsis/TARGET_Freescale/TARGET_KLXX/TARGET_KL26Z/system_MKL26Z4.h
- libraries/mbed/targets/hal/TARGET_Freescale/TARGET_KLXX/TARGET_KL26Z/PeripheralNames.h
- libraries/mbed/targets/hal/TARGET_Freescale/TARGET_KLXX/TARGET_KL26Z/PeripheralPins.c
- libraries/mbed/targets/hal/TARGET_Freescale/TARGET_KLXX/TARGET_KL26Z/PinNames.h
- libraries/mbed/targets/hal/TARGET_Freescale/TARGET_KLXX/TARGET_KL26Z/device.h
- libraries/mbed/targets/hal/TARGET_Freescale/TARGET_KLXX/TARGET_KL26Z/gpio_irq_api.c
- libraries/mbed/targets/hal/TARGET_Freescale/TARGET_KLXX/TARGET_KL26Z/mbed_overrides.c
- libraries/mbed/targets/hal/TARGET_Freescale/TARGET_KLXX/TARGET_KL26Z/serial_api.c
- libraries/mbed/targets/hal/TARGET_Freescale/TARGET_KLXX/TARGET_KL26Z/spi_api.c
- libraries/mbed/targets/hal/TARGET_Freescale/TARGET_KLXX/objects.h
- libraries/rtos/rtx/TARGET_CORTEX_M/RTX_CM_lib.h
- libraries/rtos/rtx/TARGET_CORTEX_M/RTX_Conf_CM.c
- workspace_tools/targets.py
Added KL26Z as a target.
HAL and CMSIS modules added for the KL26Z 
Added KL26Z to Targets.py
Edited USBEndpoints.h to add KL26 Target
Edited RTX_CONF_CM.c and RTX_CM_Lib.h to add KL26 target - Unsure of how many concurrent threads to add, so defined 6 as is with the KL25, however the KL46 has 14 defined so unsure what makes the difference here
Compiled Libraries successfully : MBED,CMSIS,USBHost, USBDevice, RTOS, DSP, FAT
Unable to currently test all changes on hardware due to a lack of having a FRDM-KL26Z board currently, any testing anyone could complete would be appreciated.
> Added KL26 Target

- libraries/rtos/rtx/TARGET_CORTEX_M/RTX_CM_lib.h
According to the LPC11U68 datasheet, the top of SRAM0 occurs at 0x10008000, not 0x10004000.
> [RTOS] Fixed INITIAL_SP for LPC11U68

- libraries/mbed/targets/hal/TARGET_NXP/TARGET_LPC11U6X/gpio_api.c
Hello All
Change P0_11 to use GPIO(DigitalOut) from TDI.
I accepted Contributor Agreement.
My nickname on mbed is "Hapi_Tech"
Best regards.
> [11U68]Fixed P0_11 for GPIO

- libraries/mbed/targets/hal/TARGET_NORDIC/TARGET_MCU_NRF51822/serial_api.c
This is a small optimisation for ARM compiler toolchains: constant
arrays should be declared const explicitly, to let the compiler put them
into .rodata instead of .data. GCC automatically detects that the array
is read-only, and already puts it into flash.
This way, we free 136 bytes of RAM, which is nothing to sneeze at, given
that applications only get about 2048 bytes by default, on 16k targets.
Please note that you will need to disable data compression in armlink to
see the actual difference, using the "--datacompressor off" switch, for
example.
> Nordic: add const qualifier to acceptedSpeeds in serial API

- libraries/mbed/targets/hal/TARGET_WIZNET/TARGET_W7500x/TARGET_WIZwiki_W7500/PeripheralPins.c
I found wrong pin mux about I2C.
And I correct it.
> I2C PeripheralPins bug fix.

- libraries/mbed/targets/hal/TARGET_NXP/TARGET_LPC11UXX/TARGET_MCU_LPC11U35_501/TARGET_LPC11U35_501_IBDAP/PinNames.h
- libraries/mbed/targets/hal/TARGET_NXP/TARGET_LPC11UXX/TARGET_MCU_LPC11U35_501/TARGET_LPC11U35_501_IBDAP/device.h
- workspace_tools/targets.py
This pull request is for adding Armstart IBDAP-LPC11U35 board to the mbed supported platforms.
-----------------------------------
IBDAP is a fully CMSIS-DAP compatible debug adapter. It provides vendor independent debug interface between your PC over USB and target ARM device over JTAG/SWD pins. You can do debugging functions like stepping, breakpoints, watch points and firmware download etc. It's fully supported by Keil, OpenOCD, GNU GDB, IAR and other commonly used debugging tools.
Debug adapters are expensive, some could cost thousands of dollars, some may not be compatible among different vendors. Luckily, ARM standardized the debugging interface which is called CMSIS-DAP and released the firmware implementation on some processors, however, you still need a Keil MDK Professional …
> add IBDAP-LPC11U35 platform

- libraries/mbed/api/mbed_assert.h
- libraries/mbed/common/assert.c
Modified `mbed_assert_internal()` to call `error()` with the assertation message instead of `fprintf()` followed by `mbed_die()`. This allows assertation failures to be caught by custom `error()` functions that replace the default weak definition.
> [mbed] Modified MBED_ASSERT to use error()

- libraries/mbed/targets/hal/TARGET_NXP/TARGET_LPC43XX/TARGET_LPC4337/PinNames.h
Please find test summary below. There are some errors but I think it's not critical problem.
* MBED_16 (RCT) failed by automated test, however the same test case works by manual test.
* MBED_37 and MBED_38 (Serial NC RX/TX) failed.  I saw same failure in other platform such as the LPC1768.
* MBED_A9 (Serial) timeout.  I saw same failure in other platform such as the LPC1768.
```
Test summary:
+---------+---------+-----------+-------------+---------------------------------------+--------------------+---------------+-------+
| Result  | Target  | Toolchain | Test ID     | Test Description                      | Elapsed Time (sec) | Timeout (sec) | Loops |
+---------+---------+-----------+-------------+---------------------------------------+--------------------+---------------+-------+
| OK …
```
> [LPC4337] fix PinNames.h for OM13070

- workspace_tools/singletest.py
- workspace_tools/test_api.py
Moved includes for mbed-ls-sensitive functions into try a block.
Also added checks to see if mbed-ls is installed before adding mbed-ls-sensitive command line options.
> Remove mbed-ls dependency from test framework

- workspace_tools/targets.py
Redesign Nordic nRF51 MCU and derivative platforms to use class inheritance:
* add classes to support both versions - 16K and 32K
* add classes to support 2 modes - BOOT and (F)OTA
* change all classes to use the corresponding parent class
> Redesign Nordic nRF51 MCU and derivative platforms

- workspace_tools/targets.py
This solves issues with the build system trying to build ARM_MPS targets using GCC_ARM. They currently do not compile with GCC_ARM, only with ARMCC.
> Removes GCC_ARM as a supported compiler for the ARM_MPS targets

- libraries/mbed/targets/cmsis/TARGET_STM/TARGET_STM32F0/TARGET_NUCLEO_F070RB/hal_tick.c
I assume leaving this in was an oversight.
> Removed PB6 debug toggling

- libraries/mbed/targets/hal/TARGET_NXP/TARGET_LPC81X/serial_api.c
- libraries/mbed/targets/hal/TARGET_NXP/TARGET_LPC82X/serial_api.c
This is a pull request related to a similar issue to https://github.com/mbedmicro/mbed/issues/1011 for LPC8xx targets
This fix is a port of https://github.com/mbedmicro/mbed/pull/1012 to LPC81x/LPC82x
so credits go to @jurgis
> Enable LPC8xx usart when configuring it

- libraries/rtos/rtos/Thread.cpp
The warning message is shown as below.
Compile: Thread.cpp
[Warning] Thread.cpp@45: In constructor 'rtos::Thread::Thread(void (*)(const void*), void*, osPriority, uint32_t, unsigned char*)':
comparison between signed and unsigned integer expressions [-Wsign-compare]
Signed-off-by: Jun-Ru Chang <jrjang@gmail.com>
> Fix compilation warning

- workspace_tools/test_api.py
#　Description
This is a minor change but improves toolchain issues investigations and assigns proper behavior to verbose flag.
Added verbose mode to mbed library build when using ```singletest.py``` ```-v``` (verbose) switch
When using
```
$ cd mbed/workspace_tools
$ singletest.py ... -v
```
verbose prints from mbed SDK library build were not shown.
When debugging issues related to compiler flags etc. those verbose messages should be visible.
```
$ singletest.py --auto -v
```
```make
[DEBUG] Command: c:/Keil/ARM/ARMCC\bin\armcc -c --cpu=Cortex-M4.fp --gnu -Otime --split_sections --apcs=interwork --brief_diagnostics --restrict --multibyte_chars -O3 -Ic:/Keil/ARM/ARMCC\include -DTARGET_KPSDK_MCUS -DTARGET_FF_ARDUINO -D__CORTEX_M4 -DCPU_MK64FN1M0VMD12 -DTARGET_FRDM -DTARGET_CORTEX_M …
```
> Tools: Added verbose mode to mbed library build when using singletest.py

- libraries/mbed/targets/cmsis/TARGET_NORDIC/TARGET_MCU_NRF51822/system_nrf51.c
Since some Nordic platforms don't use an external clock source, they
need to be built with the TARGET_NRF_LFCLK_RC flag. If they don't,
SystemInit will wait indefinitely for an external clock to start.
This patch adds a 1s timeout to the external oscillator initialisation,
and falls back to using the internal RC one if no LFCLKSTARTED event was
received in this interval.
For most applications, this won't matter. When building for the wrong
Nordic target, pin numbers will be mixed up as well and the application
will break later on.
But on targets that can only be updated using FOTA and don't have an
interface chip, this patch avoid ending up with a bricked device after a
slight mistake. Indeed, BLE DFU service is portable across all boards
and will run even with a mixed-up target setup, …
> Nordic: fallback to the internal LF clock in case Xtal doesn't start

- libraries/mbed/targets/hal/TARGET_NORDIC/TARGET_MCU_NRF51822/us_ticker.c
This patch clears the EVENT_COMPARE register even when we're not
expecting to get a COMPARE interrupt.
Here is a scenario where we get an unwelcome interrupt, and where it
currently results in a deadlock:
* A Ticker T1 runs at 500ms
* Its handler registers a Timeout T2 at 20µs. Since LF clock runs at
32.768kHz, this will be rounded up to a multiple of 30.5µs (actually
61µs, to ensure we're in the next tick window)
```
T1  T2                                T1' T2'
-------|---|---------------------------------|---|--------->
:   :                                 :
<---> n * 30.5µs                      :
<--------------- 500ms --------------->
```
* When the ticker API handles T1, it calls us_ticker_set_interrupt a
first time for T1', and then for registering T2.
* Since T2 period is less …
> Nordic: handle unwanted RTC interrupts

- libraries/mbed/common/board.c
- libraries/mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/TARGET_EFM32GG_STK3700/device.h
- libraries/mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/TARGET_EFM32HG_STK3400/device.h
- libraries/mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/TARGET_EFM32LG_STK3600/device.h
- libraries/mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/TARGET_EFM32WG_STK3800/device.h
- libraries/mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/TARGET_EFM32ZG_STK3200/device.h
the Silicon Labs boards do not exhibit proper siren lights when the error() function is called.
This pull request adds the proper #defines to trigger siren lights on LED0 and LED1. Now the siren lights work correctly.
Try running the following code before the PR and after. Prior it will hang and a single LED will light up, after the PR siren lights will flash and text will appear on the output terminal. 
```C
void
main(void){
error("something went wrong...");
// Siren lights should be flashing now and output should be on the terminal
}
```
> Blue Lights of Death fix for Silicon Labs boards

- libraries/mbed/targets/cmsis/TARGET_NXP/TARGET_LPC15XX/LPC15xx.h
Adjust offset for GPIO port word pin registers from 0x100 to 0x1000.
The updated SVD file supporting this change can be found on the [lpcware](https://www.lpcware.com/content/nxpfile/lpc1500-svd-file) site.
I don't think any existing code makes use of the GPIO word pin registers, but I've manually verified that they work on an LPCXpresso 1549 board.
> [LPC15XX] Fix GPIO port word pin registers offset

- libraries/mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/TARGET_EFM32GG_STK3700/device_peripherals.h
- libraries/mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/TARGET_EFM32HG_STK3400/device_peripherals.h
- libraries/mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/TARGET_EFM32LG_STK3600/device_peripherals.h
- libraries/mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/TARGET_EFM32WG_STK3800/device_peripherals.h
- libraries/mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/TARGET_EFM32ZG_STK3200/device_peripherals.h
- libraries/mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/mbed_overrides.c
In certain cases, the clock selection in the board header did not take effect, even though HFXO was requested.
Root cause: you cannot use a C-enum name in a #if compare, because the preprocessor will replace all enum names with 0 (so all checks on HFXO/LFXO checked out regardless of the define).
> [Silicon Labs] Fix incorrect clock selection

- workspace_tools/host_tests/host_test.py
- workspace_tools/host_tests/host_tests_plugins/module_copy_mbed.py
- workspace_tools/host_tests/host_tests_plugins/module_copy_shell.py
This PR aligns how mbed 2 and 3 use ```-c``` of switch for ```singletest.py```.
Note: ```-c``` switch allows users to select binary copy method.
With this change default copy (mbed flashing) method will be changed from ```shutil``` to default OS shell copy command:
* posix: ```cp```, ```sync```
* Windows: ```copy```
This hopefully will prevent issues such as 'flashing failed due to shutil.copy() implementation defects';
mbed interface chip handles well default OS copy commands, not Python's ```shutil.copy()```.
> Tools: singletest.py option -c with shell copy method as default copy method

- libraries/mbed/targets/hal/TARGET_STM/TARGET_STM32F4/TARGET_DISCO_F401VC/device.h
- libraries/mbed/targets/hal/TARGET_STM/TARGET_STM32F4/TARGET_DISCO_F407VG/device.h
- libraries/mbed/targets/hal/TARGET_STM/TARGET_STM32F4/TARGET_DISCO_F429ZI/device.h
- libraries/mbed/targets/hal/TARGET_STM/TARGET_STM32F4/TARGET_NUCLEO_F401RE/device.h
- libraries/mbed/targets/hal/TARGET_STM/TARGET_STM32F4/TARGET_NUCLEO_F411RE/device.h
- libraries/mbed/targets/hal/TARGET_STM/TARGET_STM32F4/TARGET_NUCLEO_F446RE/device.h
All ST boards do not have the blue lights of death. on calling `error()` the message will print, but the led lights will not blink, this PR adds BLoD to all ST boards. 
Add requisite lines to the device.h files to enable BLoD behavior (All ST Boards have a single led)
* improve the BLOD routine so its generic for one light (ie get change the ERROR_LED_RED to something like ERROR_LED_SINGLE) 
* change rate of blink to be random-ish like true siren lights are
* get partners to add this to all the ST Board derivitives (ublox, mdot, archmax)
> ST BLoD Fix

- .gitignore
- libraries/mbed/targets/cmsis/TARGET_NXP/TARGET_LPC81X/TARGET_LPC810/TOOLCHAIN_GCC_ARM/LPC810.ld
- libraries/mbed/targets/cmsis/TARGET_NXP/TARGET_LPC81X/TARGET_LPC812/TOOLCHAIN_GCC_ARM/LPC812.ld
- libraries/mbed/targets/cmsis/TARGET_NXP/TARGET_LPC81X/TOOLCHAIN_GCC_ARM/startup_LPC81X.S
- libraries/mbed/targets/hal/TARGET_NXP/TARGET_LPC81X/pinmap.c
- libraries/mbed/targets/hal/TARGET_NXP/TARGET_LPC81X/us_ticker.c
- workspace_tools/export/gcc_arm_lpc810.tmpl
- workspace_tools/export/gcc_arm_lpc812.tmpl
- workspace_tools/export/gccarm.py
- workspace_tools/targets.py
LPC810 has only 4KB of flash, thus avoiding dead code is really nice.
Here the NVIC interrupt setup was pulled from the us_ticker code even
if no code is using timer events.
This also adds ARM_GCC support for TARGET_LPC81X.
LPC81X and LPC82X support Cortex M0+ VTOR register, so it is not
necessary to put non-init text at 0x200.
> LPC81X: reduce code size and add ARM_GCC support

- libraries/mbed/targets/hal/TARGET_Freescale/TARGET_KLXX/TARGET_KL43Z/PeripheralPins.c
- libraries/mbed/targets/hal/TARGET_Freescale/TARGET_KLXX/rtc_api.c
RTC is available for this platform but mbed didn't support it. I've just fixed it based on sample code package from freescale: http://www.freescale.com/webapp/sps/site/prod_summary.jsp?code=FRDM-KL43Z&fpsp=1&tab=Design_Tools_Tab and tested it. 
So now it works properly. I kept also old configuration for other platforms.
> [FRDM KL43Z] Fix RTC init function for KL43Z

- libraries/mbed/targets/cmsis/TARGET_NORDIC/TARGET_MCU_NRF51822/system_nrf51.c
Fix a signed and unsigned integer comparison warning in the Nordic stack
> Fix a signed and unsigned integer comparison warning

- libraries/mbed/.yotta_ignore
This minimises the published module size.
@0xc0170 @stevenewey @jaustin
> ignore target files not supported by the yotta module

- workspace_tools/host_tests/host_test.py
- workspace_tools/host_tests/host_tests_plugins/module_copy_mbed.py
- workspace_tools/host_tests/host_tests_plugins/module_copy_shell.py
- workspace_tools/host_tests/host_tests_plugins/module_copy_silabs.py
This moves the behavior of sleeping the host test while the mbed is remounting into the host test copy plugin.
This will allow other copy plugins (one that I will submit once this is merged) to have more control over the remounting process and improve performance.
> Move program_cycle_s into host test copy plugins

- workspace_tools/host_tests/host_test.py
- workspace_tools/singletest.py
- workspace_tools/test_api.py
This PR fixes a number of issues with Unix systems and testing mbeds in parallel.
Sometimes mbeds do not remount at the same mount point and serial port when testing in parallel. This PR uses mbedls throughout the testing process if the `--auto` option is used. It updates the mbed mount point before the test is copied. It also updates the serial port before it is acquired for testing.
> Adding checks with mbedls throughout testing process

- workspace_tools/test_api.py
The test framework will mistakenly print a failure when it actually does passes at least once when using the waterfall option. This fixes the issue.
> Fixes reporting of failure when one test passes when using --consolidate-waterfall

- libraries/mbed/targets/cmsis/TARGET_NXP/TARGET_LPC176X/TOOLCHAIN_GCC_CR/LPC1768.ld
* Divide AHB SRAM for USB and Ethernet RAM regions
* Add NOLOAD keyword for .bss sections to avoid redundant data in final
image
This bug was reported as below:
https://developer.mbed.org/questions/60894/Exporting-mbed-progam-to-LPCXpresso/
https://developer.mbed.org/questions/60961/section-bss-will-not-fit-in-region-RamLo/
>  [LPC1768 GCC_CR exporter] Fixed linker description

- README.md
- libraries/mbed/targets/cmsis/TARGET_STM/TARGET_STM32L4/TARGET_DISCO_L476VG/TOOLCHAIN_ARM_MICRO/startup_stm32l476xx.s
- libraries/mbed/targets/cmsis/TARGET_STM/TARGET_STM32L4/TARGET_DISCO_L476VG/TOOLCHAIN_ARM_MICRO/stm32l476xx.sct
- libraries/mbed/targets/cmsis/TARGET_STM/TARGET_STM32L4/TARGET_DISCO_L476VG/TOOLCHAIN_ARM_STD/startup_stm32l476xx.s
- libraries/mbed/targets/cmsis/TARGET_STM/TARGET_STM32L4/TARGET_DISCO_L476VG/TOOLCHAIN_ARM_STD/stm32l476xx.sct
- libraries/mbed/targets/cmsis/TARGET_STM/TARGET_STM32L4/TARGET_DISCO_L476VG/TOOLCHAIN_GCC_ARM/STM32L476XX.ld
- libraries/mbed/targets/cmsis/TARGET_STM/TARGET_STM32L4/TARGET_DISCO_L476VG/TOOLCHAIN_IAR/stm32l476xx.icf
- libraries/mbed/targets/cmsis/TARGET_STM/TARGET_STM32L4/TARGET_NUCLEO_L476RG/TOOLCHAIN_ARM_MICRO/startup_stm32l476xx.s
- libraries/mbed/targets/cmsis/TARGET_STM/TARGET_STM32L4/TARGET_NUCLEO_L476RG/TOOLCHAIN_ARM_MICRO/stm32l476xx.sct
- libraries/mbed/targets/cmsis/TARGET_STM/TARGET_STM32L4/TARGET_NUCLEO_L476RG/TOOLCHAIN_ARM_STD/startup_stm32l476xx.s
- libraries/mbed/targets/cmsis/TARGET_STM/TARGET_STM32L4/TARGET_NUCLEO_L476RG/TOOLCHAIN_ARM_STD/stm32l476xx.sct
- libraries/mbed/targets/cmsis/TARGET_STM/TARGET_STM32L4/TARGET_NUCLEO_L476RG/TOOLCHAIN_GCC_ARM/STM32L476XX.ld
- libraries/mbed/targets/cmsis/TARGET_STM/TARGET_STM32L4/TARGET_NUCLEO_L476RG/TOOLCHAIN_IAR/stm32l476xx.icf
Move main ram to the 32k L4-SRAM2 which is being retained in
standby mode. The additional 96k ram comes second.
The new memory layout preserves all vectors and stack in standby mode.
Without this fix the heap and stack overlap on Nucleo/Disco mbed releases because the stack is wrongly defined.
I hope this is correct and it helps. (this supersedes #1349)
Regards helmut@helios.de
> Fixed stack location problem for disco and nucleo boards (STM32L4)

- requirements.txt
mbed-ls is used heavily in CI systems. This adds the tool to the requirements.txt so the CI system can automatically install it with the rest of the dependencies.
> Added mbed-ls to requirements.txt

- libraries/mbed/targets/hal/TARGET_STM/TARGET_STM32F7/rtc_api.c
Simple check to test the RTC ISR register if RTC is set up and running.
Avoids register reset on nRST or power cycle with vBAT present.
> TARGET_STM32F7\rtc_api.c enable backup RTC function

- workspace_tools/export/gcc_arm_rblab_blenano.tmpl
- workspace_tools/export/gccarm.py
- workspace_tools/export_test.py
This adds support for exporting to ARM GCC.
I wasn't able to figure out what to do about the SOFTDEVICE path for the Makefiles, but none of the other NRF51 boards seem to handle this well either.
Please let me know if I missed something, as this is my first runthrough on this codebase.
> Add ARM GCC export for RBLabs BLE Nano

- libraries/net/lwip/lwip-sys/arch/sys_arch.c
- libraries/net/lwip/lwip-sys/arch/sys_arch.h
Hi,
We reflected the change size of the structure of the Mutex associated with NEON of CMSIS-RTOS RTX for Cortex-A9 support to ethernet module.
Regards,
Yamanaka
> Reflect the change size of structure of Mutex to Ethernet module

- libraries/USBHost/USBHost/TARGET_RENESAS/TARGET_RZ_A1H/ohci_wrapp_RZ_A1.c
- libraries/USBHost/USBHost/TARGET_RENESAS/TARGET_RZ_A1H/ohci_wrapp_pipe.c
- libraries/USBHost/USBHost/USBHALHost_RZ_A1.cpp
Hi,
We modified bugs of device insertion and removal and isochronous transfer.
Bugs are as below.
- When user disconnect the USB during Audio playback, GR-PEACH may not recognize it.
- When running isochronous transfer multiple at the same time, GR-PEACH can not operate properly.
Regards,
Yamanaka
> In USB Host, fix bugs of device insertion and removal and isochronous transfer.

- workspace_tools/targets.py
Current S110 support is only available for default (SoftDevice + App)
images.
At the moment, a BOOT image built for micro:bit will contain the S130
SoftDevice and the app will be located at 0x1c000, even though we want a
S110 SoftDevice.
Since the elf build is still done with the S110 linker script, the entry
point will be offsetted by 0x2000 and it will fail to run.
This patch creates an interface class that allows all S110 targets to
override the SoftDevices list.
Signed-off-by: Jean-Philippe Brucker <jean-philippe.brucker@arm.com>
---
Changes since v1:
* Also move the TARGET_MCU_NRF51_16K_S110 label into the common interface
> targets.py: NRF51: support S110 builds for OTA and BOOT targets

- libraries/mbed/targets/hal/TARGET_Freescale/TARGET_K20XX/TARGET_K20D50M/us_ticker.c
- libraries/mbed/targets/hal/TARGET_Freescale/TARGET_K20XX/TARGET_TEENSY3_1/us_ticker.c
Fixed for the K20D50M a possible race condition in the software part of
the timer.
The Teensy has the ability to chain timers, so similar to the KSDK ones
we switched it to full hardware timers for both Ticker and regular
Timer.
I probably should have finished typing the commit name :).
> [HAL][K20XX] us_ticker changes

- libraries/mbed/targets/cmsis/TARGET_STM/TARGET_STM32F0/TARGET_NUCLEO_F042K6/system_stm32f0xx.c
this resolves a lot of problems and the external clock can be check
> [NUCLEO_F042K6] HSI default value rightly set

- libraries/mbed/targets/hal/TARGET_STM/TARGET_STM32L1/serial_api.c
Fixes issue #1405. USART4_BASE and USART5_BASE are changed to UART4_BASE and UART5_BASE in <code>libraries/mbed/targets/hal/TARGET_STM/TARGET_STM32L1/serial_api.c</code>.
> Fix broken STM32_NUCLEO_L152RE UARTs 4 and 5.

- libraries/mbed/targets/hal/TARGET_NORDIC/TARGET_MCU_NRF51822/analogin_api.c
According to the Reference Manual v3, section 31.1.5 Usage, "When the ADC conversion is completed, an END event will be generated..." therefore the END event should be polled instead of the BUSY reg. There are cases where the BUSY flag is deasserted before the result of the conversion has been stored into the RESULT reg.
> Fix analogin checking the wrong flag for completion

- workspace_tools/test_api.py
- workspace_tools/upload_results.py
- Instead reporting any result that's not OK as a FAIL, it will keep the error message (TIMEOUT, FAIL, ERROR, etc)
- Fixes this issue in the upload result script as well
> Handling failures correctly and adding timeout status

- workspace_tools/export/uvision4_nucleo_f042k6.uvproj.tmpl
- workspace_tools/export/uvision4_nucleo_f302r8.uvproj.tmpl
- workspace_tools/export/uvision4_nucleo_f303k8.uvproj.tmpl
- workspace_tools/export/uvision4_nucleo_f303re.uvproj.tmpl
- workspace_tools/export/uvision4_nucleo_f334r8.uvproj.tmpl
Hello,
I fixed typo in some NUCLEO uvproj files.
AfterMake RunUserProg1 options are now enabled.
Updated boards lists are shown below.
F042K6,F302R8,F303K8,F303RE,F334R8
Export .bin file names are now Fixed.
Updated boards lists are shown below.
F042K6,F303K8,F303RE
Regards,
Tiryoh
> Fix typo in some NUCLEO uvproj files

- workspace_tools/build.py
- workspace_tools/build_api.py
- workspace_tools/build_release.py
- workspace_tools/test_api.py
- workspace_tools/test_exporters.py
- workspace_tools/toolchains/__init__.py
- workspace_tools/toolchains/arm.py
- workspace_tools/toolchains/gcc.py
- workspace_tools/toolchains/iar.py
This is a big PR! It's hard one to split up because there are so many dependent parts.
- Attempts to consolidate most reports across all scripts. The same data structure is used for Junit reports and printed reports (for builds especially).
- Adds Junit reports for builds. This will help with keeping track of builds in CI.
- Now prints which tests and libraries succeeded or failed to build in the build summary (for build_release.py and singletest.py)
I have done quite a bit of testing with this locally and this does not seem to break any of our existing scripts. The changes are mostly behind-the-scenes with a few added features.
> Consolidate Reporting and add Build Reports

- workspace_tools/test_api.py
I introduced a regression a while ago that builds library dependencies out of order when building tests. This PR fixes that regression.
Library dependencies are now built in the order they are specified in the test's definition in tests.py.
Ex. for the test `NET_1`, its definition looks like this in tests.py:
```
{
"id": "NET_1", "description": "TCP client hello world",
"source_dir": join(TEST_DIR, "net", "helloworld", "tcpclient"),
"dependencies": [MBED_LIBRARIES, RTOS_LIBRARIES, ETH_LIBRARY, TEST_MBED_LIB],
"duration": 15,
"automated": True,
"peripherals": ["ethernet"],
},
```
You can see the order in which the library dependencies will be built by examining the `dependencies` key.
> Fix for issue with libraries being built out of order

- workspace_tools/test_api.py
There was in issue this commit: https://github.com/mbedmicro/mbed/commit/065705009828b7c1255797f7d628de1cbedc9bb4
It will try to build libraries for the tests (eg RTOS, RTX, et) multiple times. This fixes that issue.
> Fixes issue where library is compiled multiple times during testing

- libraries/mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/serial_api.c
- libraries/mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/sleep.c
- libraries/mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/spi_api.c
This PR fixes a few bugs in the serial, spi and sleep HAL implementations for EFM32.
* serial: set TXC interrupt flag on the correct peripheral when performing async write using interrupts
* spi: remove erroneous `sleep()` call in `spi_master_write()`, declare init helper functions as static
* sleep: remove option to enter EM4, as there is no way of configuring wakeup from EM4 in mbed
@0xc0170
> Bugfixes to EFM32 serial, spi and sleep HAL

- workspace_tools/tests.py
This allows targets to be excluded from automated tests.
For example, the NRF51 does not have a RTC. This will allow the RTC test to run by default except on the NRF51 targets.
> Added exclude_mcu key to tests.py config

- workspace_tools/build.py
- workspace_tools/libraries.py
- workspace_tools/make.py
- workspace_tools/paths.py
Here's my attempt at fixing #1426, which I filed earlier.  This PR adds a `--rpc` option to `build.py` and `make.py` that does the same thing as similar flags for the other libraries.
Here's what I get when I run the build script now:
~~~{.sh}
$ python2 workspace_tools/build.py --mcu=LPC1768 --tool="GCC_ARM" --rpc
[WARNING] Using default settings. Define your settings in the file "workspace_tools/private_settings.py" or in "./mbed_settings.py"
Building library CMSIS (LPC1768, GCC_ARM)
Building library MBED (LPC1768, GCC_ARM)
Building library RPC (LPC1768, GCC_ARM)
Completed in: (0.02)s
Build successes:
* GCC_ARM::LPC1768
~~~
And the outputs in the build dir seem to show that it works:
~~~{.sh}
$ tree build/rpc 
build/rpc
├── Arguments.h
├── mbed_rpc.h
├── parse_pins.h
├── RpcClasses.h
├── …
> Added option to build rpc library. closes #1426

- libraries/mbed/targets/hal/TARGET_NORDIC/TARGET_MCU_NRF51822/i2c_api.c
- libraries/mbed/targets/hal/TARGET_NORDIC/TARGET_MCU_NRF51822/twi_master.c
- libraries/mbed/targets/hal/TARGET_NORDIC/TARGET_MCU_NRF51822/twi_master.h
Without this fix SPI locks up if it is using the second I2C/SPI peripheral after I2C has been initialised (evne if I2C uses the first peripheral).
> Fix #1393 - I2C assumes NRF_TWI1

- libraries/mbed/common/InterruptIn.cpp
If we attach a function, then detach, a function pointer keeps pointing to an old function.
Fixes #1440
> InterrupIn - attach with null clears the function pointer

- libraries/mbed/targets/hal/TARGET_Freescale/TARGET_K20XX/i2c_api.c
The increase of the Teensy3.1 core clock to 96MHz has caused the i2c communication to fail.
Problem is caused by a workaround using core _NOP clock cycles to perform a delay in the i2c.stop function.
Clearly running at a higher core clock rate the delay is reduced resulting with the i2c.stop function exiting before completing.
Increasing the _NOP count to 110 does get round the issue, however this will lead to an unnecessary delay for the slower K20D50M Target that requires 60 to work, unless conditional code is employed.
Replacing the workaround code to test with I2C_S_BUSY_MASK has fixed the issue.
This now makes the function independent of the core clock frequency allowing the clock set up to be changed without affecting the i2c.stop operation.
Hardware tested on both Targets with …
> Teensy3.1 - K20D50M Update i2c_api.c

- libraries/mbed/targets/hal/TARGET_STM/TARGET_STM32L1/serial_api.c
UART RX overrun is causing interrupt flood in uart_irq() on ST platforms. This pull request adds overrun flag clearing in the uart interrupt to prevent lockup from interrupt flooding.  The test program is here https://developer.mbed.org/users/dudmuck/code/uart_overrun_test/   I have seen lockup on NUCLEO_L152RE and _F103RB boards, but not on NXP11U68.   For now I am only concerned with stm32l1xx platform.
> handle UART RX overrun on stm32l1xx

- libraries/USBHost/USBHostMSD/USBHostMSD.cpp
- libraries/USBHost/USBHostMSD/USBHostMSD.h
- libraries/fs/fat/FATFileSystem.h
- libraries/fs/sd/SDFileSystem.cpp
- libraries/fs/sd/SDFileSystem.h
Several integer widths in the public API were incorrect, and have been modified to match the underlying FatFs library.
> [FATFileSystem] Fixed API integer widths

- workspace_tools/upload_results.py
This separates the build and test results when uploading them to the test database. This will provide more explicit data when showing results.
> Separating build and test results in upload script

- libraries/mbed/targets/hal/TARGET_NORDIC/TARGET_MCU_NRF51822/serial_api.c
When initializing the NRF51's serial TX and RTS pins set the
data output register to high before setting the setting them to
output.  This prevents these pins from glitching low before
the UART has been turned on.
> Fix glitch when initializing NRF51-DK serial port

- libraries/mbed/targets/cmsis/TARGET_STM/TARGET_STM32F0/TARGET_NUCLEO_F030R8/hal_tick.c
Refer to:
https://github.com/mbedmicro/mbed/issues/1329
https://developer.mbed.org/questions/61386/Is-there-system-clock-error-in-STM32F030/
> [NUCLEO-F030R8] Fixed: The issue of LED blinking too fast.

- libraries/mbed/targets/hal/TARGET_NXP/TARGET_LPC176X/i2c_api.c
LPC1768 slave issues a STOP condition without waiting for master #666: https://developer.mbed.org/forum/bugs-suggestions/topic/5266/
Fix credits to Ravi Bamidi.
> Issue #666  LPC1768 i2c_slave_read fix

- libraries/mbed/targets/hal/TARGET_NORDIC/TARGET_MCU_NRF51822/serial_api.c
Increase the number of entries in the baud rate table from 17 to 18.
This problem was introduced in the patch:
0a6e345400e5e73eeb8df189bc3ce112f0dbd793 -
Add support for 56000 baud on nrf51
> Fix nRF51 baud table size

- workspace_tools/tests.py
Disables the automated RTC test from running on the LPC1114 (since it doesn't have an RTC)
> Added LPC1114 from RTC test exclude list

- libraries/mbed/common/RawSerial.cpp
The function vsnprintf does not properly handle a size of zero for
the destination buffer, and will write data to it.  If the buffer is
set to null this will cause a hardfault.  This patch adds a workaround
for this bug by using a buffer of size 1.
> Fix RawSerial when used with ARMCC microlib

- workspace_tools/build_release.py
Fixes an issue where build_release.py tries to build the mbed library for a platform with an unsupported toolchain
> Fixes toolchain filtering

- libraries/USBDevice/USBDevice/USBHAL_KL25Z.cpp
The IRQ handler calculated the endpoint number wrong when handling IN and OUT tokens.  The errant code worked by accident for endpoints 1 and 2 but was incorrect for other addresses.  For endpoints 5 and above it resulted in stray pointer read/writes that could crash the device.
> Fix interrupt handler for endpoints > 2

- libraries/USBDevice/USBDevice/USBHAL_KL25Z.cpp
realiseEndpoint() was unnecessarily allocating twice the buffer space for each endpoint buffer.  This was presumably for the sake of the hardware SIE's double-buffering (EVEN/ODD) system, but that's vestigial - this implementation doesn't use the double-buffering capability at all, leaving the ODDRST bit in the CTL register always set.  The double-size allocation is a pure waste of memory.
> Remove doubling of buffer size in realiseEndpoint()

- libraries/mbed/targets/cmsis/TARGET_NORDIC/TARGET_MCU_NRF51822/system_nrf51.c
- libraries/mbed/targets/hal/TARGET_NORDIC/TARGET_MCU_NRF51822/TARGET_TY51822R3/PinNames.h
- libraries/mbed/targets/hal/TARGET_NORDIC/TARGET_MCU_NRF51822/TARGET_TY51822R3/device.h
- workspace_tools/build_release.py
- workspace_tools/targets.py
- workspace_tools/tests.py
Added new nRF51822 platform.
```
Test summary:
+---------+-----------+-----------+-------------+---------------------------------------+--------------------+---------------+-------+
| Result  | Target    | Toolchain | Test ID     | Test Description                      | Elapsed Time (sec) | Timeout (sec) | Loops |
+---------+-----------+-----------+-------------+---------------------------------------+--------------------+---------------+-------+
| TIMEOUT | TY51822R3 | ARM       | DTCT_1      | Simple detect test                    |       80.41        |       40      |  0/1  |
| OK      | TY51822R3 | ARM       | EXAMPLE_1   | /dev/null                             |        3.46        |       20      |  1/1  |
| OK      | TY51822R3 | ARM       | MBED_10     | Hello World …
```
> [TY51822r3] add platform

- libraries/mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/serial_api.c
The fix to have serial_api deal with NC pins for either RX or TX was only partly replicated into the code for older platforms, causing MBED_37 (serial_nc_rx) to fail. This has now been fixed by condensing code so that there is less room for copy-paste failures.
Test report after fix:
Test summary:
+--------+-----------------+-----------+-------------+---------------------------------------+--------------------+---------------+-------+
| Result | Target          | Toolchain | Test ID     | Test Description                      | Elapsed Time (sec) | Timeout (sec) | Loops |
+--------+-----------------+-----------+-------------+---------------------------------------+--------------------+---------------+-------+
| OK     | EFM32GG_STK3700 | GCC_ARM   | MBED_A7     | InterruptIn …
> [Silicon Labs] Fix regression towards older platforms

- libraries/mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/i2c_api.c
Added code to the I2C implementation to allow for SCK to go up to 1MHz (up from 100kHz previously)
> [Silicon Labs] Allow faster I2C baudrates

- workspace_tools/upload_results.py
This patch introduces the idea of "Release Candidates". A build must begin as a Release Candidate, then based on the test results it can be promoted to a "Release" via the `promote-build` sub command.
> Adding Release_Canditate type and promote-build function to upload script

- libraries/mbed/targets/cmsis/TARGET_STM/TARGET_STM32F0/TARGET_DISCO_F051R8/system_stm32f0xx.c
- libraries/mbed/targets/cmsis/TARGET_STM/TARGET_STM32F0/TARGET_NUCLEO_F030R8/system_stm32f0xx.c
- libraries/mbed/targets/cmsis/TARGET_STM/TARGET_STM32F0/TARGET_NUCLEO_F031K6/system_stm32f0xx.c
- libraries/mbed/targets/cmsis/TARGET_STM/TARGET_STM32F0/TARGET_NUCLEO_F042K6/system_stm32f0xx.c
- libraries/mbed/targets/cmsis/TARGET_STM/TARGET_STM32F0/TARGET_NUCLEO_F070RB/system_stm32f0xx.c
- libraries/mbed/targets/cmsis/TARGET_STM/TARGET_STM32F0/TARGET_NUCLEO_F072RB/system_stm32f0xx.c
- libraries/mbed/targets/cmsis/TARGET_STM/TARGET_STM32F0/TARGET_NUCLEO_F091RC/system_stm32f0xx.c
STM32F0x has OSC_IN and OSC_OUT pins coupled with PF0 and PF_1.
If external oscillator is used then HSE must not be enabled. Otherwise PF0 will be occupied by RCC and can't be used as GPIO.
Current code use default values for init structure:
```CPP
uint8_t SetSysClock_PLL_HSI(void)
{
RCC_ClkInitTypeDef RCC_ClkInitStruct;
RCC_OscInitTypeDef RCC_OscInitStruct;
// Select PLLCLK = 48 MHz ((HSI 8 MHz / 2) * 12)
RCC_OscInitStruct.OscillatorType          = RCC_OSCILLATORTYPE_HSI;
RCC_OscInitStruct.HSIState                = RCC_HSI_ON;
RCC_OscInitStruct.PLL.PLLState            = RCC_PLL_ON;
RCC_OscInitStruct.PLL.PLLSource           = RCC_PLLSOURCE_HSI; // HSI div 2
RCC_OscInitStruct.PLL.PREDIV              = RCC_PREDIV_DIV2;
RCC_OscInitStruct.PLL.PLLMUL              = RCC_PLL_MUL12;
if …
```
> Fix HSI configuration for STM32F0x.

- libraries/mbed/targets/hal/TARGET_NXP/TARGET_LPC11U6X/pwmout_api.c
- libraries/mbed/targets/hal/TARGET_NXP/TARGET_LPC15XX/pwmout_api.c
Bug fixes related to issue #1510:
* Fixed period & pulse-width off-by-one errors
* Fixed 0% duty cycle output
* Improved duty cycle resolution at high frequencies
> [LPC11U68, LPC1549] Fixed PwmOut SCT Bugs

- libraries/mbed/targets/cmsis/TARGET_STM/TARGET_STM32F0/TARGET_NUCLEO_F072RB/system_stm32f0xx.c
Since we want to get a 48M PLLCLK when using HSI as resource and PLLMUL is 12 as it in current code, then we should set PREDIV to 2. If set the PREDIV to 1 as current code, the system clock is 96M.
PLLCLK = 48 MHz ((HSI 8 MHz / 2) * 12)
PLLCLK = 96 MHz ((HSI 8 MHz / 1) * 12)
> The predivider should be 2 here.

- README.md
I can remove the note about progen, and can add it with IAR progen PR which will come soon.
@sg-
> Readme - update ides, add note about progen replacement

- workspace_tools/targets.py
- workspace_tools/toolchains/__init__.py
> Mbedos macros

- workspace_tools/build_release.py
- workspace_tools/test_api.py
This adds the capability to build tests in the build_release script
You can do this by specifying a comma-separated list of directories (relative to /libraries/tests) of which tests to build.
- ex. `python build_release.py --build-tests=mbed,rtos/mbed`
This lets you build tests against all released platforms, which should make it easier to find linker errors quicker.
This is a necessary feature for CI.
> Allow building of tests in build_release script

- libraries/mbed/targets/cmsis/TARGET_STM/TARGET_STM32L4/TARGET_DISCO_L476VG/cmsis_nvic.c
- libraries/mbed/targets/cmsis/TARGET_STM/TARGET_STM32L4/TARGET_NUCLEO_L476RG/cmsis_nvic.c
Fix issue #1413
Fix issue #1509
> [STM32L4] Set NVIC_RAM_VECTOR_ADDRESS to 0x10000000

- libraries/mbed/targets/hal/TARGET_RENESAS/TARGET_RZ_A1H/PeripheralNames.h
- libraries/mbed/targets/hal/TARGET_RENESAS/TARGET_RZ_A1H/spi_api.c
This enables SPI_3 on GR-PEACH
> [Renesas RZ/A1H] Enable SPI_3 on GR-PEACH

- libraries/mbed/targets/cmsis/TARGET_STM/TARGET_STM32L4/stm32l4xx_hal_rcc.h
- libraries/mbed/targets/hal/TARGET_STM/TARGET_STM32L4/TARGET_DISCO_L476VG/device.h
- libraries/mbed/targets/hal/TARGET_STM/TARGET_STM32L4/rtc_api.c
make the RTC works properly with LSE (increase time out startup time + use HW flag) and add the possibility to use the LSI (internal clock)
> [NUCLEO_L476RG] RTC+LSE

- libraries/mbed/targets/hal/TARGET_NXP/TARGET_LPC15XX/analogin_api.c
Modified the LPC1549 AnalogIn implementation to use the ADCs in synchronous mode, which is consistent with the LPC11U68 implementation. This improves performance, and allows the IRC oscillator to be powered down if necessary.
> [LPC1549] Improve AnalogIn Performance

- libraries/mbed/hal/can_api.h
- libraries/mbed/targets/hal/TARGET_STM/TARGET_STM32F4/PeripheralPins.h
- libraries/mbed/targets/hal/TARGET_STM/TARGET_STM32F4/TARGET_B96B_F446VE/PeripheralNames.h
- libraries/mbed/targets/hal/TARGET_STM/TARGET_STM32F4/TARGET_B96B_F446VE/PeripheralPins.c
- libraries/mbed/targets/hal/TARGET_STM/TARGET_STM32F4/TARGET_B96B_F446VE/PinNames.h
- libraries/mbed/targets/hal/TARGET_STM/TARGET_STM32F4/TARGET_B96B_F446VE/device.h
- libraries/mbed/targets/hal/TARGET_STM/TARGET_STM32F4/TARGET_B96B_F446VE/objects.h
- libraries/mbed/targets/hal/TARGET_STM/TARGET_STM32F4/can_api.c
- libraries/tests/mbed/can/main.cpp
- libraries/tests/mbed/can_interrupt/main.cpp
- libraries/tests/mbed/can_loopback/main.cpp
- workspace_tools/tests.py
can_api is now supported with platform B96B_F446VE
MBED_A27 (loopback test) is passing.
can and can_interrupt tests are passing (only 1 can is available on this platform pins).
Some more tests were passed : I plugged can1 from B96B_F446VE board on another board's CAN transmitter, a non-crossed DB9 wire and another CAN-enabled STM board. 
. can loopback iteration
. can_rx
. can tx
. can Rx+Tx
. can Rx with interrupt
Cheers
> [STM B96B_F446VE] Add CAN feature

- workspace_tools/build_api.py
- workspace_tools/test_api.py
- workspace_tools/test_exporters.py
- workspace_tools/toolchains/__init__.py
- workspace_tools/toolchains/gcc.py
- workspace_tools/utils.py
This allows tests to specifically say they aren't supported on a target. This provides more info to the test suite user and to our build/CI system.
Tests that declare themselves "unsupported" should use the `#error` preprocessor directive in the following manner:
```
#if SUPPORTED
< Do the test >
#else
#error [NOT_SUPPORTED] This test is unsupported on this target
#endif
```
You must start the `#error` message with the prefix `[NOT_SUPPORTED]`. After that, you can add a meaningful message.
> Adding the ability for tests to report they aren't supported on a target

- workspace_tools/targets.py
Removes IAR support from all NRF51822-based targets.
Currently tests do not run on NRF51822 targets when compiled with IAR. The current definition of the NRF51_DK target specifically removes IAR support in its definition. This PR unifies this removal across all of these targets.
> Remove IAR from all NRF51822-based targets

- libraries/mbed/targets/cmsis/TARGET_NXP/TARGET_LPC15XX/system_LPC15xx.c
The user manual for the LPC1549 (Table 82) says the MSEL bits should be 5, and the PSEL bits should be 1, for the correct FCCO frequency of 288MHz. The current configuration has FCCO = 144MHz, which is technically out of spec (manual-specified 156MHz ~ 320MHz).
Tested on a custom LPC1549 board with crystal oscillator running at 12MHz; 72MHz operations of system clock appears to work.
> [LPC15XX] Fix Clock Configuration

- libraries/mbed/targets/hal/TARGET_RENESAS/TARGET_RZ_A1H/analogin_api.c
This fixes definitions of peripheral names in analogin_api.c
> [Renesas RZ/A1H] Fix analogin peripheral names

- workspace_tools/upload_results.py
Now uploading skipped tests that are not supported so that we can have that data for tracking purposes.
> Uploading skipped [NOT_SUPPORTED] tests

- libraries/tests/mbed/analog/main.cpp
- libraries/tests/mbed/analog_pot/main.cpp
- libraries/tests/mbed/bus/main.cpp
- libraries/tests/mbed/can/main.cpp
- libraries/tests/mbed/can_interrupt/main.cpp
- libraries/tests/mbed/can_loopback/main.cpp
- libraries/tests/mbed/dir/main.cpp
- libraries/tests/mbed/freopen/main.cpp
- libraries/tests/mbed/i2c_master/main.cpp
- libraries/tests/mbed/i2c_slave/main.cpp
- libraries/tests/mbed/interrupt_chaining/main.cpp
- libraries/tests/mbed/portout/main.cpp
- libraries/tests/mbed/pwm/main.cpp
- libraries/tests/mbed/pwm_led/pwm.cpp
- libraries/tests/mbed/reset/main.cpp
- libraries/tests/mbed/spi/main.cpp
- libraries/tests/mbed/spi_master/main.cpp
- libraries/tests/mbed/spi_slave/main.cpp
- libraries/tests/mbed/stdio_benchmark/main.cpp
Adding `[NOT_SUPPORTED]` message to tests (added by PR #1568)
> Adding NOT_SUPPORTED errors to tests

- libraries/tests/mbed/analog_in/main.cpp
- libraries/tests/mbed/interruptin/main.cpp
- libraries/tests/mbed/interruptin_2/main.cpp
- libraries/tests/mbed/portout_portin/main.cpp
- libraries/tests/mbed/rtc/main.cpp
- libraries/tests/mbed/sleep/main.cpp
- libraries/tests/mbed/sleep_timeout/main.cpp
This adds some more [NOT_SUPPORTED] errors to some tests that I missed the first time around.
> Adding more [NOT_SUPPORTED] messages to tests

- workspace_tools/export/exporters.py
mbed scripts copy files, therefore file paths are not valid at the moment of ahe project generation.
Therefore checks like os.path.isdir or isfile fail. If include is set to TARGET/FOLDER, this would be
treated as a file, and added to the project workspace. This commit fixes it, it adds dirs only to
include_paths, as it should.
If we export to IAR, there are non valid files currently, folders as a result of inc_dirs added to includes. It does not affect build, thus cosmetic error in this case.
I'll have a look at this, how progen or mbed scripts can handle this better. One possibility would be to enable include_paths to be set in progen data, as sometimes (in this case) `` includes != include_paths ``
@bridadan
> Exporter - progen include dirs fix

- libraries/mbed/targets/hal/TARGET_NXP/TARGET_LPC82X/pwmout_api.c
Bug fixes related to issue #1510:
* Fixed period & pulse-width off-by-one errors
* Fixed 0% and 100% duty cycle output
I have tested this with manual test and MBED_5: PWM test:
```
Initialize PWM on pin D9 with duty cycle: 0.75
{{success}}
{{end}}
```
> [LPC824] Fixed PwmOut SCT Bugs

- libraries/mbed/common/retarget.cpp
Fixes issue #1562 reported by @justbuchanan.
When building code with GCC-ARM / newlib, attempting to use the
b (binary) mode in a fopen() call would fail. newlib would parse
this option and pass it down to the LocalFileSystem open call which
didn't like the unexpected O_BINARY flag in openmode.
The openmode_to_posix() function in retarget.cpp would never set the
O_BINARY flag for the other toolchains but for GCC it would just pass
down whatever newlib placed there.  This commit masks out the O_BINARY
bit so that it never gets passed down to the file system drivers, just
as occurs for the other supported toolchains.
Test case:
FILE *fp = fopen("/local/out.txt", "rb");
I tested that code on mbed LPC1768 and LPC11U24 boards while using
GCC_ARM as the toolchain. It failed on both platforms …
> LocalFileSystem fails to open binary files

- requirements.txt
- setup.py
Adds a few missing dependencies to requirements.txt and setup.py
> Adding missing dependencies

- libraries/mbed/common/retarget.cpp
My previous commit, c6d2c81, broke Keil builds and maybe even IAR.
I need to learn how to read C code :)  I thought I was masking off the
O_BINARY bit only for GCC builds but it turns out that my update was
in the fall-through case for all toolchains.  This commit now places
the O_BINARY masking operation into a GCC specific #ifdef clause.
Testing:
I tested the same fopen("/local/out.txt","rb") code as before but this
time I built it with the online compiler and GCC_ARM. I tested the
resulting binaries on mbed-LPC11U24 and mbed-LPC1768 boards.
Thanks to @neilt6 for catching & reporting this!
> Fix issue #1599

- libraries/mbed/targets/hal/TARGET_STM/TARGET_STM32F3/analogin_api.c
When two or more analogue inputs are initialized on more than one ADC HW block the initialisation fails with:
Cannot initialize ADC
The reason is the reusage of just one ADC_HandleTypeDef for all initializations (in mbed\targets\hal\TARGET_STM\TARGET_STM32F3\analogin_api.c). After the first (successful) ADC initialisation AdcHandle.State is set to HAL_ADC_STATE_READY).
But for the next ADC block initialisation the AdcHandle.State has to be reset so that the HAL initializes it (in mbed\targets\cmsis\TARGET_STM\TARGET_STM32F3\stm32f3xx_hal_adc_ex.c line 424). When this state is not reset the HAL returns with an initialization error. And this error induces the above mbed error message.
The error message can be reproduced just with AnalogIn in1(xx); AnalogIn in2(yy); where xx and yy belongs …
> [STM32F3xx] bug fix multiple ADC channels using multiple ADC blocks

- workspace_tools/targets.py
- workspace_tools/toolchains/iar.py
**targets.py** : add IAR for NUCLEO_F746ZG and DISCO_F746NG
**iar.py:** in case of Cortex-M7F, change it into Cortex-M7 and add --fpu VFPv5_sp
I have been confirmed that for Cortex-M4F we don't need to add the --fpu VFPv4_sp
**test results**
DTCT_1 EXAMPLE_1 MBED_10 MBED_11 MBED_12 MBED_16        MBED_2  MBED_23 MBED_24 MBED_25 MBED_26 MBED_34 MBED_37 MBED_38 MBED_A1 MBED_A21 MBED_A9 MBED_BUSOUT RTOS_1        RTOS_2        RTOS_3        RTOS_4        RTOS_5        RTOS_6        RTOS_7       RTOS_8 
ARM DISCO_F746NG     OK     OK        OK      OK      OK      NOT_SUPPORTED  OK      OK      OK      OK      OK      OK      OK      OK      OK      OK       OK      OK          OK            OK            OK            OK            OK            OK            OK           OK
GCC_ARM …
> [STM32F7] Allow IAR compilation

- libraries/mbed/targets/hal/TARGET_NXP/TARGET_LPC176X/TARGET_XBED_LPC1768/PinNames.h
The platform XBED_LPC1768 doesn't have mbed interface. It needs the DIPDAP as interface for automaticed testing, using DIP25 and DIP26 as UART RX/TX.
> Change the uart pin to DIP pin for XBED_LPC1768

- libraries/tests/mbed/analog/main.cpp
- libraries/tests/mbed/analog_pot/main.cpp
- libraries/tests/mbed/can/main.cpp
- libraries/tests/mbed/can_interrupt/main.cpp
- libraries/tests/mbed/can_loopback/main.cpp
- libraries/tests/mbed/dir/main.cpp
- libraries/tests/mbed/freopen/main.cpp
- libraries/tests/mbed/i2c_master/main.cpp
- libraries/tests/mbed/i2c_slave/main.cpp
- libraries/tests/mbed/interruptin/main.cpp
- libraries/tests/mbed/interruptin_2/main.cpp
- libraries/tests/mbed/portout/main.cpp
- libraries/tests/mbed/portout_portin/main.cpp
- libraries/tests/mbed/reset/main.cpp
- libraries/tests/mbed/rtc/main.cpp
- libraries/tests/mbed/sleep/main.cpp
- libraries/tests/mbed/sleep_timeout/main.cpp
- libraries/tests/mbed/spi_master/main.cpp
- libraries/tests/mbed/spi_slave/main.cpp
- libraries/tests/mbed/stdio_benchmark/main.cpp
> Fixing issue with NOT_SUPPORTED messages

- libraries/mbed/targets/hal/TARGET_STM/TARGET_STM32F4/serial_api.c
Fixes #1605 
Applications may encounter situations where UARTx->SR & ORE is true but UARTx->SR & RXNE is not true. If this occurs when a RX interrupt handler is attached, the device will get stuck in a loop executing the serial irq handler. This is because the ORE flag can trigger the RXNE interrupt as well as the RXNE flag.
> avoid getting stuck in serial IRQ if ORE is set without RXNE

- libraries/net/lwip/lwip/lwipopts.h
UDP based protocols such as DTLS may fragment large packets, resulting in many packets being sent at once. This can lead to significant/irrecoverable packet loss on systems that respond to packets slower than network transfers.
Increasing MEMP_NUM_NETBUF to 8 allows lwip to handle a DTLS handshake successfully and should be more robust for similar protocols.
DTLS handshake:
https://tools.ietf.org/html/rfc4347#section-4.2.3
> Increased allocated netbufs to handle DTLS handshakes

- libraries/rtos/rtos/Thread.cpp
- libraries/rtos/rtos/Thread.h
- libraries/rtos/rtos/rtos_idle.c
- libraries/rtos/rtos/rtos_idle.h
- libraries/rtos/rtx/TARGET_ARM7/RTX_Conf_CM.c
- libraries/rtos/rtx/TARGET_CORTEX_A/RTX_Conf_CA.c
- libraries/rtos/rtx/TARGET_CORTEX_M/RTX_Conf_CM.c
Added a new API for attaching an idle hook to be executed by the idle task. This will allow developers to add custom logic to the idle task (e.g. to call `sleep()`) without modifying the library code.
_Updated version of #1463._
> [RTOS] Added idle hook API

- libraries/mbed/targets/hal/TARGET_STM/TARGET_STM32F4/TARGET_ARCH_MAX/device.h
- libraries/mbed/targets/hal/TARGET_STM/TARGET_STM32F4/TARGET_B96B_F446VE/device.h
- libraries/mbed/targets/hal/TARGET_STM/TARGET_STM32F4/TARGET_DISCO_F401VC/device.h
- libraries/mbed/targets/hal/TARGET_STM/TARGET_STM32F4/TARGET_DISCO_F407VG/device.h
- libraries/mbed/targets/hal/TARGET_STM/TARGET_STM32F4/TARGET_DISCO_F429ZI/device.h
- libraries/mbed/targets/hal/TARGET_STM/TARGET_STM32F4/TARGET_DISCO_F469NI/device.h
- libraries/mbed/targets/hal/TARGET_STM/TARGET_STM32F4/TARGET_ELMO_F411RE/device.h
- libraries/mbed/targets/hal/TARGET_STM/TARGET_STM32F4/TARGET_MTS_DRAGONFLY_F411RE/device.h
- libraries/mbed/targets/hal/TARGET_STM/TARGET_STM32F4/TARGET_MTS_MDOT_F405RG/device.h
- libraries/mbed/targets/hal/TARGET_STM/TARGET_STM32F4/TARGET_MTS_MDOT_F411RE/device.h
- libraries/mbed/targets/hal/TARGET_STM/TARGET_STM32F4/TARGET_NUCLEO_F401RE/device.h
- libraries/mbed/targets/hal/TARGET_STM/TARGET_STM32F4/TARGET_NUCLEO_F410RB/device.h
- libraries/mbed/targets/hal/TARGET_STM/TARGET_STM32F4/TARGET_NUCLEO_F411RE/device.h
- libraries/mbed/targets/hal/TARGET_STM/TARGET_STM32F4/TARGET_UBLOX_C029/device.h
Added for clarity.
This flag must be set to 1 if the LSE xtal is not
present on the board or if the RTC must be clocked by the device internal clock.
Continuation of PR #1548 and #1558
> [STM32F4] Add DEVICE_RTC_LSI=0 to all targets

- libraries/mbed/targets/hal/TARGET_STM/TARGET_STM32F4/serial_api.c
This is resolution of #1586
UART_IT_TC was enabled instead of UART_IT_TXE
This was causing an issue because UART_IT_TXE (and not UART_IT_TC) was disabled  by same function.
Consequently if a transfer was ongoing when serial_irq_set() was called to disable IRQ, UART_IT_TC would still trigger (once).
Side effect is maybe speed: I guess using UART_IT_TC prevented implementation of continuous transfer.
This commit is focused on solving an issue observed with TARGET_STM32F4. It doesn't presume it should or shouldn't be done for other targets.
> Fix IRQ enabled in serial_irq_set()

- libraries/mbed/targets/cmsis/TARGET_STM/TARGET_STM32F4/TARGET_MTS_DRAGONFLY_F411RE/system_stm32f4xx.c
- libraries/mbed/targets/cmsis/TARGET_STM/TARGET_STM32F4/TARGET_MTS_MDOT_F411RE/system_stm32f4xx.c
Since MTS products can be deployed and are expected to stay up and running indefinitely, reset the device if a fault is encountered instead of sitting in a while(1); loop.
> add hard fault handlers for MultiTech mDot and Dragonfly platforms

- libraries/mbed/targets/cmsis/TARGET_Freescale/TARGET_KLXX/TARGET_KL05Z/system_MKL05Z4.c
Add a delay after switching to the FEE clock mode so the FLL has a
chance to acquire a better lock.  This fixes a bug where the first byte
sent over the UART is corrupt.
> Prevent KL05 from using an unstable clock

- workspace_tools/export/uvision4.py
Tested with RTOS_1 example which failed with strange error which pinpointed that something with ``MBED_USERNAME=``
I'll try to get some answers for this asm macros behavior for uvision4.
> uvision exporter - fix - asm does not like string defined macros

- libraries/mbed/targets/cmsis/TARGET_STM/TARGET_STM32L4/TARGET_DISCO_L476VG/TOOLCHAIN_ARM_MICRO/startup_stm32l476xx.s
- libraries/mbed/targets/cmsis/TARGET_STM/TARGET_STM32L4/TARGET_DISCO_L476VG/cmsis_nvic.c
- libraries/mbed/targets/cmsis/TARGET_STM/TARGET_STM32L4/TARGET_NUCLEO_L476RG/TOOLCHAIN_ARM_MICRO/startup_stm32l476xx.s
- libraries/mbed/targets/cmsis/TARGET_STM/TARGET_STM32L4/TARGET_NUCLEO_L476RG/cmsis_nvic.c
> [STM32L4] Update ARM_MICRO startup files

- libraries/rpc/parse_pins.cpp
RPC won't compile otherwise. Pin naming format seems consistent with the other Nucleo targets, and `/DigitalOut/new ...` works on my board.
> Add Nucleo F303K8 pin parsing for RPC

- libraries/mbed/targets/cmsis/TARGET_STM/TARGET_STM32F3/TARGET_NUCLEO_F303K8/cmsis_nvic.h
Fix for #1631 
The linker scripts allocate 0x188 bytes of SRAM, but for 101 vectors, it really needs 0x194 bytes. This causes the NVIC initialization to clobber the beginning the the data section, leading to all kinds of fun like the heap pointer getting clobbered and crashing when attempting to create a Serial object.
I'm not convinced that 98 vectors is actually correct, but it seems consistently used in all the F303K8 linker scripts. And it allows Serial to initialize properly as well, too.
The STM32F3 reference (http://www.st.com/web/en/resource/technical/document/programming_manual/DM00046982.pdf section 4.3) says the NVIC supports up to 81 interrupts.
The STM32F303X6/8 reference (http://www.st.com/st-web-ui/static/active/en/resource/technical/document/datasheet/DM00092070.pdf …
> Make Nucleo F303K8 number of interrupts consistent with amount of SRAM allocated

- libraries/mbed/targets/cmsis/TARGET_STM/TARGET_STM32L1/TARGET_MOTE_L152RC/stm32l1xx_hal_conf.h
- libraries/mbed/targets/cmsis/TARGET_STM/TARGET_STM32L1/TARGET_NUCLEO_L152RE/stm32l1xx_hal_conf.h
- libraries/mbed/targets/cmsis/TARGET_STM/TARGET_STM32L1/TARGET_NZ32_SC151/stm32l1xx_hal_conf.h
- libraries/mbed/targets/hal/TARGET_STM/TARGET_STM32F4/rtc_api.c
- libraries/mbed/targets/hal/TARGET_STM/TARGET_STM32L1/TARGET_MOTE_L152RC/device.h
- libraries/mbed/targets/hal/TARGET_STM/TARGET_STM32L1/TARGET_NUCLEO_L152RE/device.h
- libraries/mbed/targets/hal/TARGET_STM/TARGET_STM32L1/TARGET_NZ32_SC151/device.h
- libraries/mbed/targets/hal/TARGET_STM/TARGET_STM32L1/rtc_api.c
the erasing of back up registers is only needed when using LSI in RTC API
> [XXX_F4XX] remove erasing of BkUpR in RTC API

- libraries/mbed/targets/cmsis/TARGET_STM/TARGET_STM32L1/TARGET_MOTE_L152RC/stm32l1xx_hal_conf.h
- libraries/mbed/targets/cmsis/TARGET_STM/TARGET_STM32L1/TARGET_NUCLEO_L152RE/stm32l1xx_hal_conf.h
- libraries/mbed/targets/cmsis/TARGET_STM/TARGET_STM32L1/TARGET_NZ32_SC151/stm32l1xx_hal_conf.h
- libraries/mbed/targets/hal/TARGET_STM/TARGET_STM32L1/TARGET_MOTE_L152RC/device.h
- libraries/mbed/targets/hal/TARGET_STM/TARGET_STM32L1/TARGET_NUCLEO_L152RE/device.h
- libraries/mbed/targets/hal/TARGET_STM/TARGET_STM32L1/TARGET_NZ32_SC151/device.h
- libraries/mbed/targets/hal/TARGET_STM/TARGET_STM32L1/rtc_api.c
- libraries/mbed/targets/hal/TARGET_STM/TARGET_STM32L4/rtc_api.c
The erasing of back up registers is needed only when using RTC+LSI
> [XXX_L476XG] remove erasing of BkUpR in RTC API

- libraries/mbed/targets/cmsis/TARGET_STM/TARGET_STM32L1/TARGET_MOTE_L152RC/stm32l1xx_hal_conf.h
- libraries/mbed/targets/cmsis/TARGET_STM/TARGET_STM32L1/TARGET_NUCLEO_L152RE/stm32l1xx_hal_conf.h
- libraries/mbed/targets/cmsis/TARGET_STM/TARGET_STM32L1/TARGET_NZ32_SC151/stm32l1xx_hal_conf.h
- libraries/mbed/targets/hal/TARGET_STM/TARGET_STM32F7/TARGET_DISCO_F746NG/device.h
- libraries/mbed/targets/hal/TARGET_STM/TARGET_STM32F7/TARGET_NUCLEO_F746ZG/device.h
- libraries/mbed/targets/hal/TARGET_STM/TARGET_STM32F7/rtc_api.c
- libraries/mbed/targets/hal/TARGET_STM/TARGET_STM32L1/TARGET_MOTE_L152RC/device.h
- libraries/mbed/targets/hal/TARGET_STM/TARGET_STM32L1/TARGET_NUCLEO_L152RE/device.h
- libraries/mbed/targets/hal/TARGET_STM/TARGET_STM32L1/TARGET_NZ32_SC151/device.h
- libraries/mbed/targets/hal/TARGET_STM/TARGET_STM32L1/rtc_api.c
add a define to choose between LSE and LSI
> [xxx_F746XG] enhance RTC api

- libraries/mbed/targets/hal/TARGET_Freescale/TARGET_KPSDK_MCUS/us_ticker.c
When a ticker is scheduled to run so fast that it is pending again
before the previous event has been processed then this next event
is processed (recursively) by calling into us_ticker_irq_handle().
This can lead to a stack overflow.
This patch prevents this recursion by replacing the call to
us_ticker_irq_handler() with a call to set the interrupt to pending
again.  This allows the next timer event to be processed without
making the stack deeper.
> Prevent recursive processing of us_ticker in FSL

- libraries/mbed/targets/hal/TARGET_STM/TARGET_STM32L0/rtc_api.c
The erasing of back up register is needed only when using LSI in RTC API
> [XXX_L0X3XX] Move erasing of BkUpR in RTC API

- libraries/mbed/targets/hal/TARGET_STM/TARGET_STM32L1/rtc_api.c
the erasing of back up register is only needed when using LSI
> [XXX_L15XX] Move erasing of BkUpR in RTC API

- libraries/mbed/targets/hal/TARGET_STM/TARGET_STM32F7/rtc_api.c
The erasing of back up register is only needed when using LSI in RTC API
> [XXX_F746XG] Move erasing of BkUpR in RTC API

- workspace_tools/export/__init__.py
Adding readme with exporters information. What should be the format ? Should it be json, yaml or just simple text file with predefined format.
Current format in exporter.txt:
```
project_generator = true/false # if progen is used
project_generator version = x.x.x
```
Should fix #1617. For more info about getting the module version: http://python-packaging-user-guide.readthedocs.org/en/latest/single_source_version/
@bridadan @sg-
> Export - add readme with exporters information

- requirements.txt
- setup.py
add pyYAML as dependency, exporters require it. Should be part of the earlier PR (#1636)
@bridadan
> pyYAML is req for exporters

- libraries/mbed/targets/hal/TARGET_NXP/TARGET_LPC81X/pwmout_api.c
Bug fixes related to issue #1510:
* Fixed 0% duty cycle output
* Fixed pulse width 0 output
* Remove unused comment-out code
* Correct cast type for GCC toolchain
* The new PWM period now update existing PWM channels, so duty cycle is kept
I have tested this with manual test and MBED_5: PWM test:
```
Initialize PWM on pin D9 with duty cycle: 0.75
{{success}}
{{end}}
```
> [LPC812] Fixed PwmOut SCT bugs

- libraries/rpc/rpc.cpp
The RPC call appended the method name to the output after the method
had already finished processing. It was unexpected for my use case,
and doesn't feel like the obvious thing to do.  This could be appended
in the RPC method itself, instead.
The adding of the method to the output was first commited in commit
556b889b5ff64126eb430aa8326e8bce0b451100.
> Removing the appending of the method name to an RPC call

- libraries/mbed/targets/hal/TARGET_Freescale/TARGET_KPSDK_MCUS/TARGET_MCU_K64F/TARGET_FRDM/PeripheralPins.c
PTC6 was wrong, should be PTD6
> Fix incorrect pin in PinMap_UART_RX - issue mbedmicro/mbed#1657

- workspace_tools/targets.py
There is missing the exporters for Keil and IAR. I hope that will solve this issue. Otherwise tell me what is missing.
> [DISCO_F429ZI] Add target name for progen

- workspace_tools/export/__init__.py
- workspace_tools/export/uvision5.py
uvision5 uses software packs for devices, plus different extension. We
should use uvision as uvision4. This is based on progen, same as uvision4.
At the moment it does not differ, I can merge uvision4 and 5 together into one file and reuse most of the code. suggestions?
@sg- @bridadan
> Exporters - uvision5 addition

- workspace_tools/export/uvision4.py
uvision uses default_toolchain, thus exporter needs to provide a method to
distinguish between ARM and uARM. Fixes #1686 
@toyowata Please test. I tested this with KL05 (uARM) and KL25Z (ARM) if proper toolchain is set
> uvision - get_toolchain method regression fix

- libraries/mbed/targets/cmsis/TARGET_ARM_SSG/TARGET_MPS2_M7/CMSDK_CM7.h
In online compiler (developer.mbed.org) generated following error when build target is ARM_MPS2_M7.
```
Error: Cannot open source input file "core_CM7.h": No such file or directory in "extras/mbed_082adc85693f/TARGET_ARM_MPS2_M7/CMSDK_CM7.h", Line: 112, Col: 101
```
This was because CMSDK_CM7.h included "core_CM7.h" and this should be "core_cm7.h".
This is now fixed.
> [ARM_MPS2_M7] Fix capital letter filename

- workspace_tools/export/uvision5.py
same solution as in PR #1687 but for Keil v5
I tested it with blinky and Nucleo_F042 and it works well after the patch.
> uvision5 - get_toolchain method

- libraries/mbed/targets/hal/TARGET_STM/TARGET_STM32F4/mbed_overrides.c
- libraries/mbed/targets/hal/TARGET_STM/TARGET_STM32F7/mbed_overrides.c
The weak function HAL_Delay is overwritten to use mbed function
'wait_ms'.
Thanks to this, the user can use stm32f[4/7]xx_hal_sd.c that calls
HAL_Delay
This will allow us to add an example detecting / writing / reading an SD
card on DISCO_F469NI and DISCO_F746NG
(cherry picked from commit d491e3cd8b1d973793e6168a5037a812eadea961)
> [STM32F4 STM32F7] Overwrite HAL_Delay to allow SD example

- libraries/mbed/hal/i2c_api.h
Fixes #1670. This follows the C++ i2c int write(int data) method, plus the implementations for nxp 1768 has it as it is with this correction, thus we can assume that's the intentional behavior. The documentation was added the last year, and was mapping some of the targets (I personally haven't noticed this).
We will add tests to get this right , we will need to fix the implementations.
@sg- @kgills
> i2c - fix return value description i2c_byte_write()

- libraries/mbed/api/CThunk.h
- libraries/mbed/common/SPI.cpp
- libraries/mbed/targets/cmsis/TARGET_RENESAS/TARGET_RZ_A1H/MBRZA1H.h
- libraries/mbed/targets/cmsis/TARGET_RENESAS/TARGET_RZ_A1H/mmu_Renesas_RZ_A1.c
- libraries/mbed/targets/hal/TARGET_RENESAS/TARGET_RZ_A1H/device.h
- libraries/mbed/targets/hal/TARGET_RENESAS/TARGET_RZ_A1H/i2c_api.c
- libraries/mbed/targets/hal/TARGET_RENESAS/TARGET_RZ_A1H/objects.h
- libraries/mbed/targets/hal/TARGET_RENESAS/TARGET_RZ_A1H/serial_api.c
- libraries/mbed/targets/hal/TARGET_RENESAS/TARGET_RZ_A1H/spi_api.c
- libraries/tests/utest/i2c_eeprom_asynch/i2c_eeprom_asynch.cpp
- libraries/tests/utest/serial_asynch/serial_asynch.cpp
- libraries/tests/utest/spi_asynch/spi_master_asynch.cpp
This enables asynchronous communications.
> [Renesas RZ/A1H] Enable asynchronous communications

- libraries/mbed/targets/hal/TARGET_STM/TARGET_STM32L0/TARGET_NUCLEO_L031K6/PinNames.h
To be more consistent with other 32 pins Nucleo targets, such as NUCLEO_F031K6 and NUCLEO_F042K6. And also to avoid collision with the led.
> [NUCLEO_L031K6] Change the default pwm pin

- libraries/rtos/rtx/TARGET_ARM7/ARM7/TOOLCHAIN_GCC/HAL_CM0.S
Simple typo fix "starck" -> "stack"
> Typo fix in HAL_CM0.S of ARM7 rtx

- workspace_tools/export/uvision4.py
- workspace_tools/toolchains/arm.py
This enables to get toolchain flags by exporters and should match 1:1 from what is used by scripts. It contains c/asm/cxx/ld/common flags.
@sg- @bridadan
> Flags unification for uvision

- workspace_tools/toolchains/arm.py
Some flags are only C specific, causes problems when there's .S file in the workspace.
For instance, -Ox is only C flag, causes a project to fail with "unrecognized option"
Tested with k64f, rtos 1 and busout examples
> uvision - fix c/asm flags

- libraries/mbed/targets/hal/TARGET_STM/TARGET_STM32F3/TARGET_DISCO_F303VC/objects.h
- libraries/mbed/targets/hal/TARGET_STM/TARGET_STM32F3/TARGET_DISCO_F334C8/objects.h
- libraries/mbed/targets/hal/TARGET_STM/TARGET_STM32F3/TARGET_NUCLEO_F302R8/objects.h
- libraries/mbed/targets/hal/TARGET_STM/TARGET_STM32F3/TARGET_NUCLEO_F303K8/objects.h
- libraries/mbed/targets/hal/TARGET_STM/TARGET_STM32F3/TARGET_NUCLEO_F303RE/objects.h
- libraries/mbed/targets/hal/TARGET_STM/TARGET_STM32F3/TARGET_NUCLEO_F334R8/objects.h
- libraries/mbed/targets/hal/TARGET_STM/TARGET_STM32F3/pwmout_api.c
- libraries/tests/mbed/pwm/main.cpp
The pull request contains:
a fix on STM32F3 family for supporting wider PWM period ranges
a simple change to the PWM test to offer easier testing of increased periods
> Fix pwmout

- libraries/rtos/rtx/TARGET_CORTEX_M/RTX_Conf_CM.c
Added error message to sysThreadError(), and improved os_error().
> [RTOS] Improved Error Functions

- libraries/rtos/rtx/TARGET_CORTEX_M/cmsis_os.h
- libraries/rtos/rtx/TARGET_CORTEX_M/rt_CMSIS.c
- libraries/rtos/rtx/TARGET_CORTEX_M/rt_Task.h
- libraries/rtos/rtx/TARGET_CORTEX_M/rt_Timer.c
- workspace_tools/toolchains/__init__.py
2 new macros were introduced to capture changes in the kernel. We used toolchains/__init__
script to capture those, which is not in the sync with actual sources. This fix introduces
those macros in the source, rather than a script.
We will further eliminate those macros to be used outside of RTX kernel (c++ API).
@sg- @neilt6
> RTOS - fix Cortex-M version - add macros required for new kernel

- workspace_tools/export/gcc_arm_common.tmpl
- workspace_tools/toolchains/gcc.py
This fixes problem we have seen with rtos_idle_loop. The symbols
was not resolved as order played a role in this case.
Before the patch ``-lmbed -lrtos -lrtx -leth -lstdc++ -lsupc++ -lm -lc -lgcc -lnosys -lmbed -lrtos -lrtx -leth -lstdc++ -lsupc++ -lm -lc -lgcc -lnosys``
After the patch ``-Wl,--start-group -lmbed -lrtos -lrtx -leth -lstdc++ -lsupc++ -lm -lc -lgcc -lnosys -Wl,--end-group``
@neilt6 Fixes the problem with rtos_idle_loop.
@adamgreen @sg- @TomoYamanaka
> gcc - use group for ld to resolve symbols from libraries

- libraries/mbed/targets/cmsis/TARGET_STM/TARGET_STM32L4/TARGET_DISCO_L476VG/TOOLCHAIN_IAR/stm32l476xx.icf
For some reason STACKHEAP block was placed in SRAM2 section which lead to
*Error[Lp011]: section placement failed - unable to allocate space for sections/
block* error. This patch modifies the STM32L4 linker script and places STACKHEAP
into SRAM1 section which was previously unused.
Change-Id: Ibe6ca52a9fe7af232a3eade2f6b1f2ce28c9bd49
> [STM32L4] Fix IAR section placement failed error

- libraries/mbed/targets/hal/TARGET_STM/TARGET_STM32F4/can_api.c
There are 28 filter banks which are shared between CAN1 and CAN2. By default
they are divided in half:
* CAN1 -> 0  ... 13
* CAN2 -> 14 ... 27
that's why we need to decide which filter number has to be chosen.
> [STM32F4 family] Assign CAN filter number properly

- libraries/mbed/targets/cmsis/TARGET_STM/TARGET_STM32L4/TARGET_DISCO_L476VG/TOOLCHAIN_ARM_MICRO/startup_stm32l476xx.s
- libraries/mbed/targets/cmsis/TARGET_STM/TARGET_STM32L4/TARGET_NUCLEO_L476RG/TOOLCHAIN_ARM_MICRO/startup_stm32l476xx.s
The heap size was wrong for the mbed MICRO online builds. This should fix it. 
L4 Nucleo and Disco versions.
BTW: The HAL libraries are outdated, the latest versions are month ahead.
> Changed the heap size to the correct MCU heap size for SRAM1

- workspace_tools/targets.py
The extra_labels should not be removed, as it could break old sources or
mbed-lib or applications.
@screamerbg @sg-
> Target - backward compatibility KSDK 1.0 labels

- libraries/mbed/targets/hal/TARGET_STM/TARGET_STM32F7/analogin_api.c
The status of the ADC after a conversion is `HAL_ADC_STATE_EOC_REG | HAL_ADC_STATE_READY`, so the function return zero.
> [STM32F7] Fix end of conversion

- libraries/mbed/targets/hal/TARGET_STM/TARGET_STM32F1/serial_api.c
- libraries/mbed/targets/hal/TARGET_STM/TARGET_STM32F4/serial_api.c
The transmit data register needs to be flushed at the initialisation of the uart.
In case previous transmission was interrupted by a uart init, uart may contain a char that will be transmitted at the next start.
This is the case in MBED_37 test (serial_auto_nc_rx).
The MCU is writting {{start}}\n
At the moment of the \n the main program is handling 'new serial'. The next time the main program is handling a printf, the previous \n is
still present in the uart->DR register and is transmitted.
This cannot happen anymore with this commit
> [STM32F1 F4] Fix #1705 MBED_37

- libraries/mbed/targets/hal/TARGET_STM/TARGET_STM32F4/can_api.c
CAN bus opperates on APB1 peripheral clock due to that we need to get PCLK1 freq
in *can_frequency()* function to properly calculate CAN speed and reconfigure
BS1, BS2, SJW bits.
Also to fully communicate with other ST platform we set the initical CAN
frequency to 100kb/s to be able to work with the slowest platform which supports
CAN, which is NUCLEO_F303K8 (APB1 is 32MHz).
========
CAN2 interrupt index was wrong leading to not properly registering interrupt.
Having this fix allow us to pass MBED_30 test.
> [STM32F4] Clock and interrupt fixes

- libraries/mbed/targets/cmsis/TARGET_RENESAS/TARGET_RZ_A1H/TOOLCHAIN_IAR/MBRZA1H.icf
Hi
We changed the sequence of ROM section to "<ro code> <ro data>" when compiled with the IAR.
Regards,
Yamanaka
> Change the sequence of the ROM section in IAR compile

- libraries/rtos/rtos/Thread.cpp
Hi
https://github.com/mbedmicro/mbed/pull/1702
In this PR, rtx has updated, the macro into the code were changed.
However, by this macro, the process of task generation in Cortex-A9 can no longer be run.
So, we solve the task generation problem by changing the macro into Tread.cpp again.
Regards,
Yamanaka
> Fixed a problem that can not be the task generation in Cortex-A9.

- libraries/mbed/targets/hal/TARGET_Freescale/TARGET_KSDK2_MCUS/TARGET_K22F/drivers/fsl_ftm.c
- libraries/mbed/targets/hal/TARGET_Freescale/TARGET_KSDK2_MCUS/TARGET_K22F/drivers/fsl_ftm.h
- libraries/mbed/targets/hal/TARGET_Freescale/TARGET_KSDK2_MCUS/TARGET_K64F/drivers/fsl_ftm.c
- libraries/mbed/targets/hal/TARGET_Freescale/TARGET_KSDK2_MCUS/TARGET_K64F/drivers/fsl_ftm.h
- libraries/mbed/targets/hal/TARGET_Freescale/TARGET_KSDK2_MCUS/TARGET_KL27Z/drivers/fsl_tpm.c
- libraries/mbed/targets/hal/TARGET_Freescale/TARGET_KSDK2_MCUS/TARGET_KL27Z/drivers/fsl_tpm.h
The latest SDK drivers for FTM & TPM has the fix for this issue
This fixes issues seen when running FTM and TPM demos in certain modes
> Fix for Issue#1740. 

- hal/api/semihost_api.h
- rtos/rtx/TARGET_ARM7/RTX_CM_lib.h
- rtos/rtx/TARGET_CORTEX_A/RTX_CM_lib.h
- rtos/rtx/TARGET_CORTEX_M/RTX_CM_lib.h
This is an update to RTX kernel to allow c++ libc array init to be called after kernel start.
This is done for Cortex-M RTX version. I'll add Cortex-A and ARM7 alignment to the codebase within this pull request.
For instance, the Thread object in the global scope should work with this patch:
```
#include "rtos.h"
DigitalOut led1(LED1);
DigitalOut led2(LED2);
Thread thread(led2_thread);
void led2_thread(void const *args) 
{
while (true) {
led2 = !led2;
Thread::wait(1000);
}
}
int main() 
{  
while (true) {
led1 = !led1;
Thread::wait(500);
}
}
```
@sg- @c1728p9 @adamgreen @neilt6 @TomoYamanaka
> RTX - init sequence (C++ array init)

- libraries/rtos/rtx/TARGET_CORTEX_A/rt_CMSIS.c
- libraries/rtos/rtx/TARGET_CORTEX_M/rt_CMSIS.c
Fixed regression that caused terminated threads to return an erroneous state value instead of "inactive".
> [RTOS] Fixed osThreadGetState()

- libraries/mbed/targets/cmsis/TARGET_STM/TARGET_STM32L0/TARGET_NUCLEO_L053R8/hal_tick.c
- libraries/mbed/targets/hal/TARGET_STM/TARGET_STM32L0/us_ticker.c
NUCLEO_L053R8 is using a 16 bit timer as a internal ticker but the mBed ticker
needs a 32 bit timer, so the upper part of that timer is being calculated in
software. Continuous HIGH/LOW voltage levels were observed for 65ms due to timer
overflow, so to narrow down the issue, it was decided to switch to 16 bit values
and glue them to get a 32 bit timer.
> [NUCLEO_L053R8] Fix issue #816

- libraries/mbed/targets/hal/TARGET_NXP/TARGET_LPC81X/pwmout_api.c
* Use conflict resolution register to set/clear output
* See #1757 more detail
> [LPC812] Fix PwmOut conflict issue

- hal/targets/cmsis/TARGET_STM/TARGET_STM32F0/TARGET_NUCLEO_F030R8/hal_tick.c
- hal/targets/cmsis/TARGET_STM/TARGET_STM32F0/TARGET_NUCLEO_F070RB/hal_tick.c
- hal/targets/cmsis/TARGET_STM/TARGET_STM32F1/TARGET_DISCO_F100RB/hal_tick.c
- hal/targets/hal/TARGET_STM/TARGET_STM32F0/us_ticker.c
- hal/targets/hal/TARGET_STM/TARGET_STM32F1/us_ticker.c
This pull request fixes issue [#816](https://github.com/mbedmicro/mbed/issues/816) plus it changes the previously implemented 16-bit timer for F0xx family.
> Fix timer #816 issue for STM32F0 and STM32F1

- libraries/mbed/targets/cmsis/core_caFunc.h
- libraries/mbed/targets/hal/TARGET_RENESAS/TARGET_RZ_A1H/serial_api.c
Hi,
In Isuues 1726, We fixed bug of Serial in IAR complie.
We modified so as to have <CODE>#if defined ( &#95;&#95;ICCARM&#95;&#95; ) </CODE> definition as well.
https://github.com/mbedmicro/mbed/issues/1726
Regards,
Yamanaka
> Bug fix of Serial in IAR compile

- docs/mbed_targets.md
- workspace_tools/targets.json
- workspace_tools/targets.py
(long commit message ahead. Sorry about that, it can't be helped.)
This commit changs targets definition from Python to JSON format, as
part of the configuration mechanism implementation. There is a new file
under workspace_tools/ called "targets.json" which contains the target
definitions. "targets.py" remains, but becomes a wrapper on top of
"targets.json", with the same interface as before. This has the
advantage of not requiring code changes outside "targets.py".
Most of the JSON definitions of targets were automatically generated by a
script (available upon request since it doesn't make a lot of sense to
include it here), only those targets that had more than one parent in
the Python implementation were converted by hand. The target definitions
should be pretty self-explanatory. A …
> Moved target definitions to JSON format

- workspace_tools/settings.py
- workspace_tools/tests.py
- uploading results supports larger runs
- update to default toolchain paths
- correct endless loop when using specific include paths
- Dont filter tests by platform, run on all
> Updates for CI

- hal/api/CAN.h
- hal/api/CallChain.h
- hal/api/Callback.h
- hal/api/FunctionPointer.h
- hal/api/InterruptIn.h
- hal/api/SerialBase.h
- hal/api/Ticker.h
- hal/api/mbed.h
- hal/api/toolchain.h
- hal/common/CAN.cpp
- hal/common/CallChain.cpp
- hal/common/InterruptIn.cpp
- hal/common/InterruptManager.cpp
- hal/common/SerialBase.cpp
original message from @geky:
1. Currently the existing APIs are difficult to work through when composing classes with callbacks. Currently function pointers must be duplicated to pass through callback APIs. This level of indirection needs to be duplicated across any classes that pass callbacks.
2. The callback interface is currently not standardized. This is notable in differences between APIs such as Ticker and Thread. The current FunctionPointer does not support the existing callback types and can’t be standardized as is. Additionally this has resulted in FunctionPointer being duplicated across the developer site ([example](https://developer.mbed.org/users/AjK/code/FPointer/)).
3. FunctionPointer is not forward compatible with C++11. Even if we hold off for now, eventually compatibility …
> mv #1783(Improve FunctionPointer class) + minor compatibility fix

- rtos/rtx/TARGET_CORTEX_M/cmsis_os.h
Added an `#ifndef` directive to the `__MBED_CMSIS_RTOS_CM` and `__CMSIS_RTOS` macro definitions in order to prevent "Incompatible redefinition of macro" warnings from the online compiler.
> [RTOS] Fixed online compiler macro warnings

- hal/api/critical.h
- hal/common/critical.c
This includes a generic critical section implementation.  This
implementation also allow a user to start a critical section while
interrupts are already disabled.
> Add a c based re-entrant critical section API

- hal/common/rtc_time.c
- hal/common/ticker_api.c
Routines using __disable_irq and __enable_irq had the effect of
enabling interrupts if called with interrupts disabled.
Some versions of __disable_irq do not return old status to restore it.
Change to use the critical section helper functions instead.
> Use critical section helper in HAL

- hal/common/SPI.cpp
- hal/common/board.c
- libraries/tests/libs/SerialHalfDuplex/SerialHalfDuplex.cpp
This is an extension of https://github.com/mbedmicro/mbed/pull/1806
Work left to be done:
hal/targets - This is partner code and should be consulted with them
rtos - We need to look here
> Remove __enable and __disable irq calls from mbed hal common code

- hal/targets/cmsis/TARGET_STM/TARGET_STM32F0/TARGET_NUCLEO_F091RC/system_stm32f0xx.c
The clock was 96MHz instead of 48MHz.
> [NUCLEO_F091RC] Fix HSI clock configuration issue.

- hal/targets/hal/TARGET_STM/TARGET_STM32F3/TARGET_NUCLEO_F303K8/PeripheralNames.h
- hal/targets/hal/TARGET_STM/TARGET_STM32F3/serial_api.c
This change allows the use of UART3 instance.
This change fixes the following issue :
https://developer.mbed.org/questions/4937/Serial-problem-no-Tx-to-PB_10
It's been validated on NUCLEO_F302RB, for PB_9 and PB_10 pins
> [STM32F3] Use USART3_BASE instead of UART3_BASE

- hal/targets/hal/TARGET_Freescale/TARGET_KSDK2_MCUS/TARGET_K22F/spi_api.c
- hal/targets/hal/TARGET_Freescale/TARGET_KSDK2_MCUS/TARGET_K64F/spi_api.c
- hal/targets/hal/TARGET_Freescale/TARGET_KSDK2_MCUS/api/i2c_api.c
- hal/targets/hal/TARGET_Freescale/TARGET_KSDK2_MCUS/api/objects.h
Fix SPI and IIC problems introduced with the switch to KSDK2.
> KSDK2 fixes

- hal/targets.json
efm32 targets were wrongly named, we follow now progendef names
(efm32gg-stk, ..).
Some tests:
```
Successful exports:
* EFM32GG_STK3700::uvision    C:\Code\git_repo\github\mbed-official\.build\export\MBED_10_uvision_EFM32GG_STK3700.zip
Successful exports:
* EFM32PG_STK3401::uvision5   C:\Code\git_repo\github\mbed-official\.build\export\MBED_10_uvision5_EFM32PG_STK3401.zip
```
I fixed ``wizwiki`` name, but not yet in progendef, will need to add it.
@stevew817
> targets - fix progen names (use - instead of _)

- hal/targets/cmsis/TARGET_Freescale/TARGET_K64F/TOOLCHAIN_GCC_ARM/MK64FN1M0xxx12.ld
The KSDK2 update restricts static data to the first 64K of RAM.
This breaks some applications which require more than 64K of
static data.  This patch moves the static data sections
(bss and data) into the second ram region which is 192K.
Changes taken from similar patches here:
https://github.com/ARMmbed/target-kinetis-k64-gcc/pull/5
https://github.com/ARMmbed/target-kinetis-k64-gcc/pull/6
> Update K64F memory map for for larger static data

- hal/common/critical.c
uARM complained about assert:
```
Error: L6218E: Undefined symbol __aeabi_assert (referred from critical.o).
Finished: 0 information, 0 warning and 1 error messages.
[ERROR] Error: L6218E: Undefined symbol __aeabi_assert (referred from critical.o).
Finished: 0 information, 0 warning and 1 error messages.
```
@c1728p9 @sg-
> Critical - use mbed assert

- rtos/rtos/Thread.cpp
- rtos/rtos/Thread.h
Problem:
- Threads begin running when constructed, allocation and execution are unnecessarily coupled
- Errors on starting threads can not be easily propagated
- Exacerbates issues with rtos initialization
- Threads lack join method, encouraging termination which can lead to very strange bugs
Proposed solution:
- Add Thread::start for explicitly starting threads and handling errors
- Defer to Thread::start from constructor if function is provided, **keeping backwards compatibility**
- Add Thread::join for gracefully merging threads
Thread::start in other languages: [c++](http://www.cplusplus.com/reference/thread/thread/operator=/), [c](http://man7.org/linux/man-pages/man3/pthread_create.3.html), [java](https://docs.oracle.com/javase/7/docs/api/java/lang/Thread.html#start%28%29), …
> Add lifetime management to threads

- hal/common/retarget.cpp
- rtos/rtx/TARGET_CORTEX_M/RTX_CM_lib.h
- workspace_tools/toolchains/gcc.py
- workspace_tools/toolchains/iar.py
Update IAR and GCC to improve thread safety.
> Thread safe

- rtos/rtos/Thread.cpp
- rtos/rtos/Thread.h
@geky's change, split off from #1793
> Adopt Callback class in rtos Threads

- hal/targets/cmsis/TARGET_STM/TARGET_STM32F3/TARGET_NUCLEO_F302R8/stm32f302x8.h
- hal/targets/cmsis/TARGET_STM/TARGET_STM32F3/TARGET_NUCLEO_F303K8/stm32f303x8.h
- hal/targets/cmsis/TARGET_STM/TARGET_STM32F3/TARGET_NUCLEO_F303RE/stm32f303xe.h
- hal/targets/cmsis/TARGET_STM/TARGET_STM32F3/TARGET_NUCLEO_F334R8/stm32f334x8.h
- hal/targets/hal/TARGET_STM/TARGET_STM32F3/PeripheralPins.h
- hal/targets/hal/TARGET_STM/TARGET_STM32F3/TARGET_NUCLEO_F302R8/PeripheralNames.h
- hal/targets/hal/TARGET_STM/TARGET_STM32F3/TARGET_NUCLEO_F302R8/PeripheralPins.c
- hal/targets/hal/TARGET_STM/TARGET_STM32F3/TARGET_NUCLEO_F302R8/device.h
- hal/targets/hal/TARGET_STM/TARGET_STM32F3/TARGET_NUCLEO_F302R8/objects.h
- hal/targets/hal/TARGET_STM/TARGET_STM32F3/TARGET_NUCLEO_F303K8/PeripheralNames.h
- hal/targets/hal/TARGET_STM/TARGET_STM32F3/TARGET_NUCLEO_F303K8/PeripheralPins.c
- hal/targets/hal/TARGET_STM/TARGET_STM32F3/TARGET_NUCLEO_F303K8/device.h
- hal/targets/hal/TARGET_STM/TARGET_STM32F3/TARGET_NUCLEO_F303K8/objects.h
- hal/targets/hal/TARGET_STM/TARGET_STM32F3/TARGET_NUCLEO_F303RE/PeripheralNames.h
- hal/targets/hal/TARGET_STM/TARGET_STM32F3/TARGET_NUCLEO_F303RE/PeripheralPins.c
- hal/targets/hal/TARGET_STM/TARGET_STM32F3/TARGET_NUCLEO_F303RE/device.h
- hal/targets/hal/TARGET_STM/TARGET_STM32F3/TARGET_NUCLEO_F303RE/objects.h
- hal/targets/hal/TARGET_STM/TARGET_STM32F3/TARGET_NUCLEO_F334R8/PeripheralNames.h
- hal/targets/hal/TARGET_STM/TARGET_STM32F3/TARGET_NUCLEO_F334R8/PeripheralPins.c
- hal/targets/hal/TARGET_STM/TARGET_STM32F3/TARGET_NUCLEO_F334R8/device.h
- hal/targets/hal/TARGET_STM/TARGET_STM32F3/TARGET_NUCLEO_F334R8/objects.h
- hal/targets/hal/TARGET_STM/TARGET_STM32F3/can_api.c
- libraries/tests/mbed/can/main.cpp
- libraries/tests/mbed/can_interrupt/main.cpp
- libraries/tests/mbed/can_loopback/main.cpp
- workspace_tools/tests.py
This pull request adds support for CAN bus for STM32F3xx family, specifically:
- NUCLEO_F302R8,
- NUCLEO_F303K8,
- NUCLEO_F303RE,
- NUCLEO_F334R8
HAL directories have been changed to accordingly.
> [STM32F3xx] CAN development for STM32F3xx family

- hal/targets/hal/TARGET_NXP/TARGET_LPC11U6X/i2c_api.c
- hal/targets/hal/TARGET_NXP/TARGET_LPC11UXX/i2c_api.c
- hal/targets/hal/TARGET_NXP/TARGET_LPC11XX_11CXX/i2c_api.c
- hal/targets/hal/TARGET_NXP/TARGET_LPC13XX/i2c_api.c
- hal/targets/hal/TARGET_NXP/TARGET_LPC176X/i2c_api.c
- hal/targets/hal/TARGET_NXP/TARGET_LPC23XX/i2c_api.c
- hal/targets/hal/TARGET_NXP/TARGET_LPC2460/i2c_api.c
- hal/targets/hal/TARGET_NXP/TARGET_LPC408X/TARGET_LPC4088/i2c_api.c
- hal/targets/hal/TARGET_NXP/TARGET_LPC408X/TARGET_LPC4088_DM/i2c_api.c
- hal/targets/hal/TARGET_NXP/TARGET_LPC43XX/i2c_api.c
In repeating start scenarios, there was a bug in the I2C driver for
various NXP LPCxxxx parts which could allow an extra I/O from the
previous operation to leak through. The scenario I encountered which
triggered this bug went like so:
* The higher level application code would first do an I2C write that
doesn't send a stop bit (use repeating start instead.)
* The higher level application code would then issues an I2C read
operation which begins with a call to i2c_start().
* i2c_start() would clear the SI bit (interrupt flag) at the top of
its implementation.
* i2C_start() would then get interrupted right after clearing the SI
bit.
* While the CPU is off running the ISR code, the I2C peripheral
repeats the last byte written to I2CDAT and then sets the SI bit to
indicate that the write has …
> Fix NXP LPCxxxx i2c_start() handling of repeated start

- hal/targets/cmsis/TARGET_NXP/TARGET_LPC408X/LPC407x_8x_177x_8x.h
- hal/targets/cmsis/TARGET_NXP/TARGET_LPC408X/system_LPC407x_8x_177x_8x.c
- libraries/net/eth/lwip-eth/arch/TARGET_NXP/lwipopts_conf.h
- workspace_tools/export/codered_lpc4088_cproject.tmpl
- workspace_tools/export/codered_lpc4088_dm_cproject.tmpl
- Resetting in LPCXpresso IDE did not reset the LCD controller which
sometimes could cause strange behaviour
- The ROM_LAT bit in the MATRIXARB register must be set in order to
prevent a HardFault when debugging
- The change of compiler in LPCXpresso IDE to ARM launchpad GCC5 was
causing build errors due to multiply defined timeval symbol.
- The exporters for LPCXpresso IDE did not set the FPU_PRESENT define
for assembler, only for c/c++. This caused very strange behaviour
in the RTOS code (e.g. timeouts no longer working, context switches
failing etc.)
> Misc fixes for LPC4088/LPC4088DM:

- hal/targets/cmsis/TARGET_STM/TARGET_STM32L0/TARGET_DISCO_L053C8/hal_tick.c
- hal/targets/cmsis/TARGET_STM/TARGET_STM32L0/TARGET_NUCLEO_L031K6/hal_tick.c
- hal/targets/cmsis/TARGET_STM/TARGET_STM32L0/TARGET_NUCLEO_L073RZ/hal_tick.c
After the PR #1743 there were some misalignment between `hal_tick.c` and `us_ticker.c` for SlaveCounter type.
> [STM32L0XX] SlaveCounter type correction

- hal/api/toolchain.h
Merges [compiler-polyfill](https://github.com/armmbed/compiler-polyfill) into hal/api/toolchain.h following the existing mbed conventions.
Tested on:
- GCC
- Clang
- ARMCC (online compiler)
- IAR
Attributes:
- MBED_PACK       
- MBED_ALIGN      
- MBED_UNUSED
- MBED_WEAK
- MBED_PURE
- MBED_FORCEINLINE
- MBED_NORETURN
- MBED_UNREACHABLE
- MBED_DEPRECATED
cc @sg-, @0xc0170, @c1728p9, @theotherjimmy 
mv [#97](https://github.com/ARMmbed/mbed-os/pull/97)
> Add useful attributes supported by supported compilers

- hal/api/critical.h
- hal/common/critical.c
Add core util functions for atomic increment, atomic decrement and
compare and set.
> Add functions for atomic access

- hal/targets/hal/TARGET_STM/TARGET_STM32F1/PeripheralPins.h
- hal/targets/hal/TARGET_STM/TARGET_STM32F1/TARGET_NUCLEO_F103RB/PeripheralNames.h
- hal/targets/hal/TARGET_STM/TARGET_STM32F1/TARGET_NUCLEO_F103RB/PeripheralPins.c
- hal/targets/hal/TARGET_STM/TARGET_STM32F1/TARGET_NUCLEO_F103RB/device.h
- hal/targets/hal/TARGET_STM/TARGET_STM32F1/TARGET_NUCLEO_F103RB/objects.h
- hal/targets/hal/TARGET_STM/TARGET_STM32F1/can_api.c
- libraries/tests/mbed/can/main.cpp
- libraries/tests/mbed/can_interrupt/main.cpp
- libraries/tests/mbed/can_loopback/main.cpp
- workspace_tools/tests.py
This pull request adds support for CAN bus for STM32F1xx family, specifically:
- NUCLEO_F103RB
Please merge #1762 first, then I will rebase.
> [STM32F1xx] CAN development for STM32F1xx family

- hal/targets/cmsis/TARGET_STM/TARGET_STM32L4/TARGET_DISCO_L476VG/TOOLCHAIN_ARM_STD/startup_stm32l476xx.s
- hal/targets/cmsis/TARGET_STM/TARGET_STM32L4/TARGET_DISCO_L476VG/TOOLCHAIN_ARM_STD/stm32l476xx.sct
- hal/targets/cmsis/TARGET_STM/TARGET_STM32L4/TARGET_DISCO_L476VG/TOOLCHAIN_GCC_ARM/STM32L476XX.ld
- hal/targets/cmsis/TARGET_STM/TARGET_STM32L4/TARGET_NUCLEO_L476RG/TOOLCHAIN_ARM_MICRO/startup_stm32l476xx.s
- hal/targets/cmsis/TARGET_STM/TARGET_STM32L4/TARGET_NUCLEO_L476RG/TOOLCHAIN_ARM_MICRO/stm32l476xx.sct
- hal/targets/cmsis/TARGET_STM/TARGET_STM32L4/TARGET_NUCLEO_L476RG/TOOLCHAIN_ARM_STD/startup_stm32l476xx.s
- hal/targets/cmsis/TARGET_STM/TARGET_STM32L4/TARGET_NUCLEO_L476RG/TOOLCHAIN_ARM_STD/stm32l476xx.sct
- hal/targets/cmsis/TARGET_STM/TARGET_STM32L4/TARGET_NUCLEO_L476RG/TOOLCHAIN_GCC_ARM/STM32L476XX.ld
aligned heap, stack config with IAR
issue: #1845
> [NUCLEO_L476RG, DISCO_L476VG]: GCC_ARM, ARM_STD fix RTOS failed

- hal/targets/cmsis/TARGET_STM/TARGET_STM32F1/TARGET_DISCO_F100RB/hal_tick.c
- hal/targets/cmsis/TARGET_STM/TARGET_STM32F1/TARGET_NUCLEO_F103RB/hal_tick.c
Due to directory structure change, modification in e93878078 was made wrong
after rebasing the code.
This reverts commit e938780788532504f6197fefb5aa909bf3c00583 and updates the path
to the correct file.
Note:
Current value of TIM_MST->CNT is read in interrupt context only.
This avoids master timer overflow without SlaveCounter update.
Continuation of patch: 07b841b08f2b173253e9268403738dbeb8df82ea
> [NUCLEO_F103RB] Revert and update path for 16-bit timer

- hal/hal/analogin_api.h
- hal/hal/analogout_api.h
- hal/hal/gpio_api.h
- hal/hal/gpio_irq_api.h
- hal/hal/i2c_api.h
- hal/hal/lp_ticker_api.h
- hal/hal/port_api.h
- hal/hal/pwmout_api.h
- hal/hal/rtc_api.h
- hal/hal/serial_api.h
- hal/hal/spi_api.h
- hal/hal/ticker_api.h
- hal/hal/us_ticker_api.h
The most doxygen docs are taken from ARMmbed/mbed-hal module
@sg- @c1728p9
> hal - adding doxygen documentation

- hal/targets/cmsis/TARGET_Freescale/TARGET_K22F/cmsis_nvic.h
- hal/targets/cmsis/TARGET_Freescale/TARGET_K64F/cmsis_nvic.h
- hal/targets/cmsis/TARGET_Freescale/TARGET_KL27Z/cmsis_nvic.h
Add the define NVIC_NUM_VECTORS for KSDK 2 targets so InterruptManager
is supported.
> Fix support for InterruptManager on KSDK 2

- libraries/tests/mbed/serial_nc_rx/main.cpp
- libraries/tests/mbed/serial_nc_tx/main.cpp
- workspace_tools/host_tests/serial_nc_rx_auto.py
- workspace_tools/host_tests/serial_nc_tx_auto.py
During initialization phase of the 2 NC serial tests,
there is a character being sent from host to target,
based on MBED_HOSTTEST_START. The problem is that
the target firmware then creates a "new" serial on the
same serial interface. the new or should, or at least may,
induce a reset of the IP, so that the character sent by host
would be lost. So we're moving the new earlier.
the real testing part happens later, to check the next
character is not received or sent.
> Modify serial nc tests init part

- docs/COMMITTERS.md
Because the encoding is wrong, and we can't build the API docs like that. GitHub said a commit will fix the encoding, so I'm comitting.
> Adding a blank line to commit

- hal/targets.json
- hal/targets/hal/TARGET_Freescale/TARGET_KSDK2_MCUS/TARGET_K64F/entropy_hardware_poll.c
This PR adds an entropy collector for mbed TLS for the K64F target to the mbed HAL.
This PR is initially provided for review and feedback, and I'm not yet asking for it to be merged.
@0xc0170 @sg-
> Add entropy collector for K64F to mbed HAL for use in mbed TLS

- hal/targets/hal/TARGET_Freescale/TARGET_KSDK2_MCUS/api/gpio_api.c
- hal/targets/hal/TARGET_Freescale/TARGET_KSDK2_MCUS/api/gpio_object.h
Freescale KSDK2 gpio_object.h pulled in Freescale libraries to inline
some GPIO operations.
The resulting namespace pollution (status_t) doesn't seem to be worth
the function call overhead. Hopefully making the base address array
non-automatic will offset that loss.
> Don't pull KSDK FSL libraries into apps

- rtos/mbed_lib.json
Defines that rtos is present, this resolves in the macro:
"MBED_CONF_RTOS_PRESENT=1"
By default, this macro would not be defined neither set, thus RTOS disabled, more to come soon.
@c1728p9 @sg-
> RTOS - add mbed_lib.json file

- hal/targets.json
- workspace_tools/remove-device-h.py
- workspace_tools/targets.py
- workspace_tools/toolchains/__init__.py
"features" will make more sense in the context of the feature support
that we'll introduce later (related to #1878). Plus, "device_has" is
arguably a better description of the actual content of this key.
> Rename "features" to "device_has" in targets.json

- hal/targets.json
- workspace_tools/toolchains/__init__.py
This should replace https://github.com/mbedmicro/mbed/pull/1878
> Feature label

- workspace_tools/toolchains/__init__.py
Introduce FEATURE_ keyword which behaves like TARGET_ but is generated from Target.features (see targets.json).
This allows specific functionality (and source-code directories) to be turned on and off depending on target features. E.g. feature "MPU" can turn on uVisor for targets that do have MPU and also implement support for uVisor
@0xc0170, @sg-, @bogdanm, @meriac, @theotherjimmy
> Introduce FEATURE_ which maps to Target.features

- hal/targets/hal/TARGET_Freescale/TARGET_KSDK2_MCUS/TARGET_K22F/drivers/fsl_common.c
- hal/targets/hal/TARGET_Freescale/TARGET_KSDK2_MCUS/TARGET_K64F/drivers/fsl_common.c
- hal/targets/hal/TARGET_Freescale/TARGET_KSDK2_MCUS/TARGET_KL27Z/drivers/fsl_common.c
Restore the state of interrupts inside InstallIRQHandler rather than
leaving them enabled.
> KSDK2 - restore interrupts in InstallIRQHandler

- libraries/net/eth/lwip-eth/arch/TARGET_Freescale/hardware_init_MK64F12.c
It seems that a clock-enable was missed for port B in lwip-eth. This bug does not appear if printfs flush before bringing up the ethernet, making the issue rare.
cc @0xc0170, @bridadan
> Fixed uninitialized port in lwip dragged in by KSDK2

- hal/targets/hal/TARGET_NORDIC/TARGET_MCU_NRF51822/us_ticker.c
The function is_in_wrapped_range, was returning false instead of true when begin <= val < end. 
The documentation was correct but not the code.
> Fix function RTOS ticker of nrf51 port

- rtos/rtx/TARGET_CORTEX_M/RTX_Conf_CM.c
The call stack of the soft device can be 0x600 (1536) bytes deep. By
adjusting the stack to a value of 2048 bytes, their is enough room for
the softdevice and RTX kernel to live together in the main stack.
Random issues due to stack overflow were visible with the previous value.
**Important** most RTOS tests on NRF51822 target are expected to fail because their is not enough space left for other threads. Tests are fine on NRF51_DK.
> Adjust the main stack of nrf51 targets to the call stack of thesoftdevice.

- tools/config.py
Example in your mbed_lib.json:
``` json
Attributes now get the filtering provided by target_overrides: 
{                                                              
"name": "cmsis-nodejs-SQL-x86",                            
"target_overrides": {                                      
"*": {                                                 
"device_has": ["SILLY_STRING", "FIRE"]             
},                                                     
"SHOE": {                                              
"features_add": ["SMELLS_FUNNY"],                  
"features_remove": ["SMELLS_NICE"]           
}                                                      
}                                                          
} …
```
> [build tools] Added support for cumulative attributes in configs directly

- rtos/rtx/TARGET_CORTEX_M/rt_CMSIS.c
The rtx SVC_Handler for IAR clobbers r0-r3 despite the number of
arguments. However, in the SVC calls, the __swi function is declared
with fewer arguments. IAR doesn't understand that the other registers are
clobbered and stores variables in r0-r3 when multiple SVCs are
dispatched in a single function.
This bug was noticed in osThreadExit, which hard-faults on IAR,
preventing any threads from exiting.
> [rtos] Fixed registers clobbered SVC_Handler in IAR

- hal/api/toolchain.h
IAR only allows word size alignment in MBED_ALIGN attribute. Noted in toolchain.h.
cc @mjs-arm
> Added warning about stack alignment limitations on IAR

- tools/build.py
- tools/build_api.py
- tools/default_settings.py
- tools/detect_targets.py
- tools/make.py
> Aligned make.py and build.py options

- tools/export/__init__.py
it is now called both uvision (old name) and uvision4 (new alias)
for consistency, and explicitness reasons
> Add alias for uvision4 exporter

- hal/api/AnalogIn.h
- hal/api/AnalogOut.h
- hal/api/I2C.h
- hal/api/InterruptManager.h
Add a virtual destructor to classes which have a virtual lock and
unlock.  Remove the virtual qualifier from functions in
InterruptManager since this class cannot be extended.
> Add virtual destructor to classes

- hal/common/retarget.cpp
The malloc lock functions were not declared as extern "C" so they
are not getting linked to the standard library.  Add extern "C" to
fix this.
This bug was introduced in the commit:
d0b7b3b497ae1824bb8cb07603c90f5105d7818d -
Fix duplicate symbols for malloc lock and unlock
> Fix GCC malloc lock

- tools/export/atmelstudio.py
- tools/export/atmelstudio6_2.cppproj.tmpl
- tools/export/codered.py
- tools/export/codered_cproject_common.tmpl
- tools/export/emblocks.py
- tools/export/exporters.py
- tools/export/gcc_arm_common.tmpl
- tools/export/gccarm.py
- tools/export/iar.py
- tools/export/simplicityv3.py
- tools/export/simplicityv3_slsproj.tmpl
- tools/toolchains/__init__.py
- tools/toolchains/arm.py
- tools/toolchains/gcc.py
- tools/toolchains/iar.py
Rebased, and fixed IAR exporter and gcc (both expor and build) - tested on top of another fix which is already for review.
@theotherjimmy
> Replacement for #1872

- tools/export/uvision4.py
- tools/export/uvision5.py
- tools/project.py
- tools/toolchains/arm.py
The project dir if using just project.py shall be a list of directories.
Using ``project.py -m KL25Z -t IAR`` works with this fix. I'll continue testing this patch, as there are some other problems.
cc @screamerbg
> Tools/project - project dir should be the list

- hal/common/critical.c
- hal/common/error.c
One header missing to include in the board.c to get mbed_error_vfprintf(), plus critical.c to get UINT32_MAX constant
@c1728p9
> Fix inclusion (board.c and critical.c)

- hal/targets/cmsis/TARGET_RENESAS/TARGET_RZ_A1H/system_MBRZA1H.c
- hal/targets/cmsis/TARGET_RENESAS/TARGET_RZ_A1H/system_MBRZA1H.h
- hal/targets/cmsis/TARGET_RENESAS/TARGET_VK_RZ_A1H/system_VKRZA1H.c
- hal/targets/cmsis/TARGET_RENESAS/TARGET_VK_RZ_A1H/system_VKRZA1H.h
Hi.
We implemented SystemcoreClock which is defined in CMSIS.
Regards;
Yamanaka
> Implement SystemcoreClock

- tools/build_api.py
- tools/test.py
- tools/test_api.py
- tools/test_exporters.py
This improves the following aspects about building and listing tests:
- Build logs has reduced amount of repeated toolchain errors (most, if not all, should be gone now)
- Printing tests is now done in alphabetical order
- Test names are now always printed in lower case
- Test build filtering is now case insensitive and can accept a comma separated list of blob names (as parsed by the python function `fnmatch`)
- NotSupported build skips fixed
> Tools improvements

- hal/targets.json
uVisor is now enabled by features, not through targets. Removing the old K64F_UVISOR target.
> Removing K64F_UVISOR target

- tools/export/uvision5.py
- one missing import
- typo: uvision instead of uvision5 used
> [uviosn5] some fixes for PR #1933

- tools/export/iar.py
- tools/export/iar_template.ewp.tmpl
- tools/toolchains/iar.py
We need to distinguish between cmd flags and exporters flags, they are not the same.
cc @theotherjimmy
> Fix iar exporter - flags duplication and consolidations

- hal/targets/cmsis/TARGET_STM/TARGET_STM32F0/TARGET_NUCLEO_F030R8/hal_tick.c
- hal/targets/cmsis/TARGET_STM/TARGET_STM32F0/TARGET_NUCLEO_F070RB/hal_tick.c
- hal/targets/hal/TARGET_STM/TARGET_STM32F0/us_ticker.c
This is a fix for #816 issue only for F0xx family. It contains two changes:
Partial revert of 07b841b and currently we are only reverting the
STM32F0xx family because new fix will be presented that's why we want to keep,
still the original solution only F1xx family (it will be fixed in future).
Also a solution for issue #816 when having two separate IRQ handlers
in Timers (UPDATE Irq and OutputCompare Irq). The update priority needs to
be higher to avoid undefined behaviours.
====
Tested on NUCLEO_F070RB and NUCLEO_F030R8 in multiple cases and MBED_16 is passed OK. Please find the test report below.
**NUCLEO_F070RB** 
All compilers, multiple tested times:
- 1000/1500/1000 - OK
- 500/1000/500 - OK
- 1500/2000/1500 - OK
- 600/800/600 - OK
- sampling rate in Saleae 90s
MBED_16 OK
=== …
> [STM32F0xx] Fix for #816 issue

- libraries/tests/mbed/serial_complete/main.cpp
- tools/host_tests/__init__.py
- tools/host_tests/serial_complete_auto.py
- tools/tests.py
This automated test makes sure that the serial
syncrhonous API ensures a full transmission before
the function returns. The complete string sent by
printf shall be completely transferred before printf
returns and the sleep modes are called.
mbed Issue #1849
> Add a serial transmission complete test

- tools/export/iar.py
- tools/export/iar_template.ewp.tmpl
- tools/toolchains/iar.py
Reverts mbedmicro/mbed#1938
This breaks all command line builds for IAR. Do not merge patches that are not tested across all toolchains.
> Revert "Fix iar exporter - flags duplication and consolidations"

- tools/build_api.py
Previously, .hex files were not copied when building source as a library.
This prevents builds that pre-compile source as a library and then includes the build directory as the only source (because there is no softdevice present). This PR adds an option to copy hex files when compiling source as a library. This is currently being used when compiling tests within `test.py`
Please review @0xc0170 and @screamerbg 
FYI @pan-
> Fixing test builds for devices with softdevices.

- tools/build_api.py
- tools/config.py
- tools/test/config_test/config_test.py
- tools/test/config_test/test21/mbed_app.json
- tools/test/config_test/test21/test_data.py
- tools/test/config_test/test22/lib1/mbed_lib.json
- tools/test/config_test/test22/mbed_app.json
- tools/test/config_test/test22/test_data.py
- tools/test/config_test/test23/lib1/mbed_lib.json
- tools/test/config_test/test23/lib2/mbed_lib.json
- tools/test/config_test/test23/mbed_app.json
- tools/test/config_test/test23/test_data.py
- tools/test/config_test/test24/FEATURE_IPV4/lib1/mbed_lib.json
- tools/test/config_test/test24/FEATURE_IPV6/lib2/mbed_lib.json
- tools/test/config_test/test24/mbed_app.json
- tools/test/config_test/test24/test_data.py
- tools/test/config_test/test25/FEATURE_IPV6/FEATURE_IPV4/lib1/mbed_lib.json
- tools/test/config_test/test25/FEATURE_IPV6/lib2/mbed_lib.json
- tools/test/config_test/test25/mbed_app.json
- tools/test/config_test/test25/test_data.py
- tools/test/config_test/test26/FEATURE_IPV4/lib1/mbed_lib.json
- tools/test/config_test/test26/FEATURE_IPV6/lib2/mbed_lib.json
- tools/test/config_test/test26/mbed_app.json
- tools/test/config_test/test26/test_data.py
- tools/toolchains/__init__.py
1. Features now recursively add to cumulative config
1. Added verification of features, error on conflicting feature declarations
supported options:
``` json
{
"feature": ["CLIENT"],
"features_add": ["IPV4"],
"features_remove": ["IPV6"]
}
```
cc @screamerbg @sg-
> [build tools] Added better support for features and recursive configs

- hal/targets.json
Without this fix, some required FEATURE_ directories are not included,
which breaks compilation for existing code.
> Added feature list for K64F

- tools/toolchains/iar.py
Exporters and cmd do not share all flags, some asm and c flags are not the same (cpu, fpu). 
This is the clean up of the latest changes, that made some changes not available for cmd or exporters.
The changeset applied to mbed lib:
After the change:
C file
```
before:
[DEBUG] Command: C:/Program Files (x86)/IAR Systems/Embedded Workbench 7.2/arm\bin\iccarm --no_wrap_diagnostics -e --diag_suppress=Pa050,Pa084,Pa093,Pa082 --cpu=Cortex-M3 --thumb --dlib_config C:/Program Files (x86)/IAR Systems/Embedded Workbench 7.2/arm\inc\c\DLib_Config_Full.h -Oh -DDEVICE_ERROR_PATTERN=1 -D__MBED__=1 -DDEVICE_I2CSLAVE=1 -DTARGET_LIKE_MBED -DTARGET_NXP -DTARGET_LPC176X -D__MBED_CMSIS_RTOS_CM -DDEVICE_RTC=1 -DDEVICE_LOCALFILESYSTEM=1 -D__CMSIS_RTOS -DDEVICE_CAN=1 -DTARGET_LIKE_CORTEX_M3 -DTARGET_CORTEX_M …
```
> iar - fix flags for cmd and exporters

- tools/project.py
Previously it was .zip always, even when using sources. This patch fixes it:`
```
Successful exports:
* K64F::uvision       path\projectfiles\uvision\Unnamed_Project_K64F
```
@sg- @screamerbg
> Export - project name fix (.zip)

- tools/build.py
Only makes sence for --source builds (which only work with --build)
> Add -N/--artifact-name argument to parser to name libraries

- hal/targets/hal/TARGET_STM/TARGET_STM32F1/pinmap.c
Failed for pin_index 0 (PA_0, PB_0,PC_0).
Usecase:
```cpp
DigitalIn pa0(PA_0, PullUp);
//or
gpio_t gpio;
gpio_init(&gpio, C9);
gpio_dir(&gpio, PIN_INPUT);
gpio_mode(&gpio, PullDown);
```
in both cases GPIO registers are corrupted.
> Fix pin mode for STM32F1 target. 

- hal/targets/hal/TARGET_Freescale/TARGET_KSDK2_MCUS/TARGET_K64F/drivers/fsl_clock.h
A previous patch removed two `volatile` keywords by mistake, which are
here re-introduced.
Fixes:
* 23904e7 "Access MCG and SIM through secure access"
@c1728p9 @sg- @meriac
> K64F KSDK2: Re-add missing volatile in CLOCK functions

- tools/build_api.py
- tools/config.py
- tools/get_config.py
- tools/test/config_test/config_test.py
- tools/toolchains/__init__.py
- tools/toolchains/arm.py
- tools/toolchains/gcc.py
- tools/toolchains/iar.py
The current implementation of the configuration system "compiles" the
configuration parameters to macros defined on the command line. This
works, but has a few limitations:
- it can bring back the maximum command line length issues in Windows.
- depending on the type of the configuration parameter, it might require
special quoting of its value in the command line.
- various 3rd party IDE/tools seem to have some limitations regarding
the total length of the macros that can be defined.
This PR is the first step in replacing the current mechanism with
one that generates configuration in header files that will be
automatically included, instead of command line macro definitions.After
this PR is accepted, compiling from the command line will use these
generated header files. Exporters still …
> Configuration in header files - step 1

- tools/build_api.py
- tools/config.py
- tools/export/exporters.py
Unified how resources are loaded into the configuration system (Config.load_resources) and applied to bith build_api and exporters
> Fixed exporters to support features

- hal/targets.json
- hal/targets/hal/TARGET_STM/TARGET_STM32F0/lp_ticker.c
- hal/targets/hal/TARGET_STM/TARGET_STM32F0/rtc_api.c
- hal/targets/hal/TARGET_STM/TARGET_STM32F0/rtc_api_hal.h
LowPowerTicker for STM32F0xx family is implemented using the RTC periodic unit
functionality. For more informations please follow this document: 
* www.st.com/resource/en/application_note/dm00025071.pdf
Supported platforms:
- NUCLEO_F072RB
- NUCLEO_F070RB
- NUCLEO_F091RC
> [STM32F0xx] LowPowerTicker implementation

- hal/common/retarget.cpp
- mbed_lib.json
As noted by @kjbracey-arm, mbed currently prints \r and \n unmodified to stdout and most serial terminals default to requiring a \r\n sequence to actually create a newline. This results in non-standard io for many setups, since the C standard states that \n will be converted to the underlying newline sequence[[1]](https://en.wikipedia.org/wiki/Newline#In_programming_languages). Annoyingly, this has resulted in the \r\n being used in many programs.
In this patch, stdout/stdin do the following conversions greedily (without delays):
on write:
```
\n   -> \r\n
\r\n -> \r\n
\r   -> \r
\n\r -> \n\r
```
on read:
```
\n   -> \n
\r\n -> \n
\r   -> \n
\n\r -> \n
```
Serial.output provides support for unmodified binary output (and still requires \r\n). This conversion remains backwards compatibly …
> Add newline conversion for stdout

- tools/config.py
Boolean configuration parameters will now be generated as integers (1
for True, 0 for False).
> Config bool to int

- hal/targets.json
- hal/targets/hal/TARGET_Freescale/TARGET_KSDK2_MCUS/TARGET_K64F/storage_driver.c
Changes so the flash mode can be selected with config system property.
This was previously submitted in this PR:
https://github.com/mbedmicro/mbed/pull/1972
But was changed to remove inadvertent device_has LOWPOWERTIMER losses.
@ohagendorf
Please see this new PR.
> cfstore flash-journal integration with config_system (Resubmitted)

- tools/toolchains/__init__.py
Also simplify build scanning logic and add comments
> Fixed double-ignored files that cause python exception

- tools/test/config_test/test12/mbed_app.json
- tools/test/config_test/test12/test_data.py
- tools/test/config_test/test16/mbed_app.json
- tools/test/config_test/test16/test_data.py
- tools/test/config_test/test21/mbed_app.json
- tools/test/config_test/test21/test_data.py
- tools/test/config_test/test22/mbed_app.json
- tools/test/config_test/test22/test_data.py
- tools/test/config_test/test24/mbed_app.json
- tools/test/config_test/test24/test_data.py
- tools/test/config_test/test26/mbed_app.json
- tools/test/config_test/test26/test_data.py
PR #1974 added a new configuration parameter to K64F, which in turn made
some tests break, because they found an unexpected configuration
parameter. Fixed by defining a special target for the tests
(test_target) that can be used independently of the actual mbed targets.
> Fix K64F-based config tests

- tools/test_exporters.py
Some `<tr>` are missing if there is more than one toolchain in an html report. It is handled by most of the browsers and the render is ok but it causes errors when you want to parse the file with python for example.
> Fix html report exporter row tag

- tools/toolchains/__init__.py
Options were parsed and logged before per-toolchain logging was setup.
Fixes #1990
> [tools] Reorder option handling in toolchains

- tools/toolchains/__init__.py
Match walk() root against the ignore list.
For example .mbedignore in tools/ contains '*' and naturally should match all files, folders including tools/ itself. Without this fix, tools/ is added to the include path
> Fixed .mbedignore logic to ignore the walk() root

- tools/export/iar_template.ewp.tmpl
- tools/toolchains/arm.py
- tools/toolchains/gcc.py
- tools/toolchains/iar.py
IAR defaults to C99 mode, but doesn't enable VLAs by default. Enable them
to make it more conformant.
We don't have much if any code using actual variable-length arrays, but
variably-modified types are occasionally used. The same switch controls
both.
> Turn on C99 VLAs in IAR

- hal/targets/hal/TARGET_STM/TARGET_STM32F4/TARGET_DISCO_F429ZI/PinNames.h
The basic SPI pins definition was missing so far - this makes SPI default usage easier
> [STM32] Add SPI defaults pins to DISCO_F429ZI

- hal/targets/hal/TARGET_STM/TARGET_STM32F4/TARGET_ARCH_MAX/PeripheralNames.h
- hal/targets/hal/TARGET_STM/TARGET_STM32F4/TARGET_B96B_F446VE/PeripheralNames.h
- hal/targets/hal/TARGET_STM/TARGET_STM32F4/TARGET_DISCO_F407VG/PeripheralNames.h
- hal/targets/hal/TARGET_STM/TARGET_STM32F4/TARGET_DISCO_F429ZI/PeripheralNames.h
- hal/targets/hal/TARGET_STM/TARGET_STM32F4/TARGET_NUCLEO_F446RE/PeripheralNames.h
- hal/targets/hal/TARGET_STM/TARGET_STM32F4/analogin_api.c
Introducing ADC2 support for NUCLEO_F446ZE implies to have the support
in the core part for all F4 chipsets that possibly support it (even if
not supported on all boards).
> [STM32F4] Add ADC2 support to F4 family

- libraries/tests/rtos/cmsis/basic/main.cpp
- libraries/tests/rtos/cmsis/isr/main.cpp
- libraries/tests/rtos/cmsis/mail/main.cpp
- libraries/tests/rtos/cmsis/mutex/main.cpp
- libraries/tests/rtos/cmsis/queue/main.cpp
- libraries/tests/rtos/cmsis/semaphore/main.cpp
- libraries/tests/rtos/cmsis/signals/main.cpp
- libraries/tests/rtos/cmsis/timer/main.cpp
- libraries/tests/rtos/mbed/basic/main.cpp
- libraries/tests/rtos/mbed/file/main.cpp
- libraries/tests/rtos/mbed/isr/main.cpp
- libraries/tests/rtos/mbed/mail/main.cpp
- libraries/tests/rtos/mbed/mutex/main.cpp
- libraries/tests/rtos/mbed/queue/main.cpp
- libraries/tests/rtos/mbed/semaphore/main.cpp
- libraries/tests/rtos/mbed/signals/main.cpp
- libraries/tests/rtos/mbed/timer/main.cpp
fail compilation of the test as not supported
> If a target is restricted to single threaded mode,

- hal/targets/hal/TARGET_Freescale/TARGET_KSDK2_MCUS/TARGET_K64F/storage_driver.c
was complaining about 'pointless comparison of unsigned integer with zero'
@simonqhughes @sg- @0xc0170
> minor fix for a warning when compiling with ARMCC

- rtos/rtx/TARGET_CORTEX_M/RTX_CM_lib.h
Previously, the `mbed_main` function was not being called when using the RTOS when compiling with IAR. This PR adds this function call in this case for Cortex M targets.
> Calling mbed_main when using RTX and compiling with IAR

- tools/export/__init__.py
- tools/export/exporters.py
- tools/project.py
tested with export using mbed (the change, introducing a flag to indicate if we use relative paths or not) and project.py (no regression there as copied flag for progen stays as it was). The fix is the first commit . 
The second commit is a cosmetic change , that actually can be breaking for callers of ``export`` as I renamed the default argument from ``relative`` to ``sources_relative``, as it is more clear what's the intention. I can revert it , just proposing an unification of this flag in the 2 files.
Tested with uvision and IAR (checked the paths are correct ). Using master of project generator (v0.9x should work as there are no changes required for this patch in the progen).
@bogdanm @theotherjimmy
> Fix paths for project.py

- tools/project.py
Before this PR:
```
Successful exports:
* K64F::uvision       .\projectfiles\uvision\Unnamed_Project_K64F
```
After this PR:
```
Successful exports:
* K64F::uvision       .\projectfiles\uvision_K64F\Unnamed_Project
```
The directory name now contains `<ide>_<target>`, which is arguably
a bit more clear.
> Change directory generation for project files.

- tools/build_api.py
- tools/config.py
- tools/toolchains/__init__.py
- tools/toolchains/iar.py
The IAR assembler doesn't accept '--preinclude', but it accepts -D.
This commit changes the way the config-related macros are propagated
to the IAR assembler to use '-D' instead of '--preinclude'. This is
the only change related to functionality, the others are small,
backward compatible changes to the config code to make passing arguments
to the toolchain instances easier.
Tested by compiled blinky with IAR, GCC_ARM and ARM for K64F.
> Fixed config-related options for the IAR assembler

- tools/default_settings.py
- tools/settings.py
- tools/toolchains/__init__.py
This PR adds the ability to set/override ARM_PATH, GCC_ARM_PATH, IAR_PATH and GCC_CR_PATH build system variables through environmental variables. If the env variable points to invalid path then it's ignored.
For backwards compatibility mbed_settings.py is still respected, but environmental variables have higher prio.
Note that the latest mbed CLI supports global config setting for these variables.
Also updated license of settings.py and default_settings.py and added comments
> [Tools] Add environmental variables support for toolchain paths

- tools/make.py
- tools/targets.py
- tools/test_api.py
Aligns program_cycle_s with the changes to the target configs
> [Tools] Force program_cycle_s to be used as an attribue everywhere

- tools/export/__init__.py
The boolean zip passed as a parameter conflicts with the zip exporter class imported.
> [Exporters] Conflicting zip name

- hal/targets.json
By default, `default_build` is set to `standard` for all targets.
`NRF51` is very a very constrained platform, it makes a lot of sense to set `default_build` to `small` for all `NRF51` based targets.
> Use nano lib by default for nrf51 based targets.

- tools/export/atmelstudio.py
- tools/export/codered.py
- tools/export/emblocks.py
- tools/export/exporters.py
- tools/export/gccarm.py
- tools/export/iar.py
- tools/export/simplicityv3.py
- tools/export/uvision4.py
- tools/export/uvision5.py
- tools/toolchains/__init__.py
- tools/toolchains/arm.py
- tools/toolchains/gcc.py
- tools/toolchains/iar.py
Affected exporters:
- gcc_arm
- uVision4
- IAR
- emblocks
- atmelstudio
- codered
- simplicityv3
Summary of discussion:
@0xc0170:
We should wait until the name of mbed_conf.h is set in stone.
@bogdanm:
We should introduce a configuration variable for all exporters to indicate if they export the mbed_conf.h. This will help eliminate duplication.
> [Exporters] Update exporters to include and use mbed_conf.h (Was #1964)

- tools/project.py
one more addition for the #2034
Error received without this patch:
```
File "tools\project.py", line 213, in <module>
tmp_path, report = export(project_dir, project_name, ide, mcu, project_dir[0], project_temp, clean=clean, zip=zip, extra_symbols=lib_symbols, sources_relative=sources_relative)
TypeError: export() got an unexpected keyword argument 'zip'
```
@bogdanm
> Project - fix zip rename argument

- tools/export/uvision4.py
- tools/export/uvision5.py
IDE has C/C++ tab, thus this only cxx flag would be applied for
C files.
This fixes errors I have seen in the C files ,as no-vla is applied for C files as well in the IDE projects.
@bogdanm @kjbracey-arm
> uvision4/5 - remove no-vla for exporters

- tools/toolchains/arm.py
libpath is not required for exporters, as they provide default paths.
This caused problems when paths are not correct for mbed tools, a project
fails to build as path is not found.
@mlnx @adbridge @bogdanm @sg-
> armcc - remove libpath from ld flags

- tools/tests.py
Although long-term we might want to fix post-main() routines to ensure output is flushed.
@bridadan @sg-
> [Testing] Disable test MBED_39 being commonly failed test

- tools/export/iar.py
The template file already enables VLA as it's for C only. This --vla flag
causes conflicts with --cpp flag that is enabled implicitly if C++ is enabled.
IAR template before this patch:
```
<state></state>
<state>--guard_calls</state>
<state>--preinclude=mbed_config.h</state>
<state>--vla</state>
<state>--preinclude=mbed_config.h</state>
<name>IExtraOptions</name>
```
This causes problems because C++ is enabled, thus --vla causes errors when compiling.
IAR template after this patch:
```
<state></state>
<state>--guard_calls</state>
<state>--preinclude=mbed_config.h</state>
<state>--preinclude=mbed_config.h</state>
<name>IExtraOptions</name>
```
@theotherjimmy Seems that preinclude is 2x there
@sg- @bogdanm
> iar - remove --vla flag for exporters

- tools/memap.py
- Removing stack & heap (dynamic) RAM information
This information was misleading and shouldn't be shown in memap.
E.g. each task may have its own stack region configured at run time.
- Adding 'bytes' unit in the total memory info
- Right aligment of numbers, so it is easier to compare numbers
> [memap] Improve wording on stack/heap and minor improvements

- hal/targets/cmsis/TARGET_RENESAS/TARGET_RZ_A1H/TOOLCHAIN_IAR/startup_RZA1H.s
- rtos/rtx/TARGET_CORTEX_A/RTX_CM_lib.h
Hi
This is an update to RTX kernel for Cortex-A version to allow c++ libc array init to be called after kernel start.
Ref: https://github.com/mbedmicro/mbed/pull/1730
Regards,
Yamanaka
> RTX - init sequence (C++ array init) for Cortex-A version

- README.md
- hal/targets.json
This modification is to allow IPV4 feature on mbed
> [NUCLEO_F746ZG] add IPV4 support for F7 in mbed

- rtos/rtx/TARGET_CORTEX_A/RTX_Conf_CA.c
Hi
We changed the stack size of main thread for RZ_A1H.
We changed "OS_MAINSTKSIZE" from 2048 to 4096.
Because stack shortage was found in the automatic test by the CI System of mbed OS.
Regards,
Yamanaka
> Change stack size of main thread for RZ_A1H

- hal/targets/cmsis/TARGET_Freescale/TARGET_K22F/TOOLCHAIN_ARM_STD/MK22FN512xxx12.sct
- hal/targets/cmsis/TARGET_Freescale/TARGET_K64F/TOOLCHAIN_ARM_STD/MK64FN1M0xxx12.sct
- hal/targets/cmsis/TARGET_Freescale/TARGET_KL27Z/TOOLCHAIN_ARM_STD/MKL27Z64xxx4.sct
- `__heap_size__` was used to allocate a fixed size region for the heap in `RW_IRAM1` ([here](https://github.com/mbedmicro/mbed/blob/master/hal/targets/cmsis/TARGET_Freescale/TARGET_K64F/TOOLCHAIN_ARM_STD/MK64FN1M0xxx12.sct#L110))
- `__user_setup_stackheap` in `sys.cpp` uses `Image$$RW_IRAM1$$ZI$$Limit` as the start of the heap, which leaves the fixed size region unused ([here](https://github.com/mbedmicro/mbed/blob/master/hal/targets/cmsis/TARGET_Freescale/TARGET_K64F/TOOLCHAIN_ARM_STD/sys.cpp#L17))
`Image$$RW_IRAM1$$ZI$$Limit` is now correctly the end of global variables. This matches the sct files for other Freescale devices.
resolves ARMmbed/mbed-os#384
cc @sg-, @c1728p9
> Removed heap region from ARM sct file on K devices

- rtos/rtx/TARGET_CORTEX_M/rt_HAL_CM.h
uVisor requires the SVCall to have priority 0, while RTX allows it to be
the second lowest priority level in the system (after PendSV).
This commit makes sure that the SVCall priority is not changed if uVisor
is present. The PendSV priority is not affected.
@meriac @Patater
> RTOS: Only set the SVC priority if uVisor is not present

- tools/toolchains/__init__.py
Should resolve #2011
This works:
```
$  python tools/make.py -t GCC_ARM -m K64F --source libraries/tests/mbed/blinky/main.cpp --source . --build .build
Building project main.cpp (K64F, GCC_ARM)
Compile: CAN.cpp
<snip>
Link: main.cpp
Elf2Bin: main.cpp
+-----------+-------+-------+------+
| Module    | .text | .data | .bss |
+-----------+-------+-------+------+
| Fill      |   121 |     4 | 2170 |
| Misc      | 47645 |  2252 | 3290 |
| Subtotals | 47766 |  2256 | 5460 |
+-----------+-------+-------+------+
Allocated Heap: 65540 bytes
Allocated Stack: 32768 bytes
Total Static RAM memory (data + bss): 7716 bytes
Total RAM memory (data + bss + heap + stack): 106024 bytes
Total Flash memory (text + data + misc): 51062 bytes
Image: .build/main.cpp.bin
```
and the led blinks.
also:
```
$  mbed …
```
> Enable passing individual files to --source options

- hal/targets.json
Hi
We added "IPV4" of Compile Macro in "targets.json" file.
We failed in the reletion test of IPV4 because "IPV4" was not entered into our Build Target setting.
This PR is that was rebased https://github.com/mbedmicro/mbed/pull/2018.
Ref : https://github.com/mbedmicro/mbed/pull/2018#issuecomment-229234343
Regards,
Yamanaka
> In targets.json, add the "IPV4" setting for RZ_A1H(Rebase #2018)

- tools/test_api.py
Test spec paths are now relative to tool execution directory as shown by the greentea docs here: https://github.com/ARMmbed/greentea#example-of-test-specification-file
This commit also normalizes the paths produced by the the test spec to Unix style paths to increase portability of the file.
```
{
"builds": {
"K64F-GCC_ARM": {
"binary_type": "bootable", 
"tests": {
"mbed-os-tests-mbedmicro-rtos-mbed-mutex": {
"binaries": [
{
"path": "C:\\m\\test\\.build\\tests\\K64F\\GCC_ARM\\mbed-os\\TESTS\\mbedmicro-rtos-mbed\\mutex\\mbed-os-tests-mbedmicro-rtos-mbed-mutex.bin"
}
]
}
}, 
"toolchain": "GCC_ARM", 
"base_path": "C:\\m\\test\\.build/tests\\K64F\\GCC_ARM", 
"baud_rate": 9600, 
"platform": "K64F"
}
}
}
```
```
{
"builds": {
"K64F-GCC_ARM": {
"binary_type": "bootable", 
"tests": { …
```
> Relative paths in test spec file

- rtos/rtx/TARGET_CORTEX_M/HAL_CM.c
- rtos/rtx/TARGET_CORTEX_M/RTX_Conf_CM.c
- rtos/rtx/TARGET_CORTEX_M/cmsis_os.h
- rtos/rtx/TARGET_CORTEX_M/rt_System.c
Fixes #2059. As reported, if timer thread is not created, the main thread
id is 0x01. We introduce MAIN_THREAD_ID macro to define the id. We shall consider,
if we keep this in a variable.
I placed MAIN_THREAD_ID in cmsis_os.h as that header is safe to include within RTX, not like
RTX_Config.h or RTX_CM_Lib.h). I reported an issue to cmsis team about this inclusion mess within RTX.
tested with K64F with default config:
```
+--------+------------+-----------+---------+-------------------------+--------------------+---------------+-------+
| Result | Target     | Toolchain | Test ID | Test Description        | Elapsed Time (sec) | Timeout (sec) | Loops |
+--------+------------+-----------+---------+-------------------------+--------------------+---------------+-------+
| OK     | K64F[f3f7] …
```
> RTOS - fix for main thread id might not be 0x02

- hal/targets/hal/TARGET_STM/TARGET_STM32L0/serial_api.c
Issue #2074
Assuming that OverSampling is initialized, the baudrate is now correctly
computed inside CMSIS (STM32 HAL) layer. This was not the case before but
most probably was fixed during latest L0 cube firmware upgrade:
commit ce436d51075b7ea08a2f0b05fd398d81d59bd54e
Author: svastm <simon.vanson@st.com>
Date:   Thu Apr 14 14:39:53 2016 +0200
Update STM32CUBE_L0 from v1.2 to v1.5
> [STM32L0] Fix baudrate initialisation

- rtos/rtos/Thread.h
Thread-spawning constructors hide errors and may lead to complex program state when a thread is declared.
The explicit Thread::start member function should be used to spawn a thread.
More info:
https://github.com/ARMmbed/mbed-os/pull/79
https://github.com/mbedmicro/mbed/issues/2024
cc @pan-, @niklas-arm, @0xc0170
> Marked thread-spawning constructors as deprecated

- tools/export_test.py
rtos was located at mbed/libraries/rtos. It is now located at mbed/rtos. This script assumed the location was mbed/libraries/rtos and failed on execution. I have changed the script to find rtos at mbed/rtos.
> Changed reference to old rtos location

- hal/api/critical.h
- hal/common/critical.c
than an integer. This removes the need for all users to mask the returned
value with 0x1 to determine interrupt status.
Expose this function externally to allow other users to check interrupt
status in a manner which will work for both cortex-A and cortex-M .
Usage:
bool disabled = get_interrupts_disabled();
> Update function get_interrupts_disabled() to return a bool value rather

- hal/common/SPI.cpp
Prevent mismatch between _owner and peripheral configuration. In the previous
implementation, the following code would leave the peripheral in an inconsistent
state:
```
SPI spi1(...);      // _owner is NULL, peripheral config is 1
spi1.transfer(...); // _owner is 1, config is 1
SPI spi2(...);      // _owner is 1, config is 2
spi1.transfer(...)  // 1 thinks it still owns peripheral, doesn't reconfigure
```
@0xc0170
> SPI: Properly aquire peripheral in constructor

- hal/targets.json
- hal/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/TARGET_EFM32GG_STK3700/PeripheralPins.c
- hal/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/TARGET_EFM32HG_STK3400/PeripheralPins.c
- hal/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/TARGET_EFM32LG_STK3600/PeripheralPins.c
- hal/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/TARGET_EFM32WG_STK3800/PeripheralPins.c
- hal/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/TESTS/spi/basic-spi/main.cpp
- hal/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/dma_api.c
- hal/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/gpio_irq_api.c
- hal/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/lp_ticker.c
- hal/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/pwmout_api.c
- hal/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/rtc_api.c
- hal/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/sleep.c
- hal/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/spi_api.c
Update HAL implementation for EFM32 devices:
* Add delay parameter for greentea test runs, to make test runner wait long enough for kit to reboot after flashing
* Use mbed critical section implementation instead of emlib implementation
* Refactor SPI HAL implementation, and add comprehensive test
* Fix peripheral ownership bug in SPI API found during the HAL refactoring
* Backport some PWM and RTC fixes from mbed OS 3
@0xc0170
> [EFM32] Update HAL implementation

- hal/targets/hal/TARGET_STM/TARGET_STM32L0/us_ticker.c
As we discussed here #1743 the *stabilization* of the timer for `STM32L0` targets do not do the trick. Because it cause also the fail of `MBED_23` for all the `STM32L0` except `NUCLEO_L073RZ`, we should remove it.
```
+--------+---------------------+-----------+---------+------------------+--------------------+---------------+-------+
| Result | Target              | Toolchain | Test ID | Test Description | Elapsed Time (sec) | Timeout (sec) | Loops |
+--------+---------------------+-----------+---------+------------------+--------------------+---------------+-------+
| OK     | NUCLEO_L053R8[CA2B] | uARM      | MBED_23 | Ticker Int us    |        11.4        |       15      |  1/1  |
| OK     | NUCLEO_L073RZ[F55F] | uARM      | MBED_23 | Ticker Int us    |       11.37        |       15 …
```
> [STM32L0XX] Remove stabilization of the timer

- hal/targets.json
- tools/targets.py
- tools/toolchains/__init__.py
- tools/toolchains/arm.py
- tools/toolchains/gcc.py
- tools/toolchains/iar.py
This is an continuative work of PR #1909 and is a suggestion to discuss the problem of two possible Cortex M7 variants: with single or with double precision fpu. 
- creating new core name Cortex_M7F_DP for targets with a double precision fpu
- adding new core name to arm.py to set compiler/linker flags to a double precision fpu when configured in target.json; current state: every Cortex_M7F is configured with single precision fpu
- up to now: gcc wrote flag for a double precision fpu -> target with STM32F746 crashes when using double variables - mcu has only single precision fpu
-changing gcc.py to use single precision for Cortex-M7F und double precision for Cortex_M7F_DP
tested with NUCLEO_F746, NUCLEO_F767 and build.py+make.py and exporting with project.py + compiling/flashing
> fpu with single/double precision - bugfix and extension

- hal/targets/hal/TARGET_STM/TARGET_STM32F3/TARGET_NUCLEO_F303K8/device.h
On NUCLEO_F303K8, RTC clk is on LSI (no LSE connected)
> [NUCLEO_F303K8] fix MBED_16.

- tools/export/exporters.py
- tools/toolchains/gcc.py
Problem
----------
when in target.json ```"default_build": "small"``` is configured and GCC_ARM is used
- build.py+make.py
- uses linker option --specs=nano.specs
- macro MBED_RTOS_SINGLE_THREAD is defined
- exporting with project.py + make Makefile
- doesn't use the linker option --specs=nano.specs
- doesn't contain macro MBED_RTOS_SINGLE_THREAD
results with current master branch
----------------------------------
```
build.py -m NUCLEO_F303K8 -t GCC_ARM
make.py -m NUCLEO_F303K8 -t GCC_ARM -n MBED_BLINKY
```
Result:
| Module    | .text | .data | .bss |
|-----------|-------|-------|------|
| Fill      |    31 |     0 |    9 |
| Misc      | 12397 |   136 |  607 |
| Subtotals | 12428 |   136 |  616 |
```
project.py -m NUCLEO_F303K8 -i gcc_arm -n MBED_BLINKY -b
make
```
Result: …
> [bugfix gcc_arm] build+make <-> export project+make: different results

- tools/export/gcc_arm_common.tmpl
- tools/export/gccarm.py
- tools/toolchains/__init__.py
Also, fix a few bugs along the way:
- python barf when something in features is None
> [Exporter-gcc_arm] do builds from project directory when --source is specified

- tools/singletest.py
- tools/test_api.py
- tools/test_exporters.py
> Adds a simple text file report format

- tools/build_api.py
- tools/memap.py
- tools/test.py
- tools/test_api.py
- tools/toolchains/__init__.py
When users are building tests with `mbed compile --tests` whey will by default
get memory map breakdown report.
This can be suppressed in the future with command line switch. For now it is
visible each time users build test cases.
List is sorted by project name created with `build_project` API.
Changes:
* `build_api` got new aggregation function `print_build_memory_usage_results()` to print summary from small 'JSON' partial reports inside build report.
* We can now generate memory usage reports for all toolchains / targets per build (within test.py). This can be extended to be used with other workflows like `make.py` or `build.py`.
* Build reports got new key-value `"memory_usage"` used to store `memap`'s structure with memory usages.
* I've rebased and will clean history / squash this PR …
> [Tools] Add summary for test building

- requirements.txt
We need to be more explicit with the required version of tools.
See this PR: https://github.com/ARMmbed/mbed-os/pull/386
@sg- @screamerbg
> Install correct version of tools

- hal/api/critical.h
- hal/common/critical.c
Currently there is no cas instrinsics for pointers. This encourages users to use the u32 versions, adding unecessary platform restrictions and unecessary casts.
Since using cas instructions with pointers is debatably their most common use, I omitted a suffix from the new functions:
```
bool core_util_atomic_cas_ptr(void **ptr, void **expectedCurrentValue, void *desiredValue);
void *core_util_atomic_incr_ptr(void **valuePtr, ptrdiff_t delta);
void *core_util_atomic_decr_ptr(void **valuePtr, ptrdiff_t delta);
```
This helps https://github.com/mbedmicro/mbed/pull/2051
cc @c1728p9
> Added cas instrinsics for pointer values

- rtos/rtx/TARGET_CORTEX_A/RTX_CM_lib.h
Hi
Renesas modified the timing at which mbed_main() is called in IAR compiler.
Because we failed about test "mbed call before main" in IAR compiler.
Ref:https://github.com/mbedmicro/mbed/pull/2018#issuecomment-229236123
Regards,
Tomo Yamanaka
> Modify the timing at which mbed_main() is called in IAR compiler.

- hal/common/critical.c
Sorry about the breakage, a last minute change went unnoticed since it only created a warning on GCC.
for #2126
> Fixed typo in incr/decr function

- hal/targets/hal/TARGET_Freescale/TARGET_KSDK2_MCUS/api/i2c_api.c
I2C slave address on TARGET_KSDK2_MCUS is set as `(user_input_address | 1) << 1`.However, the bit shift is needless.So, this commit removes it.
(My mbed account is `mrks`.I have accepted `contributor_agreement`.)
> [KSDK2_MCUS] Fix I2C slave address

- hal/targets/hal/TARGET_STM/TARGET_STM32F1/rtc_api.c
- hal/targets/hal/TARGET_STM/TARGET_STM32F3/rtc_api.c
- hal/targets/hal/TARGET_STM/TARGET_STM32F4/rtc_api.c
- hal/targets/hal/TARGET_STM/TARGET_STM32F7/rtc_api.c
```
Test summary:
+--------+---------------------+-----------+---------+------------------+--------------------+---------------+-------+
| Result | Target              | Toolchain | Test ID | Test Description | Elapsed Time (sec) | Timeout (sec) | Loops |
+--------+---------------------+-----------+---------+------------------+--------------------+---------------+-------+
| OK     | NUCLEO_F410RB[F63D] | uARM      | MBED_16 | RTC              |        5.43        |       20      |  1/1  |
| OK     | NUCLEO_F410RB[F63D] | IAR       | MBED_16 | RTC              |        5.41        |       20      |  0/1  |
| OK     | NUCLEO_F410RB[F63D] | ARM       | MBED_16 | RTC              |       22.07        |       20      |  1/1  |
| OK     | NUCLEO_F410RB[F63D] | GCC_ARM   | MBED_16 | RTC …
```
> Fix #2027 Add timeinfo.tm_isdst = -1 to pass MBED_16 test with IAR.

- hal/targets/hal/TARGET_Freescale/TARGET_KSDK2_MCUS/api/analogin_api.c
Set the channel mux before taking a reading rather than on
initialization.  This allows ADC pins on both mux A and B to be used in
the same application.
> KSDK2 - set ADC mux before taking measurement

- hal/targets/hal/TARGET_Freescale/TARGET_KSDK2_MCUS/TARGET_K64F/storage_driver.c
Together with other minor changes.
This will bring the state of the K64F driver to the point where we can submit a fix for the read-while-write issue in isolation.
@simonqhughes 
follows from https://github.com/mbedmicro/mbed/pull/2117
> introduce a context structure to encompass global state in the K64F Storage driver

- hal/common/retarget.cpp
- mbed_lib.json
Adds `core.stdio-baud-rate configuration` option. Defaults to 9600 for backwards compatibility. Mirrors the `core.stdio-convert-newlines` option.
This came up in an offline discussion again. The currently supported mechanism for changing baud rate is through the SerialBase::baud member function. This works great for implementing drivers, but has shown to be limiting for applications, where the owner of the serial connection is less well defined.
Previous discussions:
- https://github.com/mbedmicro/mbed/issues/1969
- https://github.com/mbedmicro/mbed/pull/1988
- https://github.com/ARMmbed/mbed-os/issues/449
cc @sg-, @bogdanm, @0xc0170
> Add config option for stdio baud rate

- hal/targets.json
- hal/targets/hal/TARGET_Freescale/TARGET_KSDK2_MCUS/TARGET_K64F/TARGET_FRDM/PeripheralPins.c
- hal/targets/hal/TARGET_Freescale/TARGET_KSDK2_MCUS/TARGET_K64F/serial_api.c
- hal/targets/hal/TARGET_Freescale/TARGET_KSDK2_MCUS/api/PeripheralPins.h
This commit adds hardware flow control capabilities for the K64F family
of MCUs. This is a backport of these commits:
https://github.com/ARMmbed/mbed-hal-ksdk-mcu/commit/9bfcfd0572d1835a889779515a3b612262785a46
https://github.com/ARMmbed/mbed-hal-frdm-k64f/commit/77042cc9453c91957b04e9bd200a2dd928723e5a
with a few changes:
- since the current version of KSDK doesn't seem to have APIs for
manipulating the flow control settings, we change the peripheral
registers directly.
- updated pin maps for RTS/CTS in accordance to the K64F datasheet.
> Added flow control for K64F

- tools/utils.py
This commit adds information about the location of problematic JSON
files when reporting a JSON parsing error.
Before this commit:
```
[ERROR] Expecting property name: line 7 column 9 (char 188)
```
After this commit:
```
Error parsing 'core/mbed_lib.json':
[ERROR] Expecting property name: line 7 column 9 (char 188)
```
> More verrbose errors for JSON parsing

- tools/build.py
- tools/colorize.py
- tools/make.py
- tools/options.py
- tools/settings.py
- tools/test.py
- tools/toolchains/__init__.py
These commits add colorization to all of the short form Warning and Error messages generated by the compiler when the --color switch is provided on the command line. The default colorization will make Warnings Yellow and Errors Red, but can be changed by the user, in `mbed_settings.py` if they find yellow and red unreadable or ugly.
Affects these top level scripts:
- `build.py`
- `make.py`
- `test.py`
Therefore the mbed subcommands compile, and test are also affected.
> Colorized the short Warnings/Errors generated by the toolchains

- docs/ignoring_files_from_build.md
Add documentation about the `.mbedignore` file.
Please wait for someone to check the language before merging.
> Document the .mbedignore file

- tools/build_api.py
before:
```
$  python tools/build.py  -m NRF51_DK --source . -t GCC_ARM,ARM --build build --silent
[SNIP]
Completed in: (3.39)s
Build skipped:
* GCC_ARM::NRF51_DK
* ARM::NRF51_DK
```
after:
```
$  python tools/build.py  -m NRF51_DK --source . -t GCC_ARM,ARM --build build --silent
[SNIP]
Completed in: (3.43)s
Build successes:
* GCC_ARM::NRF51_DK
* ARM::NRF51_DK
```
> [tools/build_api] Retrun truthy value on success from build_*

- tools/build.py
by skipping unsupported combinations
before:
```
$ python tools/build.py -t IAR -m NRF51_DK --source . --build build
[SNIP]
Compile: us_ticker.c
#error Compiler not supported.
^
"Z:\home\jimbri01\src\mbedmicro\mbed\hal\targets\hal\TARGET_NORDIC\TARGET_MCU_NRF51822\us_ticker.c",382  Fatal error[Pe035]: #error directive: Compiler not supported.
Fatal error detected, aborting.
#error Compiler not supported.
^
"Z:\home\jimbri01\src\mbedmicro\mbed\hal\targets\hal\TARGET_NORDIC\TARGET_MCU_NRF51822\us_ticker.c",382  Fatal error[Pe035]: #error directive: Compiler not supported.
Fatal error detected, aborting.
Completed in: (8.96)s
Build failures:
* IAR::NRF51_DK
```
after:
```
$ python tools/build.py -t IAR -m NRF51_DK --source . --build build
IAR::NRF51_DK skipped: toolchain not supported …
```
> [tools-build.py]Enforce supported toolchains

- hal/common/retarget.cpp
Remove the 2nd call of mbed_sdk_init in __iar_argc_argv
> Fix issue #2124: IAR no rtos

- hal/targets/hal/TARGET_STM/TARGET_STM32F0/rtc_api.c
- hal/targets/hal/TARGET_STM/TARGET_STM32F1/rtc_api.c
- hal/targets/hal/TARGET_STM/TARGET_STM32F3/rtc_api.c
- hal/targets/hal/TARGET_STM/TARGET_STM32F4/rtc_api.c
- hal/targets/hal/TARGET_STM/TARGET_STM32F7/rtc_api.c
- hal/targets/hal/TARGET_STM/TARGET_STM32L0/rtc_api.c
- hal/targets/hal/TARGET_STM/TARGET_STM32L1/rtc_api.c
- hal/targets/hal/TARGET_STM/TARGET_STM32L4/rtc_api.c
- The `MBED_16` fail on `STM32F0` targets.
- None of the ST targets are able to `set_time(0) => year 1970` correctly.
They use a BCD format to store the date in the RTC. The year is store on 2 * 4 bits. Because the first year is reserved to see if the RTC is init, the supposed range is `01-99`. The idea is to cover the standard range from `1970` to `2038` (limited by the 32 bits of `time_t`).
The fix move the RTC range to match the standard one. The idea is to keep the year `1970` and the leap years synchronized. By moving it `68` years forward from `1970`, it become `1969-2067` which include `1970-2038`. `68` is also a multiple of `4` so it let the leap year synchronized. Between `1904` and `2096` there is a leap year every 4 years.
They don't use a BCD format but a 32bit register for …
> [STM32XX] Fix RTC minimum date

- hal/targets/hal/TARGET_STM/TARGET_STM32F4/serial_api.c
- hal/targets/hal/TARGET_STM/TARGET_STM32F7/serial_api.c
- hal/targets/hal/TARGET_STM/TARGET_STM32L1/serial_api.c
- hal/targets/hal/TARGET_STM/TARGET_STM32L4/serial_api.c
Reported in Issue #2119
There was some inconsistency in serial interrupt handling accross STM32
serial_api.c implementation. In case application wants to be notified of
Tx interrupt, it is mainly interested in transmission complete information,
which is the _TC interrupt.
The _TXE (Transmit Data REgister Empty) is used only within driver
in case SERIAL_ASYNCH is being supported to make the transmission
more efficient.
> [STM32] Serial interrupt TC vs. TXE

- tools/export/iar.py
- tools/export/uvision4.py
- tools/export/uvision5.py
To speed up project.py, use @property for TARGETS.
When exporters are used, it would ask progen for support for all targets
(number of tools x number of targets).
```
Profiling:
Before the change:
1    0.000    0.000    0.010    0.010 definitions.py:113(get_tool_definition)
824    0.004    0.000    2.990    0.004 definitions.py:124(is_supported)
1    0.000    0.000    0.000    0.000 definitions.py:145(get_debugger)
1    0.002    0.002    0.044    0.044 definitions.py:15(<module>)
384    0.002    0.000    2.986    0.008 definitions.py:26(_load_record)
1    0.000    0.000    0.000    0.000 definitions.py:32(ProGenMcus)
992    0.055    0.000    1.959    0.002 definitions.py:34(__init__)
1376    0.002    0.000    0.003    0.000 definitions.py:40(get_mcus)
384    0.001    0.000    1.070 …
```
> Exporters - progen TARGETS lazy evaluated

- requirements.txt
- tools/export/__init__.py
- tools/export/exporters.py
- tools/export/iar.py
- tools/export/uvision4.py
- tools/export/uvision5.py
- tools/project.py
- tools/project_api.py
- tools/test/export/build_test.py
I have separated some of the exporter logic in project.py to project_api.py. I did this because I wanted to use some of that functionality in the new build_test script. build_test allows testing of ide builds (currently supports iar, uvision, and uv5) using progen. 
build_test examples:
builds blinky for iar and k64f
```
python build_test.py -i iar -t MBED_BLINKY -m K64F
```
build blinky and Hello World test for all targets on all (supported) ides
```
python build_test.py -t MBED_BLINKY MBED_10
```
builds all tests (current default is just blinky but you can specify more with -t) for all progen targets on all ides 
```
python build_test.py 
```
Revision of [this](https://github.com/mbedmicro/mbed/pull/2080) PR.
> IDE build tests with progen

- rtos/rtx/TARGET_CORTEX_A/rt_HAL_CA.h
- rtos/rtx/TARGET_CORTEX_A/rt_HAL_CM.h
- rtos/rtx/TARGET_CORTEX_M/rt_HAL_CM.h
Suppress warnings about ARMCC warnings about the __ldrex and __strex
intrinsics to match CMSIS 5.
> Suppress warnings about deprecated __ldrex/strex

- tools/memap.py
* This change is clean-up after #2047 (*Add memory usage summary for test building*)
* In code of memory usage summary columns were shortened and names changed a bit,
see [here](https://github.com/mbedmicro/mbed/pull/2047/files?w=1#diff-f9cb941bde5647a5763e18fc220efc51R410)
* Change was done to make columns not so wide for user.
* This change did not propagate to JSON and CSV reports generated by memap script.
* There is a need to align memap CSV report fields (summary columns) with what
is in code now. This discrepancy may create problems when generating reports
in the future. All columns should have the same name.
* memap CSV summary fields names changes:
* `total_static_ram` -> `static_ram`
* `allocated_heap` -> `heap`
* `allocated_stack` -> `stack`
See example of discrepancy:
* …
> [Tools] Replace in memap CSV report fields

- tools/project.py
Regression from #2179. Fixes #2184.
Before:
```
python tools\project.py -m KL25Z -p 0 -i gcc_arm
* KL25Z::gcc_arm      C:\Code\git_repo\github\mbed\.build\export\.temp\MBED_A1
```
With this patch:
```
python tools\project.py -m KL25Z -p 0 -i gcc_arm
* KL25Z::gcc_arm     mbed\.build\export\MBED_A1_gcc_arm_KL25Z.zip
```
@sarahmarshy @theotherjimmy @screamerbg
> project - zip and src check if empty fix

- tools/export/exporters.py
- tools/export/iar.py
- tools/export/uvision4.py
- tools/export/uvision5.py
@bogdanm @theotherjimmy Please review. This is a fix for backward compatibility as our tools use for instance ``if is in Exporter.TARGETS`` . I found one more solution to this via metaclass, but was less clear to me. Any suggestions welcome.
Tested with the same command as reported, plus some others (uvision4,5 and iar as all of them introduced TARGETS as property):
``tools\project.py -c -m NUCLEO_L432KC -p 0 -i uvision5``
cc @svastm
> Fix issue2183

- tools/toolchains/gcc.py
This commit includes
- Changing build option parameter from -O2 to -Os to reduce flash size of the
final binary pacakge.
The original parameter of -O2 is kept to circumvent the error
http://gcc.gnu.org/bugzilla/show_bug.cgi?id=46762 .
But this error has been long fixed and released in latest 4.9.x GCC compiler.
This change is necessary to reduce the generated binary size of mbed Client component to
avoid problem of getting images over 512 kB which is causing application to crash because of
Configuration Store problem https://github.com/ARMmbed/configuration-store/issues/21
> Changing -O2 parameter to -Os

- tools/export/exporters.py
- tools/export/uvision4.py
- tools/export/uvision5.py
- tools/settings.py
- tools/synch.py
- tools/targets.py
- tools/test_api.py
- tools/toolchains/__init__.py
- tools/toolchains/arm.py
- tools/toolchains/gcc.py
- tools/toolchains/iar.py
- tools/utils.py
* added/improved chroot support globally
* added RESPONSE_FILES flag to support optional response files (on linux the cmd param length is 2 megabytes). Default True
* added unified handling for archive and link response file (similar to includes)
* added COMPILE_C_AS_CPP flag to support compiling of c files as cpp. Default False
* added mbedToolchain.init() for post __init__ hooks
* added support to identify compiler warning/error column (supports ARMCC, GCC and IAR). Errors/warnings now report file@line,col
* added global TOOLCHAIN_PATHS which allows overriding/changing of the toolchain paths. Also simplified ARM-related paths
* added target.json to mbed library release (by @0xc0170)
* added caching to mbedToolchain.need_update() to reduce IO hits
* improved run_cmd() performance by …
> [Tools] mbed Online Build System support and improvements

- hal/api/AnalogIn.h
- hal/api/FileBase.h
- hal/api/I2C.h
- hal/api/SingletonPtr.h
- hal/common/AnalogIn.cpp
- hal/common/FileBase.cpp
- hal/common/I2C.cpp
- hal/common/retarget.cpp
- rtos/rtx/TARGET_CORTEX_A/RTX_CM_lib.h
- rtos/rtx/TARGET_CORTEX_M/RTX_CM_lib.h
Add a singleton wrapper class and use this for global mutexes
> Singleton support

- rtos/rtos/Semaphore.h
Currently Semaphore can not be instantiated without an explicit count as a constructor argument. This limits where Semaphores can be declared and requires explicit initialization in several annoying places, such as in member variables and SingletonPtr targets.
This adds a default count of 0, which has shown to be the most common initial value used for semaphores.
cc @0xc0170, @c1728p9
> [rtos] Add default constructor for Semaphore

- tools/toolchains/__init__.py
This commit adds a check for configuration data changes. If a change in
configuration data is detected, all the sources in the tree are rebuilt.
This is a fix for #2073. #2162 was originally proposed as a fix, but it
was agreed that `--preinclude` is a more convenient way to include
configuration data, since it can be used to change the behaviour of
source files that don't include "mbed_config.h" directly, which is a big
advantage when importing 3rd party source trees. Compared to #2162, this
commit has the disadvantage of rebuilding all the source files if a
configuration change is detected, but it was agreed that the advantage
of using `--preinclude` outweighs the disadvantage of the increased
compilation time.
> Rebuild sources if configuration is changed

- hal/targets/cmsis/TARGET_STM/TARGET_STM32F1/TARGET_BLUEPILL_F103C8/hal_tick.c
I can't find a PR nor issue for this code. It appears there are 2 merge commits for this code (?!) but none of them has any description (https://github.com/mbedmicro/mbed/commit/7fd0a9b875586041dd272e8c6e8a8d25f661df53 as merge commit and https://github.com/mbedmicro/mbed/commit/c8fc07928a748d75fbf030f8f2edb41bb5a9319e with code). The only information I have is that it fixes timer interrupt handler for couple of STM32 platforms. The branch that has been merged is https://github.com/svastm/mbed/commits/fix_int_handler and BLUEPILL_F103C8 was omitted in commit https://github.com/svastm/mbed/commit/bb565984c1c76b37273b5d79dcd69192c0f0c9d2.
> [BLUEPILL_F103C8] Fix interrupt handler

- TESTS/mbed_drivers/callback/main.cpp
- hal/api/Callback.h
Before, the following results in a compilation error:
``` cpp
const struct Object *obj;
void obj_doit(const Object *obj);
Callback<void()> cb(obj, obj_doit);
```
This is especially noticable when migrating from the old Thread constructor, which previously _required_ const.
Fixed by adding an additional const_cast:
``` cpp
void *_obj = const_cast<void*>(static_cast<const void*>(obj));
```
Could alternatively be fixed with C cast, not idiomatic C++ but cleaner:
``` cpp
void *_obj = (void*)obj;
```
cc @bridadan, @c1728p9
> [api] Fix handling of const objects in Callback class

- tools/project.py
Original Message from @bridadan:
> This fixes issue #1864.
```
File "..\mbed\workspace_tools\project.py", line 176, in <module>
setup_user_prj(project_dir, test.source_dir, test.dependencies)
File "C:\mbed\workspace_tools\export\__init__.py", line 170, in setup_user_prj
copy_tree(lib_path, join(user_lib, basename(lib_path)))
File "C:\mbed\workspace_tools\export\__init__.py", line 152, in copy_tree
copytree(src, dst)
File "C:\Python27\lib\shutil.py", line 171, in copytree
names = os.listdir(src)
WindowsError: [Error 3] The system cannot find the path specified: 'C:\\mbed\\.build\\rtos/*.*'
```
```
$python workspace_tools\project.py -c -m NUCLEO_F746ZG -p 96 -i uvision5
Failed exports:
* NUCLEO_F746ZG::uvision5     Library path …
```
> Preventing a traceback when a library is not built during export

- tools/build.py
- tools/make.py
- tools/project.py
- tools/test.py
- tools/utils.py
Resolves #2081 by making any parent of the repo (or the repo dir itself)
passed to --build fail at argument parsing time.
> [tools-build,make,test] Disallow parent of repo as --build args

- hal/targets/hal/TARGET_NXP/TARGET_LPC15XX/pwmout_api.c
- hal/targets/hal/TARGET_NXP/TARGET_LPC15XX/us_ticker.c
Re-wrote µs_ticker implementation to use SCT3 instead of RIT in order to fix a serious rollover bug at 1:11:34 (#1699).
> [LPC15XX] Fixed µs_ticker implementation

- rtos/rtos/RtosTimer.cpp
- rtos/rtos/RtosTimer.h
Updated the `RtosTimer` class to use `Callback` in order to be consistent with the updated `Thread` class.
> [RTOS] Updated RtosTimer to use Callback

- hal/api/FunctionPointer.h
FunctionPointer/FunctionPointerArg0/FunctionPointerArg1 has been replaced by the more flexible Callback template class.
For the motivation behind adopting the Callback class: https://github.com/mbedmicro/mbed/pull/1783
Feel free to discuss if you all feel strongly about keeping the FunctionPointer class.
cc @0xc0170, @sg-
> [api] Mark FunctionPointer and friends as deprecated

- hal/targets/hal/TARGET_ARM_SSG/TARGET_BEETLE/PinNames.h
Beetle board is built to optimize power consumption therefore does not
provide on-board LEDs.
This patch adds a comment in PinNames in order to clarify that the
Emulated LEDs are provided for compatibility reasons with the MBED test
suite.
Signed-off-by: Vincenzo Frascino <vincenzo.frascino@arm.com>
> [BEETLE] Add comment to clarify LEDs Emulation

- hal/targets.json
A lot of ST targets are defined with a `default_build: "small"` and a `default_toolchain: "uARM"`. It allow to use only one thread in the RTOS.
This commit make the st targets with less than `64KB` of FLASH use the `small` build and `uARM`. The ones with FLASH >= 64KB use `ARM` and `standard` build.
> [STM32XX] Fix default build

- features/net/network-socket/CellularInterface.h
- features/net/network-socket/DnsQuery/DnsQuery.cpp
- features/net/network-socket/DnsQuery/DnsQuery.h
- features/net/network-socket/EthInterface.h
- features/net/network-socket/MeshInterface.h
- features/net/network-socket/NetworkInterface.h
- features/net/network-socket/NetworkStack.cpp
- features/net/network-socket/NetworkStack.h
- features/net/network-socket/Socket.cpp
- features/net/network-socket/Socket.h
- features/net/network-socket/SocketAddress.cpp
- features/net/network-socket/SocketAddress.h
- features/net/network-socket/TCPServer.cpp
- features/net/network-socket/TCPServer.h
- features/net/network-socket/TCPSocket.cpp
- features/net/network-socket/TCPSocket.h
- features/net/network-socket/UDPSocket.cpp
- features/net/network-socket/UDPSocket.h
- features/net/network-socket/WiFiInterface.h
- features/net/network-socket/nsapi.h
- features/net/network-socket/nsapi_types.h
This patch introduces the network-socket API into to core mbed repo.
cc @sg-, @c1728p9
> Introduce the network-socket API to mbed

- hal/api/mbed.h
So that apps don't need to include "rtos.h" explicitly anymore.
> Includre rtos.h in mbed.h if present

- tools/config.py
- tools/test/config_test/test23/test_data.py
- tools/test/config_test/test25/test_data.py
Modified '_process_config_and_overrides' to update cumulative attributes based on cumulative overrides found during walking config files.
This should remove most of the disparity between the config target cumulative overrides and cumulative attributes set in targets.json. These cumulative overrides are updated after the global target
instantiation though, which may cause internal build tool state dependent on cumulative attributes to not correctly reflect all cumulative overrides.
Example:
``` json
{
"K64F": {
"target.features_add": ["COOL_THING"],
"target.extra_labels_add": ["COOL_THING_SUPPORTED"],
"target.macros_add": ["COOL_THING_IS_HERE"],
"target.device_has_add": ["COOL_THING_YES"]
}
}
}
```
cc @sg-, @screamerbg, @theotherjimmy
related #2209
> [tools] Modified config to aggregate cumulative overrides against targets

- tools/build_api.py
- tools/toolchains/__init__.py
Introduce prepare_toolchain() which handles:
* de-duplication of src_paths
* config initialization
* toolchain initialization
* toolchain flags
* returns toolchain object
Introduce scan_resources() which handles:
* scanning of sources
* scanning of include dirs
* inclusion of addition include dirs
* returns resources object with scanned resources
Apply prepare_toolchain() and scan_resources() in:
* get_config()
* build_project()
* build_library()
> [Tools] Unify common routines in build_api.py

- features/net/network-socket/SocketAddress.cpp
- features/net/network-socket/SocketAddress.h
Expression needed to init to zero a simple POD struct:
``` cpp
// Before (valid in C99/C++11/G++)
nsapi_addr_t addr = (nsapi_addr_t){}
// After (valid in C++03, invalid in C)
nsapi_addr_t addr = nsapi_addr_t()
```
cc @sg-, @c1728p9, @bridadan
> [nsapi] Fixed iar compilation issue with value initializer

- tools/build_api.py
There was a typo in the `build_api.py` file. This didn't surface until recently after some patches were merged. It's causing a traceback in the tools currently.
> Fixed traceback in build_api

- docs/TESTING.md
- hal/api/AnalogIn.h
- hal/api/AnalogOut.h
- hal/api/BusIn.h
- hal/api/BusInOut.h
- hal/api/BusOut.h
- hal/api/CallChain.h
- hal/api/DigitalIn.h
- hal/api/DigitalInOut.h
- hal/api/DigitalOut.h
- hal/api/InterruptIn.h
- hal/api/PwmOut.h
- hal/api/Timer.h
- hal/api/platform.h
- hal/common/BusIn.cpp
- hal/common/BusInOut.cpp
- hal/common/BusOut.cpp
- hal/common/InterruptIn.cpp
- hal/common/Timer.cpp
- libraries/tests/utest/bus/busout_ut.cpp
By default, APIs with overloaded operators are enabled. Remove the macro that was gating this but enabled by default in the header file.
> Remove macro for operators. Enable these as default behavior

- features/net/network-socket/SocketAddress.cpp
_stack->gethostbyname looks deceptively like it completely sets the socket address value, however port is not provided via DNS resolution.
cc @sg-, @c1728p9
> [nsapi] Fix missing port assignment in DNS constructor for SocketAddress

- tools/toolchains/gcc.py
Remove special case targets which have floating point enabled in
Newlib Nano from gcc.py.  To enable floating point printf/scanf
for a target configure it to use the 'standard' default build in
targets.json rather than 'small'.
> Remove floating point formatting in newlib nano

- tools/test_api.py
This mitigates the Windows paths issue by shortening the test binary name to just the test case folder name instead of the full unique test name used by the tools. This doesn't solve the Windows path limit of 260 characters, but it does reduce the characters used.
The changes should be transparent to the building and test process, the only change should be the binary name has changed.
**Todo**
@PrzemekWirkus will renaming the test binaries affect the host test discovery in htrun?
> Changing name of test binaries to just test case folder name.

- TESTS/mbedmicro-rtos-mbed/threads/main.cpp
This stack size is adjusted for NRF51 and NRF52 based targets.
This should help: https://github.com/mbedmicro/mbed/pull/2211
> Define stack size of the threads spawned by RTOS threads test.

- rtos/rtx/TARGET_CORTEX_M/cmsis_os.h
In cmsis_os.h OS_TIMERS is undefined unless the timer thread is
disabled, in which case it is defined to 0. When comparing against
an undefined value, the undefined value will evaluate as if it were
0. Because of this the MAIN_THREAD_ID was always set to 0x1.
This patch fixes that problem by checking if OS_TIMERS is defined
before comparing it to 0.
This problem only effects IAR since it has a different heap/stack
layout. GCC_ARM and ARM have a dedicated stack region so
the presence of a guard word and stack checking does not cause
problems.
This problem manifested on the NRF51_DK in the pull request
https://github.com/mbedmicro/mbed/pull/2211
as a c_strings test failure on floating point. This is because the
guard word of the main stack overlapped with standard library
data used by …
> Fix MAIN_THREAD_ID check

- hal/targets/cmsis/TARGET_STM/TARGET_STM32F1/TARGET_BLUEPILL_F103C8/hal_tick.c
This commit adds to TARGET_BLUEPILL_F103C8 changes that have been introduced with PR #2192 for other STM32_F1 targets, specifically in https://github.com/mbedmicro/mbed/commit/a227a9438c834032beb292a06a62b471eb487a02
> [BLUEPILL_F103C8] Sleep code refactor

- hal/targets.json
- hal/targets/hal/TARGET_Freescale/TARGET_KLXX/rtc_api.c
Only early versions of the interface firmware provided a clock for the RTC that was used. This has long been depreciated since it also routed the same pin to an ADC on the arduino connector which caused wiring conflicts
> Remove support for the RTC

- hal/hal/storage_abstraction/Driver_Storage.h
- hal/targets/hal/TARGET_Freescale/TARGET_KSDK2_MCUS/TARGET_K64F/storage_driver.c
- Discover flash integrity failures during erase and program
- Optimize away erase when target range is already erased. 
- Switch to using more specific names in DEVICE_STORAGE_CONFIG_*
- Salvage  changes from https://github.com/mbedmicro/mbed/pull/2150 which are still useful
Note: This change-set doesn't have the following (as requested by @mjs-arm):
> - MUST - Hardwire the K64F storage driver to ASYNC only operation (not user  >configurable).
We still need to resolve if ASYNC operation is to be forced since there are some internal use cases which rely upon synchronous operation.
review: @0xc0170 @sg- 
notify: @mjs-arm @marcuschangarm @simonqhughes @meriac
> Improvements to k64 internal-flash storage driver

- hal/targets.json
- tools/build_api.py
- tools/build_release.py
- tools/utils.py
This introduces the concept of "release versions" to the tools.
Previously, the condition for including a target in a release was decided by a `release` key being set to `true` in `hal/targets.json`. This doesn't have enough granularity when we release multiple versions of mbed.
This PR changes the `release` key in `hal/targets.json` to an array of strings, where each member is a version that the target supports. Currently the valid versions are `"2"` and `"5"`.
You can now build up lists of these release configurations by calling the new function `get_mbed_official_release` in `build_api.py`. This function add checks for invalid target configurations in a release. This is enforced whenever it is called, preventing invalid targets from coming into the release.
It updates the …
> Release versions

- tools/build.py
- tools/make.py
- tools/project.py
- tools/test.py
- tools/utils.py
Entry points affected:
- build.py
- make.py
- test.py
- project.py
They will install every dependency within `requirements.txt` that cannot be found with `pkg_resources.working_set.require`
> Force installation of dependencies in entry points

- docs/config_system.md
The configuration system uses `mbed_config.h` to export configuration
data, but when this change was made, the documentation was not properly
updated. This commit updates the documentation with the correct
behaviour of the configuration system.
> Documentation updates for the configuration system

- docs/config_system.md
Adds the much needed documentation over the cumulative attributes.
@bogdanm, please review and let me know what you feel needs to be added.
> [docs] Added documentation over the cumulative attributes

- tools/config.py
- tools/test/config_test/test27/lib1/mbed_lib.json
- tools/test/config_test/test27/mbed_app.json
- tools/test/config_test/test27/test_data.py
Basically this:
```
a | b - c  !=  (a | b) - c
```
Prevented cumulative overrides from being correctly removed.
cc @screamerbg
> [tools] Fix precedence issue in cumulative attribute set-arithmetic

- hal/targets/hal/TARGET_NORDIC/TARGET_NRF5/LF_Clock_config.md
This PR bring documentation (a *.md file) regards nRF51/nRF52 Low frequency clock configuration feature using mbed configuration system.
> documentation regards nRF51/nRF52 Low frequency clock configuration

- hal/api/AnalogIn.h
- hal/api/AnalogOut.h
- hal/api/BusIn.h
- hal/api/BusInOut.h
- hal/api/BusOut.h
- hal/api/CAN.h
- hal/api/FileBase.h
- hal/api/I2C.h
- hal/api/InterruptManager.h
- hal/api/LocalFileSystem.h
- hal/api/PlatformMutex.h
- hal/api/SPI.h
- hal/api/Serial.h
- hal/common/mbed_rtc_time.cpp
- hal/common/retarget.cpp
- libraries/fs/fat/FATDirHandle.h
- libraries/fs/fat/FATFileHandle.h
- libraries/fs/fat/FATFileSystem.h
Remove the critical section in mbed_rtc_time.c and instead use a
mutex to protect this. This function does not need to be interrupt
safe, just thread safe.
This fixes crashes on the GCC_ARM toolchain on the RTC test due to
trying to lock the GCC environment mutex while in a critical section.
Prior to this patch, this failure was likely to occur on STM and LPC
processor families.
> Fix RTC test for LPC and STM families on GCC

- hal/targets.json
The DISCO_F429ZI is enabled for the version 5 release, but the NUCLEO_F429ZI is not currently. This PR turns it on.
The RZ_A1H also satisfies the requirements for the version 5 release, so it is being enabled as well.
> Enable v5 release for NUCLEO_F429ZI and RZ_A1H

- TESTS/mbedmicro-rtos-mbed/basic/main.cpp
- TESTS/mbedmicro-rtos-mbed/isr/main.cpp
- TESTS/mbedmicro-rtos-mbed/mail/main.cpp
- TESTS/mbedmicro-rtos-mbed/mutex/main.cpp
- TESTS/mbedmicro-rtos-mbed/queue/main.cpp
- TESTS/mbedmicro-rtos-mbed/semaphore/main.cpp
- TESTS/mbedmicro-rtos-mbed/signals/main.cpp
- hal/targets.json
- libraries/tests/rtos/mbed/basic/main.cpp
- libraries/tests/rtos/mbed/isr/main.cpp
- libraries/tests/rtos/mbed/mail/main.cpp
- libraries/tests/rtos/mbed/mutex/main.cpp
- libraries/tests/rtos/mbed/queue/main.cpp
- libraries/tests/rtos/mbed/semaphore/main.cpp
- libraries/tests/rtos/mbed/signals/main.cpp
NRF targets with 16K of RAM keep their default_build configuration set to small.
Enabling standard build consume 5K of RAM which is huge on a platform with only 6K of RAM usable.
This PR is a follow up to #2258
> Change default_build from small to standard on NRF based targets with at least 32K of RAM.

- features/FEATURE_BLE/targets/TARGET_NORDIC/TARGET_NRF5/source/btle/btle_clock.h
This patch fix the clock selection for the ble stack on NRF51_DK and NRF52_DK.
Without it, ble not work correctly on NRF52.
> Fix clock selection used by the softdevice on NRF5 based targets.

- hal/api/SPI.h
- hal/common/SPI.cpp
Modified the `SPI` class to use a shared mutex for all instances in response to #2276. This is consistent with `I2C` and others.
> [HAL] Modified SPI to use shared mutex

- hal/targets.json
- tools/build_api.py
This PR enforces that the `default_build` in a target's definition in `hal/targets.json` is set to `standard` to be included in the version 5 release.
This is being enforced because `small` builds do not support multi-threading. This makes the capabilities more consistent across all boards in the version 5 release.
NOTE: This removes the MOTE_L152RC and the LPC11U68
from the version 5 release list because the 'default_build' for these
targets is currently set to 'small'.
> Enforcing 'standard' build for version 5 release

- tools/build.py
- tools/make.py
- tools/project.py
- tools/test.py
- tools/utils.py
Reverts mbedmicro/mbed#2257
Corner cases around local / global / virtualenv use case needs more attention.
> Revert "Force installation of dependencies in entry points"

- hal/targets/cmsis/TARGET_NORDIC/TARGET_NRF5/TARGET_MCU_NRF51822_UNIFIED/TOOLCHAIN_IAR/TARGET_MCU_NORDIC_16K/nRF51822_QFAA.icf
- hal/targets/cmsis/TARGET_NORDIC/TARGET_NRF5/TARGET_MCU_NRF51822_UNIFIED/TOOLCHAIN_IAR/TARGET_MCU_NORDIC_32K/nRF51822_QFAA.icf
The symbols __ICFEDIT_region_RAM_start__ and __ICFEDIT_region_RAM_end__ where not exported by IAR linker script for NRF51.
Those symbols are needed by the nordic SDK.
This patch should fix https://github.com/ARMmbed/mbed-os-example-ble/issues/8
> Export RAM start/stop symbols on NRF51

- tools/export/exporters.py
- tools/export/gcc_arm_common.tmpl
- tools/export/iar.py
> Add missing --preinclude and -input on assembly files

- features/net/FEATURE_IPV4/lwip-interface/lwip_stack.c
Previously the EthernetInterface class was unable to be connected after being brought down. The core issue is that lwip was not designed to be completely brought down due once initialized.
To work around this, the ethernet interface only initializes once and leaves itself up after a disconnect call. The DHCP lease is still released/acquired on disconnect/connect.
This should fix #2334
> [nsapi] Fix issue with reconnecting the ethernet interface

- tools/config.py
- tools/test/config_test/test28/mbed_app.json
- tools/test/config_test/test28/test_data.py
Fixed infinite loop in config scan due to list comparison error.
Previously a scanning for config terminated on comparison of the feature set, however at some point the set was changed to a list. This resulted in non-deterministic failures based on list order.
Added a test specifically for the uvisor feature_add, which revealed the issue.
fixes https://github.com/mbedmicro/mbed/issues/2312
cc @AlessandroA
> [tools] Fixed infinite loop in config scan due to list comparison error

- tools/export/ds5_5.py
resolves https://github.com/ARMmbed/mbed-os-example-blinky/issues/19
> Add toolchain flag to DS-5 exporter

- features/net/FEATURE_IPV4/TESTS/mbedmicro-net/.mbedignore
- features/net/FEATURE_IPV4/TESTS/mbedmicro-net/host_tests/tcp_echo_client.py
- features/net/FEATURE_IPV4/TESTS/mbedmicro-net/host_tests/udp_echo_client.py
- features/net/FEATURE_IPV4/TESTS/mbedmicro-net/nist_internet_time_service/main.cpp
- features/net/FEATURE_IPV4/TESTS/mbedmicro-net/tcp_client_echo/main.cpp
- features/net/FEATURE_IPV4/TESTS/mbedmicro-net/tcp_client_hello_world/main.cpp
- features/net/FEATURE_IPV4/TESTS/mbedmicro-net/udp_echo_client/main.cpp
This PR is derived from #2318. This attempts to fix an issue that occurs in earlier version of Python when generating XML test reports.
The TCP and UDP echo test cases generate random ASCII sequences to be echoed back by the host PC. In the case where a test report needs to be generated, this causes the following error:
```
(UnicodeDecodeError) exporter_testcase_junit:'unicodeescape' codec can't decode bytes in position 5349-5350: truncated \uXXXX escape
```
This PR avoids this issue by limiting the range of random ASCII characters to just '0' - '9'. This should be sufficiently random but use safer characters that shouldn't cause issues when saving to XML files.
FYI @sg-
> Patch of #2318

- features/net/FEATURE_IPV4/TESTS/mbedmicro-net/.mbedignore
- features/net/FEATURE_IPV4/TESTS/mbedmicro-net/host_tests/tcp_echo_client.py
- features/net/FEATURE_IPV4/TESTS/mbedmicro-net/host_tests/udp_echo_client.py
- features/net/FEATURE_IPV4/TESTS/mbedmicro-net/nist_internet_time_service/main.cpp
- features/net/FEATURE_IPV4/TESTS/mbedmicro-net/tcp_client_echo/main.cpp
- features/net/FEATURE_IPV4/TESTS/mbedmicro-net/tcp_client_hello_world/main.cpp
- features/net/FEATURE_IPV4/TESTS/mbedmicro-net/udp_echo_client/main.cpp
> adding tests for net/IPV4

- tools/build_api.py
At some point, the actual code that did the "clean" for build_library was
removed. This also affected building and cleaning tests. This adds this
capability back to the build API.
Please review @screamerbg
> Adding clean support back to build_library

- features/frameworks/utest/README.md
This README was pulled from the project's repo here: https://github.com/ARMmbed/utest.
I made minor modifications to the README to reflect the changes to the default scheduler (using a Timeout object instead of MINAR).
FYI @adbridge
> Adding README for utest

- hal/targets/cmsis/TARGET_NORDIC/TARGET_NRF5/TARGET_MCU_NRF51822_UNIFIED/TOOLCHAIN_IAR/TARGET_MCU_NORDIC_16K/nRF51822_QFAA.icf
- hal/targets/cmsis/TARGET_NORDIC/TARGET_NRF5/TARGET_MCU_NRF51822_UNIFIED/TOOLCHAIN_IAR/TARGET_MCU_NORDIC_32K/nRF51822_QFAA.icf
While I was doing: https://github.com/ARMmbed/mbed-os/pull/2337 . 
I've discovered that the cstack definitions for IAR were not correct. 
This patch set the size of the cstack on NRF51 to 2048 bytes.
> Fix nrf51 stack on IAR.

- tools/targets.py
- tools/toolchains/__init__.py
* Allow targets to be reloaded using set_targets_json_location(), e.g. make the targets.json param optional
* Empty the job queue before terminating it. This prevents buggy Python multiprocessing library from killing the wrong process (in Celery environment for example)
> [Tools] Build system improvements

- hal/targets/cmsis/TARGET_STM/TARGET_STM32F2/TARGET_NUCLEO_F207ZG/TOOLCHAIN_IAR/stm32f207xx.icf
The icf file was not align with other targets and they were no reserved space for NVIC vectors.
```
+---------+---------------------+-----------+-------------+---------------------------------------+--------------------+---------------+-------+
| Result  | Target              | Toolchain | Test ID     | Test Description                      | Elapsed Time (sec) | Timeout (sec) | Loops |
+---------+---------------------+-----------+-------------+---------------------------------------+--------------------+---------------+-------+
| OK      | NUCLEO_F207ZG[F079] | IAR       | DTCT_1      | Simple detect test                    |        0.52        |       10      |  1/1  |
| OK      | NUCLEO_F207ZG[F079] | IAR       | EXAMPLE_1   | /dev/null                             |        3.45 …
```
> [STM32F207ZG] Fix IAR memory init

- hal/targets/cmsis/TARGET_STM/TARGET_STM32F3/TARGET_NUCLEO_F303RE/TOOLCHAIN_ARM_MICRO/startup_stm32f303xe.S
- hal/targets/cmsis/TARGET_STM/TARGET_STM32F3/TARGET_NUCLEO_F303RE/TOOLCHAIN_ARM_STD/startup_stm32f303xe.S
Fix issue #2327.
The RAM is correctly sized. Only the initial stack pointer was wrong. In IAR and GCC, it is handle automatically. The `INITIAL_SP` of the RTOS is correctly defined to `0x2001 0000`.
> [STM32F303RE] Fix initial SP on ARM and uARM

- hal/targets/hal/TARGET_Freescale/TARGET_KSDK2_MCUS/TARGET_K64F/TARGET_HEXIWEAR/fsl_clock_config.c
Result: 26 OK
Completed in 427.14 sec
Build successes:
* HEXIWEAR::IAR::DTCT_1
* HEXIWEAR::IAR::EXAMPLE_1
* HEXIWEAR::IAR::MBED
* HEXIWEAR::IAR::MBED_10
* HEXIWEAR::IAR::MBED_11
* HEXIWEAR::IAR::MBED_12
* HEXIWEAR::IAR::MBED_16
* HEXIWEAR::IAR::MBED_2
* HEXIWEAR::IAR::MBED_23
* HEXIWEAR::IAR::MBED_24
* HEXIWEAR::IAR::MBED_25
* HEXIWEAR::IAR::MBED_26
* HEXIWEAR::IAR::MBED_34
* HEXIWEAR::IAR::MBED_37
* HEXIWEAR::IAR::MBED_38
* HEXIWEAR::IAR::MBED_A1
* HEXIWEAR::IAR::MBED_A21
* HEXIWEAR::IAR::MBED_A9
* HEXIWEAR::IAR::MBED_BUSOUT
* HEXIWEAR::IAR::RTOS
* HEXIWEAR::IAR::RTOS_1
* HEXIWEAR::IAR::RTOS_2
* HEXIWEAR::IAR::RTOS_3
* HEXIWEAR::IAR::RTOS_4
* HEXIWEAR::IAR::RTOS_5
* HEXIWEAR::IAR::RTOS_6
* HEXIWEAR::IAR::RTOS_7
* HEXIWEAR::IAR::RTOS_8
* HEXIWEAR::IAR::RTX
> Fix the clock setup for the K64 HEXIWEAR board

- docs/testing_mbed_OS_5.md
This adds documentation describing how tests are built and ran within mbed OS 5.
This doesn't cover the mbed CLI commands, but rather the underlying build and test runner process that's occurring when making the calls to mbed CLI and the underlying scripts.
It also describes how to debug tests with IDEs in conjunction with the test tools.
Please review @iriark01 
FYI @mazimkhan @adbridge
> Adding docs for the testing process for mbed OS 5

- hal/targets/cmsis/TARGET_Freescale/TARGET_KLXX/TARGET_KL46Z/TOOLCHAIN_IAR/MKL46Z4.icf
The KL46Z passes all tests on all toolchains except the following when built with IAR: `tests-mbedmicro-rtos-mbed-threads`.
This is because the heap is becomes fully allocated. This commit increases the heap from 8K to 16K.
Please review @c1728p9 
FYI @sg-
> Increasing the heap for KL46Z for IAR.

- hal/targets.json
- hal/targets/cmsis/TARGET_RENESAS/TARGET_VK_RZ_A1H/TOOLCHAIN_IAR/startup_VKRZA1H.s
VK_RZ_A1H already has lwip support and restricting FEATURE_IPV4 is unnecessary.
should fix https://github.com/ARMmbed/mbed-os-example-client/issues/67
tested locally with [mbed-os-example-client](https://github.com/ARMmbed/mbed-os-example-client) and the [nsapi tests](https://developer.mbed.org/teams/NetworkSocketAPI/code/NSAPITests/#0d938ec9100c)
cc @sg-, @bulislaw
> Enable FEATURE_IPV4 for the VK_RZ_A1H

- features/FEATURE_CLIENT/mbed-client-classic/source/m2mconnectionhandlerpimpl.cpp
- features/net/network-socket/Socket.cpp
- features/net/network-socket/Socket.h
- features/net/network-socket/TCPServer.cpp
- features/net/network-socket/mbed_lib.json
- features/net/network-socket/nsapi.h
- hal/api/mbed.h
Currently this uses the same mechanism used by the rtos to conditionally include the network-socket API. Perhaps this should be builtin to the config system?
Note: this does require that the bug-compatible inclusion of mbed.h be removed to avoid include-order issues, this may cause issues with existing examples. I will look into how this impacts mbed-os-example-client.
cc @sg-
> Expose the network-socket API through mbed.h

- .gitignore
- README.md
Readme reflects next release. .mbed files are unique to the machine and boards being developed. Do not track in the history.
> Update readme and ignore .mbed files

- hal/common/mbed_wait_api_no_rtos.c
- hal/common/mbed_wait_api_rtos.cpp
This commit adds two implementations for the mbed wait functions (wait,
wait_ms, wait_us):
- with the RTOS present, the wait functions will use `Thread::wait` for
millisecond delays and a busy wait loop for sub-millisecond delays.
- with the RTOS not present, the wait functions will always use a busy
wait loop.
> Unification of wait functions

- rtos/rtos/Thread.cpp
When a thread is terminated signal the join semaphore so any threads
joining the terminated thread wake up as expected.
> Fix joining a terminated thread

- docs/BUILDING.md
The description used in BUILDING.md does not work. It works with -L parameter
> Fix docs/BUILDING.md error

- hal/targets.json
Add support for the arduino form factor in targets.json for the
NUCLEO_F429ZI.
> Add ARDUINO to supported form factors of F429ZI

- hal/common/retarget.cpp
- hal/targets/cmsis/TARGET_NORDIC/TARGET_NRF5/TARGET_MCU_NRF52832/TOOLCHAIN_ARM_STD/startup_nrf52832.s
- hal/targets/cmsis/TARGET_NUVOTON/TARGET_NUC472/TARGET_NUMAKER_PFM_NUC472/TOOLCHAIN_IAR/NUC472_442.icf
- rtos/rtx/TARGET_CORTEX_M/HAL_CM.c
- rtos/rtx/TARGET_CORTEX_M/RTX_CM_lib.h
- rtos/rtx/TARGET_CORTEX_M/TESTS/memory/heap_and_stack/main.cpp
- rtos/rtx/TARGET_CORTEX_M/cmsis_os.h
- rtos/rtx/TARGET_CORTEX_M/rt_System.c
This is an alternative implementation of #2367 which statically defines the main thread stack rather than placing it at runtime in the heap region. This makes the memory layout simpler since the main thread is treated the same for GCC ARMCC and IAR. The downside to this is that due to the K22F's two region memory, it can no longer fit nanostack for GCC_ARM. If RAM0 and RAM1 could be combined into a single region this would not be a problem.
> Main thread stack checking alt impl

- hal/targets/hal/TARGET_NORDIC/TARGET_NRF5/us_ticker.c
The RTC1 counter can increase while the new value for the CC register
used by the os tick is computed. As a result, when interrupts are enabled
again RTC1 counter and CC register value are equal. If these two values are
equal then the interrupt for the CC channel used by the OS tick will be
generated the next time the RTC counter reach that value.
In other words, the next OS tick will occur 131 seconds latter.
This issue possibly concern all NRF51 targets with 32K of RAM but is
only visible on NRF51_DK target when their is heavy BLE load.
> Fix possible overflow of NRF51 os tick.

- docs/BUILDING.md
- features/FEATURE_UVISOR/README.md
- features/FEATURE_UVISOR/includes/uvisor/api/inc/rpc.h
- hal/targets.json
- hal/targets/hal/TARGET_STM/TARGET_STM32F1/serial_api.c
- rtos/rtos/Thread.cpp
I compared master to 5.1 branch, created a patch with all commits that are bugfixes (unified wait is not here).
cc @sg- @c1728p9 @bogdanm
> Fixes from master

- tools/build_api.py
- tools/paths.py
Previously, build_mbed_libs didn't take into account the configuration.
This is a problem when doing a binary release, since mbed_lib.json
contains configuration data relevant to the binary release.
> build_mbed_libs is now aware of the configuration

- tools/build_api.py
`build_lib` wasn't aware of configuration data, so some of the source
files that depends on configuration data fail to compile. This commit
fixes that by making `build_lib` aware of configuration data.
> Add config data to build_lib in build_api.py

- TESTS/mbedmicro-rtos-mbed/malloc/main.cpp
Add a test to repeatedly malloc and free from different threads to
test if these functions are thread safe.
> Add a test for thread-safe malloc

- libraries/tests/mbed/can_loopback/main.cpp
- tools/tests.py
MBED_A27 test doesn't need any peripheral
it can then be added in the common list
> Add MBED_A27 test in the common list

- tools/config.py
resolves #2083
It now tells you something like
```
[ERROR] Library configured at /home/----/src/mbedmicro/Nucleo_blink_led/mbed-os/features/net/network-socket/mbed_lib.json has no name field
```
> [tools!] Improve error for missing name from mbed_lib.json

- hal/targets.json
- hal/targets/cmsis/TARGET_NORDIC/TARGET_NRF5/TARGET_MCU_NRF51822_UNIFIED/system_nrf51.c
- hal/targets/hal/TARGET_NORDIC/TARGET_NRF5/TARGET_MCU_NRF51822_UNIFIED/TARGET_TY51822R3/PinNames.h
- hal/targets/hal/TARGET_NORDIC/TARGET_NRF5/TARGET_MCU_NRF51822_UNIFIED/TARGET_TY51822R3/device.h
- Changed inherit to "MCU_NRF51_32K_UNIFIED".
- Added 32MHz XTAL support to "system_nrf.c".
- Added TY51822r3 support to "MCU_NRF51_32K_UNIFIED".
> [TY51822r3] Add support for mbed OS 5

- hal/targets.json
- hal/targets/hal/TARGET_STM/TARGET_STM32F4/TARGET_ARCH_MAX/objects.h
- hal/targets/hal/TARGET_STM/TARGET_STM32F4/TARGET_B96B_F446VE/objects.h
- hal/targets/hal/TARGET_STM/TARGET_STM32F4/TARGET_DISCO_F401VC/objects.h
- hal/targets/hal/TARGET_STM/TARGET_STM32F4/TARGET_DISCO_F407VG/objects.h
- hal/targets/hal/TARGET_STM/TARGET_STM32F4/TARGET_DISCO_F429ZI/objects.h
- hal/targets/hal/TARGET_STM/TARGET_STM32F4/TARGET_DISCO_F469NI/objects.h
- hal/targets/hal/TARGET_STM/TARGET_STM32F4/TARGET_ELMO_F411RE/objects.h
- hal/targets/hal/TARGET_STM/TARGET_STM32F4/TARGET_MTS_DRAGONFLY_F411RE/objects.h
- hal/targets/hal/TARGET_STM/TARGET_STM32F4/TARGET_MTS_MDOT_F405RG/objects.h
- hal/targets/hal/TARGET_STM/TARGET_STM32F4/TARGET_MTS_MDOT_F411RE/objects.h
- hal/targets/hal/TARGET_STM/TARGET_STM32F4/TARGET_NUCLEO_F401RE/objects.h
- hal/targets/hal/TARGET_STM/TARGET_STM32F4/TARGET_NUCLEO_F410RB/objects.h
- hal/targets/hal/TARGET_STM/TARGET_STM32F4/TARGET_NUCLEO_F411RE/objects.h
- hal/targets/hal/TARGET_STM/TARGET_STM32F4/TARGET_NUCLEO_F429ZI/objects.h
- hal/targets/hal/TARGET_STM/TARGET_STM32F4/TARGET_NUCLEO_F446RE/objects.h
- hal/targets/hal/TARGET_STM/TARGET_STM32F4/TARGET_NUCLEO_F446ZE/objects.h
- hal/targets/hal/TARGET_STM/TARGET_STM32F4/TARGET_UBLOX_C029/objects.h
- hal/targets/hal/TARGET_STM/TARGET_STM32F4/common_objects.h
- hal/targets/hal/TARGET_STM/TARGET_STM32F4/serial_api.c
- libraries/tests/utest/serial_asynch/serial_asynch.cpp
This PR clean the serial_api.c and enable the asynchronous serial on the following targets:
- DISCO_F429ZI
- NUCLEO_F429ZI
- NUCLEO_F411RE
- NUCLEO_F401RE
- NUCLEO_F410RB
- NUCLEO_F446ZE
- NUCLEO_F446RE
The DMA and the yotta defines have been removed. The `struct serial_s` has been moved to `common_objects.h`.
[test report](https://svastm.github.io/report__2016-08-09_16.04.13.89__ALL__debug__ALL.html)
> [STM32F4] Add asynchronous serial

- TESTS/mbedmicro-mbed/attributes/attributes.c
- hal/api/FunctionPointer.h
- hal/api/toolchain.h
- rtos/rtos/RtosTimer.h
- rtos/rtos/Thread.h
From the discussion on issue #2068:
Functions marked deprecated in the mbed library should have a stated lifetime. This lifetime should be no less than 2 quarters (6 months).
Added the following macro:
> ``` cpp
> MBED_DEPRECATED_SINCE("version", "message string")
> ```
> Mark a function declaration as deprecated, noting that the declaration was deprecated on the specified version. If the function is used then a warning will be issued by the compiler possibly including the provided message. Note that not all compilers are able to display this message.
>
> ``` cpp
> #include "toolchain.h"
>
> MBED_DEPRECATED_UNTIL("2006-08-14", "don't foo any more, bar instead")
> void foo(int arg);
> ```
Adopted in existing deprecations:
- FunctionPointer
- RtosTimer
- Thread
cc @0xc0170, @sg-, @pan-, …
> Add more well-defined garuntees on deprecation notices in mbed

- TESTS/mbedmicro-mbed/attributes/attributes.c
- hal/api/FunctionPointer.h
- hal/api/toolchain.h
- rtos/rtos/RtosTimer.h
- rtos/rtos/Thread.h
From an offline discussion, the `v5.1` notation is not used elsewhere in the code base. The branch name provides a reasonable precedence.
Example:
``` cpp
MBED_DEPRECATED_SINCE("mbed-os-5.1", "don't foo any more, bar instead")
void foo(int arg);
```
cc @sg-, @0xc0170
> Updated deprecation notices to match branch names

- hal/targets/cmsis/TARGET_Maxim/TARGET_MAX32600/dac_regs.h
- hal/targets/cmsis/TARGET_Maxim/TARGET_MAX32600/gpio_regs.h
- hal/targets/cmsis/TARGET_Maxim/TARGET_MAX32600/max32600.h
- hal/targets/cmsis/TARGET_Maxim/TARGET_MAX32600/spi_regs.h
- hal/targets/cmsis/TARGET_Maxim/TARGET_MAX32600/system_max32600.c
- hal/targets/cmsis/TARGET_Maxim/TARGET_MAX32610/dac_regs.h
- hal/targets/cmsis/TARGET_Maxim/TARGET_MAX32610/gpio_regs.h
- hal/targets/cmsis/TARGET_Maxim/TARGET_MAX32610/max32610.h
- hal/targets/cmsis/TARGET_Maxim/TARGET_MAX32610/system_max32610.c
- hal/targets/cmsis/TARGET_Maxim/TARGET_MAX32610/usb_regs.h
- hal/targets/hal/TARGET_Maxim/TARGET_MAX32600/analogout_api.c
- hal/targets/hal/TARGET_Maxim/TARGET_MAX32600/i2c_api.c
- hal/targets/hal/TARGET_Maxim/TARGET_MAX32600/objects.h
- hal/targets/hal/TARGET_Maxim/TARGET_MAX32600/spi_api.c
- hal/targets/hal/TARGET_Maxim/TARGET_MAX32610/analogout_api.c
- hal/targets/hal/TARGET_Maxim/TARGET_MAX32610/i2c_api.c
- hal/targets/hal/TARGET_Maxim/TARGET_MAX32610/objects.h
- hal/targets/hal/TARGET_Maxim/TARGET_MAX32610/spi_api.c
Fixed I2C and DAC driver bugs and cleaned up register definitions.
> [MAX326xx] Bug fixes and clean up.

- features/net/FEATURE_IPV4/lwip-interface/lwip_stack.c
- features/net/FEATURE_IPV4/lwip-interface/lwipopts.h
From the [posix documentation](http://pubs.opengroup.org/onlinepubs/009695399/functions/setsockopt.html):
> SO_REUSEADDR - Specifies that the rules used in validating addresses supplied to bind() should allow reuse of local addresses, if this is supported by the protocol. This option takes an int value. This is a Boolean option.
This patch adds this behaviour for the non-conflicting NSAPI_REUSEADDR socket option.
Provides the standard solution for https://github.com/ARMmbed/mbed-os/issues/2438 and https://github.com/ARMmbed/mbed-os/issues/2408.
> [nsapi] Add support for NSAPI_REUSEADDR to the lwip interface

- features/net/FEATURE_IPV4/lwip-interface/lwip-eth/arch/TARGET_STM/TARGET_STM32F2/TARGET_NUCLEO_F207ZG/stm32f2_eth_init.c
- features/net/FEATURE_IPV4/lwip-interface/lwip-eth/arch/TARGET_STM/TARGET_STM32F2/stm32f2_emac.c
- features/net/FEATURE_IPV4/lwip-interface/lwip-eth/arch/TARGET_STM/TARGET_STM32F4/TARGET_ARCH_MAX/stm32f4_eth_init.c
- features/net/FEATURE_IPV4/lwip-interface/lwip-eth/arch/TARGET_STM/TARGET_STM32F4/TARGET_NUCLEO_F429ZI/stm32f4_eth_init.c
- features/net/FEATURE_IPV4/lwip-interface/lwip-eth/arch/TARGET_STM/TARGET_STM32F4/stm32f4_emac.c
- features/net/FEATURE_IPV4/lwip-interface/lwip-eth/arch/TARGET_STM/TARGET_STM32F7/TARGET_DISCO_F746NG/stm32f7_eth_init.c
- features/net/FEATURE_IPV4/lwip-interface/lwip-eth/arch/TARGET_STM/TARGET_STM32F7/TARGET_NUCLEO_F746ZG/stm32f7_eth_init.c
- features/net/FEATURE_IPV4/lwip-interface/lwip-eth/arch/TARGET_STM/TARGET_STM32F7/TARGET_NUCLEO_F767ZI/stm32f7_eth_init.c
- features/net/FEATURE_IPV4/lwip-interface/lwip-eth/arch/TARGET_STM/TARGET_STM32F7/stm32f7_emac.c
- hal/targets.json
This commit refactor the `lwip-eth/arch/TARGET_STM` folder and add the IPV4 feature for the
following targets:
- NUCLEO_F207ZG
- NUCLEO_F429ZI
- NUCLEO_F767ZI
- DISCO_F746NG
```
+-------------------+---------------+--------------------------------------------------------------------------+--------+--------------------+-------------+
| target            | platform_name | test suite                                                               | result | elapsed_time (sec) | copy_method |
+-------------------+---------------+--------------------------------------------------------------------------+--------+--------------------+-------------+
| NUCLEO_F207ZG-ARM | NUCLEO_F207ZG | features-net-feature_ipv4-tests-mbedmicro-net-nist_internet_time_service | OK     | 14.79              | shell …
```
> [STM32] Add ethernet and feature IPV4

- tools/memap.py
It was simply in the wrong spot
before:
```
+-----------+--------+-------+-------+
| Module    |  .text | .data |  .bss |
+-----------+--------+-------+-------+
| Subtotals | 381094 |  2704 | 84676 |
+-----------+--------+-------+-------+
Allocated Heap: 65540 bytes
Allocated Stack: 32768 bytes
Total Static RAM memory (data + bss): 87380 bytes
Total RAM memory (data + bss + heap + stack): 185688 bytes
Total Flash memory (text + data + misc): 384838 bytes
```
after
```
+-----------------------------+--------+-------+-------+
| Module                      |  .text | .data |  .bss |
+-----------------------------+--------+-------+-------+
| Fill                        |    484 |    18 |  2161 |
| Misc                        | 110012 |  2341 |  5852 |
| features/FEATURE_CLIENT     |  66624 | …
```
> Print module information in 'table' output format

- tools/toolchains/gcc.py
The output of the GCC compiler is such that the toolchain regex sometimes
got hung up on the `:` charcter being printed in front of the drive letter when
running on Windows. This PR changes the matching logic to be more flexible
by using `search` to check the entire string for a match, not just the
beginning of the string.
An example of where the current implementation fails is on this PR: https://github.com/ARMmbed/mbed-os/pull/2422
The CI failure is visible here (scroll to the bottom): http://10.118.12.43:8081/job/build_matrix/270/target=KL25Z,toolchain=GCC_ARM/console
You can see the tools didn't print the error here. This PR should fix this issue.
> Fixing issue where GCC fails to report compile errors when non-verbose

- README.md
It looks like https://docs.mbed.com/docs/mbed-os-release-notes/en/latest/5_1/release results in a 404 page, but https://docs.mbed.com/docs/mbed-os-release-notes/en/latest/5_1/release/ works.
> Fixed link to release page

- TESTS/mbed_drivers/stats/main.cpp
- features/frameworks/utest/source/utest_greentea_handlers.cpp
- features/frameworks/utest/source/utest_harness.cpp
- features/storage/FEATURE_STORAGE/cfstore/source/cfstore_test.c
- hal/api/mbed_stats.h
- hal/common/retarget.cpp
- tools/toolchains/gcc.py
Keep track of the current and maximum space used by malloc and report
it at the end of a test.
> Malloc heap info

- features/net/FEATURE_IPV4/TESTS/mbedmicro-net/nist_internet_time_service/main.cpp
A UDP request to the NIST servers can fail to return data due to UDP
packet loss. Since packets are not guaranteed with UDP, this is a valid
failure and should not be treated as a test failure. The test should retry
the request in this case. This commit adds those retries.
This test sometimes fails in CI even when the actual PR can't cause the test to fail (#2393 is an example of this). This should help cut down on false failures.
> Adding retries to the NIST test.

- hal/targets/hal/TARGET_RENESAS/TARGET_RZ_A1H/spi_api.c
This enables SPI1 on P6_4 ~ P6_7
> [Renesas RZ/A1H] Enable SPI1 on P6_4 ~ P6_7

- hal/api/SingletonPtr.h
Check to see if ptr is NULL after acquiring the singleton lock to
prevent initialization race conditions. Also explicitly call the
constructor for type T.
> Fix SingletonPtr problems

- hal/common/retarget.cpp
uVisor only wraps malloc_r, realloc_r and free_r, not calloc_r!
Fixes what was added in https://github.com/ARMmbed/mbed-os/commit/6a31ffbf3e7e8411e3bfbb81961a792a040fcb28.
cc @c1728p9 @bogdanm @0xc0170 @AlessandroA @meriac @Patater
> Fix missing wrapping of calloc_r with uVisor enabled.

- features/net/FEATURE_IPV4/TESTS/mbedmicro-net/nist_internet_time_service/main.cpp
Previous behaviours overwrote server address on failures, causing spurious failures during CI.
continuation of https://github.com/ARMmbed/mbed-os/pull/2404
cc @bridadan
> Fixed recvfrom address in ipv4 nist tests

- TESTS/mbed_drivers/lp_timeout/main.cpp
- TESTS/mbed_hal/lp_ticker/main.cpp
- hal/api/Ticker.h
- hal/targets.json
- hal/targets/hal/TARGET_ARM_SSG/TARGET_BEETLE/sleep.c
- hal/targets/hal/TARGET_Freescale/TARGET_KSDK2_MCUS/api/lp_ticker.c
@0xc0170 Could you have a look please.
> K22F/K64F: Add lp_ticker implementation and HAL lp_ticker tests

- features/net/FEATURE_IPV4/lwip-interface/lwip_stack.c
When a socket is created via accept set the mode to nonblocking -
a timeout of 1ms. This allows send and recv to occur at the same time.
> LWIP - fix recv blocking send on accepted sockets

- hal/targets.json
- tools/tests.py
Target FLASH is quiet small (16KB),
so only uARM and very small applications are supported 
Some common test cases are then not supported:
Result	              Target	                 Toolchain	    Test ID	     Total Flash memory	OK in 16KB?
BUILD_FAILED 	 NUCLEO_L011K4       	 uARM      	 EXAMPLE_1   	16907	NO
BUILD_FAILED 	 NUCLEO_L011K4       	 uARM      	 MBED_16     	17961	NO
BUILD_FAILED 	 NUCLEO_L011K4       	 uARM      	 MBED_37     	16543	NO
BUILD_FAILED 	 NUCLEO_L011K4       	 uARM      	 MBED_38     	16467	NO
BUILD_FAILED 	 NUCLEO_L011K4       	 uARM      	 MBED_BUSOUT 	16543	NO
> [NUCLEO_L011K4] build issues

- hal/targets.json
- hal/targets/hal/TARGET_NORDIC/TARGET_NRF5/serial_api.c
Introduce uart hardware flow control configuration using mbed configuration system for MCU_NRF51_UNIFIED and MCU_NRF52 targets.
The target.uart_hwfc key is used to configure flow control for nRF5x SoC.
Related to issues:
https://github.com/ARMmbed/mbed-os/issues/2474
https://github.com/ARMmbed/mbed-os/issues/2489
https://github.com/ARMmbed/mbed-os-example-ble/issues/25
> nRF5x uart hardware flow control configuration using mbed configuration systsem

- hal/targets.json
- rtos/rtx/TARGET_CORTEX_M/RTX_CM_lib.h
Fix STM32F3 RTOS test regression for IAR and GCC_ARM
> STM32F3 :  test fix

- hal/targets/hal/TARGET_STM/TARGET_STM32F4/pwmout_api.c
This remains from a debug session but is not needed and creates a warning,
so better remove it.
> [STM32F4] pwmout: remove printf

- features/FEATURE_CLIENT/mbed-client-classic/source/m2mconnectionhandlerpimpl.cpp
Fix is done for https://github.com/ARMmbed/mbed-os-example-client/issues/75
This PR is to merge the fix into mbed-os release candidate.
> Fix for https://github.com/ARMmbed/mbed-os-example-client/issues/75

- features/frameworks/utest/utest/utest_types.h
Description
Fixes issue #2508.
The default compiler(ARMCC) copy constructor for failure_t doesn't behave as
expected and has unexpected side effects. This fix adds a custom copy constructor
to fix this.
> Utest: default copy constructor for failure_t doesn't behave as expected

- features/FEATURE_CLIENT/mbed-client-classic/source/m2mconnectionhandlerpimpl.cpp
- features/FEATURE_CLIENT/mbed-client/docs/Introduction.md
- features/FEATURE_CLIENT/mbed-client/docs/dev_man_serv_enable.md
- features/FEATURE_CLIENT/mbed-client/module.json
- features/FEATURE_CLIENT/mbed-client/source/m2minterfaceimpl.cpp
This PR is for fixing error found in integration testing for Bootstrap and Connector functionality.
The corresponding fixes done here
https://github.com/ARMmbed/mbed-client/commit/6925e894871fa0505c8114eae2cb00d0cbf211ae
https://github.com/ARMmbed/mbed-client-classic/commit/fbfb300d622aaa8ccd0fc5a158f4d327ecf78416
> Fix for IOTCLT-961 for next mbed-os release candidate

- features/net/FEATURE_IPV4/lwip-interface/lwip-eth/arch/TARGET_NUVOTON/TARGET_NUC472/nuc472_eth.c
In NUC472 ethernet driver, it doesn't fetch right RX interrupt status  in RX-Action. This update could fix it.
> Fix NUC472 Ethernet wrong INT status in RX_Action

- hal/targets.json
All NUCLEO/DISCO_xxx8 targets have 64K Flash,
which is not enough for GCC standard
Non regression tests have been performed well.
Thx
> Use GCC small build for 64K flash STM32

- rtos/rtx/TARGET_ARM7/RTX_CM_lib.h
- rtos/rtx/TARGET_CORTEX_A/RTX_CM_lib.h
- rtos/rtx/TARGET_CORTEX_M/RTX_CM_lib.h
Silence the following compiler warning: 
[Warning] RTX_CM_lib.h@807,5: implicit declaration of function 'atexit' [-Wimplicit-function-declaration]
> Fix implicit declaration of function 'atexit'

- tools/build_api.py
- tools/test.py
This came up when building tests, but affects any library using config that's first built, then included as "source" with the mbed tools. JSON files are not copied by default when building a library, so when this is built it loses the config data associated with the library. This commit copies all JSON files into the build directory when building libraries.
There is a strange side effect now which is there are now multiple `mbed_config.h` files created during the build process: one when building the library and one when building the actual application. This isn't currently a problem since none of our code explicitly includes `mbed_config`, but it does look strange. Is anyone aware of potential issues with this? If so, having the ability to prevent an `mbed_config.h` from being created in …
> Copying JSON files to pick up config for built libraries

- tools/toolchains/__init__.py
- tools/toolchains/arm.py
- tools/toolchains/gcc.py
- tools/toolchains/iar.py
Fixes #2360.
New error:
[ERROR] Could not find executable for IAR.
Currently set search path: /default/path/that/doesnt/exist
(System exit before any build system calls)
@theotherjimmy  @0xc0170 @bridadan
> Readable error when toolchain paths not set. Allow IAR and ARM toolchains to be set in user's PATH.

- tools/toolchains/__init__.py
GCC toolchain path does not require .exe extension for execution on the command line, but the extension is required to check existence in Windows.
> Check if executble exists 

- rtos/rtos/rtos_idle.c
It's enabled by default for all platforms defining DEVICE_SLEEP and
DEVICE_LOWPOWERTIMER.
@sg- I don't have rights to push it directly to the branch, could you merge this PR please.
> RTOS: Add tickles sleep implementation

- hal/common/mbed_alloc_wrappers.cpp
- hal/common/retarget.cpp
Tested with uvisor example:
```
+-------------------------+-------+-------+-------+
| Module                  | .text | .data |  .bss |
+-------------------------+-------+-------+-------+
| Fill                    |   141 |   512 |  2389 |
| Misc                    | 42795 |  1688 |  3838 |
| features/FEATURE_UVISOR |   650 |     0 |     1 |
| features/frameworks     |  4236 |    52 |   744 |
| hal/common              |  2619 |     0 |   325 |
| hal/targets             | 12851 |    12 |   200 |
| rtos/rtos               |   559 |     4 |     0 |
| rtos/rtx                |  6427 |    20 |  6787 |
| Subtotals               | 70278 |  2288 | 14284 |
+-------------------------+-------+-------+-------+
Allocated Heap: 65540 bytes
Allocated Stack: unknown
Total Static RAM memory (data + bss): …
```
> Fix uvisor memory tracing

- tools/build.py
- tools/get_config.py
- tools/make.py
- tools/project.py
- tools/test.py
- tools/utils.py
Also makes all argument errors (from our code and argpase) look the same
> [tools] Prevent trace-backs from incomplete args

- TESTS/mbed_drivers/callback/main.cpp
- TESTS/mbed_functional/callback/main.cpp
- TESTS/mbed_functional/callback_big/main.cpp
- TESTS/mbed_functional/callback_small/main.cpp
- TESTS/mbed_functional/functionpointer/main.cpp
- features/net/network-socket/Socket.h
- hal/api/CallChain.h
- hal/api/Callback.h
- hal/api/FunctionPointer.h
- hal/api/InterruptIn.h
- hal/api/SerialBase.h
- hal/api/Ticker.h
- hal/common/CAN.cpp
- hal/common/InterruptIn.cpp
- hal/common/SerialBase.cpp
- rtos/rtos/RtosTimer.h
- rtos/rtos/Thread.h
From this discussion https://github.com/ARMmbed/mbed-os/pull/2395 and the related issue https://github.com/ARMmbed/mbed-os/issues/2490
The combination of cv-qualifiers with callback overloads results in a large number of overloads to match all possible types that could be passed to the Callback class.
This isn't a big problem for `void (*)(cv T *)` function types, but for `void (T::*)() cv` types, the method in which cv-qualifiers are associated prevents encoding the cv-qualifiers in the `T` type, and requiring a large combination of overloads for all cv-qualifiers.
This pr involves several changes:
- Adds full support for cv-qualifiers in Callback constructor
- Provides convenience `mbed::callback` function to pass different arguments to Callback with infered type.
- Deprecates existing …
> Add cv-qualifiers to Callback and deprecate combinatorial explody functions

- tools/config.py
> tools-config! -  Allow an empty or mal-formed config to be passed to the config system

- TESTS/mbed_drivers/callback/main.cpp
- TESTS/mbed_functional/callback/main.cpp
- TESTS/mbed_functional/callback_big/main.cpp
- TESTS/mbed_functional/callback_small/main.cpp
- TESTS/mbed_functional/functionpointer/main.cpp
- features/net/network-socket/Socket.h
- hal/api/CallChain.h
- hal/api/Callback.h
- hal/api/FunctionPointer.h
- hal/api/InterruptIn.h
- hal/api/SerialBase.h
- hal/api/Ticker.h
- hal/common/CAN.cpp
- hal/common/InterruptIn.cpp
- hal/common/SerialBase.cpp
- rtos/rtos/RtosTimer.h
- rtos/rtos/Thread.h
**Note:** This is currently dependent on https://github.com/ARMmbed/mbed-os/pull/2496 and will be updated based on the discussion in that pr. Here are the new commits:
756a090 Added explicit void specialization in callbacks
022f821 Rewrote thread deprecation notices to help migration
User feedback indicated that the previous deprecation notices were confusing. Additionally, limitations on implicit casts for callback arguments tripped up attempts at migrating from the old style of thread spawning and led to a poor user experience.
In an effort to remedy this:
1. The callback class was updated to accept explicit void pointers, allowing implicit casts to void pointer, and avoids requiring users to change the argument types of their code.
2. The deprecation notices were updated to emphasize …
> Clean up confusion with deprecated constructors and callbacks in thread-spawning functions

- TESTS/mbed_drivers/race_test/main.cpp
- hal/common/retarget.cpp
Fix lazy initialization of objects in GCC along with adding a test for it.
> Fix GCC lazy init race condition and add test

- features/net/FEATURE_IPV6/nanostack-interface/NanostackInterface.cpp
When freeing all memory in the rx buffer chain set the head pointer to
NULL. This prevents the head rx buffer from getting freed twice.
> Fix double free in NanostackInterface

- .github/issue_template.md
- .github/pull_request_template.md
Bring github templates back.
@sg- @bogdanm please review this
> github issue and PR templates

- hal/targets/hal/TARGET_Freescale/TARGET_KSDK2_MCUS/TARGET_MCU_K64F/TARGET_HEXIWEAR/PeripheralPins.c
Although the signals connected to the SD Card on Hexiwear are marked as SDHC, the  [SDFileSystem](https://developer.mbed.org/teams/mbed/code/SDFileSystem/) library on mbed uses legacy SPI mode and thus the pins need to be able to be configured for SPI, which they can be with this patch.
> add PTEx pins as option for SPI on Hexiwear - for SD Card Interface

- tools/test_api.py
The shared `prepare_toolchain` and `scan_resources` functions in build_api
expect a list, not a string. This is different from the
toolchain.scan_resources function. Now the functions are being used
correctly within the `find_tests` function in test_api
Thanks @sarahmarshy for finding this!
> Correctly providing directories to build_apis

- TESTS/mbedmicro-rtos-mbed/threads/main.cpp
- rtos/rtos/Thread.cpp
Fix thread self termination and add a test to catch future regressions.
> Fix thread self termination

- TESTS/mbed_drivers/lp_timeout/main.cpp
- TESTS/mbed_hal/lp_ticker/main.cpp
Because microseconds timer can be disable during deepsleep.
> Use lp_timer to count time in the deepsleep tests

- hal/api/CAN.h
- hal/api/SerialBase.h
Rather than hard coding the size of the callback array for irqs,
instead set the size to IrqCnt which is defined by the irq enumeration.
> Set size of callback irq array to IrqCnt

- hal/targets/cmsis/TARGET_NXP/TARGET_LPC11U6X/TOOLCHAIN_GCC_CR/TARGET_LPC11U68/startup_LPC11U68.cpp
- hal/targets/cmsis/TARGET_NXP/TARGET_LPC11UXX/TOOLCHAIN_GCC_CR/startup_LPC11xx.cpp
- hal/targets/cmsis/TARGET_NXP/TARGET_LPC11XX_11CXX/TOOLCHAIN_GCC_CR/TARGET_LPC11XX/startup_LPC11xx.cpp
- hal/targets/cmsis/TARGET_NXP/TARGET_LPC15XX/TOOLCHAIN_GCC_CR/startup_LPC15xx.cpp
- hal/targets/cmsis/TARGET_NXP/TARGET_LPC176X/TOOLCHAIN_GCC_CR/startup_LPC17xx.cpp
- hal/targets/cmsis/TARGET_NXP/TARGET_LPC408X/TOOLCHAIN_GCC_CR/startup_lpc407x_8x.cpp
See detail here: https://github.com/ARMmbed/mbed-os/issues/2581
Automated test result is below:
```
Test summary:
+--------+---------+-----------+-------------+---------------------------------------+--------------------+---------------+-------+
| Result | Target  | Toolchain | Test ID     | Test Description                      | Elapsed Time (sec) | Timeout (sec) | Loops |
+--------+---------+-----------+-------------+---------------------------------------+--------------------+---------------+-------+
| OK     | LPC1768 | GCC_CR    | DTCT_1      | Simple detect test                    |        6.49        |       20      |  1/1  |
| OK     | LPC1768 | GCC_CR    | EXAMPLE_1   | /dev/null                             |        6.41        |       20      |  1/1  |
| OK     | LPC1768 | …
```
> [GCC_CR] fix runtime hang for baremetal build

- features/net/FEATURE_IPV4/lwip-interface/lwip_stack.c
- features/net/network-socket/TCPServer.cpp
This required two small modifications:
- Correct handling of max sockets in lwip socket_accept
- Correct handling of errors in TCPServer accept
Related issue https://github.com/ARMmbed/mbed-os/issues/2523
> lwip - Fix handling of max sockets in socket_accept

- hal/targets.json
Tests are OK
[nucleo-f446ze_mbed5_tests.zip](https://github.com/ARMmbed/mbed-os/files/461172/nucleo-f446ze_mbed5_tests.zip)
> NUCLEO_F446ZE - Enable mbed5 release version

- libraries/USBHost/USBHost/USBDeviceConnected.h
- libraries/USBHost/USBHost/USBEndpoint.h
- libraries/USBHost/USBHost/USBHost.cpp
- libraries/USBHost/USBHost/USBHost.h
- libraries/USBHost/USBHostMSD/USBHostMSD.cpp
- libraries/USBHost/USBHostSerial/USBHostSerial.h
Updated USBHost classes to use Callback<void()> and new Thread API to fix compiler warnings.
> Updated USBHost for library changes

- libraries/USBDevice/USBAudio/USBAudio.h
- libraries/USBDevice/USBSerial/USBSerial.h
Updated USBAudio and USBSerial to use Callback<void()> instead of FunctionPointer to fix compiler warnings.
> Updated USBDevice to use Callback

- tools/test_api.py
#2613 should be merged first. 
Using test_api, I found that the test names were dependent on where mbed-os (if that is the root) is stored on disk if you provide anything other than '.' as the root directory. 
This would change names like: 
```
repos-mbed-os-example-blinky-mbed-os-features-storage-feature_storage-tests-cfstore-example3
```
to
```
features-storage-feature_storage-tests-cfstore-example3
```
> Test names not dependent on disk location of root

- hal/targets.json
- hal/targets/hal/TARGET_NORDIC/TARGET_MCU_NRF51822/TARGET_MTM_MTCONNECT04S/PinNames.h
- hal/targets/hal/TARGET_NORDIC/TARGET_MCU_NRF51822/TARGET_MTM_MTCONNECT04S/device.h
- tools/export/gcc_arm_mtm_mtconnect04S.tmpl
- tools/export/gccarm.py
Added support for the target MTM_MTCONNECT04S.
Automated test report:
For further information, please refer to the following websites:
https://developer.mbed.org/teams/MtM/
http://www.nordicsemi.com/eng/News/News-releases/Product-Related-News/Nordic-powered-Bluetooth-low-energy-development-kit-offers-complete-turnkey-solution-for-rapid-Internet-of-Things-product-development
https://blog.mtmtech.com.tw/mtconnect04s/
> [MTM_MTCONNECT04S] Added support for MTM_MTCONNECT04S

- hal/common/mbed_critical.c
Suppressed "#3731-D: intrinsic is deprecated" compiler warnings in critical API.
> [HAL] Fixed "intrinsic is deprecated" warnings

- hal/common/mbed_alloc_wrappers.cpp
Fixed a bug and compiler warning in the memory tracer implementation.
> [HAL] Improve memory tracer

- features/net/network-socket/TCPServer.h
- Avoid a call to the protected method `get_stack()` which cause a build fail.
- Remove the constructor definition `TCPServer(NetworkStack *stack)`
because it has no implementation.
---
```
> mbed compile -m NUCLEO_F746ZG -t ARM
Building project mbed-os (NUCLEO_F746ZG, ARM)
Scan: .
Scan: FEATURE_CLIENT
Scan: FEATURE_IPV4
Scan: FEATURE_IPV6
Scan: mbed
Scan: env
Compile: main.cpp
[Warning] ip_addr.h@53,0:  #3135-D: attribute does not apply to any entity
[Warning] ip_addr.h@74,0:  #3135-D: attribute does not apply to any entity
[Error] TCPServer.h@50,0:  #265-D: function "EthernetInterface::get_stack" (declared at line 59 of "./mbed-os/features/net/FEATURE_IPV4/lwip-interface/EthernetInterface.h") is …
```
> Fix TCPServer constructor

- tools/build_api.py
- tools/config.py
- tools/make.py
- tools/options.py
- tools/test.py
- tools/test/build_api/build_api_test.py
- tools/test/config/config_test.py
- tools/test/test_api/test_api_test.py
- tools/test_api.py
* Add command line switch `--app-config` to specify the location of an app config file to use in `options.py`
* Add support for specifying app config in `mbed test` and `mbed make`
This is an example use of the switch, where `test.json` is in the format of a `mbed_app.json` file
```
$ python test.py --compile -m K64F -t GCC_ARM --app-config test.json
```
> Add app config command line switch for test and make

- tools/toolchains/__init__.py
The linking order of object files affects the actual code placement,
which in turn affects the size of fill section due to the number of
zeros required to maintain appropriate data/code alignment may change.
This is observed when building on Mac and Linux host.
example: mbed compile -m K64F -t GCC_ARM (build 1)
```
+---------------------+-------+-------+-------+
| Module              | .text | .data |  .bss |
+---------------------+-------+-------+-------+
| Fill                |   120 |     4 |  2381 |
| Misc                | 28755 |  2216 |    84 |
| features/frameworks |  4236 |    52 |   744 |
| hal/common          |  2745 |     4 |   325 |
| hal/targets         | 12116 |    12 |   200 |
| rtos/rtos           |   119 |     4 |     0 |
| rtos/rtx            |  5721 |    20 |  6786 |
| …
```
> Tools - Fix fill section size variation

- hal/api/CThunk.h
The asynchronous versions of the communication interfaces (serial, i2c and spi) need the CThunk class which is not yet implemented for cortex-M7.
My first idea was to use the same OP code than CM3 and CM4, `ldm.w pc,{r0,r1,r2,pc}`, because they use ARMv7-M and thumb2 like the CM7. But this OP code give me an hard fault and I don't understand why.
I poorly used the code from CM0, CM0+ which looks cleaner but a bit longer. Then I was able to run the following test code on ARM and IAR but it still fail on GCC. I tried with a NUCLEO_F746ZG and a DISCO_F746NG.
``` c++
#include "CThunk.h"
class DummyClass {
public: 
void method() {
printf("method called => attribute: %d\n", attribute);
}
public:
int attribute;
};
int main() {
printf("Begin\n");
DummyClass dm; …
```
> Add CThunk for CM7

- features/net/network-socket/NetworkInterface.h
- features/net/network-socket/WiFiInterface.h
- features/net/network-socket/nsapi_types.h
General refactoring of the API and two new methods added:
* get_rssi() - measures radio signal strenght
* get_state() - which returns current state (not connected,
connecting, connected, error)
@lauri-piikivi @sg- 
I changed how the get_rssi function works, comparing to what Lauri proposed. It's more in line in how other IOT SDKs work and also it's simpler. It only fetches current RSSI, if application wants to average it out over multiple measurements it can always wrap it in a loop, but I think it's probably good enough for most people.
> Extend and rework WiFi interface

- libraries/tests/mbed/can_loopback/main.cpp
bugfixing the can loop test which failed after PR #2504
**READY**
```
+--------+---------------------+-----------+----------+-------------------+--------------------+---------------+-------+
| Result | Target              | Toolchain | Test ID  | Test Description  | Elapsed Time (sec) | Timeout (sec) | Loops |
+--------+---------------------+-----------+----------+-------------------+--------------------+---------------+-------+
| OK     | NUCLEO_F746ZG[F920] | ARM       | MBED_A28 | CAN loopback test |       10.37        |       20      |  1/1  |
+--------+---------------------+-----------+----------+-------------------+--------------------+---------------+-------+
+--------+--------------------+-----------+----------+-------------------+--------------------+---------------+-------+
| …
```
> classic mbed: bugfix can loop test

- features/net/FEATURE_IPV4/lwip-interface/lwip-eth/arch/TARGET_STM/TARGET_STM32F4/stm32f4_emac.c
The current implementation of link state changes in stm32f4_emac.c seems to be vendor specific since it uses PHY registers above 16. To be more vendor independent we suggest to use the common registers to poll the link status. This is required to get ethernet on the C029 board to work.
What do you think?
@LMESTM
@bcostm
Needs review. This has been locally verified to work with the C029 board but not with any ST-boards.
> Replace vendor specific register usage in stm32f4_emac.c with basic register

- features/FEATURE_COMMON_PAL/nanostack-hal-mbed-cmsis-rtos/arm_hal_timer.cpp
Jenkins jobs are failing due build error: 
```
Compile: arm_hal_timer.cpp
[Error] arm_hal_timer.cpp@28,9: reference to 'callback' is ambiguous
[Error] arm_hal_timer.cpp@50,5: reference to 'callback' is ambiguous
[Warning] arm_hal_timer.cpp@19,15: 'callback' defined but not used [-Wunused-variable]
[ERROR] ./mbed-os/features/FEATURE_COMMON_PAL/nanostack-hal-mbed-cmsis-rtos/arm_hal_timer.cpp: In function 'void timer_thread(const void*)':
./mbed-os/features/FEATURE_COMMON_PAL/nanostack-hal-mbed-cmsis-rtos/arm_hal_timer.cpp:28:9: error: reference to 'callback' is ambiguous
callback();
^
./mbed-os/features/FEATURE_COMMON_PAL/nanostack-hal-mbed-cmsis-rtos/arm_hal_timer.cpp:19:15: note: candidates are: void (* callback)()
static void (*callback)(void);
^
In file included from …
```
> Avoid type collision by renaming callback variable

- features/FEATURE_COMMON_PAL/nanostack-hal-mbed-cmsis-rtos/arm_hal_random.c
- features/net/FEATURE_IPV6/nanostack-interface/NanostackInterface.cpp
- features/net/FEATURE_IPV6/nanostack-interface/NanostackInterface.h
- features/net/FEATURE_IPV6/nanostack-interface/NanostackRfPhy.h
Create a Nanostack rf phy class to wrap various rf physical interfaces.
Allow this phy to be set at runtime rather than compile time.
> Remove IPv6 link time dependency on an RF phy

- features/net/FEATURE_IPV4/lwip-interface/EthernetInterface.cpp
- features/net/FEATURE_IPV4/lwip-interface/lwip_stack.c
- features/net/FEATURE_IPV4/lwip-interface/lwip_stack.h
- Check if disconnected in socket open
- Check if connected in interface connect
- Check if disconnected in interface disconnect
Related issues https://github.com/ARMmbed/mbed-os/issues/2439, https://github.com/ARMmbed/mbed-os/issues/2421, https://github.com/ARMmbed/mbed-os/issues/2445
> lwip - Add checks for invalid state of network

- tools/memap.py
Removed code that checks if the path to the map file matches with the selected toolchain.
Fixes this: https://github.com/ARMmbed/mbed-os/issues/2608
Example:
```
C:\mbed\memap>mbed compile -t ARM -m K64F -c --build .build/XXX/
```
Output with patch:
```
+---------------------+-------+-------+-------+
| Module              | .text | .data |  .bss |
+---------------------+-------+-------+-------+
| Misc                | 13641 |    20 |  1372 |
| features/frameworks |  4315 |   572 |   296 |
| features/net        |    84 |     0 |    92 |
| hal/common          |  4790 |    28 |   168 |
| hal/targets         | 13904 |    76 |   136 |
| rtos/rtos           |   128 |     4 |     0 |
| rtos/rtx            |  6614 |    92 |  8316 |
| Subtotals           | 43476 |   792 | 10380 | …
```
> Fixed bug on memap (non-default output path)

- features/frameworks/greentea-client/greentea-client/greentea_metrics.h
- features/frameworks/greentea-client/source/greentea_metrics.cpp
- features/frameworks/greentea-client/source/test_env.cpp
- features/frameworks/utest/source/utest_greentea_handlers.cpp
- rtos/rtos/Thread.cpp
- rtos/rtos/Thread.h
- rtos/rtx/TARGET_CORTEX_A/RTX_Conf_CA.c
- rtos/rtx/TARGET_CORTEX_A/cmsis_os.h
- rtos/rtx/TARGET_CORTEX_A/rt_CMSIS.c
- rtos/rtx/TARGET_CORTEX_A/rt_TypeDef.h
- rtos/rtx/TARGET_CORTEX_M/RTX_Conf_CM.c
- rtos/rtx/TARGET_CORTEX_M/cmsis_os.h
- rtos/rtx/TARGET_CORTEX_M/rt_CMSIS.c
- rtos/rtx/TARGET_CORTEX_M/rt_Task.c
- rtos/rtx/TARGET_CORTEX_M/rt_TypeDef.h
Add CMSIS-OS API to get stack usage on all running Threads. Report this information at the end of testing.
> Stack stats

- tools/export/exporters.py
The previous way of finding group names found the encompassing directory of each file. If the project is exported from the online compiler, this resulted in temporary folder names like tmpyKKWv_ showing up as group names in offline IDEs.
I propose defaulting to the project name if the file is in the project root.
@theotherjimmy @screamerbg 
Thanks to @bridadan for finding and reporting this issue.
> Fix exported project file group naming

- features/net/network-socket/SocketAddress.cpp
- features/net/network-socket/SocketAddress.h
Add equality operators to the network-socket API Socket Address class:
``` cpp
bool operator==(const SocketAddress &a, const SocketAddress &b);
bool operator!=(const SocketAddress &a, const SocketAddress &b);
```
This is especially useful for checking udp packets to be from the correct sender:
``` cpp
UDPSocket server(&iface);
SocketAddress client_address;
int err = server->recvfrom(&client_address, packet, sizeof packet);
if (err || client_address !=expected_client_address) {
error("oh no!");
}
```
cc @c1728p9
> nsapi - Add equality operators to SocketAddress class

- hal/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/us_ticker.c
Cleaned up the EFM32 us_ticker implementation since it was taking way too long to execute, leading to very unpredictable results. About a 4x speedup by optimizing out a long division.
Relevant forum thread: [https://developer.mbed.org/forum/platform-66-EFM32-Zero-Gecko-community/topic/26198/]
> [EFM32] Microsecond ticker optimization

- tools/export/GettingStarted.html
- tools/export/exporters.py
This was auto-generated within the old exporters, and I think it would be useful to have in the new exporters. The link may contain extra steps that must be taken to have an export work for the end user.
> tools-exporters! - Globally add a gettingstarted.html

- tools/export/simplicityv3.py
- tools/export/simplicityv3_slsproj.tmpl
Simplicity Studio exporter doesnt really support header files in the root directory (looking at you, mbed_config.h), so this is a workaround for that issue.
Fix for #2655
> [EFM32] Fix exporter to pull root path

- tools/toolchains/__init__.py
The check was simply wrong, and .gitignore files were ignored
> tools - Correct adding repo_files

- tools/build.py
- tools/make.py
- tools/test.py
- tools/toolchains/__init__.py
- tools/toolchains/arm.py
- tools/toolchains/gcc.py
- tools/toolchains/iar.py
Mbed-cli is responsible for checking toolchain paths for executables that will be used for compilation. 
@screamerbg
> Revise checking toolchain path

- hal/targets/cmsis/TARGET_NORDIC/TARGET_NRF5/TARGET_MCU_NRF51822_UNIFIED/TOOLCHAIN_GCC_ARM/TARGET_MCU_NORDIC_32K/NRF51822.ld
- hal/targets/cmsis/TARGET_NORDIC/TARGET_NRF5/TARGET_MCU_NRF51822_UNIFIED/TOOLCHAIN_GCC_ARM/TARGET_MCU_NRF51_16K_S130/NRF51822.ld
- hal/targets/cmsis/TARGET_NORDIC/TARGET_NRF5/TARGET_MCU_NRF52832/TOOLCHAIN_GCC_ARM/NRF52832.ld
fs_data symbol is needed for flowing nRF5 SDk components:
fstorage, fds, Peer manager.
This part of RAM must be initialized at the startup.
> [NRF5] Add fs_data symbol in data secton for gcc

- hal/targets.json
Move common device_has attributes into MCU_NRF51 and MCU_NRF51_UNIFIED. This ensures all nrf51 devices have the correct features enabled. Any devices that want to explicitly disable features should use device_has_remove.
> Add device_has to all nrf51 devices

- tools/project_api.py
This reduces the size of said zip-files and is used by the online exporters
> tools-exporters! - disable inclusion of repo-dirs in zips by default

- hal/targets/hal/TARGET_NORDIC/TARGET_NRF5/serial_api.c
These changes were needed to make daplink-validation test pass (it uses baud rate 56000, which was not properly handled by previous implementation).
> TARGET_NRF5: Changed 'serial_baud' implementation to support special baud rates.

- hal/targets/hal/TARGET_STM/TARGET_STM32L4/TARGET_DISCO_L476VG/PinNames.h
Add usual definition as in other STM32 targets
READY
> DISCO_L476VG: add SPI nicknames

- tools/toolchains/arm.py
- tools/toolchains/gcc.py
- tools/toolchains/iar.py
Adds a warning about changing flags, and record where the profiles go
when the flags change
> tools - Add documentation about profiles to the toolcahins

- hal/targets/hal/TARGET_Freescale/TARGET_KSDK2_MCUS/TARGET_K22F/serial_api.c
- hal/targets/hal/TARGET_Freescale/TARGET_KSDK2_MCUS/TARGET_KL27Z/serial_api.c
- hal/targets/hal/TARGET_Freescale/TARGET_KSDK2_MCUS/TARGET_KL43Z/serial_api.c
Prevent assertion error for even parity on KL27, KL43 and K22 platforms. This fix was added to the K64 platform.
**READY
> KSDK serial_api.c: Fix assertion error for ParityEven

- tools/toolchains/iar.py
There is a missing import statement for os.path.exists in the IAR toolchain script. This adds it back in.
**READY**
NO
If you currently run `python tools/build.py -m LPC1768 -t IAR`, it will fail with the error `global name 'exists' is not defined`.
> Fixing archived library builds for IAR

- hal/targets/cmsis/TARGET_NXP/TARGET_LPC11U6X/TOOLCHAIN_GCC_ARM/TARGET_LPC11U68/startup_LPC11U68.cpp
- rtos/rtx/TARGET_CORTEX_M/RTX_CM_lib.h
- rtos/rtx/TARGET_CORTEX_M/RTX_Conf_CM.c
1. STM32F4 - Fix STM32F407VG target name
The target name of STM32F407VG should be TARGET_STM32F407VG,
rather than TARGET_F407VG.
Signed-off-by: Tony Wu <tung7970@gmail.com>
2.  LPC11U6X - Fix multiple definition of operator new/delete
Fix the following linker errors:
ToolException: ./.build/LPC11U68/GCC_ARM/mbed-os/hal/targets/cmsis/TARGET_NXP/TARGET_LPC11U6X/TO
startup_LPC11U68.cpp:(.text._Znwj+0x0): multiple definition of `operator new(unsigned int)'
./.build/LPC11U68/GCC_ARM/mbed-os/hal/common/retarget.o:retarget.cpp:(.text._Znwj+0x0): first de
./.build/LPC11U68/GCC_ARM/mbed-os/hal/targets/cmsis/TARGET_NXP/TARGET_LPC11U6X/TOOLCHAIN_GCC_ARM
startup_LPC11U68.cpp:(.text._Znaj+0x0): multiple definition of `operator new[](unsigned int)' …
> Fix STM32F407VG target name and LPC11U6X linker errors

- features/net/FEATURE_IPV4/lwip-interface/lwip_stack.c
Fixed to return 0 on successful shutdown
should resolve https://github.com/ARMmbed/mbed-os/issues/2554
cc @infinnovation
> lwip - Fixed error code on disconnect TCP socket

- features/frameworks/greentea-client/greentea-client/test_env.h
- features/frameworks/greentea-client/source/test_env.cpp
Notes:
Changes in greentea-client API to support uVisor standalone test framework. Enables PR https://github.com/ARMmbed/uvisor-tests-standalone/pull/2
**READY**
NO
https://github.com/ARMmbed/uvisor-tests-standalone/pull/2
branch | PR
required changes in …
> Changes in greentea-client for uvisor-tests-standalone integration

- hal/targets.json
- hal/targets/cmsis/TARGET_STM/TARGET_STM32F4/stm32f4xx_hal_spi.c
- hal/targets/hal/TARGET_STM/TARGET_STM32F4/TARGET_ARCH_MAX/objects.h
- hal/targets/hal/TARGET_STM/TARGET_STM32F4/TARGET_B96B_F446VE/objects.h
- hal/targets/hal/TARGET_STM/TARGET_STM32F4/TARGET_DISCO_F401VC/objects.h
- hal/targets/hal/TARGET_STM/TARGET_STM32F4/TARGET_DISCO_F407VG/objects.h
- hal/targets/hal/TARGET_STM/TARGET_STM32F4/TARGET_DISCO_F429ZI/objects.h
- hal/targets/hal/TARGET_STM/TARGET_STM32F4/TARGET_DISCO_F469NI/objects.h
- hal/targets/hal/TARGET_STM/TARGET_STM32F4/TARGET_ELMO_F411RE/objects.h
- hal/targets/hal/TARGET_STM/TARGET_STM32F4/TARGET_MTS_DRAGONFLY_F411RE/objects.h
- hal/targets/hal/TARGET_STM/TARGET_STM32F4/TARGET_MTS_MDOT_F405RG/objects.h
- hal/targets/hal/TARGET_STM/TARGET_STM32F4/TARGET_MTS_MDOT_F411RE/objects.h
- hal/targets/hal/TARGET_STM/TARGET_STM32F4/TARGET_NUCLEO_F401RE/objects.h
- hal/targets/hal/TARGET_STM/TARGET_STM32F4/TARGET_NUCLEO_F410RB/objects.h
- hal/targets/hal/TARGET_STM/TARGET_STM32F4/TARGET_NUCLEO_F411RE/objects.h
- hal/targets/hal/TARGET_STM/TARGET_STM32F4/TARGET_NUCLEO_F429ZI/objects.h
- hal/targets/hal/TARGET_STM/TARGET_STM32F4/TARGET_NUCLEO_F446RE/objects.h
- hal/targets/hal/TARGET_STM/TARGET_STM32F4/TARGET_NUCLEO_F446ZE/objects.h
- hal/targets/hal/TARGET_STM/TARGET_STM32F4/TARGET_UBLOX_C029/objects.h
- hal/targets/hal/TARGET_STM/TARGET_STM32F4/common_objects.h
- hal/targets/hal/TARGET_STM/TARGET_STM32F4/spi_api.c
- libraries/tests/utest/spi_asynch/spi_master_asynch.cpp
This PRs adds SPI asynch support to F4 family.
This work is derived from existing work done on MBED 3.0
Test summary:
+--------+---------------------+-----------+---------------+------------------+--------------------+---------------+-------+
| Result | Target              | Toolchain | Test ID       | Test Description | Elapsed Time (sec) | Timeout (sec) | Loops |
+--------+---------------------+-----------+---------------+------------------+--------------------+---------------+-------+
| OK     | NUCLEO_F411RE[F26A] | ARM       | UT_SPI_ASYNCH | Asynch spi test  |        1.93        |       20      |  1/1  |
| OK     | NUCLEO_F429ZI[F1CD] | ARM       | UT_SPI_ASYNCH | Asynch spi test  |        1.92        |       20      |  1/1  |
| OK     | NUCLEO_F446ZE[F130] | ARM       | …
> Dev spi asynch stm32f4

- tools/export/__init__.py
- tools/export/uvision4.py
- tools/test/export/build_test.py
uVision4 is no longer maintained by the Keil team (support was stopped
long time ago).
This is why we need to make the uvision exporter able to generate uVision5
projects by default (which is based on software packs).
Also, adding note that the uvision4 exporter is now deprecated and will be
removed in the future.
@0xc0170 @sg-
> Change default uvision exporter to uvision5

- hal/targets.json
- hal/targets/hal/TARGET_STM/TARGET_STM32F3/lp_ticker.c
- hal/targets/hal/TARGET_STM/TARGET_STM32F3/rtc_api.c
- hal/targets/hal/TARGET_STM/TARGET_STM32F3/rtc_api_hal.h
This PR add a low power timer implementation for STM32F3 targets. ~~It also protect `hal_tick` from multiple init. (it was reset after a wake up from deepsleep)~~
- NUCLEO_F302R8
- NUCLEO_F303K8
- NUCLEO_F303R8
- NUCLEO_F334R8
- DISCO_F334C8
- DISCO_F303VC
- The `1s lp_ticker deepsleep` tests do not pass because on ST targets the `us_timer` is stopped during deepsleep but I manually checked the timing with a oscilloscope and I measured 1.00104s (at least with the NUCLEO_F303RE).
Even if it can give us some false positives, we could change the test to use `lp_ticker_read()` instead of `us_ticker_read()`. The `lp_ticker_read()` and `lp_ticker_set_interrupt()` are already tested by the other tests.
@bulislaw I can add a commit, just let me now if you agree.
- This is failing on GCC due to …
> STM32F3 - Add low power timer

- features/net/FEATURE_IPV4/TESTS/mbedmicro-net/tcp_client_hello_world/main.cpp
- features/net/FEATURE_IPV4/TESTS/mbedmicro-net/udp_echo_client/main.cpp
result status should be set to false by default before starting test execution.
For ex, tcp_client_hello_world test case was always OK event if there is no HTTP connection server.
READY
> FEATURE_IPV4/TESTS: result status could be wrong

- tools/build_api.py
- tools/config.py
- tools/targets.py
- tools/test/config_test/config_test.py
- tools/toolchains/__init__.py
avoids a multi-threading bug in the online export system
> Refactor Target and Config away from global variables

- rtos/rtx/TARGET_CORTEX_A/rt_CMSIS.c
- rtos/rtx/TARGET_CORTEX_M/rt_CMSIS.c
- rtos/rtx/TARGET_CORTEX_M/rt_HAL_CM.h
Before, rtx calls would hard fault in critical sections when an svc instruction was attempted with interrupts disabled.
Code exhibiting the issue:
``` cpp
Semaphore sema;
void called_from_irq_or_thread() {
core_util_critical_section_enter();
stateful_stuff();
sema.release();
more_stateful_stuff();
core_util_critical_section_exit();
}
```
Required changes:
- Added check for CPSR I bit in Cortex-A rtx
- Added check for PRIMASK in Cortex-M rtx
- Modified critical sections in Cortex-M rtx to be recursive
(already recursive in Cortex-A)
cc @c1728p9, @0xc0170
> [rtos] Fix irq-safe rtx calls when inside critical sections

- hal/targets/hal/TARGET_NXP/TARGET_LPC43XX/TARGET_LPC4330/PeripheralNames.h
- hal/targets/hal/TARGET_NXP/TARGET_LPC43XX/TARGET_LPC4330/PinNames.h
- hal/targets/hal/TARGET_NXP/TARGET_LPC43XX/TARGET_LPC4337/PeripheralNames.h
- hal/targets/hal/TARGET_NXP/TARGET_LPC43XX/TARGET_LPC4337/PinNames.h
- hal/targets/hal/TARGET_NXP/TARGET_LPC43XX/analogin_api.c
These changes make it possible to configure adc only pins available in LPC43xx devices.
> Added support for ADC only pins in LPC43xx

- features/net/FEATURE_IPV4/lwip-interface/EthernetInterface.cpp
- features/net/FEATURE_IPV4/lwip-interface/EthernetInterface.h
- features/net/FEATURE_IPV4/lwip-interface/lwip_stack.c
- features/net/FEATURE_IPV4/lwip-interface/lwip_stack.h
- features/net/network-socket/CellularInterface.cpp
- features/net/network-socket/CellularInterface.h
- features/net/network-socket/MeshInterface.h
- features/net/network-socket/NetworkInterface.cpp
- features/net/network-socket/NetworkInterface.h
- features/net/network-socket/WiFiInterface.cpp
- features/net/network-socket/WiFiInterface.h
This is a proposal to add static configuration to network interfaces.
This accomplishes two things:
1. Provides a simple route for adding static IP address support to the base NetworkInterface
2. Provides a simple route for adding configurability to network interfaces and unifies the network interface to consistent connect call, allowing network interfaces to be passed around abstractly
Additional functions:
``` cpp
int NetworkInterface::set_network(const char *ip_address, const char *netmask, const char *gateway);
int NetworkInterface::set_dhcp(bool dhcp);
int WiFiInterface::set_credentials(const char *ssid, const char *pass);
int CellularInterface::set_credentials(const char *apn, const char *user, const char *pass);
```
Let me know any concerns
related discussion …
> nsapi - Add optional API for static configuration of network interfaces

- features/FEATURE_BLE/targets/TARGET_NORDIC/TARGET_NRF5/source/btle/btle.cpp
- features/FEATURE_BLE/targets/TARGET_NORDIC/TARGET_NRF5/source/btle/btle_discovery.cpp
- features/FEATURE_BLE/targets/TARGET_NORDIC/TARGET_NRF5/source/btle/btle_security_pm.cpp
- hal/targets/hal/TARGET_NORDIC/TARGET_NRF5/sdk/ble/peer_manager/pm_buffer.h
- hal/targets/hal/TARGET_NORDIC/TARGET_NRF5/sdk/libraries/util/app_util_platform.h
Peer manager (PM) replace security features implemented so fare by Device Manager. Device manager is a legacy module, not recommended to feature use. Changes touch those targets that uses SoftDevices sd13x. S110 based target (doesn't exist any so fare) keeps Device manager in usage.
merged https://github.com/ARMmbed/mbed-os/pull/2687
- security key distribution settings - signing is not supported.
- PM internal bug (For gcc with -0s optimization an application fail to save a boonding data)
- fuse redeclaration of PACKED macro in nRF5 SDK sources
- deleted unused local reference to nRF5xGap class in bleGattcEventHandler.
> [BLE NRF5] introduce the SDK nRF5 Peer manager into BLE security features

- hal/targets/cmsis/TARGET_Freescale/TARGET_K22F/TOOLCHAIN_ARM_STD/MK22FN512xxx12.sct
- hal/targets/cmsis/TARGET_Freescale/TARGET_K66F/TOOLCHAIN_ARM_STD/MK66FN2M0xxx18.sct
- hal/targets/cmsis/TARGET_Freescale/TARGET_KL27Z/TOOLCHAIN_ARM_STD/MKL27Z64xxx4.sct
- hal/targets/cmsis/TARGET_Freescale/TARGET_KL43Z/TOOLCHAIN_ARM_STD/MKL43Z256xxx4.sct
- hal/targets/cmsis/TARGET_Freescale/TARGET_MCU_K64F/TOOLCHAIN_ARM_STD/MK64FN1M0xxx12.sct
1. This fixes a gap introduced in the memory map of ARMCC toolchain saved of the HEAP. Heap space is allocated at run time inside sys.cpp.
2. Updated to the latest scripts
**READY
1. Fix Heap start address
2. Update to the latest script provided by the Kinetis SDK team
> Updated ARM linker scripts for Kinetis platforms that use SDK 2.0

- tools/tests.py
It seems that my test bench is very slow...
I need to increase the timeout value in order to get the port ready...
READY
> Serial init timeout: increase default value

- features/net/FEATURE_IPV4/lwip-interface/lwip-eth/arch/TARGET_STM/TARGET_STM32F4/TARGET_UBLOX_C029/stm32f4_eth_init.c
- hal/targets.json
Note that the test station could not be connected to the same network as the IUT which resulted in two IPV4 tests failing.
```
+--------------------+---------------+------------------------------------------------------------------------------+---------+--------------------+-------------+
| target             | platform_name | test suite                                                                   | result  | elapsed_time (sec) | copy_method |
+--------------------+---------------+------------------------------------------------------------------------------+---------+--------------------+-------------+
| UBLOX_C029-GCC_ARM | UBLOX_C029    | features-frameworks-utest-tests-unit_tests-basic_test                        | OK      | 9.05               | shell       |
| UBLOX_C029-GCC_ARM …
```
> Added ethernet and enabled IPV4 feature for the EVK-ODIN-W2/C029 target

- hal/common/SerialBase.cpp
Notes:
Fix signed/unsigned comparison warning in SerialBase.cpp
Silence the following compiler warning:
Compile: SerialBase.cpp
[Warning] SerialBase.cpp@34,23: comparison between signed and unsigned integer expressions [-Wsign-compare]
READY
NO
mbed compile -m K64F -t GCC_ARM
> Fix signed/unsigned comparison warning in SerialBase.cpp

- features/net/FEATURE_IPV4/lwip-interface/lwip-eth/arch/TARGET_STM/stm32xx_emac.c
#2685 has been forgotten with #2731
@svastm 
@andreaslarssonublox
READY
Tests with STM32 NUCLEO OK
> STM32 / IPV4: #2685 has been forgotten with #2731

- features/net/FEATURE_IPV4/lwip-interface/lwip-eth/arch/TARGET_STM/stm32xx_emac.c
This patch set a MAC address depending on the target unique Id of each MCU.
READY
Tests with STM32 NUCLEO boards are OK (ARM/IAR/GCC)
> [STM32 NUCLEO] Init MAC address

- hal/targets/hal/TARGET_NXP/TARGET_LPC11U6X/gpio_irq_api.c
This pull request fix an issue of InterruptIn failure in particular port (PIO2[7:0]) of the LPC11U68 platform.
A test code below didn't work properly (no interrupt occurred), because of wrong offset for PINTSEL register setting.
```
Serial pc(USBTX, USBRX);
DigitalOut myled(LED1);
DigitalOut green(LED2, 1);
InterruptIn in(D9); // PIO2_3
void func()
{
green = !green;
}
int main()
{
in.mode(PullUp);
in.fall(&func);
pc.printf("hello, mbed\n");
while(1) {
myled = 1;
wait(0.7);
myled = 0;
wait(1.2);
}
}
```
This PR made fix for offset calculation for PINTSEL register which is described as users manual as follows.
**READY**
None
None
```
Test …
```
> [LPC11U68] Fix pin interrupt select offset

- hal/targets.json
- hal/targets/hal/TARGET_STM/TARGET_STM32F0/lp_ticker.c
- hal/targets/hal/TARGET_STM/TARGET_STM32F0/rtc_api.c
- hal/targets/hal/TARGET_STM/TARGET_STM32F0/rtc_api_hal.h
- hal/targets/hal/TARGET_STM/TARGET_STM32F0/sleep.c
This PR add a low power timer implementation for STM32F0 targets.
need this PR #2640 to pass the tests.
- NUCLEO_F070RB
- NUCLEO_F072RB
- NUCLEO_F091RC
The following ones are not enabled because they don't have a wake up timer, (or it is not supported by STM32CUBE library):
- NUCLEO_F030R8
- NUCLEO_F031K6
- NUCLEO_F042K6
---
* **ARM**
```
+-------------------+---------------+---------------------------------------+-------------------------------------+--------+--------+--------+--------------------+
| target            | platform_name | test suite                            | test case                           | passed | failed | result | elapsed_time (sec) |
+-------------------+---------------+---------------------------------------+----- …
```
> STM32F0 - Add low power timer

- hal/targets.json
- hal/targets/hal/TARGET_STM/TARGET_STM32L1/lp_ticker.c
- hal/targets/hal/TARGET_STM/TARGET_STM32L1/rtc_api.c
- hal/targets/hal/TARGET_STM/TARGET_STM32L1/rtc_api_hal.h
This PR add a low power timer implementation for STM32L1 targets.
- NUCLEO_L152RE
---
* **ARM**
```
+-------------------+---------------+---------------------------------------+-------------------------------------+--------+--------+--------+--------------------+
| target            | platform_name | test suite                            | test case                           | passed | failed | result | elapsed_time (sec) |
+-------------------+---------------+---------------------------------------+-------------------------------------+--------+--------+--------+--------------------+
| NUCLEO_L152RE-ARM | NUCLEO_L152RE | mbed-os-tests-mbed_drivers-lp_timeout | 1ms LowPowerTimeout                 | 1      | 0      | OK     | 0.04 …
```
> STM32L1 - Add low power timer

- hal/targets.json
- hal/targets/hal/TARGET_STM/TARGET_STM32L4/lp_ticker.c
- hal/targets/hal/TARGET_STM/TARGET_STM32L4/rtc_api.c
- hal/targets/hal/TARGET_STM/TARGET_STM32L4/rtc_api_hal.h
This PR add a low power timer implementation for STM32L4 targets.
- DISCO_L476VG
- NUCLEO_L432KC
- NUCLEO_L476RG
---
* **ARM**
```
+-------------------+---------------+---------------------------------------+-------------------------------------+--------+--------+--------+--------------------+
| target            | platform_name | test suite                            | test case                           | passed | failed | result | elapsed_time (sec) |
+-------------------+---------------+---------------------------------------+-------------------------------------+--------+--------+--------+--------------------+
| NUCLEO_L152RE-ARM | NUCLEO_L152RE | mbed-os-tests-mbed_drivers-lp_timeout | 1ms LowPowerTimeout                 | 1      | 0 …
```
> STM32L4 - Add low power timer

- hal/targets/hal/TARGET_STM/TARGET_STM32L4/sleep.c
During deepsleep enter, the STM32L4 devices were entering in `stop mode 0` instead of `stop mode 1` due to a `PWR` clock not initialized.
**READY**
NO
```c++
int main() {
printf("before deepsleep\n");
deepsleep();
printf("after deepsleep\n");
}
```
Flash this code on a STM32L4 and check the power consumption on IDD jumper. It should decrease from 110 uA to 9 uA with this PR
> STM32L4 - Update deepsleep implementation

- tools/export/makefile/__init__.py
Commands must be in quotes on Windows, in case the path contains spaces. Previously, they were escaped with ```"```, but it seems like ```'``` is more agreeable to Windows. 
**READY**
NO
#2577 
**Only reproducible on Windows** 
Run this from master:
```mbed export -m whatever -i make_iar```
Try to execute the makefile.
Repeat with this PR.
@sg- @theotherjimmy @screamerbg
> [Exporters] [Makefile] Single quotes for escaping commands

- tools/toolchains/__init__.py
e.g.:
```
$ mbed compile -t gcc_arm -m k64f -c
[mbed] Auto-installing missing Python modules...
[mbed] WARNING: Unable to auto-install required Python modules.
---
[mbed] WARNING: -----------------------------------------------------------------
[mbed] WARNING: The mbed OS tools in this program require the following Python modules: colorama, requests
[mbed] WARNING: You can install all missing modules by running "pip install -r requirements.txt" in "/home/jimbri01/src/arm-mbed/mbed-os-example-blinky/mbed-os"
[mbed] WARNING: On Posix systems (Linux, Mac, etc) you might have to switch to superuser account or use "sudo"
---
Building project mbed-os-example-blinky (K64F, GCC_ARM)
Scan: .
Scan: FEATURE_IPV6
Scan: FEATURE_IPV4 …
```
> Print percent complete when building

- hal/targets.json
- hal/targets/cmsis/TARGET_STM/TARGET_STM32F3/TARGET_NUCLEO_F303ZE/TOOLCHAIN_ARM_STD/startup_stm32f303xe.S
All MBED OS2 (uARM, GCC, IAR, ARM) and OS5 (GCC, IAR, ARM) tests are OK with that patch and NUCLEO_F303ZE
READY
> [NUCLEO_F303ZE] MBED-OS5 capability

- features/net/FEATURE_IPV4/lwip-interface/lwip-eth/arch/TARGET_STM/stm32xx_emac.c
> Revert "[STM32 NUCLEO] Init MAC address"

- hal/api/Callback.h
- rtos/rtos/RtosTimer.h
- rtos/rtos/Thread.h
Before:
``` cpp
Callback<void()> b = callback(arg, function)
```
After:
```cpp
Callback<void()> b = callback(function, arg)
```
This ordering is more intuitive based on feedback from users. This order was initially considered but proved problematic when integrated with other variable arguments in attach functions.
With `callback` as a separate convenience function, this style no longer presents a problem.
cc @sg-, @pan-, @0xc0170, concerns?
> callback - Reorder optional argument to static C function

- features/net/FEATURE_IPV4/lwip-interface/lwip_stack.c
- features/net/network-socket/NetworkInterface.cpp
- features/net/network-socket/NetworkInterface.h
- features/net/network-socket/NetworkStack.cpp
- features/net/network-socket/NetworkStack.h
- features/net/network-socket/SocketAddress.cpp
- features/net/network-socket/SocketAddress.h
- features/net/network-socket/TCPSocket.cpp
- features/net/network-socket/UDPSocket.cpp
- features/net/network-socket/nsapi_dns.cpp
- features/net/network-socket/nsapi_dns.h
- features/net/network-socket/nsapi_types.h
Currently in the network-socket API, DNS resolution can only be performed implicitly through functions such as `TCPSocket::connect`, `UDPSocket::sendto`, and construction of the `SocketAddress` which is limited, returns no errors, requires an unintuitive stack parameter, and as a constructor does not imply a heavy operation.
Previously, the network-socket API provided `gethostbyname` in the NetworkInterface, but this was removed when the `NetworkStack` class was split out and hidden from users.
This pr proposes adding back the `gethostbyname` function with IPv4 and IPv6 support to the NetworkInterface as well as `dns_add_server` to allow users to add custom DNS servers and work around limited stacks.
``` cpp
/** Translates a hostname to an IP address
*
*  The hostname may be either a …
```
> nsapi - Add explicit DNS interface to the network socket API

- features/net/FEATURE_IPV4/lwip-interface/EthernetInterface.cpp
`EthernetInterface` should default to enabled DHCP to preserve backwards compatibility.
missed change to https://github.com/ARMmbed/mbed-os/pull/2664#issuecomment-248826695
cc @sg-
> lwip - Fix default behaviour of DHCP

- docs/testing_mbed_OS_5.md
- tools/test.py
This PR was spurred in response to https://github.com/ARMmbed/mbed-cli/issues/344, however it has larger implications to make the implementation cleaner and to provide a more consistent experience when building tests.
This addresses the issue where building tests via test.py always triggered
a clean build. This is because the mbed_config.h file was being deleted from
the shared OS build to ensure that the correct config was always being
used. However, this constantly triggered a rebuild of the OS since the
config file was not present.
Due to the shared build, having multiple app configurations that could
override the OS settings is not possible. For this reason, we now ignore
app config files unless explicitly set via the command line option
'--app-config'. Though there will now be two …
> Fixing constant cleaning when compiling tests

- hal/api/Callback.h
Problematic line:
``` cpp
memcpy(&_func, obj, sizeof obj);
```
Should be:
``` cpp
memcpy(&_func, method, sizeof method);
```
Introduced during renaming of callback arguments for clarity: #2794
Unfortunately, the type is hidden by the `memcpy` since method is shoved into an opaque member-function-pointer type. A generic template solution may have avoided this slip up.
This is a quick patch to fix master, I will look into why the tests did not catch this mistake.
Thanks to @kjbracey-arm for tracking this down.
> callback - Fixed parameter misname

- hal/targets.json
- hal/targets/hal/TARGET_STM/TARGET_STM32L0/lp_ticker.c
- hal/targets/hal/TARGET_STM/TARGET_STM32L0/rtc_api.c
- hal/targets/hal/TARGET_STM/TARGET_STM32L0/rtc_api_hal.h
This PR add a low power timer implementation for STM32L0 targets.
- NUCLEO_L053R8
- NUCLEO_L073RZ
- NUCLEO_L011K4
- NUCLEO_L031K6
- DISCO_L053C8
---
* **ARM**
```
+-------------------+---------------+---------------------------------------+-------------------------------------+--------+--------+--------+--------------------+
| target            | platform_name | test suite                            | test case                           | passed | failed | result | elapsed_time (sec) |
+-------------------+---------------+---------------------------------------+-------------------------------------+--------+--------+--------+--------------------+
| NUCLEO_L073RZ-ARM | NUCLEO_L073RZ | mbed-os-tests-mbed_drivers-lp_timeout | 1ms …
```
> STM32L0 - Add low power timer

- hal/targets.json
- hal/targets/hal/TARGET_STM/TARGET_STM32F7/lp_ticker.c
- hal/targets/hal/TARGET_STM/TARGET_STM32F7/rtc_api.c
- hal/targets/hal/TARGET_STM/TARGET_STM32F7/rtc_api_hal.h
This PR add a low power timer implementation for STM32F7 targets.
- NUCLEO_F746ZG
- NUCLEO_F767ZI
- DISCO_F746NG
- DISCO_F769NI
---
* **ARM**
```
+-------------------+---------------+---------------------------------------+-------------------------------------+--------+--------+---------+--------------------+
| target            | platform_name | test suite                            | test case                           | passed | failed | result  | elapsed_time (sec) |
+-------------------+---------------+---------------------------------------+-------------------------------------+--------+--------+---------+--------------------+
| NUCLEO_F746ZG-ARM | NUCLEO_F746ZG | mbed-os-tests-mbed_drivers-lp_timeout | 1ms LowPowerTimeout …
```
> STM32F7 - Add low power timer

- tools/export/iar.py
Removes #2745 IAR from the IAR IDE. The DEFAULT_FLAGS also go to the IAR IDE when exporting. This is a problem, as IAR only allows the c and c++ flags to be distinct through configuration window checkboxes. In other words (and pictures), they share a common list of flags except the following options:
Frustratingly, these can only be set here, and are disallowed from the common list (which looks just as command line flag strings would look). I assume they just append those flags given the selections seen here, as setting them in that list produces duplicated flag errors (even if the boxes are unchecked!).
For now, this optimization will be left off of the IAR IDE options, as it requires some XML shenanigans. I'd like to add that functionality to #2708. As it is, it would require a progen …
> Removed --no_static_destruction from IAR IDE flags

- libraries/USBDevice/USBDevice/USBHAL_STM32F4.cpp
I'm not sure, what was an original idea behind these `USBHAL::EP1_OUT_callback` methods. But it looks like a typo for me.
Someone, please review. =]
> STM32: Clear epComplete flag if a packet has been handled in the callback

- mbed_lib.json
Set correct default stdio baud rate on EFM32 STKs.
Should fix #2791.
@0xc0170
> [EFM32] Set default baud rate to 115200.

- TESTS/mbedmicro-rtos-mbed/threads/main.cpp
NUCLEO_F091RC patch for tests-mbedmicro-rtos-mbed-threads
Previous status:
- OK with GCC and ARM
- FAIL with IAR
READY
```
+-------------------+---------------+-----------------------------------+--------------------------------------+--------+--------+--------+--------------------+
| target            | platform_name | test suite                        | test case                            | passed | failed | result | elapsed_time (sec) |
+-------------------+---------------+-----------------------------------+--------------------------------------+--------+--------+--------+--------------------+
| NUCLEO_F091RC-IAR | NUCLEO_F091RC | tests-mbedmicro-rtos-mbed-threads | Testing parallel threads             | 1      | 0      | OK     | 0.06               |
| NUCLEO_F091RC-IAR | …
```
> [STM32F091RC] patch for tests-mbedmicro-rtos-mbed-threads

- hal/targets/cmsis/TARGET_STM/TARGET_STM32F4/TARGET_DISCO_F429ZI/TOOLCHAIN_ARM_STD/startup_stm32f429xx.s
- hal/targets/cmsis/TARGET_STM/TARGET_STM32F4/TARGET_DISCO_F429ZI/TOOLCHAIN_ARM_STD/stm32f429xx.sct
- hal/targets/cmsis/TARGET_STM/TARGET_STM32F4/TARGET_NUCLEO_F429ZI/TOOLCHAIN_ARM_STD/startup_stm32f429xx.s
- hal/targets/cmsis/TARGET_STM/TARGET_STM32F4/TARGET_NUCLEO_F429ZI/TOOLCHAIN_ARM_STD/stm32f429xx.sct
- hal/targets/cmsis/TARGET_STM/mbed_rtx.h
rtos-rtx-target_cortex_m-tests-memory-heap_and_stack was failed with DISCO_F429ZI and NUCLEO_F429ZI
New tests status for both targets:
- MBED OS2 tests OK with GCC/ARM/IAR
- MBED OS5 tests OK with GCC/ARM/IAR
READY
> [STM32F429ZI] INITIAL_SP correction

- hal/targets.json
- hal/targets/hal/TARGET_STM/TARGET_STM32F4/lp_ticker.c
- hal/targets/hal/TARGET_STM/TARGET_STM32F4/rtc_api.c
- hal/targets/hal/TARGET_STM/TARGET_STM32F4/rtc_api_hal.h
This PR add a low power timer implementation for STM32F0 targets.
- NUCLEO_F411RE
- NUCLEO_F401RE
- DISCO_F429ZI
- NUCLEO_F446RE
- NUCLEO_F410RB
- DISCO_F469NI
- NUCLEO_F446ZE
- B96B_F446VE
---
* **ARM**
```
+-------------------+---------------+---------------------------------------+-------------------------------------+--------+--------+---------+--------------------+
| target            | platform_name | test suite                            | test case                           | passed | failed | result  | elapsed_time (sec) |
+-------------------+---------------+---------------------------------------+-------------------------------------+--------+--------+---------+--------------------+
| NUCLEO_F410RB-ARM | NUCLEO_F410RB | …
```
> STM32F4 - Add low power timer

- TESTS/mbedmicro-rtos-mbed/basic/main.cpp
- TESTS/mbedmicro-rtos-mbed/isr/main.cpp
- TESTS/mbedmicro-rtos-mbed/mail/main.cpp
- TESTS/mbedmicro-rtos-mbed/mutex/main.cpp
- TESTS/mbedmicro-rtos-mbed/queue/main.cpp
- TESTS/mbedmicro-rtos-mbed/semaphore/main.cpp
- TESTS/mbedmicro-rtos-mbed/signals/main.cpp
- libraries/tests/rtos/mbed/basic/main.cpp
- libraries/tests/rtos/mbed/isr/main.cpp
- libraries/tests/rtos/mbed/mail/main.cpp
- libraries/tests/rtos/mbed/mutex/main.cpp
- libraries/tests/rtos/mbed/queue/main.cpp
- libraries/tests/rtos/mbed/semaphore/main.cpp
- libraries/tests/rtos/mbed/signals/main.cpp
Just a patch to clean RTOS tests as we doesn't support any more RTOS for some targets since #2648
READY
> Clean RTOS tests after PR #2648

- hal/targets/hal/TARGET_NXP/TARGET_LPC13XX/pwmout_api.c
- libraries/tests/mbed/pwm/main.cpp
Fix PwmOut prescaler for 16-bit timer on the LPC1347 platform.
See #2660 more detail.
**READY**
https://github.com/ARMmbed/mbed-os/issues/2660#issue-176174346
```
Test summary:
+---------------+---------+-----------+-------------+---------------------------------------+--------------------+---------------+-------+
| Result        | Target  | Toolchain | Test ID     | Test Description                      | Elapsed Time (sec) | Timeout (sec) | Loops |
+---------------+---------+-----------+-------------+---------------------------------------+--------------------+---------------+-------+
| OK            | LPC1347 | ARM       | DTCT_1      | Simple detect test                    |        0.51        |       10      |  1/1  |
| OK            | LPC1347 | ARM       | EXAMPLE_1   | /dev/null …
```
> [LPC1347] Fix PwmOut prescaler for 16-bit timer 

- TESTS/mbedmicro-rtos-mbed/threads/main.cpp
Current status:
| NUCLEO_F410RB-IAR | NUCLEO_F410RB | tests-mbedmicro-rtos-mbed-threads                                            | TIMEOUT | 86.19              | shell       |
Test has been updated and is OK now for all tool chains.
READY
> [STM32F410RB] update OS5 RTOS thread test

- features/net/FEATURE_IPV6/nanostack-interface/NanostackInterface.cpp
When the border router is switched off, the several retries will end up triggering the asserts in NanostackSocket::open. This is caused because socket_tbl elements, are never set to NULL. This fix prevents that.
**READY**
https://github.com/ARMmbed/mbed-os/issues/2840
> Fixed assert failure on reconections

- hal/api/Callback.h
The callback class can now accept generalized function-objects:
``` cpp
class Thing {
public:
int value;
void operator()() {
printf("hi! %d\n", value);
}
};
Callback<void()> cb(Thing(2));
```
However, with the intention of avoiding implicit dynamic-memory allocations, the Callback class is limited to a single word of storage. Exceeding this size will eliminate the function-object type from the
overload set and fail to compile.
Effort was invested to make this situation very clear to the user. Here is an example error message with noise removed:
``` 
[ERROR] ./main.cpp: In function 'int main()':
./mbed-os/hal/api/Ticker.h:101:10: note:
no known conversion for argument 1 from 'BigFunc' to 'mbed::Callback<void()>'
```
The real benefit of this change is the ability for users to hook into the …
> callback - Add size-limited function-object overloads to Callback 

- tools/test/examples/examples.json
- tools/test/examples/examples.py
This PR was driven by the fact that the uVisor example only supports being compiled for K64F with GCC_ARM.
In order to support this, this adds the ability to filter examples by toolchains.
It then uses these changes to limit the uvisor example to just the GCC_ARM toolchain
**READY**
NO
> [Tests] Example build toolchain filtering

- tools/config.py
- tools/targets.py
Fixes tools exceptions caused by backporting #2757 without #2691 
In particular, changes the way it which custom targets are handled after the config refactor.
> Release - Update custom target handling

- TESTS/mbedtls/selftest/main.cpp
This set of tests is a port of the mbed TLS test program at `mbedtls/programs/test/selftest.c`. The test executes the `mbedtls_*_self_test()` functions in the library modules and checks the output (PASS, FAIL). This patch ports the self test program to use mbedgt instead but maintains the same functionality.
> Port mbed TLS self test to greentea

- .travis.yml
- tools/memap.py
- tools/test/memap/memap_test.py
- tools/toolchains/__init__.py
This fixes an issue where the output from memap.py was not
consistent across all output formats. This issue stemmed from the fact
that a few important calculations were being performed at output
generation time. This has been moved to the 'parse' function and saved for
future use by the 'generate' functions.
YES
Because this commit saves more data to the MemapParser instance, there
were some name collisions. The public member 'mem_summary' has been
renamed to 'mem_report'. 'mem_report' contains the data structure used by
the json generator. This includes both the section data and the memory
summary. The 'mem_summary' member now just contains the …
> [tools] Making memap output consistent across output formats

- tools/toolchains/arm.py
- tools/toolchains/gcc.py
- tools/toolchains/iar.py
This functionality was already present in the ARM toolchain script, but
this commit adds this across all toolchain scripts. Solves an issue that
cropped up where a build error wasn't being printed unless the verbose
flag was used. This should now print any existing error messages that have
been printed when the compiler output is being parsed.
**READY**
NO, **however this does touch the toolchain scripts, so this definitely needs to be under review for a bit before it gets merged.**
This issue cropped up on the IAR build of this PR in CI: https://github.com/ARMmbed/mbed-os/pull/2849
The build correctly failed, however the error message was not printed
This may add more …
> [Tools] Making all toolchains print final compiler message

- hal/targets/cmsis/TARGET_STM/mbed_rtx.h
Fix multiple STM32F411RE definitions in mbed_rtx.h. Increase main stack size for MTS_MDOT_F411RE and MTS_DRAGONFLY_F411RE. Fix wrong OS_CLOCK definition for MTS_MDOT_F411RE and MTS_DRAGONFLY_F411RE.
Resolves #2858.
**READY**
> resolve multiple STM32F411RE configurations in mbed_rtx.h

- tools/build_api.py
This PR copies the main mbed config file (`mbed_lib.json` in the root of `mbed-os`) into the `<build_directory>/mbed/TARGET_<target_name>` folder. This can then be used when building tests using the mbed 2 flows.
**READY**
NO
This should unblock PR https://github.com/ARMmbed/mbed-os/pull/2422
I'm a bit concerned that I'm copying json file either at the wrong point in the mbed lib build process OR that I'm copying it to the wrong directory. If you have any feedback on this @screamerbg that'd be great!
> [Tools] Copying main config json file for mbed lib builds

- tools/test_api.py
Previously, when building tests with `test.py`, if an exception occurred, the
error message would be masked by the function 'build_tests'. This commit
handles `NotSupportedException`s and `ToolException`s, but lets all other
Exceptions propigate up to the caller function. In most cases, this is the
CLI scripts, which will print a traceback. This will allow us to better
debug the python tools if errors occur.
**READY**
NO
> [Tools] Handling Exceptions better when building tests

- .travis.yml
- tools/build_api.py
- tools/test/build_api/build_api_test.py
- tools/toolchains/__init__.py
Correct incremental percent printing.
**READY**
Nope
1. ```$ touch mbed-os/hal/api/Callback.h```
2. ```$ mbed compile ```
```
[mbed] Auto-installing missing Python modules...
Building project mbed-os-example-blinky (K64F, GCC_ARM)
Scan: .
Scan: FEATURE_IPV6
Scan: FEATURE_IPV4
Scan: mbed
Scan: env
Compile [ 89.1%]: greentea_serial.cpp
Compile [ 89.4%]: main.cpp
Compile [ 89.8%]: greentea_metrics.cpp
Compile [ 90.1%]: unity_handler.cpp
Compile [ 90.4%]: mbed-utest-shim.cpp
Compile [ 90.8%]: utest_case.cpp
Compile [ 91.1%]: utest_default_handlers.cpp
Compile [ 91.5%]: test_env.cpp
Compile [ 91.8%]: utest_greentea_handlers.cpp
Compile [ 92.2%]: utest_shim.cpp
Compile [ 92.5%]: utest_types.cpp
Compile [ …
```
> Correct percent printing

- TESTS/mbed_functional/callback/main.cpp
- TESTS/mbed_functional/callback_big/main.cpp
- TESTS/mbed_functional/callback_small/main.cpp
- hal/api/Callback.h
Note: This has no api changes, just removes an erronous set of overloads:
``` cpp
class Func {
public:
operator()() {};
}
ticker.attach(Func());            // perfectly fine
ticker.attach(callback(Func());   // compile error
```
Unfortunately, it is very difficult to infer the parameters of function-objects generically in C++03 without any additional type information. The current implementation fails to do so, and the compiler simply bails with "unable to deduce template parameter".
Rather than leaving the user with a small novel of error messages, this patch removes the problematic callback overloads, leaving only callback overloads for the original pointer types.
Also updated the tests based on argument order.
related issue in mbed-events: https://github.com/ARMmbed/mbed-events/pull/24 …
> callback - Remove problematic callback overloads

- hal/targets.json
- tools/build_api.py
- tools/git_hooks/find_duplicates.py
- tools/test/toolchains/api.py
- tools/toolchains/__init__.py
Find duplicate object files and header files as part of the build process.
Also contains a git hook.
**READY**
Nope
```
$ mbed compile
[mbed] Auto-installing missing Python modules...
Building project mbed-os-example-blinky (K64F, GCC_ARM)
Scan: .
Scan: FEATURE_IPV6
Scan: FEATURE_IPV4
Scan: mbed
Scan: env
+------------------+-------+-------+-------+
| Module           | .text | .data |  .bss |
+------------------+-------+-------+-------+
| Fill             |    70 |     4 |  2532 |
| Misc             | 26603 |  2212 |    88 |
| features/storage |    42 |     0 |   184 |
| hal/common       |  1560 |     4 |   277 |
| hal/targets      | 10004 |    12 |   188 |
| rtos/rtos        |    38 |     4 |     4 |
| …
```
> [Tools] Find and report duplicates

- tools/memap.py
Adds more detail to the Misc contents from memap.py 
**READY**
NO
> [Tools] Added -d (--detailed) paremeter to unfold 'Misc' contents in memap.py table

- events/equeue/equeue.c
Added workaround for armc assumptions on integer underflow
With ARM Compiler 5.06u3, when the equeue_tickdiff function is inlined, the compiler treats the unsigned integer subtraction as undefined behaviour and assumes falsely the comparisons could never be true.
The workaround is to an explicit cast, which politely reminds the compiler to emit the correct comparison.
> events - Add workaround for armc assumptions on integer overflow

- tools/export/sw4stm32.py
To make the exporter easier to maintain and avoid duplicated data. Use the information from targets.json about floating point unit to chose the correct config in the exporter template.
**READY**
NO
This is an enhancement of this PR #2811
> SW4STM32 - Use targets.json to find fp config

- tools/test/toolchains/api.py
Prevent the garbage folders from showing up after running tests. They were caused by some compile command function generating directories.
**READY**
Nope!
Run `py.test tools/test/toolchain/api.py`
```
$ py.test tools/test/toolchains/api.py
========================================== test session starts ==========================================
platform linux2 -- Python 2.7.12, pytest-3.0.2, py-1.4.31, pluggy-0.3.1
rootdir: /home/jimbri01/src/mbedmicro/mbed, inifile: 
plugins: hypothesis-3.5.2, quickcheck-0.8.2
collected 5 items 
tools/test/toolchains/api.py .....
======================================= 5 passed in 2.24 seconds ========================================
$ ls
`                     [A?                   Jenkinsfile         #%\`RiS
~<                    aVqu                  K …
```
> [Tests] Prevent garbage generation from toolchain api test

- targets/targets.json
> HEXIWEAR: Enable the entropy collector for use in mbed TLS

- tools/export/sw4stm32.py
- tools/export/uvision4.py
- tools/export/uvision5.py
- tools/project.py
- tools/test/export/build_test.py
- tools/utils.py
This PR is in response to issue #2892, with commits from both myself and @sarahmarshy.
When build profiles came in (#2802), the exporter build test script was missed. There were also some exporter script issues left over from the reorganization (#2878). This PR fixes those issues.
**READY**
NO
> [Exporters] Resolving Python errors and uVision build issues

- drivers/RawSerial.cpp
- drivers/RawSerial.h
- drivers/Serial.cpp
- drivers/Serial.h
- drivers/SerialBase.cpp
- drivers/SerialBase.h
- platform/mbed_lib.json
This commit adds a `baud` argument for Serial and RawSerial objects:
- there is a new `Serial` constructor with a mandatory baud rate
argument. The old constructor also got a `baud` argument with a
default value (to keep backward compatibility).
- the `RawSerial` constructor also got a `baud` argument with a default
value.
There's also a new configuration parameter (`default-serial-baud-rate`)
that can be used to specify the default value of the above `baud`
arguments.
> Added a baud argument for (Raw)Serial objects

- TESTS/mbedmicro-rtos-mbed/basic/main.cpp
- TESTS/mbedmicro-rtos-mbed/isr/main.cpp
- TESTS/mbedmicro-rtos-mbed/mail/main.cpp
- TESTS/mbedmicro-rtos-mbed/mutex/main.cpp
- TESTS/mbedmicro-rtos-mbed/queue/main.cpp
- TESTS/mbedmicro-rtos-mbed/semaphore/main.cpp
- TESTS/mbedmicro-rtos-mbed/signals/main.cpp
- TESTS/mbedmicro-rtos-mbed/threads/main.cpp
Fix RTOS unit test failures for xDot platform. Due to memory constraints, the default stack size for xDot is 256 bytes. This appears to be too small for some unit tests, so we increase it to 1024 for the tests.
**READY**
> fix RTOS unit tests for MultiTech xDot platform

- .gitignore
The latest versions of mbed-cli generate their output in BUILD/ instead
of .build/. This commit adds BUILD/ to the list of git ignored
directories.
> Ignore BUILD directory

- targets/cmsis/TARGET_ONSEMI/TARGET_NCS36510/TOOLCHAIN_GCC_ARM/NCS36510.ld
Decrease the minimum space reserved for the heap from 16K down to
2K for GCC. This does not have an effect on the actual heap size since
the heap takes up all free RAM. This just allows code to compile in
configurations where the heap is smaller than 16K.
> NCS36510 - decrease reserved heap space

- events/Event.h
- platform/Callback.h
In the IAR ide, implicitly generated structures based on function templates end up with missing type information. This has no effect on using the IAR compiler standalone, but when used through the ide the missing type information causes the ide to error.
As a workaround, moved the function attributes generated for the Callback and Event classes into the class scope. This avoids the syntax that confuses IAR.
cc @pan-, @bridadan, @sarahmarshy
> callback - Add workaround for IAR issue with type information

- features/nanostack/FEATURE_NANOSTACK/targets/TARGET_NCS36510/NanostackRfPhyNcs36510.cpp
- features/nanostack/FEATURE_NANOSTACK/targets/TARGET_NCS36510/NanostackRfPhyNcs36510.h
Check in the RF phy for the ncs36510. Note that the RF phy is included
in the built when nanostack is included since the phy is specific to
nanostack.
> Add ncs36510 RF phy

- platform/retarget.cpp
- rtos/rtx/TARGET_CORTEX_M/RTX_CM_lib.h
- targets/TARGET_STM/TARGET_STM32F0/mbed_overrides.c
- targets/TARGET_STM/TARGET_STM32F0/pwmout_api.c
- targets/TARGET_STM/TARGET_STM32F0/serial_api.c
- targets/TARGET_STM/TARGET_STM32F1/mbed_overrides.c
- targets/TARGET_STM/TARGET_STM32F1/pwmout_api.c
- targets/TARGET_STM/TARGET_STM32F1/serial_api.c
- targets/TARGET_STM/TARGET_STM32F2/serial_api.c
- targets/TARGET_STM/TARGET_STM32F3/i2c_api.c
- targets/TARGET_STM/TARGET_STM32F3/mbed_overrides.c
- targets/TARGET_STM/TARGET_STM32F3/serial_api.c
- targets/TARGET_STM/TARGET_STM32F4/mbed_overrides.c
- targets/TARGET_STM/TARGET_STM32F4/serial_api.c
- targets/TARGET_STM/TARGET_STM32F7/mbed_overrides.c
- targets/TARGET_STM/TARGET_STM32F7/serial_api.c
- targets/TARGET_STM/TARGET_STM32L0/mbed_overrides.c
- targets/TARGET_STM/TARGET_STM32L1/mbed_overrides.c
- targets/TARGET_STM/TARGET_STM32L1/pwmout_api.c
- targets/TARGET_STM/TARGET_STM32L1/serial_api.c
- targets/TARGET_STM/TARGET_STM32L4/mbed_overrides.c
- targets/TARGET_STM/TARGET_STM32L4/pwmout_api.c
- targets/TARGET_STM/TARGET_STM32L4/serial_api.c
Rebase #2160 on to master in perpetration for the release.
> Initialization steps in toolchains 

- tools/profiles/debug.json
with option  --profile ./tools/profiles/debug.json , the IAR built is failed
READY
No change needed
python ./tools/build.py -m DISCO_L476VG -t IAR --profile ./tools/profiles/debug.json
command return  
Fatal error[Su011]: More than one source file specified:
non-native end of line sequence
> [IAR build] fix debug build

- targets/TARGET_RENESAS/TARGET_RZ_A1H/pwmout_api.c
- targets/TARGET_RENESAS/TARGET_VK_RZ_A1H/pwmout_api.c
I fixed bugs of PWM driver.
Bugs are as below.
- In the case of MTU2 mode, modify a problem that does not excute "pwmout_write ()" at the end of "pwmout_pulsewidth_us ()" function.
- In the case of MTU2 mode in "pwmout_period_us ()" function, modify a problem that the executing result of "set_mtu2_duty_again ()" function does not reflect in the register of TGRA_MATCH [] and TGRC_MATCH [].
> Fix bugs of PWM driver.

- features/nanostack/FEATURE_NANOSTACK/targets/TARGET_NCS36510/NanostackRfPhyNcs36510.cpp
- features/nanostack/FEATURE_NANOSTACK/targets/TARGET_NCS36510/NanostackRfPhyNcs36510.h
Fix the header guard in the ncs36510 RF driver. Also update the license in NanostackRfPhyNcs36510.h.
> Fix ncs36510 by updating header guard

- features/mbedtls/importer/adjust-config.sh
This PR makes it possible to use the default config whenever `MBEDTLS_TEST_NULL_ENTROPY` instead of the config-no-entropy.h. Furthermore, an include of `MBEDTLS_USER_CONFIG_FILE` is added whenever config-no-entropy.h is in use. This makes it possible for users to use config-no-entropy.h AND customise it by providing custom config options.
READY
NO
There are no related PRs pending for merge.
- [X ] Documentation
This change does not require any changes, simply use mbedtls as normal.
> Fix mbedtls user config and null entropy

- targets/TARGET_STM/TARGET_STM32F7/TARGET_DISCO_F746NG/PeripheralPins.c
- targets/TARGET_STM/TARGET_STM32F7/TARGET_DISCO_F746NG/PinNames.h
- targets/TARGET_STM/TARGET_STM32F7/TARGET_DISCO_F769NI/PeripheralPins.c
- targets/TARGET_STM/TARGET_STM32F7/TARGET_DISCO_F769NI/PinNames.h
- targets/TARGET_STM/TARGET_STM32F7/TARGET_NUCLEO_F746ZG/PeripheralPins.c
- targets/TARGET_STM/TARGET_STM32F7/TARGET_NUCLEO_F746ZG/PinNames.h
- targets/TARGET_STM/TARGET_STM32F7/TARGET_NUCLEO_F767ZI/PeripheralPins.c
- targets/TARGET_STM/TARGET_STM32F7/TARGET_NUCLEO_F767ZI/PinNames.h
- targets/TARGET_STM/TARGET_STM32F7/analogin_api.c
Add the support of ADC internal channels.
READY
NO changes in API or behaviors.
#2924 #2923 #2814 #2681 #2538
> STM32F7xx - Add support of ADC internal channels

- targets/TARGET_STM/TARGET_STM32F0/analogin_api.c
Use the ADC internal channels specific definitions instead of using the channel number.
READY
No API or behavior change.
> STM32F0xx - Use ADC internal channels specific definitions

- targets/TARGET_Freescale/TARGET_KSDK2_MCUS/TARGET_MCU_K64F/TARGET_FRDM/PinNames.h
Modifying D8 to reflect latest hardare changes in RevD hardware
https://github.com/ARMmbed/mbed-os/issues/2933
> Change K64F D8 pin from PTA0->PTC12

- features/mbedtls/VERSION.txt
- features/mbedtls/importer/Makefile
- features/mbedtls/importer/adjust-config.sh
- features/mbedtls/inc/mbedtls/check_config.h
- features/mbedtls/inc/mbedtls/cipher.h
- features/mbedtls/inc/mbedtls/cmac.h
- features/mbedtls/inc/mbedtls/config.h
- features/mbedtls/inc/mbedtls/md.h
- features/mbedtls/src/Makefile
- features/mbedtls/src/cipher.c
- features/mbedtls/src/cmac.c
- features/mbedtls/src/version_features.c
This PR updates the feature mbedtls with the development HEAD of the mbed TLS repo. It contains the latest features (such as CMAC) and bug fixes. However, this is NOT the next release of mbed TLS, there will be a separate PR to update the feature once more when the release is complete.
READY
The PR adds new APIs for the CMAC mbed TLS feature.
YES 
This PR builds on top of https://github.com/ARMmbed/mbed-os/pull/2926
- Documentation
This PR should not cause any disruption, simply use mbed OS as normal.
> Update mbed TLS with the development HEAD

- features/netsocket/nsapi_dns.cpp
DNS name resolution was returning error even for successful cases
**READY**
CC: @geky @0xc0170
> DNS: Fix return value for successful name resolutions

- targets/TARGET_STM/TARGET_STM32L0/TARGET_DISCO_L053C8/PeripheralPins.c
- targets/TARGET_STM/TARGET_STM32L0/TARGET_DISCO_L053C8/PinNames.h
- targets/TARGET_STM/TARGET_STM32L0/TARGET_NUCLEO_L011K4/PeripheralPins.c
- targets/TARGET_STM/TARGET_STM32L0/TARGET_NUCLEO_L011K4/PinNames.h
- targets/TARGET_STM/TARGET_STM32L0/TARGET_NUCLEO_L031K6/PeripheralPins.c
- targets/TARGET_STM/TARGET_STM32L0/TARGET_NUCLEO_L031K6/PinNames.h
- targets/TARGET_STM/TARGET_STM32L0/TARGET_NUCLEO_L053R8/PeripheralPins.c
- targets/TARGET_STM/TARGET_STM32L0/TARGET_NUCLEO_L053R8/PinNames.h
- targets/TARGET_STM/TARGET_STM32L0/TARGET_NUCLEO_L073RZ/PeripheralPins.c
- targets/TARGET_STM/TARGET_STM32L0/TARGET_NUCLEO_L073RZ/PinNames.h
- targets/TARGET_STM/TARGET_STM32L0/analogin_api.c
Add the support of ADC internal channels (Temperature, VREF, VLCD) on STM32L0xx devices.
READY
No changes in API or behaviors.
#2928 #2924 #2923 #2814 #2681 #2538
> STM32L0xx - Add support of ADC internal channels

- targets/TARGET_STM/TARGET_STM32F4/gpio_irq_api.c
- targets/TARGET_STM/TARGET_STM32F4/pinmap.c
This is a fix to issue #2638
The pull-up / pull-down mode was overwritten
**READY**
non regression on F4 family is ok 
Test summary:
+--------------+---------------------+-----------+-------------+---------------------------------------+--------------------+---------------+-------+
| Result       | Target              | Toolchain | Test ID     | Test Description                      | Elapsed Time (sec) | Timeout (sec) | Loops |
+--------------+---------------------+-----------+-------------+---------------------------------------+--------------------+---------------+-------+
| OK           | DISCO_F429ZI[F0A3]  | ARM       | DTCT_1      | Simple detect test                    |        0.45        |       10      |  1/1  |
| OK           | DISCO_F429ZI[F0A3]  | ARM       | EXAMPLE_1   | …
> Fix pull overwrite

- targets/TARGET_STM/TARGET_STM32L4/TARGET_DISCO_L476VG/PeripheralPins.c
- targets/TARGET_STM/TARGET_STM32L4/TARGET_DISCO_L476VG/PinNames.h
- targets/TARGET_STM/TARGET_STM32L4/TARGET_NUCLEO_L432KC/PeripheralPins.c
- targets/TARGET_STM/TARGET_STM32L4/TARGET_NUCLEO_L432KC/PinNames.h
- targets/TARGET_STM/TARGET_STM32L4/TARGET_NUCLEO_L476RG/PeripheralPins.c
- targets/TARGET_STM/TARGET_STM32L4/TARGET_NUCLEO_L476RG/PinNames.h
- targets/TARGET_STM/TARGET_STM32L4/analogin_api.c
Add the support of ADC internal channels (Temperature, VREF, VLCD) on STM32L4xx devices.
READY
No changes in API or behaviors.
#2946 #2928 #2924 #2923 #2814 #2681 #2538
> STM32L4xx - Add support of ADC internal channels

- tools/memap.py
I'm getting:
```
Allocated Heap: 32768 bytes
Allocated Stack: 16384 bytes
Total Static RAM memory (data + bss): 11896 bytes
Total RAM memory (data + bss + heap + stack): 61048 bytes
Total Flash memory (text + data + misc): 44975 bytes
File "/Users/barsza01/devel/mbed/bulislaw/mbed-os-example-blinky/mbed-os/tools/make.py", line 292, in <module>
toolchain))
File "/Users/barsza01/devel/mbed/bulislaw/mbed-os-example-blinky/mbed-os/tools/build_api.py", line 455, in build_project
res, _ = toolchain.link_program(resources, build_path, name)
File "/Users/barsza01/devel/mbed/bulislaw/mbed-os-example-blinky/mbed-os/tools/toolchains/__init__.py", line 999, in link_program
self.map_outputs = self.mem_stats(map)
File …
```
> Fix file path quoting while constructing CSV file in memmap.py

- targets/TARGET_STM/TARGET_STM32L0/TARGET_NUCLEO_L073RZ/device/TOOLCHAIN_ARM_MICRO/stm32l073xz.sct
- targets/TARGET_STM/TARGET_STM32L0/TARGET_NUCLEO_L073RZ/device/TOOLCHAIN_ARM_STD/stm32l073xz.sct
The changes modify the flash size for Nucleo L073RZ and fix a bug when trying to compile a program with a size greater than 64K.
Try to compile a program greater than 64K in the online IDE. I get this error:
Error number: L6220E
Load region LR_IROM1 size (69108 bytes) exceeds limit (65536 bytes). Region contains 105 bytes of padding and 0 bytes of veneers (total 105 bytes of linker generated content).
> Modify the flash size for Nucleo L073RZ.
