- libraries/mbed/targets/hal/TARGET_STM/TARGET_NUCLEO_F303RE/analogin_api.c
> [NUCLEO_F303RE] Correct ADC initialization

- workspace_tools/export/__init__.py
The previous fix (https://github.com/mbedmicro/mbed/pull/846) only worked on windows. This is a patch to that to work on all OS's
> Fix readme.html

- libraries/tests/mbed/sd/main.cpp
read_result always  false when read file success
> fix read_result always  false

- libraries/mbed/targets/hal/TARGET_STM/TARGET_NUCLEO_F103RB/gpio_irq_api.c
- libraries/mbed/targets/hal/TARGET_STM/TARGET_NUCLEO_F103RB/objects.h
- EXTI lines 5 to 9
- EXTI lines 10 to 15
> Updated gpio irq hal with max num of irq

- libraries/mbed/targets/hal/TARGET_RENESAS/TARGET_RZ_A1H/analogin_api.c
- libraries/mbed/targets/hal/TARGET_RENESAS/TARGET_RZ_A1H/device.h
- libraries/mbed/targets/hal/TARGET_RENESAS/TARGET_RZ_A1H/gpio_api.c
- libraries/mbed/targets/hal/TARGET_RENESAS/TARGET_RZ_A1H/gpio_object.h
- libraries/mbed/targets/hal/TARGET_RENESAS/TARGET_RZ_A1H/i2c_api.c
- libraries/mbed/targets/hal/TARGET_RENESAS/TARGET_RZ_A1H/objects.h
- libraries/mbed/targets/hal/TARGET_RENESAS/TARGET_RZ_A1H/rtc_api.c
- libraries/mbed/targets/hal/TARGET_RENESAS/TARGET_RZ_A1H/serial_api.c
- libraries/mbed/targets/hal/TARGET_RENESAS/TARGET_RZ_A1H/us_ticker.c
Hi,
We add some function and fix some bugs as below.
RTC
Add RTC function.
Serial
Add Serial flow control and fix a bug that parity setting is wrong.
Modifies are as below.
- Add flow control
- Change the range of baud rate that can be set in the baud function.
　8138 bps more -> 128 bps more
- Fixed a bug that designation of parity had been reversed in format().
AnalogIn
Modify some processing of AnalgIn.
Modifies are as below.
- Change the A/D conversion time to run fast.
- Change the macro value of ANALOGIN_MEDIAN_FILTER
1 -> 0
I2C
Add some processing of I2C driver
Changes are as below
- Add STOP condition omission processing of I2C Master
- Add I2C Slave processing 
Ticker
Modify ticker driver to make consistent with Pull Reqest#839 and #864.
gpio_object.h
Add include mbed_assert.h. …
> [RZ_A1H]Add some function and fix some bugs.

- libraries/mbed/targets/cmsis/TARGET_Freescale/TARGET_K22F/cmsis_nvic.c
- libraries/mbed/targets/cmsis/TARGET_Freescale/TARGET_K22F/cmsis_nvic.h
> Targets - K22 - fix issue #758 - vectors number + allocation

- libraries/mbed/targets/hal/TARGET_NXP/TARGET_LPC43XX/ethernet_api.c
> Initial ethernet support for LPC433x

- workspace_tools/export/.hgignore
- workspace_tools/export/__init__.py
Changed the URL for getting started with offline exporters, as per @screamerbg 's request.
Added .hgignore file to make bringing files back online easier. 
@sg- over here
> Update to Offline Exporters

- libraries/rtos/rtx/TARGET_CORTEX_A/RTX_Conf_CA.c
Hi,
We modify OS setting of private thread num.
Increase private thread num.
Regards,
Hamanaka
> [RZ/A1H]Increase private thread num.

- workspace_tools/host_tests/echo.py
- workspace_tools/targets.py
- workspace_tools/toolchains/__init__.py
Changes
* Better output extension handling in link_program()
* Minor improvement to the echo test
> Output extension handling and echo test improvement

- libraries/mbed/common/us_ticker_api.c
- libraries/mbed/hal/us_ticker_api.h
Handled condition when head is NULL. Do you think it is acceptable to return 0 in this condition?
> Issue #934: Handled condition when head is NULL.

- workspace_tools/export/README.md
- workspace_tools/export/coide.py
- workspace_tools/export/coide_nucleo_f070rb.coproj.tmpl
- Added exporter
- Updated workspace_tools/export/README.md
> [NUCLEO_F070RB] exporter for CoIDE

- workspace_tools/export/iar.py
Fixed the script to handle linux paths, added documentation and pylint messages.
> Fixed Issue #996 IAR EXPORT

- workspace_tools/tests.py
adding RTOS tests for NUCLEO_F303RE in singletest.py
> [NUCLEO_F303RE] RTOS singletest

- libraries/mbed/targets/hal/TARGET_NXP/TARGET_LPC15XX/serial_api.c
This is a pull request for this issue: https://github.com/mbedmicro/mbed/issues/1011
> Enable LPC1549 usart when configuring it

- libraries/mbed/targets/hal/TARGET_NXP/TARGET_LPC15XX/serial_api.c
Pull request fixing issue: https://github.com/mbedmicro/mbed/issues/1013
> Properly disable LPC1549 usart interrupt

- libraries/mbed/targets/cmsis/TARGET_Maxim/TARGET_MAX32610/TOOLCHAIN_ARM_STD/startup_MAX32610.s
Fixing comments in startup file for ARM compiler.
> [MAXWSNENV] Fixing comments in startup file for ARM compiler.

- libraries/mbed/targets/hal/TARGET_Maxim/TARGET_MAX32610/analogin_api.c
- libraries/mbed/targets/hal/TARGET_Maxim/TARGET_MAX32610/analogout_api.c
Adjusting sampling of analogin and shifting of values for analogout.
> [MAXWSNENV] Adjusting hal analog.

- libraries/mbed/targets/cmsis/TARGET_NXP/TARGET_LPC176X/TOOLCHAIN_GCC_ARM/TARGET_XBED_LPC1768/XBED_LPC1768.ld
- libraries/mbed/targets/hal/TARGET_NXP/TARGET_LPC176X/TARGET_XBED_LPC1768/PinNames.h
- libraries/mbed/targets/hal/TARGET_NXP/TARGET_LPC176X/TARGET_XBED_LPC1768/device.h
- libraries/mbed/targets/hal/TARGET_NXP/TARGET_LPC176X/TARGET_XBED_LPC1768/reserved_pins.h
- workspace_tools/targets.py
Hi~
This is a porting for [xbed-LPC1768] (http://developer.mbed.org/platforms/xbed-LPC1768/) of [SmeshLink] (http://developer.mbed.org/teams/Smeshlink/).
Details of this platform can be found here: http://developer.mbed.org/platforms/xbed-LPC1768/
We have read the SDK porting page and been informed to commit our porting code here.
Thanks for your time.
> Added target XBED_LPC1768

- libraries/USBDevice/USBDevice/USBHAL_STM32F4.cpp
Add call to suspendStateChanged at USB reset/suspend for STM32F4 target
> add suspend callback to STM32F4 USBDevice HAL

- libraries/USBDevice/USBDevice/USBEndpoints_Maxim.h
- libraries/mbed/targets/hal/TARGET_Maxim/TARGET_MAX32600/TARGET_MAX32600MBED/PinNames.h
- libraries/mbed/targets/hal/TARGET_Maxim/TARGET_MAX32600/spi_api.c
- libraries/mbed/targets/hal/TARGET_Maxim/TARGET_MAX32610/spi_api.c
1) Updated pin definitions for version 2 boards
2) Added USBDevice definitions to eliminate build errors for USB projects.
3) Corrected SPI frequency assertion.
> Maxim Integrated platform updates

- libraries/mbed/api/Ticker.h
- libraries/mbed/api/Timer.h
- libraries/mbed/api/TimerEvent.h
- libraries/mbed/common/Timer.cpp
Fixes #1124
Unnecessary protection in this case
> Timer/Ticker - fix constness of the data argument/member

- libraries/tests/rtos/mbed/basic/main.cpp
- libraries/tests/rtos/mbed/mail/main.cpp
- libraries/tests/rtos/mbed/mutex/main.cpp
- libraries/tests/rtos/mbed/queue/main.cpp
- libraries/tests/rtos/mbed/semaphore/main.cpp
To make them passed with GCC and ARM compilers
> [NUCLEO_L053R8] enhance RTOS main test

- workspace_tools/host_tests/mbedrpc.py
Consolidated code with some generic inheritance. Changed the way rpc interfaces are called. Eliminated platform specific pin names.
> Updated to mbedrpc python script

- libraries/mbed/api/CircularBuffer.h
@adamgreen Thanks for noticing :cake:
> CircularBuffer - volatile full flag + indexes

- workspace_tools/test_api.py
This fixes a runtime error when testing fails due to a build failure
> Fix error when testing fails due to build failure

- libraries/mbed/targets/hal/TARGET_Freescale/TARGET_KLXX/TARGET_KL25Z/serial_api.c
- libraries/mbed/targets/hal/TARGET_Freescale/TARGET_KLXX/TARGET_KL46Z/serial_api.c
- libraries/mbed/targets/hal/TARGET_Freescale/TARGET_KPSDK_MCUS/serial_api.c
This pull request fixes how the Freescale boards K64F,K22F,KL25Z, and KL46Z handle having one of the serial pins set to NC.
> Fix handling of Serial NC pins in K64F,K22F,KL25Z, and KL46Z

- libraries/net/lwip/lwip-sys/arch/sys_arch.c
- libraries/rtos/rtos/Thread.cpp
- libraries/rtos/rtx/TARGET_CORTEX_A/RTX_CM_lib.h
- libraries/rtos/rtx/TARGET_CORTEX_A/RTX_Conf_CA.c
- libraries/rtos/rtx/TARGET_CORTEX_A/cmsis_os.h
- libraries/rtos/rtx/TARGET_CORTEX_A/rt_CMSIS.c
Hi,
we modified the OS stack acquisition method to align the A Series with the M Series.
Regards,
Yamanaka
> [RZ_A1H]Modify the OS track acquisition method

- libraries/mbed/targets/cmsis/TARGET_Maxim/TARGET_MAX32600/system_max32600.c
- libraries/mbed/targets/cmsis/TARGET_Maxim/TARGET_MAX32610/system_max32610.c
Added ring oscillator trimming procedure for Maxim Integrated targets.
> [MAXWSNENV,MAX32600MBED] Added ring oscillator trimming procedure.

- libraries/mbed/targets/hal/TARGET_RENESAS/TARGET_RZ_A1H/PeripheralNames.h
- libraries/mbed/targets/hal/TARGET_RENESAS/TARGET_RZ_A1H/can_api.c
- libraries/mbed/targets/hal/TARGET_RENESAS/TARGET_RZ_A1H/device.h
- libraries/mbed/targets/hal/TARGET_RENESAS/TARGET_RZ_A1H/objects.h
- workspace_tools/tests.py
Hi,
We added CAN driver.
Regards,
Yamanaka
> [RZ_A1H]Add CAN driver.

- workspace_tools/build_release.py
mps2 added to build_release.py as requested
> mps2 added to build_release.py

- libraries/mbed/targets/hal/TARGET_RENESAS/TARGET_RZ_A1H/PeripheralNames.h
- libraries/mbed/targets/hal/TARGET_RENESAS/TARGET_RZ_A1H/pwmout_api.c
Hi,
we modified PWM driver for period improvement.
In PWM, modify the range that can be taken of the period.
Regards,
Yamanaka
> [RZ_A1H]Modify PWM driver for period improvement

- workspace_tools/export/README.md
- workspace_tools/export/gcc_arm_teensy3_1.tmpl
- workspace_tools/export/gccarm.py
Add support for GCC_ARM export for TEENSY3_1
> Yoonghm-Export-gcc_arm_teensy3 1

- libraries/mbed/targets/cmsis/TARGET_WIZNET/TARGET_W7500x/TARGET_WIZwiki_W7500/W7500x.h
- libraries/mbed/targets/cmsis/TARGET_WIZNET/TARGET_W7500x/W7500x_conf.h
- libraries/mbed/targets/cmsis/TARGET_WIZNET/TARGET_W7500x/W7500x_dualtimer.c
- libraries/mbed/targets/cmsis/TARGET_WIZNET/TARGET_W7500x/W7500x_dualtimer.h
- libraries/mbed/targets/hal/TARGET_WIZNET/TARGET_W7500x/us_ticker.c
I change ticker used by two PWM timer to used by one PWM timer and one dualtimer.
So I added dualtimer driver and header and I bug fix define in W7500x.h.
> Change us_ticker

- workspace_tools/targets.py
Change DELTA_DFCM_NNN40 ram size to 32KB config
> Change DELTA_DFCM_NNN40 ram size to 32KB config

- requirements.txt
'pip install -r requirements.txt' will install all the needed python packages
> Added requirements.txt file

- libraries/net/eth/lwip-eth/arch/TARGET_RZ_A1H/rza1_emac.c
- libraries/rpc/Arguments.cpp
- libraries/rpc/parse_pins.cpp
Hi,
We added RZ_A1H in RPC.
And we modified a problem that sometimes fail to "pbuf_alloc" function in Ethernet.
Regards,
Yamanaka
> [RZ_A1H]Add RZ_A1H in RPC. Modify communication problem of Ethernet.

- libraries/mbed/targets/hal/TARGET_NXP/TARGET_LPC11U6X/serial_api.c
- It was not possible to set/clear Rx and/or Tx interrupts of Uart1-4 peripherals because of wrong register usage for clearing irq and wrong register usage in the different irq handlers
- Pins P0_14,P0_13 can also be configured for use with Uart1
> [LPC11U68] fix Uart1-4 irq handling bugs, add Pins P0_14,P0_13 for use with Uart1

- libraries/mbed/targets/hal/TARGET_RENESAS/TARGET_RZ_A1H/pinmap.c
- libraries/mbed/targets/hal/TARGET_RENESAS/TARGET_RZ_A1H/pwmout_api.c
Hi,
We modified the register setting method in the pin setting configuration.
Regards,
Yamanaka
> Modify the register setting method in the pin setting configuration.

- libraries/mbed/targets/cmsis/TARGET_ARM_SSG/TARGET_MPS2_BEID/CMSDK_BEID.h
- libraries/mbed/targets/cmsis/TARGET_ARM_SSG/TARGET_MPS2_BEID/SMM_MPS2.h
- libraries/mbed/targets/cmsis/TARGET_ARM_SSG/TARGET_MPS2_BEID/TOOLCHAIN_ARM_STD/MPS2.sct
- libraries/mbed/targets/cmsis/TARGET_ARM_SSG/TARGET_MPS2_BEID/TOOLCHAIN_ARM_STD/startup_MPS2.s
- libraries/mbed/targets/cmsis/TARGET_ARM_SSG/TARGET_MPS2_BEID/cmsis.h
- libraries/mbed/targets/cmsis/TARGET_ARM_SSG/TARGET_MPS2_BEID/cmsis_nvic.c
- libraries/mbed/targets/cmsis/TARGET_ARM_SSG/TARGET_MPS2_BEID/cmsis_nvic.h
- libraries/mbed/targets/cmsis/TARGET_ARM_SSG/TARGET_MPS2_BEID/peripherallink.h
- libraries/mbed/targets/cmsis/TARGET_ARM_SSG/TARGET_MPS2_BEID/system_CMSDK_BEID.c
- libraries/mbed/targets/cmsis/TARGET_ARM_SSG/TARGET_MPS2_BEID/system_CMSDK_BEID.h
- workspace_tools/host_tests/host_tests_plugins/__init__.py
- workspace_tools/host_tests/host_tests_plugins/module_copy_mps2.py
- workspace_tools/host_tests/host_tests_plugins/module_reset_mps2.py
- workspace_tools/targets.py
new sdk for MPS2, target is IoT Subsystem for Cortex-M Platform
> changes for adding IoT Subsystem for Cortex-M target

- libraries/mbed/targets/hal/TARGET_NXP/TARGET_LPC11XX_11CXX/serial_api.c
Yes, you are right but i suggest this way to be similar like another platforms exp 1768.
> fix -Wmaybe-uninitialized warning.

- libraries/mbed/targets/hal/TARGET_Freescale/TARGET_K20XX/TARGET_TEENSY3_1/PinNames.h
> Update Teensy3.1 PinNames.h

- libraries/mbed/targets/cmsis/TARGET_Freescale/TARGET_K20XX/TARGET_TEENSY3_1/MK20DX256.h
Added missing PIT timer chain defines.
> Teensy3.1 Update MK20DX256.h

- libraries/mbed/targets/hal/TARGET_STM/TARGET_STM32F0/analogout_api.c
- libraries/mbed/targets/hal/TARGET_STM/TARGET_STM32F3/analogout_api.c
- libraries/mbed/targets/hal/TARGET_STM/TARGET_STM32F4/analogout_api.c
- libraries/mbed/targets/hal/TARGET_STM/TARGET_STM32F7/analogout_api.c
- libraries/mbed/targets/hal/TARGET_STM/TARGET_STM32L0/analogout_api.c
- libraries/mbed/targets/hal/TARGET_STM/TARGET_STM32L1/analogout_api.c
- libraries/mbed/targets/hal/TARGET_STM/TARGET_STM32L4/analogout_api.c
> [STM32xx] Fix analog_out issue with 12 to 16bits conversion

- libraries/net/eth/lwip-eth/arch/TARGET_RZ_A1H/rza1_emac.c
Hi,
We added the measures so as not to miss the received data In EthernetInterface.
Regards,
Yamanaka
> Modify to not missed the received data in EthernetInterface

- libraries/mbed/targets/hal/TARGET_NORDIC/TARGET_MCU_NRF51822/pwmout_api.c
Please Refer to this issue:
deleting PwmOut object crashes application https://github.com/mbedmicro/mbed/issues/1409
> Free hardware resource in pwmout_free()

- workspace_tools/export/coide_nucleo_f042k6.coproj.tmpl
adding missing coide project template
> [NUCLEO_F042K6] coide exporter

- workspace_tools/tests.py
Removes WFI test from automated tests
> Removed WFI test from automated tests

- workspace_tools/upload_results.py
This PR allows the upload script to handle build reports as well as test reports
> Fix upload results script

- workspace_tools/upload_results.py
This fixes an issue where skipped builds were being uploaded to the test database.
> Handle Skipped Builds in Upload Script

- libraries/mbed/api/Stream.h
- libraries/mbed/common/Stream.cpp
Makes logging a little easier and more consistent in implementation. Also fewer local buffers.
```
void trace(const char* format, ...)
{
va_list argp;
va_start(argp, format);
vprintf(format, argp);
va_end(argp);
}
```
> Enhance stream

- workspace_tools/build_api.py
- workspace_tools/test_api.py
- workspace_tools/upload_results.py
Adding vendor property to reports so the testing database can handle new platforms as they get added
> Adding vendor property to reports

- workspace_tools/upload_results.py
Adds 'Release' to the build types
> Adding 'Release' build type

- libraries/rtos/rtx/TARGET_CORTEX_M/RTX_Conf_CM.c
> Update Teensy3_1 OS_CLOCK

- libraries/mbed/targets/hal/TARGET_STM/TARGET_STM32F7/rtc_api.c
the logical test for RTC_ISR_INITS was wronlgy reported from other STMfamilies.
MBED_16 test works with this modification.
> [STM32F7 family] fix issue with RTC init

- libraries/mbed/api/mbed.h
- libraries/mbed/targets/hal/TARGET_STM/TARGET_STM32L4/rtc_api.c
> Dev l476rg rtc

- workspace_tools/build_release.py
Hi,
We modified the following to support the export function to the IAR.
- In tools files, we added the IAR tool chain to release build.
Regards,
Yamanaka
> Bug fix to support the export function to IAR.

- requirements.txt
- setup.py
> Adding requests to requirements

- libraries/mbed/targets/hal/TARGET_RENESAS/TARGET_RZ_A1H/device.h
Hi.
We modified the value of "DEVICE_STDIO_MESSAGES" and "DEVICE_ERROR_PATTERN" in order to output the error message.
Regards,
Yamanaka
> Modify macro value of device error in device.h

- libraries/mbed/targets/cmsis/TARGET_STM/TARGET_STM32L1/TARGET_MOTE_L152RC/stm32l1xx_hal_conf.h
- libraries/mbed/targets/cmsis/TARGET_STM/TARGET_STM32L1/TARGET_NUCLEO_L152RE/stm32l1xx_hal_conf.h
- libraries/mbed/targets/cmsis/TARGET_STM/TARGET_STM32L1/TARGET_NZ32_SC151/stm32l1xx_hal_conf.h
- libraries/mbed/targets/hal/TARGET_STM/TARGET_STM32L1/TARGET_MOTE_L152RC/device.h
- libraries/mbed/targets/hal/TARGET_STM/TARGET_STM32L1/TARGET_NUCLEO_L152RE/device.h
- libraries/mbed/targets/hal/TARGET_STM/TARGET_STM32L1/TARGET_NZ32_SC151/device.h
- libraries/mbed/targets/hal/TARGET_STM/TARGET_STM32L1/rtc_api.c
Add define to choose between LSI or LSE
modify RTC api accordingly
> [XXX_L15XXX] enhance RTC files

- libraries/mbed/targets/cmsis/TARGET_STM/TARGET_STM32F0/stm32f0xx_hal_conf.h
- libraries/mbed/targets/cmsis/TARGET_STM/TARGET_STM32L1/TARGET_MOTE_L152RC/stm32l1xx_hal_conf.h
- libraries/mbed/targets/cmsis/TARGET_STM/TARGET_STM32L1/TARGET_NUCLEO_L152RE/stm32l1xx_hal_conf.h
- libraries/mbed/targets/cmsis/TARGET_STM/TARGET_STM32L1/TARGET_NZ32_SC151/stm32l1xx_hal_conf.h
- libraries/mbed/targets/hal/TARGET_STM/TARGET_STM32F0/TARGET_DISCO_F051R8/device.h
- libraries/mbed/targets/hal/TARGET_STM/TARGET_STM32F0/TARGET_NUCLEO_F030R8/device.h
- libraries/mbed/targets/hal/TARGET_STM/TARGET_STM32F0/TARGET_NUCLEO_F031K6/device.h
- libraries/mbed/targets/hal/TARGET_STM/TARGET_STM32F0/TARGET_NUCLEO_F042K6/device.h
- libraries/mbed/targets/hal/TARGET_STM/TARGET_STM32F0/TARGET_NUCLEO_F070RB/device.h
- libraries/mbed/targets/hal/TARGET_STM/TARGET_STM32F0/TARGET_NUCLEO_F072RB/device.h
- libraries/mbed/targets/hal/TARGET_STM/TARGET_STM32F0/TARGET_NUCLEO_F091RC/device.h
- libraries/mbed/targets/hal/TARGET_STM/TARGET_STM32F0/rtc_api.c
- libraries/mbed/targets/hal/TARGET_STM/TARGET_STM32L1/TARGET_MOTE_L152RC/device.h
- libraries/mbed/targets/hal/TARGET_STM/TARGET_STM32L1/TARGET_NUCLEO_L152RE/device.h
- libraries/mbed/targets/hal/TARGET_STM/TARGET_STM32L1/TARGET_NZ32_SC151/device.h
- libraries/mbed/targets/hal/TARGET_STM/TARGET_STM32L1/rtc_api.c
add define to select between LSI or LSE
modify RTC API accordingly
> [XXX_F0XX] enhance RTC API

- libraries/mbed/targets/cmsis/TARGET_STM/TARGET_STM32F3/stm32f3xx_hal_rcc.h
- libraries/mbed/targets/cmsis/TARGET_STM/TARGET_STM32L1/TARGET_MOTE_L152RC/stm32l1xx_hal_conf.h
- libraries/mbed/targets/cmsis/TARGET_STM/TARGET_STM32L1/TARGET_NUCLEO_L152RE/stm32l1xx_hal_conf.h
- libraries/mbed/targets/cmsis/TARGET_STM/TARGET_STM32L1/TARGET_NZ32_SC151/stm32l1xx_hal_conf.h
- libraries/mbed/targets/hal/TARGET_STM/TARGET_STM32F3/TARGET_DISCO_F303VC/device.h
- libraries/mbed/targets/hal/TARGET_STM/TARGET_STM32F3/TARGET_DISCO_F334C8/device.h
- libraries/mbed/targets/hal/TARGET_STM/TARGET_STM32F3/TARGET_NUCLEO_F302R8/device.h
- libraries/mbed/targets/hal/TARGET_STM/TARGET_STM32F3/TARGET_NUCLEO_F303K8/device.h
- libraries/mbed/targets/hal/TARGET_STM/TARGET_STM32F3/TARGET_NUCLEO_F303RE/device.h
- libraries/mbed/targets/hal/TARGET_STM/TARGET_STM32F3/TARGET_NUCLEO_F334R8/device.h
- libraries/mbed/targets/hal/TARGET_STM/TARGET_STM32F3/rtc_api.c
- libraries/mbed/targets/hal/TARGET_STM/TARGET_STM32L1/TARGET_MOTE_L152RC/device.h
- libraries/mbed/targets/hal/TARGET_STM/TARGET_STM32L1/TARGET_NUCLEO_L152RE/device.h
- libraries/mbed/targets/hal/TARGET_STM/TARGET_STM32L1/TARGET_NZ32_SC151/device.h
- libraries/mbed/targets/hal/TARGET_STM/TARGET_STM32L1/rtc_api.c
add define to select LSI or LSE and modify rtc api accordingly
> [XXX_F3XX] enhance RTC API

- libraries/mbed/targets/cmsis/TARGET_STM/TARGET_STM32F1/stm32f1xx_hal_conf.h
- libraries/mbed/targets/hal/TARGET_STM/TARGET_STM32F1/TARGET_DISCO_F100RB/device.h
- libraries/mbed/targets/hal/TARGET_STM/TARGET_STM32F1/TARGET_NUCLEO_F103RB/device.h
- libraries/mbed/targets/hal/TARGET_STM/TARGET_STM32F1/rtc_api.c
Add a define to select between LSE or LSI
> [XXX_F10XRB] enhance RTC API

- workspace_tools/build_release.py
Add EFM32 Pearl Gecko to the library builds in anticipation of release.
> Add EFM32 Pearl Gecko to the library builds in anticipation of release

- workspace_tools/build_release.py
- workspace_tools/export/gcc_arm_nrf51_microbit.tmpl
- workspace_tools/export/gccarm.py
> Add GCC exporter for micro:bit

- libraries/mbed/targets/cmsis/TARGET_STM/TARGET_STM32F0/TARGET_NUCLEO_F042K6/stm32f042x6.h
- libraries/mbed/targets/cmsis/TARGET_STM/TARGET_STM32F0/TARGET_NUCLEO_F072RB/stm32f072xb.h
- libraries/mbed/targets/cmsis/TARGET_STM/TARGET_STM32F0/TARGET_NUCLEO_F091RC/stm32f091xc.h
- libraries/mbed/targets/hal/TARGET_STM/TARGET_STM32F0/PeripheralPins.h
- libraries/mbed/targets/hal/TARGET_STM/TARGET_STM32F0/TARGET_NUCLEO_F042K6/PeripheralNames.h
- libraries/mbed/targets/hal/TARGET_STM/TARGET_STM32F0/TARGET_NUCLEO_F042K6/PeripheralPins.c
- libraries/mbed/targets/hal/TARGET_STM/TARGET_STM32F0/TARGET_NUCLEO_F042K6/device.h
- libraries/mbed/targets/hal/TARGET_STM/TARGET_STM32F0/TARGET_NUCLEO_F042K6/objects.h
- libraries/mbed/targets/hal/TARGET_STM/TARGET_STM32F0/TARGET_NUCLEO_F072RB/PeripheralNames.h
- libraries/mbed/targets/hal/TARGET_STM/TARGET_STM32F0/TARGET_NUCLEO_F072RB/PeripheralPins.c
- libraries/mbed/targets/hal/TARGET_STM/TARGET_STM32F0/TARGET_NUCLEO_F072RB/device.h
- libraries/mbed/targets/hal/TARGET_STM/TARGET_STM32F0/TARGET_NUCLEO_F072RB/objects.h
- libraries/mbed/targets/hal/TARGET_STM/TARGET_STM32F0/TARGET_NUCLEO_F091RC/PeripheralNames.h
- libraries/mbed/targets/hal/TARGET_STM/TARGET_STM32F0/TARGET_NUCLEO_F091RC/PeripheralPins.c
- libraries/mbed/targets/hal/TARGET_STM/TARGET_STM32F0/TARGET_NUCLEO_F091RC/device.h
- libraries/mbed/targets/hal/TARGET_STM/TARGET_STM32F0/TARGET_NUCLEO_F091RC/objects.h
- libraries/mbed/targets/hal/TARGET_STM/TARGET_STM32F0/can_api.c
- libraries/tests/mbed/can/main.cpp
- libraries/tests/mbed/can_interrupt/main.cpp
- libraries/tests/mbed/can_loopback/main.cpp
- workspace_tools/tests.py
CAN development for STM32F0xx family
> [STM32F0xx] Can development for STM32F0xx family

- .travis.yml
- travis/install_dependencies.sh
travis.yaml file - add before install, print versions of tools we use
Let's try to make travis working again..
> Travis - remove install sh script

- .gitignore
Since 9bd2b4e commit, .build is the build directory
> Update .gitignore for build directory

- hal/targets/hal/TARGET_Freescale/TARGET_KSDK2_MCUS/TARGET_K64F/TARGET_FRDM/mbed_overrides.c
I haven't tested this on the hw yet.
@sg-
> k64f - mac address - fix warnings - get UID via K64F SIM macros

- hal/targets.json
Also, remove UVISOR_SUPPORTED from the other targets.
> Add a K64F target with uVisor enabled

- tools/export/gcc_arm_hrm1017.tmpl
changed merging softdevice from s110 to s130
> [HRM1017] Update exporting template

- README.md
> Add missing EFM32 Pearl Gecko to README.

- tools/toolchains/arm.py
In case libpath is with spaces, in my case it happened :)
> armcc - fix libpath - windows spaces

- tools/toolchains/__init__.py
> Removed duplicate feature declarations

- tools/build_api.py
- tools/toolchains/__init__.py
Also improve compile speed by not re-scanning the source locations
> Fixed features not being included

- hal/targets/hal/TARGET_STM/TARGET_STM32F0/serial_api.c
Continuation of fixing Issue #1705
> [STM32F0] Add USART force/release Reset at Init phase

- hal/hal/spi_api.h
> spi hal - specify default bit order

- hal/targets.json
- hal/targets/hal/TARGET_Freescale/TARGET_KSDK2_MCUS/TARGET_K64F/storage_driver.c
> Revert "cfstore flash-journal integration with config_system (Resubmitted)"

- .travis.yml
This adds the config system's test scripts to the Travis CI script.
> Adding config tests to travis script

- hal/targets/hal/TARGET_STM/TARGET_STM32F4/TARGET_MTS_MDOT_F411RE/PinNames.h
Add leds 2-4 for mDot platform
> [MTS_MDOT_F411RE] add LED2-LED4 definitions

- hal/targets/hal/TARGET_STM/TARGET_STM32F0/spi_api.c
- hal/targets/hal/TARGET_STM/TARGET_STM32F1/spi_api.c
- hal/targets/hal/TARGET_STM/TARGET_STM32F3/spi_api.c
- hal/targets/hal/TARGET_STM/TARGET_STM32F4/spi_api.c
- hal/targets/hal/TARGET_STM/TARGET_STM32F7/spi_api.c
- hal/targets/hal/TARGET_STM/TARGET_STM32L0/spi_api.c
- hal/targets/hal/TARGET_STM/TARGET_STM32L1/spi_api.c
- hal/targets/hal/TARGET_STM/TARGET_STM32L4/spi_api.c
Rework for SPI clock selection.
Tested ok locally on all ST boards..
> Spi freq selection

- tools/toolchains/__init__.py
> Fix a bug that caused the gcc_arm exporter to fail

- hal/targets.json
this allows standard Arduino pins usage on DISCO F746ZG
> [NUCLEO_F746ZG] Add Arduino Form Factor property

- hal/targets/cmsis/TARGET_STM/TARGET_STM32F3/TARGET_DISCO_F303VC/stm32f3xx.h
With this fix DISCO_F303VC build is passed.
> [DISCO_F303VC] : fix build issue

- tools/build_api.py
- tools/test.py
- tools/test_api.py
This PR aims to make custom targets (defined in mbed_app.json) usable with tests.
> Fix tests with config

- hal/targets.json
Tracking issue: https://github.com/mbedmicro/mbed/issues/2108
> Targets - LPC23678 ARM fails to build, remove from supported toolchains

- hal/targets.json
- requirements.txt
- setup.py
> [target.json - progen] changing a wrong config

- tools/project.py
> [Project.py] Make -i and -m optional

- rtos/rtx/TARGET_CORTEX_M/RTX_Conf_CM.c
> The core clock in run mode is 80MHz for K22F

- tools/export/iar.py
- tools/export/uvision4.py
- tools/export/uvision5.py
This saves ~329 calls
@screamerbg @sg- @sarahmarshy @theotherjimmy
> Export - define ProGenDef outside of the loop

- features/FEATURE_CLIENT/mbed-client/module.json
- features/FEATURE_CLIENT/mbed-client/source/m2mnsdlinterface.cpp
This commit includes
- Fixed mbed-client Tag mbed-os-5.0-rc2
> Fix for https://github.com/ARMmbed/mbed-os-example-client/issues/44

- requirements.txt
- setup.py
Fixes #2275. Reference:
http://pybuilder.github.io/documentation/external_plugins.html#.V5m-hfmANBc
> Requirements - fix progen def name - use dashes

- DOXYGEN_FRONTPAGE.md
I don't have a good text for it yet - I just want to make sure it works properly on docs.mbed
> Creating the doxygen front page

- libraries/tests/rtos/mbed/semaphore/main.cpp
- rtos/rtos/Thread.cpp
- rtos/rtos/Thread.h
Fix join and make Thread class thread safe
> Thread safe thread class

- features/net/FEATURE_IPV6/sal-stack-nanostack/TOOLCHAIN_ARM/TARGET_CORTEX_A/TARGET_A9/error_nanostack.c
- features/net/FEATURE_IPV6/sal-stack-nanostack/TOOLCHAIN_ARM/TARGET_CORTEX_M/TARGET_M0/error_nanostack.c
- features/net/FEATURE_IPV6/sal-stack-nanostack/TOOLCHAIN_ARM/TARGET_CORTEX_M/TARGET_M0P/error_nanostack.c
- features/net/FEATURE_IPV6/sal-stack-nanostack/TOOLCHAIN_ARM/TARGET_CORTEX_M/TARGET_M7/error_nanostack.c
- features/net/FEATURE_IPV6/sal-stack-nanostack/TOOLCHAIN_GCC/TARGET_CORTEX_A/TARGET_A9/error_nanostack.c
- features/net/FEATURE_IPV6/sal-stack-nanostack/TOOLCHAIN_GCC/TARGET_CORTEX_M/TARGET_M0/error_nanostack.c
- features/net/FEATURE_IPV6/sal-stack-nanostack/TOOLCHAIN_GCC/TARGET_CORTEX_M/TARGET_M0P/error_nanostack.c
- features/net/FEATURE_IPV6/sal-stack-nanostack/TOOLCHAIN_GCC/TARGET_CORTEX_M/TARGET_M7/error_nanostack.c
- features/net/FEATURE_IPV6/sal-stack-nanostack/TOOLCHAIN_IAR/TARGET_CORTEX_A/TARGET_A9/error_nanostack.c
- features/net/FEATURE_IPV6/sal-stack-nanostack/TOOLCHAIN_IAR/TARGET_CORTEX_M/TARGET_M0/error_nanostack.c
- features/net/FEATURE_IPV6/sal-stack-nanostack/TOOLCHAIN_IAR/TARGET_CORTEX_M/TARGET_M0P/error_nanostack.c
- features/net/FEATURE_IPV6/sal-stack-nanostack/TOOLCHAIN_IAR/TARGET_CORTEX_M/TARGET_M7/error_nanostack.c
* Error message for unsupported platforms
> Adding error message for unsupported platforms

- hal/targets/hal/TARGET_Freescale/TARGET_KSDK2_MCUS/TARGET_K64F/TARGET_HEXIWEAR/PeripheralPins.c
> K64 HEXIWEAR: Add CTS and RTS pin defines

- tools/export/exporters.py
- tools/export/iar.py
> Removed preinclude config from asm flags

- DOXYGEN_FRONTPAGE.md
> Very minimal text

- features/FEATURE_UVISOR/README.md
- features/FEATURE_UVISOR/includes/uvisor/api/inc/rpc.h
This PR introduces no functional change.
* Updated README (using importer script).
* Updated RPC header file (no API change).
@0xc0170 @sg-
> Update the uVisor README and RPC header

- hal/targets/hal/TARGET_STM/TARGET_STM32F1/serial_api.c
Catch HAL init error like STM32F4 api.
> STM32F1 serial_api initialize failure message

- tools/config.py
> Fix macros being the exact same when generating mbed_config.h

- tools/build_everything.py
alternate implementation of #2285
> Move find_tests to where it's has arguments

- hal/targets/hal/TARGET_Freescale/TARGET_KSDK2_MCUS/TARGET_MCU_K64F/TARGET_HEXIWEAR/PeripheralPins.c
> HEXIWEAR: Update I2C pin mapping

- features/FEATURE_CLIENT/mbed-client-classic/source/m2mconnectionhandlerpimpl.cpp
This commit fixes issue
https://github.com/ARMmbed/mbed-os/issues/2569
This commit has to go in coming mbed-os release else the build is broken.
> Fix failing compilation for mbed-os

- hal/targets.json
[mbed Greentea Results Report.pdf](https://github.com/ARMmbed/mbed-os/files/432513/mbed.Greentea.Results.Report.pdf)
> [NUCLEO_F207ZG] Add MBED5 capability

- hal/targets/hal/TARGET_Maxim/TARGET_MAX32600/serial_api.c
- hal/targets/hal/TARGET_Maxim/TARGET_MAX32610/serial_api.c
- hal/targets/hal/TARGET_Maxim/TARGET_MAX32620/serial_api.c
Fixed some issues preventing mbed tests from passing on Maxim targets.
> [MAX326xx] Removed echoing of characters and carriage return.

- hal/targets.json
- hal/targets/hal/TARGET_NORDIC/TARGET_NRF5/TARGET_MCU_NRF52832/TARGET_DELTA_DFBM_NQ620/PinNames.h
- hal/targets/hal/TARGET_NORDIC/TARGET_NRF5/TARGET_MCU_NRF52832/TARGET_DELTA_DFBM_NQ620/device.h
We manege to finish the porting of DELTA_DFBM_NQ620 based on the existing platform NRF52_DK. 
Greentea result is shown as below
mbedgt: test suite results: 45 OK 
mbedgt: test case results: 147 OK
Please kindly review this PR.
> DELTA_DFBM_NQ620 platform porting

- features/net/FEATURE_IPV4/lwip-interface/EthernetInterface.cpp
- features/net/FEATURE_IPV4/lwip-interface/LWIPIPStack.cpp
- features/net/FEATURE_IPV4/lwip-interface/emac_lwip.c
- features/net/FEATURE_IPV4/lwip-interface/emac_stack_lwip.cpp
- features/net/FEATURE_IPV4/lwip-interface/eth_arch.h
- features/net/FEATURE_IPV4/lwip-interface/lwip_stack.c
- features/net/network-socket/IPStackInterface.h
- features/net/network-socket/WiFiInterface.h
- features/net/network-socket/emac_stack_mem.h
- hal/hal/emac_api.h
> HAL: Add Emac interface

- hal/targets/hal/TARGET_Freescale/TARGET_KSDK2_MCUS/TARGET_K66F/drivers/fsl_sdhc.c
- hal/targets/hal/TARGET_Freescale/TARGET_KSDK2_MCUS/TARGET_K66F/drivers/fsl_sdhc.h
- hal/targets/hal/TARGET_Freescale/TARGET_KSDK2_MCUS/TARGET_MCU_K64F/drivers/fsl_sdhc.c
- hal/targets/hal/TARGET_Freescale/TARGET_KSDK2_MCUS/TARGET_MCU_K64F/drivers/fsl_sdhc.h
1. Use function pointer for interrupt handler, this should reduce the code-size
for applications that do not use this driver
2. Fix the wait for initialization of the SD card
3. Fix SDHC driver support for non-word aligned accesses
4. Remove some redundant code & assert function calls.
5. Updated various comments
**READY
- Tests
* Code size prior to commit:
```
Elf2Bin: dev_null
+-----------+-------+-------+-------+
| Module    | .text | .data |  .bss |
+-----------+-------+-------+-------+
| Misc      | 37371 |   292 | 10036 |
| Subtotals | 37371 |   292 | 10036 |
+-----------+-------+-------+-------+
Allocated Heap: unknown
Allocated Stack: unknown
Total Static RAM memory (data + bss): 10328 bytes
Total RAM memory (data + bss + heap + stack): 10328 bytes
Total Flash memory (text + data …
```
> Update KSDK SDHC driver for K64F & K66F

- hal/targets.json
- hal/targets/cmsis/TARGET_STM/TARGET_STM32L1/TARGET_XDOT_L151CC/TOOLCHAIN_IAR/startup_stm32l152xc.S
- hal/targets/cmsis/TARGET_STM/TARGET_STM32L1/TARGET_XDOT_L151CC/TOOLCHAIN_IAR/stm32l152xc.icf
Add MultiTech xDot to mbed 5 releases.
**READY**
> include MultiTech xDot in mbed 5 releases

- tools/project_api.py
Needed for compatibility with mbed-cli
> exporters - Add .bld directories to exported project

- tools/profiles/debug.json
There was a bug in json syntax in debug.json profile file
READY
NO
cc: @0xc0170
> Fix json syntax in debug.json profile file

- platform/CallChain.cpp
Notes:
Fix call chain add_front assignment, where _chain should point to the new element.
READY
NO
NO
No change to build environment, but should be back-ported if accepted.
bug fix, will not be triggered unless add_fronts is called.
> callchain - fix add_front assignment

- tools/memap.py
add a --max-depth option that only affects the table output
**READY**
> Allow max-depth specification in memap

- events/Event.h
- events/EventQueue.h
This was a missed part of pr https://github.com/ARMmbed/mbed-os/pull/2898
Related to https://github.com/ARMmbed/oob-mbed-os-example-ble/issues/5#issuecomment-253177750
Fixes some other iar-related issues some other users have seen.
cc @pan-, @bridadan, @sarahmarshy
> callback - Fixed missing workaround for IAR issue with type information

- features/storage/FEATURE_STORAGE/TESTS/cfstore/create/create.cpp
- features/storage/FEATURE_STORAGE/cfstore/source/configuration_store.c
Fix problems with config store so tests pass on all compilers.
> Fix config store

- tools/export/makefile/Makefile.tmpl
This allows you to run make on windows with bash/sh in your path or from git bash!
**READY**
> [Exporters - Make-based] Quote the shell call in mkdir and rmdir

- tools/test/examples/examples_lib.py
Fix an incorrect indentation for changing directory after each target/ide combo within a project.
> [Export build-test] Directory traversal error

- tools/export/makefile/__init__.py
> [Exporters - Make-based] Force make exporter to search PATH for compilers

- features/frameworks/greentea-client/source/greentea_metrics.cpp
fix to https://github.com/ARMmbed/mbed-os/issues/3296
> added static specifer in green_metrics.cpp

- docs/exporters.md
Adds instructions for updating index.json with new target information.
> [Exporter docs] index.json update instructions

- features/FEATURE_LWIP/lwip-interface/lwip-eth/arch/TARGET_Freescale/hardware_init_MK66F18.c
- features/FEATURE_LWIP/lwip-interface/lwip-eth/arch/TARGET_Freescale/k64f_emac.c
- targets/targets.json
Enable LWIP feature on FRDM K666F
**READY
Ran the LWIP tests
> K66F: Enable LWIP feature

- targets/TARGET_Maxim/TARGET_MAX32620/serial_api.c
Fixing the serial readable function. Function used to check an interrupt flag, but now checks a status register. 
READY
NO
> [MAX32620] Fixing serial readable function.

- features/FEATURE_LORAWAN/LoRaWANInterface.h
- features/FEATURE_LORAWAN/todo.md
Notes:
* Feature branch for further developing a LoRaWAN interface for mbed OS
* See list of items needed to be worked on
API outline and list of ToDo
**READY**
> Adding draft API for LoRaWANInterface

- targets/TARGET_STM/TARGET_STM32F4/TARGET_NUCLEO_F412ZG/objects.h
- targets/targets.json
Add support of TRNG peripheral (True Random Generator).
READY
NO
> NUCLEO_F412ZG - Add support of TRNG peripheral

- README.md
"Latest" is back to life so we can link to it now
> Linking to latest

- README.md
Add note that mbed-cli is needed for building mbed OS; update link to the docs to point to the latest version.
**READY**
CC: @0xc0170 @theotherjimmy
> README: Build info; Docs version updated

- rtos/rtx2/TARGET_CORTEX_M/TARGET_RTOS_M4_M7/TOOLCHAIN_ARM/irq_cm4f.s
- rtos/rtx2/TARGET_CORTEX_M/TARGET_RTOS_M4_M7/TOOLCHAIN_IAR/irq_cm4f.s
- targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_K66F/device/cmsis_nvic.h
- targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_K82F/device/cmsis_nvic.h
- targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KL27Z/device/cmsis_nvic.h
- targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KL43Z/device/cmsis_nvic.h
- targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KL82Z/device/cmsis_nvic.h
- targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KW24D/device/cmsis_nvic.h
- targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KW41Z/device/cmsis_nvic.h
- targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K22F/TARGET_MCU_K22F512/device/cmsis_nvic.h
- targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K64F/device/cmsis_nvic.h
- targets/TARGET_Silicon_Labs/mbed_rtx.h
> cmsis5: Feature branch testing

- tools/export/__init__.py
- tools/export/vscode/__init__.py
- tools/export/vscode/launch.tmpl
- tools/export/vscode/tasks.tmpl
- tools/export/vscode/vscode.md
Supersedes #3568 
Some stuff that still would need to be fixed to make this work properly:
Microsoft/vscode-cpptools#374 - for Intellisense
Microsoft/vscode-cpptools#442 - for finding the pyOCD tools without relying on full paths
**READY**
> Feature vscode

- tools/export/iar/iar_definitions.json
https://developer.mbed.org/questions/76907/Export-NUCLEO-F207ZG-project-to-IAR/
Add the IAR project file information for the NUCLEO_F207ZG.
@sg- 
@theotherjimmy
> Add IAR export support for NUCLEO_F207ZG

- targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K64F/device/TOOLCHAIN_ARM_STD/MK64FN1M0xxx12.sct
- targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K64F/device/TOOLCHAIN_GCC_ARM/MK64FN1M0xxx12.ld
- targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K64F/device/TOOLCHAIN_IAR/MK64FN1M0xxx12.icf
- targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F429xI/device/TOOLCHAIN_ARM_MICRO/stm32f429xx.sct
- targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F429xI/device/TOOLCHAIN_ARM_STD/stm32f429xx.sct
- targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F429xI/device/TOOLCHAIN_GCC_ARM/STM32F429xI.ld
- targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F429xI/device/TOOLCHAIN_IAR/stm32f429xx_flash.icf
- targets/TARGET_STM/TARGET_STM32F4/TARGET_UBLOX_EVK_ODIN_W2/device/TOOLCHAIN_ARM_MICRO/stm32f439xx.sct
- targets/TARGET_STM/TARGET_STM32F4/TARGET_UBLOX_EVK_ODIN_W2/device/TOOLCHAIN_ARM_STD/stm32f439xx.sct
- targets/TARGET_STM/TARGET_STM32F4/TARGET_UBLOX_EVK_ODIN_W2/device/TOOLCHAIN_GCC_ARM/STM32F439ZI.ld
- targets/TARGET_STM/TARGET_STM32F4/TARGET_UBLOX_EVK_ODIN_W2/device/TOOLCHAIN_IAR/stm32f439xx_flash.icf
Update the linker scripts of the Odin, stm32f429, and K64F to support a bootloader.
> Linker script updates

- tools/project_api.py
The zipping function of the exporters would unconditionally add all
files scanned by scan resources to a zip, including all of the files
associated with each feature. This would conflict with
`build_api.scan_resources` adding all of the files to the resources
object that correspond to the enabled features. To resolve this
difference in behavior, I made the zipping function oblivious to
features and had the upper level function, which has access to the
target configuration, do the proper merging.
**READY**
> Remove duplicate files in zipped exports

- rtos/mbed_boot.c
- targets/TARGET_NORDIC/TARGET_NRF5/TARGET_MCU_NRF51822_UNIFIED/device/cmsis_nvic.c
- targets/TARGET_NORDIC/TARGET_NRF5/TARGET_MCU_NRF52832/device/cmsis_nvic.c
- targets/TARGET_NORDIC/TARGET_NRF5/TARGET_MCU_NRF52832/device/cmsis_nvic.h
- targets/TARGET_NORDIC/TARGET_NRF5/us_ticker.c
- targets/targets.json
resolution of:
https://github.com/ARMmbed/mbed-os/issues/3690
**READY**
> [NRF5] cmsis5/rtx2 nrf5x: RTX SysTick API update and "private" set/get vector reinstatement.

- rtos/Thread.cpp
- rtos/Thread.h
Fix thread wrapper signal_wait function
@SeppoTakalo
> cmsis5: Fix thread wrapper signal_wait function

- targets/TARGET_Silicon_Labs/TARGET_EFM32/spi_api.c
> [Silicon Labs] Bugfix for EFM32 SPI HAL

- features/unsupported/USBDevice/USBAudio/USBAudio.cpp
- features/unsupported/USBDevice/USBAudio/USBAudio.h
Add a parameter to add or remove one sample from  iso packet length  sent  to USB host.
READY
> USBAudio: writesync with 1 sample jitter capability.

- targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KW41Z/trng_api.c
Fix comments in KW41Z hardware entropy driver
> Fix comments in KW41Z hardware entropy driver

- cmsis/TARGET_CORTEX_A/TOOLCHAIN_ARM/cmsis_armclang.h
- cmsis/TARGET_CORTEX_M/TOOLCHAIN_ARM/cmsis_armclang.h
- cmsis/core_ca.h
- rtos/rtx2/TARGET_CORTEX_M/rtx_kernel.c
- rtos/rtx2/TARGET_CORTEX_M/rtx_lib.c
- rtos/rtx2/TARGET_CORTEX_M/rtx_msgqueue.c
- rtos/rtx2/TARGET_CORTEX_M/rtx_os.h
- rtos/rtx2/TARGET_CORTEX_M/rtx_system.c
- rtos/rtx2/TARGET_CORTEX_M/rtx_timer.c
This PR is for testing purposes only, please ignore.
> CMSIS5: Testing change

- features/unsupported/USBDevice/USBDevice/USBHAL_Maxim.cpp
Adding support for new platforms into official USB library
> Maxim USB library update

- targets/TARGET_STM/TARGET_STM32L1/TARGET_MOTE_L152RC/objects.h
Fix MOTE_L152RC GPIO Write
This pull request supercedes pr #4378 
Run Simple LED Blinky program
> #4354 Fix MOTE_L152RC GPIO Write

- tools/toolchains/__init__.py
There was a bug in the dependency handling that broke incremental compiles.
This PR fixes that bug.
> Fix a bug in dependency handling

- tools/config/__init__.py
> Fix typo in tools code to handle bootloader builds

- targets/TARGET_STM/TARGET_STM32L0/common_objects.h
- targets/TARGET_STM/TARGET_STM32L0/flash_api.c
- targets/targets.json
Rebase against master for: #4135
> STM32 L0: Add Flash API support - Rebase

- targets/TARGET_NORDIC/TARGET_NRF5/trng_api.c
- targets/targets.json
Moving PR #4056 to master.
CC: @andresag01 @yanesca @nvlsianpu
> NRF52840: TRNG support

- targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KW41Z/trng_api.c
- targets/targets.json
Moved PR #4050 to master.
CC @mmahadevan108
> Add TRNG support for KW41Z

- features/FEATURE_LWIP/lwip-interface/lwip-eth/arch/TARGET_Realtek/lwipopts_conf.h
Fix typo and cleanup coding style
READY
NO
#4438 
NONE
NONE
NONE
> lwip - fix typo and cleanup coding style

- targets/TARGET_Silicon_Labs/TARGET_EFM32/spi_api.c
Moving PR #4054 to master.
CC @akselsm
> Silicon Labs: Fix bug with SPI MISO and CS handling

- targets/TARGET_STM/TARGET_STM32L4/common_objects.h
- targets/TARGET_STM/TARGET_STM32L4/flash_api.c
- targets/targets.json
Moving PR #4058 to master.
CC: @adustm
> STM32L4 Flash support

- targets/TARGET_Silicon_Labs/TARGET_EFM32/common/objects.h
- targets/TARGET_Silicon_Labs/TARGET_EFM32/flash_api.c
- targets/targets.json
Moving PR #4037 to master
CC: @akselsm
> Silicon Labs: Add flash API support

- tools/config/__init__.py
Moving PR #4061 to master.
CC @theotherjimmy
> Improve error messages for bootloader build errors

- tools/utils.py
Before, print_large_string was replacing the last character in each buffer it 
printed with a " ". This patch fixes that bug.
**ready**
- /morph something
> Fix a bug in print_large_string

- rtos/rtx5/TARGET_CORTEX_M/rtx_mutex.c
> Rename runnig_thread to running_thread in rtx_mutex

- .github/issue_template.md
Notes:
* I have accepted the Contributor Agreement on Tue 25 Oct 2016
> Correct a typo in the github issue template

- features/FEATURE_LWIP/TESTS/mbedmicro-net/udp_echo_parallel/main.cpp
A message of "Failed to close socket" was always being printed, not
just when the socket failed to close. This patch fixes this in
addition to a simplifying the call to a thread safe printf.
**READY**
NO
> Fix bad test print and move locks for printf into macro.

- targets/TARGET_STM/TARGET_STM32L0/TARGET_DISCO_L053C8/PeripheralPins.c
- targets/TARGET_STM/TARGET_STM32L0/TARGET_NUCLEO_L011K4/PeripheralPins.c
- targets/TARGET_STM/TARGET_STM32L0/TARGET_NUCLEO_L031K6/PeripheralPins.c
- targets/TARGET_STM/TARGET_STM32L0/TARGET_NUCLEO_L053R8/PeripheralPins.c
- targets/TARGET_STM/TARGET_STM32L0/TARGET_NUCLEO_L073RZ/PeripheralPins.c
- targets/TARGET_STM/TARGET_STM32L0/analogin_api.c
Internal ADC pin are now out of PinMap_ADC array
This PR is following #4153 
READY
> STM32L0 : internal ADC channels

- targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L475xG/TARGET_DISCO_L475VG_IOT01A/PeripheralPins.c
Just adding more comments on the pins connected to other components present on the board.
**READY**
NO
> DISCO_L475VG_IOT01A: typo corrections in PeripheralPins.c

- tools/toolchains/__init__.py
Partially reverts 2ddf4b33cbfbee616a263c04cec6f15685ba0972
> Prevent double define in very old builds

- platform/ATCmdParser.h
Related to-- https://developer.mbed.org/questions/78439/the-new-class-ATCmdParserHow-to-make-an-/
I agree that this is unclear. 
@hasnainvirk
> Update ATCmdParser example code

- targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F437xG/TARGET_UBLOX_C030/system_clock.c
- targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F437xG/device/TOOLCHAIN_ARM_STD/stm32f437xx.sct
- targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F437xG/device/TOOLCHAIN_GCC_ARM/STM32F437xx.ld
- targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F437xG/device/TOOLCHAIN_IAR/stm32f437xx.icf
- targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F437xG/device/flash_api.c
- targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F437xG/device/flash_data.h
- targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F437xG/device/nvic_addr.h
- targets/targets.json
This Pull Request created to replace #4590 in order to work around a CI infrastructure issue.
> Add bootloader support for the UBLOX_C030 platforms.

- targets/TARGET_STM/hal_tick_16b.c
- targets/TARGET_STM/hal_tick_32b.c
- targets/TARGET_STM/us_ticker_16b.c
- targets/TARGET_STM/us_ticker_32b.c
> STM32: Align HAL & US tickers

- targets/targets.json
This PR resolves Issue #4876 as suggested in https://github.com/ARMmbed/mbed-os/issues/4876#issuecomment-322768591 by @jeromecoutant 
All tests PASS.
> bug fix: xdot clock config 

- features/FEATURE_COMMON_PAL/mbed-coap/CHANGELOG.md
- features/FEATURE_COMMON_PAL/mbed-coap/module.json
- features/FEATURE_COMMON_PAL/mbed-coap/source/sn_coap_builder.c
- features/FEATURE_COMMON_PAL/mbed-coap/source/sn_coap_header_check.c
- features/FEATURE_COMMON_PAL/mbed-coap/source/sn_coap_parser.c
- features/FEATURE_COMMON_PAL/mbed-coap/source/sn_coap_protocol.c
Fixes following error: 
IOTMAC-615 Node mDS registration failure during OTA transfer
**READY**
NO
https://github.com/ARMmbed/mbed-coap/pull/32
https://github.com/ARMmbed/mbed-coap/pull/33
> Update mbed-coap to version 4.0.10

- features/FEATURE_LWIP/TESTS/mbedmicro-net/tcp_hello_world/main.cpp
update server to  os.mbed.com 
**READY**
https://github.com/ARMmbed/mbed-os/issues/5121
> update server name to os.mbed.com

- tools/memap.py
Resolves #5048
Thanks @RonEld!
> Parse libraries with memap-arm

- tools/test/examples/examples.json
They are not part of the releases
cc @adbridge @pan-
> examples: remove eddystone ble examples

- targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_K66F/us_ticker.c
- targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_K82F/us_ticker.c
- targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KL27Z/us_ticker.c
- targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KL43Z/us_ticker.c
- targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KL82Z/us_ticker.c
- targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KW24D/us_ticker.c
- targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KW41Z/us_ticker.c
- targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K22F/us_ticker.c
- targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K24F/us_ticker.c
- targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K64F/us_ticker.c
Same as https://github.com/ARMmbed/mbed-os/pull/5316. restarting CI with a clean slate !
@mmahadevan108
> MCUXpresso: Fix issue of ticker interrupt incorrectly firing

- .github/pull_request_template.md
Copy edit file to match our style guide to fulfill old JIRA task.
> Copy edit pull_request_template.md

- tools/test/examples/examples_lib.py
In preparation to exporter tests, we would need the binaries from exporter build to test on actual hardware. 
**HOLD**
> Collect build artifacts, disable cleanup

- targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC546XX/TARGET_FF_LPC546XX/PeripheralNames.h
- targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC546XX/TARGET_FF_LPC546XX/PeripheralPins.c
- targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC546XX/TARGET_FF_LPC546XX/PinNames.h
- targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC546XX/TARGET_FF_LPC546XX/clock_config.c
- targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC546XX/TARGET_FF_LPC546XX/clock_config.h
- targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC546XX/TARGET_FF_LPC546XX/device.h
- targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC546XX/TARGET_FF_LPC546XX/mbed_overrides.c
- targets/targets.json
based on lpc546XX
board id: 8081
ready
> add new target L-Tek FF-LPC546XX

- targets/TARGET_NUVOTON/TARGET_M480/device/M480.h
- targets/TARGET_NUVOTON/TARGET_NANO100/device/Nano100Series.h
- targets/TARGET_NUVOTON/TARGET_NUC472/device/NUC472_442.h
Replaces #5498 as travis did not pick up the PR.
> [M487/NUC472/NANO130] fix TRUE/FALSE redefinition

- TESTS/mbedmicro-rtos-mbed/condition_variable/main.cpp
- rtos/ConditionVariable.cpp
- rtos/ConditionVariable.h
Fix the circular linked list handling in ConditionVariable and add a test to validate the linked list implementation.
> Fix and add test for ConditionVariable

- targets/targets.json
> STM32F407VG: Fix RTC

- platform/mbed_retarget.h
Found in sd-driver CI failure https://github.com/ARMmbed/sd-driver/pull/71
> Definition for stat was missing in header file

- hal/rtc_api.h
Add clarification as to what powerdown means for RTC.
> HAL: RTC: Add clarification to rtc_free doxygen

- drivers/QSPI.cpp
- drivers/QSPI.h
- hal/qspi_api.h
- targets/TARGET_NORDIC/TARGET_NRF5/TARGET_MCU_NRF52840/PeripheralNames.h
- targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK13/drivers_nrf/qspi/nrf_drv_qspi.c
- targets/TARGET_NORDIC/TARGET_NRF5/objects.h
- targets/TARGET_NORDIC/TARGET_NRF5/qspi_api.c
Notes:
This includes the QSPI driver implementation on top of Martin's QSPI HAL implementation and some modifications to the current QSPI HAL API to add command transfer operation and other changes.
> Feature QSPI: driver implementation

- drivers/QSPI.cpp
- drivers/QSPI.h
Please review, style changes only plus one bugfix regarding size NONE again
> Feature QSPI: driver arguments fix

- TESTS/network/wifi/get_interface.cpp
- TESTS/network/wifi/main.cpp
- TESTS/network/wifi/template_mbed_app.txt
- TESTS/network/wifi/wifi_connect.cpp
- TESTS/network/wifi/wifi_connect_disconnect_repeat.cpp
- TESTS/network/wifi/wifi_connect_params_channel.cpp
- TESTS/network/wifi/wifi_connect_params_channel_fail.cpp
- TESTS/network/wifi/wifi_connect_params_valid_secure.cpp
- TESTS/network/wifi/wifi_connect_params_valid_unsecure.cpp
- TESTS/network/wifi/wifi_connect_secure.cpp
- TESTS/network/wifi/wifi_connect_secure_fail.cpp
- TESTS/network/wifi/wifi_get_rssi.cpp
- TESTS/network/wifi/wifi_scan.cpp
Split Wi-Fi test for secure & unsecure tests
**READY**
NO
cc @ashok-rao, @MarceloSalazar, @screamerbg
> [TESTS/NETWORK] Split Wi-Fi test for secure & unsecure tests

- targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K24F/TARGET_MCU_K24F1M/device/TOOLCHAIN_ARM_STD/MK24FN1M0xxx12.sct
- targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K24F/TARGET_MCU_K24F1M/device/TOOLCHAIN_GCC_ARM/MK24FN1M0xxx12.ld
- targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K24F/TARGET_MCU_K24F1M/device/TOOLCHAIN_IAR/MK24FN1M0xxx12.icf
Changes in linker script for MK24F1 target to enable bootloader support.
**READY**
> Adding bootloader support to MK24F1 target

- targets/TARGET_NORDIC/TARGET_NRF5/TARGET_MCU_NRF52840/TARGET_NRF52840_DK/PinNames.h
- targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F469xI/TARGET_DISCO_F469NI/PinNames.h
Adding pins for QSPI flash for 2 targets
Note: feature-qspi was rebased today to the latest master
@maciejbocianski @SenRamakri Please review
> QSPI pins to PinNames for targets

- README.md
Trivial typo fix in the README.
READY
> Simple typo fix in the README.md

- hal/qspi_api.h
> QSPI HAL : docs fixes

- features/FEATURE_COMMON_PAL/mbed-coap/source/sn_coap_protocol.c
Every outgoing GET request must have a token.
READY
> Add token to every GET(block2) request

- features/FEATURE_BLE/ble/pal/SimpleEventQueue.h
Fix case of BLE inclusion in SimpleEventQueue.h
**READY**
NO
> BLE: Fix inclusion of BLE.h (case)

- targets/TARGET_NORDIC/TARGET_NRF5x/nordic_critical.c
Copy in new mbed HAL critical section implementation from `TARGET_NORDIC/TARGET_NRF5/nordic_critical.c`.
> [feature-nrf52] Update critical section for NRF5x

- mbed.h
- platform/ScopedLock.h
- rtos/Mutex.h
This PR is continuation of work done in #5420 related to scoped lock
It contains implementation of:
- mbed::ScopedLock
- rtos::ScopedMutexLock
**READY**
YES
#5420
> ScopedLock implementation

- TESTS/mbed_platform/Transaction/main.cpp
Provide Transaction class unit test.
**READY**
NO
> Add Transaction class unit test.

- targets/TARGET_STM/TARGET_STM32F3/TARGET_STM32F303xC/TARGET_DISCO_F303VC/PinNames.h
- targets/TARGET_STM/TARGET_STM32F3/TARGET_STM32F303xC/TARGET_DISCO_F303VC/system_clock.c
- targets/TARGET_STM/TARGET_STM32F3/TARGET_STM32F303xC/device/TOOLCHAIN_IAR/startup_stm32f303xc.S
- targets/TARGET_STM/TARGET_STM32F3/TARGET_STM32F303xC/device/TOOLCHAIN_IAR/stm32f303xc.icf
- targets/targets.json
3 commits:
- Defined STDIO pins were wrong
- add IAR files
- Align clock configuration with STM32 family
**READY**
OK
> DISCO_F303VC : STDIO pins correction and alignment with STM32 family

- targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F439xI/TARGET_MODULE_UBLOX_ODIN_W2/TARGET_MTB_UBLOX_ODIN_W2/PinNames.h
Fixed serial pins and a small typo for ODIN MTB.
**READY**
> Fix serial pins and a typo for ODIN MTB

- features/filesystem/bd/MBRBlockDevice.h
cc @deepikabhavnani, @JaniSuonpera 
from https://github.com/ARMmbed/mbed-os/issues/5999
> mbr: Add note about limitations

- rtos/Semaphore.cpp
> remove unused variable / resolve compiler warning

- events/mbed_shared_queues.h
cc @kjbracey-arm, @marcemmers
from https://github.com/ARMmbed/mbed-os/issues/6107
> equeue: Add note about using global event queues in irq

- tools/export/atmelstudio/__init__.py
- tools/export/cces/__init__.py
- tools/export/cdt/__init__.py
- tools/export/cmake/__init__.py
- tools/export/cmsis/__init__.py
- tools/export/coide/__init__.py
- tools/export/e2studio/__init__.py
- tools/export/embitz/__init__.py
- tools/export/exporters.py
- tools/export/gnuarmeclipse/__init__.py
- tools/export/iar/__init__.py
- tools/export/kds/__init__.py
- tools/export/makefile/__init__.py
- tools/export/mcuxpresso/__init__.py
- tools/export/nb/__init__.py
- tools/export/qtcreator/__init__.py
- tools/export/simplicity/__init__.py
- tools/export/sw4stm32/__init__.py
- tools/export/uvision/__init__.py
- tools/export/vscode/__init__.py
- tools/project.py
> Correct exporter clean behavior

- tools/utils.py
This should also resolve any missed ascii-ification bugs in python3
> Simplify json-to-dict utility

- features/nanostack/FEATURE_NANOSTACK/coap-service/source/coap_connection_handler.c
- features/nanostack/FEATURE_NANOSTACK/coap-service/source/coap_message_handler.c
- features/nanostack/FEATURE_NANOSTACK/coap-service/source/coap_service_api.c
- features/nanostack/FEATURE_NANOSTACK/coap-service/source/include/coap_connection_handler.h
- features/nanostack/FEATURE_NANOSTACK/coap-service/source/include/coap_message_handler.h
- features/nanostack/FEATURE_NANOSTACK/coap-service/test/coap-service/unittest/coap_message_handler/test_coap_message_handler.c
- features/nanostack/FEATURE_NANOSTACK/coap-service/test/coap-service/unittest/coap_service_api/coap_service_apitest.cpp
- features/nanostack/FEATURE_NANOSTACK/coap-service/test/coap-service/unittest/coap_service_api/test_coap_service_api.c
- features/nanostack/FEATURE_NANOSTACK/coap-service/test/coap-service/unittest/coap_service_api/test_coap_service_api.h
- features/nanostack/FEATURE_NANOSTACK/coap-service/test/coap-service/unittest/stub/coap_connection_handler_stub.c
- features/nanostack/FEATURE_NANOSTACK/coap-service/test/coap-service/unittest/stub/coap_connection_handler_stub.h
- features/nanostack/FEATURE_NANOSTACK/coap-service/test/coap-service/unittest/stub/coap_message_handler_stub.c
- features/nanostack/FEATURE_NANOSTACK/coap-service/test/coap-service/unittest/stub/coap_message_handler_stub.h
Fixed Thread Commissioning issue: https://github.com/ARMmbed/coap-service/issues/96 in CoAP service.
> Fixed Thread Commissioning issue in CoAP service

- TESTS/host_tests/pyusb_basic.py
- TESTS/usb_device/basic/USBTester.cpp
- TESTS/usb_device/basic/USBTester.h
- TESTS/usb_device/basic/main.cpp
- hal/mbed_usb_phy.cpp
- hal/usb_phy_api.h
- platform/USBPhy.h
- targets/TARGET_NXP/TARGET_LPC176X/usb/USBEndpoints_LPC17_LPC23.h
- targets/TARGET_NXP/TARGET_LPC176X/usb/USBHAL_LPC17.cpp
- targets/TARGET_NXP/TARGET_LPC176X/usb/USBPhyHw.h
- targets/targets.json
- tools/build_travis.py
- usb/device/USBDevice/EndpointResolver.cpp
- usb/device/USBDevice/EndpointResolver.h
- usb/device/USBDevice/USBDescriptor.h
- usb/device/USBDevice/USBDevice.cpp
- usb/device/USBDevice/USBDevice.h
- usb/device/USBDevice/USBDevice_Types.h
Initial USBDevice HAL specification changes
> USBDevice HAL specification

- tools/config/__init__.py
- tools/config/definitions.json
> Improve json schema and schema errors

- targets/TARGET_NORDIC/TARGET_NRF5x/PeripheralPinsDefault.c
- targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/TARGET_MCU_NRF52832/config/sdk_config.h
- targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/TARGET_MCU_NRF52840/config/sdk_config.h
- targets/TARGET_NORDIC/TARGET_NRF5x/objects.h
- targets/TARGET_NORDIC/TARGET_NRF5x/pinmap_ex.c
- targets/TARGET_NORDIC/TARGET_NRF5x/pinmap_ex.h
- targets/TARGET_NORDIC/TARGET_NRF5x/pwmout_api.c
Driver uses new API in SDK 14.2
> [feature-nrf528xx] NRF52 series PWM reimplementation for SDK 14.2

- targets/TARGET_Realtek/TARGET_AMEBA/RTWInterface.cpp
Add checks for empty strings
set_channel() not supported for STA mode wifi driver
> rtl8195am - improve credentials handling

- tools/utils.py
Decode option lists passed into our argparse custom up-casing type when they are not unicode.
> Convert option list to unicode

- tools/targets/REALTEK_RTL8195AM.py
> Correct Realtek post-build script to work in the online compiler

- targets/TARGET_Freescale/usb/USBPhy_Kinetis.cpp
- targets/TARGET_NXP/TARGET_LPC176X/usb/USBHAL_LPC17.cpp
- usb/device/USBDevice/USBDevice.cpp
Fully setup endpoint before enabling it in endpoint_add. This prevents undefined behavior due to the previous configuration.
> Fix USB problems

- features/netsocket/emac-drivers/README.md
Add driver porting docs to feature-emac branch.
Note that GitHub will show the formatted file if you click "View" in the diff.
> Add EMAC driver README.md with porting guide

- usb/device/targets/TARGET_Template/USBPhyHw.h
- usb/device/targets/TARGET_Template/USBPhy_template.cpp
Add a template for implementing a USBPhy.
> Add USBPhy template

- requirements.txt
Add pyusb to requirements so the greentea USB tests work.
> Add pyusb to requirements

- targets/TARGET_ONSEMI/TARGET_NCS36510/watchdog_api.c
- targets/targets.json
Watchdog implementation for NCS36510.
[ ] Fix  
[ ] Refactor  
[x] Feature  
> Added watchdog implementation for NCS36510.

- drivers/InterruptManager.h
- platform/ATCmdParser.h
- platform/CallChain.h
- platform/CriticalSectionLock.h
- platform/mbed_power_mgmt.h
Fix doxygen comments to reflect the deprecated APIs in Mbed-OS.
[X ] Fix  
[ ] Refactor  
[ ] Feature  
> Fix doxygen comments to reflect the deprecated functions

- TESTS/mbed_drivers/crc/main.cpp
- drivers/MbedCRC.cpp
- drivers/MbedCRC.h
Test cases to verify software CRC
[x] Fix
[ ] Refactor
[ ] New target
[ ] Feature
@0xc0170 @sg-
> Add test for MbedCRC.h

- targets/targets.json
It does not compile as there is no port for this board.
[x] Fix  
[ ] Refactor  
[ ] Feature  
> Remove MPS2 M1

- .github/pull_request_template.md
Use X to fill PR template and be more specific about only one PR type per pull request.
Not ticks, special characters
[X] Fix  
[ ] Refactor  
[ ] Feature  
> PR template: fix tick definition

- tools/export/iar/iar_definitions.json
Add iar export support for STM32L151CC
[ ] Fix  
[ ] Refactor  
[X] Feature  
> Add iar export support for STM32L151CC

- features/cellular/UNITTESTS/at/athandler/Makefile
- features/cellular/UNITTESTS/stubs/ATHandler_stub.cpp
- features/cellular/UNITTESTS/stubs/Kernel.cpp
Fixed ATHandler unit tests. No code changes.
Internal ref to defect: IOTCELL-777
[X] Fix  
[ ] Refactor  
[ ] Feature  
> Cellular: fixed athandler unit tests.

- targets/targets.json
Enable USBDEVICE for ARCH_PRO target
[ ] Fix  
[ ] Refactor  
[X] Feature  
> target: arch_pro enable USBDEVICE support

- TESTS/usb_device/basic/USBTester.cpp
- TESTS/usb_device/basic/USBTester.h
- usb/device/USBDevice/USBDevice.cpp
- usb/device/USBDevice/USBDevice.h
- usb/device/USBSerial/USBCDC.cpp
- usb/device/USBSerial/USBCDC.h
This PR adds support for 
- USB device deconfiguration
- USB device multi-configuration
Even though our high level classes don't use this functionality yet,
it's good to have it just for test purpose
[ ] Fix  
[ ] Refactor  
[X] Feature  
> USBDevice multi-configuration/deconfiguration support

- targets/targets.json
Dummy PR Testing feature-hal-spec-ticker after rebase
> Testing feature-hal-spec-ticker after rebase

- usb/device/USBDevice/USBDevice.cpp
Fix value returned from `USBDevice::endpoint_add/USBDevice::read_start` functions
[X] Fix  
[ ] Refactor  
[ ] Feature  
> USBDevice: endpoint_add/read_start functions return value fix

- .github/pull_request_template.md
Looks like the URL changed where #workflow became workflow.html. Cherry picked the previous commit from @sg- (removing change to checkboxes).
[X] Fix
[ ] Refactor
[ ] New target
[ ] Feature
> Update URL that points at a blank page.

- drivers/SAI.cpp
- hal/mbed_sai_api.c
- hal/sai_api.h
- targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/api/sai_api.c
- targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F429xI/TARGET_NUCLEO_F429ZI/PinNames.h
- targets/TARGET_STM/TARGET_STM32F4/sai_api.c
- targets/TARGET_STM/TARGET_STM32F4/stm_i2s_driver.c
- targets/TARGET_STM/TARGET_STM32F4/stm_sai_api.h
- targets/TARGET_STM/TARGET_STM32F4/stm_sai_driver.c
This fixes @0xc0170 review & make this feature-branch pass the tests provider by #6596.
It follows #6136 .
[ ] Fix
[x] Refactor
[ ] New target
[ ] Feature
> Feature hal spec sai fix testability
